### PR TITLE
[WIP] update node to v8.2.1, add termux module

### PR DESCRIPTION
**Pull request by devsnek**
This PR is aimed to update the nodejs package to node 8.2.1 and add a `termux` module to interact with the termux packages from termux:api and other things.

this is a continuation of #1080 

commentary and help is welcome

### CODE REVIEW

**Comment by devsnek** [comment]
@fornwall do all these patches matching against ancient versions of node still need to be applied?

**Comment by its-pointless** [comment]
Thanks for doing this i was going to try and fix this up but im not someone who uses nodejs ...
Anyways the tmpdir stuff might of been useful before since we cant' use /tmp on android. But the issue is if its affected by $TMPDIR or $TMP shell variables, if it is its probably not heeded anymore since we should be setting those things ourselves but keeping them there for simply avoiding potential bugs in the future is probably sensible.

**Comment by its-pointless** [comment]
Also iv got test builds on my repo if anyone wants to test...
Also
cp $TERMUX_PKG_BUILDER_DIR/termux.js ./lib/termux.js
Is the proper way to do it..

**Comment by devsnek** [comment]
@its-pointless thank you, perhaps you can help me out here :)

**Comment by its-pointless** [comment]
https://github.com/its-pointless/termux-packages/ minor edits to what you are doing.

**Comment by its-pointless** [comment]
Iv added the stuff needed to get arm working... 
i have no idea how a x86-64 build would react to that set up though.

**Comment by devsnek** [comment]
I don't have any i686 or x86-64 gear, but this built arm for me, so i'll merge it in and we'll see if anyone can do a quick build for the aforementioned architectures

**Comment by its-pointless** [comment]
i tried and it dies...
this approach will not work if using x86 targets.

**Comment by devsnek** [comment]
@its-pointless i just noticed `[ $TERMUX_ARCH = "arm" ] || [ $TERMUX_ARCH = "arm" ];`
is this intentional? 😄

**Comment by its-pointless** [comment]
probabbly not. 
Any way i got it compiling on x86_64 and figured out a way so the build gcc doesn't get bad flags from cross compile stuff....

**Comment by its-pointless** [comment]
ok the whole thing should work fine now.

**Comment by devsnek** [comment]
Thanks I'll attempt to test it later tonight and if it passes I'll merge it in

**Comment by its-pointless** [comment]
Using this technique we can probably remove the sudo hack to build on arm

**Comment by fornwall** [comment]
A `nodejs-current` package is now available at version 8.2.1 (you can re-open a new PR:s for the remaining changes here).

**Comment by devsnek** [comment]
rip ok

**Pull request closed without merging**
