### PR TITLE
indent

### PR DESCRIPTION
**Pull request by its-pointless**
#2184

### CODE REVIEW

**Comment by flipflop97** [comment]
Seems to depend on the package texi2html which is missing in Termux repos too.

**Comment by its-pointless** [comment]
needs to install texi2html on build host so its in docker image. Should be functional on device if you want to test i will make packages and put in my repo.

**Comment by flipflop97** [comment]
Oh my bad, I thought it was a runtime dependency. I'll wait until it appears in the repo.

**Comment by fornwall** [comment]
Thanks - the package is now available for installation!

**Pull request merged**
