### PR TITLE
xwayland: Bump to 22.1.8

### PR DESCRIPTION
**Pull request by xtkoba**

### CODE REVIEW

**Comment by jp311** [comment]
This update causes termux-x11 to fail to boot properly.

**Comment by jp311** [comment]
This update causes termux-x11 to fail to boot properly.

**Comment by twaik** [comment]
Maybe it is my fault. What message do you have?

**Comment by twaik** [comment]
Update termux-x11 to latest version and check again, it should be fixed.

**Comment by twaik** [comment]
It is definitely my fault. I had no full `xdg-wm-base` support. I thought I fixed this a month ago.

**Pull request merged**
