### PR TITLE
Add package aircrack-ng

### PR DESCRIPTION
**Pull request by Auxilus**

### CODE REVIEW

**Comment by fornwall** [comment]
As i understand it aircrack-ng does not work on Android, so it would be no point in packaging it.

Or does it work?

**Comment by Auxilus** [comment]
I was able to crack some passwords using sample capture `.cap and .pcap` files,

**Comment by Auxilus** [comment]
screenshot_20171015-083500

**Comment by Auxilus** [comment]
screenshot_20171015-083508

**Comment by xeffyr** [comment]
Aircrack tools works on Android. I'm able to use it with USB WiFi module.

**Comment by Auxilus** [comment]
@xeffyr `airmon-ng` shoud also work in termux right ?

I used an app called Intercepter-NG [Intercepter-ng](http://sniff.su/) which appears to make use of airmon-ng or `wireshark`  (rooted dev is required)

**Comment by xeffyr** [comment]
@Auxilus I have rewrited airmon-ng so it will work on Android

**Comment by Auxilus** [comment]
@xeffyr should I just replace original airmon-ng with yours?

**Comment by xeffyr** [comment]
You can, but this script uses **wireless-tools** (iwconfig). Also airodump-ng depends on it.

**Comment by Auxilus** [comment]
@xeffyr how did you packaged iwconfig? I have PR for iw open but seems like it doesn't include iwconfig

**Comment by Auxilus** [comment]
@fornwall I'm opening PR on termux-root-packages with aircrack-ng as it needs root

**Comment by Auxilus** [comment]
closing in favor of https://github.com/termux/termux-root-packages/pull/3

**Pull request closed without merging**
