### PR TITLE
add(main): new package logo-ls

### LINKED ISSUE #11178: [Package]: logo-ls
### Package description

modern ls command with beautiful Icons and Git Integrations . Written in Golang

### Home page URL

https://github.com/Yash-Handa/logo-ls

### Source code URL

https://github.com/Yash-Handa/logo-ls

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by T-Dynamos**
Closes #11178

### CODE REVIEW

**Comment by T-Dynamos** [comment]
> Screenshot_20220913-222334_1
> 
> [#11178 (comment)](https://github.com/termux/termux-packages/issues/11178#issuecomment-1177303633)
> 
> doesn't seem to solve this.

IMG_20220913_200133

I use font from termux-styling addon

**Comment by 2096779623** [comment]
> I use font from termux-styling addon

How to remind the user to change the font so as not to affect the display effect ?

**Comment by T-Dynamos** [comment]
> > I use font from termux-styling addon
> 
> How to remind the user to change the font so as not to affect the display effect ?

Maybe just telling the user in postinstall script? 

Like this?
```bash
termux_step_create_debscripts() {                   
        cat <<- POSTINST_EOF > ./postinst           
        #!$TERMUX_PREFIX/bin/sh         
        echo "Please use font from termux-styling addon"
        POSTINST_EOF
}

```

**Comment by 2096779623** [comment]
> Like this?
> 
> ```shell
> termux_step_create_debscripts() {                   
>         cat <<- POSTINST_EOF > ./postinst           
>         #!$TERMUX_PREFIX/bin/sh         
>         echo "Please use font from termux-styling addon"
>         POSTINST_EOF
> }
> ```

Just tell them what needs to be changed in addition to the termux-styling plugin installed.

**Comment by remo7777** [comment]
##Before
IMG_20241020_233426

[New fork](https://github.com/utfeight/logo-ls-modernized.git) <---😘😘
##After
IMG_20241020_233820

**Comment by twaik** [comment]
@remo7777 if you think we should replace project with its fork you should open appropriate package request.

**Comment by TomJo2000** [comment]
> @remo7777 if you think we should replace project with its fork you should open appropriate package request.

See: https://github.com/termux/termux-packages/issues/11178#issuecomment-2425159424

**Pull request merged**
