### PR TITLE
Split artifact name using arch (arm, arm64...)

### PR DESCRIPTION
**Pull request by MedzikUser**
This will make some artifacts (so you can only download 1 deb)

### CODE REVIEW

**Comment by MedzikUser** [comment]
...

**Comment by MedzikUser** [comment]
ss

**Review by buttaface — APPROVED** [review]
I like this change, but would it require other changes when unpacking the artifacts in our scripts?

**Comment by MedzikUser** [comment]
> I like this change, but would it require other changes when unpacking the artifacts in our scripts?

Rather it does not require changes in scripts, files after downloading have the same file names, the only change is that the upload is split

**Comment by MedzikUser** [comment]
No other changes should be required now. I know the code is repetitive but I had no other idea xD

**Comment by buttaface** [comment]
You can test this pull on the CI by adding a temporary commit to bump some small package's version, commenting out the line that disables package uploads for pull requests, then manually deleting the actual uploads, ie get rid of everything after the `tar xf` block.

**Pull request merged**
