### PR TITLE
fix rust

### PR DESCRIPTION
**Pull request by its-pointless**
test rustc first before commiting.

### CODE REVIEW

**Comment by roalyr** [comment]
Is everything working now? Rustc, cargo, clippy, rustfmt? Can I safely update?

**Comment by Grimler91** [comment]
Seem to still be problems on at least x86_64, based on this reddit post: https://www.reddit.com/r/termux/comments/imbr7g/no_binaries_in_rust_14601_package_on_x86_64/

**Comment by d3ck** [comment]
Still be problems for aarch64 android too

**Comment by roalyr** [comment]
aarch64 seems to work fine and all binaries are in there.

**Comment by stonecharioteer** [comment]
Is this problem solved?

I get: `error: no overrides or default configuration set` when running anything from `rustc --version` to `cargo init`.

**Pull request merged**
