### PR TITLE
use /data/data/com.termux/cache as TMPDIR

### PR DESCRIPTION
**Pull request by xeffyr**
A possible solution to #1772.

### CODE REVIEW

**Comment by shawnl** [comment]
LGTM

**Comment by vishalbiswas** [comment]
I think this should be done in the Android app.

**Comment by Quasic** [comment]
I've manually made the link to try. It's working, so far, without issue...

**Comment by xeffyr** [comment]
@vishalbiswas I done this for Android app, see https://github.com/termux/termux-app/pull/478.

**Comment by SamSanuch** [comment]
@xeffyr 
_We can build ndk for termux but I need someone help because I don't have any friends who can help I have also email you please check: blush:

**Comment by xeffyr** [comment]
After some time of testing, I have found that using application's cache directory as TMPDIR is not useful.
```
/data/data/com.termux/cache ➤ ls -l
total 32
-rw------- 1 u0_a73 u0_a73 16512 Jan 19 17:03 63892f6c81e1ccc8cacdf855d6488c1a38521baf.megatools.cache
drwx------ 2 u0_a73 u0_a73  4096 Jan 18 00:48 hsperfdata_u0_a73
drwx------ 2 u0_a73 u0_a73  4096 Jan 18 00:17 pulse-6aNuj9slFMb1
srw------- 1 u0_a73 u0_a73     0 Jan 19 16:32 ssh-agent
drwx------ 2 u0_a73 u0_a73  4096 Jan 18 00:35 tmux-10073
/data/data/com.termux/cache ➤ du -hs .
40K	.
```
As you can see, the content of my tmpdir stuff takes about 40 KB of space. Of course, some users could have a several megabytes in the TMPDIR, but this should not be a problem.

I'm closing this pull request for now.

**Pull request closed without merging**
