### PR TITLE
bitcoin: Downgrade to version 22.0

### PR DESCRIPTION
**Pull request by xtkoba**
DEBs for version 23.0 have never been released so no need to bump epoch.

### CODE REVIEW

**Comment by buttaface** [comment]
Why not upgrade?

**Comment by xtkoba** [comment]
Due to build issue.

**Comment by buttaface** [comment]
I thought the auto-updater won't update unless the build succeeds?

**Comment by buttaface** [comment]
> It checks build, but only for one arch that is not blacklisted

No, that's fine. I didn't realize we were checking one arch and another one failed, makes sense.

**Pull request merged**
