### PR TITLE
nodejs: update to v17.7.1

### PR DESCRIPTION
**Pull request by thunder-coding**

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
So nodejs takes more priority than board papers, huh!

**Comment by thunder-coding** [comment]
> So nodejs takes more priority than board papers, huh!

Well it was just a single line version and checksum change. The patch files were rebased using a script. So it took less than 15 minutes!

**Comment by agnostic-apollo** [comment]
Cool cool, just messing around. Do whatever*

**Comment by agnostic-apollo** [comment]
What!!! Bio is love! 😱

But yeah, not for everybody. You prefer IT I assume. Why did you choose bio if you hate it, weren't there other combos available?

**Review by xtkoba — CHANGES_REQUESTED** [review]
Fix typo in the subject.

**Comment by agnostic-apollo** [comment]
> Science isn't divided into the 3 streams untill 11th here. So I have to study biology too

I see, that sucks. Well, happy thunder-doctoring! ;)

**Pull request merged**
