### PR TITLE
setup-ubuntu.sh: adding python3.12 package

### PR DESCRIPTION
**Pull request by Maxython**

### CODE REVIEW

**Comment by fornwall** [comment]
I wonder if we can go for #21421 instead - updating to Ubuntu 24.04 where Python 3.12 is the system Python? Would appreciate any help testing it (see the PR description)!

**Comment by TomJo2000** [comment]
Moving the build container to Ubuntu 24.04 would seem preferable,
though will understandably require additional testing.

**Comment by Maxython** [comment]
> I wonder if we can go for https://github.com/termux/termux-packages/pull/21421 instead - updating to Ubuntu 24.04 where Python 3.12 is the system Python?

Oops, I didn't notice that. I opened this PR (without knowing that there is already a PR with the same direction) to update [python-glibc](https://github.com/termux-pacman/glibc-packages/pull/287).

**Comment by fornwall** [comment]
> Oops, I didn't notice that. I opened this PR (without knowing that there is already a PR with the same direction) to update https://github.com/termux-pacman/glibc-packages/pull/287.

👍. If #21421 gets delayed because of some issues we can merge this before to avoid being blocked.

But let's aim at getting #21421 done first if possible - can you help out with testing it to check if it works ok with glibc-packages? Let me know if I can help in any way!

**Comment by Maxython** [comment]
Closing due to better alternative PR (#21421)

**Pull request closed without merging**
