### PR TITLE
rust 1.44.0: res_init

### PR DESCRIPTION
**Pull request by r4v3n6101**
I tried to resolve 5387 making a new patch based on @coolreader18 PR.
It didn't throw an error in local build as in previous PR.

### CODE REVIEW

**Comment by r4v3n6101** [comment]
Seems that patch had applied before libc crate  downloaded. So it needs workaround. I'm thinking that script should copy libc then patch it and build with it

**Comment by coolreader18** [comment]
Maybe it'd be best to just patch the one spot in libstd where `res_init` is actually used, rather than try to edit a dependency. It's weird, though, cause the src tarball comes with all the vendored dependencies, so it really shouldn't need to then download them.

**Comment by r4v3n6101** [comment]
I don't really know how process is working, but I can see "downloaded libc" in logs. So that the cause I'm thinking suck way

**Comment by dram** [comment]
Seems that the patch file is broken.

**Comment by r4v3n6101** [comment]
I don't pull changes to local repo, so it crashed.
For now, I'm thinking that #5387 should be only one repo for this issue, so I'll closed this one.

**Pull request closed without merging**
