### PR TITLE
	modified:   scripts/setup-archlinux.sh

### PR DESCRIPTION
**Pull request by SDRausty**

### CODE REVIEW

**Comment by xeffyr** [comment]
Can you tell why this patch is necessary ? `sudo` under root is no-op and can be kept to simplify the script.

Or you need this in TermuxArch ?

**Comment by SDRausty** [comment]
> why this patch 

eases installing on device, incl. proot

> in TermuxArch ?

` setup-archlinux.sh ` runs smoother with this patch in TermuxArch

**Comment by SDRausty** [comment]
I attempted to **build `ncurses5-compat-libs` and `makedepend` on device** in Arch Linux in Termux PRoot , but `makepkg` will not build on aarch64 in for some reason.  

Reference https://github.com/termux/termux-packages/wiki for build on device.

**Comment by SDRausty** [comment]
@xeffyr are lines [#48 & #49](https://github.com/termux/termux-packages/blob/master/scripts/setup-archlinux.sh#L48&#L49) necessary?

> sudo mkdir -p /data/data/com.termux/files/usr
sudo chown -R $(whoami) /data

If these are not needed, then [#L47 diff](https://github.com/termux/termux-packages/pull/4753/files#diff-d45a214183a220e7a5f8b55f4e1491b6R47) is unnecessary too. 

> [ "$(id -u)" -ne 0 ] && sudo mkdir -p /data/data/com.termux/files/usr && sudo chown -R $(whoami) /data

**Comment by xeffyr** [comment]
All sudo-related changes are implemented now in https://github.com/termux/termux-packages/commit/0af821b51f68a714b7265359fb404bc10df3945d.

**Comment by xeffyr** [comment]
Also Termux packages can be built on device. See https://github.com/termux/termux-packages/wiki/Build-environment#termux.

On TermuxArch you won't be able to install/use Android NDK which is the most important thing for building packages. (that issue is not relevant for x86_64 users)

**Pull request closed without merging**
