### PR TITLE
bump(main/telegram-bot-api): 20241031

### PR DESCRIPTION
**Pull request by Sarisan**
Is this okay if I mark myself as a maintainer?

### CODE REVIEW

**Review by twaik — APPROVED** [review]
LGTM.

**Comment by twaik** [comment]
Probably we should write auto-update rule for it.
Since tdlib does not have releases or tags we shoyld pull its CMakeLists.txt and check if the version changed.

**Comment by Sarisan** [comment]
> Probably we should write auto-update rule for it. Since tdlib does not have releases or tags we should pull its CMakeLists.txt and check if the version changed.

Is there any example? I can't figure out how should it update SHA256 this way

**Comment by twaik** [comment]
> Is there any example

https://github.com/termux/termux-packages/blob/master/x11-packages/browsh/build.sh
https://github.com/termux/termux-packages/blob/master/packages/v2ray/build.sh
https://github.com/termux/termux-packages/blob/master/packages/tinygo/build.sh
https://github.com/termux/termux-packages/blob/master/packages/artalk/build.sh

**Pull request merged**
