### PR TITLE
dropbear: fix getpass()

### PR DESCRIPTION
**Pull request by xeffyr**
Fix for issue with TCSAFLUSH, like in https://github.com/termux/termux-packages/pull/2609

### CODE REVIEW

**Comment by tomty89** [comment]
Can we have getpass(3) as a library/package like we do for crypt(3)?

**Comment by xeffyr** [comment]
@tomty89 Yes, we can.

**Comment by xeffyr** [comment]
@tomty89 getpass() implementation as a separate library is ready: https://github.com/xeffyr/termux-packages/tree/add-libgetpass/packages/libgetpass, but it is still needed to make packages use it.

**Comment by tomty89** [comment]
It should probably be used like libandroid-support? You may want to check out my not-yet-merged PR before mimicking the way: #2499. Not sure if @fornwall has been having concern about it though.

**Comment by its-pointless** [comment]
I thought of doing it but instead of patching every package integrate it in headers so its just -DGETPASS=1 and add -landroid-getpass to ldflags or just leave it in header form...

**Comment by xeffyr** [comment]
@its-pointless Would it be acceptable to implement it as ndk-patch for unistd.h (without readline dependency of course) ?

**Comment by fornwall** [comment]
An inline implementation (without readline depdendency) in `unistd.h` would perhaps be nice?

**Comment by xeffyr** [comment]
@fornwall Yes, the standard location of getpass() is in unistd.h, so we can probably omit patches for including additional headers/libraries.

**Comment by xeffyr** [comment]
I did this in https://github.com/termux/termux-packages/pull/2611. Test this on `unrar` package - everything is ok.

**Comment by xeffyr** [comment]
I'm closing this in favor of https://github.com/termux/termux-packages/pull/2611.

**Comment by xeffyr** [comment]
Perhaps we can't put implementation of getpass() into header only as this require additional headers `stdio.h` and `termios.h` and may cause problems with compiling some software like libgnutls.

I guess it will be better to have only definition in `unistd.h` and implementation in package `libutil`.

**Pull request closed without merging**
