### PR TITLE
chore(main/mympd): correct mpd socket path

### PR DESCRIPTION
**Pull request by LaunchLee**
According to the default config(mpd.conf) in main/mpd:

* bind_to_address "@TERMUX_PREFIX@/var/run/mpd.socket"

So change the path "@TERMUX_PREFIX@/var/run/mpd/socket"
to "@TERMUX_PREFIX@/var/run/mpd.socket"

### CODE REVIEW

**Comment by Grimler91** [comment]
Please bump the revision of the package (i.e. add `TERMUX_PKG_REVISION=1` under `TERMUX_PKG_VERSION` line) and squash the commits

**Comment by LaunchLee** [comment]
@Grimler91 TERMUX_PKG_REVISION=1 has been added under TERMUX_PKG_VERSION line and the commits have been squashed.

**Comment by Grimler91** [comment]
> the commits have been squashed

This PR contains 3 commits, all with the same commit message (`chore(main/mympd): correct mpd socket path`), seems like they have not been squashed

**Comment by LaunchLee** [comment]
@Grimler91 I'm sorry for my fault. I just learned the the meaning of the squash in git and some knowledge about it. Now it has been squashed. Thanks.

**Pull request merged**
