### PR TITLE
Use PCRE in less

### PR DESCRIPTION
**Pull request by vmiliantsei**

### CODE REVIEW

**Comment by fornwall** [comment]
I'm unsure of the benefits here. Compatibility with Linux distributions would be a motivator, but e.g. Ubuntu does not seem to enable pcre in less. Could you motivate the change @vmiliantsei ?

**Comment by vmiliantsei** [comment]
@fornwall, Arch Linux has it: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/less

**Comment by vmiliantsei** [comment]
@fornwall, it just adds a support of a more powerful regex. Why not to have it?

**Comment by fornwall** [comment]
@vmiliantsei Thanks! I guess following Arch is good enough reason. This is now available in the updated `530-1` version of the less package.

**Pull request merged**
