### PR TITLE
python-pip: test build

### PR DESCRIPTION
**Pull request by Maxython**
NOT MERGE!!!

### CODE REVIEW

**Comment by Maxython** [comment]
@xtkoba, there is a problem with compiling python packages (for example pip - https://github.com/termux-pacman/termux-packages/actions/runs/3929500534). Can you explain why `popd` is needed (it causes an error)?

**Comment by xtkoba** [comment]
@Maxython To go back to the previous working directory. It was needed when the code snippet was used in `termux_step_pre_configure`, because we assume pwd is `$TERMUX_PKG_SRCDIR` when we are in that function. I don't know if it (`popd`) is needed now because the logic has been drastically changed.

**Comment by xtkoba** [comment]
Probably not needed. IIUC that part of code is only invoked through the `termux_step_get_dependencies_python` function, which is only invoked in `build-package.sh`. Right after the function is called `termux_step_patch_package`, at the top of which `cd "$TERMUX_PKG_SRCDIR"` is done.

So IIUC `popd` is not needed anymore and `pushd` can be replaced by `cd`.

**Comment by Maxython** [comment]
Ok, thanks for the explanation.

**Pull request closed without merging**
