### PR TITLE
termux-tools: add new system value TERMUX_PACKAGE_FORMAT

### PR DESCRIPTION
**Pull request by Maxython**
This value is needed by scripts that use the package manager in their work to work correctly.

### CODE REVIEW

**Comment by xeffyr** [comment]
Could you elaborate on why this is actually required?

Yes, `TERMUX_PACKAGE_FORMAT` is referenced in scripts. But it is actually *expanded* by heredoc execution during package build time into value one of: `debian`, `pacman`.

Example: https://github.com/termux/termux-packages/blob/98c4c40edb97bff17b3371a83f4d69521d27ee1c/packages/liblua54/lua54.subpackage.sh#L8

**Comment by Maxython** [comment]
>Could you elaborate on why this is actually required?

The value is considered not for compiler scripts, but for community or developers who have an action with a package manager in scripts, for example, these can be installer scripts. 

Yes, they could use the logic `dpkg 2>/dev/null ||  pacman`, but it is not reliable for two reasons:
1. Real dpkg or apt errors will not be reported.
2. There is a chance that a user can use apt and pacman, so this logic does not work for users who use pacman as their main package manager and apt for other purposes.

**Comment by Maxython** [comment]
@Grimler91, you can check this change?

**Comment by Grimler91** [comment]
@Maxython changes look acceptable, but please rebase to get rid of those merge commits

**Comment by Maxython** [comment]
Closing and creating new clean pull request

**Pull request closed without merging**
