### PR TITLE
golang: upgrade to 1.17.1

### PR DESCRIPTION
**Pull request by MedzikUser**
- Upgrade golang to 1.17.1 (latest version)

### CODE REVIEW

**Comment by MedzikUser** [comment]
`go tool compile: fork/exec /data/data/com.termux/files/usr/lib/go/pkg/tool/android_arm64/compile: no such file or directory`

**Comment by MedzikUser** [comment]
strange because the file exists...

**Comment by MedzikUser** [comment]
I guess `glibc` will be a bug

**Comment by thunder-coding** [comment]
Go through all comments in #7316

**Comment by thunder-coding** [comment]
Seems like the linker path can be changed as stated in https://github.com/golang/go/issues/47782#issuecomment-901259207

**Comment by thunder-coding** [comment]
Setting a `GO_LDSO` didn't work as well, my failed attempt can be viewed in #7474

So, if you have any other woraround, go for it or else close this PR

**Comment by MedzikUser** [comment]
> `$ go install golang.org/x/tools/gopls@latest`
> out: `go tool compile: fork/exec /data/data/com.termux/files/usr/lib/go/pkg/tool/android_arm64/compile: no such file or directory`

SUCCESS! This bug has been fixed!!!

**Comment by Pradeep688** [comment]
I have problems to vnc viewer and pycharm installation

**Comment by landfillbaby** [comment]
so is this working now? ready for merge?

**Comment by uudashr** [comment]
I have this issue
```
~/projects $ go run main.go
fork/exec /data/data/com.termux/files/usr/tmp/go-build827045429/b001/exe/main: no such file or directory
```

And built binary also fail
```
~/projects $ go build -o ./hello main.go
~/projects $ ls
hello  main.go
~/projects $ ./hello
-bash: ./hello: No such file or directory
```

**Comment by zorro** [comment]
```
$ go build hello.go                      
$ patchelf --print-interpreter hello     
/lib64/ld-linux-x86-64.so.2
```

Looks like go is linking to `/lib64/ld-linux-x86-64.so.2` instead of  `/system/bin/linker`

**Pull request merged**
