### PR TITLE
New package : dust #7082

### LINKED ISSUE #7082: Packaging request：dust
Description：Another more intuitive du command

home：https://github.com/bootandy/dust

Source code ：https://github.com/bootandy/dust/releases/tag/v0.6.0

### PR DESCRIPTION
**Pull request by MrAdityaAlok**
closes #7082

### CODE REVIEW

**Comment by suhan-paradkar** [comment]
Why is the file packages/dust/v0.6.0.tar.gz included??

**Comment by MrAdityaAlok** [comment]
@suhan-paradkar  sorry that was by mistake....

**Comment by xeffyr** [comment]
Merging this for now, however I should note that `dust` is not the first alternative to `du` available in our repository. We already have:
* `duc`
* `diskus`
* `tin-summer`
and maybe something else.

Lots of packages barely doing same task (even in slightly different way) is something that potentially unwanted.

*Remember that Termux is not Debian and doesn't have same amount of hosting and maintainer resources and therefore this is not a place where all in world existing packages should be dropped.*

**Comment by MrAdityaAlok** [comment]
> Merging this for now, however I should note that `dust` is not the first alternative to `du` available in our repository. We already have:
> * `duc`
> * `diskus`
> * `tin-summer`
> 
> and maybe something else.
> 
> Lots of packages barely doing same task (even in slightly different way) is something that potentially unwanted.
> 
> *Remember that Termux is not Debian and doesn't have same amount of hosting and maintainer resources and therefore this is not a place where all in world existing packages should be dropped.*

Okay, I will keep that in mind next time.

**Pull request merged**
