### PR TITLE
addpkg(main/seanime): 2.1.0

### PR DESCRIPTION
**Pull request by aicynide**
closes: https://github.com/termux/termux-packages/issues/21331

### CODE REVIEW

**Comment by SonaliBendre** [comment]
Merge IT merge it

**Comment by TomJo2000** [comment]
> is it forbidden to change `setup` script? if so let me know

Updating the setup scripts is fine, but is usually something for a separate PR.

<h1><em></em></h1>  

<sup>(This is a pre-written, saved reply.)</sup>
Please make sure to keep your commits squashed by the way.
For adding to a single commit you can use `git commit --amend`.
Since you already have multiple commits on your branch though,
you'll need to squash those with `git rebase -i HEAD~<n>` first.
<sup>(Where <code>\<n\></code> is the number of commits you want to modify.
Please make sure to only modify ***your*** commits.)</sup>
<a href="https://www.baeldung.com/ops/git-squash-commits#1-squash-the-last-x-commits">https://www.baeldung.com/ops/git-squash-commits#1-squash-the-last-x-commits</a>

<h1><em></em></h1> 

Since squashing or amending commits changes the git history you will need to force push any such changes.
e.g. `git push --force`,
or preferably `git push --force-with-lease=branchname`
to make sure you aren't clobbering any refs you haven't fetched locally yet.

**Comment by TomJo2000** [comment]
> Github allows squashing all commits while merging

While that's true, we prefer PR authors to keep their branches tidy.
The existence of a squashing function during merge does not excuse poor GitOps.

<h1><em></em></h1>  

<sup>(This is a pre-written, saved reply.)</sup>
Please make sure to keep your commits squashed by the way.
For adding to a single commit you can use `git commit --amend`.
Since you already have multiple commits on your branch though,
you'll need to squash those with `git rebase -i HEAD~<n>` first.
<sup>(Where <code>\<n\></code> is the number of commits you want to modify.
Please make sure to only modify ***your*** commits.)</sup>
<a href="https://www.baeldung.com/ops/git-squash-commits#1-squash-the-last-x-commits">https://www.baeldung.com/ops/git-squash-commits#1-squash-the-last-x-commits</a>

<h1><em></em></h1> 

Since squashing or amending commits changes the git history you will need to force push any such changes.
e.g. `git push --force`,
or preferably `git push --force-with-lease=branchname`
to make sure you aren't clobbering any refs you haven't fetched locally yet.

**Comment by TomJo2000** [comment]
> My 2 parent commit can't be squashed

They absolutely can be if you use `git rebase -i HEAD~3` instead of a `git merge`.

**Comment by TomJo2000** [comment]
> Fuck u I've better idea

Insulting me is not gonna get your commits squashed.

**Pull request closed without merging**
