### PR TITLE
Update youtubedr to 2.0.0

### PR DESCRIPTION
**Pull request by kcubeterm**

### CODE REVIEW

**Comment by kcubeterm** [comment]
I didn't expect that error, this build locally work

**Comment by Grimler91** [comment]
The CI tried building the updated packages in https://github.com/termux/termux-packages/commit/b59a7f025db590508e08f113c1ee7751917e224f for some reason. I restarted the build, let's see if it works now that the lastest master commit builds

**Comment by kcubeterm** [comment]
Again CI building b59a7f0

**Comment by kcubeterm** [comment]
Okay, finally it completed

**Pull request merged**
