### PR TITLE
new package: difftastic

### PR DESCRIPTION
**Pull request by pvonmoradi**
Add package [difftastic](https://difftastic.wilfred.me.uk/introduction.html), a syntax-aware diff tool

### CODE REVIEW

**Review by 2096779623 — CHANGES_REQUESTED** [review]
Refer to other related PRs to see how they build packages written in rust.
Example: https://github.com/termux/termux-packages/pull/11292/files

**Comment by pvonmoradi** [comment]
> Refer to other related PRs to see how they build packages written in rust. Example: https://github.com/termux/termux-packages/pull/11292/files

I thought for Rust projects and `cargo`, the build scripts are automatic? Like these:  
https://github.com/termux/termux-packages/pull/7295/files
https://github.com/termux/termux-packages/pull/7283/files
https://github.com/termux/termux-packages/pull/7269/files

**Comment by 2096779623** [comment]
> > Refer to other related PRs to see how they build packages written in rust. Example: https://github.com/termux/termux-packages/pull/11292/files
> 
> I thought for Rust projects and `cargo`, the build scripts are automatic? 

Yes,but it may be better to specify release when building.

**Comment by 2096779623** [comment]
```
~/debs $ pkg i ./difftastic_0.31.0_aarch64.deb             No group of mirrors selected. You might want to select a group by running 'termux-change-repo'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'difftastic' instead of './difftastic_0.31.0_aarch64.deb'
The following NEW packages will be installed:                difftastic
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.                                                        Need to get 0 B/3351 kB of archives.
After this operation, 49.9 MB of additional disk space will be used.
Get:1 /data/data/com.termux/files/home/debs/difftastic_0.31.0_aarch64.deb difftastic aarch64 0.31.0 [3351 kB]         Selecting previously unselected package difftastic.
(Reading database ... 26428 files and directories currently installed.)
Preparing to unpack .../difftastic_0.31.0_aarch64.deb ...
Unpacking difftastic (0.31.0) ...
Setting up difftastic (0.31.0) ...
~/debs $ difftastic
difftastic: command not found
~/debs $ difftastic
difftastic: command not found
~/debs $
```

**Comment by 2096779623** [comment]
> https://github.com/termux/termux-packages/pull/7295/files https://github.com/termux/termux-packages/pull/7283/files https://github.com/termux/termux-packages/pull/7269/files

These packages need fixing!

**Comment by pvonmoradi** [comment]
> ```
> ~/debs $ pkg i ./difftastic_0.31.0_aarch64.deb             No group of mirrors selected. You might want to select a group by running 'termux-change-repo'
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Note, selecting 'difftastic' instead of './difftastic_0.31.0_aarch64.deb'
> The following NEW packages will be installed:                difftastic
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.                                                        Need to get 0 B/3351 kB of archives.
> After this operation, 49.9 MB of additional disk space will be used.
> Get:1 /data/data/com.termux/files/home/debs/difftastic_0.31.0_aarch64.deb difftastic aarch64 0.31.0 [3351 kB]         Selecting previously unselected package difftastic.
> (Reading database ... 26428 files and directories currently installed.)
> Preparing to unpack .../difftastic_0.31.0_aarch64.deb ...
> Unpacking difftastic (0.31.0) ...
> Setting up difftastic (0.31.0) ...
> ~/debs $ difftastic
> difftastic: command not found
> ~/debs $ difftastic
> difftastic: command not found
> ~/debs $
> ```
‍‍‍Can you try `difft` since it is the name of the executable. I chose the name of the package be `difftastic` since other distros are naming it as such.
‍‍
```
  Installing /data/data/com.termux/files/usr/bin/difft
  Installed package `difftastic v0.31.0 (/home/builder/.termux-build/difftastic/src)` (executable `difft`)
```

**Comment by 2096779623** [comment]
> ‍‍‍Can you try difft since it is the name of the executable. I chose the name of the package be difftastic since other distros are naming it as such.

Oh,terribly sorry!

Btw, https://github.com/Wilfred/difftastic#license

You need to add `TERMUX_PKG_LICENSE_FILE` under `TERMUX_PKG_LICENSE`.

**Review by 2096779623 — APPROVED** [review]

**Pull request merged**
