### PR TITLE
php: update from 8.0.3 to 8.0.5

### PR DESCRIPTION
**Pull request by PuneetGopinath**
Update PHP 8.0.3 to PHP 8.0.5

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
This time, I didn't take sha256 hash from php.net
Instead I ran `php -r "echo hash_file('sha256', 'https://github.com/php/php-src/archive/php-8.0.5.tar.gz');"` in the command line

**Comment by PuneetGopinath** [comment]
Oh yes, now I checked it again looks like, I made a mistake in copy paste

**Comment by PuneetGopinath** [comment]
https://github.com/php/php-src/blob/php-8.0.5/LICENSE shows PHP License v3.01
So I updated license to 3.01, that fails in the workflow

**Comment by PuneetGopinath** [comment]
Thanks, I didn't check those files

**Comment by suhan-paradkar** [comment]
@PuneetGopinath the patches need to be updated...

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath the patches need to be updated...

Ok I will see, I didn't understand why the workflow failed this time, it was night in India at that time so I slept 💤

**Comment by PuneetGopinath** [comment]
Is the problem there in `ext-opcache-config.m4.patch`
I couldn't understand the workflow run?

**Comment by PuneetGopinath** [comment]
Can't connect to grimler.se
```
curl: (28) Failed to connect to grimler.se port 443: Connection timed out
Warning: Transient problem: timeout Will retry in 30 seconds. 20 retries left.
```

**Comment by PuneetGopinath** [comment]
My diff:
```diff
--- php.orig/ext/opcache/config.m4      2021-05-04 09:28:29.763613354 +0530
+++ php/ext/opcache/config.m4   2021-05-04 11:14:29.205191538 +0530
@@ -219,7 +219,9 @@
 }
 ]])],[dnl
     AC_DEFINE(HAVE_SHM_MMAP_ANON, 1, [Define if you have mmap(MAP_ANON) SHM support])
-    have_shm_mmap_anon=yes],[have_shm_mmap_anon=no],[have_shm_mmap_anon=no])
+    have_shm_mmap_anon=yes],[have_shm_mmap_anon=no],
+    AC_DEFINE(HAVE_SHM_MMAP_ANON, 1, [Define if you have mmap(MAP_ANON) SHM support])
+    [have_shm_mmap_anon=yes])
   AC_MSG_RESULT([$have_shm_mmap_anon])

   PHP_CHECK_FUNC_LIB(shm_open, rt, root)
@@ -336,6 +338,9 @@
 	$ZEND_JIT_SRC,
 	shared,,-DZEND_ENABLE_STATIC_TSRMLS_CACHE=1,,yes)
 
+  OPCACHE_SHARED_LIBADD=-lpcre2-8
+  PHP_SUBST(OPCACHE_SHARED_LIBADD)
+
   PHP_ADD_BUILD_DIR([$ext_builddir/Optimizer], 1)
   PHP_ADD_EXTENSION_DEP(opcache, pcre)
 
```

**Comment by PuneetGopinath** [comment]
I think workflow run has problem with grimler.se mirror?

**Comment by xeffyr** [comment]
Add TERMUX_PKG_LICENSE_FILE which specifies a license file (path relative to sources root).

**Comment by PuneetGopinath** [comment]
I think for TERMUX_PREFIX, I should use @TERMUX_PREFIX@

**Comment by xeffyr** [comment]
source root is a package source base directory. Not the prefix or something else. Also I have mentioned relative path use, so definitely no `$PREFIX`, `@TERMUX_PREFIX@` or something else.

If php source dir contains something like `LICENSEFILE.txt`, then `TERMUX_PKG_LICENSE_FILE=LICENSEFILE.txt`. If this file in subdirectory, then `TERMUX_PKG_LICENSE_FILE=package/sample/subdir/LICENSEFILE.txt`.

If package does not provide license with source code, then override `termux_step_install_license` build step and copy license from `$TERMUX_PKG_BUILDER_DIR`, but ensure that file is placed to directory with `build.sh`.

**Comment by xeffyr** [comment]
Also note on `@TERMUX_PREFIX@` - this will work only in patches because they are preprocessed with `sed`.

**Comment by PuneetGopinath** [comment]
Thanks so much, I think I learnt a lot about maintaining packages in termux

**Comment by PuneetGopinath** [comment]
Is there I problem with grimler.se mirror only for i686 ?

**Comment by Grimler91** [comment]
There's some issue with github actions, it fails to download files fairly often sincethe last couple of days. The failing arch should be random

**Comment by unknow2403** [comment]
okey thanks bro

Pada tanggal Rab, 5 Mei 2021 11:31, Henrik Grimler ***@***.***>
menulis:

**Comment by PuneetGopinath** [comment]
> There's some issue with github actions, it fails to download files fairly often sincethe last couple of days. The failing arch should be random

Ohh, should you re run all jobs?

**Comment by suhan-paradkar** [comment]
> 
> 
> There's some issue with github actions, it fails to download files fairly often sincethe last couple of days. The failing arch should be random

yeah you are right... that is a problem specifically to github actions CI, my build environment (docker image) works just fine in gcloud

**Comment by PuneetGopinath** [comment]
Now checks are passing, will I merge branch master using git?

**Comment by unknow2403** [comment]
i'm ready to up, but spek hp failed

Pada tanggal Rab, 5 Mei 2021 13:54, Puneet Gopinath <
***@***.***> menulis:

**Comment by suhan-paradkar** [comment]
> Now checks are passing, will I merge branch master using git?

@xeffyr or any other member will merge it... You don't need to (you can't)

**Comment by PuneetGopinath** [comment]
I can, just run `git add orig https://github.com/termux/termux-packages.git` after cloning my fork with branch `update-php`.
Then run `git pull orig master`, commit and push

**Comment by PuneetGopinath** [comment]
> @xeffyr or any other member will merge it... You don't need to (you can't)

I can, just run `git remote add orig https://github.com/termux/termux-packages.git` after cloning my fork with branch `update-php`.
Then run `git pull orig master`, commit and push

**Pull request merged**
