### PR TITLE
ctags: add ctags-cross subpackage

### PR DESCRIPTION
**Pull request by stsp**
This patch adds ctags-cross subpackage that can be used for cross-builds. Had to increment version to force rebuild.

### CODE REVIEW

**Comment by twaik** [comment]
> Had to increment version to force rebuild

That is the reason `TERMUX_PKG_REVISION` exists.

**Comment by Biswa96** [comment]
stsp, Again! why are you keep creating pull requests for host packages which is not required for this repository?

**Comment by stsp** [comment]
> stsp, Again! why are you keep creating pull requests for host packages which is not required for this repository?

Well, this time I put it into the subpackage,
as was suggested here:
https://github.com/termux/termux-packages/pull/22569#discussion_r1897609222
Why is this the problem?
The aforementioned smallerc-cross
subpackage is also not required for the
repository, yet I was suggested to create
it.

**Comment by stsp** [comment]
> That is the reason TERMUX_PKG_REVISION exists.

Thanks for that info, done.
Especially good to know because I
had problems with colon in file name
when running things via termux-apt-repo
and upload-artifacts action.
With that change there is no more colon.

**Comment by Biswa96** [comment]
> Why is this the problem?
> The aforementioned smallerc-cross
> subpackage is also not required for the
> repository, yet I was suggested to create
> it.

Because smallerc-cross is probably required in that case. You have not provide any reason for this one and for _this_ repository.

**Comment by stsp** [comment]
> Because smallerc-cross is probably required in that case. You have not provide any reason for this one and for this
> repository.

There are really no deps in this repo
currently for ctags-cross, as well as no
deps for smallerc-cross.
I just thought that if some package is
already being built, then adding a host
sub-package is not a big deal.
If this is a problem, I can close this PR.
But I really don't understand why, or
what's the difference with smallerc-cross.

**Comment by stsp** [comment]
And of course I need this for the packages
I build in my branch. Otherwise I wouldn't
be doing that.

**Comment by Biswa96** [comment]
I think, the host sub-package is added only when it is required by more than one package. For example, qt6-base-cross, libwayland-cross etc.

**Comment by stsp** [comment]
Ah, sorry, smallerc-cross is self-required
(needed to build smallerc libs).
So yes, bad example, you are right.
So should I close this?

**Comment by stsp** [comment]
Ok.

**Comment by Biswa96** [comment]
By the way, your comments are formatted like a column. I'm not sure if it as GitHub issue.

**Comment by stsp** [comment]
Got too used to mobile where you don't have a space for long lines.

**Pull request closed without merging**
