### PR TITLE
composer: update to 2.0.14 from 2.0.13

### PR DESCRIPTION
**Pull request by PuneetGopinath**
Hi everyone! Composer package maintaner here!

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
This version was just released 30 minutes ago.

**Comment by Grimler91** [comment]
Please rebase against master and the build should proceed further

**Comment by PuneetGopinath** [comment]
@Grimler91 It's still failing, I rebased

**Comment by Grimler91** [comment]
Right, I only fixed apr and not apr-util. If you rebase again it should work ([after this](https://github.com/termux/termux-packages/commit/db2340ae62b9c349ffed7dae8ba342b9729e411d))

**Comment by PuneetGopinath** [comment]
> Right, I only fixed apr and not apr-util. If you rebase again it should work ([after this](https://github.com/termux/termux-packages/commit/db2340ae62b9c349ffed7dae8ba342b9729e411d))

This time I had problem while rebasing, so I pulled instead of rebasing

**Comment by suhan-paradkar** [comment]
> > Right, I only fixed apr and not apr-util. If you rebase again it should work ([after this](https://github.com/termux/termux-packages/commit/db2340ae62b9c349ffed7dae8ba342b9729e411d))
> 
> This time I had problem while rebasing, so I pulled instead of rebasing

What problems did you have?

**Comment by PuneetGopinath** [comment]
> What problems did you have?

It said `Already up to date`, I checked my branch using `git status` but it said `On branch feature/add-composer...`
I ran `git rebase master`

**Comment by suhan-paradkar** [comment]
Send the output of git status

**Comment by PuneetGopinath** [comment]
```
On branch feature/add-composer
Your branch is up to date with 'origin/feature/add-composer'.

nothing to commit, working tree clean
```

**Comment by suhan-paradkar** [comment]
Well, first you need to set upstream

```
git checkout master
git remote add upstream https://github.com/termux/termux-packages
```

Then, merge it...

```
git fetch upstream
git merge upstream/master
```

This is one-time only... Then you can fetch upstream and merge from github website for all repositories (easier way)...

Now checkout to target branch and rebase against master

```
git checkout feature/add-composer
git rebase master
```

You may need to force push it to remote

**Comment by PuneetGopinath** [comment]
Thanks for this big description, I know these things
See that my master branch is up to date: https://github.com/PuneetGopinath/termux-packages/tree/master
GitHub says
```
This branch is even with termux:master.
```

**Comment by suhan-paradkar** [comment]
Looks like apache2 source url needs to be updated...

**Comment by PuneetGopinath** [comment]
> Looks like httpd source url needs to be updated...

I saw in website that the latest release is 2.4.46 how is it 2.4.47 here, see https://httpd.apache.org/

**Comment by suhan-paradkar** [comment]
> I saw in website that the latest release is 2.4.46 how is it 2.4.47 here, see https://httpd.apache.org/

It May be that they downgraded it...

**Comment by xeffyr** [comment]
> I saw in website that the latest release is 2.4.46 how is it 2.4.47 here

Removed for some reason.

Arch uses 2.4.47 now: https://github.com/archlinux/svntogit-packages/commit/7af681753b35f427f1e277d49f223691f8612d13

Debian has archived sources here: https://deb.debian.org/debian/pool/main/a/apache2/apache2_2.4.47.orig.tar.gz

**Comment by PuneetGopinath** [comment]
> It May be that they downgraded it... 

Can a released version be removed, as per what I know it should be never deleted

**Comment by PuneetGopinath** [comment]
> > I saw in website that the latest release is 2.4.46 how is it 2.4.47 here
> 
> Removed for some reason.
> 
> Arch uses 2.4.47 now: https://github.com/archlinux/svntogit-packages/commit/7af681753b35f427f1e277d49f223691f8612d13
> 
> Debian has archived sources here: https://deb.debian.org/debian/pool/main/a/apache2/apache2_2.4.47.orig.tar.gz
> 
> ***
> 
> P.S. https://bz.apache.org/bugzilla/show_bug.cgi?id=65294, maybe we really need to downgrade too.

Oh, will I open a PR?

**Comment by xeffyr** [comment]
You can downgrade it in this pull request.

**Comment by PuneetGopinath** [comment]
> You can downgrade it in this pull request.

I will do it tomorrow

**Comment by PuneetGopinath** [comment]
> You can downgrade it in this pull request.

I committed now.

**Comment by xeffyr** [comment]
@PuneetGopinath Package manager can't handle downgrade on its own. When downgrading the package, you should set or increment its epoch. Otherwise `pkg upgrade` won't work.

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath Package manager can't handle downgrade on its own. When downgrading the package, you should set or increment its epoch. Otherwise `pkg upgrade` won't work.

Sorry, I should have read the contributing guidelines again
But I guess we have to use `TERMUX_PKG_REVISION`.

**Comment by xeffyr** [comment]
> But I guess we have to use TERMUX_PKG_REVISION.

Nope. In order to use revision, you'll have to leave the version to be 2.4.47.

Downgrading as well as changing versioning scheme will need epoch bumping. Otherwise `apt` won't recognize this as update.

**Comment by PuneetGopinath** [comment]
> > But I guess we have to use TERMUX_PKG_REVISION.
> 
> Nope. In order to use revision, you'll have to leave the version be 2.4.47.
> 
> Downgrading as well as changing versioning scheme will need epoch bumping. Otherwise `apt` won't recognize this as update.

Thanks, can this pr be merged

**Pull request merged**
