### PR TITLE
Add: Hermes

### PR DESCRIPTION
**Pull request by AbhiTheModder**
Hermes is a JavaScript engine optimized for React Native apps. It can improve performance, reduce memory usage, and enable faster startup times.

In this pull request, I've added a new package `hermes` that builds the following tools in addition to `hermes`:

- `hdb`: A command line debugger for JavaScript code running on hermes
- `hbcdump`: A tool to disassemble hermes bytecode files
-`hermesc`: A standalone compiler that can convert JavaScript to hermes bytecode, but cannot execute it
- `hvm`: A standalone virtual machine that can execute hermes bytecode, but cannot compile it

These tools can be useful for debugging & testing on termux. You can find more information about them [here](https://github.com/facebook/hermes/blob/main/doc/BuildingAndRunning.md#other-tools)

### CODE REVIEW

**Comment by AbhiTheModder** [comment]
@Grimler91 could you please check what's the issue causing gh actions to fail? I cross checked by building in my device also and it's working fine. 

Please review and let me know if you have any feedback or suggestions. Thanks!

**Comment by AbhiTheModder** [comment]
> Missing dependency on readline it seems
@Grimler91 while during local compilation it didn't show that... Thats strange

**Comment by AbhiTheModder** [comment]
@sylirre Now I get it, I'll fix it and do a PR after rebasing. Thanks

**Comment by AbhiTheModder** [comment]
@sylirre Hi, after fixing the readline I encountered another error which of .cmake file and when I looked at hermes main repo docs they said we need to provide it's `$PATH` for cross-compilation but the issue is that file during build of termux is put at  `/home/builder/.termux-build/hermes/build/ImportHermesc.cmake` instead of  `/home/builder/.termux-build/hermes/src/ImportHermesc.cmake`, Note the `/src/` and` /build/` part. If the file were to be at `/src/` I can set the path through `$TERMUX_PKG_SRCDIR` but for this, how should I go with?

**Comment by AbhiTheModder** [comment]
> And you have many unrelated changes in commits. Make sure you add changes on the top of the latest `master` branch and do `git pull --rebase` since then without any merge commits.

Thanks ... don't worry I'm just check right now for actions testing because my local builds are passing so it's the only for testing, I'll rebase everything at last and then raise the PR.

**Comment by TomJo2000** [comment]
I'm combing through old PRs right now, am I right in assuming this PR is abandoned?
In either case, it's in no state to merge.

**Comment by AbhiTheModder** [comment]
> It's in no state to merge.

Yeah, It's too much old and outdated now, I should close it.

**Pull request closed without merging**
