### PR TITLE
python: update to 3.12

### LINKED ISSUE #18210: python 3.12.0 request
### Why is it worth to add this package?

python 3.12.0 is essential for most functions now 

### Home page URL

python 3.12.0 is essential for most functions now 

### Source code URL

python 3.12.0 is essential for most functions now 

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

python 3.12.0 is essential for most functions now

### PR DESCRIPTION
**Pull request by landfillbaby**
See [What’s New In Python 3.12](https://docs.python.org/3/whatsnew/3.12.html).

Fixes #18210.

### CODE REVIEW

**Comment by 2096779623** [comment]
https://github.com/python/cpython/blob/6678ef41d2a188a92c7ac5249d716e942b5114a6/configure.ac#L153C50-L153C50

**Comment by licy183** [comment]
We should build a host python for python3.12. Ubuntu 22.04 hasn't packaged it yet. Some other repositories such as `ppa/deadsnakes` may be an alternative in the future, but it hasn't packaged python3.12 yet.

IMO we had better hold it to 3.11 until some other python libraries support it. Bumping to python3.12 will at least break the build process of `numpy` because python3.12 remove support for distutils but `meson-python` (which `numpy` uses for python3.12) hasn't supported cross-compile.

**Comment by romanovj** [comment]
I think that termux should stick to 3.11and 3.12 could be provided by tur-repo

**Comment by TomJo2000** [comment]
> I think that termux should stick to 3.11and 3.12 could be provided by tur-repo

The opposite will be the case.
Termux is a rolling release and the main repo hosts the latest versions of packages.
Older versions are only provided in special cases such as LTS releases, or on the TUR.

**Comment by showierdata9978** [comment]
atleast allow people to install it as python3.12

**Comment by Randrianasulu** [comment]
installing CI artefacts resulted in pip setup error:


```
~ $ dpkg -i debs/python*.deb                                                                       
(Reading database ... 125977 files and directories currently installed.)                           
Preparing to unpack .../python-ensurepip-wheels_3.12.0_all.deb ...                               
  Unpacking python-ensurepip-wheels (3.12.0) over (3.12.0) ...                                       Preparing to unpack .../python-numpy-static_1.26.1-1_aarch64.deb ...                              
 Unpacking python-numpy-static (1.26.1-1) over (1.26.1-1) ...                                       Preparing to unpack .../python-numpy_1.26.1-1_aarch64.deb ...                                      Unpacking python-numpy (1.26.1-1) over (1.26.1-1) ...                                              Preparing to unpack .../python-pillow_10.1.0-1_aarch64.deb ...                                     Unpacking python-pillow (10.1.0-1) over (10.1.0-1) ...                                             Preparing to unpack debs/python-pip_23.3-1_all.deb ...                                             Unpacking python-pip (23.3-1) over (23.3-1) ...                                                    Preparing to unpack .../python-static_3.12.0_aarch64.deb ...                                       Unpacking python-static (3.12.0) over (3.12.0) ...                                                 Preparing to unpack .../python-tkinter_3.12.0_aarch64.deb ...                                      Unpacking python-tkinter (3.12.0) over (3.12.0) ...                                                Preparing to unpack debs/python_3.12.0_aarch64.deb ...                                             Unpacking python (3.12.0) over (3.12.0) ...                                                        Setting up python (3.12.0) ...                                                                     Setting up python-ensurepip-wheels (3.12.0) ...                                                    Setting up python-numpy (1.26.1-1) ...                                                             
Setting up python-pillow (10.1.0-1) ...                                                            
Setting up python-pip (23.3-1) ...                                                                 
pip setup...                                                                                       
Traceback (most recent call last):                                                                   File "/data/data/com.termux/files/usr/bin/pip", line 5, in <module>                                  
from pip._internal.cli.main import main                                                          File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 10, in <module>                                                                                     from pip._internal.cli.autocompletion import autocomplete                                        File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>                                                                          
 from pip._internal.cli.main_parser import create_main_parser                                     File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pip/_internal/cli/main_parser.py", line 5, in <module>                                                                               import subprocess                                                                                File "/data/data/com.termux/files/usr/lib/python3.12/subprocess.py", line 104, in <module>        
   from _posixsubprocess import fork_exec as _fork_exec                                           
ImportError: dlopen failed: cannot locate symbol "_Py_NoneStruct" referenced by "/data/data/com.termux/files/usr/lib/python3.12/lib-dynload/_posixsubprocess.cpython-312.so"...                     
  Setting up python-static (3.12.0) ...                                                              
Setting up python-tkinter (3.12.0) ...                                                             
Setting up python-numpy-static (1.26.1-1) ...                                                      
Processing triggers for man (1.14.6-1) ...
```

**Comment by Randrianasulu** [comment]
> @Randrianasulu Using wildcards with dpkg won't result in proper installation order of dependencies.

well, I tried to reinstall with
pkg reinstall ~/debs/python-ensurepip-wheels_3.12.0_all.deb

and then.python and python-static, and then again ensurepip and python-pip still giving me same error ....

**Comment by landfillbaby** [comment]
yeah i kind of abandoned this since python 3.12 drops so much support

**Comment by yubrajbhoi** [comment]
Looks like some old patches were not applied. Here are all the patches: https://github.com/yubrajbhoi/termux-python-12/tree/main/patches

I have tested them with Python `3.12.0` and `3.12.1`. Every modules seems to be working, including `subprocess`. Also, AFAIK `distutils` is still available from `setuptools` package. Can't we use that?

I used that to build Numpy for `Python-3.12.1` using the `setup.py` script and it worked.

**Comment by licy183** [comment]
It tests fine on my device.

@landfillbaby @sylirre Could you please test it again?

The setuptools should be hardcoded to `67.6.1` if crossenv wants to be used, even `67.7` can't be used due to some weird errors...

**Comment by licy183** [comment]
Next, we should find all the revdeps of python, check whether it supports python3.12 and revbump if needed.

**Comment by Loup-Garou911XD** [comment]
:eyes:

**Comment by codenamedpkt** [comment]
`distutils` still exists and not archived from pypa's GitHub Account, they also belongs to Python.org: https://github.com/pypa/distutils

**Comment by licy183** [comment]
Revdeps of python

```
2ping
asciidoc
asciinema
autojump
boost
borgbackup
calcurse
dbus-python
electrum
emscripten
fetchmail
frida
gdb
gjots2
glib
gnumeric
gobject-introspection
gst-python
hash-slinger
hexchat
inkscape
iwyu
jbig2enc
ki18n
kitty
ledger
libllvm
libncnn
libpcsclite
libplacebo
libsearpc
libtorrent-rasterbar
libtsduck
libunbound
libxml2
lilypond
lv2
matplotlib
olivia
opencv
orca
panda3d
pastebinit
pathpicker
profanity
pyatspi
pycairo
pygobject
pyqt5
python-apsw
python-apt
python-bcrypt
python-contourpy
python-cryptography
python-greenlet
python-grpcio
python-lameenc
python-libsass
python-lxml
python-msgpack
python-numpy
python-pillow
python-pyqtwebengine
python-qscintilla
python-sabyenc3
python-scipy
python-tldp
python-torch
python-torchaudio
python-torchvision
python-xlib
ranger
rdiff-backup
rdircd
recoll
rhythmbox
sabnzbd
seafile-client
speechd
srt2vobsub
termux-apt-repo
termux-create-package
termux-gui-package
termux-gui-pm
tizonia
uftrace
units
uwsgi
vim-gtk
vim-python
weechat
xfce4-panel-profiles
zeronet
```

**Comment by TomJo2000** [comment]
I'm gonna pull down this PR to my development fork and do some local builds for all of these.

**Comment by TomJo2000** [comment]
Finally had the time to finish up local testing.
<details><summary>82/93</summary>
<p>



| Package Name          | Builds? |
|-----------------------|---------|
| 2ping                 | [x]     |
| asciidoc              | [x]     |
| asciinema             | [x]     |
| autojump              | [x]     |
| boost                 | [x]     |
| borgbackup            | [x]     |
| calcurse              | [x]     |
| dbus-python           | [x]     |
| electrum              | [x]     |
| emscripten            | [x]     |
| fetchmail             | [x]     |
| frida                 | [ ]     |
| gdb                   | [x]     |
| gjots2                | [x]     |
| glib-bin              | [x]     |
| gnumeric              | [x]     |
| gobject-introspection | [x]     |
| gst-python            | [x]     |
| hash-slinger          | [x]     |
| hexchat               | [x]     |
| inkscape              | [x]     |
| iwyu                  | [x]     |
| jbig2enc              | [x]     |
| ki18n                 | [x]     |
| kitty                 | [ ]     |
| ledger                | [x]     |
| libllvm               | [x]     |
| libncnn               | [x]     |
| libpcsclite           | [x]     |
| libplacebo            | [x]     |
| libsearpc             | [x]     |
| libtorrent-rasterbar  | [ ]     |
| libtsduck             | [x]     |
| libunbound            | [x]     |
| libxml2               | [x]     |
| lilypond              | [x]     |
| lv2                   | [x]     |
| matplotlib            | [x]     |
| olivia                | [x]     |
| opencv                | [ ]     |
| orca                  | [x]     |
| panda3d               | [x]     |
| pastebinit            | [x]     |
| pathpicker            | [x]     |
| profanity             | [x]     |
| pyatspi               | [x]     |
| pycairo               | [x]     |
| pygobject             | [x]     |
| pyqt5                 | [x]     |
| python-apsw           | [x]     |
| python-apt            | [x]     |
| python-bcrypt         | [x]     |
| python-contourpy      | [x]     |
| python-cryptography   | [x]     |
| python-greenlet       | [x]     |
| python-grpcio         | [ ]     |
| python-lameenc        | [x]     |
| python-libsass        | [x]     |
| python-lxml           | [x]     |
| python-msgpack        | [x]     |
| python-numpy          | [x]     |
| python-pillow         | [x]     |
| python-pyqtwebengine  | [x]     |
| python-qscintilla     | [x]     |
| python-sabyenc3       | [x]     |
| python-scipy          | [ ]     |
| python-tldp           | [x]     |
| python-torch          | [ ]     |
| python-torchaudio     | [ ]     |
| python-torchvision    | [ ]     |
| python-xlib           | [x]     |
| ranger                | [x]     |
| rdiff-backup          | [x]     |
| rdircd                | [x]     |
| recoll                | [x]     |
| rhythmbox             | [x]     |
| sabnzbd               | [x]     |
| seafile-client        | [x]     |
| speechd               | [x]     |
| srt2vobsub            | [ ]     |
| termux-apt-repo       | [x]     |
| termux-create-package | [x]     |
| termux-gui-package    | [x]     |
| termux-gui-pm         | [x]     |
| tizonia               | [ ]     |
| uftrace               | [x]     |
| units                 | [x]     |
| uwsgi                 | [x]     |
| vim-gtk               | [x]     |
| vim-python            | [x]     |
| weechat               | [x]     |
| xfce4-panel-profiles  | [x]     |
| zeronet               | [x]     |

</p>
</details>

**Comment by TomJo2000** [comment]
As mentioned above, since `xkeyboard-config` now depends on `python` it'll need to be added to the rebuild list.

**Comment by truboxl** [comment]
emscripten just need the `$PREFIX/bin/python3` interpreter to exist, no python library compiling happens

**Comment by codenamedpkt** [comment]
> We should build a host python for python3.12. Ubuntu 22.04 hasn't packaged it yet. Some other repositories such as `ppa/deadsnakes` may be an alternative in the future, but it hasn't packaged python3.12 yet.
> 
> IMO we had better hold it to 3.11 until some other python libraries support it. Bumping to python3.12 will at least break the build process of `numpy` because python3.12 remove support for distutils but `meson-python` (which `numpy` uses for python3.12) hasn't supported cross-compile.

Look on lines from official meson-python GitHub repo, from pyproject.toml:

```pyproject.toml
Requires = [
  'meson >= 1.2.3; python_version >= "3.12"',
  'packaging >= 19.0',
  'pyproject-metadata >= 0.7.1',
]
```

They gave up numpy and tomli as requirements and deps, in their main branch.

**Comment by TomJo2000** [comment]
> They gave up numpy and tomli as requirements and deps, in their main branch.

I am not sure where the hell you are getting that from.
Surely not `mesonbuild/meson-python`

Which very much [still states](https://github.com/mesonbuild/meson-python/blob/063fe8bc8ad6984c29b24a0f72a14e1ced091a9c/pyproject.toml#L8-L14):
```toml
requires = [
  'meson >= 0.63.3; python_version < "3.12"',
  'meson >= 1.2.3; python_version >= "3.12"',
  'packaging >= 19.0',
  'pyproject-metadata >= 0.7.1',
  'tomli >= 1.0.0; python_version < "3.11"',
]
```

**Comment by codenamedpkt** [comment]
Look at https://github.com/mesonbuild/meson-python/blob/main/pyproject.toml#L8-L14

> > They gave up numpy and tomli as requirements and deps, in their main branch.
> 
> I am not sure where the hell you are getting that from. Surely not `mesonbuild/meson-python`
> 
> Which very much [still states](https://github.com/mesonbuild/meson-python/blob/063fe8bc8ad6984c29b24a0f72a14e1ced091a9c/pyproject.toml#L8-L14):
> 
> ```toml
> requires = [
>   'meson >= 0.63.3; python_version < "3.12"',
>   'meson >= 1.2.3; python_version >= "3.12"',
>   'packaging >= 19.0',
>   'pyproject-metadata >= 0.7.1',
>   'tomli >= 1.0.0; python_version < "3.11"',
> ]
> ```

https://github.com/mesonbuild/meson-python/blob/master/pyproject.toml#L9

>   'meson >= 0.63.3; python_version < "3.12"',

This means, if you have meson grater equal than v0.63.3 but less than v1.2.2, you need python 3.11 or earlier. Or only use the latest meson-python tied with python 3.12.4 and tomli is not needed in latest meson-python commits.

**Comment by TomJo2000** [comment]
Ah okay I read that wrong then.

**Comment by codenamedpkt** [comment]
As your table:

> Finally had the time to finish up local build testing.

<details><summary />93/93

|Package Name|Builds?|
|------------|-------|
|2ping|	[x]|
|asciidoc	|[x]|
|asciinema|	[x]|
|autojump|	[x]|
|boost|	[x]|
|borgbackup|	[x]|
|calcurse|	[x]|
|dbus-python|	[x]|
|electrum|	[x]|
|emscripten|	[x]|
|fetchmail|	[x]|
|frida	|	[x]|
|gdb		|	[x]|
|gjots2	|	[x]|
|glib-bin|	[x]|
|gnumeric|	[x]|
|gobject-introspection|	[x]|
|gst-python|	[x]|
|hash-slinger|	[x]|
|hexchat|	[x]|
|inkscape|	[x]|
|iwyu|	[x]|
|jbig2enc|	[x]|
|ki18n|	[x]|
|kitty|	[x]|
|ledger|	[x]|
|libllvm|	[x]|
|libncnn|	[x]|
|libpcsclite|	[x]|
|libplacebo|	[x]|
|libsearpc|	[x]|
|libtorrent-rasterbar|	[x]|
|libtsduck|	[x]|
|libunbound|	[x]|
|libxml2|	[x]|
|lilypond|	[x]|
|lv2|	[x]|
|matplotlib|	[x]|
|olivia|	[x]|
|opencv|	[x]|
|orca|	[x]|
|panda3d|	[x]|
|pastebinit|	[x]|
|pathpicker|	[x]|
|profanity|	[x]|
|pyatspi|	[x]|
|pycairo|	[x]|
|pygobject|	[x]|
|pyqt5|	[x]|
|python-apsw|	[x]|
|python-apt|	[x]|
|python-bcrypt|	[x]|
|python-contourpy|	[x]|
|python-cryptography|	[x]|
|python-greenlet|	[x]|
|python-grpcio|	[x]|
|python-lameenc|	[x]|
|python-libsass|	[x]|
|python-lxml|	[x]|
|python-msgpack|	[x]|
|python-numpy|	[x]|
|python-pillow|	[x]|
|python-pyqtwebengine|	[x]|
|python-qscintilla|	[x]|
|python-sabyenc3|	[x]|
|python-scipy|	[x]|
|python-tldp|	[x]|
|python-torch|	[x]|
|python-torchaudio|	[x]|
|python-torchvision|	[x]|
|python-xlib|	[x]|
|ranger|	[x]|
|rdiff-backup|	[x]|
|rdircd|	[x]|
|recoll|	[x]|
|rhythmbox|	[x]|
|sabnzbd|	[x]|
|seafile-client|	[x]|
|speechd|	[x]|
|srt2vobsub|	[x]|
|termux-apt-repo|	[x]|
|termux-create-package|	[x]|
|termux-gui-package|	[x]|
|termux-gui-pm|	[x]|
|tizonia|	[x]|
|uftrace|	[x]|
|units|	[x]|
|uwsgi|	[x]|
|vim-gtk|	[x]|
|vim-python|	[x]|
|weechat|	[x]|
|xfce4-panel-profiles|	[x]|
|zeronet|	[x]|
</details>

If you mean `Kitty` is a GPU-ed terminal emus thats one: [Kitty Terminal Emulater](https://github.com/kovidgoyal/kitty) or using pypi from kitty, it is yanked.
Others:
- [Frida](https://pypi.org/project/frida/#data) 
- [LibTorrent as libtorrent-rasterbar](https://pypi.org/project/libtorrent/#data) 
- [OpenCV](https://pypi.org/project/opencv-python/#data) 
- [gRPCIO](https://pypi.org/project/grpcio/#data) 
- [SciPy](https://pypi.org/project/scipy/#data) 
- [PyTorch](https://pypi.org/project/torch/#data) 
- [Audio by PyTorch](https://pypi.org/project/torchaudio/#data) 
- [Vision by PyTorch](https://pypi.org/project/torchvision/#data) 
- [SRT2VobSub](https://srt2vobsub.sourceforge.io) 
- [Skema by Tizonia](https://github.com/tizonia/skema)

I finished up here.

**Comment by codenamedpkt** [comment]
> > If you mean `Kitty` is a GPU-ed terminal emus thats one: [Kitty Terminal Emulater](https://github.com/kovidgoyal/kitty) or using pypi from kitty, it is yanked. Others:
> > 
> > * [Frida](https://pypi.org/project/frida/#data)
> > * [LibTorrent as libtorrent-rasterbar](https://pypi.org/project/libtorrent/#data)
> > * [OpenCV](https://pypi.org/project/opencv-python/#data)
> > * [gRPCIO](https://pypi.org/project/grpcio/#data)
> > * [SciPy](https://pypi.org/project/scipy/#data)
> > * [PyTorch](https://pypi.org/project/torch/#data)
> > * [Audio by PyTorch](https://pypi.org/project/torchaudio/#data)
> > * [Vision by PyTorch](https://pypi.org/project/torchvision/#data)
> > * [SRT2VobSub](https://srt2vobsub.sourceforge.io)
> > * [Skema by Tizonia](https://github.com/tizonia/skema)
> > 
> > I finished up here.
> 
> Those packages are referring to all packages in our repositories that depend on Python. These 11 were the ones that failed in my local build testing. Are you saying you tested them and they build fine? Or are you just listing them for no reason.

They are not depends to actual Python. We just list them for reference.

**Comment by codenamedpkt** [comment]
> > > If you mean `Kitty` is a GPU-ed terminal emus thats one: [Kitty Terminal Emulater](https://github.com/kovidgoyal/kitty) or using pypi from kitty, it is yanked. Others:
> > > 
> > > * [Frida](https://pypi.org/project/frida/#data)
> > > * [LibTorrent as libtorrent-rasterbar](https://pypi.org/project/libtorrent/#data)
> > > * [OpenCV](https://pypi.org/project/opencv-python/#data)
> > > * [gRPCIO](https://pypi.org/project/grpcio/#data)
> > > * [SciPy](https://pypi.org/project/scipy/#data)
> > > * [PyTorch](https://pypi.org/project/torch/#data)
> > > * [Audio by PyTorch](https://pypi.org/project/torchaudio/#data)
> > > * [Vision by PyTorch](https://pypi.org/project/torchvision/#data)
> > > * [SRT2VobSub](https://srt2vobsub.sourceforge.io)
> > > * [Skema by Tizonia](https://github.com/tizonia/skema)
> > > 
> > > I finished up here.
> > 
> > 
> > Those packages are referring to all packages in our repositories that depend on Python. These 11 were the ones that failed in my local build testing. Are you saying you tested them and they build fine? Or are you just listing them for no reason.
> 
> They are not depends to actual Python. We just list them for reference.

You can use pip install -U --no-cache-dir --force-reinstall --clean your_http_github_or_gitlab_link ... .

**Comment by TomJo2000** [comment]
> They are not depends to actual Python. We just list them for reference.

That is not helpful.
I am gonna apologize in advance but I'm going to have to ask you to either start being actually helpful in here or stop clogging up this PR with what amounts to spam.

The 93 packages listed are the sum total of all packages in the repositories at that time with `python` listed in their dependencies.

You can help by figuring out what the blockers for building the 11 failing packages of that list against Python 3.12 are.

**Comment by fornwall** [comment]
I think we`re getting ready for python 3.12 🎉!

`kitty`, `libtorrent-rasterbar`, `opencv`, `python-grpcio`, `python-scipy`, `python-torch/torchaudio/torchvision`, `srt2vobsub` and `tizonia` all builds now.

`frida` has not been buildable for a year or so, but once/if that package is fixed in general, the latest versions are compatible with python 3.12.

Any concerns or ideas of things to look into?

**Comment by TomJo2000** [comment]
I think we should definitely have some contingency in place in case we need to role this back.
Maybe keep a copy of the last Python 3.11 build script and patches in the disabled-packages directory pending its move to the TUR?

Also does that list constitute all the reverse dependencies for Python?

**Comment by fornwall** [comment]
> I think we should definitely have some contingency in place in case we need to role this back. Maybe keep a copy of the last Python 3.11 build script and patches in the disabled-packages directory pending its move to the TUR?

👍 - added `disabled-packages/python3.11` now.

> Also does that list constitute all the reverse dependencies for Python?

This list - kitty, libtorrent-rasterbar, opencv, python-grpcio, python-scipy, python-torch/torchaudio/torchvision, srt2vobsub and tizonia? I just mentioned these as being recently fixed, in this PR or in other recent ones. In general all reverse dependencies seems to build now (as in build with `./build-package.sh -i <revdep>` after checking out this branch), though I may of course have missed something.

**Review by TomJo2000 — APPROVED** [review]
Welp we're gonna find out in prod soon enough.

**Comment by fornwall** [comment]
One important thing to note with a python minor version update such as this is that users are going to loose (having to reinstall) all pip-installed packages, as they are in `lib/python3.11/site-packages`, and the new python 3.12 won't look there (and the contents of it might not be 3.12 compatible anyway).

It's nothing "strange" in a way, and the same thing happened in the last `3.10` -> `3.11` update - but that was almost 2 years ago (9a396657b3), so it might come as a surprise for some. I don't know if informing about it in a `postinst` would help?

**Comment by TomJo2000** [comment]
Got a full rebuild list based on `rg 'DEPENDS.*python'`

```bash
./scripts/run-docker.sh ./build-package.sh -i python gnumeric kf6-ki18n vim-gtk xkeyboard-config inkscape gjots2 ki18n python-pyqtwebengine rhythmbox python-qscintilla pyatspi olivia hexchat opencv opencv xfce4-panel-profiles orca kitty python-torch mlt python-torchaudio pyqt5 python-torchvision libpcsclite frida libtsduck rdircd python-pip python-bcrypt dbus-python lv2 electrum libplacebo python-xlib python-greenlet gst-python panda3d python-lxml seafile-client termux-gui-pm weechat manim termux-apt-repo libncnn autojump python-grpcio asciinema python-numpy python-contourpy asciidoc python-libsass hash-slinger python-msgpack pastebinit python-tldp srt2vobsub fetchmail libunbound libunbound python-sabyenc3 tizonia libllvm uftrace borgbackup units python-apsw python-skia-pathops gobject-introspection pygobject python-pillow profanity lilypond recoll calcurse vim-python python-scipy python-pynvim pathpicker boost libxml2 libxml2 libxml2 termux-create-package libsearpc pypy3 python-cryptography python-apt python-onnxruntime iwyu ledger jbig2enc glib emscripten sabnzbd rdiff-backup pycairo termux-gui-package matplotlib zeronet python-lameenc libtorrent-rasterbar python-pyarrow nala ranger 2ping gdb speechd uwsgi ytui-music
```
Python and 109 direct reverse dependencies.

**Comment by TomJo2000** [comment]
> I don't know if informing about it in a `postinst` would help?

Could be a good precaution

**Review by licy183 — APPROVED** [review]
LGTM. Thanks for working on this!

**Comment by fornwall** [comment]
> Got a full rebuild list based on rg 'DEPENDS.*python'

Did you run this @TomJo2000 ? Two things:
- `frida` (requires NDK 25) and `iwyu` (not compatible with llvm 19) won't build due to unrelated build failures (builds are broken on master as well )
- `./build-package.sh -i python-torchvision` and `./build-package.sh -i python-torchaudio` would break, as I didn't revbump `python-torch` in this PR, so they would download the old `python-torch` built for python 3.12. I just pushed a revbump of `python-torch` to this PR now to fix that.

I'm running the full rebuild now.

**Comment by TomJo2000** [comment]
> > Got a full rebuild list based on rg 'DEPENDS.*python'
> 
> Did you run this @TomJo2000 ? Two things:
> - `frida` (requires NDK 25) and `iwyu` (not compatible with llvm 19) won't build due to unrelated build failures (builds are broken on master as well )
> - `./build-package.sh -i python-torchvision` and `./build-package.sh -i python-torchaudio` would break, as I didn't revbump `python-torch` in this PR, so they would download the old `python-torch` built for python 3.12. I just pushed a revbump of `python-torch` to this PR now to fix that.
> 
> I'm running the full rebuild now.

I left the rebuilds running over night.
I haven't checked if anything else failed yet but at least `frida` and `iwyu` were expected.

**Comment by truboxl** [comment]
python-skia-pathops is also not buildable.

**Comment by TomJo2000** [comment]
`python-grpcio` fails in my local testing.

**Comment by fornwall** [comment]
> `python-grpcio` fails in my local testing.

What build error do you get?

It works for me locally. Check if cleaning out `rm ~/.termux-build` and running `./build-package.sh -i python-grpcio` works perhaps.

**Comment by fornwall** [comment]
Just added (in 1e28a6c1e595742b268774b5b84d9fb3bbf07b0c) the below message to `postinst`:

```sh
if [ -d $TERMUX_PREFIX/lib/python3.11/site-packages ]; then
    echo
    echo NOTE: The Termux python package has been updated to 3.12.
    echo NOTE: Run 'pkg upgrade' to update Termux system python packages.
    echo NOTE: Packages installed using pip needs to be re-installed.
    echo
fi
```

What do you think? Otherwise we're ready to merge this (and follow up revbumps). Any concerns before merging?

**Comment by TomJo2000** [comment]
> What build error do you get?
> 
> It works for me locally. Check if cleaning out `rm ~/.termux-build` and running `./build-package.sh -i python-grpcio` works perhaps.

Yep sorry, that one was a fluke.
Probably some conflicts with leftovers from an earlier build.
Just reran the build on a fresh container and it works fine.

Also finished up the rebuilds, nothing unexpected that hasn't been mentioned before,

**Comment by TomJo2000** [comment]
> Just added (in [1e28a6c](https://github.com/termux/termux-packages/commit/1e28a6c1e595742b268774b5b84d9fb3bbf07b0c)) the below message to `postinst`:
>  [...]
> ```shell
>     echo "NOTE: Run 'pkg upgrade' to update system python packages."
> ```

I guess we can't guarantee that people do a full upgrade eh?
So that note is probably good to keep.

<h1><em></em></h1>  

As more of a logistical clarification, `pip` modules required for packages are defined by the `TERMUX_PKG_PYTHON_TARGET_DEPS` variable; and installed/checked on installation/upgrade of the package in question.
e.g.
`nala` will try to install or upgrade these pip modules when it is installed or upgraded.
https://github.com/termux/termux-packages/blob/6d93c8787cab41343649f448737d9c31b0b3ef63/packages/nala/build.sh#L14
Which seems to be done as part of the `postinst` script.
https://github.com/termux/termux-packages/blob/6d93c8787cab41343649f448737d9c31b0b3ef63/packages/nala/build.sh#L31

<h1><em></em></h1>  

> What do you think? Otherwise we're ready to merge this (and follow up revbumps). Any concerns before merging?

LGTM.

**Review by truboxl — APPROVED** [review]

**Review by TomJo2000 — APPROVED** [review]

**Comment by TomJo2000** [comment]
TUR pull request to move Python 3.11:
- termux-user-repository/tur#1230

**Pull request merged**
