### PR TITLE
pulseaudio: Update from 14.2 to 16.1

### PR DESCRIPTION
**Pull request by tomty89**

### CODE REVIEW

**Comment by tomty89** [comment]
It seems that currently no static library will be emitted: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/679
And I don't suppose there's any necessity to patch it downstream for that? (I haven't been following the policy here on static library emission, if there's one.)

**Comment by Grimler91** [comment]
> It seems that currently no static library will be emitted
> And I don't suppose there's any necessity to patch it downstream for that?

Fine by me to skip the static lib.

You have maintained pulseaudio and contributed to many other packages for quite a while, so I sent you an invitation to join the termux organisation as a package maintainer, which would give you the power to merge updates like this one :)

**Comment by tomty89** [comment]
Thanks. I'll merge this once I have the time to bump the revision number of all the dependants. (Speaking of that, has any script been introduced to ease the work?)

**Comment by Grimler91** [comment]
> Thanks. I'll merge this once I have the time to bump the revision number of all the dependants. (Speaking of that, has any script been introduced to ease the work?)

We have the [revbump script](https://github.com/termux/termux-packages/blob/master/scripts/bin/revbump) for bumping the revision of given packages, but dependencies to bump have to be specified manually

**Pull request merged**
