### PR TITLE
graphviz: bump to 2.50.0

### PR DESCRIPTION
**Pull request by thunder-coding**

### CODE REVIEW

**Comment by Grimler91** [comment]
Note that graphviz suffers from https://github.com/termux/termux-packages/issues/8029, changing so that it is configured with cmake would be best for now I think

**Comment by thunder-coding** [comment]
The config file generated by `dot -c` is empty (`$PREFIX/lib/graphviz/config6`). This was also a problem when building with autotools. I had took a backup of my earlier config file, and dot seems to be able to generate ninja's graph.jpg

This needs to be resolved before merging this

**Comment by Grimler91** [comment]
Same issue as in https://github.com/termux/termux-packages/issues/5135, which was solved with the first version of the [lib-gvc-gvconfig.c.patch](https://github.com/termux/termux-packages/commit/693d2212e4c5ae5178b813a60247e6df2172051a)

**Comment by thunder-coding** [comment]
Thanks @Grimler91, this should now have been fixed. And here is the commit which caused this https://gitlab.com/graphviz/graphviz/-/commit/e9433e3289bd4650abdb91dda5f8932f262d9813 (Keeping it here for future reference for some other future contributor)

**Pull request merged**
