### PR TITLE
update to NDK r12b and Node.js 6.3.0

### PR DESCRIPTION
**Pull request by citrusui**
Just a few minor changes.

### CODE REVIEW

**Comment by citrusui** [comment]
Node.js has problems when updating from 6.2.2 to 6.3.0.

Additionally, APT is now at a higher version and needs more patches to work correctly.

**Comment by fornwall** [comment]
The `downloads.sourceforge.net` to `heanet.dl.sourceforge.net` changes, should they really be done? I thought that using downloads chose a mirror automatically.

**Comment by citrusui** [comment]
Yes, because SourceForge returns an HTML redirect instead of an actual file. In a web browser, this would be fine, but on the command line, this causes many builds to error out.

**Comment by fornwall** [comment]
Hm, SourceForge returns (in addition to the HTML content) a `HTTP 302 Found` redirect with a `Location` header pointing at a mirror.

Since the `termux_download` function uses the `-L/--location` option to `curl` this should work - do you get a reproducible error due to the redirect?

**Comment by citrusui** [comment]
You should probably change [this line](https://github.com/termux/termux-packages/blob/82620efb1ce4d40f63480f019f49fb1b4d5d9250/scripts/setup-android-sdk.sh#L37), as it's breaking the SDK/NDK download process.

I'm currently setting up termux and will report back when I'm done.

**Comment by citrusui** [comment]
When building `expect`, I get this error:

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
0
```

Must not be returning a .tar.gz for me.

**Comment by fornwall** [comment]
Hm, could you try deleting the cached tar.gz file:

    rm -Rf $HOME/.termux-build/expect/cache/*

and then try building expect again? It should work, perhaps you're cached file is corrupt.

**Comment by citrusui** [comment]
Seems to be working now. This PR can finally be closed.

**Pull request closed without merging**
