### PR TITLE
bump(main/google-glog): 0.7.0

### LINKED ISSUE #19272: Auto update failing for google-glog
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [google-glog](https://github.com/termux/termux-packages/blob/3c77b8be466a433462393ca2f64c6e1f591505fd/packages/google-glog) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating google-glog [Current version: 0.6.0]
INFO: package being updated to 0.7.0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 13165    0 13165    0     0  63942      0 --:--:-- --:--:-- --:--:-- 63942
100  178k    0  178k    0     0   782k      0 --:--:-- --:--:-- --:--:-- 7881k

You are about to commit these changes:

--------------------
diff --git a/packages/google-glog/build.sh b/packages/google-glog/build.sh
index a463c8f04..28b6ab6b2 100644
--- a/packages/google-glog/build.sh
+++ b/packages/google-glog/build.sh
@@ -2,10 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://github.com/google/glog
 TERMUX_PKG_DESCRIPTION="Logging library for C++"
 TERMUX_PKG_LICENSE="BSD 3-Clause"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="0.6.0"
-TERMUX_PKG_REVISION=1
+TERMUX_PKG_VERSION="0.7.0"
 TERMUX_PKG_SRCURL=https://github.com/google/glog/archive/v$TERMUX_PKG_VERSION.tar.gz
-TERMUX_PKG_SHA256=8a83bf982f37bb70825df71a9709fa90ea9f4447fb3c099e1d720a439d88bad6
+TERMUX_PKG_SHA256=375106b5976231b92e66879c1a92ce062923b9ae573c42b56ba28b112ee4cc11
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_DEPENDS="gflags, libc++"
 TERMUX_PKG_BUILD_DEPENDS="gflags-static"
--------------------

bump(main/google-glog): 0.7.0

Not committing to Git!

INFO: Trying to build package.
INFO: Package google-glog exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building google-glog for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  85095      0 --:--:-- --:--:-- --:--:-- 85285
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2462      0 --:--:-- --:--:-- --:--:--  2464
gpg: Signature made Sat 17 Feb 2024 01:53:50 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  36229      0 --:--:-- --:--:-- --:--:-- 36195
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2370      0 --:--:-- --:--:-- --:--:--  2373
gpg: Signature made Thu 15 Feb 2024 06:23:45 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  37228      0 --:--:-- --:--:-- --:--:-- 37167
100 13120  100 13120    0     0  37217      0 --:--:-- --:--:-- --:--:-- 37167
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0  11212      0 --:--:-- --:--:-- --:--:-- 11256
gpg: Signature made Sat 17 Feb 2024 12:34:21 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency libc++@26b if necessary...
Found libc++ in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libc/libc++/libc++_26b_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  297k  100  297k    0     0  3593k      0 --:--:-- --:--:-- --:--:-- 3629k
extracting libc++ to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency gflags@2.2.2-9 if necessary...
Found gflags in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/gflags/gflags_2.2.2-9_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 73560  100 73560    0     0   133k      0 --:--:-- --:--:-- --:--:--  133k
extracting gflags to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency gflags-static@2.2.2-9 if necessary...
Found gflags-static in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/gflags-static/gflags-static_2.2.2-9_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 54300  100 54300    0     0    98k      0 --:--:-- --:--:-- --:--:--   98k
100 54300  100 54300    0     0    98k      0 --:--:-- --:--:-- --:--:--   98k
extracting gflags-static to /home/builder/.termux-build/_cache-aarch64...
Downloading https://github.com/google/glog/archive/v0.7.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  178k    0  178k    0     0   787k      0 --:--:-- --:--:-- --:--:--  787k
ERROR: SOVERSION guard check failed.
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-02-17 18:22:39 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/7943388574">7943388574</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes #19272

### CODE REVIEW

**Comment by Biswa96** [comment]
librime build failure is reported in upstream https://github.com/rime/librime/issues/823

**Comment by Biswa96** [comment]
yay, all are green \o/

**Comment by 2096779623** [comment]
Please resole conflicts.

**Comment by Biswa96** [comment]
I have rebased the changes.

**Pull request merged**
