### PR TITLE
mariadb: Blacklist 32-bit arches due to off_t

### PR DESCRIPTION
**Pull request by fornwall**
@vishalbiswas What do you say about doing this for now and enable it while we're awaiting unified headers and `-D_FILE_OFFSET_BITS=64` support?

### CODE REVIEW

**Comment by vishalbiswas** [comment]
Okay! But is it tested on i686. I am only guessing that it may be held back by off_t. I may be wrong.

Right now termux_create_debscripts does nothing

**Comment by fornwall** [comment]
> Okay! But is it tested on i686? I am only guessing that it may be held back by off_t. I may be wrong.

Right, i686 has the same 32-bit off_t problem as arm.

> Right now termux_create_debscripts does nothing

Hm, I guess it would be nice to setup a database there.

**Comment by vishalbiswas** [comment]
> Right, i686 has the same 32-bit off_t problem as arm.
What I meant was, does the problem with arm is confirmed to be because of off_t inconsistencies?

**Comment by fornwall** [comment]
@vishalbiswas Aha, right! I just assumed blame on 32-bit off_t, but I guess we would need a closer investigation to verify (if it works with `-D_FILE_OFFSET_BITS=64` support after the NDK r15 release I guess that is a good indication that this was the problem).

**Comment by vishalbiswas** [comment]
Delete this branch now?

**Comment by fornwall** [comment]
@vishalbiswas Thanks, it's deleted now!

**Pull request merged**
