### PR TITLE
libllvm: update to 11.1.0

### PR DESCRIPTION
**Pull request by landfillbaby**
let's see if this works

### CODE REVIEW

**Comment by landfillbaby** [comment]
i did some testing and it all runs well :)

**Review by buttaface — APPROVED** [review]
Rust will need to be rebuilt after this is updated, @its-pointless, should work fine? The only other Termux package built against this is iwyu, but it's linked statically so no hurry to update it. Swift uses its own forked LLVM, so that's not an issue, but it does import some of the clang headers, so I will bump that too once this is in.

**Comment by landfillbaby** [comment]
ok i just bumped rust too

**Comment by landfillbaby** [comment]
and then we have to woth on rust 1.50

**Comment by wingfancy** [comment]
How to install 'LLVMPolly.so' with LLVM 11.1.0?

**Comment by buttaface** [comment]
> How to install 'LLVMPolly.so' with LLVM 11.1.0?

`pkg install libpolly`

**Pull request merged**
