### PR TITLE
Add: rz-pm & rizin improvements

### PR DESCRIPTION
**Pull request by AbhiTheModder**
**Add:** 
- `rizin` package manager(`rz-pm`) for termux

**Update:** 
- `rizin` to recommend installation of `rz-pm`
- There wasn't a need for suggestions so removed them

### CODE REVIEW

**Comment by TomJo2000** [comment]
That's likely not gonna be useful in a Termux context if it installs software not compiled for a Termux environment.

**Comment by AbhiTheModder** [comment]
> That's likely not gonna be useful in a Termux context if it installs software not compiled for a Termux environment.
@TomJo2000 Thanks for review again :)
It installs for every system... similar to radare2 `r2pm`.

**Comment by TomJo2000** [comment]
> It installs for every system... similar to radare2 `r2pm`.

Which we also don't package.
As a matter of fact, `rz-pm` doesn't seem to be packaged anywhere aside from its GitHub page.

**Comment by AbhiTheModder** [comment]
> > It installs for every system... similar to radare2 `r2pm`.
> 
> Which we also don't package. As a matter of fact, `rz-pm` doesn't seem to be packaged anywhere aside from its GitHub page.

Tried through `doc` bulding guide with system env `Go` only builds for that system
Yeah, but is it bad idea if I tried to do a packaging for termux myself. 🤔😓

**Pull request closed without merging**
