### PR TITLE
libpulseaudio: process_msg/asyncmsgq refactor for aaudio sink

### LINKED ISSUE #3338: Pulseaudio frequently crashes
**Problem description**
Pulseaudio crashes frequently with the following error:
```
2019-02-12_09:04:16.72759 E: [AudioTrack] memblockq.c: Assertion 'bq->n_blocks >= 1' failed at /home/builder/.termux-build/libpulseaudio/src/src/pulsecore/memblockq.c:183, function void drop_block(pa_memblockq *, struct list_item *)(). Aborting.
```

**Steps to reproduce**
Listening to Music with MPD. It happens about once an hour, maybe? So it's quite tricky to reproduce

**Expected behavior**
Pulseaudio doesn't crash

**Additional information**
Updatable packages:
All packages up to date
System information:
Linux localhost 3.4.0-perf-g284400aea4b #1 SMP PREEMPT Mon Feb 4 11:41:05 UTC 2019 armv7l Android
Termux-packages arch:
arm
Android version:
8.1.0
Device manufacturer:
Fairphone
Device model:
FP2

### PR DESCRIPTION
**Pull request by tomty89**
Fixes #3338 for the aaudio sink. @Neo-Oli Would be great if you can test it out as well.

Haven't tested if the handle for `AAUDIO_ERROR_DISCONNECTED` still works as before yet. Will test when I have time.

### CODE REVIEW

**Comment by Neo-Oli** [comment]
@tomty89 Unfortunately I'm still getting the same kind of errors and even a segfault now.
```
I: [pulseaudio] sink-input.c:     module-stream-restore.id = "sink-input-by-media-role:music"
I: [pulseaudio] protocol-native.c: Requested tlength=250.00 ms, minreq=20.00 ms
D: [pulseaudio] protocol-native.c: Traditional mode enabled, modifying sink usec only for compat with minreq.
D: [pulseaudio] protocol-native.c: Requested latency=210.00 ms, Received latency=20.00 ms
D: [pulseaudio] memblockq.c: memblockq requested: maxlength=4194304, tlength=88200, base=8, prebuf=81152, minreq=7056 maxrewind=0
D: [pulseaudio] memblockq.c: memblockq sanitized: maxlength=4194304, tlength=88200, base=8, prebuf=81152, minreq=7056 maxrewind=0
I: [pulseaudio] protocol-native.c: Final latency 270.00 ms = 210.00 ms + 2*20.00 ms + 20.00 ms
E: [AudioTrack] sink-input.c: Assertion 'PA_SINK_INPUT_IS_LINKED(i->thread_info.state)' failed at /home/builder/.termux-build/libpulseaudio/src/src/pulsecore/sink-input.c:1046, function void pa_sink_input_drop(pa_sink_input *, size_t)(). Aborting.
```
```
D: [AudioTrack] sink-input.c: dropping 320
D: [AudioTrack] sink-input.c: peek
D: [AudioTrack] sink-input.c: peeking 640
D: [AudioTrack] sink-input.c: dropping 640
D: [AudioTrack] sink-input.c: peek
D: [AudioTrack] sink-input.c: peeking 960
D: [AudioTrack] sink-input.c: dropping 960
D: [AudioTrack] sink-input.c: peek
D: [AudioTrack] sink-input.c: peeking 960
D: [AudioTrack] sink-input.c: dropping 960
D: [pulseaudio] module-suspend-on-idle.c: Sink AAudio_sink becomes idle, timeout in 5 seconds.
E: [AudioTrack] sink.c: Assertion '!s->thread_info.rewind_requested' failed at /home/builder/.termux-build/libpulseaudio/src/src/pulsecore/sink.c:1378, function void pa_sink_render_into_full(pa_sink *, pa_memchunk *)(). Aborting.
zsh: abort      pulseaudio -vvv
```
```
D: [AudioTrack] sink-input.c: peek
D: [AudioTrack] sink-input.c: pushing 956
D: [AudioTrack] sink-input.c: peeking 956
D: [AudioTrack] sink-input.c: dropping 956
D: [AudioTrack] sink-input.c: peek
D: [AudioTrack] protocol-native.c: Implicit underrun of 'PulseAudio'
D: [AudioTrack] sink-input.c: peeking 960
D: [AudioTrack] sink-input.c: dropping 960
D: [pulseaudio] module-suspend-on-idle.c: Sink AAudio_sink becomes idle, timeout in 5 seconds.
D: [AudioTrack] sink-input.c: peek
zsh: segmentation fault  pulseaudio -vvv
```

**Comment by tomty89** [comment]
I do notice I made a mistake, but I am not sure if it has anything to do with the errors you see, will update soon.

As for the segfault, try to add `no_close_hack=true` after `load-module module-aaudio-sink`. On some Android builds, there's a bug that segfault will always be triggered as long as you call `AAudioStream_close` (but it may not happen right away, instead it happen when you switch to another app).

**Comment by tomty89** [comment]
It seems to me that using a seperate asyncmsgq for rendering messages is wrong, as that means there will be a seperate mutex lock for them. So now I just use the same asyncmsgq for them, and that probably needs to be applied to #3359 as well.

Also now `AAudioStream_requestStart` are called via `PA_SINK_MESSAGE_SET_STATE`/`set_state_in_io_thread` to avoid rendering from actually being started before `s->thread_info.state` is changed from `PA_SINK_INIT` to a linked state.

Some more work (make use of `AAudioStream_waitForStateChange` for `AAudioStream_requestStop`) still needs to be done for the case when the sink is being unlinked.

**Comment by tomty89** [comment]
@Neo-Oli I don't think you had been testing the right build as the messages were prefixed with `[AudioTrack]` instead of `aaudio-sink`, which means `pa_sink_render_full_into` was still called directly in the aaudio callback/thread.

#3338 should have been fixed as long as we do render via process_msg. From what I understand now it doesn't even have anything to do with the asyncmsgq mutex but the fact that the messages are queued and processed one by one during `pa_rtpoll_run`. That's why when locking the mutex and our rendering function did nothing and why we can have multiple asyncmsgq / pa_rtpoll_item.

You might still bump into certain assertion error with the aaudio sink regarding the sink link state (as with the current code the sink could be unlinked before rendering stopped / after rendering started), but not anything regarding sink input / rewind.

P.S. I don't think you have bumped into any problem anymore with the sles sink, have you?

**Comment by tomty89** [comment]
Superseded by #3391.

**Comment by Neo-Oli** [comment]
@tomty89 Weird. I thought I did everything correctly. But I pulled it into the other pull request, so maybe I did something wrong doing that. Since #3391 has now been merged I will just test again once that update is available officially. I haven't had any more issues with the sles sink. I've been using (and logging) it for a week now.

**Comment by Neo-Oli** [comment]
@tomty89 I am unable to test this at the moment because I am affected by #3441, as MPD will crash long before pulseaudio would I did notice that pulseaudio will now freeze and die when I disconnect my bluetooth headphones while the aaudio-sink is enabled.

**Pull request closed without merging**
