### PR TITLE
Bump `nodejs` to 16.3.0

### PR DESCRIPTION
**Pull request by thunder-coding**
PS: I am also gonna try building for `x86_64`

### CODE REVIEW

**Comment by thunder-coding** [comment]
On Android `nameser` is available as [`arpa/nameser`](https://android.googlesource.com/platform/bionic/+/master/libc/include/arpa/nameser.h)

**Comment by truboxl** [comment]
Probably a stretch to ask: maybe check if x86_64 can be built as well? Thanks

**Comment by thunder-coding** [comment]
Probably something related to this https://github.com/nodejs/node/issues/36287

**Comment by thunder-coding** [comment]
Should I blacklist the `i868` arch

**Comment by suhan-paradkar** [comment]
@thunder-coding Check out #6973

**Comment by thunder-coding** [comment]
So we need to wait for these errors to be patched on upstream?

**Comment by suhan-paradkar** [comment]
> So we need to wait for these errors to be patched on upstream?

I guess so...

**Comment by thunder-coding** [comment]
Lets hope this patch fixes build on some archs

**Pull request closed without merging**
