### PR TITLE
new package: ani-cli

### LINKED ISSUE #9665: [Package]: ani-cli
### Package description

A cli tool to browse and play anime

### Home page URL

https://github.com/pystardust/ani-cli

### Source code URL

https://github.com/pystardust/ani-cli

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xtkoba**
Closes #9665.

### CODE REVIEW

**Comment by aicynide** [comment]
I forgot to tell you 1 thing, there's a script to install it on termux

```pkg install git termux-tools ncurses-utils openssl-tool -y
git clone https://github.com/pystardust/ani-cli && cd ani-cli
cp ani-cli $PREFIX/bin/ani-cli
echo 'am start --user 0 -a android.intent.action.VIEW -d "$2" -n is.xyz.mpv/.MPVActivity' > $PREFIX/bin/mpv
chmod +x $PREFIX/bin/mpv
```

**Comment by xtkoba** [comment]
It overwrites `$PREFIX/bin/mpv` which is not acceptable.

**Comment by aicynide** [comment]
I got a idea.
let's rename `mpv` to `mpv-ac` 

And just change 1 word in `ani-cli` using sed. Change player_fn "mpv-ac" in line no. 475 https://github.com/pystardust/ani-cli/blob/master/ani-cli#L475
Problem solved

**Comment by xtkoba** [comment]
That should go upstream I suppose.

**Comment by aicynide** [comment]
@xtkoba can you make this script `echo 'am start --user 0 -a android.intent.action.VIEW -d "$2" -n is.xyz.mpv/.MPVActivity' > $PREFIX/bin/mpv-ac` dependency  instead of termux mpv package please? It will use mpv android app then where we can watch video

**Pull request merged**
