### PR TITLE
Add package libusb

### PR DESCRIPTION
**Pull request by Auxilus**
https://github.com/termux/termux-packages/issues/1714

### CODE REVIEW

**Comment by stainslav** [comment]
@Auxilus are you on telegram Whatsapp or Facebook?

**Comment by Auxilus** [comment]
I'd prefer gitter

**Comment by stainslav** [comment]
What's your gitter?

**Comment by Auxilus** [comment]
Same as github `Auxilus`

**Comment by joakim-noah** [comment]
Already in disabled packages, see #2175.

**Comment by Grimler91** [comment]
I've added the package to the root repo, so closing this.

**Pull request closed without merging**
