### PR TITLE
add(main): new package openmp

### PR DESCRIPTION
**Pull request by T-Dynamos**
https://github.com/termux/termux-packages/pull/11800#issuecomment-1236040007

### CODE REVIEW

**Comment by T-Dynamos** [comment]
Any ideas? which  package causing this error
```
-- Found FFI: /data/data/com.termux/files/usr/lib/libffi.so  
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /data/data/com.termux/files/usr/lib/libtinfo.so  
-- Found ZLIB: /data/data/com.termux/files/usr/lib/libz.so (found version "1.2.12") 
-- Found LibXml2: /data/data/com.termux/files/usr/lib/libxml2.so (found version "2.9.14") 
CMake Error at /data/data/com.termux/files/usr/lib/cmake/llvm/LLVMExports.cmake:1629 (message):
  The imported target "LLVMDemangle" references the file

     "/data/data/com.termux/files/usr/lib/libLLVMDemangle.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/data/data/com.termux/files/usr/lib/cmake/llvm/LLVMExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /data/data/com.termux/files/usr/lib/cmake/llvm/LLVMConfig.cmake:329 (include)
  libomptarget/cmake/Modules/LibomptargetGetDependencies.cmake:29 (find_package)
  libomptarget/CMakeLists.txt:31 (include)


-- Configuring incomplete, errors occurred!
See also "/home/builder/.termux-build/openmp/build/CMakeFiles/CMakeOutput.log".
See also "/home/builder/.termux-build/openmp/build/CMakeFiles/CMakeError.log".
```

**Comment by 2096779623** [comment]
```bash
~ $ apt-file search libLLVMDemangle.a
libllvm-static: /data/data/com.termux/files/usr/lib/libLLVMDemangle.a
~ $
```

**Comment by sylirre** [comment]
libomp library is already available. I guess it is a part of our LLVM, so close this PR.

**Review by sylirre — CHANGES_REQUESTED** [review]
libomp (OpenMP) library is already available. It is a part of `clang` package and exists as `$PREFIX/lib/libomp.a`. You should look how to link with it instead of this pull request.

**Comment by T-Dynamos** [comment]
I will try.

**Pull request closed without merging**
