### PR TITLE
Add package : ncrack

### PR DESCRIPTION
**Pull request by Auxilus**

### CODE REVIEW

**Comment by stephengroat** [comment]
@Auxilus I'm getting these 2 errors, seem to be from `openssl`. are you seeing the same?

```
In file included from strlcpy.c:21:
In file included from ./includes.h:190:
In file included from ./entropy.h:30:
In file included from ./buffer.h:28:
In file included from ./sshbuf.h:29:
In file included from /data/data/com.termux/files/usr/include/openssl/bn.h:134:
In file included from /data/data/com.termux/files/usr/include/openssl/crypto.h:120:
/home/builder/.termux-build/_lib/15.2-aarch64-21-v14/bin/../sysroot/usr/include/stdlib.h:206:5: error: expected identifier or '('
int mblen(const char*, size_t) __INTRODUCED_IN(26) __VERSIONER_NO_GUARD;
    ^
./openbsd-compat.h:241:23: note: expanded from macro 'mblen'
# define mblen(x, y)    (1)
                         ^
In file included from strlcpy.c:21:
In file included from ./includes.h:190:
In file included from ./entropy.h:30:
In file included from ./buffer.h:28:
In file included from ./sshbuf.h:29:
In file included from /data/data/com.termux/files/usr/include/openssl/bn.h:134:
In file included from /data/data/com.termux/files/usr/include/openssl/crypto.h:120:
/home/builder/.termux-build/_lib/15.2-aarch64-21-v14/bin/../sysroot/usr/include/stdlib.h:206:5: error: expected ')'
./openbsd-compat.h:241:23: note: expanded from macro 'mblen'
# define mblen(x, y)    (1)
                         ^
/home/builder/.termux-build/_lib/15.2-aarch64-21-v14/bin/../sysroot/usr/include/stdlib.h:206:5: note: to match this '('
./openbsd-compat.h:241:22: note: expanded from macro 'mblen'
# define mblen(x, y)    (1)
                        ^
2 errors generated.
```

**Comment by Auxilus** [comment]
Ye im getting those same errors too

**Comment by Auxilus** [comment]
Should I just comment out 'em?

**Comment by stephengroat** [comment]
not a 100% fix. after that, i get this. trying to track down right now

```
In file included from cleanup.c:23:
/home/builder/.termux-build/_lib/15.2-aarch64-21-v14/bin/../sysroot/usr/include/unistd.h:108:20: error: expected ')'
    __attribute__((__sentinel__(1)));
                   ^
1 error generated.
```

**Comment by Auxilus** [comment]
@stephengroat please let me know how it goes cause looks like I reached my limit, thanks

**Pull request closed without merging**
