### PR TITLE
mdp: Fix Android 7.x non-ASCII characters issue

### LINKED ISSUE #2497: mdp doesn't support non-ascii characters
I just tried the new mdp package for termux. It doesn't display non-ascii characters like "äöü" or other unicode characters, even though according to the [demo](https://cloud.githubusercontent.com/assets/2237222/5810237/797c494c-a043-11e4-9dbd-959cab4055fa.gif) at the mdp repository it should work.

### PR DESCRIPTION
**Pull request by xtkoba**
Fixes #2497.

### CODE REVIEW

**Comment by landfillbaby** [comment]
this doesn't actually link against libandroid-support, just adds it as a package dependency. if it's working it's because of #8069. same with #8092 and #8093

**Comment by xtkoba** [comment]
Does link, due to https://github.com/termux/termux-packages/blob/09ecfc3c2670a73985bf0e066960fcae6929d61b/scripts/build/termux_step_setup_toolchain.sh#L88-L91

**Comment by xtkoba** [comment]
And indeed,

```
$ readelf -Wa bin/mdp | grep NEEDED
 0x00000001 (NEEDED)                     Shared library: [libncursesw.so.6]
 0x00000001 (NEEDED)                     Shared library: [libandroid-support.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
```

**Comment by landfillbaby** [comment]
oh oops i forgot! you're right

**Pull request merged**
