### PR TITLE
[WIP] mpv: Update from 0.29.1 to 0.30.0

### PR DESCRIPTION
**Pull request by tomty89**

### CODE REVIEW

**Comment by xeffyr** [comment]
Requires https://github.com/termux/x11-packages/blob/master/packages/mpv-x/wscript_build.py.patch

**Comment by tomty89** [comment]
@xeffyr I will come up with a more proper fix (which I will apply here and submit to upstream)

**Comment by tomty89** [comment]
Uhm, this shouldn't be merged as it wasn't updated to use the same approach as the one for the android-5 branch...

**Comment by xeffyr** [comment]
Merged it because it works.

> as the one for the android-5 branch...

Isn't https://github.com/termux/termux-packages/pull/4477/files#diff-7319979d049a92ae5945b0de27ded7cc same as https://github.com/termux/termux-packages/pull/4478/files#diff-faa1b701e29428852fc775852f609db7 ?

**Comment by tomty89** [comment]
Hmm, looks like I have a bad sector...sorry.
Thanks for merging :D

**Pull request merged**
