### PR TITLE
tealdeer: Downgrade `app_dirs` cargo dependency

### PR DESCRIPTION
**Pull request by PeroSar**
Previously, running example: `tldr ls`, shows the following error:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/ndk-glue-0.4.0/src/lib.rs:59:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Downgrading `app_dirs` fixes this issue.

Signed-off-by: PeroSar <perosar1111@gmail.com>

### CODE REVIEW

**Comment by Grimler91** [comment]
Looks like this was fixed in https://github.com/app-dirs-rs/app_dirs2/commit/35a9b19487cf9173549ef5c246d60fcd65858a9f, so upgrading the app_dirs2 dependency to 2.4.0 should hopefully work as well. 

Have you tried upgrading it?

**Comment by PeroSar** [comment]
> Looks like this was fixed in [app-dirs-rs/app_dirs2@35a9b19](https://github.com/app-dirs-rs/app_dirs2/commit/35a9b19487cf9173549ef5c246d60fcd65858a9f), so upgrading the app_dirs2 dependency to 2.4.0 should hopefully work as well.
> 
> Have you tried upgrading it?

After upgrading `app_dirs2`, it fails at jni crate:
```
Compiling jni v0.19.0
error[E0425]: cannot find value `EXPECTED_JVM_FILENAME` in this scope
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/jni-0.19.0/build.rs:102:25
    |
102 |         if file_name == EXPECTED_JVM_FILENAME {
    |                         ^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

**Comment by Grimler91** [comment]
> After upgrading `app_dirs2`, it fails at jni crate:
> 
> ```
> Compiling jni v0.19.0
> error[E0425]: cannot find value `EXPECTED_JVM_FILENAME` in this scope
>    --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/jni-0.19.0/build.rs:102:25
>     |
> 102 |         if file_name == EXPECTED_JVM_FILENAME {
>     |                         ^^^^^^^^^^^^^^^^^^^^^ not found in this scope
> ```
> 
> after patching `build.rs` file, it compiles but running example: `tldr ls` still doesn't work:
> 
> ```
> thread 'main' panicked at 'android context was not initialized', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/ndk-context-0.1.0/src/lib.rs:72:30
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

Hmm, was this when compiling on device? It seems to work for at least aarch64 when compiling in docker image, I pushed another commit to try it in this PR. 

Thanks for looking into the issue, greatly appreciated :+1:

**Comment by Grimler91** [comment]
Right, no, sorry, it gives the same ndk-context-0.1.0 error when run on device

**Comment by PeroSar** [comment]
> Hmm, was this when compiling on device?

yes, i was compiling on device

> Right, no, sorry, it gives the same ndk-context-0.1.0 error when run on device

true, so, downgrade?

**Comment by Grimler91** [comment]
> true, so, downgrade?

Seems like the only solution for now. Seems like https://github.com/rust-windowing/android-ndk-rs/ would have to be made termux-friendly for this to work out of the box

**Comment by Grimler91** [comment]
Merged: https://github.com/termux/termux-packages/commit/ff9aaad94b27feafc5d0639c78bec3103d7a5850, thanks!

**Pull request closed without merging**
