### PR TITLE
adwaita-icon-theme-legacy: Fix license directory conflict with adwaita-icon-theme

### PR DESCRIPTION
**Pull request by Biswa96**
It's my mistake. I didn't notice it in earlier PR :bowing_man:

### CODE REVIEW

**Comment by truboxl** [comment]
Why do we have adwaita-icon-theme-legagy in the first place?

**Comment by Biswa96** [comment]
> Why do we have adwaita-icon-theme-legacy in the first place?

https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/288

**Comment by TomJo2000** [comment]
> Why do we have adwaita-icon-theme-legacy in the first place?

Because adwaita is a fundamentally broken theme, and this is the solution they can live with for making it work for non-GNOME applications.

**Comment by truboxl** [comment]
Just update the version also. 43 is old...

**Comment by Biswa96** [comment]
> Just update the version also. 43 is old...

It was done in previous PR.

**Comment by truboxl** [comment]
I think this conflict file issue also worth making another CI check...

**Comment by TomJo2000** [comment]
First grimler now you?
Guess I'm writing more linter checks today.

**Comment by Biswa96** [comment]
> Not exactly sure how you would lint that though.

That could be possible by actually install the packages with apt in termux environment after building.

**Comment by TomJo2000** [comment]
> Just update the version also. 43 is old...

@truboxl GNOME 43 was the last version that shipped a FDO compliant version of Adwaita.
So Debian took it, cut out the parts that are missing in the newer releases, slapped a `-legacy` on the package and shipped it as a dependency for adwaita-icon-theme.
What's changed is that *now* `adwaita-icon-theme-legacy` is an official upstream GNOME project that ships the compatibility files for adwaita.
Although "-legacy" in GNOME-ish means, compatibility for non-GNOME applications using FDO icon themes.

**Pull request merged**
