### PR TITLE
bmon: added package and its dependencies (libconfuse and libnl3)

### PR DESCRIPTION
**Pull request by vaites**
I created a builder for bmon and its dependencies:
> bmon is a monitoring and debugging tool to capture networking related statistics and prepare them visually in a human friendly way. It features various output methods including an interactive curses user interface and a programmable text output for scripting.

Is very interesting for monitoring wireless traffic using it as hotspot (choose rmnetX interfaces). Interesting too if you download things in background or if you use a proxy like #406 (choose wlan0 interface)

screenshot_20170209-003258

### CODE REVIEW

**Comment by fornwall** [comment]
Nice!

About libnl3, it seems that the homepage https://www.infradead.org/~tgr/libnl/
  is dead and https://github.com/thom311/libnl should be used instead. (see http://lists.infradead.org/pipermail/libnl/2016-August/002201) and that https://github.com/thom311/libnl should be used. 

On the new site the latest release is 3.2.29 (https://github.com/thom311/libnl/releases) - could you update to point to the newer github site for TERMUX_PKG_HOMEPAGE and TERMUX_PKG_SRCURL, and bump the version to 3.2.29?

**Comment by vaites** [comment]
Done: fixed homepage and download URL. Also bumped version and verified
compilation.

Many times I take a look at Debian packages and get some info from there
(homepage, dependencies...). Will take a look deeper next time.

**Comment by fornwall** [comment]
Thanks, looks nice! I'll try it out and hopefully merge it later today.

I've added upstream pull requests to include the patches you have made:

https://github.com/tgraf/libnl/pull/12
https://github.com/tgraf/bmon/pull/55

so hopefully we can remove our local patches from the next release of the respective packages!

**Comment by fornwall** [comment]
The packages are now built and availalbe for installation:

    apt update && apt install bmon

I renamed `libnl3` to `libnl`, as we try to avoid having version numbers in package names (in contrast to debian here).

**Comment by vaites** [comment]
Thanks. Will avoid versioning in new packages...

**Pull request merged**
