### PR TITLE
add(x11): new package lapce

### PR DESCRIPTION
**Pull request by T-Dynamos**

### CODE REVIEW

**Comment by T-Dynamos** [comment]
```
    Compiling process_path v0.1.4
error[E0433]: failed to resolve: use of undeclared crate or module `os`
  --> /home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/process_path-0.1.4/src/lib.rs:58:5
   |
58 |     os::get_executable_path()
   |     ^^ use of undeclared crate or module `os`

error[E0433]: failed to resolve: use of undeclared crate or module `nix`
  --> /home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/process_path-0.1.4/src/lib.rs:71:9
   |
71 |         nix::get_dylib_path()
   |         ^^^ use of undeclared crate or module `nix`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `process_path` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```
Any solutions?

**Comment by ifurther** [comment]
Maybe should patch the `src/lib.rs` file with `[cfg(target_os = "android")]`https://github.com/wesleywiser/process_path/blob/33c2bdbd29d040674b82c1aa8e29e5c6941a1ea5/src/lib.rs#L28

**Comment by T-Dynamos** [comment]
Suppose if patch the forked repo but how to specify patched `process_path`

https://github.com/lapce/lapce/issues/1064

**Comment by ifurther** [comment]
similar [tihs](https://github.com/termux/termux-packages/blob/b312b033abcdc5d403f31fc25d5d3324fb660b7d/packages/below/nix-0.22.0-src-sys-statfs.rs.diff)

**Comment by ifurther** [comment]
Maybe should update the version

**Comment by xtkoba** [comment]
Looks like abandoned. @T-Dynamos Still work in progress?

**Comment by T-Dynamos** [comment]
```

**Comment by T-Dynamos** [comment]
```
error: failed to run custom build command for `freetype-sys v0.13.1`

Caused by:
  process didn't exit successfully: `/home/builder/.termux-build/lapce/src/target/release/build/freetype-sys-585a48904e23c9d0/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_aarch64-linux-android = None
  CMAKE_TOOLCHAIN_FILE_aarch64_linux_android = None
  TARGET_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-linux-android = None
  CMAKE_GENERATOR_aarch64_linux_android = None
  TARGET_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_aarch64-linux-android = None
  CMAKE_PREFIX_PATH_aarch64_linux_android = None
  TARGET_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-linux-android = None
  CMAKE_aarch64_linux_android = None
  TARGET_CMAKE = None
  CMAKE = None
  running: "cmake" "/home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/freetype-sys-0.13.1/freetype2" "-DWITH_BZip2=OFF" "-DWITH_HarfBuzz=OFF" "-DWITH_PNG=OFF" "-DWITH_ZLIB=OFF" "-DCMAKE_INSTALL_PREFIX=/home/builder/.termux-build/lapce/src/target/aarch64-linux-android/release/build/freetype-sys-7a00e94a84aa9380/out" "-DCMAKE_C_FLAGS= -DANDROID -ffunction-sections -fdata-sections -fPIC -fstack-protector-strong -I/data/data/com.termux/files/usr/include" "-DCMAKE_C_COMPILER=/home/builder/.termux-build/_cache/android-r25b-api-24-v3/bin/aarch64-linux-android-clang" "-DCMAKE_CXX_FLAGS= -DANDROID -ffunction-sections -fdata-sections -fPIC -fstack-protector-strong" "-DCMAKE_CXX_COMPILER=/home/builder/.termux-build/_cache/android-r25b-api-24-v3/bin/aarch64-linux-android-clang++" "-DCMAKE_ASM_FLAGS= -DANDROID -ffunction-sections -fdata-sections -fPIC -fstack-protector-strong -I/data/data/com.termux/files/usr/include" "-DCMAKE_ASM_COMPILER=/home/builder/.termux-build/_cache/android-r25b-api-24-v3/bin/aarch64-linux-android-clang" "-DCMAKE_BUILD_TYPE=Release"

  --- stderr
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

  build script failed, must exit now', /home/builder/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by 2096779623** [comment]
`termux_setup_cmake` .

**Review by PraveenNanda124 — COMMENTED** [review]
Great work

**Pull request closed without merging**
