### PR TITLE
Bump Neovim

### PR DESCRIPTION
**Pull request by xyllery-7**

### CODE REVIEW

**Comment by xyllery-7** [comment]
Builds fine (until uploading, obviously). IDK why Github Actions' commit failed

**Comment by Grimler91** [comment]
Why does it need to be bumped? 0.6.0 seem to be available from repo: https://packages.termux.org/apt/termux-main/pool/main/n/neovim/

**Comment by sk0kanik** [comment]
> Why does it need to be bumped? 0.6.0 seem to be available from repo: https://packages.termux.org/apt/termux-main/pool/main/n/neovim/

maybe 0.6.0 was uploaded manually. github action [failed to build neovim for aarach64](https://github.com/termux/termux-packages/actions/runs/1522344555).

**Comment by thunder-coding** [comment]
Closing for the same reason as said by Grimler

**Comment by xyllery-7** [comment]
Sorry, forgot to apt update and thought something failed in the build

**Pull request closed without merging**
