### PR TITLE
FIX TOOLS: revert go to 1.16

### PR DESCRIPTION
**Pull request by MedzikUser**
I changed because there is a problem with compilation of tools. #7356

### CODE REVIEW

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#downgrading-the-package-or-changing-versioning-scheme, adjust your pull request accordingly.

**Comment by MedzikUser** [comment]
> https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#downgrading-the-package-or-changing-versioning-scheme, adjust your pull request accordingly.

that was it?

**Comment by xeffyr** [comment]
You have bumped epoch, but also reverted your version change. See https://github.com/termux/termux-packages/pull/7373/commits/7a988b6a6fed3e22145addbb73496437ae1480e1 on how it should look like.

**Comment by NatoBoram** [comment]
I managed to build `go1.17`

* https://github.com/golang/go/issues/47727#issuecomment-903309804

**Pull request merged**
