### PR TITLE
Qemu: add new package (system emulation only)

### PR DESCRIPTION
**Pull request by phcoder**
New set of packages: qemu. It doesn't have SDL support, but it works fine with serial output, VNC and Spice.

### CODE REVIEW

**Comment by phcoder** [comment]
The build failed because test suite stops after 4MiB of logs. With all the dependencies, it's too short

**Comment by its-pointless** [comment]
Is there a reason qemu compiles with 1 make process?
make -j ${TERMUX_MAKE_PROCESSES} 
kind of speeds things up somewhat

**Comment by phcoder** [comment]
@its-pointless thank you for suggestion. Updated branch

**Comment by its-pointless** [comment]
Also on TERMUX_ARCH=i686 the build fails 
/home/builder/.termux-build/qemu-common/src/include/exec/cpu-defs.h:28:10: fatal error: 'tcg-target.h' file not found

**Comment by phcoder** [comment]
@its-pointless fixed compilation for all architectures. I moved user emulation to separate PR as it needs more work to compile on i686

**Comment by its-pointless** [comment]
Ok iv uploaded a builds to my repo if anyone else wants to test.

**Comment by xeffyr** [comment]
I have added **qemu** (both system and user emulation) to [termux/x11-packages](https://github.com/termux/x11-packages/tree/master/packages/qemu-system-x86_64).

**Pull request closed without merging**
