### PR TITLE
haskell toolchain

### PR DESCRIPTION
**Pull request by MrAdityaAlok**
- refactor(ghc-libs): rename ghc to ghc-libs
  - seperate ghc libraries from ghc bins
  - enable dynamic libs for ghc
    - ghc-libs is further seperated into static and dynamic packages
    - enabling dynamic support will reduce package size as well as boost there
      performance on device.
- feat(ghc): enable cross-compiling haskell packages on CI
- feat(build scripts): allow packages to define extra static split patterns
- feat: add cabal-install package
- chore(codeowners): add packages maintained by me

#### Packaging policy for haskell packages

- I am going with [ArchLinux policy](https://wiki.archlinux.org/title/Haskell_package_guidelines) to only provide dynamic libs and executables by default, except that
  there is no seperate ghc-pkg database for static packages.

  - Since there is no seperate ghc-pkg database for static packages, installing and using static libs should
    work out of the box, without any extra work from users side.

  See also: https://wiki.archlinux.org/title/Haskell

**NOTE:** ghc cross-compiler and patched cabal-install for CI is built in my repo, so for transparency reasons if you would like to add it to Termux then you may do so.

closes: #8919 
closes: #5973

### CODE REVIEW

**Comment by MrAdityaAlok** [comment]
Everything is working fine except `runhaskell` bin which gives following error.

@Grimler91 and @xtkoba what this error could be:
```
Setup.hs: <command line>: dlopen failed: cannot locate symbol "stg_ARR_WORDS_info" referenced by "/data/data/com.termux/files/usr/lib/ghc-8.10.7/text-1.2.4.1/libHStext-1.2.4.1-ghc8.10.7.so"...
``` 
I am unable to find which library defines `stg_ARR_WORDS_info` or what to patch...

**Comment by danwdart** [comment]
Oh nice! Thanks for this PR!

**Comment by chenyulue** [comment]
Thanks for the PR! One issue: `ghc` or `cabal` cannot find any packages while compiling or building, even the `base` packages cannot be found. However, `ghc-pkg list` gives the list of installed packages.

```haskell
-- hello.hs
module Main where

main = putStrLn "Hello World!"
```

When compiling the above code with `ghc hello.hs`, it tells missing the 'base-4.14.3.0' package.

**Comment by MrAdityaAlok** [comment]
@chenyulue as I stated here

>Packaging policy for haskell packages
>I am going with [ArchLinux policy](https://wiki.archlinux.org/title/Haskell_package_guidelines) to only provide dynamic libs and
 >executables by default, except that
>there is no seperate ghc-pkg database for static packages.

>Since there is no seperate ghc-pkg database for static packages, installing and using static libs should
>work out of the box, without any extra work from users side.
>See also: https://wiki.archlinux.org/title/Haskell

Only dynamic libs are available by default, compile with `ghc hello.hs -dynamic` or install static libs with `pkg i ghc-libs-static`

**Comment by chenyulue** [comment]
Solved, thanks! I missed the important message.

**Pull request merged**
