### PR TITLE
[WIP] NDK r18

### PR DESCRIPTION
**Pull request by fornwall**
Currently using r18-beta2. The final r18 version should hopefully be released next according to https://github.com/android-ndk/ndk/wiki.

### CODE REVIEW

**Comment by Grimler91** [comment]
Binutils fails for aarch64 with:
```
LIB_PATH='' /bin/bash /home/builder/.termux-build/binutils/src/ld/genscripts.sh "/home/builder/.termux-build/binutils/src/ld" "/data/data/com.termux/files/usr/lib" "/data/data/com.termux/files/usr" "/data/data/com.termux/files/usr" aarch64-unknown-linux-android aarch64-unknown-linux-android aarch64-linux-android "a
arch64linux aarch64linuxb aarch64linux32 aarch64linux32b armelfb_linux_eabi armelf_linux_eabi" "/system/lib64" no yes aarch64elf32 "aarch64-linux-android"
/home/builder/.termux-build/binutils/src/gold/x86_64.cc:1592:10: error: case value evaluates to 3221225474, which cannot be narrowed to type 'int' [-Wc++11-narrowing]
    case elfcpp::GNU_PROPERTY_X86_FEATURE_1_AND:
         ^
/home/builder/.termux-build/binutils/src/gold/x86_64.cc:1591:10: error: case value evaluates to 3221225473, which cannot be narrowed to type 'int' [-Wc++11-narrowing]
    case elfcpp::GNU_PROPERTY_X86_ISA_1_NEEDED:
         ^
/home/builder/.termux-build/binutils/src/gold/x86_64.cc:1590:10: error: case value evaluates to 3221225472, which cannot be narrowed to type 'int' [-Wc++11-narrowing]
    case elfcpp::GNU_PROPERTY_X86_ISA_1_USED:
         ^
/home/builder/.termux-build/binutils/src/gold/x86_64.cc:1617:10: error: case value evaluates to 3221225474, which cannot be narrowed to type 'int' [-Wc++11-narrowing]
    case elfcpp::GNU_PROPERTY_X86_FEATURE_1_AND:
         ^
/home/builder/.termux-build/binutils/src/gold/x86_64.cc:1614:10: error: case value evaluates to 3221225473, which cannot be narrowed to type 'int' [-Wc++11-narrowing]
    case elfcpp::GNU_PROPERTY_X86_ISA_1_NEEDED:
         ^
/home/builder/.termux-build/binutils/src/gold/x86_64.cc:1611:10: error: case value evaluates to 3221225472, which cannot be narrowed to type 'int' [-Wc++11-narrowing]
    case elfcpp::GNU_PROPERTY_X86_ISA_1_USED:
         ^
```

Seems like it's trying to use  /home/builder/.termux-build/binutils/src/gold/x86_64.cc instead of /home/builder/.termux-build/binutils/src/gold/aarch64.cc

**Comment by Grimler91** [comment]
Next problem is that `~/lib/android-ndk/toolchains/{ARCH}-linux-android-4.9/prebuilt/linux-x86_64/bin/{ARCH}-linux-android-gcc` has been replaced with this script:
```bash
#!/bin/bash
exec `dirname $0`/../../../../llvm/prebuilt/linux-x86_64/bin/clang -target {ARCH}-linux-android "$@"
```
Which can't be run after it has been put into `~/.termux-build/_cache/`, since the relative path is all wrong. We could easily patch it in termux_step_setup_toolchain() but I wonder if there is a better solution?

**Comment by Grimler91** [comment]
I've opened a couple of PRs. I'm running a `build-all.sh -a all` to see if more packages need to be updated.

**Comment by Grimler91** [comment]
Nginx fails with:
```
[...]
aarch64-linux-android-clang -c -Oz -I/data/data/com.termux/files/usr/include -DIOV_MAX=1024  -Oz -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs \
        -o objs/src/os/unix/ngx_thread_id.o \
        src/os/unix/ngx_thread_id.c
src/event/modules/ngx_epoll_module.c:594:6: error: token is not a valid binary operator in a preprocessor subexpression
#if (NGX_READ_EVENT != EPOLLIN|EPOLLRDHUP)
     ^~~~~~~~~~~~~~
src/event/ngx_event.h:360:29: note: expanded from macro 'NGX_READ_EVENT'
#define NGX_READ_EVENT     (EPOLLIN|EPOLLRDHUP)
                            ^~~~~~~
/home/builder/.termux-build/_cache/18-aarch64-21-v1/bin/../sysroot/usr/include/linux/eventpoll.h:28:36: note: expanded from macro 'EPOLLIN'
#define EPOLLIN (__force __poll_t) 0x00000001
                ~~~~~~~~~~~~~~~~~~ ^
src/event/modules/ngx_epoll_module.c:601:6: error: token is not a valid binary operator in a preprocessor subexpression
#if (NGX_WRITE_EVENT != EPOLLOUT)
     ^~~~~~~~~~~~~~~
src/event/ngx_event.h:361:28: note: expanded from macro 'NGX_WRITE_EVENT'
#define NGX_WRITE_EVENT    EPOLLOUT
                           ^~~~~~~~
/home/builder/.termux-build/_cache/18-aarch64-21-v1/bin/../sysroot/usr/include/linux/eventpoll.h:30:37: note: expanded from macro 'EPOLLOUT'
#define EPOLLOUT (__force __poll_t) 0x00000004
                 ~~~~~~~~~~~~~~~~~~ ^
2 errors generated.
objs/Makefile:852: recipe for target 'objs/src/event/modules/ngx_epoll_module.o' failed
make[1]: *** [objs/src/event/modules/ngx_epoll_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/builder/.termux-build/nginx/src'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by fornwall** [comment]
I merged this now, we'll fix issues on master!

**Pull request merged**
