### PR TITLE
python: update to 3.8.3

### PR DESCRIPTION
**Pull request by landfillbaby**
hopefully this is trivial but I've been wrong in the past. let's see what CI thinks

### CODE REVIEW

**Comment by landfillbaby** [comment]
ooh ok here we go

**Comment by landfillbaby** [comment]
hmm

**Comment by xeffyr** [comment]
Remove 0001-compileall-Fix-ddir-when-recursing.patch.

**Comment by landfillbaby** [comment]
oh oops you're right. i had checked all of the patches manually except that one for some reason

**Pull request merged**
