### PR TITLE
gstreamer: Bump 1.19.3

### PR DESCRIPTION
**Pull request by Yonle**
This pull has a version bump of gstreamer alongside with it's plugins including libav

### CODE REVIEW

**Comment by Yonle** [comment]
Something related with outdated meson. Will check out

**Comment by Grimler91** [comment]
Looking at the diff that [removed the line in the libcaca patch shows that it was just moved](https://github.com/GStreamer/gst-plugins-good/commit/dd3496c830fc401b59977a63809dc2d93b468537#diff-34c47aa892978a9ae957a0d43377845f83cae79a21438a615d6b4e2f7be7c275R91), so patch should be adapted (assuming we still need it)

**Comment by Yonle** [comment]
> Looking at the diff that [removed the line in the libcaca patch shows that it was just moved](https://github.com/GStreamer/gst-plugins-good/commit/dd3496c830fc401b59977a63809dc2d93b468537#diff-34c47aa892978a9ae957a0d43377845f83cae79a21438a615d6b4e2f7be7c275R91), so patch should be adapted (assuming we still need it)

Well then, We need somebody to create a patch...

**Comment by Yonle** [comment]
Missclicked.

**Comment by Yonle** [comment]
Since we're still need that patch, I may convert this pull as draft.

**Review by thunder-coding — APPROVED** [review]

**Pull request merged**
