### PR TITLE
New Package: Chafa

### PR DESCRIPTION
**Pull request by Yonle**
Image-to-text converter supporting a wide range of symbols, etc.

### CODE REVIEW

**Comment by Yonle** [comment]
Updated upstream.

**Comment by Grimler91** [comment]
If I merge it now it will show up as "unverified". Do you want to rebase, [sign the commit](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits) and force push to fix that?

**Comment by Yonle** [comment]
Sure. Let me sign the commit

**Comment by Yonle** [comment]
Let's try this.

**Comment by Yonle** [comment]
Okay, seems like i just make everything messed up

**Pull request closed without merging**
