### PR TITLE
`nushell`: Bump to 0.33.0

### PR DESCRIPTION
**Pull request by thunder-coding**

### CODE REVIEW

**Comment by thunder-coding** [comment]
I messed it up 🤦. Consider `Sqash and Merge`

**Comment by suhan-paradkar** [comment]
You can squash that @thunder-coding 
```
git checkout bump-nushell
git rebase HEAD~3
```

**Comment by thunder-coding** [comment]
Thanks @suhan-paradkar

**Comment by buttaface** [comment]
Wait, what? I updated this last week, de23c08.

**Comment by Grimler91** [comment]
Looks like only the patch header was updated after the squash/debase: https://github.com/termux/termux-packages/commit/8c38c828b7542c710f7c357a2fe7a77c90c0dcae#diff-39e1e69ae9d07c7291b2db89cf64cff11424945379a9f2ef0b615a9802801c2b

**Comment by buttaface** [comment]
Yeah, but how does it show him bumping the version in the pull here? It should have shown a conflict when the pull was submitted.

**Comment by Grimler91** [comment]
Yes, seems like a github quirk..

**Pull request merged**
