### PR TITLE
CI: switch to Cirrus

### PR DESCRIPTION
**Pull request by xeffyr**
Replaces current setup where we have Travis for pull requests and Gitlab CI for compiling and uploading. While Cirrus CI has hard limit of 2 hours per build, it actually 2-3 times faster than Gitlab CI.

Though, it has following 2 cons:
* No support for scheduled jobs. Means that we cannot do automatic APT repository cleanup via CI task.

* PRs always diff'ed against head of the base branch. This means that pull requests always should be up-to-date, otherwise unnecessary work will be performed on push.

### CODE REVIEW

**Comment by fkorotkov** [comment]
Two notes: 

1. Cron Jobs is [currently under development](https://github.com/cirruslabs/cirrus-ci-docs/issues/39) and will be available later this month.
2. For PRs `changesInclude` uses list of files that the PR affected so no need to worry about up-to-date branch.

**Comment by xeffyr** [comment]
It seems that `changesInclude` can be used only for expressions `only_if` and `skip`. It can't be used for retrieving actual file list and storing it in variable. Am I wrong here ?

**Comment by fkorotkov** [comment]
Yes, it's only for evaluating of the `changesInclude` expression so the files only loaded when you need them and not all the time. You can use `CIRRUS_BASE_SHA` [environment variable](https://cirrus-ci.org/guide/writing-tasks/#environment-variables) to calculate the list for a PR.

**Comment by xeffyr** [comment]
> You can use CIRRUS_BASE_SHA environment variable to calculate the list for a PR.

That is what actually used.

Usually, `CIRRUS_BASE_SHA` points to the commit on which pull request is based. But after force-push (no matter for which purpose) `CIRRUS_BASE_SHA` became updated to the head of base branch. So diff'ing between  `CIRRUS_BASE_SHA` and `CIRRUS_CHANGE_IN_REPO` shows files not only from pull request.

**Comment by fkorotkov** [comment]
Interesting! `CIRRUS_BASE_SHA` comes from a GitHub webhook event so seems it's an expected GitHub behaviour for a force push. 🤔

**Pull request merged**
