### PR TITLE
tsu: workaround magisk v19.3 bug

### PR DESCRIPTION
**Pull request by Grimler91**
exec /sbin/su -c "foo=bar bash" gives a shell that can't be exited for some reason, it just hangs.
foo=bar exec /sbin/su -c "bash" seem to work fine.

Also minor cleanup of build script.

### CODE REVIEW

**Comment by Grimler91** [comment]
Should perhaps be tested with another su variant before merging

**Comment by xeffyr** [comment]
It doesn't work correctly with Lineage OS addonsu. Option `-e` doesn't work.
Just `su -c "PATH=$PATH /data/data/com.termux/files/usr/bin/bash"` works much better.

**Comment by Grimler91** [comment]
Does lineage addonsu support any options? 

I guess we have to make a `if magisk; then ... elif los addonsu; then ...; fi` loop then and select syntax based on that. I have an phone with lineage at home so can improve this PR during the week.

**Comment by xeffyr** [comment]
> Does lineage addonsu support any options?

Yes.
```
Usage: su [options] [--] [-] [LOGIN] [--] [args...]

Options:
  --daemon                      start the su daemon agent
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        do not change environment variables
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -v, --version                 display version number and exit
  -V                            display version code and exit,
                                this is used almost exclusively by Superuser.apk
$
```

**Pull request closed without merging**
