### PR TITLE
new package: notcurses

### LINKED ISSUE #8860: [Package]: notcurses
### Package description

blingful character graphics/TUI library. definitely not curses.

### Home page URL

https://nick-black.com/dankwiki/index.php/Notcurses

### Source code URL

https://github.com/dankamongmen/notcurses

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by pvonmoradi**
Adds [notcurses](https://github.com/dankamongmen/notcurses)
Close #8860 .

### CODE REVIEW

**Comment by buribu** [comment]
closes #8860

**Comment by buribu** [comment]
``` /home/builder/.termux-build/notcurses/src/src/lib/internal.h:1836:6: warning: implicit declaration of function 'pthread_cancel' is invalid in C99 [-Wimplicit-function-declaration]
  if(pthread_cancel(tid)){ ```

**Comment by zorro** [comment]
@pvonmoradi You should add ```libandroid-spawn``` to ```TERMUX_PKG_DEPENDENCIES```

**Comment by zorro** [comment]
@pvonmoradi You should add ```libandroid-spawn``` to ```TERMUX_PKG_DEPENDS```

**Comment by xtkoba** [comment]
Not even attempting to work around `pthread_cancel`. Closing.

**Pull request closed without merging**
