### PR TITLE
python: have bin/python${_MAJOR_VERSION}m back

### PR DESCRIPTION
**Pull request by tomty89**
and convert bin/python${_MAJOR_VERSION} from hardlink to symlink

### CODE REVIEW

**Comment by fornwall** [comment]
This would make it conflict with the `python2` package due to `bin/python-config` and `bin/pydoc` being present there. Could you update the `python2` package here and move them to `python2-config` and `pydoc2`?

Also, a minor improvement that can be made: Replace `rm -f python; ln -s python3 python` and other similar calls with `ln -f -s python3 python` - the `-f` option removes the destination file so the `rm` call is not needed anymore.

**Comment by tomty89** [comment]
@fornwall Done. Added an extra commit that delete idle/tk/test files in the python2 package. Also delete test files in the packages with glob.

Would you kindly check out and merge #2381 before this PR? Since this one has the revision bumps and breaks/replaces. Thanks a lot!

**Comment by tomty89** [comment]
Btw having lines for `*/test` and `*/tests` respectively is intentional since I think it's better to be explicit in this, though `*/test*/` (with trailing slash, otherwise `asyncio/test_utils.py` in python3 will be matched) should also work fine at the moment, if desired.

**Comment by tomty89** [comment]
Fixed commit for pydoc in python2.

**Comment by fornwall** [comment]
Now that you have updated python2, you don't need TERMUX_PKG_BREAKS and TERMUX_PKG_REPLACES anymore, right? As python and python2 continues to be installable side by side?

**Comment by tomty89** [comment]
@fornwall I think they are necessary for upgrade without manual intervention, as apt may upgrade python before python2. Breaks is not the same as Conflicts, and it's versioned.

**Comment by fornwall** [comment]
@tomty89 Ah, I missed the versioned part, great! Still, shouldn't breaks be enough, and you should remove replaces? Because you don't want to replace `python2` with `python` for users?

**Comment by tomty89** [comment]
@fornwall From what I understand, when Replaces is used with Breaks (and / or versioned), it doesn't prevent the package it replaces from being upgraded:
https://www.debian.org/doc/debian-policy/#overwriting-files-and-replacing-packages-replaces
But to be honest, I am not sure when Replaces is and is not necessary. I don't think.the documentation is clear on that as it seem to only have vague statement like:
> Normally, Breaks should be used in conjunction with Replaces.
I don't know apt/dpkg very well coz my background is mainly Arch/pacman, which does this kind of stuff in an, IMHO, way more understandable way.

**Comment by fornwall** [comment]
Thanks! The updated package is now available for installation.

I removed `Replaces` and left just `Breaks`, as I think that is more correct (the `python` package does not replace the older `python2` package, it's just incompatible with it). It seems to work, let me know if there are any problems!

**Pull request merged**
