### PR TITLE
rust: Update to 1.63.0

### PR DESCRIPTION
**Pull request by PeroSar**
Signed-off-by: PeroSar <perosar1111@gmail.com>

### CODE REVIEW

**Comment by buttaface** [comment]
Btw, is the current Rust package working fine after the NDK 25 update? If so, no hurry on getting this arm issue fixed: I wonder if this pull builds fine with NDK 23c or if this is because of the Rust version update.

**Comment by pro465** [comment]
any updates?

**Comment by PeroSar** [comment]
> any updates?

No idea about how to fix the arm build

**Comment by buttaface** [comment]
Bunch of linker errors like this:
```
ld: error: /home/builder/.termux-build/rust/build/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/armv7-linux-androideabi/lib/libcompiler_builtins-3bb56b4aa4d5410e.rlib(compiler_builtins-3bb56b4aa4d5410e.compiler_builtins.63dd7eb2-cgu.138.rcgu.o):
symbol __aeabi_memcpy@@LIBC_N has undefined version LIBC_N
```
@sylirre, any idea?

**Comment by arctic-hen7** [comment]
I work on a Rust project that needs 1.63 on my tablet when I'm on the go, is there anything I can do to help this forward?

**Comment by buttaface** [comment]
@arctic-hen7, you could test out [the AArch64 build from the last CI run by installing it with `dpkg -i rust*deb`](https://github.com/termux/termux-packages/actions/runs/2889604036) and let us know of any problems.

**Comment by Grimler91** [comment]
So the symbols that give errors for arm are defined in the [compiler_builtins arm.rs file](https://github.com/rust-lang/compiler-builtins/blob/master/src/arm.rs#L93). I'll see if some tweaks to the definitions helps us get rid of this error..

**Comment by arctic-hen7** [comment]
@buttaface not sure if I'm doing something wrong with the installation (followed your instructions exactly after `apt purge rust` and `rm -rf ~/.cargo`), but I can't even run `rustc --version`, I'm getting this error (I'm using Fish):

```
fish: Job 1, 'rustc --version' terminated by signal SIGSEGV (Address boundary error)
```

Using the current package available with `apt install rust` doesn't produce that error.

**Comment by arctic-hen7** [comment]
I tried downloading the 1.62.1 artifacts and ran `dpkg -i` on that Rust package (I'm just installing `rust` itself, not any of the other packages), and `rustc --version` worked fine. That would seem to indicate that there's something wrong with the aarch64 1.63 package, rather than my installation thereof.

**Comment by buttaface** [comment]
> I can't even run rustc --version, I'm getting this error

Thanks, this is the first rust build with the new NDK 25b, and it's possible there's been some regression.

**Comment by licy183** [comment]
Sorry for the mess. I merged https://github.com/termux/termux-packages/commit/8a957b51163ce6ccb3be6863bb87c2a35f30cb32 and I forgot to check the packages list. It should be fixed by https://github.com/termux/termux-packages/commit/0c92e85834d0708460dfe2d6d2b941f5ae8087bc.

**Comment by Grimler91** [comment]
@licy183 no worries!

**Comment by Grimler91** [comment]
Rebased again after @xtkoba's build fix in https://github.com/termux/termux-packages/commit/aebc02285b0ff6a7c65433f1036ef1c6c6428380, and dropped the attempts to get rid of the hacks that hides various libraries (for now). Lets try to get this in.

**Pull request merged**
