### PR TITLE
new package: tdl

### PR DESCRIPTION
**Pull request by Valium007**
new package: tdl

📥 A Telegram downloader/tools written in Golang

https://github.com/iyear/tdl

### CODE REVIEW

**Comment by truboxl** [comment]
No need to close and reopen new PRs...
https://github.com/termux/termux-packages/pulls?q=author%3Aiamwho001

Please fix your tabbing (spaces -> tabs) and remove all the duplicated new lines

**Comment by iamwho001** [comment]
> No need to close and reopen new PRs... https://github.com/termux/termux-packages/pulls?q=author%3Aiamwho001
> 
> Please fix your tabbing (spaces -> tabs) and remove all the duplicated new lines

Done!

**Comment by truboxl** [comment]
License should be `AGPL-V3`

I feel a bit conflicted whether to add this or not since tdl means something else on https://repology.org/project/tdl/versions

**Comment by Valium007** [comment]
> License should be `AGPL-V3`
> 
> I feel a bit conflicted whether to add this or not since tdl means something else on https://repology.org/project/tdl/versions

Thanks, sorry i didnt checked it carefully.
Updated it

**Comment by truboxl** [comment]
May I know how does tdl works?

tdl doesn't seem to work with `org.telegram.messenger` app for me. And if it does Android blocks Termux access to Telegram folders.

tdl seems like rely on Telegram Desktop and we haven't packaged that.

**Comment by Valium007** [comment]
should I squash all the commits?

**Comment by twaik** [comment]
Yes.

**Comment by truboxl** [comment]
Actually our side can help squash it. But thanks for your contribution for the package.

**Pull request merged**
