### PR TITLE
Add package ngrok [WIP] 

### PR DESCRIPTION
**Pull request by Auxilus**

### CODE REVIEW

**Comment by Grimler91** [comment]
What does 1.7.1.tar.gz contain? (It doesn't seem to be source code)
Why are you downloading it from your github page and not the origin?

**Comment by Auxilus** [comment]
I tried compiling package from source code, but its not working, So i had go for this..

**Comment by Grimler91** [comment]
Go for what? Where did you get the file from?

If it is compiled for a normal Linux system then it won't work for two reasons:
1. It assumes libraries and binaries are at /usr/{lib,bin}
2. It is compiled for one architecture (for example x86_64) and then it won't work for the other arches (arm, aarch64,...)

**Comment by Auxilus** [comment]
Okay, I'll close this one till i come up with a better solution..

**Comment by Grimler91** [comment]
@Auxilus we need to compile from source since termux is a quite none-standard Linux environment. 

I think it would be good if you give a bit more information in the pull requests, for example:
Is the pull request a WIP or is it good to go?
Is the package tested (on device)?

The more information the better, as it simplifies for everyone else when testing or reviewing 👍

**Comment by Auxilus** [comment]
Ngrok has direct download link on their website ( which gives executable file directly )  and yes it's been tested by numerous people ( in termux itself ) that's why I created tarball with executable in it and put `cp ngrok $TERMUX_PREFIX/bin/` in build.sh ( I tried compiling from source ).

**Comment by Auxilus** [comment]
Direct executable download link is https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip

**Comment by Grimler91** [comment]
Thanks! Great, always good to know where a file comes from.  

ngrok-stable-linux-arm.zip is for arm though so it won't work on aarch64, x86_64 or i686. 
If you've tested it on the device then I assume that you had to run it in a termux-chroot env, else it probably complains that libraries that it assumes are at /usr/lib are missing. All the packages in the repo so far (correct me if I'm wrong someone) are cross compiled and therefore can be run without chroot, we should probably keep it this way

**Comment by Auxilus** [comment]
I'm working on compiling it from source

**Comment by Auxilus** [comment]
```
[21:26][u0_a164¦~/ngrok-1.5]$ make
go fmt ngrok/...
go get -tags '' -d -v ngrok/...
Fetching https://launchpad.net/goyaml?go-get=1
Parsing meta tags from https://launchpad.net/goyaml?go-get=1 (status code 200)
get "launchpad.net/goyaml": found meta tag get.metaImport{Prefix:"launchpad.net/goyaml", VCS:"bzr", RepoRoot:"https://launchpad.net/~goyaml/goyaml/trunk"} at https://launchpad.net/goyaml?go-get=1
launchpad.net/goyaml (download)
go: missing Bazaar command. See https://golang.org/s/gogetcmd
package launchpad.net/goyaml: exec: "bzr": executable file not found in $PATH
Fetching https://code.google.com/p/log4go?go-get=1
Parsing meta tags from https://code.google.com/p/log4go?go-get=1 (status code 200)
package code.google.com/p/log4go: unrecognized import path "code.google.com/p/log4go" (parse https://code.google.com/p/log4go?go-get=1: no go-import meta tags ())
github.com/garyburd/go-websocket (download)
# cd .; git clone https://github.com/garyburd/go-websocket /data/data/com.termux/files/home/ngrok-1.5/src/github.com/garyburd/go-websocket
Cloning into '/data/data/com.termux/files/home/ngrok-1.5/src/github.com/garyburd/go-websocket'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/garyburd/go-websocket/websocket: exit status 128
make: *** [Makefile:7: deps] Error 1
[21:26][u0_a164¦~/ngrok-1.5]$
```

**Comment by M33nato** [comment]
so
where i can find files, downlads by termux?

**Pull request closed without merging**
