### PR TITLE
Remove gnupg1

### PR DESCRIPTION
**Pull request by Grimler91**
I've been using this for a couple of weeks and it seems to work fine. 

More testing is probably needed though, and feedback, have I forgotten some other package that secretly relies on gnupg?

### CODE REVIEW

**Comment by Grimler91** [comment]
> We probably want to remove --enable-gpg-is-gpg2 from the gnupg2 package, right? So that gnupg2 installs gpg and other binaries without version suffix. 

Maybe, most programs (that I normally use) seem to work fine or already use gpg2/gpgv2/other. 
Might be safest to remove it though, for all the programs I do not normally use. 
I'll update the PR.

**Comment by fornwall** [comment]
> Maybe, most programs (that I normally use) seem to work fine or already use gpg2/gpgv2/other.
Might be safest to remove it though, for all the programs I do not normally use.
I'll update the PR.

Right, I think it's best for compatibility with common linux distributions such as ubuntu, where gpg already is gnupg2. We should probably setup `bin/gpg2` as a symlink to `bin/gpg` for compatibility as well (which is also something that at least ubuntu does).

**Comment by fornwall** [comment]
Two more things:

1. What do you think about renaming the package to `gnupg`? And then also adding

```
TERMUX_PKG_CONFLICTS=gnupg2
TERMUX_PKG_REPLACES=gnupg2
```

to the new package, so that everyone that has gnupg2 installed gets upgraded to the new `gnupg` package?

2. apt does not need the full gnupg commands, just `gpgv`. In order to keep the base packages (that every Termux has has installed) as small as possible, could you split out `gpgv` into a subpackage and let apt depend on it, just as was done for gpg1?

**Comment by Grimler91** [comment]
Sure, I don't have much experience in ubuntu so I'll just trust your expertise here.. :)
(Suse provides symlinks but keeps the package as gpg2)

Splitting out gpgv sounds like a good idea, I'll implemented the requested changes.

**Comment by fornwall** [comment]
The updated packages are now available for installation! The bootstrap zips have also been updated.

**Pull request merged**
