### PR TITLE
[Helix] Bump from version 0.2.1 to 0.3.0

### PR DESCRIPTION
**Pull request by MrAdityaAlok**

### CODE REVIEW

**Comment by Grimler91** [comment]
Please try to write what package the commit relates to in the commit message as well, i.e.
`helix: Bump from version 0.2.1 to 0.3.0` 
or 
`[Helix] Bump from version 0.2.1 to 0.3.0` 
as you wrote instead of 
`Bump from version 0.2.1 to 0.3.0`

thanks!

**Comment by MrAdityaAlok** [comment]
> Please try to write what package the commit relates to in the commit message as well, i.e.
> `helix: Bump from version 0.2.1 to 0.3.0`
> or
> `[Helix] Bump from version 0.2.1 to 0.3.0`
> as you wrote instead of
> `Bump from version 0.2.1 to 0.3.0`

Sure, I'll keep in mind next time.

**Comment by buttaface** [comment]
Consider adding this to [the list of automatically checked and updated github projects too](https://github.com/termux/termux-packages/blob/master/scripts/updates/github-projects.txt).

**Comment by MrAdityaAlok** [comment]
> Consider adding this to [the list of automatically checked and updated github projects too](https://github.com/termux/termux-packages/blob/master/scripts/updates/github-projects.txt).

Sure, I'll add it soon.

**Pull request merged**
