### PR TITLE
add(main): new package Imath

### PR DESCRIPTION
**Pull request by T-Dynamos**
A first step towards #11674

### CODE REVIEW

**Review by 2096779623 — CHANGES_REQUESTED** [review]
Why are two blank lines added?

**Comment by T-Dynamos** [comment]
> Why are two blank lines added?

I am confused that why it is not building ( see build time is 5secs) .
So to just confirm I added , I will remove

**Comment by 2096779623** [comment]
Maybe you can add Python bindings as subpackage.

**Comment by 2096779623** [comment]
> I am confused that why it is not building ( see build time is 5secs) . So to just confirm I added , I will remove

Try to add `TERMUX_PKG_BUILD_IN_SRC=true` .

**Comment by 2096779623** [comment]
> > Why are two blank lines added?
> 
> I am confused that why it is not building ( see build time is 5secs) . So to just confirm I added , I will remove

Try changing the package name to lowercase.

**Review by 2096779623 — APPROVED** [review]

**Pull request merged**
