### PR TITLE
Travis pkg builds

### PR DESCRIPTION
**Pull request by stephengroat**
#1108 

Probably still needs some work, but it's a start. Other file touches show functionality

Might be helpful to enable using travis `allow_failures` feature to allowed failed builds to start with

### CODE REVIEW

**Comment by fornwall** [comment]
A nice start, thanks!

**Comment by fornwall** [comment]
It's up and running (with issues it seems) at https://travis-ci.org/termux/termux-packages.

**Comment by stephengroat** [comment]
currently seeing an issue #1122 

needs continuous/real-time stdout forwarding to help with travis timeouts. will work on

**Comment by vishalbiswas** [comment]
you don't actually need to build inside a docker container. And you can increase the timeout https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Pull request merged**
