### PR TITLE
chore(x11/python-torch): Remove unused dependencies

### PR DESCRIPTION
**Pull request by fornwall**
Remove some dependencies and flags which no longer seems to be relevant in the current pytorch version:

- The `ffmpeg` dependency seems to no longer be used - the `USE_FFMPEG` cmake flag does not exist.
- The `libzmq` dependency seems to no longer be used - the `USE_ZMQ` cmake flag does not exist.
- The `opencv` dependency seems to no longer be used - the `USE_OPENCV` cmake flag does not exist.
- There doesn't seem to be any direct dependency on `abseil-cpp` (it's still pulled in as an indirect dependency).
- The `fmt` dependency doesn't seem to be used, an internal copy of it is built when when `fmt` is present.
- The `USE_METAL` cmake flag does not exist.
- The `OpenBLAS_INCLUDE_DIR` flag does not exist (but openblas seems to be found and used regardless).

Saves a few hundred of megabytes of disk space when installing `python-torch` on a clean setup.

### CODE REVIEW

**Comment by licy183** [comment]
If torch doesn't depend on opencv, is it possible to be moved to main packages?

**Review by licy183 — APPROVED** [review]
LGTM. Thanks for working on this!

**Comment by TomJo2000** [comment]
> If torch doesn't depend on opencv, is it possible to be moved to main packages?

If that was the only dependency from the X11 channel then it should be.

**Comment by fornwall** [comment]
:+1: I'll create a separate follow up PR for moving it from x11 to main.

**Pull request merged**
