### PR TITLE
Pidgin: Enabling audio conference, TCL scripting

### PR DESCRIPTION
**Pull request by IntinteDAO**
Many features in Pidgin have been disabled, my PR restores some of them.

Unfortunately, this does not solve the problem that Pidgin in Termux does not work properly (there are no protocols, while I think there should be 10 of them)

### CODE REVIEW

**Comment by truboxl** [comment]
Suggest to combine patches since its only patching a single configure file

**Comment by IntinteDAO** [comment]
@truboxl 
I hope it's fixed ;)

**Comment by IntinteDAO** [comment]
@truboxl Yhm, the CI/CD fucks up, what to do? :D

**Comment by truboxl** [comment]
I will help rebase. You can also rebase by `git checkout master; git pull; git checkout -; git rebase -i master`

**Comment by IntinteDAO** [comment]
> I will help rebase. You can also rebase by `git checkout master; git pull; git checkout -; git rebase -i master`
> 
> Oh nvm you are using master branch so probably need another way to do that...

I need to learn how to work on Github. Usually when I do it on Gitlab and I have my own branch and the projects are dependent on me. I don't know how to properly push fully to someone else's repository.

**Comment by truboxl** [comment]
I checked the build logs and it doesn't seem like build with voice and video is enabled...

**Comment by IntinteDAO** [comment]
@truboxl 
If I am successful I will introduce it. I did it because there is a strange bug in Pidgin and I wondered if I would fix it, but unfortunately not.

It looks from the Build Log that various protocols are being built for communication (such as XMPP), but Pidgin doesn't see them at all. 

I will probably have to report the bug.

**Pull request merged**
