### PR TITLE
oathtool: add package and its dependencies (xmlsec)

### PR DESCRIPTION
**Pull request by vaites**
I added [OATH Toolkit](http://www.nongnu.org/oath-toolkit/index.html), to generate OTPs via CLI:

> The OATH Toolkit provide components for building one-time password authentication systems. It contains shared libraries, command line tools. Supported technologies include the event-based HOTP algorithm (RFC4226) and the time-based TOTP algorithm (RFC6238). OATH stands for Open AuTHentication, which is the organization that specify the algorithms. For managing secret key files, the Portable Symmetric Key Container (PSKC) format described in RFC6030 is supported.

You can now forget Google Authenticator...

I named it like Debian does (they split in several packages, but I think here is not necessary), and is tested as usual:

screenshot_20170302-002514

### CODE REVIEW

**Comment by vishalbiswas** [comment]
+1. Your description says "and a PAM module"

**Comment by vaites** [comment]
Well, I copied the description from the website but PAM module is disabled here.. m

**Comment by fornwall** [comment]
Thanks! The built package is now available for installation.

**Comment by vaites** [comment]
Thanks!

**Pull request merged**
