### PR TITLE
add(main): new package libdecor

### PR DESCRIPTION
**Pull request by T-Dynamos**

### CODE REVIEW

**Comment by T-Dynamos** [comment]
This PR is ready to be merged.

**Comment by truboxl** [comment]
It doesn't help when https://gitlab.gnome.org/jadahl/libdecor shows
```
 Archived project! Repository and other project resources are read-only
```

**Comment by TomJo2000** [comment]
Furthermore, from the Readme.md
New URL is https://gitlab.freedesktop.org/libdecor/libdecor

**Comment by T-Dynamos** [comment]
Done, but even on new URL, version is same.

**Comment by TomJo2000** [comment]
Is this required as a dependency for another package or anything?
We don't usually package random libraries just for fun.

**Comment by T-Dynamos** [comment]
Ah, I am sorry I forgot to mention that it is required by the latest blender. SEE: https://github.com/termux-user-repository/tur/issues/365

**Comment by TomJo2000** [comment]
If this is required for the Blender package in the TUR, wouldn't it be more appropriate to package it over in the TUR?

**Comment by T-Dynamos** [comment]
>  wouldn't it be more appropriate to package it over in the TUR?
I don't think so, it is also required by other packages. Like SDL (for Wayland client decorations).

**Comment by TomJo2000** [comment]
So why wasn't this packaged previously as a dependency for SDL?
And wouldn't the build script for SDL need to be adjusted to use `libdecor`?

**Comment by T-Dynamos** [comment]
I will enable `libdecor` in SDL after this PR.

**Comment by truboxl** [comment]
Have you ever checked why Wayland is even needed in Blemder before adding extra package?
It isn't even declared. Maybe the user installed libwayland hence the bad build detection?
https://github.com/termux-user-repository/tur/blob/master/tur-on-device/blender/build.sh#L16

And then does Wayland even work on Termux?

**Comment by T-Dynamos** [comment]
Hm, it builds flawlessly. So should I close this PR?

**Comment by 2096779623** [comment]
> Hm, it builds flawlessly. So should I close this PR?

Close this pr or transfer this package to tur.

**Pull request closed without merging**
