### PR TITLE
new package: e2fsprogs

### PR DESCRIPTION
**Pull request by xeffyr**
EXT 2/3/4 filesystem utilities.

### CODE REVIEW

**Comment by pawamoy** [comment]
Any news on this? It seems the build failed because of something else than e2fsprogs:

```
...
termux - build of 'e2fsprogs' done
rake aborted!
NoMethodError: undefined method `exitstatus' for nil:NilClass
/home/travis/build/termux/termux-packages/Rakefile:33:in `block (2 levels) in <top (required)>'
/home/travis/build/termux/termux-packages/Rakefile:19:in `each'
/home/travis/build/termux/termux-packages/Rakefile:19:in `block in <top (required)>'
/home/travis/build/termux/termux-packages/vendor/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `load'
/home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `<main>'
Tasks: TOP => default => build
(See full trace by running task with --trace)

The command "bundle exec rake" exited with 1.
```

**Comment by xeffyr** [comment]
> termux - build of 'e2fsprogs' done

Package was built successfully. Everything else is just Travis build script error and can be ignored since we use Travis CI just to check that package can be compiled.

Now Travis fails anyway because of failed `ca-certificates`.

**Comment by pawamoy** [comment]
So, we're just waiting for @fornwall to merge?

**Comment by xeffyr** [comment]
Yes.

I can build package myself and post it here because I don't know when this will be merged.

**Comment by pawamoy** [comment]
Don't bother, I could pull your branch and build the package myself as well, but I'm not in a hurry and at the end I need it in the pkg repo for [Tomb](https://github.com/dyne/Tomb) to work in Termux. So let's wait, fornwall was mentioned so he'll get the notification :slightly_smiling_face: 

Anyway, thank you very much @xeffyr for your work! I couldn't have done this myself :O

**Comment by xeffyr** [comment]
[e2fsprogs_1.44.4_aarch64.deb.gz](https://github.com/termux/termux-packages/files/2650774/e2fsprogs_1.44.4_aarch64.deb.gz)
[e2fsprogs_1.44.4_arm.deb.gz](https://github.com/termux/termux-packages/files/2650775/e2fsprogs_1.44.4_arm.deb.gz)
[e2fsprogs_1.44.4_i686.deb.gz](https://github.com/termux/termux-packages/files/2650776/e2fsprogs_1.44.4_i686.deb.gz)
[e2fsprogs_1.44.4_x86_64.deb.gz](https://github.com/termux/termux-packages/files/2650777/e2fsprogs_1.44.4_x86_64.deb.gz)

**Comment by pawamoy** [comment]
Hi @fornwall, I was wondering: is there something preventing you to merge this? If not and you're just waiting for the time and ability to do so, please disregard my comment :slightly_smiling_face:

**Comment by xeffyr** [comment]
It's a subject for https://github.com/termux/unstable-packages currently.

**Pull request closed without merging**
