### PR TITLE
Update tsu to v2.1. Use git clone to checkout tags.

### PR DESCRIPTION
**Pull request by cswl**
Minor release since Magisk fixed 64bit support.

### CODE REVIEW

**Comment by xeffyr** [comment]
You are not checking out version tag which makes specified package version useless. Build may not be reproducible once something was added to upstream.

**Comment by cswl** [comment]
Ow.. I did push tag to the repo.. will update

**Comment by cswl** [comment]
@xeffyr Updated. now it should checkout the specified tag.

**Comment by xeffyr** [comment]
Now okay.

**Comment by xeffyr** [comment]
Updated package is now available for installation ([android-7](https://bintray.com/termux/termux-packages-24) repository only).

**Pull request merged**
