### PR TITLE
libandroid-support: update to v29

### PR DESCRIPTION
**Pull request by landfillbaby**
I've just updated `wcwidth` to Unicode 15.
This shouldn't be merged until the next `termux-app` release, due to the rendering bugs that happened last time `wcwidth` wasn't in sync between `termux-app` and `libandroid-support`.
This doesn't block #13915 or any other revbumps of it though.

### CODE REVIEW

**Comment by stevenxxiu** [comment]
Thanks for this. Should it be updated and merged now for v0.119.0-beta.1, or wait until v0.119 is released as there might be more changes required?

**Comment by agnostic-apollo** [comment]
Both `v0.118.1` and `v0.119.0-beta.1` contain support.

https://github.com/termux/termux-app/releases

**Comment by stevenxxiu** [comment]
Thanks! I tested v0.119.0-beta.1 after it went on *F-Droid*. Indeed it fixes my original issue in *Neovim*.

**Comment by agnostic-apollo** [comment]
Cool, welcome.

**Review by ABirHAsan123-beep — COMMENTED** [review]
​

**Pull request merged**
