### PR TITLE
openjdk-9-headless: make it build (at least on arm)

### PR DESCRIPTION
**Pull request by vishalbiswas**
switch from jdk9/dev to mobile/dev repo
switch from tag based to changeset based build
add patch to use our getgr{gid,nam}_r from grp.h
remove all old patches
clean up code big time (no more custom patch format)

Edit
There is a bug in the built package which causes the jdk path to be returned as (null).

### CODE REVIEW

**Comment by fornwall** [comment]
Nice - exciting to see openjdk 9 progress!

**Comment by PaulAtBanno** [comment]
Any comment on progress on this, for x86_64 especially?

**Comment by vishalbiswas** [comment]
@PaulAtBanno x86_64 build succeeds, I'll upload an up-to-date deb file for testing tomorrow.

**Comment by vishalbiswas** [comment]
@PaulAtBanno please test openjdk from here https://drive.google.com/drive/folders/0B8Q4yBRb9PSHQ2lfVVYzLU5JelE
it's a test build so may not behave well

**Comment by PaulAtBanno** [comment]
Thanks! Would you mind posting your build steps? I haven't been successful in building locally.

**Comment by PaulAtBanno** [comment]
Here's the output when I try:

```shell
psnively@Ragnarok:~/projects/termux-packages|master 
⇒  ./scripts/run-docker.sh ./build-package.sh -a x86_64 -D openjdk-9-jre-headless
Running container 'termux-package-builder' from image 'termux/package-builder'...
Creating new container...
58b2160010296f4a71ecf512c1110167eaaac84643495905ed0f788eb78aa328
Changed builder uid/gid... (this may take a while)
groupmod: GID '20' already exists
psnively@Ragnarok:~/projects/termux-packages|master 
⇒  ./scripts/run-docker.sh ./build-package.sh -a x86_64 -D openjdk-9-jre-headless
Running container 'termux-package-builder' from image 'termux/package-builder'...
ERROR: Dependencies for openjdk-9-jre-headless could not be calculated (skip dependency check with -s)
psnively@Ragnarok:~/projects/termux-packages|master 
⇒  ./scripts/run-docker.sh ./build-package.sh -a x86_64 -D -s openjdk-9-jre-headless
Running container 'termux-package-builder' from image 'termux/package-builder'...
Downloading https://raw.githubusercontent.com/termux/termux-elf-cleaner/v1.1/termux-elf-cleaner.cpp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5668  100  5668    0     0  25697      0 --:--:-- --:--:-- --:--:-- 25763
termux - building openjdk-9-jre-headless for arch x86_64...
Downloading http://hg.openjdk.java.net/mobile/dev/archive/b0ac0fef5b92.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  786k    0  786k    0     0   405k      0 --:--:--  0:00:01 --:--:--  405k
Wrong checksum for http://hg.openjdk.java.net/mobile/dev/archive/b0ac0fef5b92.tar.bz2:
Expected: b269c630374c181840c126f8e82cd799147b556482cad3231c577741d0718373
Actual:   1a736f7dc36f6859dccaaeebc90963028ca505a7697343ec31da3191e0e94cb3
```

**Comment by PaulAtBanno** [comment]
@vishalbiswas: So far, your test packages are working perfectly, by which I mean "well enough to support bootstrapping Scala's sbt build tool, compile a 'Hello, world!' in Scala, and run it." I haven't thrown anything heavier-weight at it just yet, but plan to soon-ish. Thank you so much!

**Comment by vishalbiswas** [comment]
Only x86 then. ARM packages cause hell.

**Comment by PaulAtBanno** [comment]
I'd like to contribute, but per the above, I an't even build the package successfully. Any hints on how to resolve that? Thanks so much!

**Comment by vishalbiswas** [comment]
@PaulAtBanno I have update the package at https://github.com/vishalbiswas/termux-packages/tree/openjdk
Please check whether that works

**Comment by its-pointless** [comment]
@vishalbiswas curently using docker image the build fails because the local /usr/bin/g++ doesn't link properly. i needed -lpthread -ldl at end of line but its at beginning so linking fails since it can't find pthread and libdl symbols.

_Sent from my Htc HTC 2PS6200 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by its-pointless** [comment]
Command that fails
/usr/bin/g++ -ldl -lpthread -Wl,-z,defs -Wl,-z,noexecstack -Wl,-O1 -Wl,-z,relro -static-libstdc++ -static-libgcc -shared -Wl,-version-script=/home/builder/.termux-build/openjdk-9-jre-headless/build/buildjdk/hotspot/variant-server/libjvm/mapfile -Wl,-soname=libjvm.so -o /home/builder/.termux-build/openjdk-9-jre-headless/build/buildjdk/support/modules_libs/java.base/server/libjvm.so @/home/builder/.termux-build/openjdk-9-jre-headless/build/buildjdk/hotspot/variant-server/libjvm/objs/_BUILD_LIBJVM_objectfilenames.txt -lm -lc

Command it needs to work
/usr/bin/g++ -ldl -lpthread -Wl,-z,defs -Wl,-z,noexecstack -Wl,-O1 -Wl,-z,relro -static-libstdc++ -static-libgcc -shared -Wl,-version-script=/home/builder/.termux-build/openjdk-9-jre-headless/build/buildjdk/hotspot/variant-server/libjvm/mapfile -Wl,-soname=libjvm.so -o /home/builder/.termux-build/openjdk-9-jre-headless/build/buildjdk/support/modules_libs/java.base/server/libjvm.so @/home/builder/.termux-build/openjdk-9-jre-headless/build/buildjdk/hotspot/variant-server/libjvm/objs/_BUILD_LIBJVM_objectfilenames.txt -lm -lc -lpthread -ldl
Only way i have gotten it to compile is to into sysroot/usr/lib in tool chain and 
ln -s libc.so libpthread.so
And then edit the patches so to not remove -lpthread then both local and tool chain stuff compiles

_Sent from my Htc HTC 2PS6200 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by its-pointless** [comment]
PaulAtBanno
if you want ill up my working* branch if you really are interested. It will at least get you a starting point.

* definition of working is subject to interpretation.

**Comment by PaulAtBanno** [comment]
@vishalbiswas, that is amazing work. I would most definitely like to help
with your "working" branch. Hopefully we can push "working" to a definition
most people will find suitable. :-) Thanks so much for your help!

**Comment by its-pointless** [comment]
https://github.com/its-pointless/termux-packages/tree/openjdk-wip 
the issue is with linking. the pthread lib stuff on android is in libc.so so there is no libpthread.so to link to so it fails. What i do is goto the cross compiler sysroot
example: 
cd  ~/.termux-build/_lib/15.2-i686-21-v12/sysroot/usr/lib
ln -s libc.so libpthread.so 
that should make it build fine.

**Comment by vishalbiswas** [comment]
Or you can change the openjdk-target to <arch>-linux-android[eabi], which will strip down some other functionality but give you a better compilation experience.

**Comment by PaulAtBanno** [comment]
@its-pointless: Sorry I'm late with this response, but I cloned your repo, checked out your `openjdk-wip` branch, and went through the following steps:

1. Launched Docker for Mac.
2. ```⇒  ./scripts/run-docker.sh ./build-package.sh -a i686 -D openjdk-9-jre-headless
Running container 'termux-package-builder' from image 'termux/package-builder'...
ERROR: Dependencies for openjdk-9-jre-headless could not be calculated (skip dependency check with -s)
```
3. `./scripts/run-docker.sh ./build-package.sh -a i686 -D -s openjdk-9-jre-headless`. This got a ways down the road before complaining that it couldn't find the dependency on `freetype`, of course.
4. `./scripts/run-docker.sh ./build-package.sh -a i686 freetype`. Obviously, this is a perfectly good supported package, so it built without a hitch.
5. Retried `./scripts/run-docker.sh ./build-package.sh -a i686 -D -s openjdk-9-jre-headless`. This also went without a hitch this time, depositing the expected `.deb`s in the `debs` directory.

I've installed them on my Chromebook, but not actually used them for anything yet. But I wanted to report on the successful build process anyway. Thanks for your help!

**Pull request merged**
