### PR TITLE
boost: Update from 1.65.1 to 1.67.0

### PR DESCRIPTION
**Pull request by tomty89**

### CODE REVIEW

**Comment by its-pointless** [comment]
It is necesary to link with python because of the android linker. Opencv wouldh't work properly without doing that.

**Comment by its-pointless** [comment]
It would literally error out can;t find python symbol etc. Without linking with python it simply won't import lib without error.
So yes it was like that for a reason.

**Comment by tomty89** [comment]
Have the include line back and add python to TERMUX_PKG_BUILD_DEPENDS, as apparently its pyconfig.h is necessary and used:
```
clang-linux.compile.c++.without-pth bin.v2/libs/python/build/clang-linux-aarch64/release/target-os-android/threading-multi/list.o

In file included from libs/python/src/list.cpp:5:

In file included from ./boost/python/list.hpp:8:

In file included from ./boost/python/detail/prefix.hpp:13:

./boost/python/detail/wrap_python.hpp:50:11: fatal error: 'pyconfig.h' file not found

# include <pyconfig.h>

          ^~~~~~~~~~~~

1 error generated.



  "aarch64-linux-android-clang++" -c -x c++ -fPIC -O3 -Wall -Wno-inline  -Oz -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE -DNDEBUG -I"." -I"/data/data/com.termux/files/usr/include" -I"/usr/include/python2.7" -o "bin.v2/libs/python/build/clang-linux-aarch64/release/target-os-android/threading-multi/list.o" "libs/python/src/list.cpp"



...failed clang-linux.compile.c++.without-pth bin.v2/libs/python/build/clang-linux-aarch64/release/target-os-android/threading-multi/list.o...

clang-linux.compile.c++.without-pth bin.v2/libs/python/build/clang-linux-aarch64/release/target-os-android/threading-multi/long.o

In file included from libs/python/src/long.cpp:5:

In file included from ./boost/python/long.hpp:8:

In file included from ./boost/python/detail/prefix.hpp:13:

./boost/python/detail/wrap_python.hpp:50:11: fatal error: 'pyconfig.h' file not found

# include <pyconfig.h>

          ^~~~~~~~~~~~

1 error generated.



  "aarch64-linux-android-clang++" -c -x c++ -fPIC -O3 -Wall -Wno-inline  -Oz -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE -DNDEBUG -I"." -I"/data/data/com.termux/files/usr/include" -I"/usr/include/python2.7" -o "bin.v2/libs/python/build/clang-linux-aarch64/release/target-os-android/threading-multi/long.o" "libs/python/src/long.cpp"



...failed clang-linux.compile.c++.without-pth bin.v2/libs/python/build/clang-linux-aarch64/release/target-os-android/threading-multi/long.o...

...failed updating 2 targets...

...updated 14824 targets...

Error building boost
```
(https://api.travis-ci.org/v3/job/372654579/log.txt)

For whatever reason, /usr/include/python2.7/pyconfig.h om the build host is not found/used. Maybe it's a good thing though since pyconfig.h probably indicates the capabilities of the specific python build.

**Comment by tomty89** [comment]
I am not seeing the sense in this. Even on desktop distros libboost_python isn't linked (at the very least not dynamically) against libpython. Where comes the problem with opencv and the android linker?

Btw there's a chance that the libboost_python that we have been shipping was built for python2, if it was built on Ubuntu but not Arch, as `python` is python2 on Ubuntu AFAIK. The bootstrap script by default does version detection with the `python` executable and hence can only rely on the host python. Worsestill it was forced to use the python3 headers of the Termux build.

Even my last commit was not alright, because apparently `./b2 clean` doesn't force a rebuilt, and instead I need to use `-a`. Will repush an updated version of the last two commit soon. Would be great if you can help testing @its-pointless

**Comment by tomty89** [comment]
Btw it's probably not a must to build libboost_python against Termux python. In fact I am not sure if either way is better or safer. Apparently the Travis CI image doesn't have python-dev and python2-dev installed though, so build test will fail if I use host python builds instead.

One good thing about using host python might be that it may allow us to build numpy bindings, if they are desired, since on Termux we rely on pip which can't really be used in the build system.

**Comment by Grimler91** [comment]
> Even on desktop distros libboost_python isn't linked (at the very least not dynamically) against libpython. Where comes the problem with opencv and the android linker?

See comments in https://github.com/termux/termux-packages/issues/1992 for background why ˋ-lpython3.6mˋ was needed.

See https://github.com/android-ndk/ndk/issues/201 for discussion about the differences in the linkers.

**Comment by tomty89** [comment]
@Grimler91 Well I failed to see that any libraries in opencv (including the `cv2` ones for python) actually make use of any of boost libraries in any way, including but not limited to libboost_python. I have no idea how you have come to the conclusion that one should forcefully link opencv against libboost_python (and in turn forcefully link libboost_python against libpython).

Apparently you thought that `PyFloat_Type` is something specific to libboost_python, because you bumped into a bug report that mentioned it (where the error is not even the same), of a project that makes use of libboost_python; but it is not:
```
$ readelf -Ws ../usr/lib/libpython3.6m.so.1.0 | grep PyFloat_Type
   192: 00000000001f35a8   400 OBJECT  GLOBAL DEFAULT   16 PyFloat_Type
$
```

The OP never even return to report that `-lboost_python` actually helped in his case. To be honest, even if it does help magically, it still doesn't mean it's the right way, coz it really doesn't make any sense.

**Comment by its-pointless** [comment]
Symbol visibility when opening shared libraries using dlopen() works differently. On a normal linker, when an executable linking against a shared library libA dlopen():s another shared library libB, the symbols of libA are exposed to libB without libB needing to link against libA explicitly. This does not work with the Android linker, which can break plug-in systems where the main executable dlopen():s a plug-in which doesn't explicitly link against some shared libraries already linked to by the executable. See the relevant NDK issue for more information.

**Comment by Grimler91** [comment]
Looking back, it seems a bit weird that libboost_python is needed so you might be right here @tomty89.

I tried recompiling without `-lboost_python` and with `-lpython3.6m` but got the same error as before: `dlopen failed: cannot locate symbol "PyFloat_Type" referenced by "/data/data/com.termux/usr/lib/python3.6/site-packages/cv2.cpython-36m.so` so just setting LDFLAGS=-lpython3.6m doesn't work but linking against boost_python works for some reason. 

Sidenote for @its-pointless : I also received an error first that header numpy/ndarrayobject.h couldn't be found, I solved it by symlinking `site-packages/numpy-1.14-......./numpy/core/include/numpy/` to `$PREFIX/include`.

**Comment by tomty89** [comment]
@its-pointless The difference / issue of the Android linker isn't relevant here. As I've said, the `cv2` library isn't even written with boost in mind, but only python and numpy. The decision that libboost_python should be linked to libpython was based on something that is even sensical (linking opencv against libboost_python, that is).

@Grimler91 I am not sure how much support you can get from developers of opencv for this, but I do think it should be reported upstream (whether the reason is the android linker as @its-pointless said or not). AFAIR they do/did have at least some intention to support Android.

As for why the two forced linkage workaround the error, I have no idea. My guess is because libboost_python was malformed, and hence it somehow fits the taste of the broken `cv2` library.

**Comment by tomty89** [comment]
From https://github.com/android-ndk/ndk/issues/201#issuecomment-248060092:
> On Android only the main executable and LD_PRELOADs are considered to be RTLD_GLOBAL, all the dependencies of the main executable remain RTLD_LOCAL.

> ld-linux.so marks everything linked against main executable with RTLD_GLOBAL, this is why the example works on Linux.

> Adding libshared.so dependency to libplugin.so should solve this problem

I guess the problem is, because we have libpython built on Termux as most distros do, the symbols of the Python C-API are in libpython and are marked with RTLD_LOCAL and are hence not available for python extensions as they are on desktop distros.

When I test with the example "spam" in https://docs.python.org/3.6/extending/index.html, the results are coherent to the quoted statements:

```
$ clang -shared -I ../usr/include/python3.6m spam.c -o spam.so
$ python -c 'import spam'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen failed: cannot locate symbol "PyArg_ParseTuple" referenced by "/data/data/com.termux/files/home/spam.so"...
$ clang -shared -I ../usr/include/python3.6m -lpython3.6m spam.c -o spam.so
$ python -c 'import spam'
$
```

```
$ clang -shared -I ../usr/include/python3.6m spam.c -o spam.so
$ python -c 'import spam'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen failed: cannot locate symbol "PyArg_ParseTuple" referenced by "/data/data/com.termux/files/home/spam.so"...
$ LD_PRELOAD=$PREFIX/lib/libpython3.6m.so python -c 'import spam'
$
```

So the only remaining question is why `-lpython3.6m` doesn't work for the `cv2` library.

@Grimler91 Have you confirmed that the linkage has actually been applied to the `cv2` library by checking it with ldd? (I mean, could `-lpython3.6m` but not `-lboost_python` somehow got filtered/ignored?) Also can you test if the LD_PRELOAD method works for the `cv2` library?

P.S. I think it's clear enough that libboost_python is not relevant in the problem at all now.

**Comment by Grimler91** [comment]
@tomty89 Awesome, so that's the proper fix.. 
Annoying that the normal LDFLAGS=... didn't work.

**Comment by its-pointless** [comment]
you can enable coroutine and context but to do so we have to compile the assembler files. This needs 
architecture=arm  \
         abi=aapcs \
         binary-format=elf  \

in the command line for arm and arm64 and for i686 and x86_64 its
architecture=x86 \
abi=sysv \
binary-format=elf \


since for compabititlity all packages which are linked against c++ are going to be recompiled to work with new libc++_shared.so may as well update this as well since all packages that link against boost have to updated on boost update.

**Comment by its-pointless** [comment]
https://github.com/moritz-wundke/Boost-for-Android/issues/130

**Comment by fornwall** [comment]
Nice work! The updated package is available (with the updates in https://github.com/termux/termux-packages/pull/2425 to enable coroutine and context).

**Pull request merged**
