### PR TITLE
upgpkg(main/nodejs): v19.4.0

### LINKED ISSUE #14106: [Package]: nodejs 19.3.0
### Why do you want to add this package to Termux?

i think newer version of nodejs will be better

### Home page URL

https://nodejs.org/en/download/current/

### Source code URL

https://nodejs.org/dist/v19.3.0/node-v19.3.0.tar.gz

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by thunder-coding**
Will run the test suite locally once CI finishes. Also there's update for libicu, will make sure that there's no regression.

Closes #14106 

- [X] Update to v19
- [X] Make sure no regressions are there
- [ ] ~~Use Ninja with GYP (in progress)~~
- [ ] ~~Run tests again to ensure nothing broke~~
Migration to Ninja may be done later

### CODE REVIEW

**Comment by licy183** [comment]
How about adding a command named `termux-setup-npm`, which will apply the patch for `cacache`?
If someone updates `npm` manually, he/she could run that command and apply the patch. We could remove this custom command until upstream fix this issue.

**Comment by thunder-coding** [comment]
> How about adding a command named `termux-setup-npm`, which will apply the patch for `cacache`? If someone updates `npm` manually, he/she could run that command and apply the patch. We could remove this custom command until upstream fix this issue.

The problem with this approach is that this patch won't gauranteedly work on all versions of npm. Also users can install specific versions themselves. Making it better for users to do the patch work manually instead of using a script do the same (which can also be disastrous in certain cases)

**Comment by 2096779623** [comment]
The latest version of `nodejs-lts` is `18.12.1`, please update it.

**Comment by thunder-coding** [comment]
> The latest version of `nodejs-lts` is `18.12.1`, please update it.

I'll be going as usual, first current version then LTS, also users will need some time to migrate their apps

**Comment by truboxl** [comment]
Any reason why we dont decouple and provide `npm` separately?

I do agree it is still better to fix it upstream.

**Comment by thunder-coding** [comment]
> Any reason why we dont decouple and provide npm separately?

Sure we can do this, :+1: from my side.

Btw, I am planning to switch from make to ninja for building nodejs. Should also help reduce build time by a small extent. 
https://github.com/minrk/node/commit/5e533cb943eef68b270f55f0cba02c0ec67c699d
https://github.com/nodejs/node/blob/main/doc/contributing/building-node-with-ninja.md

**Comment by thunder-coding** [comment]
This PR is now targetting v19.4.0. Will be pulled quickly after testing along with updating nodejs-lts to v18.13.0

**Pull request merged**
