### PR TITLE
q-dns-client: Bump to 0.11.2

### PR DESCRIPTION
**Pull request by CHIZI-0618**

### CODE REVIEW

**Comment by xtkoba** [comment]
If you use a source tarball then Git commit ID cannot be obtained in the following line:

https://github.com/termux/termux-packages/blob/c18e8d8816cce461a0c1c55d653b9ac72dc1ce5b/packages/q-dns-client/build.sh#L25

Please either remove this line or keep using the Git repository as the source. The former is no problem as it just makes the commit ID in the version string "unknown".

**Comment by xtkoba** [comment]
(Please do not specify the commit ID directly in the `build.sh` again. It just makes the maintenance of the package more difficult.)

**Comment by CHIZI-0618** [comment]
> Please either remove this line or keep using the Git repository as the source. (Please do not specify the commit ID directly in the build.sh again. It just makes the maintenance of the package more difficult.)

How do I do the sha256 check if I change back to the git source and don't specify a commit ID?

**Comment by xtkoba** [comment]
The branch defaults to `v${TERMUX_PKG_VERSION}`. So:

```bash
git clone --depth=1 --single-branch --branch=v0.11.2 https://github.com/natesales/q
cd q
find . -type f ! -path '*/.git/*' -print0 | xargs -0 sha256sum | LC_ALL=C sort | sha256sum
```

**Comment by xtkoba** [comment]
Or you may skip the checksum; just remove the `TERMUX_PKG_SHA256` line and the `termux_step_post_get_source` paragraph. This is allowed for Git repositories or rather is the default. Not a good practice though.

**Comment by CHIZI-0618** [comment]
> The branch defaults to `v${TERMUX_PKG_VERSION}`. So:
> 
> ```shell
> git clone --depth=1 --single-branch --branch=v0.11.2 https://github.com/natesales/q
> cd q
> find . -type f ! -path '*/.git/*' -print0 | xargs -0 sha256sum | LC_ALL=C sort | sha256sum
> ```

As you wish

**Pull request merged**
