### PR TITLE
Add erlang package

### PR DESCRIPTION
**Pull request by remvee**
Tested build using docker.  I am not sure about the way the openssl dependency is handled in the build script but it works when you first build openssl.

Erlang runs fine on a Nexus 5 with stock Android 6.  I've tested [a small example webserver](http://stackoverflow.com/questions/2206933/how-to-write-a-simple-webserver-in-erlang#2219330) and even got elixir to compile and install, after some fiddling (shebang stuff) on the target and successfully ran some scripts I wrote.

### CODE REVIEW

**Comment by its-pointless** [comment]
It fails to build if termux version of pcre is built before it. It uses its own version of pcre and fails with normal pcre.

**Comment by remvee** [comment]
@its-pointless: thanks for the pointer.

**Comment by cdarne** [comment]
I've compiled this branch with the docker build env and I've successfully got it installed on my Nexus 5 as well. I've been able to get an Elixir project running. 👍

**Comment by fornwall** [comment]
Thanks a lot! The `erlang` package is now available (updated to the latest 19.2 version) for installation with `apt update && apt install erlang`.

**Pull request merged**
