### PR TITLE
Add nyancat package

### PR DESCRIPTION
**Pull request by TheDiamondYT1**
Because everyone loves a nyancat.

### CODE REVIEW

**Comment by Neo-Oli** [comment]
Why was this closed?

**Comment by TheDiamondYT1** [comment]
I think i did the build.sh wrong

**Comment by Neo-Oli** [comment]
I see. I tried to build it and there where indeed some problems. I looked at it and wrote a short tutorial on how I managed to build nyancat. 
```
TERMUX_PKG_HOMEPAGE=http://nyancat.dakko.us
TERMUX_PKG_DESCRIPTION="Nyancat in your terminal, rendered through ANSI escape sequences."
TERMUX_PKG_VERSION=1.5.1
TERMUX_PKG_SRCURL=https://github.com/klange/nyancat/archive/${TERMUX_PKG_VERSION}.tar.gz
# If the decompressed foldername differs from the SRCURL filename it needs to be specified
TERMUX_PKG_FOLDERNAME=nyancat-$TERMUX_PKG_VERSION
# Some programms don't work well when built outside the source directory
TERMUX_PKG_BUILD_IN_SRC=yes
# clang is not needed. The build environment provides a compiler. The compiled binary no longer needs the compiler (unlike, for example, a python application)
# TERMUX_PKG_DEPENDS="clang"
# since it's compiled C code, it will need to be compiled for each arch separately, therefore you can't put it as platfom independent
# TERMUX_PKG_PLATFORM_INDEPENDENT=yes
```

 My build script without comments: 
```
TERMUX_PKG_HOMEPAGE=http://nyancat.dakko.us
TERMUX_PKG_DESCRIPTION="Nyancat in your terminal, rendered through ANSI escape sequences."
TERMUX_PKG_VERSION=1.5.1
TERMUX_PKG_SRCURL=https://github.com/klange/nyancat/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_FOLDERNAME=nyancat-$TERMUX_PKG_VERSION
TERMUX_PKG_BUILD_IN_SRC=yes
```

Unfortunately nyancat's Makefile is pretty poor and it also needs the following patch to build correctly and put the binary and the manpage into the right directory. Put this in a file named makefile.patch (will get applied automatically while building)
```
diff --git a/Makefile b/Makefile
index 8d68431..6653583 100644
--- a/Makefile
+++ b/Makefile
@@ -33,7 +33,9 @@ distcheck: $(distdir).tar.gz
        @echo "*** Package $(distdir).tar.gz is ready for distribution."

 install: all
-       install src/nyancat /usr/bin/${package}
-       gzip -9 -c < nyancat.1 > /usr/share/man/man1/nyancat.1.gz
+       install -d "$(DESTDIR)$(PREFIX)/bin"
+       install -d "$(DESTDIR)$(PREFIX)/share/man/man1"
+       install src/nyancat "$(DESTDIR)$(PREFIX)/bin/nyancat"
+       install -m644 nyancat.1 "$(DESTDIR)$(PREFIX)/share/man/man1/nyancat.1"

 .PHONY: FORCE all clean check dist distcheck install

```
I created this by cloning the repository of nyancat, making the necessairy changes to the makefile and running `git diff > ~/termux-packages/packages/nyancat/makefile.patch` which writes a diff of the programm to the makefile.patch file.


When building packages, you really should test the build process. It's easiest to use docker for this.
On a ubuntu other debian you can run `sudo apt install docker.io` to then build the package (and all it's dependencies you can run:
```
cd termux-packages
sudo ./scripts/run-docker.sh ./clean.sh #this removes previously built packages
for p in `./scripts/buildorder.py nyancat`; do #get the order of which the packages need to be built
    ./scripts/run-docker.sh ./build-package.sh -aall $p; #build all packages. -aall builds it for all architectures. You can specify only yours for faster building
done
```
after that the packages are in the termux-packages/debs folder. Copy the .deb corresponding to your arch to your Android device. Then you can install it with `dpkg -i nyancat_1.5.1_aarch64.deb`

**Comment by TheDiamondYT1** [comment]
I succesfully built it from source just by using `make` so why do  you need a patch?

**Comment by TheDiamondYT1** [comment]
Also i do not have access to a linux / ubuntu machine.

**Comment by Neo-Oli** [comment]
Because cross compiling for termux is a deal more complicated than building from source. All files need to be installed with `install`, otherwise they won't get picked up by the packager. 
Also docker is available on a number of operating systems. Just look up a guide on whatever OS you're on.

**Comment by TheDiamondYT1** [comment]
Windows 10

**Comment by Neo-Oli** [comment]
Do you want to try again or should I go ahead and submit my own PR? You know, since I already did the work, I might as well. But if you try again you can add yourself as a package maintainer.

**Comment by TheDiamondYT1** [comment]
You can do it

**Pull request closed without merging**
