### PR TITLE
nodejs: Try compile using new NDK

### PR DESCRIPTION
**Pull request by thunder-coding**
Well v8 should compile with the new NDK since they use the NDK from `master` branch and update it on a weekly basis. And for core part of nodejs it should work, but I feel that dependencies of nodejs may give some trouble. 

This PR tries to compile nodejs using NDK r23.

### CODE REVIEW

**Comment by thunder-coding** [comment]
Seems like the CI is stuck somewhere in an infinite loop. I am staring at the logs since more than an hour and no logging activity there. It would be great if someone can stop the CI so that I can investigate....

**Comment by agnostic-apollo** [comment]
Done.

**Comment by thunder-coding** [comment]
By comparing log output with https://github.com/unicode-org/icu/blob/release-69-1/icu4c/source/configure

https://github.com/unicode-org/icu/blob/0e7b4428866f3133b4abba2d932ee3faa708db1d/icu4c/source/configure#L3682 corresponds to the last line in log. And this is the yes thing after it https://github.com/unicode-org/icu/blob/0e7b4428866f3133b4abba2d932ee3faa708db1d/icu4c/source/configure#L3743

So the infinite loop problem is somewhere below that but at the same time very near to line 3743 in configure

**Comment by thunder-coding** [comment]
@agnostic-apollo, the CI seems to be again stuck inside an infinite loop 😅

**Comment by agnostic-apollo** [comment]
Gosh, if by "maintaing nodejs" you meant making CI to get stuck in an infinite loop, I think I can do this too, we can even put Yonle up for that if I'm busy 😂

**Comment by thunder-coding** [comment]
Closing this PR, since I feel that I need to have some more experience for teasing with the new NDK. I atleast hope that with my comments here, Grimler can atleast get an idea of what's wrong here.

**Comment by agnostic-apollo** [comment]
And there goes our esteemed maintainer... 😂

Could have just sprinkled some print statements to maybe get more of a clue where exactly its getting stuck.

**Comment by Yonle** [comment]
> we can even put Yonle up for that if I'm busy 
Say one more time and i will turn yourself became CI

**Comment by Yonle** [comment]
Alright alright. I'ma gonna test it once somebody managed to get it compiled.

**Comment by agnostic-apollo** [comment]
> Say one more time and i will turn yourself became CI

Well, you can guess whose pull requests are gonna start getting auto-rejected :p

**Pull request closed without merging**
