### PR TITLE
chore(scripts): Remove TERMUX_PKG_ENABLE_CLANG16_PORTING

### PR DESCRIPTION
**Pull request by fornwall**
The `TERMUX_PKG_ENABLE_CLANG16_PORTING` variable should no longer be necessary as the transition is complete, and packages have adopted to building with modern clang (patches or build flags) where necessary, and any external package should do the same.

Ping @xtkoba.

### CODE REVIEW

**Comment by finagolfin** [comment]
xtkoba does not contribute here anymore: @licy183, @truboxl or @TomJo2000, any opinion?

**Review by licy183 — APPROVED** [review]
I think it can be removed too.

**Comment by truboxl** [comment]
The whole `CMAKE_TERMUX_TOOL_C_COMPILER` can also be removed as it was added in https://github.com/termux/termux-packages/commit/0ead023121901676ce6a731e29fbd7b8fccb5db0. Can also revert that commit.

**Comment by fornwall** [comment]
> The whole `CMAKE_TERMUX_TOOL_C_COMPILER` can also be removed as it was added in [0ead023](https://github.com/termux/termux-packages/commit/0ead023121901676ce6a731e29fbd7b8fccb5db0). Can also revert that commit.

@truboxl Thanks! Pushed another commit here removing `CMAKE_TERMUX_TOOL_C_COMPILER`: 5723e5f4d118e4967066e4d11d3695c144ff4688. Looks good?

**Comment by TomJo2000** [comment]
Should be resolved by now, and we're at Clang/LLVM 18 by now, should be fine to remove it.

**Pull request merged**
