### PR TITLE
add package: yazi

### LINKED ISSUE #18935: [Package]: yazi
### Why is it worth to add this package?

Yazi is a blazing fast terminal file manager written in Rust, based on async I/O.

### Home page URL

https://yazi-rs.github.io/

### Source code URL

https://github.com/sxyazi/yazi

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes #18935

### CODE REVIEW

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/pull/11913#issuecomment-1245518847

We need to tell the user to use nerd font or hack font to display the icon normally.

**Comment by Biswa96** [comment]
> We need to tell the user to use nerd font or hack font to display the icon normally.

Thank you for the review. I have added that function. I was wondering if the similar function should be added for lsd, eza etc. packages also.

**Comment by 2096779623** [comment]
> Thank you for the review. I have added that function. I was wondering if the similar function should be added for lsd, eza etc. packages also.

`eza` does not enable icons by default, I think some users need it, this is a good idea, welcome to PR.

**Review by 2096779623 — APPROVED** [review]

**Comment by TomJo2000** [comment]
A general recommendation to install a NerdFont for using `yazi`, `eza`, `starship`, `neovim`, `neofetch`(or any of the other stat fetcher applications) is probably a good idea.

You might also want to add `nerdfix` in the `TERMUX_PKG_SUGGESTS` field to help in spotting and replacing obsolete NerdFont 2.x symbols.

**Comment by 2096779623** [comment]
BTW, you can add termux installation method in [the docs](https://yazi-rs.github.io/docs/installation/).

**Comment by TomJo2000** [comment]
We might also want to consider shipping a NerdFont by default in the future, but I don't wanna start any bike shedding.

**Comment by TomJo2000** [comment]
> You might also want to add `nerdfix` in the `TERMUX_PKG_SUGGESTS` field to help in spotting and replacing obsolete NerdFont 2.x symbols.

I just noticed I was a bit late on that suggestion.
I'll open up a separate PR and get to it when I get home.

**Comment by 2096779623** [comment]
> You might also want to add `nerdfix` in the `TERMUX_PKG_SUGGESTS` field to help in spotting and replacing obsolete NerdFont 2.x symbols.

I have tested many fonts using nerdfix and there is no problem. The f-droid version of termux-styling's nerd font version is `3.0.2` .

**Comment by TomJo2000** [comment]
I think part of the confusion here is that `nerdfix` doesn't operate on the font files.
It finds obsolete codepoints in (configuration) files and suggests the corresponding replacements.

**Comment by 2096779623** [comment]
In the AUR, yazi has many dependencies for optimizing user experience. I recommend adding these to `TERMUX_PKG_DEPENDS` or `TERMUX_PKG_SUGGESTS` .
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yazi-git#n13

**Comment by TomJo2000** [comment]
The `optdepends` field in AUR package builds is analogous to our `TERMUX_PKG_SUGGESTS` field.
I'll fold it in with #19104
Which I did still manage to forget about when I got home yesterday despite opening it specifically so I wouldn't forget about it.

**Pull request merged**
