### PR TITLE
bad sed statement with tsocks

### PR DESCRIPTION
**Pull request by Justsoos**
not work with `source tsocks off`, there is no `\?`

### CODE REVIEW

**Comment by xeffyr** [comment]
Your patch is not working.
```
bash-4.4$ source tsocks on
bash-4.4$ echo $LD_PRELOAD
/data/data/com.termux/files/usr/lib/libtsocks.so
bash-4.4$ source tsocks off
bash-4.4$ echo $LD_PRELOAD
/data/data/com.termux/files/usr/lib/libtsocks.so
```

Busybox's sed doesn't understand `\?`, install a normal sed (`pkg install sed`) and everything will be fine:
```
bash-4.4$ source tsocks on
bash-4.4$ echo $LD_PRELOAD
/data/data/com.termux/files/usr/lib/libtsocks.so
bash-4.4$ source tsocks off
bash-4.4$ echo $LD_PRELOAD

bash-4.4$
```

I suggest you to add a `sed` dependency to build.sh:
```
## for bin/tsocks script
TERMUX_PKG_DEPENDS="sed"
```

**Comment by Justsoos** [comment]
@xeffyr , the sed ver is the key, but my default installation of Termux from F-Droid, the $LD_PRELOAD is alwasy being, and busybox sed is the default config.
```
$ echo $LD_PRELOAD
/data/data/com.termux/files/usr/lib/libtermux-exec.so
$ source tsocks on
$ echo $LD_PRELOAD
/data/data/com.termux/files/usr/lib/libtsocks.so /data/data/com.termux/files/usr/lib/libtermux-exec.so
$ source tsocks off
$ echo $LD_PRELOAD
/data/data/com.termux/files/usr/lib/libtermux-exec.so
```
busybox sed is a BRE, basic syntax, can not treat `\?` as a escape meaning as ERE, extended syntax, but `*` is good in any case, so, I think, at least to get rid of this bug of termux, we could modify the patch with `blank + *`.

**Comment by Justsoos** [comment]
test works, to any case, busybox sed or not, $LD_PRELOAD empty or not, with:
`echo -n $LD_PRELOAD | sed "s:/data/data/com.termux/files/usr/lib/libtsocks.so *::"`
https://github.com/termux/termux-packages/pull/2475/commits/b8cb2902101f5ab53851b7e7126db1eaa358bb31

**Comment by xeffyr** [comment]
Yes, after https://github.com/termux/termux-packages/pull/2475/commits/b8cb2902101f5ab53851b7e7126db1eaa358bb31 works with both busybox and GNU sed.

**Comment by fornwall** [comment]
Thanks - the updated package at version `1.8beta5-2` is now available for installation!

**Pull request merged**
