### PR TITLE
ci(package_updates): allow dry run auto update in PR

### PR DESCRIPTION
**Pull request by truboxl**

### CODE REVIEW

**Comment by truboxl** [comment]
I copied mostly from packages.yml with a bit of testing on my own repo. 😓
But feel free fix any bugs arise.

**Comment by TomJo2000** [comment]
I assume this will automatically try to validate the autoupdate function when a PR is pushed containing one?

**Comment by truboxl** [comment]
Welp already got token error. I guess need to see how to fix this.

**Comment by truboxl** [comment]
Ok good news switching to GITHUB_TOKEN works. You should now be able to test if auto update request is working or not before merging a PR.

**Pull request merged**
