### PR TITLE
update angle-android (2024.12.13)

### PR DESCRIPTION
**Pull request by ar37-rs**
latest main now correctly being built: with significant improvement
Screenshot_2024-12-13_15-10-35

### CODE REVIEW

**Comment by TomJo2000** [comment]
Congratulations, it's a merge conflict.

You're gonna need to clean up this branch, it should only contain a single update commit to the `angle-android` build script.
Please also make sure to follow the commit message format [laid out in the contribution guidelines](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#commit-guidelines).

**Comment by TomJo2000** [comment]
On a procedural note.
Using a `git rebase` workflow is going to be ***significantly*** easier than a merge based workflow for short lived feature branches.

`git rebase` rewrites the branch history to instead place the start of the branch at a different point on the parent branch.
This is absolutely fine for a PR as it by definition contains new changes not yet present in the upstream.
And it crucially avoids introducing useless merge commits which complicate the git history of the branch and increase the likelihood of merge conflicts as they progressively apply parallel commit histories which will tend more toward divergence.

A rebase workflow also makes maintaining tidy commits on the feature branch easier as you can simply update commits using `git commit --amend` or `git rebase --interactive` instead of having every incremental revision of the PR tracked by its branch.

**Comment by ar37-rs** [comment]
> Congratulations, it's a merge conflict.
> 
> You're gonna need to clean up this branch, it should only contain a single update commit to the `angle-android` build script. Please also make sure to follow the commit message format [laid out in the contribution guidelines](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#commit-guidelines).

oh ok, forgot to rebase

**Comment by TomJo2000** [comment]
You can keep this same PR for the updated version.
You just need to rebase the branch or make a new branch with the same name and fixed commit history and force push it.

**Pull request closed without merging**
