### PR TITLE
Add mirror: cdn.lumito.net (UK)

### PR DESCRIPTION
**Pull request by LumitoLuma**
|Repository|sources.list entry|
|-|-|
|[Main](https://github.com/termux/termux-packages)|`deb https://cdn.lumito.net/termux/termux-main stable main`|
|[Root](https://github.com/termux/termux-root-packages)|`deb https://cdn.lumito.net/termux/termux-root root main`|
|[X11](https://github.com/termux/x11-packages)|`deb https://cdn.lumito.net/termux/termux-x11 x11 main`|

Mirror also supports HTTP (same URL) and RSYNC (at `rsync://rsync.lumito.net/termux/`). 2 Gb/s. Cloudflare. IPv4 + IPv6. 2 TB/month bandwith. Mirror updated each hour.

### CODE REVIEW

**Review by 2096779623 — APPROVED** [review]

**Comment by 2096779623** [comment]
Please squash the commits and/or rewrite commit messages to match the formats used in [git history](https://github.com/termux/termux-packages/commits/master), or the format specified in #10748.

**Review by 2096779623 — CHANGES_REQUESTED** [review]
Please squash the commits and/or rewrite commit messages to match the formats used in [git history](https://github.com/termux/termux-packages/commits/master), or the format specified in #10748.

**Comment by 2096779623** [comment]
Where is this mirror?

**Comment by LumitoLuma** [comment]
@2096779623 Now it should be fine.

**Review by 2096779623 — APPROVED** [review]

**Pull request merged**
