### PR TITLE
[WIP] Download dependencies instead of building them

### PR DESCRIPTION
**Pull request by Grimler91**
Continuation of https://github.com/termux/termux-packages/pull/1169.

It needs testing but works well for a lot of packages. 

To (speed)build a package with these changes run `./build-package -i pkg`. Dependencies .debs are downloaded with curl and their checksums obtained after the InRelease file has been gpg verified. The bootstraps aren't gpg verified right now though, it might be nice to add a signed list of bootstrap checksums to termux.net/bootstrap/.

If a package can't be found in the repo, or if the local version differs from the repo version, then the local version is built instead.

Doing a `-i` build removes all installed packages from $PREFIX, to give a fresh environment for the build.

Downloaded .debs are put in `_cache-$TERMUX_ARCH`. It might be nice to change ./clean.sh so that it doesn't remove these folders unless some option is given.

Stuff left to do:
- [ ] lldb (error due to it using the llvm-config from `$PREFIX`, I think)
- [ ] ldc (error due to it using the llvm-config from `$PREFIX`, I think)
- [ ] rust (error due to it using the llvm-config from `$PREFIX`, I think)
- [ ] libsoup (minor errors)
- [ ] php (minor errors)
- [ ] php (minor errors)
- [ ] all packages haven't been tested yet

- [ ] It only supports the main repo (and Fornwalls signing key) so far

@xeffyr could you try this PR out with travis/gitlab-CI when you have time?

### CODE REVIEW

**Comment by Wetitpig** [comment]
So the .travis.yml is not going to be changed, right? Because 12 builds diffing between installing dependencies or not is quite unnecessary.

**Comment by Grimler91** [comment]
@Wetitpig I'm basically clueless to how travis works, would be great if you could help clean the .travis.yml script (and open a PR against this branch). 

Running one job for each arch, in parallel, would make sense

**Comment by xeffyr** [comment]
@Grimler91 Got first errors:
```
./build-package.sh: line 516: bootstrap_sha256: unbound variable
Input/output error @ io_fillbuf - fd:10 /dev/pts/1
Error building apt
```

See https://travis-ci.org/xeffyr/termux-packages/jobs/484730271

**Comment by xeffyr** [comment]
After few fixes, builds are successful:
* https://travis-ci.org/xeffyr/termux-packages/jobs/484748555
* https://travis-ci.org/xeffyr/termux-packages/jobs/484748556

**Comment by xeffyr** [comment]
@Grimler91 Package "devscripts" is needed to, otherwise build-package.sh will fail to execute debdiff.

**Comment by xeffyr** [comment]
In file ".travis.yml" we can left only parallel builds with package downloading.

**Comment by Grimler91** [comment]
> Regarding support only for the main repo - I have build caching enabled (both for Travis and Gitlab) which does nearly same thing.

Could you elaborate on that? You mean the CI builds saves the data from previous builds? 

We might want to remove devscripts and the debdiff function entirely once this PR is up and running, but yeah, should be added for now. 

> In file ".travis.yml" we can left only parallel builds with package downloading.

Do you mind fixing that? I still haven't looked into how to setup .travis.yml files

**Comment by xeffyr** [comment]
> Could you elaborate on that? You mean the CI builds saves the data from previous builds?

Yes. It is possible to configure CI to **archive specified directories.**

See speed difference in https://gitlab.com/xeffyr/x11-packages/pipelines/44632668 and https://gitlab.com/xeffyr/x11-packages/pipelines/44636774.

Of course, cache might not be always available so we shouldn't rely on it.

For more information how this work, see

* For Travis CI: recommended to set language to "generic", data directory should be passed to docker image as volume.
  * [travis.yml](https://github.com/termux/x11-packages/blob/master/.travis.yml#L11)
  * [build script](https://github.com/termux/x11-packages/blob/master/scripts/travis-ci-build.sh#L89)
* For Gitlab CI: data directory should be stored in project source tree and bind-mounted to /data. Otherwise caching system won't see it.
  * [gitlab-ci.yml](https://github.com/termux/x11-packages/blob/master/.gitlab-ci.yml#L58)
  * [build script](https://github.com/termux/x11-packages/blob/master/scripts/gitlab-ci-build.sh)

> Do you mind fixing that? I still haven't looked into how to setup .travis.yml files

Yes, I'll do it.

**Comment by xeffyr** [comment]
As further improvement, we can use gpg key from [trusted.gpg](https://github.com/termux/termux-packages/blob/master/packages/apt/trusted.gpg) which already present in source tree. This will completely fix problem with retrieving gpg key from the Internet.

**Comment by Wetitpig** [comment]
@xeffyr Thanks for implementing my proposed changes.

**Comment by Grimler91** [comment]
@xeffyr good idea

**Comment by Grimler91** [comment]
So, let's merge this for now and continue fixing packages over time

**Pull request merged**
