### PR TITLE
Add package ciso

### PR DESCRIPTION
**Pull request by ravener**
Hopefully I've done this corrrectly.

### CODE REVIEW

**Review by Grimler91 — CHANGES_REQUESTED** [review]
`gcc` is hardcoded as compiler in ciso's Makefile, so it has to be patched to use `$(CC)` instead, and preferably CPPFLAGS, CFLAGS and LDFLAGS should also be added to the compile commands (CPPFLAGS and CFLAGS to the generation of `ciso.o` and LDFLAGS to the generation of `ciso`)

And when fixing those things please squash the commits and/or rewrite commit messages to match the formats used in [git history](https://github.com/termux/termux-packages/commits/master), or the format specified in https://github.com/termux/termux-packages/pull/10748. Right now you have one commit with message `typo`, which is not a good description of the commit, and two commits with message `Add package ciso`, which also is weird

**Comment by ravener** [comment]
@Grimler91 I added a patch file, that's hopefully done right. I apologize for the commits, I even made another mistake right now. I'll try to take better note next time. I also did this entirely on the browser with github web so I'm not sure if I can squash or something.

**Comment by ravener** [comment]
ok now I apparently got the patch file wrong. Man I'm so bad at this, I think it's time for me to just rage quit and let someone else take over or else I'm gonna be doing too much trash commits.

**Comment by Grimler91** [comment]
Patch should hopefully work if you just replace `--- Makefile` with `--- ./Makefile` and `+++ Makefile-patch` with `+++ ./Makefile`

**Comment by Grimler91** [comment]
i.e., from `$TERMUX_PKG_SRCDIR` running something like `diff -u ./Makefile.orig ./Makefile` should work, but running `diff -u Makefile.orig Makefile` gives a patch file for which patch fails to find the file to patch, for some reason

**Comment by ravener** [comment]
@Grimler91 done

**Comment by ravener** [comment]
I'm not sure how to do that, is it possible from the github web ui? And can't you just select "rebase and squash" when merging?

**Comment by Grimler91** [comment]
> is it possible from the github web ui? 

No, github's does not support this, but it is possible from termux's command line with something like:

```
# Assuming remote origin is github.com/termux/termux-packages:
git fetch origin
git rebase origin/master
# Choose which commits to squash or rewrite in interactive rebase:
git rebase -i HEAD~7
# Assuming remote ravener is github.com/ravener/termux-packages:
git push -f ravener master
```

> And can't you just select "rebase and squash" when merging?

Yes, I could rebase, squash and re-write the commit messages for you, but I expect contributors to do these things. It's better if I provide you with the steps so that you can do it own your own, so that your next PR fulfills the style requirements out of the box

**Comment by ravener** [comment]
I'll be prepared next time I promise, for now though I don't wanna clone the repository.

**Pull request merged**
