### PR TITLE
bump(main/borgbackup): 1.4.0

### PR DESCRIPTION
**Pull request by TomJo2000**
Just rewriting the patch and bumping msgpack.

> Checklist
> - [x] Builds locally
> - [x] Builds on CI
> - [x] Tested on device (Android 13, Aarch64, Fairphone 5)

also set a maintainer

### CODE REVIEW

**Comment by TomJo2000** [comment]
For some reason it's no longer detecting the package name for building the pip wheel, even though I didn't touch that:
```styl
Processing /home/builder/.termux-build/borgbackup/src
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-1.4.0-cp311-cp311-linux_aarch64.whl size=1630394 sha256=7610fc3d3f2490d0062f2656f58b39abae117a78d27e904803c0c8c4dee3e42e
  Stored in directory: /tmp/pip-ephem-wheel-cache-bs9cei9d/wheels/66/cf/eb/ac19181e9b868c0f786153d843bed4d73643af083e05d74722
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 1.4.0
    Not uninstalling unknown at /data/data/com.termux/files/usr/lib/python3.11/site-packages, outside environment /home/builder/.termux-build/python-crossenv-prefix-aarch64/cross
    Can't uninstall 'UNKNOWN'. No files were found to uninstall.
Successfully installed UNKNOWN-1.4.0
```

It should be looking like this:
```styl
Processing /home/builder/.termux-build/borgbackup/src
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: borgbackup
  Building wheel for borgbackup (pyproject.toml) ... done
  Created wheel for borgbackup: filename=borgbackup-1.2.8-cp311-cp311-linux_aarch64.whl size=1990948 sha256=acae6379f8d301a371a185d420e006efaa14c79f131da2733dbfa87c51904b28
  Stored in directory: /tmp/pip-ephem-wheel-cache-4kou39ru/wheels/66/cf/eb/ac19181e9b868c0f786153d843bed4d73643af083e05d74722
Successfully built borgbackup
Installing collected packages: borgbackup
Successfully installed borgbackup-1.2.8
```

**Comment by TomJo2000** [comment]
Thanks licy.
I hadn't gotten around to fixing this PR.

**Comment by TomJo2000** [comment]
I'll look this over and will probably do at least one more force push to this branch before merging.
Please remember to use `git push --force-with-lease={{branchname}}` if you intend to do more changes to this PR.

**Comment by TomJo2000** [comment]
I wanted to turn this guard statement into a easily reusable block, for any other Python package that may benefit from it.
https://github.com/termux/termux-packages/blob/9fb19ac7ccb1d83eee8d17c6aa60d9ab3478963d/packages/borgbackup/build.sh#L17-L20

**Review by twaik — APPROVED** [review]

**Pull request merged**
