### PR TITLE
Add deprecation and future disabling of playstore builds warning to banner

### PR DESCRIPTION
**Pull request by agnostic-apollo**
Sorry for the duplicate. I forgot to re-commit before force pushing after undoing the single commit.

@Grimler91 and @buttaface thanks for the suggestions. I have tried to incorporate them from both of you. Its slightly shorter and will show even if banner is disabled.

I can't really say "The termux apps will be removed from Play store", since that requires involvement from @fornwall, who hasn't been responding on emails/sms.

I have updated https://github.com/termux/termux-app#installation as well and added deprecation details.

Let me know of any further changes.

playstore-banner

### CODE REVIEW

**Comment by Grimler91** [comment]
Looks good!

This:
```
.. so that new users
cannot install them and to **disable** them for
existing users with updates so that they do not
continue using outdated versions.
```
could be modified to make it clear who "they" are in the second part of the sentence. Perhaps:
```
.. so that new users
cannot install them and to **disable** them for
existing users with app updates to prevent the use 
of outdated app versions.
```

**Comment by agnostic-apollo** [comment]
@Grimler91 Done!

If someone else doesn't suggest changes in next few hours, I'll bump `termux-tools` version.

**Comment by RalfWerner** [comment]
Do it, even if I do not mean [playstore](https://github.com/termux/termux-packages/pull/7479#issuecomment-914116071) users [have](https://github.com/termux/termux-packages/pull/7479#issuecomment-914158845) an [advantage](https://github.com/termux/termux-packages/pull/7479#issuecomment-914150721) of it.

**Review by xeffyr — APPROVED** [review]

**Review by nikooseyfi07 — COMMENTED** [review]
​

**Review by Bryant-Coulson93 — COMMENTED** [review]
​

**Review by Bryant-Coulson93 — COMMENTED** [review]
​

**Pull request merged**
