### PR TITLE
updpkg(main/opencl-headers): upgrade to 2022.05.18

### PR DESCRIPTION
**Pull request by truboxl**

### CODE REVIEW

**Review by 2096779623 — CHANGES_REQUESTED** [review]
Please squash the commits, use the description of the first commit as the commit description for squash.

**Review by 2096779623 — APPROVED** [review]

**Comment by Grimler91** [comment]
Having multiple, tiny, commits is fine I think. Most important is that the changes are logical, commit message should describe what the commit does

**Comment by Grimler91** [comment]
@2096779623 yes, I agree, I think you've done a great job reviewing PRs and pointing out when commits have been a mess

**Comment by truboxl** [comment]
CC @MrAdityaAlok just in case
I have no idea how auto update is working or not 😅
Running `GITHUB_TOKEN=my_token_here ./scripts/bin/check-auto-update ./packages/opencl-headers` looks ok per https://github.com/termux/termux-packages/wiki/Auto-updating-packages

**Comment by MrAdityaAlok** [comment]
> CC @MrAdityaAlok just in case I have no idea how auto update is working or not 😅 Running `GITHUB_TOKEN=my_token_here ./scripts/bin/check-auto-update ./packages/opencl-headers` looks ok per https://github.com/termux/termux-packages/wiki/Auto-updating-packages

Yes, it can be auto-updated.

**Review by MrAdityaAlok — APPROVED** [review]

**Pull request merged**
