### PR TITLE
add(x11): new package xfce4-genmon-plugin

### LINKED ISSUE #11669: [Package]: xfce4-genmon-plugin
### Package description

xfce4-genmon-plugin is extremely useful from monitoring battery status to switching themes. As a plugin in xfce, it is commonly used and allows tons of tweaks. There is infinite functionality because users can write their own scripts to use with the plugin.

I see no reason not to add this to termux packages.

### Home page URL

_No response_

### Source code URL

https://gitlab.xfce.org/panel-plugins/xfce4-genmon-plugin

### Packaging policy acknowledgement

- [x] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### PR DESCRIPTION
**Pull request by T-Dynamos**
Closes #11669

### CODE REVIEW

**Comment by T-Dynamos** [comment]
```
checking for gcc... aarch64-linux-android-clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
configure: error: in `/home/builder/.termux-build/xfce4-genmon-plugin/src':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
checking whether we are cross compiling... 
Error: Process completed with exit code 1.
```
Why?

**Comment by 2096779623** [comment]
> ```
> checking for gcc... aarch64-linux-android-clang
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> configure: error: in `/home/builder/.termux-build/xfce4-genmon-plugin/src':
> configure: error: cannot run C compiled programs.
> If you meant to cross compile, use `--host'.
> See `config.log' for more details
> checking whether we are cross compiling... 
> Error: Process completed with exit code 1.
> ```
> 
> Why?

https://github.com/termux/termux-packages/blob/114a7152a4680b6f750f39c6e73f2c32e0acd0fa/packages/libtranscript/build.sh#L29

**Review by 2096779623 — APPROVED** [review]

**Comment by 2096779623** [comment]
First use `git reset` to roll back to the previous commit.
Use `git pull upstream master --rebase` to make it upto date.

**Comment by T-Dynamos** [comment]
@2096779623 
> Use git pull upstream master --rebase to make it upto date.
This is not working. Can you just do it (I have enabled edits by maintainers)

**Comment by T-Dynamos** [comment]
Please merge it

**Comment by babaric-dev** [comment]
Please approve this PR. I am waiting for the package to be available in Termux repos :)

**Pull request merged**
