### PR TITLE
cmatrix/build.sh: Adds TERMUX_PKG_MAINTAINER

### PR DESCRIPTION
**Pull request by abishekvashok**
packages/cmatrix/build.sh lacked the TERMUX_PKG_MAINTAINER parameter,
adds name of the maintainer and his Github username to it as a value.

Signed-off-by: Abishek V Ashok <abishekvashok@gmail.com>

### CODE REVIEW

**Comment by Neo-Oli** [comment]
TERMUX_PKG_MAINTAINER is used for the "Maintainer" Section of `apt show`. It is usually reserved for the individual who maintains the Termux Package of a program and not for the original author of the program. It's used to figure out who in the Termux Developer Community to ping with issues and bug reports. In this Termux is similar to Debian and Ubuntu. 
On Ubuntu for example cmatrix also shows `Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>` as maintainer. 
```
$ apt show cmatrix
Package: cmatrix
Version: 1.2a-5build2
Priority: optional
Section: universe/misc
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
````
Termux shows @fornwall as maintainer, which is the default when TERMUX_PKG_MAINTAINER isn't set. (He did package cmatrix after all)
```
$ apt show cmatrix
Package: cmatrix
Version: 1.2b
Maintainer: Fredrik Fornwall @fornwall
```

As for credit to the Author, we have the Hompage-field, which for cmatrix links to `https://github.com/abishekvashok/cmatrix`.

**Comment by sdrausty** [comment]
@Neo-Oli This pull request spun off from https://github.com/sdrausty/sdrausty.github.io/issues/1 "Update maintainer names" Maintainer information is updated from Packages.xz at termux.net for automatically generating https://sdrausty.github.io/pages/more which lists how many packages we have, once a day in Termux on device; And then this information is automatically uploaded to GitHub. 

screenshot_20170807-125133

**Comment by Neo-Oli** [comment]
@sdrausty I see. Nevertheless TERMUX_PKG_MAINTAINER is for information about the Maintainer of the Termux Package. Maybe you can rename the field to "Package Maintainer" instead of "Maintainer" to alleviate potential confusion? Or remove it completely, as it has a very limited purpose only related to Termux Development?

**Comment by sdrausty** [comment]
@Neo-Oli Thank you for your time and quick reply. Both your suggestions sound fine. What do you think about renaming "Maintainer" to "Termux Package Maintainer"?

**Pull request closed without merging**
