### PR TITLE
Fixed versions for pacman packages

### PR DESCRIPTION
**Pull request by Maxython**

### CODE REVIEW

**Review by xeffyr — APPROVED** [review]

**Comment by xeffyr** [comment]
Why the commit author has been set as "Termux Github Actions" ?

**Comment by Maxython** [comment]
> Why the commit author has been set as "Termux Github Actions" 

I don't know, apparently this is after my fixing the compilation bug for the host.

**Comment by xeffyr** [comment]
Fix your `~/.gitconfig` or repository-specific configuration (`$PWD/.git/config`).

**Comment by Maxython** [comment]
Thank

**Pull request closed without merging**
