### PR TITLE
bump(main/yazi): 0.4.0

### LINKED ISSUE #22480: Auto update failing for yazi
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [yazi](https://github.com/termux/termux-packages/blob/831fbd5b546988125e8e0cb9d6217c8c20e63f1c/packages/yazi) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating yazi [Current version: 0.3.3]
INFO: package being updated to 0.4.0.
Downloading https://github.com/sxyazi/yazi/archive/refs/tags/v0.4.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  793k    0  793k    0     0  2678k      0 --:--:-- --:--:-- --:--:-- 2678k

You are about to commit these changes:

--------------------
diff --git a/packages/yazi/build.sh b/packages/yazi/build.sh
index f49d2bcf79..a3436939c4 100644
--- a/packages/yazi/build.sh
+++ b/packages/yazi/build.sh
@@ -2,10 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://yazi-rs.github.io/
 TERMUX_PKG_DESCRIPTION="Blazing fast terminal file manager written in Rust, based on async I/O"
 TERMUX_PKG_LICENSE="MIT"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="0.3.3"
-TERMUX_PKG_REVISION=1
+TERMUX_PKG_VERSION="0.4.0"
 TERMUX_PKG_SRCURL=https://github.com/sxyazi/yazi/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=fe2a458808334fe20eff1ab0145c78d684d8736c9715e4c51bce54038607dc4e
+TERMUX_PKG_SHA256=65a063705dceecd23cfc3f617bf5e9ec9e31a7e5eef2f9bf4da4ffd4752b5e5c
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_BUILD_IN_SRC=true
 
--------------------

bump(main/yazi): 0.4.0

Not committing to Git!

INFO: Trying to build package.
INFO: Package yazi exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building yazi for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13133  100 13133    0     0  86249      0 --:--:-- --:--:-- --:--:-- 86401
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   5084      0 --:--:-- --:--:-- --:--:--  5110
gpg: Signature made Sun 08 Dec 2024 05:47:20 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  85885      0 --:--:-- --:--:-- --:--:-- 85935
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   5306      0 --:--:-- --:--:-- --:--:--  5339
gpg: Signature made Thu 28 Nov 2024 12:30:35 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13119  100 13119    0     0  84104      0 --:--:-- --:--:-- --:--:-- 84638
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   5191      0 --:--:-- --:--:-- --:--:--  5206
gpg: Signature made Sun 08 Dec 2024 10:09:33 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://github.com/sxyazi/yazi/archive/refs/tags/v0.4.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  793k    0  793k    0     0  4203k      0 --:--:-- --:--:-- --:--:-- 4203k
Applying patch: Cargo.lock.patch
1 out of 1 hunk FAILED -- saving rejects to file Cargo.lock.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-12-08 18:14:18 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/12224069962">12224069962</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by Biswa96**
Remove Cargo.lock.patch file which was added in upstream. https://github.com/sxyazi/yazi/commit/9483798459cbe8cb7dcca036a9463dc659fb0a41

* Fixes #22480

### CODE REVIEW

**Comment by Biswa96** [comment]
@sxyazi Failed to compile for 32 bit architectures.

**Comment by sxyazi** [comment]
Thanks for reporting @Biswa96! 

Fixed in https://github.com/sxyazi/yazi/commit/62ac224cffd01efd6b58e14d926b1bfdadc9e1ef, I'll release a new version the next day or two

**Comment by Biswa96** [comment]
For the record, the compiler error was as following.

```
    Compiling yazi-fs v0.4.0 (/home/builder/.termux-build/yazi/src/yazi-fs)
error[E0308]: mismatched types
   --> yazi-fs/src/fns.rs:261:11
    |
261 |                 .mode(cha.mode)
    |                  ---- ^^^^^^^^ expected `u32`, found `u16`
    |                  |
    |                  arguments to this method are incorrect
    |
note: method defined here
   --> /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/os/unix/fs.rs:380:8
help: you can convert a `u16` to a `u32`
    |
261 |                 .mode(cha.mode.into())
    |                               +++++++

For more information about this error, try `rustc --explain E0308`.
```

**Comment by TomJo2000** [comment]
I'd actually like to have auto updates handle this if possible.

**Comment by truboxl** [comment]
Still need to merge this because patch conflict

**Comment by TomJo2000** [comment]
Oh, right.

**Pull request merged**
