### PR TITLE
Update angle-android (2014-11-15)

### PR DESCRIPTION
**Pull request by ar37-rs**
Fixes crashing on wgpu example shadow example:
https://wgpu.rs/examples/?backend=webgl2&example=shadow

A workaround for PowerVr GPU added: https://chromium-review.googlesource.com/c/angle/angle/+/6026793

### CODE REVIEW

**Comment by licy183** [comment]
Thanks!

**Comment by ar37-rs** [comment]
@licy183 working great with virgl android --angle-vulkan,
plus enviar:
```
export MESA_GL_VERSION_OVERRIDE=4.1COMPAT
export MESA_GLSL_VERSION_OVERRIDE=410
```
on mali-g52 as well

**Comment by twaik** [comment]
@licy183 can we make a install-time check for virglrenderer-android for choosing the most suitable GL implementation? I mean there are some faulty stuff when using prop implementation on mali, but everything works fine with angle-gl so we can make postinst script probe for the best (or at least working) GL implementation and make virglrenderer-android use it by default.

**Comment by ar37-rs** [comment]
@twaik it by default mali bitfrost only support
```
export MESA_GL_VERSION_OVERRIDE=4.1COMPAT
export MESA_GLSL_VERSION_OVERRIDE=410```
using compat most of the things working as expected tested on wine-glibc (GPU_CAPS_Viewer) as well, without performance degeradation (using 4.3COMPAT and above is not supported and slower),
without 4.1COMPAT it only support 2.1 as by default virgl.

**Comment by ar37-rs** [comment]
Screenshot_2024-11-16_17-02-44
using `virgl_test_server_android --angle-gl &` got error switching context.
--angel-vulkan or --angle-null is the most stable use case.

**Comment by licy183** [comment]
> can we make a install-time check for virglrenderer-android for choosing the most suitable GL implementation? I mean there are some faulty stuff when using prop implementation on mali, but everything works fine with angle-gl so we can make postinst script probe for the best (or at least working) GL implementation and make virglrenderer-android use it by default.

It is really difficult to determine whether `virglrenderer-android` works or not with specified GL implementation. It seems not meaningful to use a hard-coded list, search the default GL implementation from them and use it by default. IMO it is better to add some hints in `postinst` script, suggesting Mali use angle-gl/angle-vulkan, and Adreno to use Native GL.

**Comment by twaik** [comment]
> It is really difficult to determine whether `virglrenderer-android` works or not with specified GL implementation

We already know some code in glmark2 in conjunction with mesa+virgl module make virglrenderer crash. Can we use this code in a test program?

**Comment by licy183** [comment]
> We already know some code in glmark2 in conjunction with mesa+virgl module make virglrenderer crash. Can we use this code in a test program?

It is possible, but I really don't think it is necessary. It is sufficient to prompt some suggestions in `postinst`.

**Comment by twaik** [comment]
I just think stuff should work out of the box. There are a small percent of people who will really read postinst prompts and will really understand and follow them. Probing for the most suitable configuration will be much better for end user.

**Pull request merged**
