### PR TITLE
Bump libffi and dependent packages

### PR DESCRIPTION
**Pull request by thunder-coding**
Packages that need to be bumped/revised:
- [x] `ctypes-sh`
- [x] `ecl`
- [x] `glib`
- [x] `imagemagick`
- [x] `libgmime`
- [x] `libllvm`
- [x] `p11-kit`
- [x] `profanity`
- [x] `python`
- [x] `python2`
- [x] `ruby`

### CODE REVIEW

**Comment by xeffyr** [comment]
Is this still worked on or finished?

**Comment by thunder-coding** [comment]
> Is this still worked on or finished?

Work is still going on. My exams are coming lately, thats why it's quite stale

**Comment by thunder-coding** [comment]
Anyways, do I also need to bump revision for dependent packages of dependent packages of libffi?

**Comment by xeffyr** [comment]
You need to rebuild dependent packages only if dependency (libffi) changed its ABI, which usually happen only on major version updates.

**Comment by thunder-coding** [comment]
aarch64 builds have passed. And other arch builds failed due to some other problem. 

Ready to merge, after re-running CI

**Review by xeffyr — APPROVED** [review]

**Pull request merged**
