### PR TITLE
test for #2066

### PR DESCRIPTION
**Pull request by its-pointless**
This should allow people affected by #2066 to still use termux.

### CODE REVIEW

**Comment by Neo-Oli** [comment]
On Android disc IO is slow, can we test with a command other than `ls`? I suggest `busybox true`,  it does essentialy nothing and isn't affected by how many files a user has. (busybox to avoid calling a shell builtin).

**Comment by tomty89** [comment]
@its-pointless What's the point of the `$SHELL -c`  btw? Also `> /dev/null 2>&1` is not gonna help I think:
```
$ /system/bin/linker &>/dev/null
Aborted (core dumped)
$ /system/bin/linker64 &>/dev/null
Segmentation fault (core dumped)
$
```

Also can we not afford to just make termux-exec optional again?

**Comment by fornwall** [comment]
As termux-exec in LD_PRELOAD causes quite some issue it's perhaps the best to avoid it there.

Another approach would be to link a limited amount of packages (bash, dash, node, python, ruby, ...) against libtermux-exec.so, so that normal shebangs work when exec:ed from shells and scripts, but the system is otherwise unaffected. What do you think about that?

**Comment by its-pointless** [comment]
Umm it doesn't fix anything it just tests and unsets LD_PRELOAD before starting the proper shell if it fails to to execute the command in the intended shell

**Comment by fornwall** [comment]
Thanks! The updated package is available, and the bootstrap zips which are installed for new users have been re-generated to contain that.

**Comment by tomty89** [comment]
@its-pointless I know. I meant can't you just have:
```
busybox true || unset LD_PRELOAD
```
Is the issue even shell-specific that we have to make everyone starts $SHELL twice upon `login`?

And since you can't redirect/silent the core dumped messages, the commit seems to make little point (actually it sort of make it worse because you can't silent that one message anymore by having `unset LD_PRELOAD` in your .bashrc or so)

@fornwall personally I never really liked the idea of termux-exec anyway, so to me this sort of hack is better left optional (i.e. disabled by default). I don't know if problems would really be gone if you have it linked only to certain programs, all I know is that at least with LD_PRELOAD, it's a user configuration that you can change on run-time, while otherwise it's not.

**Comment by its-pointless** [comment]
"Is the issue even shell-specific that we have to make everyone starts $SHELL twice upon login?"
yes bash starts for some people and not others. So it has to execute something in that shell.

"And since you can't redirect/silent the core dumped messages, the commit seems to make little point "
You can in android because android is weird. At least no core dump messages showed when i did tests that ended with failure.

**Comment by tomty89** [comment]
Seems like my Android is not weird enough then.

**Pull request merged**
