### PR TITLE
dpkg: enable scanpackages

### PR DESCRIPTION
**Pull request by WMCB-Tech**
this dpkg subcommand may be useful to create/update apt repositories locally

### CODE REVIEW

**Comment by WMCB-Tech** [comment]
for this one. perl module `dpkg` must be installed manually. otherwise it would fail saying dpkg module is not installed

**Comment by WMCB-Tech** [comment]
the installation stopped at gettext saying locale not found

**Comment by WMCB-Tech** [comment]
Dpkg perl module depends on gettext however Termux does not support locales. closing until some workarounds for this are found

**Comment by zairullahdev** [comment]
How about port it? (Change some configuration of conffile, control of Deb?)

**Pull request closed without merging**
