### PR TITLE
add Dockerfile to repository

### PR DESCRIPTION
**Pull request by acornejo**

### CODE REVIEW

**Comment by robertvalik** [comment]
Hey, I am trying to use docker but the build command fails with:

     ---> Running in a09e32dea5e8
    chown: invalid user: 'termux'
    The command '/bin/sh -c mkdir -p /data/data/com.termux/files/usr && chown -R termux /data && mkdir /root/termux' returned a non-zero code: 1

And I cannot open an interactive shell:

    bash-3.2$ docker run --rm=true -ti termux /bin/bash
    Unable to find image 'termux:latest' locally
    Pulling repository docker.io/library/termux
    Error: image library/termux:latest not found

How to get out of this situation?

Thanks.

**Comment by acornejo** [comment]
Hi Robert,

I just updated the image (there was a line left over from earlier testing). Please try agin, it should work now (you will need to build the image first)

**Comment by robertvalik** [comment]
Thanks, it is working now. But there are two issues with build-all.sh script. The buildorder.py is missing. I believe that it can be fixed by adding to Dockfile something like:

    ADD *.py /root/termux/

The other issue is that it conflicts somehow with build paths. Line 12:

    rm -Rf $HOME/termux /data/data $HOME/termux/_buildall

Dont know why it has to delete /root/termux...

**Comment by acornejo** [comment]
yup, adding buildorder is simple enough (I only tested the image building individual packages, which is why I didn't realize it was missing).

The other one is only slightly trickier, the problem is that I chose to store the files under a termux folder without knowing it would create conflcits with build all. Please give it another try, I just updated again (and thanks a lot for testing this stuff out).

**Comment by robertvalik** [comment]
It seems to be working. The build-all.sh script works, builds some packages but fails on ant:

    /root/termux-packages/packages/ant/build.sh: line 14: /root/lib/android-sdk/build-tools/23.0.0/dx: No such file or directory

Dont know if this is issue from termux or docker image...

**Comment by fornwall** [comment]
Nice work, merged this now! I haven't tested Docker myself, but will try it out soon.

**Pull request merged**
