### PR TITLE
bump(main/cabal-install): 3.10.1.0

### PR DESCRIPTION
**Pull request by twaik**

### CODE REVIEW

**Comment by twaik** [comment]
I am not sure how to ask that, but is it legit? I mean how can it build fine for all abis except arm?

**Comment by 2096779623** [comment]
```
~ $ cabal update
Config file path source is default config file.
Config file not found: /data/data/com.termux/files/home/.config/cabal/config
Writing default configuration to
/data/data/com.termux/files/home/.config/cabal/config
Warning: 'nslookup' tool missing - can't locate mirrors
Downloading the latest package list from hackage.haskell.org
```
Please add `dnsutils` as `TERMUX_PKG_DEPENDS`.

**Comment by 2096779623** [comment]
```
~ $ cabal init myfirstapp -n
Error: cabal: The program 'ghc' version >=7.0.1 is required but it could not
be found.
```
It looks like `ghc` needs to be added too.

**Comment by twaik** [comment]
`ghc` is suggested, but not forced to install. Should I move it to TERMUX_PKG_DEPENDS?

**Comment by 2096779623** [comment]
Screenshot_20231002-220556_Element

**Comment by twaik** [comment]
Ok, the build cancelled because arm building is failed.

**Comment by MrAdityaAlok** [comment]
`ghc` needs to be updated first.

**Pull request closed without merging**
