### PR TITLE
Add package tvheadend

### LINKED ISSUE #3066: Package Request: tvheadend
(or 'How can i compile it from source?')

### PR DESCRIPTION
**Pull request by MrAdityaAlok**
- closes #3066

### CODE REVIEW

**Comment by leapofazzam123** [comment]
Add `--disable-ccache` to additional configure flags

**Comment by leapofazzam123** [comment]
> Add `--disable-ccache` to additional configure flags

@MrAdityaAlok

**Comment by MrAdityaAlok** [comment]
@leapofazzam123 ccache is not problem, it is disabled by default

**Comment by suhan-paradkar** [comment]
Add 
```
termux_step_pre_configure() {
    termux_setup_cmake
}
```

To your `build.sh`

**Comment by MrAdityaAlok** [comment]
@suhan-paradkar Oh! Thank you. Totally forgot about that script.

**Comment by suhan-paradkar** [comment]
Try adding `wget` to `scripts/setup-ubuntu.sh`.. If absent

**Comment by MrAdityaAlok** [comment]
> Try adding `wget` to `scripts/setup-ubuntu.sh`.. If absent

Was doing that only.....

**Pull request closed without merging**
