### PR TITLE
new package: tur-repo

### PR DESCRIPTION
**Pull request by kcubeterm**

### CODE REVIEW

**Comment by 2096779623** [comment]
image

Why is there an expiration time?

**Comment by kcubeterm** [comment]
>> Why is there an expiration time?

so that key could expire :) why do you think it should't expire ? if you want I can set bit longer, like 1 light year

**Comment by 2096779623** [comment]
> > > Why is there an expiration time?
> 
> so that key could expire :) why do you think it should't expire ? if you want I can set bit longer, like 1 light year

image

[termux-autobuilds](https://github.com/termux/termux-packages/blob/master/packages/termux-keyring/termux-autobuilds.gpg?raw=true)

**Comment by agnostic-apollo** [comment]
You can always extend expiry date for keys. It's not advisable to set it to forever since if you lose private key and revocation cert, then key can be misused forever if it gets compromised.

https://superuser.com/questions/813421/can-you-extend-the-expiration-date-of-an-already-expired-gpg-key

https://security.stackexchange.com/questions/14718/does-openpgp-key-expiration-add-to-security/79386

**Comment by kcubeterm** [comment]
That's the point Thanks.

**Pull request merged**
