### PR TITLE
scripts: fixing the method of extracting files from packages in pacman format

### PR DESCRIPTION
**Pull request by Maxython**

### CODE REVIEW

**Review by twaik — APPROVED** [review]
LGTM.

**Comment by agnostic-apollo** [comment]
Note that `tar --exclude='.MTREE'` etc will match files in subdirectories as well instead of just root directory of tar file. Using `./MTREE` and `/.MTREE` will not work either, which won't exclude any file as none would match. I had already fixed this in my local changes for pacman by extracting `rootfs_top_level_dir` only, which would be `/data` by default.

**Comment by Maxython** [comment]
> Note that tar --exclude='.MTREE' etc will match files in subdirectories as well instead of just root directory of tar file. Using ./MTREE and /.MTREE will not work either, which won't exclude any file as none would match.

Thanks for pointing that out. To fix this, need to specify the path before the file. It should look like this `--exclude='./.MTREE'`.

> I had already fixed this in my local changes for pacman by extracting rootfs_top_level_dir only, which would be /data by default.

Please do not make such a change, as the `rootfs_top_level_dir` directory (`data/` in our case) may not exist in the pacman package, for example in metapackages. This will cause an error when extracting such packages.

**Comment by agnostic-apollo** [comment]
> To fix this, need to specify the path before the file. It should look like this --exclude='./.MTREE'.
 
 That does not work from my tests, even if put before `-C` or -f`.
 
 >metapackages
 
 Example package? What's the path in that case?
 
 Can always extract entire tar and then manually delete pacman files from rootfs.

**Comment by agnostic-apollo** [comment]
Also note that files listed by `tar -t` do not start with `./` for pacman tar package files as there is no dot `.` directory at root of tar, like it exists for `deb` `data.tar.xz` files, so `./` in `--exclude` wouldn't match regardless of order.

**Comment by Maxython** [comment]
> Example package? What's the path in that case?

[opengl-glibc](https://service.termux-pacman.dev/gpkg/aarch64/opengl-glibc-0.1-1-any.pkg.tar.xz) - this package contains only metadata. That is, there is nothing to extract.

**Comment by agnostic-apollo** [comment]
Okay, thanks, will update my changes.

**Comment by Maxython** [comment]
> That does not work from my tests, even if put before -C or -f.

Sorry for the misinformation, I was testing with my created archive for this, and the `--exclude` flag understood that argument with that archive. When I tested with the package, it stopped working. However, I found what needs to be done to fix this issue, just need to add the `--anchored` flag.

**Comment by agnostic-apollo** [comment]
>However, I found what needs to be done to fix this issue, just need to add the --anchored flag.

Ah nice, I didn't notice that. Thanks.

**Pull request merged**
