### PR TITLE
Add duf

### PR DESCRIPTION
**Pull request by kcubeterm**
A Disk usage/free utility

### CODE REVIEW

**Comment by xeffyr** [comment]
Really, how much we have utilities performing same tasks? du, duc, diskus...

There are plenty of other packages requested - https://github.com/termux/termux-packages/issues?q=is%3Aopen+is%3Aissue+label%3A%22package+request%22

**Comment by kcubeterm** [comment]
Yes, we have but duf is slightly different and user friendly. it has few features like 
>  * User-friendly, colorful output
 > * Adjusts to your terminal's width
>  * Sort the results according to your needs
 > * Groups & filters devices
 > * Can conveniently output JSON

**Comment by kcubeterm** [comment]
Thanks, it is first PR in October.

**Comment by xeffyr** [comment]
> it is first PR in October.

Снимок экрана от 2020-09-30 23-07-48

From future.

**Comment by kcubeterm** [comment]
You merged it first that's why .

**Pull request merged**
