### PR TITLE
add libmnl

### PR DESCRIPTION
**Pull request by stephengroat**
#1739

### CODE REVIEW

**Comment by fornwall** [comment]
Is this package a root-only package (only usable for rooted users)? The new repo at https://github.com/termux/termux-root-packages is being created to contain those.

**Comment by zx2c4** [comment]
No, this package is a library, `libmnl.so`, to which other packages link.

**Comment by fornwall** [comment]
@zx2c4 Right - but is the library interesting for any non-root packages?

**Comment by zx2c4** [comment]
libmnl is useful for talking Netlink, which is one of the kernel's primary userspace<-->kernelspace IPC mechanisms. In general, though *some* Netlink commands require `CAP_NET_ADMIN`, many others do not. Therefore, libmnl is useful for more than just root.

**Comment by fornwall** [comment]
Thanks - the package is now available for installation!

**Pull request merged**
