### PR TITLE
mpd only working with openal and no mixer still good

### PR DESCRIPTION
**Pull request by its-pointless**
it works well with ncmpcpp ....

### CODE REVIEW

**Comment by its-pointless** [comment]
Software mixer working.
Its good to go from my point of view.

**Comment by its-pointless** [comment]
And opensles and openal both work .... its done.

**Comment by Neo-Oli** [comment]
There is a shell script at $PREFIX/bin/mpd that sets up the environment and starts the real mpd process. Could you prefix that with `exec` please. Otherwise there will be a useless `sh` process running. It also causes issues when running mpd as a service (with runit). When killing the mpd service it will kill the `sh` procsess, but not the mpd process.

At [Line 44 of build.sh](https://github.com/termux/termux-packages/pull/1007/files#diff-def6fab382e81a3a8e946612665a33d9R44):
`echo "LD_LIBRARY_PATH=/system/$SYSTEM_LIBFOLDER:/system/vendor/$SYSTEM_LIBFOLDER:$TERMUX_PREFIX/lib exec $TERMUX_PREFIX/libexec/mpd \"\$@\"" >> $TERMUX_PREFIX/bin/mpd`

**Comment by its-pointless** [comment]
Sure

**Comment by vishalbiswas** [comment]
Why is the port required to be above 6000? (6600>6000)

**Comment by fornwall** [comment]
@its-pointless Is this ready for merging and an initial release?

**Comment by its-pointless** [comment]
It appears so. Cant find anything worth blocking this atm.

**Pull request merged**
