### PR TITLE
xorg-server, xorg-server-xvfb, xwayland: fix for using /dev/ashmem

### PR DESCRIPTION
**Pull request by twaik**
Fixes https://github.com/termux/termux-packages/issues/15239

### CODE REVIEW

**Comment by xtkoba** [comment]
Please revbump `tigervnc` when modifying configs and patches for `xorg-server-xvfb`. (Done on my side this time.)


FYI, Xvfb stands for **X** **v**irtual **f**rame**b**uffer.

**Comment by twaik** [comment]
@xtkoba I am trying to update xwayland version, but I've got a problem. How can I update PKG_CONFIG_LIBDIR? Updating it in termux_step_pre_configure does not work.
<details>

```
TERMUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/wiki/
TERMUX_PKG_DESCRIPTION="Wayland X11 server"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=22.1.7
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/xserver/xwayland-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=d53afac6c71953f5cf66d03d289dacd8961da5bd309c1dff125d5955d9db5f76
TERMUX_PKG_DEPENDS="libandroid-shmem, libdrm, libpciaccess, libpixman, libx11, libxau, libxfont2, libxinerama, libxkbfile, libxshmfence, opengl, openssl, xkeyboard-config, xorg-xkbcomp, libwayland, libwayland-protocols, libepoxy"
TERMUX_PKG_BUILD_DEPENDS="libwayland-cross-scanner, mesa, xorg-font-util"

TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-Dmitshm=true
-Dxres=true
-Dxv=true
-Dsecure-rpc=false
-Dscreensaver=true
-Dxdmcp=true
-Dglx=true
-Ddri3=true
-Dxinerama=true
-Dxace=true
-Dxcsecurity=true
-Dxf86bigfont=true
-Ddrm=true
-Dglamor=false
-Dxwayland_eglstream=false
-Dxvfb=false
-Dlibunwind=false
-Dipv6=true
-Dsha1=libcrypto"

# Remove files conflicting with xorg-server:
TERMUX_PKG_RM_AFTER_INSTALL="
share/X11/xkb/compiled
share/man/man1/Xserver.1
"

termux_step_pre_configure() {
	export PATH="$TERMUX_PREFIX/opt/libwayland/cross/bin:$PATH"
	export TERMUX_PKG_CONFIG_LIBDIR="$(dirname $(find $TERMUX_PREFIX/opt/libwayland/cross -name wayland-scanner.pc)):$TERMUX_PKG_CONFIG_LIBDIR"
	export PKG_CONFIG_LIBDIR="$(dirname $(find $TERMUX_PREFIX/opt/libwayland/cross -name wayland-scanner.pc)):$PKG_CONFIG_LIBDIR"
	CFLAGS+=" -fcommon -fPIC -DFNDELAY=O_NDELAY -Wno-int-to-pointer-cast"
	CPPFLAGS+=" -fcommon -fPIC -I${TERMUX_PREFIX}/include/libdrm"
	LDFLAGS+=" -landroid-shmem"

	if [ "${TERMUX_DEBUG_BUILD}" = "true" ]; then
		TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" -Ddebug=true"
	fi
}

```
</details

**Comment by twaik** [comment]
I tried to update it, but last versions of xwayland have no autoconf support, only meson. I tried to update it, but failed replacing `wayland-scanner`.
[xwayland.tar.gz](https://github.com/termux/termux-packages/files/10793065/xwayland.tar.gz)

**Comment by twaik** [comment]
About termux-x11. I am planning to get rid of wayland dependency and connect to Xorg with dummy driver. It will allow me to make something like connecting to existing session. And it will fix seemly random disconnections and unexpected session killings.

**Comment by xtkoba** [comment]
As for wayland-scanner, some patching would need to `hw/xwayland/meson.build` in the source tree.

**Comment by twaik** [comment]
I thought it is unneded since it gets wayland-scanner's path from pkgconfig.

**Comment by xtkoba** [comment]
It is also possible, though it requires some workaround as well.

**Comment by twaik** [comment]
Is it ready to be merged?

**Comment by xtkoba** [comment]
Some description somewhere (maybe at the head of each patch) is suggested, to prevent us from removing them when they are not applied cleanly.

As for functionality, `tigervnc` seems to work without problem as of now. I'm not qualified to review other packages.

**Comment by xtkoba** [comment]
Probably no one else can review this properly, other than yourself. So it is OK, maybe? I don't know.

**Comment by twaik** [comment]
I think it is OK. So can I merge?

**Comment by twaik** [comment]
Ok, these patches touch nothing but ashmem support in xservers so I am merging this...

**Comment by twaik** [comment]
> BTW, may I bump xwayland to the latest version (22.1.8) ? The bump is pending because (1) it is a major bump, (2) it may break termux-x11, and (3) I cannot test the functionality on my own.

You were right, it broke `termux-x11`, but it is probably my fault...

**Comment by twaik** [comment]
BTW I already fixed this.

**Pull request merged**
