### PR TITLE
Add Coinor CBC and CGL

### LINKED ISSUE #19777: [Package]: Coinor CBC and CGL
### Why is it worth to add this package?

Currently, Coinor's CLP is available (`pkg install coinor-clp`).  CBC is a powerful solver that adds MILP (the CGL library is just a dependency).

It would also warm my heart if this were available, since my motivation is that I need it for a project I'm working on.

### Home page URL

_No response_

### Source code URL

https://github.com/coin-or/Cbc/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

While trying to add this myself, I got the following error.  I was unable to try to build CBC because the error prevented me from building CGL:

```
*** Warning: Linking the shared library libCgl.la against the
*** static library /data/data/com.termux/files/usr/lib/clang/18/lib/linux/libclang_rt.builtins-aarch64-android.a is not portable!
aarch64-linux-android-clang++ -shared -nostdlib /data/data/com.termux/files/usr/lib/crtbegin_so.o  .libs/CglCutGenerator.o .libs/CglMessage.o .libs/CglStored.o .libs/CglParam.o .libs/CglTreeInfo.o -Wl,--whole-archive CglAllDifferent/.libs/libCglAllDifferent.a CglClique/.libs/libCglClique.a CglDuplicateRow/.libs/libCglDuplicateRow.a CglFlowCover/.libs/libCglFlowCover.a CglGMI/.libs/libCglGMI.a CglGomory/.libs/libCglGomory.a CglKnapsackCover/.libs/libCglKnapsackCover.a CglLandP/.libs/libCglLandP.a CglLiftAndProject/.libs/libCglLiftAndProject.a CglMixedIntegerRounding/.libs/libCglMixedIntegerRounding.a CglMixedIntegerRounding2/.libs/libCglMixedIntegerRounding2.a CglOddHole/.libs/libCglOddHole.a CglPreProcess/.libs/libCglPreProcess.a CglProbing/.libs/libCglProbing.a CglRedSplit/.libs/libCglRedSplit.a CglRedSplit2/.libs/libCglRedSplit2.a CglResidualCapacity/.libs/libCglResidualCapacity.a CglSimpleRounding/.libs/libCglSimpleRounding.a CglTwomir/.libs/libCglTwomir.a CglZeroHalf/.libs/libCglZeroHalf.a -Wl,--no-whole-archive  -Wl,--rpath -Wl,/data/data/com.termux/files/usr/lib -Wl,--rpath -Wl,/data/data/com.termux/files/usr/lib -L/data/data/com.termux/files/usr/lib /data/data/com.termux/files/usr/lib/clang/18/lib/linux/libclang_rt.builtins-aarch64-android.a /data/data/com.termux/files/usr/lib/libOsiClp.so /data/data/com.termux/files/usr/lib/libClpSolver.so /data/data/com.termux/files/usr/lib/libClp.so /data/data/com.termux/files/usr/lib/libOsi.so /data/data/com.termux/files/usr/lib/libCoinUtils.so -lbz2 -lz -L/system/lib64 -lc++_shared -lm -lc -l:libunwind.a -ldl /data/data/com.termux/files/usr/lib/crtend_so.o  -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-soname -Wl,libCgl.so.1 -o .libs/libCgl.so.1.10.8
ld.lld: error: CglAllDifferent/.libs/libCglAllDifferent.a(libclang_rt.builtins-aarch64-android.a): not an ELF file
```

Here's my `libcoinor-cgl/build.sh`:

```
TERMUX_PKG_HOMEPAGE=https://github.com/coin-or/Cgl
TERMUX_PKG_DESCRIPTION="An open-source cut generation library for COIN-OR projects"
TERMUX_PKG_LICENSE="EPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1:0.60.8
TERMUX_PKG_SRCURL=https://github.com/coin-or/Cgl/archive/refs/tags/releases/${TERMUX_PKG_VERSION#*:}.tar.gz
TERMUX_PKG_SHA256=1482ba38afb783d124df8d5392337f79fdd507716e9f1fb6b98fc090acd1ad96
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_METHOD=repology
TERMUX_PKG_DEPENDS="libc++, libcoinor-osi, libcoinor-utils"
termux_step_pre_configure() {
    LDFLAGS+=" $($CC -print-libgcc-file-name)"
}
```

This was my `coinor-cbc/build.sh`:

```
TERMUX_PKG_HOMEPAGE=https://github.com/coin-or/Cbc
TERMUX_PKG_DESCRIPTION="An open-source mixed integer linear programming solver"
TERMUX_PKG_LICENSE="EPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1:2.10.11
TERMUX_PKG_SRCURL=https://github.com/coin-or/Cbc/archive/refs/tags/releases/${TERMUX_PKG_VERSION#*:}.tar.gz
TERMUX_PKG_SHA256=1fb591dd88336fdaf096b8e42e46111e41671a5eb85d4ee36e45baff1678bd33
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_METHOD=repology
TERMUX_PKG_DEPENDS="libc++, libcoinor-osi, libcoinor-utils, libcoinor-cgl"
termux_step_pre_configure() {
    LDFLAGS+=" $($CC -print-libgcc-file-name)"
}
```

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes #19777

### CODE REVIEW

**Comment by Biswa96** [comment]
I accidentally deleted the branch and can not reopen the PR.

**Comment by finagolfin** [comment]
It is easy to recreate the branch and push it again:
```
git push my-repo coinor
```
or if you deleted it locally too, run these commands first:
```
git checkout -b coinor
git cherry-pick 3067cc2
```

**Comment by Biswa96** [comment]
> It is easy to recreate the branch and push it again

I did that but the reopen button was disabled.

**Comment by twaik** [comment]
It is disabled because there is another PR opened for the same branch. #20240

**Comment by Biswa96** [comment]
I opened that new PR after I saw the disabled reopen button here.

**Comment by finagolfin** [comment]
OK, maybe it is not possible if you are not a contributor.

**Pull request closed without merging**
