### PR TITLE
command-not-found: Always return an error

### LINKED ISSUE #564: command-not-found should return an error
Some programs (like rupa/z ) might rely on the return status to detect presence of a command. Simply returning an error status instead of 0 should fix this issue.

### PR DESCRIPTION
**Pull request by anisse**
Fixes #564

### CODE REVIEW

**Comment by fornwall** [comment]
Nice! Could you change the return code to 127 in both instances? [127 historically means command not found](http://www.tldp.org/LDP/abs/html/exitcodes.html) and seems to be what command-not-found on debian/ubuntu returns, so nice to be compatible!

**Comment by anisse** [comment]
Done.

**Comment by fornwall** [comment]
Thanks! The update command-not-found package (version 1.15) is now available for installation from the apt repository.

**Comment by Neo-Oli** [comment]
This has caused zsh output to change from: 
```
The program 'sl' is not installed. Install it by executing:
 apt install sl
```
to 
```
The program 'sl' is not installed. Install it by executing:
 apt install sl
zsh: command not found: sl
```

**Comment by fornwall** [comment]
@Neo-Oli Thanks, fixed in the 5.2.0-5 update of the zsh package.

**Pull request merged**
