### PR TITLE
update to v2.6.4

### PR DESCRIPTION
**Pull request by Ladxn**

### CODE REVIEW

**Comment by Anonymous1231-dev** [comment]
Can you edit your or title as "chore(main/alist): Fix archive url in termux_step_make" ?

**Comment by Anonymous1231-dev** [comment]
Plus, you must add "TERMUX_PKG_REVISION=1" in 'build.sh'

**Comment by Grimler91** [comment]
No need to set TERMUX_PKG_REVISION on package update, but commit message should be re-written as pointed out by @Anonymous1231-dev

**Review by 2096779623 — APPROVED** [review]

**Comment by 2096779623** [comment]
Sorry for that, I haven't seen the webTag.

**Comment by Grimler91** [comment]
Now it looks like TERMUX_PKG_REVISION needs to be bumped as well, since TERMUX_PKG_VERSION is not touched

**Pull request merged**
