### PR TITLE
Add racket package

### PR DESCRIPTION
**Pull request by goodmind**
I managed to build `racket` but subprocess functions not working

Build variables:

``` sh
export TERMUX_ARCH="arm"
export TERMUX_ARCH_BITS="32"
export TERMUX_HOST_PLATFORM="${TERMUX_ARCH}-linux-androideabi"
```

Termux Racket

### CODE REVIEW

**Comment by goodmind** [comment]
@fornwall any thoughts on this?

**Comment by goodmind** [comment]
@fornwall How to patch file which is one directory up (from source)?

```diff
diff --git a/collects/racket/system.rkt ../collects/racket/system.rkt
index 9de72fe..78beae6 100644
--- a/racket/collects/racket/system.rkt
+++ ../collects/racket/system.rkt
@@ -17,7 +17,7 @@
 
 (define (shell-path/args who argstr)
   (case (system-type)
-    [(unix macosx) (append '("/bin/sh" "-c") (list argstr))]
+    [(unix macosx) (append '("@TERMUX_PREFIX@/bin/sh" "-c") (list argstr))]
     [(windows) (let ([cmd
                       (let ([d (find-system-path 'sys-dir)])
                         (let ([cmd (build-path d "cmd.exe")])
```

This gives me 
```shell
The text leading up to this was:
--------------------------
|diff -u -r a/collects/racket/system.rkt ../collects/racket/system.rkt
|index 9de72fe..78beae6 100644
|--- a/racket/collects/racket/system.rkt
|+++ ../collects/racket/system.rkt
--------------------------
File to patch: 
```

**Comment by fornwall** [comment]
@goodmind Sorry for the delay here, and thanks for the work!

I've updated the racket build script to only modify TERMUX_PKG_SRCDIR after patching files, so we can patch all the files with normal patch files.

**Comment by fornwall** [comment]
@goodmind I've also changed build-package.sh, so you don't need the

    export TERMUX_ARCH="arm"
    export TERMUX_ARCH_BITS="32"
    export TERMUX_HOST_PLATFORM="${TERMUX_ARCH}-linux-androideabi"

variables anymore (just specify the architecture with the -a switch, as in `./build-package -a arm/i686/aarch64/x86_64 ...`).

**Comment by fornwall** [comment]
Is the racket package ready to be enabled? Would you @goodmind like to stand as the maintainer (add a line `TERMUX_PKG_MAINTAINER="firstname lastname @goodmind"` to the build file), so issues in the package can be assigned to you?

**Comment by goodmind** [comment]
I think it's not ready to be enabled
I got this error when I'm tried to run racket test suite:
```shell
raco test: "/data/data/com.termux/files/home/.racket/6.7/pkgs/racket-test-core/tests/racket/test.rkt"
raco test: @(test-responsible '(eli jay matthias mflatt robby ryanc samth))
Section(basic)
SIGSEGV MAPERR si_code 1 fault on addr 0xe59f3010

Program received signal SIGABRT, Aborted.
0xb6c91f50 in tgkill () from /system/lib/libc.so
```

**Comment by goodmind** [comment]
@fornwall any thoughts? Do you know how to build racket with debug symbols and not stripped?

**Comment by fornwall** [comment]
@goodmind Specifying the `-d` flag to `build-package.sh` will cause it to build with debug symbol and not stripping it (note, update from git master as the `-d` flag was just fixed there).

**Comment by goodmind** [comment]
So, I give up on this for some period :(

**Pull request merged**
