### PR TITLE
Speed up via aria2.

### PR DESCRIPTION
**Pull request by Wetitpig**
Aria2c parallel download can increase the speed by 50%

### CODE REVIEW

**Comment by fornwall** [comment]
Do you have numbers to see how much this speeds up things?

**Comment by Wetitpig** [comment]
From 420s to 250s

**Comment by Wetitpig** [comment]
Because it has been implemented for quite a while already, also it is under different settings.

**Comment by fornwall** [comment]
Sorry for the long delay here!

I don't want to start using simultaneous connections as I understand it to not be accepted good netiquette. Also, environments doing repeated builds (such as Travis) were this is relevant already uses the Docker image which contains the NDK and SDK.

**Pull request closed without merging**
