### PR TITLE
 libprotobuf: Bump to 25.1

### LINKED ISSUE #18575: Auto update failing for libprotobuf-c
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the libprotobuf-c package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating libprotobuf-c [Current version: 1.4.1]
INFO: package being updated to 1.5.0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  495k  100  495k    0     0  1216k      0 --:--:-- --:--:-- --:--:-- 1216k

You are about to commit these changes:

--------------------
diff --git a/packages/libprotobuf-c/build.sh b/packages/libprotobuf-c/build.sh
index 18f55cf24..b6bf3c9d2 100644
--- a/packages/libprotobuf-c/build.sh
+++ b/packages/libprotobuf-c/build.sh
@@ -2,10 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://github.com/protobuf-c/protobuf-c
 TERMUX_PKG_DESCRIPTION="Protocol buffers C library"
 TERMUX_PKG_LICENSE="BSD 2-Clause"
 TERMUX_PKG_MAINTAINER="Henrik Grimler @Grimler91"
-TERMUX_PKG_VERSION="1.4.1"
-TERMUX_PKG_REVISION=8
+TERMUX_PKG_VERSION="1.5.0"
 TERMUX_PKG_SRCURL=https://github.com/protobuf-c/protobuf-c/releases/download/v${TERMUX_PKG_VERSION}/protobuf-c-${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=4cc4facd508172f3e0a4d3a8736225d472418aee35b4ad053384b137b220339f
+TERMUX_PKG_SHA256=7b404c63361ed35b3667aec75cc37b54298d56dd2bcf369de3373212cc06fd98
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_DEPENDS="abseil-cpp, libc++, libprotobuf, protobuf"
 TERMUX_PKG_BREAKS="libprotobuf-c-dev"
--------------------

bump(main/libprotobuf-c): 1.5.0

Not committing to Git!

INFO: Trying to build package.
INFO: Package libprotobuf-c exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building libprotobuf-c for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  20641      0 --:--:-- --:--:-- --:--:-- 20618
100 13134  100 13134    0     0  20638      0 --:--:-- --:--:-- --:--:-- 20618
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1414      0 --:--:-- --:--:-- --:--:--  1416
gpg: Signature made Sun 26 Nov 2023 12:15:50 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  22995      0 --:--:-- --:--:-- --:--:-- 22965
100 13320  100 13320    0     0  22990      0 --:--:-- --:--:-- --:--:-- 22965
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1301      0 --:--:-- --:--:-- --:--:--  1303
gpg: Signature made Thu 23 Nov 2023 06:22:37 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  24520      0 --:--:-- --:--:-- --:--:-- 24569
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1553      0 --:--:-- --:--:-- --:--:--  1551
100   833  100   833    0     0   1552      0 --:--:-- --:--:-- --:--:--  1551
gpg: Signature made Fri 24 Nov 2023 09:49:40 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency libc++@26b if necessary...
Found libc++ in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libc++ to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency abseil-cpp@20230802.1 if necessary...
Found abseil-cpp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/a/abseil-cpp/abseil-cpp_20230802.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1043k  100 1043k    0     0  15.3M      0 --:--:-- --:--:-- --:--:-- 15.4M
extracting abseil-cpp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency zlib@1.3 if necessary...
Found zlib in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting zlib to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libprotobuf@2:22.4-2 if necessary...
Found libprotobuf in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libp/libprotobuf/libprotobuf_2:22.4-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  984k  100  984k    0     0  14.0M      0 --:--:-- --:--:-- --:--:-- 14.1M
extracting libprotobuf to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency protobuf-dev@2:22.4-2 if necessary...
Found protobuf-dev in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/protobuf-dev/protobuf-dev_2:22.4-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2796  100  2796    0     0   5180      0 --:--:-- --:--:-- --:--:--  5187
extracting protobuf-dev to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency protobuf@2:22.4-2 if necessary...
Found protobuf in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/protobuf/protobuf_2:22.4-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  693k  100  693k    0     0  9151k      0 --:--:-- --:--:-- --:--:-- 9240k
extracting protobuf to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libutf8-range@2:22.4-2 if necessary...
Found libutf8-range in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libu/libutf8-range/libutf8-range_2:22.4-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5816  100  5816    0     0   9926      0 --:--:-- --:--:-- --:--:--  9941
extracting libutf8-range to /home/builder/.termux-build/_cache-aarch64...
Downloading https://github.com/protobuf-c/protobuf-c/releases/download/v1.5.0/protobuf-c-1.5.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0  495k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  495k  100  495k    0     0  1520k      0 --:--:-- --:--:-- --:--:-- 15.6M
Applying patch: protobuf-c-1.4.1-protobuf-22.0.patch
1 out of 2 hunks FAILED -- saving rejects to file protoc-c/c_helpers.cc.rej
2 out of 2 hunks FAILED -- saving rejects to file protoc-c/c_message.cc.rej
1 out of 3 hunks FAILED -- saving rejects to file protoc-c/c_primitive_field.cc.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-11-26 00:33:24 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/6992210740">6992210740</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by 2096779623**
Close #18575 .

### CODE REVIEW

**Comment by 2096779623** [comment]
I have no idea to fix this error, can anyone help?

**Comment by twaik** [comment]
Seems like your error is 
```
[30/41] Linking C shared library libz.so.1.2.11
FAILED: libz.so.1.2.11 
: && /home/twaik/.termux-build/_cache/android-r26b-api-24-v0/bin/aarch64-linux-android-clang -fPIC -fstack-protector-strong -Oz --target=aarch64-linux-android24  -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -landroid-execinfo --target=aarch64-linux-android24 -Wl,--version-script,"/home/twaik/.termux-build/libarrow-cpp/build/orc_ep-prefix/src/orc_ep-build/zlib_ep-prefix/src/zlib_ep/zlib.map" -shared -Wl,-soname,libz.so.1 -o libz.so.1.2.11 CMakeFiles/zlib.dir/adler32.o CMakeFiles/zlib.dir/compress.o CMakeFiles/zlib.dir/crc32.o CMakeFiles/zlib.dir/deflate.o CMakeFiles/zlib.dir/gzclose.o CMakeFiles/zlib.dir/gzlib.o CMakeFiles/zlib.dir/gzread.o CMakeFiles/zlib.dir/gzwrite.o CMakeFiles/zlib.dir/inflate.o CMakeFiles/zlib.dir/infback.o CMakeFiles/zlib.dir/inftrees.o CMakeFiles/zlib.dir/inffast.o CMakeFiles/zlib.dir/trees.o CMakeFiles/zlib.dir/uncompr.o CMakeFiles/zlib.dir/zutil.o   && :
ld.lld: error: version script assignment of 'local' to symbol 'gz_intmax' failed: symbol not defined
```
Checkoing how to fix this.

**Comment by twaik** [comment]
`sed '/gz_intmax/d' ${TERMUX_PKG_BUILDDIR}/orc_ep-prefix/src/orc_ep-build/zlib_ep-prefix/src/zlib_ep/zlib.map` on post configure step should be enough, but I am not sure about this.

**Comment by twaik** [comment]
Or you can patch `${TERMUX_PKG_BUILDDIR}/orc_ep-prefix/src/orc_ep-build/zlib_ep-prefix/src/zlib_ep/gzlib.c:625` to define `unsigned ZLIB_INTERNAL gz_intmax() { return INT_MAX; } in the case if INT_MAX is defined.

**Comment by 2096779623** [comment]
This PR will be merged after 4 hours if there is no need to modify it.

**Pull request merged**
