### PR TITLE
Cache dependencies for Golang packages

### PR DESCRIPTION
**Pull request by thunder-coding**
TODOs:

- [x] aerc
- [x] age
- [x] algernon
- [x] android-tools
- [x] antibody
- [x] aptly
- [x] brook
- [x] caddy
- [x] chezmoi
- [x] clash
- [x] croc
- [x] delve
- [x] direnv
- [x] duf
- [x] elvish
- [x] flyctl
- [x] fzf
- [x] gbt
- [x] germanium
- [x] geth
- [x] gh
- [x] git-lfs
- [x] gitea
- [x] glow
- [x] go-findimagedupes
- [x] gogs
- [ ] golang
- [x] gopass
- [x] gotty
- [x] helm
- [x] hub
- [x] hugo
- [x] hydroxide
- [x] ipfs
- [x] jfrog-cli
- [x] k9s
- [x] keybase
- [x] kubectl
- [x] lazygit
- [x] lf
- [x] lnd
- [x] micro
- [x] o-editor
- [x] obfs4proxy
- [x] proton-bridge
- [x] pup
- [x] rclone
- [x] restic
- [x] rush
- [x] shell2http
- [x] shfmt
- [x] shiori
- [x] slides
- [x] sops
- [x] syncthing
- [x] teleport-tsh
- [x] tweego
- [x] vegeta
- [x] virustotal-cli
- [x] wuzz
- [x] youtubedr

### CODE REVIEW

**Comment by thunder-coding** [comment]
Network errors, 😒

**Comment by thunder-coding** [comment]
Out of disk space problems 🧐

**Comment by thunder-coding** [comment]
Everything done, and about `golang`, I don't think people build it on device

**Comment by xeffyr** [comment]
Does it really work? I've tried to build `rclone` multiple times and network activity monitor showed that deps are mostly, if not completely, redownloaded.

**Comment by thunder-coding** [comment]
> Does it really work? I've tried to build `rclone` multiple times and network activity monitor showed that deps are mostly, if not completely, redownloaded.

It only works for on device builds

**Review by xeffyr — APPROVED** [review]

**Comment by thunder-coding** [comment]
Yeah @xeffyr, you are correct. Caching isn't working b109e79c2cdc870ebb8313516f9bfcec4622a310 (Running `go get` again after restoring cache messed it up). We need to invalidate cache when `go.sum` file is changed., probably by storing `go.sum` SHA256 somewhere

**Comment by xeffyr** [comment]
@thunder-coding Maybe just put GOPATH into cache dir and don't touch it (e.g. copying to builddir) then?

**Comment by thunder-coding** [comment]
> @thunder-coding Maybe just put GOPATH into cache dir and don't touch it (e.g. copying to builddir) then?

Oh yeah, that would have been much cleaner than the current approach. 
Just dont `go get` and `go build` takes care of it 🤦

**Comment by thunder-coding** [comment]
But as your approach there is a major problem. Patching dependencies would come at a cost of dependency cache

**Comment by thunder-coding** [comment]
Anyways @xeffyr, just revert the merge for now, I will come up with a better fix fot this soon

**Pull request merged**
