### PR TITLE
new package: predict

### PR DESCRIPTION
**Pull request by 2096779623**

### CODE REVIEW

**Comment by thunder-coding** [comment]
@2096779623, I'm seeing you closing your PR and opening another one multiple times. Can you please stick to one PR ?

**Comment by 2096779623** [comment]
> @2096779623, I'm seeing you closing your PR and opening another one multiple times. Can you please stick to one PR ?

definitely next time.

**Comment by 2096779623** [comment]
> 

I want to reduce the number of commits as much as possible.

**Comment by xtkoba** [comment]
> I want to reduce the number of commits as much as possible.

Then <a href="https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits">squash them</a>.

**Comment by xtkoba** [comment]
Currently nothing useful is installed.

```
$ tar tf data.tar.xz
./
./data/
./data/data/
./data/data/com.termux/
./data/data/com.termux/files/
./data/data/com.termux/files/usr/
./data/data/com.termux/files/usr/opt/
./data/data/com.termux/files/usr/opt/predict/
./data/data/com.termux/files/usr/opt/predict/.version
./data/data/com.termux/files/usr/share/
./data/data/com.termux/files/usr/share/man/
./data/data/com.termux/files/usr/share/man/man1/
./data/data/com.termux/files/usr/share/man/man1/predict.1.gz
./data/data/com.termux/files/usr/share/doc/
./data/data/com.termux/files/usr/share/doc/predict/
./data/data/com.termux/files/usr/share/doc/predict/LICENSE
$
```

**Comment by 2096779623** [comment]
> > I want to reduce the number of commits as much as possible.
> 
> Then [squash them](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits).

Thanks.

**Pull request closed without merging**
