### PR TITLE
add dbus-glib and telepathy-glib for zeitgeist

### PR DESCRIPTION
**Pull request by RossComputerGuy**
More packages needed for midori, maybe I shouldve done a big branch instead of a bunch of small ones.

### CODE REVIEW

**Comment by xeffyr** [comment]
Examples should be excluded from build since they use utilities compiled for target architecture. This results in the following error:
```
dbus-binding-tool: cannot execute binary file: Exec format error
```

**Comment by RossComputerGuy** [comment]
I wont be able to fix it right now since Im getting a DNS issue with the freedesktop website so I cant download and check the configure options and i'll be busy most of the day.On Jul 13, 2019 6:03 AM, Leonid Plyushch <notifications@github.com> wrote:Examples should be excluded from build since they use utilities compiled for target architecture. This results in the following error:
dbus-binding-tool: cannot execute binary file: Exec format error

**Comment by RossComputerGuy** [comment]
Nevermind about the site losding, its working now. I see no way to disable examples, only tests.On Jul 13, 2019 6:35 AM, Tristan Ross <notifications@github.com> wrote:I wont be able to fix it right now since Im getting a DNS issue with the freedesktop website so I cant download and check the configure options and i'll be busy most of the day.On Jul 13, 2019 6:03 AM, Leonid Plyushch <notifications@github.com> wrote:Examples should be excluded from build since they use utilities compiled for target architecture. This results in the following error:



dbus-binding-tool: cannot execute binary file: Exec format error

**Comment by xeffyr** [comment]
Examples can be disabled by patching dbus/Makefile.{in,am} files. But after that I'm getting another error:
```
make[2]: Entering directory '/home/builder/.termux-build/dbus-glib/src/tools'
../dbus/dbus-binding-tool --mode=glib-client --prefix=dbus_bus --output=dbus-glib-bindings.h ../dbus-bus-introspect.xml
../dbus/dbus-binding-tool: line 117: /home/builder/.termux-build/dbus-glib/src/dbus/.libs/dbus-binding-tool: No such file or directory
```

I guess will be better to do a host build, then provide host `dbus-binding-tool` via `--with-dbus-binding-tool=` configure option.

**Pull request merged**
