### PR TITLE
subversion: build perl bindings for git svn

### PR DESCRIPTION
**Pull request by tomty89**

### CODE REVIEW

**Comment by fornwall** [comment]
As `perl` is a reather heavy dependency, could you split out the bindings to a subpackage, so that `subversion` could still be installed without perl?

**Comment by tomty89** [comment]
@fornwall I didn't add it as dependency but build dependency. Do you think it needs to be a subpackage with dependency? Coz to me that isn't necessary for language bindings. (As for git, we may add subversion and perl as "Recommends", although we barely do "Recommends" in Termux.)

**Comment by fornwall** [comment]
Ah sorry, I missed that it was only a build dependency!

I agree - I don't think we need to split it out to a subpackage then.

**Comment by tomty89** [comment]
```
Running Mkbootstrap for _Core ()

chmod 644 "_Core.bs"

"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- _Core.bs blib/arch/auto/SVN/_Core/_Core.bs 644

x86_64-linux-gnu-gcc -c  -I/data/data/com.termux/files/usr/include/apr-1   -I/data/data/com.termux/files/usr/include/apr-1  -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/lib/perl5/5.26.2/aarch64-android/CORE   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/home/builder/.termux-build/subversion/src/subversion/bindings/swig/perl/libsvn_swig_perl  -I/home/builder/.termux-build/subversion/src/subversion/include  -I../../../../../subversion  -I/home/builder/.termux-build/subversion/src/subversion/bindings/swig -g -Werror=unknown-warning-option  -Oz -std=c11   -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64    -DVERSION=\"\" -DXS_VERSION=\"\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.26/CORE"  -I/data/data/com.termux/files/usr/include -I/data/data/com.termux/files/usr/lib/perl5/5.26.2/aarch64-android/CORE   -DLINUX -D_REENTRANT -D_GNU_SOURCE core.c

[01m[Kcc1:[m[K [01;31m[Kerror: [m[Kargument to â€˜[01m[K-O[m[Kâ€™ should be a non-negative integer, â€˜[01m[Kg[m[Kâ€™, â€˜[01m[Ks[m[Kâ€™ or â€˜[01m[Kfast[m[Kâ€™

[01m[Kcc1:[m[K [01;31m[Kerror: [m[K-Werror=unknown-warning-option: no option -Wunknown-warning-option

Makefile:360: recipe for target 'core.o' failed

make[1]: *** [core.o] Error 1

make[1]: Leaving directory '/home/builder/.termux-build/subversion/build/subversion/bindings/swig/perl/native'

Makefile:876: recipe for target 'swig-pl' failed

make: *** [swig-pl] Error 2

Error building subversion
```

Not sure why it used `x86_64-linux-gnu-gcc` instead of `aarch64-linux-android-clang` when building the perl bindings...

**Comment by tomty89** [comment]
```
$ cd subversion-1.10.0/subversion/bindings/swig/perl/native/
$ find ./ -exec grep aarch64-linux-android {} +
./Makefile:AR = aarch64-linux-android-ar
./Makefile:CC = aarch64-linux-android-clang
./Makefile:LD = aarch64-linux-android-clang
./Makefile:RANLIB = aarch64-linux-android-ranlib
./Makefile:     aarch64-linux-android-clang -E -P -c $(PASTHRU_INC) $(INC) \
./Makefile.client:AR = aarch64-linux-android-ar
./Makefile.client:CC = aarch64-linux-android-clang
./Makefile.client:LD = aarch64-linux-android-clang
./Makefile.client:RANLIB = aarch64-linux-android-ranlib
./Makefile.client:      aarch64-linux-android-clang -E -P -c $(PASTHRU_INC) $(INC) \
./Makefile.delta:AR = aarch64-linux-android-ar
./Makefile.delta:CC = aarch64-linux-android-clang
./Makefile.delta:LD = aarch64-linux-android-clang
./Makefile.delta:RANLIB = aarch64-linux-android-ranlib
./Makefile.delta:       aarch64-linux-android-clang -E -P -c $(PASTHRU_INC) $(INC) \
./Makefile.fs:AR = aarch64-linux-android-ar
./Makefile.fs:CC = aarch64-linux-android-clang
./Makefile.fs:LD = aarch64-linux-android-clang
./Makefile.fs:RANLIB = aarch64-linux-android-ranlib
./Makefile.fs:  aarch64-linux-android-clang -E -P -c $(PASTHRU_INC) $(INC) \
./Makefile.ra:AR = aarch64-linux-android-ar
./Makefile.ra:CC = aarch64-linux-android-clang
./Makefile.ra:LD = aarch64-linux-android-clang
./Makefile.ra:RANLIB = aarch64-linux-android-ranlib
./Makefile.ra:  aarch64-linux-android-clang -E -P -c $(PASTHRU_INC) $(INC) \
./Makefile.repos:AR = aarch64-linux-android-ar
./Makefile.repos:CC = aarch64-linux-android-clang
./Makefile.repos:LD = aarch64-linux-android-clang
./Makefile.repos:RANLIB = aarch64-linux-android-ranlib
./Makefile.repos:       aarch64-linux-android-clang -E -P -c $(PASTHRU_INC) $(INC) \
./Makefile.wc:AR = aarch64-linux-android-ar
./Makefile.wc:CC = aarch64-linux-android-clang
./Makefile.wc:LD = aarch64-linux-android-clang
./Makefile.wc:RANLIB = aarch64-linux-android-ranlib
./Makefile.wc:  aarch64-linux-android-clang -E -P -c $(PASTHRU_INC) $(INC) \
$
```

We can probably run some `sed`s in the `$(SWIG_PL_DIR)/native/Makefile` target. It's just the fifth recurring instace is a bit tricky...

**Comment by tomty89** [comment]
```
Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/auto/SVN/_Ra/_Ra.so

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/auto/SVN/_Wc/_Wc.so

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/auto/SVN/_Core/_Core.so

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/auto/SVN/_Fs/_Fs.so

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/auto/SVN/_Client/_Client.so

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/auto/SVN/_Repos/_Repos.so

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/auto/SVN/_Delta/_Delta.so

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/SVN/Wc.pm

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/SVN/Ra.pm

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/SVN/Client.pm

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/SVN/Core.pm

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/SVN/Delta.pm

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/SVN/Repos.pm

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/SVN/Base.pm

Installing /data/data/com.termux/files/usr/lib/x86_64-linux-gnu/perl/5.26.1/SVN/Fs.pm
```
Closing this, as it would be too ugly to further patch the Makefile for this. Better off build it on site.

**Pull request closed without merging**
