### PR TITLE
sabnzbd: python target dependencies

### LINKED ISSUE #20060: [Bug]: sabnzbd>=4.3.0 missing dependency apprise
### Problem description

Sabnzbd doesn't start anymore after updating to 4.3.1 due to the missing module apprise

```
ModuleNotFoundError: No module named 'apprise'
```

According to the changelog apprise should already been present in 4.3.0. so it will probably also not start.

However I have not tested it as I previously ran 4.2.3

### What steps will reproduce the bug?

Update to 4.3.1

### What is the expected behavior?

Sabnzbd should start

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=12574
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.3san.dev/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://termux.3san.dev/termux/termux-root root stable
Updatable packages:
sabnzbd/stable 4.3.1 all [upgradable from: 4.2.3]
termux-tools version:
1.42.0
Android version:
14
Kernel build information:
Linux localhost 4.9.337-perf-g56f4118d056c #1 SMP PREEMPT Fri May 3 21:35:49 UTC 2024 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
POCO F1
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

### PR DESCRIPTION
**Pull request by tqfx**
Close #20060

### CODE REVIEW

**Comment by tqfx** [comment]
How about using termux_step_post_get_source to get the dependencies of the python target?

```sh
termux_step_post_get_source() {
	export TERMUX_PKG_PYTHON_TARGET_DEPS=""
	while IFS="" read -r dep
	do
		if [ -z "$dep" ]; then
			break
		fi
		dep="${dep/[# ]*}"
		if [ -z "$dep" ]; then
			continue
		fi
		TERMUX_PKG_PYTHON_TARGET_DEPS+="'$dep', "
	done < $TERMUX_PKG_SRCDIR/requirements.txt
}
```

**Comment by licy183** [comment]
For this package, parsing them from `requirements.txt` seems okay, because it is not a regular python package, but a program using python.

Maybe it is off-topic, but I want to discuss this issue for other regular python packages.

In fact, in python packages, `requirements.txt` does not guarantee that all existing items are runtime dependencies - it may contain some build-time dependencies, or some dependencies that exist when building the extra module. If possible, a better approach is to get the `METADATA` file from the already-built wheel and read the `Requires-Dist` entry from it. Besides, just installing the package itself in `postinst` will be a possible approach to this issue too.

```
termux_step_create_debscripts() {
	cat <<- EOF > ./postinst
	#!$TERMUX_PREFIX/bin/sh
	echo "Installing dependencies through pip..."
	pip3 install the-package-name
	EOF
}
```

**Review by TomJo2000 — APPROVED** [review]
I think we're good to merge this in the meantime.

**Comment by licy183** [comment]
Thanks!

**Pull request merged**
