### PR TITLE
chore(x11/kf5): Prevent auto-updating to version 6.x.x

### PR DESCRIPTION
**Pull request by Biswa96**
%ci:no-build

### CODE REVIEW

**Comment by Biswa96** [comment]
Need reviews who actually knows what happens with version regex in hindsight.

**Comment by TomJo2000** [comment]
> Need reviews who actually knows what happens with version regex in hindsight.

That check is done here.
https://github.com/termux/termux-packages/blob/388cd7e4279e8a1e154fd3af572aa79d9d72cefa/scripts/updates/utils/termux_pkg_upgrade_version.sh#L20-L32
I personally think the variable names are a bit misleading, but the latest version number is compared against the PCRE specified in `TERMUX_PKG_UPDATE_VERSION_REGEXP` and the autoupdate is only allowed if the regex matches.

**Comment by TomJo2000** [comment]
Assuming say a 5.117.0 release, yes they would.
As that will match the regex.

**Comment by Biswa96** [comment]
The regexp condition did not work. There are now multiple auto update issues.

**Comment by Biswa96** [comment]
Auto update was disabled for kf5 packages in ebce607fd20fe5052eb58b59e2e6ee132a78c2c1 commit because "Repology reports only latest version so filtering with `TERMUX_PKG_UPDATE_VERSION_REGEXP="5\.\d+\.\d+"` does not work.".

I agree with the change. kf5 is now in feature freeze mode. New versions of those packages will be released less frequently and can be updated manually.

**Comment by TomJo2000** [comment]
We could take a page out of for example `gopls`' build script and override the auto update function.
https://github.com/termux/termux-packages/blob/1ce8e58993e07acd3c8365cc8247c0015d1a46bf/packages/gopls/build.sh#L8-L21

**Pull request merged**
