### PR TITLE
libicu: Bump to 70.1

### PR DESCRIPTION
**Pull request by thunder-coding**
New version of ICU was released a few days ago, let's bump this.

TODOs :-

- [x] libical
- [x] libzim
- [x] music-file-organizer
- [x] nodejs-lts
- [x] nodejs
- [x] php
- [x] postgresql
- [x] samba
- [ ] swift (I will leave this on @buttaface to do just like the previous time)
- [x] texlive-bin

### CODE REVIEW

**Comment by thunder-coding** [comment]
Samba, old version tarball has been removed, I need to update it to latest version in same PR

**Comment by thunder-coding** [comment]
The current errors for php, 

We need to either wait for libgd newer version to be released (
 https://github.com/libgd/libgd/issues/777), or update php to newer version

**Comment by buttaface** [comment]
Yes, I will bump Swift separately because that takes a while to build.

**Comment by thunder-coding** [comment]
This is now ready to merge. After this is merged, someone needs to look into `samba` and `php` newer versions, we are quite too lacking in terms of the two packages.

**Pull request merged**
