### PR TITLE
Su-Do-Ku!

### PR DESCRIPTION
**Pull request by vaites**
[Su-Do-Ku!](https://github.com/cinemast/sudoku) is a console based sudoku generator/solver

screenshot_20160424-103217

### CODE REVIEW

**Comment by Wetitpig** [comment]
I think packages should not be for entertainment, but for facilitating scripting.

**Comment by vishalbiswas** [comment]
@Wetitpig I disagree. This looks like something I may wan't to waste time on.

**Comment by vaites** [comment]
Termux aims to be a repository like any other in Linux world (I think) with
software of any category. It has games like GNU Chess of GNU Go, even
rogue-like ones...

**Comment by Wetitpig** [comment]
Ok... Maybe integrate it with some other games like chess. Would that be better?

**Comment by vishalbiswas** [comment]
It has been 2 years since last update to that repo. No wonder this hasn't been merged.

**Comment by fornwall** [comment]
I'm closing this for now, but anyone is welcome to create a third-party repository with e.g. https://github.com/termux/termux-apt-repo (if so, we can link to third-party repositories for discoverability).

**Pull request closed without merging**
