### PR TITLE
add shell completion for parallel

### PR DESCRIPTION
**Pull request by Freed-Wu**

### CODE REVIEW

**Review by MrAdityaAlok — CHANGES_REQUESTED** [review]
Move `src/_parallel` to `TERMUX_PKG_BUILDER_DIR` and give it some meaningful name such as `zsh-completions`.

**Comment by Freed-Wu** [comment]
A meaningful name may be good. And, I think the upstream should provide this script and add a target named `install-zsh-completion` in Makefile, then the downstream just `make install` may be better?

**Comment by MrAdityaAlok** [comment]
> A meaningful name may be good. And, I think the upstream should provide this script and add a target named `install-zsh-completion` in Makefile, then the downstream just `make install` may be better?

Yah! That should be better, but unless upstream provides you should follow as suggested.

Have you upstreamed that patch?

**Comment by Freed-Wu** [comment]
I'll concact upstream to request them to do it. `:)`

**Comment by MrAdityaAlok** [comment]
> I'll concact upstream to request them to do it. `:)`

It's good!

Please apply requested changes. I do not think GNU will release so soon with your requested changes (if they accepted).

One more suggestion. Instead of moving to `TERMUX_PKG_BUILDER_DIR` you may put it directly in build.sh as:
```bash

mkdir -p $TERMUX_PREFIX/share/zsh/site-functions/_parallel

cat <<- EOF > $TERMUX_PREFIX/share/zsh/site-functions/_parallel

	#compdef parallel
	
	(( $+functions[_comp_parallel] )) ||
 		eval "$(parallel --shell-completion auto)" &&
 		_comp_parallel
 
EOF
```

**Comment by Freed-Wu** [comment]
OKay:)

**Review by MrAdityaAlok — APPROVED** [review]

**Pull request merged**
