### PR TITLE
Add a package for full clang/llvm

### PR DESCRIPTION
**Pull request by phcoder**
Full clang allows to have cross-compilations to other architectures

### CODE REVIEW

**Comment by phcoder** [comment]
The failure is due to time limit

**Comment by fornwall** [comment]
I guess this would need some other additions (like binutils) as well to be useful?

How large is the size increase in the package of enabling all targets? If it's not too big we could enable it in the normal clang/llvm package without splitting it up.

**Comment by phcoder** [comment]
This makes libllvm about 3MiB larger. Other package sizes are unchanged. Yes, you're right, it's too small to be worth the hassle of splitted packages. Clang has integrated assembled and I'm working on adding lld, so that we have a linker for all the platforms. This is enough to compile standalone programs like libc, kernels and bootloaders (my goal, to use with qemu) but for userspace additional work would be required. I'll remake the branch

**Comment by phcoder** [comment]
I updated this pull request. Now it has LLD and doesn't split anymore. I was able to compile GRUB on my phone with this (+update to svn snapshot of llvm which is subject of separate pull request)
BTW: could you have a look at your emails, thanks

**Comment by joakim-noah** [comment]
Nice work, I especially like the lld inclusion, which should finally obsolete binutils.

I want to try out cross-compiling for desktop/server platforms too, like Windows/x64 or linux/x64, whereas you seem to focus on other Android platforms with this pull.  Do you know how much more would need to be added to get small desktop/server C executables built with the clang from this pull?

**Comment by phcoder** [comment]
I don't think we can deprecate binutils just yet. Binutils has nm, objdump and strip. Later is needed by some programs to compile. As for desktop/server executables you needs libs and includes for the platform in question

**Comment by joakim-noah** [comment]
I can get the libs and platform includes, especially easy for linux, and I guess the compiler includes should all be there because we're just building stock clang, not the NDK clang.  I'll try it sometime.

**Comment by phcoder** [comment]
Ping?

**Comment by shawnl** [comment]
I want this for to make distccd useful (distcc is already useful, and easy to build)

**Comment by fornwall** [comment]
@phcoder Thanks and sorry for the delay here! The updated llvm and clang packages are now available for installation (update with `pkg up`) at version 5.0.0-1.

**Comment by shawnl** [comment]
CANNOT LINK EXECUTABLE "clang": cannot locate symbol "LLVMInitializeAArch64TargetInfo" referenced by "/data/data/com.termux/files/usr/bin/clang-5.0"...


when trying to cross compile

**Comment by shawnl** [comment]
This is on armv7 (32-bit)

**Comment by joakim-noah** [comment]
Are you sure you have the latest clang?  Seems to work for me.

**Comment by shawnl** [comment]
Didn't upgrade libllvm as well. Sry.

**Comment by fornwall** [comment]
@shawnl No problem. Currently Termux package updated are very laxy with version qualifiers, generally assuming that all dependencies are at their latest versions. So the current best practice is to always update all packages (`pkg up`) instead of updating a single package (and also to update all packages before installing a new package).

**Comment by shawnl** [comment]
Works with distcc https://github.com/termux/termux-packages/pull/1785

**Pull request merged**
