### PR TITLE
fix(main/clvk): temp revert upstream commit

### PR DESCRIPTION
**Pull request by truboxl**
The commit introduced a regression
dlopen failed: cannot locate symbol "vkGetBufferDeviceAddress"

### CODE REVIEW

**Comment by xtkoba** [comment]
This does not seem to change anything for me. Both with and without this fix I have:

```
ocl-icd(/home/builder/.termux-build/ocl-icd/src/ocl_icd_loader.c:213): _load_icd: error while dlopening the IDL: 'dlopen failed: cannot locate symbol "vkGetPhysicalDeviceFeatures2" referenced by "/data/data/com.termux/files/usr/lib/clvk/libOpenCL.so"...',
```

Indeed `vkGetBufferDeviceAddress` (without fix) and `vkGetPhysicalDeviceFeatures2` (with and without fix) are the symbols in `lib/clvk/libOpenCL.so` with `Type Bind Vis Ndx` being `NOTYPE GLOBAL DEFAULT UND` (almost always a necessary condition of "undefined reference" error.)

**Comment by xtkoba** [comment]
BTW is this PR intended to be for merge?

I suggest it be clarified that "6ccb8a03" is an upstream commit hash. Reference to upstrem issue is also suggested: https://github.com/kpet/clvk/issues/491.

**Comment by truboxl** [comment]
It is expected for `clvk` to only work on Android 9 as a minimum as noted in `build.sh` since that's where system `libvulkan.so` is sufficiently supported
I dont believe upstream is care enough to bump down to low as Android 7 and I am not sure I am willing to go that far to support

**Comment by xtkoba** [comment]
Then can it be linked against `libvulkan.so` in `28` directory? "NOTYPE GLOBAL DEFAULT UND" is somewhat misleading.

**Comment by xtkoba** [comment]
See `build.sh` of `pulseaudio` for example.

**Pull request merged**
