### PR TITLE
[android-5] termux-upgrade-repo: fix shebang, and only try to install packages that are installable

### PR DESCRIPTION
**Pull request by Grimler91**
Use comm to get intersection of packages_to_install and installable_packages. Works with both busybox and coreutils comm.

Should get rid of errors that packages can't be found.

### CODE REVIEW

**Comment by xeffyr** [comment]
It doesn't work properly. Package "libutil" appeared again in installation list.

**Comment by xeffyr** [comment]
Worked okay.

**Comment by xeffyr** [comment]
No. Still not working properly.
Just verified installed packages - ones from unstable-repo and x11-repo are not getting installed.

**Comment by Grimler91** [comment]
@xeffyr Not getting installed as in they don't appear in the `apt install` command or as in the `apt install` command fails? 

I've only tried it from an android 7 device but x11 packages and unstable-packages seem to be included in the `apt install` list

**Comment by Grimler91** [comment]
Ah, I think I understand where I messed up now. Can't use the same dpkg-query to get list of reinstallable packages after `rm -rf $PREFIX`

**Comment by xeffyr** [comment]
termux-reinstall.sh was executed without error but packages from additional repositories are not re-installed.

**Comment by Grimler91** [comment]
@xeffyr Could you give it another shot when you have time?

**Comment by xeffyr** [comment]
Now works.

**Pull request merged**
