### PR TITLE
add package tor

### PR DESCRIPTION
**Pull request by vishalbiswas**
Tor is an anonymizing program. Also, known as The Onion Router.

### CODE REVIEW

**Comment by fornwall** [comment]
Awesome! I've updated the package to version 0.2.9.8, and it's now available in the apt repository for installation.

**Comment by fornwall** [comment]
It would be nice to have torsocks. I've started a disabled package at https://github.com/termux/termux-packages/tree/master/disabled-packages/torsocks, it builds but segfaults when trying to run any program under it.

**Comment by vishalbiswas** [comment]
@fornwall Actually, no, it doesn't segfault. The error is generated internally because its trying to find libc.so.6, whereas we have libc.so on our mobile devices. The following patch fixes it:
```diff
--- ./configure.ac      2016-10-18 22:14:01.000000000 +0530
+++ ../configure.ac     2016-12-21 09:33:09.557722947 +0530
@@ -131,6 +131,7 @@
        ],
        [libc_name="libc.so"]
 )
+libc_name="libc.so"
 AC_DEFINE_UNQUOTED([LIBC_NAME],["${libc_name}"], [Description])
 AC_MSG_RESULT($libc_name)

```

**Comment by fornwall** [comment]
@vishalbiswas Nice! I've added a libc_name patch to configure.ac, and torsocks works for me now when I test!

Does it not work for you (are you sure you run with tor up on the default SOCKS proxy port)? On which device&android version?

**Comment by vishalbiswas** [comment]
It works with ip addresses but as soon as you try to resolve a hostname it fails. Try `torsocks ping google.com`

**Comment by fornwall** [comment]
Hm, right, `ping` fails to resolve hostnames. 

But it seems that `curl` and `ssh` manages to do it?

**Comment by vishalbiswas** [comment]
Neither does lynx

**Comment by vishalbiswas** [comment]
I am able to get upto the Debug message at gethostbyname.c:68, but it doesn't reach the next debug message.

**Pull request merged**
