### PR TITLE
helix: Separate grammar-related files as subpackages

### PR DESCRIPTION
**Pull request by xtkoba**
* Install under `$PREFIX/opt`

### CODE REVIEW

**Comment by xtkoba** [comment]
Handed over to @MrAdityaAlok.

**Comment by MrAdityaAlok** [comment]
This would not make much difference. Other package will still occupy more than 800mb's when unpacked.

**Comment by xtkoba** [comment]
> This would not make much difference. Other package will still occupy more than 800mb's when unpacked.

Doesn't make sense to me. What is other package here?

From time to time we receive requests to reduce package size. For example I already did some work for `boost` and `openjdk-17`. I believe this makes a non-negligile difference.

Also note that this saves disk space for bindist mirrors as well. `helix-grammars-source_22.12-1_all.deb` takes about 77MiB. So 230MiB of space will be saved.

**Comment by MrAdityaAlok** [comment]
@xtkoba I'm really sorry! I misunderstood things. Grammars sources should never be packaged. That was was my mistake. I highly apologise for the mistake 🙏🏼.

I'll fix it.

**Pull request merged**
