### PR TITLE
racket: Bump to 8.6

### PR DESCRIPTION
**Pull request by xtkoba**

### CODE REVIEW

**Comment by xtkoba** [comment]
Not working.

**Comment by zorro** [comment]
What was the error? I tried the aarch64 package on an android 9 device and it is working fine

**Comment by xtkoba** [comment]
Yes, it works. Just that my testing environment was wrong. Thanks!

**Comment by xtkoba** [comment]
Merged as ede8de9548c3a2543e978f7d95b2f72b05c2476c.

**Comment by xtkoba** [comment]
And 8a854165d35254b1c11e6481c16e279ff64d9948.

**Pull request closed without merging**
