### PR TITLE
packages: add keybase and kbfs

### LINKED ISSUE #2133: Package request: keybase
Hi Termux - would be awesome if keybase could be packaged for termux

I believe there used to be some issues between the termux version of go and the one keybase needs 
- not sure if that is still an issue

related issues
* https://github.com/keybase/client/issues/9152
* https://github.com/keybase/kbfs/issues/1231

Thanks!!! termux on chromeos has been amazing

Justin

### PR DESCRIPTION
**Pull request by philips**
Fixes #2133

Based on https://github.com/keybase/client/blob/master/packaging/linux/build_binaries.sh

```
./scripts/run-docker.sh ./build-package.sh kbfs
```

### CODE REVIEW

**Comment by philips** [comment]
Someone helped me in the IRC channel: 

```
./scripts/run-docker.sh ./build-package.sh -a x86_64 kbfs
```

Testing now.

**Comment by philips** [comment]
Hrm, keybase is not happy. I think it might be related to devel mode. Investigating.

```
▶ WARNING Running in devel mode
Your keybase username or email address: philips
▶ ERROR API network error: doRetry failed, attempts: 3, timeout 13.5s, last err: Get http://localhost:3000/_/api/1.0/user/lookup.json?fields=basics%2Cpublic_keys%2Cpictures&load_deleted_v2=1&multi=1&username=philips: dial tcp 127.0.0.1:3000: connect: connection refused (code 1601)
```

cc @songgao

**Comment by songgao** [comment]
Oh hi Brandon! Great to hear from you. Yeah both client binaries (keybase and kbfs) run in dev mode by default. Having an env var set `KEYBASE_RUN_MODE=prod` would put it in production mode. There’s also a `run_keybase` script in Linux distribution that has a bunch of boiler plate to start app processes. I’m guessing you might be able to even just remove the electron part and stick it in there as the entry point.

On mobile now but I can try to help more later!

**Comment by philips** [comment]
Figured it out. Fixed and pushed! `keybase` cli seems to work. The trick is the go tags.

**Comment by philips** [comment]
@songgao is there anyway to use the keybase encrypted git remote without kbfsuse? Termux doesn't support FUSE so I think I will need to abandon that.

**Comment by songgao** [comment]
@philips I think the `kbfsfuse` process provides some RPC services that's used by the remote helper (`git-remote-keybase`) so it'd need to be running. If you don't really mind having that binary running but just can't run FUSE, you can use the `-mount-type=none` flag to run the `kbfsfuse` process without actually mounting a FUSE device.

**Comment by strib** [comment]
`kbfsfuse` isn't technically needed, it's only used for accessing the persistent block cache. But the `keybase` process definitely needs to be running, to handle logging and access to the local device keys.

**Comment by fornwall** [comment]
Thanks! The new packages are now available for installation.

Should ˋkbfsˋ depend on ˋkeybaseˋ?

**Comment by songgao** [comment]
@philips please also see strib’s comment above; it should work even without kbfsfuse (probably slower in some cases because it can’t uses the local cache for blocks). So if the existing setup with both remote helper and the keybase process doesn’t work, there might be something else that’s wrong.

**Comment by Walkman100** [comment]
Thanks everyone, I have `keybase` and `kbfs` installed. When I installed `kbfs` however I noticed it didn't recommend `keybase` (and `apt show kbfs` doesn't list it either), nor did installing `keybase` recommend `kbfs`. Is this intentional?

**Comment by philips** [comment]
I think making kbfs require keybase is reasonable. I don't have a strong
opinion.

**Comment by songgao** [comment]
Yeah `kbfs` should depend on `keybase`, as it needs to talk to the `keybase` daemon. `keybase` should probably recommend `kbfs` too as people might install `keybase` thinking they'd get the Keybase Git, but it's actually provided by the `kbfs` package.

I don't have termux setup anywhere to test it though. Could any of you make the change please?

**Comment by philips** [comment]
@fornwall could you make kbfs rely on keybase? Otherwise I will try and do it next weekend.

**Comment by fornwall** [comment]
@philips Sure! That is now done in version `2.6.0-1` of the kbfs package.

**Pull request merged**
