### PR TITLE
Add package: Mailutils

### PR DESCRIPTION
**Pull request by suhan-paradkar**
As promised in #6530

### CODE REVIEW

**Comment by suhan-paradkar** [comment]
The package requires glob.h which requires API level 28 to work properly

**Comment by Grimler91** [comment]
@suhan-paradkar isn't libandroid-glob enough? What error did you get?

**Comment by xeffyr** [comment]
Yes, libandroid-glob provides the `glob.h` and related library functions. Though, package has to be linked manually by adding `-landroid-glob` to either `LIBS` or `LDFLAGS`, depending on used build system.

**Comment by suhan-paradkar** [comment]
> @suhan-paradkar isn't libandroid-glob enough? What error did you get?

It was a linker problem.. clang couldn't link 'glob' and 'globfree'

**Comment by suhan-paradkar** [comment]
> Yes, libandroid-glob provides the `glob.h` and related library functions. Though, package has to be linked manually by adding `-landroid-glob` to either `LIBS` or `LDFLAGS`, depending on used build system.

I'll try that

**Comment by xeffyr** [comment]
Needs patching for setpwent/getpwent, their calls should be removed as well as related functionality. Even though Android supports file `/etc/passwd` (`/system/etc/passwd`), its usage is very limited and in case of Termux completely useless.

See patches of `pure-ftpd` or `mc` for examples.

**Comment by suhan-paradkar** [comment]
there seems to be a peculiar problem with github actions CI
it builds the packages that are not updated in the fork of the repository along with the changed files when a pull request is submitted
'''
Package: busybox

Syntax check: PASS

TERMUX_PKG_HOMEPAGE: PASS
TERMUX_PKG_DESCRIPTION: PASS
TERMUX_PKG_LICENSE: PASS
TERMUX_PKG_MAINTAINER: PASS
TERMUX_PKG_API_LEVEL: PASS
TERMUX_PKG_VERSION: PASS
TERMUX_PKG_SRCURL: PASS
TERMUX_PKG_SHA256: PASS
TERMUX_PKG_BUILD_IN_SRC: PASS
TERMUX_PKG_SERVICE_SCRIPT: PASS

================================================================

Package: dart

Syntax check: PASS

TERMUX_PKG_HOMEPAGE: PASS
TERMUX_PKG_DESCRIPTION: PASS
TERMUX_PKG_LICENSE: PASS
TERMUX_PKG_MAINTAINER: PASS
TERMUX_PKG_API_LEVEL: PASS
TERMUX_PKG_VERSION: PASS
TERMUX_PKG_SKIP_SRC_EXTRACT: PASS
TERMUX_PKG_BUILD_IN_SRC: PASS

================================================================

Package: debootstrap

Syntax check: PASS

TERMUX_PKG_HOMEPAGE: PASS
TERMUX_PKG_DESCRIPTION: PASS
TERMUX_PKG_LICENSE: PASS
TERMUX_PKG_MAINTAINER: PASS
TERMUX_PKG_API_LEVEL: PASS
TERMUX_PKG_VERSION: PASS
TERMUX_PKG_SRCURL: NON-HTTPS (acceptable)
TERMUX_PKG_SHA256: PASS
TERMUX_PKG_BUILD_IN_SRC: PASS
TERMUX_PKG_PLATFORM_INDEPENDENT: PASS

================================================================

Package: dte

Syntax check: PASS

TERMUX_PKG_HOMEPAGE: PASS
TERMUX_PKG_DESCRIPTION: PASS
TERMUX_PKG_LICENSE: PASS
TERMUX_PKG_MAINTAINER: PASS
TERMUX_PKG_API_LEVEL: PASS
TERMUX_PKG_VERSION: PASS
TERMUX_PKG_SRCURL: PASS
TERMUX_PKG_SHA256: PASS
TERMUX_PKG_BUILD_IN_SRC: PASS

================================================================

Package: duf

Syntax check: PASS

TERMUX_PKG_HOMEPAGE: PASS
TERMUX_PKG_DESCRIPTION: PASS
TERMUX_PKG_LICENSE: PASS
TERMUX_PKG_MAINTAINER: PASS
TERMUX_PKG_API_LEVEL: PASS
TERMUX_PKG_VERSION: PASS
TERMUX_PKG_SRCURL: PASS
TERMUX_PKG_SHA256: PASS

================================================================

Package: e2fsprogs

Syntax check: PASS

TERMUX_PKG_HOMEPAGE: NON-HTTPS (acceptable)
TERMUX_PKG_DESCRIPTION: PASS
TERMUX_PKG_LICENSE: PASS
TERMUX_PKG_MAINTAINER: PASS
TERMUX_PKG_API_LEVEL: PASS
TERMUX_PKG_VERSION: PASS
TERMUX_PKG_SRCURL: PASS
TERMUX_PKG_SHA256: PASS
TERMUX_PKG_NO_STATICSPLIT: PASS
TERMUX_PKG_RM_AFTER_INSTALL: PASS
TERMUX_PKG_CONFFILES: PASS

================================================================
'''

**Comment by xeffyr** [comment]
This is not a problem. That's expected behavior from how pull request work. CI script runs the diff between base commit and the top one. As you didn't rebased your fork on latest changes in `master` branch, all intermediate packages are picked.

So `git pull --rebase` your fork, no way to workaround that.

**Comment by unknow2403** [comment]
mana apknya bos ku ? buat ulang kalian ?

Pada tanggal Rab, 5 Mei 2021 13:56, Suhan G Paradkar <
***@***.***> menulis:

**Comment by unknow2403** [comment]
capek aku nunggu !! butug dana cepat HELP ME HELP ME !!!!

Pada tanggal Rab, 5 Mei 2021 13:56, Suhan G Paradkar <
***@***.***> menulis:

**Pull request closed without merging**
