### PR TITLE
Properly package texlive and split package into texlive & texlive-bin

### PR DESCRIPTION
**Pull request by Grimler91**
This changes makes texlive more like any other package, without the need for download and installation on device.

Summary
=======

* Move binaries to arch-dependent package texlive-bin and keep everything else in
  arch-independent texlive
* Download full texmf-dist tree but only extract files in a (quite) minimal
  scheme (same scheme as in the old version of the texlive package)
* Replace tlmgr symlink with wrapper to prevent it breaking on `tlmgr update
  --self`
* Include xelatex (requested in #1069)
* No more warnings when installing (solves #1118)
* Remove files from old version before installing, except for the texmf-dist folder (to prevent people from having to download a full distribution again if they have done that).

Additional possible improvements (in the future)
================================

Handle tlpdb better
-------------------
When the version of `texlive` is bumped, the upgrade replaces the texlive.tlpdb (the texlive database containing info about which packages has been installed) with the original (minimal) one. All tlmgr packages installed since the texlive package was first installed are then no longer recognized by tlmgr. 

The files are still there and can be used but they cannot be upgraded through tlmgr.

Instead of overwriting the tlpdb on upgrade, it should be possible to merge the existing database with the one being installed. (The various scripts in texlive's dev sources at ftp://ftp.tug.org/texlive/historic/2017/texlive-20170524-devsource.tar.xz are probably useful for this).

Specify packages instead of files
---------------------------------

Instead of having {texlive-texmf,texlive-extra,install-tl}.list, we should be able to just specify which packages we want and then extract which files these packages contains from texlive.tlpdb. This would make the build a bit nicer. 

Again, I'm guessing the dev sources at ftp://ftp.tug.org/texlive/historic/2017/texlive-20170524-devsource.tar.xz would be useful for this.

Speed up tlmgr
--------------

tlmgr is quite slow at the moment, partly due to the option "--persistent-downloads" not working (due to some perl libs not being installed(?)).

### CODE REVIEW

**Comment by sdrausty** [comment]
@Grimler91 Cool. Thank you:)

**Comment by fornwall** [comment]
Impressive working maintaining texlive!

Could you fix the conflicts and let me know, so I'll merge and update the package ASAP!

**Comment by Grimler91** [comment]
@fornwall Hm, looks like I managed to rebase (cool). 

Should be ready for merge unless I'm missing something :+1:

**Comment by rnauber** [comment]
Wow, thanks for cleaning my mess!  This is far better... It worked great for me, I would love to see this patch merged...

**Comment by rnauber** [comment]
btw, could you please readd "texliveonthefly"?
Thanks!

**Comment by fornwall** [comment]
Nice! The updated packages are now available in the apt package repository for installation.

@Grimler91 @sdrausty Can `wget` be removed as a dependency for texlive or is it still used?

**Comment by Grimler91** [comment]
@rnauber woops, I didn't realise I had removed it. Must be one of the files deleted when texlive-bin removes the texmf-dist tree (line 73 in texlive-bin/build.sh). Keeping the texmf-dist from texlive-bin caused errors when installing texlive+texlive-bin as there are some files in both packages. 
I can open a pull request later. 

@fornwall some kind of wget is needed by texlive's package management. 
I think there was something about the busybox version that caused annoyance but I can re-check if it's possible to remove the dependency.

**Comment by fornwall** [comment]
> @fornwall some kind of wget is needed by texlive's package management.
I think there was something about the busybox version that caused annoyance but I can re-check if it's possible to remove the dependency.

Ok, no problem, wget is not that big of a package. The busybox wget lacks options and do not handle https, so it's understandable if texlive uses the real wget.

**Pull request merged**
