### PR TITLE
readline: Update from 7.0 to 8.0

### PR DESCRIPTION
**Pull request by TheInfected**

### CODE REVIEW

**Comment by xeffyr** [comment]
Readline 8.0 changes ABI so all dependent packages should be bumped. Done in https://github.com/termux/termux-packages/pull/3366/commits/93294a3aafc174cfd6e98c6e5c2cb1fff3990f92.

**Comment by its-pointless** [comment]
probably want to all libc++ linked at the same time as because it needs to be done with ndk update anyway?

**Comment by its-pointless** [comment]
CFLAGS+=" -fexceptions" should be added back ...

**Comment by xeffyr** [comment]
> probably want to all libc++ linked at the same time

Okay, I'll bump all C++ packages.

**Comment by TheInfected** [comment]
> CFLAGS+=" -fexceptions" should be added back ...
Yah that was typo nvm

**Comment by fornwall** [comment]
Thanks a lot! This was merged from the command line (due to some smaller conflicts) in https://github.com/termux/termux-packages/commit/03c2cf26ca6700fabb27b40ced3e3e7843ac940b

**Pull request merged**
