### PR TITLE
add libcurl to transmission dependencies

### PR DESCRIPTION
**Pull request by stephengroat**
#1169

### CODE REVIEW

**Comment by stainslav** [comment]
Help buddies I have downloaded setoolkit but it says are you root?execute it as root when running "python setup.py install" help buddies I'm in big trouble hope you one like a good answer me:)

**Comment by stephengroat** [comment]
@stainslav no problem, but this pr probably isn't the best place to ask the question. could you ask it on the gitter channel for termux?

**Comment by stainslav** [comment]
@stephengroat what's you gitter I'd?

**Comment by stephengroat** [comment]
@stainslav same as my github. you might have some luck with either a Github Issue or talking on the `termux` gitter channel (gets a lot more exposure that way!)

**Pull request merged**
