### PR TITLE
alsa-{lib,utils,plugins} and pulseaudio packages

### PR DESCRIPTION
**Pull request by ackalker**
See issue #821

### CODE REVIEW

**Comment by ackalker** [comment]
For testing on my device, I use the following script to modify some configs in `$TERMUX_PREFIX/etc/pulse`:

```sh
#!/data/data/com.termux/files/usr/bin/sh

TERMUX_PREFIX=~/../usr

sed -i $TERMUX_PREFIX/etc/pulse/daemon.conf \
    -e '/^; exit-idle-time =/{s/^; //;s/ 20/ -1/}'

# When no sinks are available, Pulseaudio automatically adds a null sink named 'auto_null.

# Stream the 'auto_null' sink over TCP.
# This can be played by Simple Protocol Player app on Google Play.
sed -i $TERMUX_PREFIX/etc/pulse/default.pa \
    -e '$aload-module module-simple-protocol-tcp source=auto_null.monitor port=12345 record=true'

# In addition, or alternatively,
# add a(nother) null sink named 'rtp' and stream it over RTP.
# This can be played by VLC, etc.
# sed -i $TERMUX_PREFIX/etc/pulse/default.pa \
#     -e '/^#load-module module-null-sink sink_name=rtp /s/#//' \
#     -e '/^#load-module module-rtp-send source=rtp.monitor$/s/#//'
```

**Comment by ackalker** [comment]
Known issues:

* Very high latency using ALSA's Pulseaudio plugin. Playing audio using `aplay` takes a very long time to start.
* `speaker-test -c 2` crashes with `Floating point exception`.

I suspect that both of the above are caused by ALSA reporting a bogus buffer size to clients. I'm still looking for a fix for this.
I cannot reproduce this on my Void Linux desktop with same version of Pulseaudio and identical `default.pa` setup. Besides the obvious difference in architecture, I think this could be due to my desktop ALSA packages and Pulseaudio having a different selection of configured dependencies.

**Comment by ackalker** [comment]
Ready to merge, I think. Please let me know if there are any issues. I have a PR for `cmus` ready to go on top of this.

**Comment by ackalker** [comment]
Force pushed update, dropped spurious file `setup-pulseaudio.sh`.

**Comment by fornwall** [comment]
Great - the `libpulseaudio` and `pulseaudio` packages are now available in the apt package repository!

**Comment by ackalker** [comment]
Thanks for merging!

**Pull request merged**
