### PR TITLE
new opencl packages

### PR DESCRIPTION
**Pull request by truboxl**
Revive #1346

`pocl` is omitted as I haven't have time to dig deep (dealing with `LLVM`, `hwloc` and update / maintain Android specific patches)
`hashcat` is omitted because reasons
Others are welcome to get messy before I did

`opencl-headers` provides OpenCL header files
`ocl-icd` provides the "portable" libOpenCL.so so other packages may start adding support for OpenCL
`clinfo` and `clpeak` can be used to test OpenCL
`clvk` is the big one, provides "experimental" OpenCL on top of Vulkan (but likely won't work for Android 8.1 and older)

### CODE REVIEW

**Comment by truboxl** [comment]
Have to do `LD_LIBRARY_PATH=$PREFIX/lib:/vendor/lib64:/vendor/lib64/egl` to detect vendor OpenCL lib and co-exist with clvk

clinfo output
```
Number of platforms                               2
  Platform Name                                   clvk
  Platform Vendor                                 clvk
  Platform Version                                OpenCL 1.2 clvk
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_khr_extended_versioning
  Platform Extensions function suffix             clvk

  Platform Name                                   ARM Platform
  Platform Vendor                                 ARM
  Platform Version                                OpenCL 2.0 v1.r26p0-01eac0.###other-sha0123456789ABCDEF0###
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_il_program cl_khr_priority_hints cl_khr_create_command_queue cl_khr_spirv_no_integer_wrap_decoration cl_khr_extended_versioning cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_size cl_arm_import_memory cl_arm_import_memory_dma_buf cl_arm_import_memory_host cl_arm_import_memory_android_hardware_buffer cl_arm_integer_dot_product_int8 cl_arm_integer_dot_product_accumulate_int8 cl_arm_integer_dot_product_accumulate_int16
  Platform Extensions function suffix             ARM

  Platform Name                                   clvk
Number of devices                                 1
  Device Name                                     Mali-G71
  Device Vendor                                   FIXME
  Device Vendor ID                                0x13b5
  Device Version                                  OpenCL 1.2 CLVK on Vulkan v1.1.131 driver 109051904
  Device UUID                                     0200a060-0100-0000-0000-000000000000
  Driver UUID                                     71e6d387-48a5-162c-605a-4203e13cdf83
  Valid Device LUID                               No
  Device LUID                                     0000-000000000000
  Device Node Mask                                0
  Device Numeric Version                          0x402000 (1.2.0)
  Driver Version                                  1.2 CLVK on Vulkan v1.1.131 driver 109051904
  Device OpenCL C Version                         OpenCL C 1.2 CLVK on Vulkan v1.1.131 driver 109051904
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               1
  Max clock frequency                             0MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             384x384x384
  Max work group size                             384
  Preferred work group size multiple (kernel)     16
  Preferred / native vector sizes
    char                                                 1 / 1
    short                                                1 / 1
    int                                                  1 / 1
    long                                                 1 / 1
    half                                                 1 / 1        (cl_khr_fp16)
    float                                                1 / 1
    double                                               1 / 1        (n/a)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              1073741824 (1024MiB)
  Error Correction support                        No
  Max memory allocation                           268435456 (256MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        None
  Image support                                   Yes
    Max number of samplers per kernel             20
    Max size for 1D images from buffer            16384 pixels
    Max 1D or 2D image array size                 1024 images
    Max 2D image size                             16383x16383 pixels
    Max 3D image size                             16383x16383x16383 pixels
    Max number of read image args                 256
    Max number of write image args                21
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max number of constant args                     8
  Max constant buffer size                        65536 (64KiB)
  Max size of kernel argument                     1024
  Queue properties
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    ILs with version                              SPIR-V                                                           0x400000 (1.0.0)
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                (n/a)
  Built-in kernels with version                   (n/a)
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_extended_versioning cl_khr_create_command_queue cl_khr_spirv_no_integer_wrap_decoration cl_arm_non_uniform_work_group_size cl_khr_suggested_local_work_size cl_khr_device_uuid cl_khr_fp16
  Device Extensions with Version                  cl_khr_global_int32_base_atomics                                 0x400000 (1.0.0)
                                                  cl_khr_global_int32_extended_atomics                             0x400000 (1.0.0)
                                                  cl_khr_local_int32_base_atomics                                  0x400000 (1.0.0)
                                                  cl_khr_local_int32_extended_atomics                              0x400000 (1.0.0)
                                                  cl_khr_byte_addressable_store                                    0x400000 (1.0.0)
                                                  cl_khr_extended_versioning                                       0x400000 (1.0.0)
                                                  cl_khr_create_command_queue                                      0x400000 (1.0.0)
                                                  cl_khr_spirv_no_integer_wrap_decoration                          0x400000 (1.0.0)
                                                  cl_arm_non_uniform_work_group_size                               0x400000 (1.0.0)
                                                  cl_khr_suggested_local_work_size                                 0x400000 (1.0.0)
                                                  cl_khr_device_uuid                                               0x400000 (1.0.0)
                                                  cl_khr_fp16                                                      0x400000 (1.0.0)

  Platform Name                                   ARM Platform
Number of devices                                 1
  Device Name                                     Mali-G71 r0p0
  Device Vendor                                   ARM
  Device Vendor ID                                0x60a00002
  Device Version                                  OpenCL 2.0 v1.r26p0-01eac0.###other-sha0123456789ABCDEF0###
  Device Numeric Version                          0x800000 (2.0.0)
  Driver Version                                  2.0
  Device OpenCL C Version                         OpenCL C 2.0 v1.r26p0-01eac0.###other-sha0123456789ABCDEF0###
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               2
  Available core IDs                              0-1
  Max clock frequency                             5MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             384x384x384
  Max work group size                             384
  Preferred work group size multiple (kernel)     4
  Preferred / native vector sizes
    char                                                16 / 4
    short                                                8 / 2
    int                                                  4 / 1
    long                                                 2 / 1
    half                                                 8 / 2        (cl_khr_fp16)
    float                                                4 / 1
    double                                               0 / 0        (n/a)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    64, Little-Endian
  Global memory size                              3820535808 (3.558GiB)
  Error Correction support                        No
  Max memory allocation                           955133952 (910.9MiB)
  Unified memory for Host and Device              Yes
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   No
    Fine-grained system sharing                   No
    Atomics                                       No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Preferred alignment for atomics
    SVM                                           0 bytes
    Global                                        0 bytes
    Local                                         0 bytes
  Max size for global variable                    65536 (64KiB)
  Preferred total size of global vars             0
  Global Memory cache type                        Read/Write
  Global Memory cache size                        262144 (256KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   32 bytes
    Pitch alignment for 2D image buffers          64 pixels
    Max 2D image size                             32768x32768 pixels
    Max 3D image size                             32768x32768x32768 pixels
    Max number of read image args                 128
    Max number of write image args                64
    Max number of read/write image args           64
  Max number of pipe args                         16
  Max active pipe reservations                    1
  Max pipe packet size                            1024
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max number of constant args                     128
  Max constant buffer size                        955133952 (910.9MiB)
  Max size of kernel argument                     1024
  Queue properties (on host)
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Queue properties (on device)
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Preferred size                                2097152 (2MiB)
    Max size                                      16777216 (16MiB)
  Max queues on device                            1
  Max events on device                            1024
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    IL version                                    SPIR-V_1.0
    ILs with version                              SPIR-V                                                           0x400000 (1.0.0)
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                (n/a)
  Built-in kernels with version                   (n/a)
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_il_program cl_khr_priority_hints cl_khr_create_command_queue cl_khr_spirv_no_integer_wrap_decoration cl_khr_extended_versioning cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_size cl_arm_import_memory cl_arm_import_memory_dma_buf cl_arm_import_memory_host cl_arm_import_memory_android_hardware_buffer cl_arm_integer_dot_product_int8 cl_arm_integer_dot_product_accumulate_int8 cl_arm_integer_dot_product_accumulate_int16
  Device Extensions with Version                  cl_khr_global_int32_base_atomics                                 0x400000 (1.0.0)
                                                  cl_khr_global_int32_extended_atomics                             0x400000 (1.0.0)
                                                  cl_khr_local_int32_base_atomics                                  0x400000 (1.0.0)
                                                  cl_khr_local_int32_extended_atomics                              0x400000 (1.0.0)
                                                  cl_khr_byte_addressable_store                                    0x400000 (1.0.0)
                                                  cl_khr_3d_image_writes                                           0x400000 (1.0.0)
                                                  cl_khr_int64_base_atomics                                        0x400000 (1.0.0)
                                                  cl_khr_int64_extended_atomics                                    0x400000 (1.0.0)
                                                  cl_khr_fp16                                                      0x400000 (1.0.0)
                                                  cl_khr_icd                                                       0x400000 (1.0.0)
                                                  cl_khr_egl_image                                                 0x400000 (1.0.0)
                                                  cl_khr_image2d_from_buffer                                       0x400000 (1.0.0)
                                                  cl_khr_depth_images                                              0x400000 (1.0.0)
                                                  cl_khr_il_program                                                0x400000 (1.0.0)
                                                  cl_khr_priority_hints                                            0x400000 (1.0.0)
                                                  cl_khr_create_command_queue                                      0x400000 (1.0.0)
                                                  cl_khr_spirv_no_integer_wrap_decoration                          0x400000 (1.0.0)
                                                  cl_khr_extended_versioning                                       0x400000 (1.0.0)
                                                  cl_arm_core_id                                                   0x400000 (1.0.0)
                                                  cl_arm_printf                                                    0x400000 (1.0.0)
                                                  cl_arm_thread_limit_hint                                         0x400000 (1.0.0)
                                                  cl_arm_non_uniform_work_group_size                               0x400000 (1.0.0)
                                                  cl_arm_import_memory                                             0x400000 (1.0.0)
                                                  cl_arm_import_memory_dma_buf                                     0x400000 (1.0.0)
                                                  cl_arm_import_memory_host                                        0x400000 (1.0.0)
                                                  cl_arm_import_memory_android_hardware_buffer                     0x400000 (1.0.0)
                                                  cl_arm_integer_dot_product_int8                                  0x400000 (1.0.0)
                                                  cl_arm_integer_dot_product_accumulate_int8                       0x400000 (1.0.0)
                                                  cl_arm_integer_dot_product_accumulate_int16                      0x400000 (1.0.0)


NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  clvk
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [clvk]
  clCreateContext(NULL, ...) [default]            Success [clvk]
  clCreateContext(NULL, ...) [other]              Success [ARM]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 clvk
    Device Name                                   Mali-G71
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 clvk
    Device Name                                   Mali-G71
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 clvk
    Device Name                                   Mali-G71

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.3.1
  ICD loader Profile                              OpenCL 3.0
```

clpeak output (screen may become UNRESPONSIVE)
```

Platform: clvk
  Device: Mali-G71
    Driver version  : 1.2 CLVK on Vulkan v1.1.131 driver 109051904 (Android)
    Compute units   : 1
    Clock frequency : 0 MHz

    Global memory bandwidth (GBPS)
      float   : 4.31
      float2  : 5.17
      float4  : 3.78
      float8  : 3.25
      float16 : 2.03

    Single-precision compute (GFLOPS)
      float   : 21.22
      float2  : 21.26
      float4  : 21.15
      float8  : 21.17
      float16 : 19.97

    Half-precision compute (GFLOPS)
      half   : 21.22
      half2  : 41.53
      half4  : 41.45
      half8  : 21.08
      half16 : 19.83

    No double precision support! Skipped

    Integer compute (GIOPS)
      int   : 21.06
      int2  : 21.04
      int4  : 20.99
      int8  : 20.83
      int16 : 19.21

    Integer compute Fast 24bit (GIOPS)
      int   : 21.05
      int2  : 20.76
      int4  : 20.78
      int8  : 20.76
      int16 : 19.14

    Transfer bandwidth (GBPS)
      enqueueWriteBuffer              : 3.05
      enqueueReadBuffer               : 0.46
      enqueueWriteBuffer non-blocking : 3.43
      enqueueReadBuffer non-blocking  : 0.48
      enqueueMapBuffer(for read)      : 678.21
        memcpy from mapped ptr        : 0.47
      enqueueUnmap(after write)       : 1898.41
        memcpy to mapped ptr          : 3.65

    Kernel launch latency : 139.29 us


Platform: ARM Platform
  Device: Mali-G71 r0p0
    Driver version  : 2.0 (Android)
    Compute units   : 2
    Clock frequency : 5 MHz

    Global memory bandwidth (GBPS)
      float   : 4.31
      float2  : 6.11
      float4  : 5.94
      float8  : 4.06
      float16 : 1.48

    Single-precision compute (GFLOPS)
      float   : 21.52
      float2  : 21.50
      float4  : 21.46
      float8  : 21.40
      float16 : 20.31

    Half-precision compute (GFLOPS)
      half   : 21.52
      half2  : 42.78
      half4  : 42.65
      half8  : 42.42
      half16 : 42.06

    No double precision support! Skipped

    Integer compute (GIOPS)
      int   : 21.46
      int2  : 21.41
      int4  : 21.33
      int8  : 21.21
      int16 : 16.32

    Integer compute Fast 24bit (GIOPS)
      int   : 21.45
      int2  : 21.41
      int4  : 21.32
      int8  : 21.19
      int16 : 16.32

    Transfer bandwidth (GBPS)
      enqueueWriteBuffer              : 1.46
      enqueueReadBuffer               : 2.21
      enqueueWriteBuffer non-blocking : 1.46
      enqueueReadBuffer non-blocking  : 2.21
      enqueueMapBuffer(for read)      : 4.21
        memcpy from mapped ptr        : 2.91
      enqueueUnmap(after write)       : 4.25
        memcpy to mapped ptr          : 2.94

    Kernel launch latency : 258.16 us

```

**Comment by xeffyr** [comment]
> Have to do LD_LIBRARY_PATH=$PREFIX/lib:/vendor/lib64:/vendor/lib64/egl to detect vendor OpenCL lib

Compiling-in as DT_RUNPATH doesn't work?

**Comment by truboxl** [comment]
> Compiling-in as DT_RUNPATH doesn't work?
It works but you won't be able to use the OpenCL vendor libs in the device. I think `LD_LIBRARY_PATH` trick still applies here.

**Comment by truboxl** [comment]
> Compiling-in as DT_RUNPATH doesn't work?

Doesn't look like DT_RUNPATH (or even `dlopen()`) works for linking with anything inside /vendor/lib64
It is still the `(default)` namespace issue that block the linking
```
~ $ OCL_ICD_DEBUG=1 clinfo
ocl-icd(/home/builder/.termux-build/ocl-icd/src/ocl_icd_loader.c:213): _load_icd: error while dlopening the IDL: 'dlopen failed: library "/vendor/lib64/libOpenCL.so" needed or dlopened by "/data/data/com.termux/files/usr/lib/libOpenCL.so" is not accessible for the namespace "(default)"',
  => skipping ICD
ocl-icd(/home/builder/.termux-build/ocl-icd/src/ocl_icd_loader.c:285): _get_function_addr: Missing global symbol 'clIcdGetPlatformIDsKHR' in ICD, should be skipped
ocl-icd(/home/builder/.termux-build/ocl-icd/src/ocl_icd_loader.c:291): _get_function_addr: Missing function 'clIcdGetPlatformIDsKHR' in ICD, should be skipped
ocl-icd(/home/builder/.termux-build/ocl-icd/src/ocl_icd_loader.c:443): _find_and_check_platforms: Missing symbols in ICD, skipping it
ocl-icd(/home/builder/.termux-build/ocl-icd/src/ocl_icd_loader.c:285): _get_function_addr: Missing global symbol 'clGetExtensionFunctionAddress' in ICD, should be skipped
ocl-icd(/home/builder/.termux-build/ocl-icd/src/ocl_icd_loader.c:285): _get_function_addr: Missing global symbol 'clIcdGetPlatformIDsKHR' in ICD, should be skipped
ocl-icd(/home/builder/.termux-build/ocl-icd/src/ocl_icd_loader.c:443): _find_and_check_platforms: Missing symbols in ICD, skipping it
ocl-icd(/home/builder/.termux-build/ocl-icd/src/ocl_icd_loader.c:388): _sort_platforms: Nb platefroms: 0
Number of platforms                               0
```
I guess I am removing the `LDFLAGS+=" -Wl,-rpath=/vendor/lib64 -Wl,-rpath=/vendor/lib64/egl"` bits for ocl-icd

I don't think I want to patch in ocl-icd to manipulate `LD_LIBRARY_PATH` before `dlopen()` vendor OpenCL libs

But the good news is clvk don't need to manipulate `LD_LIBRARY_PATH` and should work out of the box on most devices as long as there's system libvulkan.so and Android 9+

**Review by xeffyr — APPROVED** [review]

**Pull request merged**
