### PR TITLE
zip: always assume large file support

### LINKED ISSUE #5504: Zip is not compiled with ZIP64 support
**Problem description**
In order to handle input files or zip files of more than 2^32 bytes in size, zip needs to use an extension called ZIP64....but this is optional, and apparently the zip in Termux doesn't have it enabled.

The result is that very large zip files created with the zip in Termux are silently corrupted.

Other zip-related tools on Termux, like unzip and p7zip, *do* seem to properly support ZIP64.

The case where I discovered this was about 15GB of files.

**Steps to reproduce**
1. Install the Termux "zip" and "unzip" packages (the latter for testing)
2. Make or acquire a set of files greater than 4GB in size, BIGFILES
2. Use the zip program to put them in a zip file:  `zip zipfile.zip BIGFILES`
3. Try to examine that zip file using unzip tools (which support ZIP64):
```
       zipinfo zipfile.zip
       unzip -l zipfile.zip
```

Notice that the commands in step (4) emit error messages saying that the zip file is corrupt, and that they are attempting to recover.

**Expected behavior**
The commands in step (4) should give info without complaint.

A proper zip file using ZIP64 can be created for comparison, using the "7z" command from the "p7zip" package, like: `7z a -tzip zipfile2.zip BIGFILES`

**Additional information**
```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
apt/stable 1.4.9-28 aarch64 [upgradable from: 1.4.9-27]
bash/stable 5.0.17-2 aarch64 [upgradable from: 5.0.17]
bzip2/stable 1.0.8-6 aarch64 [upgradable from: 1.0.8-5]
ca-certificates/stable 20200626 all [upgradable from: 20200101]
command-not-found/stable 1.54 aarch64 [upgradable from: 1.52]
coreutils/stable 8.32-2 aarch64 [upgradable from: 8.32-1]
curl/stable 7.71.0-1 aarch64 [upgradable from: 7.70.0-1]
dash/stable 0.5.11-3 aarch64 [upgradable from: 0.5.11]
diffutils/stable 3.7-3 aarch64 [upgradable from: 3.7-2]
dos2unix/stable 7.4.1-1 aarch64 [upgradable from: 7.4.1]
dpkg/stable 1.20.4-4 aarch64 [upgradable from: 1.20.0-3]
ed/stable 1.16-1 aarch64 [upgradable from: 1.16]
findutils/stable 4.7.0-2 aarch64 [upgradable from: 4.7.0]
gawk/stable 5.1.0-1 aarch64 [upgradable from: 5.1.0]
grep/stable 3.4-1 aarch64 [upgradable from: 3.4]
gzip/stable 1.10-4 aarch64 [upgradable from: 1.10-3]
inetutils/stable 1.9.4-10 aarch64 [upgradable from: 1.9.4-9]
libandroid-glob/stable 0.6-2 aarch64 [upgradable from: 0.6]
libbz2/stable 1.0.8-6 aarch64 [upgradable from: 1.0.8-5]
libcrypt/stable 0.2-3 aarch64 [upgradable from: 0.2-2]
libcurl/stable 7.71.0-1 aarch64 [upgradable from: 7.70.0-1]
libgcrypt/stable 1.8.5-4 aarch64 [upgradable from: 1.8.5-1]
libgmp/stable 6.2.0-1 aarch64 [upgradable from: 6.2.0]
libmpfr/stable 4.0.2-3 aarch64 [upgradable from: 4.0.2-2]
libnghttp2/stable 1.41.0-1 aarch64 [upgradable from: 1.41.0]
libssh2/stable 1.9.0-2 aarch64 [upgradable from: 1.9.0-1]
libtirpc/stable 1.2.6-1 aarch64 [upgradable from: 1.2.6]
nano/stable 4.9.3-4 aarch64 [upgradable from: 4.9.3-3]
ncurses/stable 6.2.20200222-1 aarch64 [upgradable from: 6.2.20200222]
openssl/stable 1.1.1g-4 aarch64 [upgradable from: 1.1.1g-2]
pcre/stable 8.44-1 aarch64 [upgradable from: 8.44]
readline/stable 8.0.4-1 aarch64 [upgradable from: 8.0.4]
sed/stable 4.8-1 aarch64 [upgradable from: 4.8]
tar/stable 1.32-6 aarch64 [upgradable from: 1.32-5]
termux-licenses/stable 2.0-1 all [upgradable from: 1.0]
termux-tools/stable 0.83-1 all [upgradable from: 0.81-3]
unzip/stable 6.0-7 aarch64 [upgradable from: 6.0-5]
util-linux/stable 2.35.2-1 aarch64 [upgradable from: 2.35.2]
zlib/stable 1.2.11-5 aarch64 [upgradable from: 1.2.11-4]
Android version:
7.0
Kernel build information:
Linux localhost 3.18.35+ #1 SMP PREEMPT Fri Mar 22 16:46:06 CST 2019 aarch64 Android
Device manufacturer:
Sony
Device model:
F3113
```

### PR DESCRIPTION
**Pull request by landfillbaby**
fixes #5504

### CODE REVIEW

**Comment by landfillbaby** [comment]
ok yeah could clean up the pre-existing build warnings but minimal diff is better i guess

**Comment by landfillbaby** [comment]
https://github.com/termux/termux-packages/pull/5508/checks#step:4:448
the underlying problem seems to be that github is cross-compiling everything

**Comment by landfillbaby** [comment]
still, i confirmed that the build works and has zip64 support so i guess the underlying stuff doesn't matter

**Comment by landfillbaby** [comment]
ok i actually changed the problem parts of the makefile now. please merge

**Comment by Grimler91** [comment]
Thanks!

>  other packages might have configure files like this too, that don't account for cross-compiling

Yeah, we have quite a few configure patches to fix tests that don't work when cross-compiling

**Pull request merged**
