### PR TITLE
[Add Package] edbrowse 3.8.0

### PR DESCRIPTION
**Pull request by jeevatattva**
Closes https://github.com/termux/termux-packages/issues/7607.

### CODE REVIEW

**Comment by jeevatattva** [comment]
[1092  `aarch64-linux-android-clang main.o buffers.o sendmail.o fetchmail.o html.o format.o plugin.o ebrc.o messages.o stringfile.o html-tidy.o decorate.o msg-strings.o http.o isup.o css.o startwindow.o dbstubs.o jseng-quick.o -L/data/data/com.termux/files/usr/lib/quickjs -lquickjs -ldl -latomic -s -L/data/data/com.termux/files/usr/lib -lpcre2-8 -L/data/data/com.termux/files/usr/lib -lcurl -lreadline -L/data/data/com.termux/files/usr/lib -ltidy  -landroid-glob -lm  -o edbrowse`](https://github.com/termux/termux-packages/pull/7697/checks#step:3:1092)

[1093  `/home/builder/.termux-build/_cache/android-r21d-api-24-v5/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: error: cannot find -lquickjs`](https://github.com/termux/termux-packages/pull/7697/checks#step:3:1092)

Strange, `-lquickjs` is available at `-L/data/data/com.termux/files/usr/lib/quickjs` in my local build environment.

**Comment by xeffyr** [comment]
Static libraries subpackages are automatically generated and you can only disable them. They contain only `.a` files and intended only to reduce size of the primary deb file.

**Comment by xeffyr** [comment]
One note: static library dependencies should be specified in `TERMUX_PKG_BUILD_DEPENDS` because they are not needed during runtime because library data is compiled into binary.

I have updated the build.sh on my own, hopefully `edbrowse` doesn't require interpreter utility to be present in PATH. Otherwise `quickjs` package should be added (as runtime dep) in addition to specified `quickjs-static`.

**Comment by jeevatattva** [comment]
>static library dependencies should be specified in TERMUX_PKG_BUILD_DEPENDS 

I was wondering about that, adding build dependencies. I am little familiar with `brew` package manager. 

>hopefully edbrowse doesn't require interpreter utility to be present in PATH.

Yes, I have checked `edbrowse` package's executable - `edbrowse`, runs fine without the `quickjs`'s executable `qjs`.

**Pull request merged**
