### PR TITLE
Add package : crunch

### PR DESCRIPTION
**Pull request by Auxilus**

### CODE REVIEW

**Comment by stephengroat** [comment]
any reason not to use the https://downloads.sourceforge.net/project/crunch-wordlist/crunch-wordlist/crunch-3.6.tgz source?

**Comment by Grimler91** [comment]
As @stephengroat said, please use the original url and add changes you had to do as patches.

**Comment by Auxilus** [comment]
Done

**Comment by xeffyr** [comment]
Implemented in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install crunch
```

**Comment by Auxilus** [comment]
Thanks!

**Comment by Auxilus** [comment]
Thanks!

**Pull request closed without merging**
