### PR TITLE
add(main): new package oidn

### PR DESCRIPTION
**Pull request by T-Dynamos**
#11674

### CODE REVIEW

**Comment by 2096779623** [comment]
https://github.com/OpenImageDenoise/oidn/#prerequisites

**Comment by T-Dynamos** [comment]
> https://github.com/OpenImageDenoise/oidn/#prerequisites




https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openimagedenoise-git#n13

**Comment by 2096779623** [comment]
> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openimagedenoise-git#n13

Screenshot_20220902-220717_1

Try to follow the steps in README.MD :) , AUR is just for reference.

**Comment by T-Dynamos** [comment]
> > https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openimagedenoise-git#n13
> 
> Screenshot_20220902-220717_1
> 
> Try to follow the steps in README.MD :) , AUR is just for reference.

Never mind , I am noob. Proceeding to add [ispc](https://github.com/ispc/ispc)

**Comment by 2096779623** [comment]
> Never mind , I am noob. Proceeding to add [ispc](https://github.com/ispc/ispc)

I am noob too.

**Comment by T-Dynamos** [comment]
@2096779623

Now as I see in ispc, there are no build instructions. In aur https://github.com/archlinux/svntogit-community/blob/8f4a3c04aff477dd5b3c46dc55495dfccd13660d/trunk/PKGBUILD#L11 `spirv-llvm-translator` is mentioned but in fedorda its no. Also this wiki link is wrong https://src.fedoraproject.org/rpms/ispc/blob/rawhide/f/ispc.spec#_31 here

**Comment by 2096779623** [comment]
```bash
-- Found LLVM LLVM_14_0
-- LLVM_CONFIG_EXECUTABLE: /data/data/com.termux/files/usr/bin/llvm-config
-- CLANG_EXECUTABLE: /data/data/com.termux/files/usr/bin/clang
-- CLANGPP_EXECUTABLE: /data/data/com.termux/files/usr/bin/clang++
-- LLVM_DIS_EXECUTABLE: /data/data/com.termux/files/usr/bin/llvm-dis
-- LLVM_AS_EXECUTABLE: /data/data/com.termux/files/usr/bin/llvm-as
-- FILE_CHECK_EXECUTABLE: /data/data/com.termux/files/usr/bin/FileCheck
-- Detected LLVM version: 14.0.6
CMake Warning at cmake/FindLLVM.cmake:134 (message):
  LLVM was built without assertions enabled (-DLLVM_ENABLE_ASSERTIONS=OFF).
  This disables dumps, which are required for ISPC to be fully functional.
Call Stack (most recent call first):
  CMakeLists.txt:214 (include)


-- GIT_BINARY: /data/data/com.termux/files/usr/bin/git
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- M4 macro processor: /data/data/com.termux/files/usr/bin/m4
-- ISPC will be built with support of linux for arm
-- Enabling target: linux / armv7
-- Enabling target: linux / aarch64
-- ISPC Runtime will be built with support of OpenMP tasking model on CPU
CMake Error at /data/data/com.termux/files/usr/share/cmake-3.24/Modules/FindOpenMP.cmake:185 (file):
  file attempted to write a file:
  /data/data/com.termux/files/home/ispc-1.18.0/CMakeFiles/FindOpenMP/OpenMPTryFlag.c
  into a source directory.
Call Stack (most recent call first):
  /data/data/com.termux/files/usr/share/cmake-3.24/Modules/FindOpenMP.cmake:201 (_OPENMP_WRITE_SOURCE_FILE)
  /data/data/com.termux/files/usr/share/cmake-3.24/Modules/FindOpenMP.cmake:462 (_OPENMP_GET_FLAGS)
  ispcrt/CMakeLists.txt:78 (find_package)
-- Configuring incomplete, errors occurred!
```

[CMakeOutput.log](https://github.com/termux/termux-packages/files/9481743/CMakeOutput.log)

**Comment by T-Dynamos** [comment]
Adding Openmp https://github.com/archlinux/svntogit-packages/blob/packages/openmp/trunk/PKGBUILD should be the solution ( it was a optional dep so it could have been excluded using some cmake option)

**Comment by licy183** [comment]
`oidn` supports 64-bit platforms only (https://github.com/OpenImageDenoise/oidn/#prerequisites) and won't work on Linux/ARM64 (https://github.com/OpenImageDenoise/oidn/issues/125#issuecomment-916479769). Is it really necessary to add it?

**Comment by T-Dynamos** [comment]
Thanks @licy183!

**Comment by T-Dynamos** [comment]
But does that means that blender will only work for x64?

(Blender works on rpi and its also in raspbian repo)

**Comment by licy183** [comment]
> But does that means that blender will only work for x64?
> 
> (Blender works on rpi and its also in raspbian repo)

I think `oidn` is an optional dependency of `blender`. See https://developer.blender.org/D10958.

**Comment by T-Dynamos** [comment]
What are the deps remaining to be built for blender?

**Comment by licy183** [comment]
> What are the deps remaining to be built for blender?

I have no idea, but you could refer the raspbian repo.

**Comment by T-Dynamos** [comment]
This is also ready to be merged

**Pull request merged**
