### PR TITLE
fix(main/aalib): update patches to match Arch Linux

### PR DESCRIPTION
**Pull request by robertkirkman**
Fixes "`error: incomplete definition of type 'struct _win_st'`" during
build.

Progress on https://github.com/termux/termux-packages/issues/21130

Copied and pasted from https://gitlab.archlinux.org/archlinux/packaging/packages/aalib/-/commit/05e22fdc66114a51ac0a6ff07f3c156356439c63

`0005-aalib-m4.patch`: Fix --with-aalib-prefix argument

`0006-aalib-c99.patch`: Fix builtin-declaration-mismatch compiler warnings

`0007-aalib-free-offset-pointer.patch`: Fix free-nonheap-object compiler warning

`0008-aalib-key-down-OOB.patch`: Fix aggressive-loop-optimizations compiler warning

`0009-aalib-aalinuxkbd-return.patch`: Fix 'return' with no value compiler warning

`0010-aalib-opaque-ncurses-fix.patch`: Fix build for ncurses built with opaque-curses option

`0011-aalib-fix-aarender.patch`: Fix rendering with custom aspect ratio

`0012-aalib-mouse.patch`: Fix typo for KEY_MOUSE condition

### CODE REVIEW

**Review by TomJo2000 — APPROVED** [review]
LGTM

Would this necessitate rebuilding `aalib`'s reverse dependencies against the new revision?

**Comment by robertkirkman** [comment]
I do not believe so, because, 
1. there is no use of the static library, only the shared library
2. no function signatures in the library are changed, only function definitions
3. the names of the files inside the package are not changed

I am pretty sure those are the three cases where rebuilding reverse dependencies is usually required, but if there are additional situations where it is needed in this repo, please let me know.

**Comment by robertkirkman** [comment]
Yes, it is, but I accidentally clicked that update button, that is probably wrong hold on

**Comment by robertkirkman** [comment]
Ok it is ready now. I still see this on my screen, but I don't see a merge commit anywhere now so I don't know why it says that, I assume it is a github bug. Is there a way it can somehow flag as a "merge commit" when no files outside the aalib folder are shown as modified in the commit?

image

**Comment by TomJo2000** [comment]
> Ok it is ready now. I still see this on my screen, but I don't see a merge commit anywhere now so I don't know why it says that, I assume it is a github bug. Is there a way it can somehow flag as a "merge commit" when no files outside the aalib folder are shown as modified in the commit?
> 
> image
> 
> edit: never mind I think it says that on every open PR in this repo from anyone.

I think it defaults to Merge by merge commit.
We disabled that on this repo because it causes clutter in the Git history.

Squash and merge and rebase and merge do not do that.

**Pull request merged**
