### PR TITLE
bump(main/wasmedge): 0.14.0

### LINKED ISSUE #20304: Auto update failing for wasmedge
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [wasmedge](https://github.com/termux/termux-packages/blob/4043a428f727a15d5f44de592aca790973238490/packages/wasmedge) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating wasmedge [Current version: 0.13.5]
INFO: package being updated to 0.14.0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 40957    0 40957    0     0   103k      0 --:--:-- --:--:-- --:--:--  103k
100 3569k    0 3569k    0     0  5552k      0 --:--:-- --:--:-- --:--:-- 13.4M

You are about to commit these changes:

--------------------
diff --git a/packages/wasmedge/build.sh b/packages/wasmedge/build.sh
index 0bc56a78f..1f618cf91 100644
--- a/packages/wasmedge/build.sh
+++ b/packages/wasmedge/build.sh
@@ -3,9 +3,9 @@ TERMUX_PKG_DESCRIPTION="A lightweight, high-performance, and extensible WebAssem
 TERMUX_PKG_LICENSE="Apache-2.0"
 TERMUX_PKG_LICENSE_FILE="LICENSE, LICENSE.spdx"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="0.13.5"
+TERMUX_PKG_VERSION="0.14.0"
 TERMUX_PKG_SRCURL=https://github.com/WasmEdge/WasmEdge/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=588b8933a89f75c3ee5d4b92fe9d65294ae86fd48a95d2d4ac1a93ee3c5e1d75
+TERMUX_PKG_SHA256=27ef0ffa399fbaf44fb43733ea4ae4a4c1d9836a175269924ffd7e3d258d3567
 TERMUX_PKG_DEPENDS="libc++"
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
--------------------

bump(main/wasmedge): 0.14.0

Not committing to Git!

INFO: Trying to build package.
INFO: Package wasmedge exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building wasmedge for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  29452      0 --:--:-- --:--:-- --:--:-- 29448
100 13134  100 13134    0     0  29445      0 --:--:-- --:--:-- --:--:-- 29448
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2245      0 --:--:-- --:--:-- --:--:--  2251
gpg: Signature made Thu 23 May 2024 06:20:55 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/main/binary-aarch64/Packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  1 1580k    1 30689    0     0  56144      0  0:00:28 --:--:--  0:00:28 56104
100 1580k  100 1580k    0     0  1717k      0 --:--:-- --:--:-- --:--:-- 1716k
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  36665      0 --:--:-- --:--:-- --:--:-- 36694
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2327      0 --:--:-- --:--:-- --:--:--  2326
gpg: Signature made Sat 18 May 2024 12:27:16 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  35515      0 --:--:-- --:--:-- --:--:-- 35555
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2315      0 --:--:-- --:--:-- --:--:--  2313
100   833  100   833    0     0   2314      0 --:--:-- --:--:-- --:--:--  2313
gpg: Signature made Tue 21 May 2024 11:05:56 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency libc++@26b if necessary...
Found libc++ in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libc++ to /home/builder/.termux-build/_cache-aarch64...
Downloading https://github.com/WasmEdge/WasmEdge/archive/refs/tags/0.14.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 2992k    0 2992k    0     0  8458k      0 --:--:-- --:--:-- --:--:-- 8458k
100 3569k    0 3569k    0     0  8272k      0 --:--:-- --:--:-- --:--:-- 7501k
Applying patch: cmake-Helper.cmake.patch
1 out of 1 hunk FAILED -- saving rejects to file cmake/Helper.cmake.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-05-23 18:47:36 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/9212758220">9212758220</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by tqfx**
Close #20304

### CODE REVIEW

**Comment by tqfx** [comment]
How about this patch?

```diff
diff --git a/lib/loader/aot_section.cpp b/lib/loader/aot_section.cpp
index bc09eb4..ac1339d 100644
--- a/lib/loader/aot_section.cpp
+++ b/lib/loader/aot_section.cpp
@@ -7,8 +7,13 @@
 
 #if WASMEDGE_OS_LINUX || WASMEDGE_OS_MACOS
 extern "C" {
+#ifdef __arm__
+void __register_frame(void *) {}
+void __deregister_frame(void *) {}
+#else
 extern void __register_frame(void *);
 extern void __deregister_frame(void *);
+#endif
 }
 #endif
 
```

**Comment by truboxl** [comment]
> How about this patch?
> 
> ```diff
> diff --git a/lib/loader/aot_section.cpp b/lib/loader/aot_section.cpp
> index bc09eb4..ac1339d 100644
> --- a/lib/loader/aot_section.cpp
> +++ b/lib/loader/aot_section.cpp
> @@ -7,8 +7,13 @@
>  
>  #if WASMEDGE_OS_LINUX || WASMEDGE_OS_MACOS
>  extern "C" {
> +#ifdef __arm__
> +void __register_frame(void *) {}
> +void __deregister_frame(void *) {}
> +#else
>  extern void __register_frame(void *);
>  extern void __deregister_frame(void *);
> +#endif
>  }
>  #endif
>  
> ```
Looks good to me

**Comment by tqfx** [comment]
OK, I patched it.

**Review by truboxl — APPROVED** [review]
Thanks

**Pull request merged**
