### PR TITLE
fixed cmake not working on arm

### PR DESCRIPTION
**Pull request by its-pointless**
Make currently hangs when used by cmake on arm. This fixes it.

### CODE REVIEW

**Comment by fornwall** [comment]
What is happening here? Do make always hang on arm when used by cmake?

**Comment by its-pointless** [comment]
Yes. it always hangs when using cmake it seems.

**Comment by Grimler91** [comment]
This fixes https://github.com/termux/termux-packages/issues/2983

**Comment by fornwall** [comment]
@its-pointless Does `ac_cv_func_pselect=no` also fix this problem (from your comment in #2983)?

**Comment by its-pointless** [comment]
yes. 
Both of them do.

**Comment by fornwall** [comment]
@its-pointless Great, nice work!

I went with that solution in e47952a1b50927d3ff78bb1d0cf3533cc99f6066, and the updated make package is now available for installation at version `4.2.1-2`.

**Pull request closed without merging**
