### PR TITLE
Update docker image to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by fornwall**

### CODE REVIEW

**Comment by Grimler91** [comment]
Need some minor changes to setup-ubuntu.sh (doing a `build-all -a arm` now), but seems to mostly work fine. I'll push some changes when it is done

**Comment by Grimler91** [comment]
Seems python is a symlink to python3 in 20.04 instead of python2 as in previous version, most problems are related to that

**Comment by xeffyr** [comment]
> Seems python is a symlink to python3 in 20.04 instead of python2

`apt remove python-is-python3` should fix that.

**Comment by Grimler91** [comment]
> apt remove python-is-python3 should fix that.

It's not too much patching needed, probably good to use python3 where possible, IMO

**Comment by Grimler91** [comment]
Actually, the python-is-python3 is not installed (so /usr/bin/python does not exist). Installing python-is-python3 probably fixes most problems

**Pull request merged**
