### PR TITLE
Youtubedr : new package

### PR DESCRIPTION
**Pull request by kcubeterm**
It's golang library , standalone binary with no dependency , maybe a good youtube-dl alternative for just downloading youtube videos.

Related discussions on  reddit .
https://www.reddit.com/r/termux/comments/gfxl3j/looking_for_a_script_to_download_videos_from/?utm_medium=android_app&utm_source=share

### CODE REVIEW

**Comment by kcubeterm** [comment]
When i checked build log, it's show
>  go: downloading golang.org/x/net v0.0.0-20191209160850-c0dbc17a3553
> termux - build of 'youtube-dl' done

But real name is youtubedr,

**Comment by kcubeterm** [comment]
🤔 , i just reopen the PR, i didn't even change a single space .

**Comment by xeffyr** [comment]
Why package is named youtube-dl ?

**Comment by xeffyr** [comment]
And why duplicate submission of [shell2http](https://github.com/termux/termux-packages/commit/907d113faea48da6249977909ffbbdfffa2093f5) ?

Suggesting to use non-master branch for pull requests.

**Comment by kcubeterm** [comment]
> Why package is named youtube-dl ?

I don't know, in my local system, its shows youtubedr ,

**Comment by xeffyr** [comment]
```
~/termux-packages-kcubeterm/packages $ ls -ld youtube*
drwx------ 2 k-17 k-17 4096 мая  9 13:48 youtube-dl
```
what is in your fork.

**Comment by xeffyr** [comment]
Fixed.

**Pull request merged**
