### PR TITLE
qalc update to 2.2.1

### PR DESCRIPTION
**Pull request by Hax4us**

### CODE REVIEW

**Comment by Grimler91** [comment]
Looks like the parch needs to be re-implemented.

**Comment by Hax4us** [comment]
But why ? This line ` FILE *pipe = popen("gnuplot - 2>/dev/null", "w");` is already present in original code or are you saying about any other patch or thing ?

**Comment by Grimler91** [comment]
I haven't peeked into the source, just looked at travis output, which says that one of the patches failed.

**Comment by Hax4us** [comment]
Ohh okk :) No prob but i checked so I think it is ready for merge and what you think ?

**Comment by fornwall** [comment]
Nice work! The updated package is now available for installation.

**Pull request merged**
