### PR TITLE
termux-tools: deleting information in motd about installing repo for pacman format

### LINKED ISSUE #10919: [Pacman] Remove additional repositories in motd
### Problem description

motd from termux-tools installed with pacman shows additional repositories that cannot be installed with pacman, but they are already included in pacman mirrorlist

### What steps will reproduce the bug?

1. Open termux, you see this information in motd
2. Run pkg install root-repo or pkg install x11-repo

### What is the expected behavior?

It should not show these additional repositories in motd

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=pacman
TERMUX_APP_PID=16762
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=pacman
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# /data/data/com.termux/files/usr/etc/pacman.conf
[main]
Server = https://s3.amazonaws.com/termux-main.pacman/aarch64
[x11]
Server = https://s3.amazonaws.com/termux-x11.pacman/aarch64
[root]
Server = https://s3.amazonaws.com/termux-root.pacman/aarch64
Updatable packages:
All packages up to date
termux-tools version:
0.184
Android version:
11
Kernel build information:
Linux localhost 4.14.245-QuicksilveR-ginkgo-v2.5/a2dbd412 #1 SMP PREEMPT Mon Oct 4 02:10:01 CEST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8
```

### PR DESCRIPTION
**Pull request by Maxython**
Close #10919

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
This should be fine. But squash the commits before merging. Although, can also define `motd` file in `build.sh` dynamically.

**Comment by Maxython** [comment]
> Although, can also define motd file in build.sh dynamically.

Do you want to add a motd create action to build.sh?  
If so, then that sounds like a better solution.

**Comment by agnostic-apollo** [comment]
Yeah, do it. It's already being done like for `termux-login.sh`. Just create a variable first with the value and write to `motd` file. Don't append `root` and `x11` to variable for pacman.

**Comment by Maxython** [comment]
> It's already being done like for termux-login.sh.

Do you want to add this action to `termux-login.sh`?

**Comment by agnostic-apollo** [comment]
No. I said like: https://github.com/termux/termux-packages/blob/e8a85feee3e5dd8a5ecd56ddfa341aa361df6bbd/packages/termux-tools/build.sh#L77

```
motd="some value"
if [ "$TERMUX_PACKAGE_FORMAT" != "pacman" ]; then
    motd+="some non-pacman value"
fi
printf "%s" "$motd" > $TERMUX_PKG_BUILDER_DIR/motd
install -Dm600 $TERMUX_PKG_BUILDER_DIR/motd $TERMUX_PREFIX/etc/motd
```

**Comment by MrAdityaAlok** [comment]
Ahh..I was working on it locally, but thankyou!

**Comment by agnostic-apollo** [comment]
Yup, looks good to me. You can merge. Thanks.

**Comment by Maxython** [comment]
> You can merge

I can't ._.

**Comment by Grimler91** [comment]
Try now, I've added you to a "package maintainer team", which should have access to termux-packages (possibly you have another invitation in your email)

**Comment by Maxython** [comment]
> Try now, I've added you to a "package maintainer team", which should have access to termux-packages (possibly you have another invitation in your email)

Thank you, very much

**Pull request merged**
