### PR TITLE
addpkg(x11/qbittorrent-enhanced-edition{,-nox}): 4.6.5.10

### PR DESCRIPTION
**Pull request by zhongerxll**

### CODE REVIEW

**Comment by TomJo2000** [comment]
You're gonna need to elaborate in what way this package improves upon `qbittorrent` to warrant a separate package.

**Review by TomJo2000 — CHANGES_REQUESTED** [review]
Had a look at the source repositories readme.

> # Features:
> 1. Auto Ban Xunlei, QQ, Baidu, Xfplay, DLBT and Offline downloader
>
> 2. _Auto Ban Unknown Peer from China_ Option (Default: OFF)
>
> 3. Auto Update Public Trackers List (Default: OFF)
>
> 4. Auto Ban BitTorrent Media Player Peer Option (Default: OFF)
>
> 5. Peer whitelist/blacklist

That's gonna be a NACK from my end.
This package is a one to one fork of qBittorrent with some blocklists.

**Comment by zhongerxll** [comment]
> Had a look at the source repositories readme.
> 
> > # Features:
> > 
> > 1. Auto Ban Xunlei, QQ, Baidu, Xfplay, DLBT and Offline downloader
> > 2. _Auto Ban Unknown Peer from China_ Option (Default: OFF)
> > 3. Auto Update Public Trackers List (Default: OFF)
> > 4. Auto Ban BitTorrent Media Player Peer Option (Default: OFF)
> > 5. Peer whitelist/blacklist
> 
> That's gonna be a NACK from my end. This package is a one to one fork of qBittorrent with some blocklists.

Okay... I just wanted to use the 'Auto Update Public Trackers List' feature.

**Comment by TomJo2000** [comment]
You can build the package on your own development fork by enabling GitHub Actions on it,
or on your own computer/development environment using the package build container or local setup - if that is available to you as an option.
And then install the result `.DEB` package on your Termux from the local deb file using `pkg i ./name-of-package.deb`

But there is very little point to packaging a one to one, tracking fork of qBittorrent on Termux.

**Comment by zhongerxll** [comment]
> You can build the package on your own development fork by enabling GitHub Actions on it, or on your own computer/development environment using the package build container or local setup - if that is available to you as an option. And then install the result `.DEB` package on your Termux from the local deb file using `pkg i ./name-of-package.deb`
> 
> But there is very little point to packaging a one to one, tracking fork of qBittorrent on Termux.

Thanks.

**Pull request closed without merging**
