### PR TITLE
Added Github Pages

### PR DESCRIPTION
**Pull request by sdrausty**
Added Github Pages which can be linked to the main website, i.e. https://termux.com/termux-packages from a smartphone 📱in Termux 💪🙂 and created a pull request, all from device! Thank you!

### CODE REVIEW

**Comment by sdrausty** [comment]
For example https://sdrausty.github.io/buildAPKs/ is published in this fashion. The community repos https://wiki.termux.com/wiki/Package_Management#Community_Repositories I have just recently published, are published in a very similar fashion, e.g. https://github.com/sdrausty/au and https://sdrausty.github.io/repo/ respectively via https://pages.github.com

**Comment by TheDiamondYT1** [comment]
what is this?

**Comment by sdrausty** [comment]
@TheDiamondYT1 This is only a stub for https://termux.com/termux-packages via https://pages.github.com 

Hopefully, this will grow into additional documentation for termux-packages 

Please see https://github.com/sdrausty/buildAPKs/tree/master/docs which is published at https://sdrausty.github.io/buildAPKs/ or https://github.com/sdrausty/repo which is published at https://sdrausty.github.io/repo/ for working examples of documenting and publishing github reops. 

See https://pages.github.com for details.

**Comment by sdrausty** [comment]
Once published it will look like something like this https://sdrausty.github.io/buildAPKsFlashlights/ As said this is only a stub. Once content is added, it should complement https://github.com/termux/termux-packages well.

**Comment by sdrausty** [comment]
https://sdrausty.github.io/buildAPKsFlashlights/ was updated so it is no longer a stub as in the screenshot above.

**Comment by fornwall** [comment]
I think working with content on wiki.termux.com is a better alternative for now than using github pages - let me know if you disagree!

**Comment by Auxilus** [comment]
@fornwall check out https://github.com/termux/termux-app/pull/436

**Comment by sdrausty** [comment]
+fornwall if you don't give it a try, we won't find out which is better, or the best.

**Comment by sdrausty** [comment]
@fornwall if you don't give it a try, we won't find out which is better, or the best.

**Pull request closed without merging**
