### PR TITLE
mu-1.0

### PR DESCRIPTION
**Pull request by ayatakesi**
I create mu-1.0 repository.
It is depends libgmime2.

### CODE REVIEW

**Comment by ayatakesi** [comment]
oops...
What can I do?

**Comment by Grimler91** [comment]
Nothing to do before libgmime2 is merged.

**Comment by ayatakesi** [comment]
Ok, I will wait.

**Comment by fornwall** [comment]
A mu package (at version 1.2) has been added in 929665850b005f561a6d349668c6f8c754100357 - install it with `pkg install mu`.

Sorry for the delay here @ayatakesi !

**Comment by ayatakesi** [comment]
Thanks!

2019年6月3日(月) 午後7:25 Fredrik Fornwall <notifications@github.com>:

**Pull request closed without merging**
