### PR TITLE
termux-tools: add manpages

### PR DESCRIPTION
**Pull request by xeffyr**
Manpages for some commands in termux-tools. Solves #1580.

### CODE REVIEW

**Comment by sdrausty** [comment]
$ man termux-tools
man: No entry for termux-tools in the manual.

**Comment by xeffyr** [comment]
@sdrausty, why we need manual for 'termux-tools' ?
I have added manpages for ping, chsh, pkg, termux-open, other commands are too simple and they don't need manual. Also __dalvikvm__ command may be vary on different Android versions.

**Comment by sdrausty** [comment]
@xeffyr just suggesting `termux-tools` and other native Termux progs. Thanks for the good job. Hopefully this will be merged.

**Comment by xeffyr** [comment]
It seems unlikely to be merged. At least for now.

**Pull request closed without merging**
