### PR TITLE
Package Nix 1.12

### PR DESCRIPTION
**Pull request by puffnfresh**
I used the unreleased 1.12 because it removes the Perl dependencies. You should be able to use Nix with:

```bash
pkg install nix proot git
termux-chroot
git clone --depth 1 https://github.com/NixOS/nixpkgs.git
nix-build -A hello -I nixpkgs=$PWD/nixpkgs
```

It looks like nix-shell is a bit broken because of assumptions around ld-linux. Other things are probably broken.

### CODE REVIEW

**Comment by nico202** [comment]
Its quite late in the night but in going to try this right now, i'll update you asap

**Comment by nico202** [comment]
Just realized that i dont know how to buils it from mobile, will look tomorrow :(

  Thansk again and good night

**Comment by puffnfresh** [comment]
Thanks @nico202. I uploaded the 2 new packages here for aarch64:

https://brianmckenna.org/files/libseccomp_2.3.2_aarch64.deb

https://brianmckenna.org/files/nix_1.12~a27789_aarch64.deb

**Comment by edanaher** [comment]
I don't have much time to troubleshoot, but after building with run-docker.sh, copying the non-dev debs to my phone, and `dpkg -i *.deb`, running nix-build from the termux-chroot gave
```
bash-4.4$ nix-build -A hello -I nixpkgs=$PWD/nixpkgs
CANNOT LINK EXECUTABLE "nix-build": library "libc++_shared.so" not found
Aborted
```
Pixel phone (aarch64) with Android 7.1.2, July 5 security patches, what appears to be the latest termux from Google Play, just ran `apt-get update; apt-get upgrade`.

**Comment by nico202** [comment]
I compiled it for arm, installed. Chroot is extremely slow, so i mounted a directory to /nix, gave write permissions (777), cloned nixpkgs and run:

    nix-shell -p hello -I nixpkgs=./nixpkgs

But I get

    anonymous function at /data/data/com.termux/files/home/nixpkgs/pkgs/build-support/cc-wrapper/default.nix:8:1 called without required argument 'hostPlatform', at /data/data/com.termux/files/home/nixpkgs/pkgs/stdenv/native/default.nix:121:10              (use '--show-trace' to show detailed location information)

**Comment by puffnfresh** [comment]
@nico202 can you do a --show-trace for me? That line does seem like a bug in nixpkgs, I dunno how it's being triggered though.

**Comment by nico202** [comment]
~ nix-shell -p which --show-trace                             error: while evaluating the attribute 'buildInputs' of the derivation 'shell' at /data/data/com.termux/files/home/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:85:11:                           while evaluating the attribute 'src' of the derivation 'which-2.21' at /data/data/com.termux/files/home/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:85:11:                                     while evaluating the attribute 'buildInputs' of the derivation 'which-2.21.tar.gz' at /data/data/com.termux/files/home/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:85:11:                      while evaluating the attribute 'configureFlags' of the derivation 'curl-7.54.1' at /data/data/com.termux/files/home/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:85:11:                         while evaluating the attribute 'nativeBuildInputs' of the derivation 'openssl-1.0.2l' at /data/data/com.termux/files/home/nixpkgs/
pkgs/stdenv/generic/make-derivation.nix:85:11:                   while evaluating the attribute 'configureFlags' of the derivation 'perl-5.24.1' at /data/data/com.termux/files/home/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:85:11:                         while evaluating 'getOutput' at /data/data/com.termux/files/home/nixpkgs/lib/attrsets.nix:450:23, called from /data/data/com.termux/files/home/nixpkgs/pkgs/development/interpreters/perl/default.nix:20:13:                                                        while evaluating the attribute 'cc.libc' at /data/data/com.termux/files/home/nixpkgs/pkgs/stdenv/generic/default.nix:118:14:      while evaluating the attribute 'cc' at /data/data/com.termux/file
s/home/nixpkgs/pkgs/stdenv/generic/default.nix:118:14:           while evaluating the attribute 'cc' at /data/data/com.termux/file
s/home/nixpkgs/pkgs/stdenv/native/default.nix:121:5:             anonymous function at /data/data/com.termux/files/home/nixpkgs/pkgs/build-support/cc-wrapper/default.nix:8:1 called without required argument 'hostPlatform', at /data/data/com.termux/files/home/n
ixpkgs/pkgs/stdenv/native/default.nix:121:10

Il 5 agosto 2017 01:17:29 CEST, Brian McKenna <notifications@github.com> ha scritto:
>@nico202 can you do a --show-trace for me? That line does seem like a
>bug in nixpkgs, I dunno how it's being triggered though.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/termux/termux-packages/pull/1194#issuecomment-320372854

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by nico202** [comment]
I changed my phone in the meantime. Tried again right now and I'm able to compile and run hello, as in your example.

However, nix-env is not working:
```
$ nix-env -f . -i hello
installing 'hello-2.10'
building path(s) '/nix/store/nsqcmv9nak9cxvs9jfzi86idj622c8vi-user-environment'
CANNOT LINK EXECUTABLE "buildenv": library "libnixmain.so" not found
builder for '/nix/store/75vfs0004rl490pyz5d3pf9l8d041wgk-user-environment.drv' failed due to signal 6 (Aborted)
error: build of '/nix/store/75vfs0004rl490pyz5d3pf9l8d041wgk-user-environment.drv' failed
```

and nix-shell seems to work until:

```bash: error while loading shared libraries: /nix/store/dpi6dj4aiv5v5apx2my035vyy1hw0d44-glibc-2.26-115/lib/libc.so: invalid ELF header     ```

**Comment by bbigras** [comment]
Any progress?

**Comment by puffnfresh** [comment]
Nix 2.0 has been released very recently so I should try updating my work to that.

**Comment by arkanoid87** [comment]
I've successfully installed nix-env (Nix) 2.0.2 in termux into a proot environment using termux-chroot and a slightly modified install and startup script.

All you have to do is being careful with the env variables LD_PRELOAD and LD_LIBRARY_PATH. When are set termux binaries will work but not nix, and vice-versa.

I'll drop here a quick setup.

First download the install script `wget https://nixos.org/nix/install` and add the unset at the bottom just before `"$script" "$@"`

```
#!/bin/sh

# This script installs the Nix package manager on your system by
# downloading a binary distribution and running its installer script
# (which in turn creates and populates /nix).

{ # Prevent execution if this script was only partially downloaded
oops() {
    echo "$0:" "$@" >&2
    exit 1
}

tmpDir="$(mktemp -d -t nix-binary-tarball-unpack.XXXXXXXXXX || \
          oops "Can\'t create temporary directory for downloading the Nix binary tarball")"
cleanup() {
    rm -rf "$tmpDir"
}
trap cleanup EXIT INT QUIT TERM

require_util() {
    type "$1" > /dev/null 2>&1 || which "$1" > /dev/null 2>&1 ||
        oops "you do not have '$1' installed, which I need to $2"
}

case "$(uname -s).$(uname -m)" in
    Linux.x86_64) system=x86_64-linux; hash=d0c2492d7d8f824e3b1ace15a1a58f64a0a8faacc59936ebedfe18905d982d7c;;
    Linux.i?86) system=i686-linux; hash=01d5da9fad80c3282c5c7d9a7913b505c4c789940d021a1b21cb49df8ae081f8;;
    Linux.aarch64) system=aarch64-linux; hash=97397dad4c57031f2e5be37f49c8d610aa98620c971cf99eff8e4c8354d38615;;
    Darwin.x86_64) system=x86_64-darwin; hash=3c22d1591b4b39c69054839311cb024ea531d8a57019ec18ff60449a596962a0;;
    *) oops "sorry, there is no binary distribution of Nix for your platform";;
esac

url="https://nixos.org/releases/nix/nix-2.0.2/nix-2.0.2-$system.tar.bz2"

tarball="$tmpDir/$(basename "$tmpDir/nix-2.0.2-$system.tar.bz2")"

require_util curl "download the binary tarball"
require_util bzcat "decompress the binary tarball"
require_util tar "unpack the binary tarball"

echo "downloading Nix 2.0.2 binary tarball for $system from '$url' to '$tmpDir'..."
curl -L "$url" -o "$tarball" || oops "failed to download '$url'"

if type sha256sum > /dev/null 2>&1; then
    hash2="$(sha256sum -b "$tarball" | cut -c1-64)"
elif type shasum > /dev/null 2>&1; then
    hash2="$(shasum -a 256 -b "$tarball" | cut -c1-64)"
elif type openssl > /dev/null 2>&1; then
    hash2="$(openssl dgst -r -sha256 "$tarball" | cut -c1-64)"
else
    oops "cannot verify the SHA-256 hash of '$url'; you need one of 'shasum', 'sha256sum', or 'openssl'"
fi

if [ "$hash" != "$hash2" ]; then
    oops "SHA-256 hash mismatch in '$url'; expected $hash, got $hash2"
fi

unpack=$tmpDir/unpack
mkdir -p "$unpack"
< "$tarball" bzcat | tar -xf - -C "$unpack" || oops "failed to unpack '$url'"

script=$(echo "$unpack"/*/install)

[ -e "$script" ] || oops "installation script is missing from the binary tarball!"

unset LD_PRELOAD
unset LD_LIBRARY_PATH
"$script" "$@"

} # End of wrapping
```

then run `termux-chroot` and `mkdir /nix`. The folder will be in /nix in the prooted environment actually in ~/../nix in the host filesystem

you should now be able to execute the modified install script. You should get some missing grep warnings but actually everything goes well you should end up with the nix base installation in /nix.

Now, to start the nix environment, you have to apply the same unset trick to the launch script. First remove the line `if [ -e /home/.nix-profile/etc/profile.d/nix.sh ]; then . /home/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer` from ~/.bash_profile, then create the following scripts

~/start_nix_env
```
#!/bin/bash
echo "Starting termux-chroot environment"
termux-chroot bash ~/nix_prepare
echo "Quitting termux-chroot environment"
```
~/nix_prepare
```
#!/bin/bash
echo "Starting nix environment"
unset LD_LIBRARY_PATH LD_PRELOAD PATH
if [ -e /home/.nix-profile/etc/profile.d/nix.sh ]; then . /home/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
<add here your first nix env command, mine was nix-env -i bash. You can safely drop here 'bash -l' later>
echo "Quitting nix environment"
```

By starting ~/start_nix_env you should get a clean nix environment. Exit will drop you into the parent termux environment.

**Comment by arkanoid87** [comment]
I am doing some strace debug
https://gist.github.com/arkanoid87/25b5fc4e28184f2d5ee8415467c221f4#file-strace-txt-L3451

basically it stops reading LD_LIBRARY_PATH somewhere down the subprocess tree and when pid 22115 gets to line 3452 
`[pid 22115] execve("/data/data/com.termux/files/usr/bin/bash", ["bash", "-e", "/data/data/com.termux/files/nix/store/n0vlly8yxy41ff4y3s1dcxk55cs37d1b-unpack-channel.sh"], 0x790fc4f800 /* 20 vars */ <unfinished ...>`
It complains missing libandroid-support.so

I've tried loading with LD_PRELOAD but no success
```
-bash-4.4$ export LD_PRELOAD=/data/data/com.termux/files/usr/lib/libandroid-support.so
-bash-4.4$ ./nix-channel --update
unpacking channels...
CANNOT LINK EXECUTABLE "bash": library "libandroid-support.so" not found
builder for '/data/data/com.termux/files/nix/store/cn8dgx7hqx4g7gbfnxzc8w6ig7df9n2n-nixpkgs.drv' failed due to signal 6 (Aborted)
error: build of '/data/data/com.termux/files/nix/store/cn8dgx7hqx4g7gbfnxzc8w6ig7df9n2n-nixpkgs.drv' failed
error: program '/data/data/com.termux/files/nix/local/bin/nix-env' failed with exit code 100
-bash-4.4$
```

**Comment by fornwall** [comment]
We are closing old pull requests as a cleanup action.

If you are interested in picking this work up, please submit a new pull request with up to date content and we promise to be more responsive with the proposed change!

**Pull request closed without merging**
