### PR TITLE
bump(main/bc-gh): 7.0.0

### PR DESCRIPTION
**Pull request by gavinhoward**

### CODE REVIEW

**Comment by TomJo2000** [comment]
We should consider enabling `TERMUX_PKG_AUTO_UPDATE` on this package.

**Comment by gavinhoward** [comment]
Okay, I somehow managed to figure out GitHub tokens and checked; this package can be auto-updated, so I'll add a new PR trying to set that up.

**Comment by TomJo2000** [comment]
GitHub tokens shouldn't be necessary for that on your side.

**Comment by gavinhoward** [comment]
They're not necessary for auto updating, but they are necessary for testing if auto update can be enabled.

**Comment by TomJo2000** [comment]
Eh fair enough.
I should look into building better tooling for that so you can test it without needing to do that.

**Pull request merged**
