### PR TITLE
Add calc

### LINKED ISSUE #2417: Package request: calc
http://www.isthe.com/chongo/tech/comp/calc/

This is my favorite calculator for Linux. Uses readline for input.

### PR DESCRIPTION
**Pull request by karolba**
Resolves #2417

### CODE REVIEW

**Comment by Grimler91** [comment]
Are all these configure files really necessary, is it totally impossible to configure it for cross-compilation?

If they are necessary, please replace all /data/data/com.termux/files/usr with @TERMUX_PREFIX@ and either provide the files as a patch or sed it after you've copied the files.

Also, which error did you get when building with clang?

**Comment by karolba** [comment]
Hi, thanks for the reply!

Yeah, they sadly seem to be necessary as the only way to generate them seems to be to run autoconf-style utilities present in various .c files in the project that don't accept any arguments.

I have deleted `conf.h` from these headers as it's the only one that had contained `/data/data/com.termux/files/usr` in it and didn't depend on a .c utility, so no sed turns out to be necessary.

>Also, which error did you get when building with clang?

Welp, seems like the build goes fine with clang now, sorry for that. Deleting that line.

As for why the build is failing: travis doesn't seem to have the `col` and `less` utilities. I'm assuming this means that the Docker containers also don't have those tools, so I have switched to `more` instead of `less` and took `col.c` from FreeBSD which build.sh compiles. Is that approach fine with you?

**Comment by Grimler91** [comment]
> and took col.c from FreeBSD which build.sh compiles

Yeah should be fine.
Which arch did you configure it for? I assume that different arches, for example i686 and aarch64, will have different configure results and therefore need different sets of these config files.

**Comment by fornwall** [comment]
We are closing old pull requests as a cleanup action.

If you are interested in picking this work up, please submit a new pull request with up to date content and we promise to be more responsive with the proposed change!

**Pull request closed without merging**
