### PR TITLE
packages: bump keybase to v4.0.0

### PR DESCRIPTION
**Pull request by philips**
- bump to the latest release on Github
- drop kbfs package, kbfs moved to keybase/client

Warning! An environment variable needs to be set to make this work:

See https://github.com/keybase/client/issues/17203

### CODE REVIEW

**Comment by philips** [comment]
I would appreciate any advice on how to handle the kbfs package being deleted "elegantly".

**Comment by Grimler91** [comment]
Hi, you can use 
```bash
TERMUX_PKG_REPLACES="kbfs"
TERMUX_PKG_CONFLICTS="kbfs"
```
To handle the transition gracefully. Docs can be found here: https://www.debian.org/doc/debian-policy/ch-relationships.html#s-replaces

For the env var, best way to ensure it would be set would be to add the file `$PREFIX/etc/profile.d/keybase.sh` with the content
```bash
export KEYBASE_SECRET_STORE_FILE=1
```
Then only people with the package will have the var set.
You might want to echo a message in a postinst script that people need to open a new session before keybase will work then also

**Comment by philips** [comment]
thanks @Grimler91. pushed with those fixes and will test tomorrow.

**Comment by xeffyr** [comment]
> For the env var, best way to ensure it would be set would be to add the file $PREFIX/etc/profile.d/keybase.sh

It works only for bash and dash shells. For zsh/fish variable still not set.

This patch works better: 
[mkdefault-secret-store-file.patch.txt](https://github.com/termux/termux-packages/files/3168928/force-secret-store-file.patch.txt)

```diff
diff -uNr client-4.0.0/go/libkb/env.go client-4.0.0.mod/go/libkb/env.go
--- client-4.0.0/go/libkb/env.go	2019-05-07 22:35:07.000000000 +0300
+++ client-4.0.0.mod/go/libkb/env.go	2019-05-11 13:01:47.359107174 +0300
@@ -1784,7 +1784,7 @@
 func (e *Env) ForceSecretStoreFile() bool {
 	// By default use system-provided secret store (like MacOS Keychain), but
 	// allow users to fall back to file-based store for testing and debugging.
-	return e.GetBool(false,
+	return e.GetBool(true,
 		func() (bool, bool) { return e.getEnvBool("KEYBASE_SECRET_STORE_FILE") },
 		func() (bool, bool) { return e.GetConfig().GetForceSecretStoreFile() },
 	)
```
Just makes default value for KEYBASE_SECRET_STORE_FILE to be "true".

**Comment by philips** [comment]
Everything seems to work on my device. This is ready to merge IMHO @fornwall 

I don't know what the test failures are about but it looks unrelated.

@xeffyr I would prefer not to patch the code. Honestly it seems like something the keybase devs should enable fixing a different way. It is really easy to search the web for which environment variable to set to fix this so other shell users should be able to fix this quickly.

**Comment by fornwall** [comment]
@philips Nice work! The updated package is now available for installation.

Note that I have applied the patch from @xeffyr to change the default value of KEYBASE_SECRET_STORE_FILE (in commit c8dc7ae882feadfb2931399eaf3070cada8939e4), as it simplifies things, I hope you are ok with it?

**Comment by philips** [comment]
Totally cool with that, I just don't like maintaining patches. 😎

Thanks everyone for the review ♥️

**Pull request merged**
