### PR TITLE
emacs: update to 27.1

### PR DESCRIPTION
**Pull request by Grimler91**
Updated patches for 27. I have played around and tried to build a dumped emacs with the portable dumper, but so far not succeeded (might need a postinst script to do the dumping on device)

### CODE REVIEW

**Comment by snogglethorpe** [comment]
What problems do you have dumping?

I built Emacs 27 in Termux on my Chromebook, and it dumped and runs great\*.  However this is an x86 (me) box, maybe other archs have issues?

\* The traditional Termux Emacs random crash issues are still present, but that's apparently orthogonal to dumping it not

**Comment by xeffyr** [comment]
> What problems do you have dumping?

```
/usr/bin/mkdir -p ../etc
rm -f bootstrap-emacs.pdmp
./temacs --batch  -l loadup --temacs=pbootstrap
/bin/bash: ./temacs: cannot execute binary file: Exec format error
make[1]: *** [Makefile:817: bootstrap-emacs.pdmp] Error 126
```

Cross-compiled binaries cannot be exec'ed on host.

**Comment by Grimler91** [comment]
> > What problems do you have dumping?
> 
> ```
> /usr/bin/mkdir -p ../etc
> rm -f bootstrap-emacs.pdmp
> ./temacs --batch  -l loadup --temacs=pbootstrap
> /bin/bash: ./temacs: cannot execute binary file: Exec format error
> make[1]: *** [Makefile:817: bootstrap-emacs.pdmp] Error 126
> ```
> 
> Cross-compiled binaries cannot be exec'ed on host.

And using the host built `$TERMUX_PKG_HOSTBUILD_DIR/src/temacs`  creates an emacs that doesn't work on device (due to different architectures I suppose)

**Comment by Grimler91** [comment]
Works now. Just need to verify that postinst dumping works on other arches than aarch64

**Pull request merged**
