### PR TITLE
Create bash-pac v1.2.1.sh

### PR DESCRIPTION
**Pull request by stuffbymax**
simple terminal game for termux
the bash-pac is clone of pacman that is writen in bash script.

### CODE REVIEW

**Comment by TomJo2000** [comment]
We do not package random pet projects or scripts that run fine without any packaging.
Also that is not how the build system works, at all.
Just placing your script into the packages directory does not turn it into a DEB package.
Hell let's yet the CI fail just for shits and giggles.

**Comment by stuffbymax** [comment]
Shit sorry

**Comment by TomJo2000** [comment]
I am baffled that we do not check if there is a `build.sh` when there is a change in the `packages/` directory, thanks for giving me another thing to add to the linter I guess?

Look, I'm sorry I didn't mean to go off on you.
I'm sure it's a fun game and you learned a lot writing the script.
But it doesn't meet our [packaging criteria](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by stuffbymax** [comment]
I don't even remember that I  pul requested

**Comment by TomJo2000** [comment]
Eh no worries.

**Comment by stuffbymax** [comment]
Thanks for your time

**Comment by TomJo2000** [comment]
Thank you for making me realize we don't actually check for the proper layout of new package builds.
Somehow it never occurred to me.

**Comment by stuffbymax** [comment]
even a master carpenter gets cut sometimes

**Pull request closed without merging**
