### PR TITLE
new package: dosbox-staging

### PR DESCRIPTION
**Pull request by leapofazzam123**

### CODE REVIEW

**Comment by leapofazzam123** [comment]
Did the CI just fail because an unrelated package failed to build?

**Comment by buttaface** [comment]
Yep, the CI tries to build anything new since the last trunk commit it recognizes in your branch. Rebase your branch to avoid this issue.

**Comment by leapofazzam123** [comment]
rebased my branch, does it look good?

**Comment by leapofazzam123** [comment]
dammit it still fails because of an unrelated package, fuck you macchina

**Pull request closed without merging**
