### PR TITLE
removed http and added https

### PR DESCRIPTION
**Pull request by HusniMuhammad**
http URL to secure https  URL

### CODE REVIEW

**Comment by twaik** [comment]
Use `[no ci]` to not trigger building.

**Comment by HusniMuhammad** [comment]
> Use `[no ci]` to not trigger building.

How to use that

**Comment by twaik** [comment]
That must be a part of commit message.

**Comment by HusniMuhammad** [comment]
> That must be a part of commit message.

How to add that message

**Comment by twaik** [comment]
That must be done when you are creating commit.

**Comment by HusniMuhammad** [comment]
> That must be done when you are creating commit.

Screenshot_20230927-161138


Sorry 😐, next time I will do that

**Comment by HusniMuhammad** [comment]
Screenshot_20230927-163422

Is this correct??

**Comment by twaik** [comment]
It is not necessary to change http to https. In the case it will be a problem we will do that.

**Comment by HusniMuhammad** [comment]
Why this message showing 
Screenshot_20230927-164014

**Comment by HusniMuhammad** [comment]
In that picture

Homepage link http://wvware.sourceforge.net/ is a permanent redirect to its HTTPS counterpart https://wvware.sourceforge.net/ and should be updated.

**Comment by twaik** [comment]
It is not critical.

**Comment by HusniMuhammad** [comment]
> It is not critical.

Still it's a problem though

**Comment by HusniMuhammad** [comment]
> It is not critical.

I think someone write a script to automatically going to https urls directly (not redirecting)

**Pull request closed without merging**
