### PR TITLE
github actions: don't free disk space on CI unless needed for large builds

### PR DESCRIPTION
**Pull request by buttaface**
See if this works.

### CODE REVIEW

**Comment by buttaface** [comment]
We are currently wasting 4-5 mins on every CI run clearing up disk space, when really only one package needs that much space, rust. The CI reports 39 GB of free space, which translates to 26 GB in our Docker container. This clearing of space appears to double that to 52 GB, but I think there is only one package that needs that.

@xeffyr, let me know what you think.

**Comment by thunder-coding** [comment]
I think the free disk step should run when compiling multiple large packages (when nodejs, nodejs-lts and dependencies are bumped)

**Comment by buttaface** [comment]
Do you think even those node packages combined need more than 26 GB of disk space?

**Comment by xeffyr** [comment]
If really 26 GB available for container, then it shouldn't be necessary always run this step.

**Comment by buttaface** [comment]
I ran it through the CI a couple times to check: here is where I got [those](https://github.com/termux/termux-packages/runs/2926939761?check_suite_focus=true#step:3:573) [numbers](https://github.com/termux/termux-packages/runs/2926804813?check_suite_focus=true#step:3:1356) from. Both are inside the Docker container, the first when we don't free up disk space.

**Pull request merged**
