### PR TITLE
nim: update to 1.6.4

### PR DESCRIPTION
**Pull request by zorro**

### CODE REVIEW

**Review by xtkoba — COMMENTED** [review]
I cannot assess the legitimacy of `openssl3.patch` patch. Are there any references such as an upstream issue or PR?

**Comment by zorro** [comment]
> I cannot assess the legitimacy of `openssl3.patch` patch. Are there any references such as an upstream issue or PR?

It's documented in the openssl documentation. SSL_get_peer_certificate has been renamed to SSL_get1_peer_certificate in openssl3

https://www.openssl.org/docs/man3.0/man3/SSL_get1_peer_certificate.html

**Comment by xtkoba** [comment]
According to the documentation, `SSL_get_peer_certificate` is just deprecated but not renamed, isn't it?

What about <a href="https://nim-lang.org/">the nim-lang upstream</a>?

**Comment by zorro** [comment]
> According to the documentation, `SSL_get_peer_certificate` is just deprecated but not renamed, isn't it?
> 
> What about [the nim-lang upstream](https://nim-lang.org/)?

The `openssl` documentation says deprecated. But when I built nim and nimble without patch nimble failed with error `SSL_get_peer_certificate not found`

**Comment by xtkoba** [comment]
Then `nim` should depend on `openssl-1.1` and link against it, rather than adapting to OpenSSL 3.0. That is what we normally do when a package is not compatible with OpenSSL 3.0.

As the issue is not Android specific (I believe), it should be reported upstream.

**Comment by zorro** [comment]
@xtkoba done

**Pull request merged**
