### PR TITLE
newpkg(main/janet): 1.37.1

### LINKED ISSUE #20567: [Package]: janet
### Why is it worth to add this package?

Janet is a functional and imperative programming language implemented in LISP.

### Home page URL

https://janet-lang.org

### Source code URL

https://github.com/janet-lang/janet

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

Janet also has a package manager called [jpm](https://github.com/janet-lang/jpm)

### PR DESCRIPTION
**Pull request by mbekkomo**
Closes #20567

### CODE REVIEW

**Comment by mbekkomo** [comment]
Waiting for janet-lang/janet#1524

**Comment by TGSMLM** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by sogaiu** [comment]
For reference, starting from [here](https://github.com/janet-lang/janet/pull/840#issuecomment-1236120893), there is some info on getting janet to build for termux.

It uses the Makefile approach though.

**Comment by TomJo2000** [comment]
Fixed the local rebuild issue.
The Host build directory needs to be cleaned out between builds.

See also:
https://github.com/termux/termux-packages/blob/f75b248724e95207b252bee516a115a78b80e473/packages/libtd/build.sh#L19-L22

<h1><em></em></h1> 

On a sidenote, the linter doesn't see tabs as trailing whitespace, so that should be fixed.

**Comment by TomJo2000** [comment]
Right, so is this ready for merge if repeatability is cleaned up?
Have you actually tested it on device?

**Comment by mbekkomo** [comment]
I have tested it, it runs perfectly.

**Pull request merged**
