### PR TITLE
rust: update to 1.43.1

### PR DESCRIPTION
**Pull request by coolreader18**

### CODE REVIEW

**Comment by coolreader18** [comment]
It looks like the issue is that the `libc` crate assumes that res_init will be linked as `__res_init` when I think termux's environment has it as just `res_init`. Does anyone think it would it fix the problem If I just added a patch to call `res_init()` instead of `__res_init()`?

**Comment by dram** [comment]
It seems interesting that when compiling following code under Termux, no link error is encountered:

```rust
fn main() {
    unsafe {
        libc::res_init();
    }
}
```

**Comment by r4v3n6101** [comment]
Looks like x86 doesn't have `__res_init` as in other cases but has `res_init`. I think there should be one more conditional annotation. Kinda that:
```
#[cfg_attr(
        all(target_os = "linux", target_arch = "x86"),
        link_name = "res_init"
)]
```

**Comment by r4v3n6101** [comment]
What about making patch of this line (removing 2 underscores): 
https://github.com/rust-lang/libc/blob/e74204347f05af76b702fd9abfbbe22d0c367339/src/unix/mod.rs#L1238

**Comment by dram** [comment]
How about remove all those lines https://github.com/rust-lang/rust/blob/a647c0cd68bdd0f15081019f0b21bc31ae23f072/src/libstd/sys/unix/net.rs#L390-L397 , as those code are only workaround for DNS cache problem under `target_env = "gnu"`, delete those lines should not affect both bootstrapping process and final artifacts for Android.

**Comment by r4v3n6101** [comment]
@dram doing this in #5404

**Comment by coolreader18** [comment]
Wait, that shouldn't even matter, `on_resolver_failure` only does something when `cfg(target_env = "gnu")` and that's not the case for android targets. Maybe something else in libstd is calling res_init?

**Comment by dram** [comment]
According to the error message, it failed when trying to link x86_64-unknown-linux-gnu binaries, so it may be relevant.

```
  = note: /usr/bin/ld: /home/builder/.termux-build/rust/build/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-4a5f12d71462636a.rlib(std-4a5f12d71462636a.std.esf88y2y-cgu.1.rcgu.o): undefined reference to symbol '__res_init@@GLIBC_2.2.5'
```

**Comment by coolreader18** [comment]
Yeah, I just realized -- it's erroring while it's trying to compile proc macro crates, e.g. binaries targeting the host target. Not sure why that's failing, though...

**Comment by coolreader18** [comment]
Hmm, but the host is set as `x86_64-linux-android`. Interesting.

**Comment by coolreader18** [comment]
I made an issue rust-lang/rust#73426 to ask about this.

**Comment by dram** [comment]
How about try to upgrade to 1.43.0 or 1.43.1, to figure out which version the problem is introduced.

**Comment by coolreader18** [comment]
Hmm. 1.43 works; do you want to just update to 1.43 for now and try to figure out what's up with 1.44 later?

**Comment by r4v3n6101** [comment]
Could you also try 1.43.1? Are there any major changes which can't be compatible with termux's builds?

**Comment by coolreader18** [comment]
Oh, this is 1.43.1.

**Comment by dram** [comment]
Although not latest, but I think firstly go to 1.43 is better than stay with 1.42.

BTW, may have a try without `packages/rust/res_init-symbol-name.patch`, I think that patch file is not necessary.

**Comment by coolreader18** [comment]
I've rebased and force-pushed; I'll open a new PR for 1.44

**Comment by coolreader18** [comment]
Can this be merged? Further work/ideas for fixing 1.44 will go in the other PR.

**Comment by wangjia184** [comment]
I am encountering this error : https://github.com/rust-embedded/cross/issues/444

Is that caused by this ?

**Pull request merged**
