### PR TITLE
fix(main/pypy3): Permission denied

### PR DESCRIPTION
**Pull request by 1q23lyc45**
fix issue #20809 

This fix is for pypy3, not the original pypy (2)

### CODE REVIEW

**Comment by 1q23lyc45** [comment]
What happened?

**Comment by TomJo2000** [comment]
As noted in #20966 pypy3 currently has unresolved build issues.

**Comment by 1q23lyc45** [comment]
It seems that the Docker container cannot be started.

It's also difficult for me to solve this dependency problem, especially since I'm not familiar with the Docker compilation environment. I thought it was cross compilation, but it wasn't as simple as I thought 😭😭😭.

One possibility is that the Termux-docker image has been updated to support DNS resolve, but build.sh has not been adapted accordingly. Finally, it resulted in incompatible dependencies and inability to compile properly.

**Comment by TomJo2000** [comment]
I'm sure @licy183 can go into some more detail but Pypy and Pypy3 are some of the more complex package builds we maintain.
From what I understand they don't support cross compilation so we need an additional docker layer with QEMU in order to compile them.

**Comment by TomJo2000** [comment]
*Should* be fixed by https://github.com/termux/termux-packages/commit/8ad78adb11b9a8970807b6563906d47f956e49f0

**Comment by licy183** [comment]
I'm trying to use python in Ubuntu to translate the pypy sources rather than the one in termux-docker. It works for pypy2 but not for pypy3.

**Comment by 1q23lyc45** [comment]
II changed the method of changing DNS and directly hardcoded Cloudflare DNS(1.1.1
1). I don't know if it can be solved?

**Comment by 1q23lyc45** [comment]
In your Docker environment, no matter how the DNS is changed, the domain name cannot be resolved. Is it due to the interception of the outbound port 53 or something else

**Comment by 1q23lyc45** [comment]
[9997-shutil-py.patch](https://github.com/user-attachments/files/16504307/9997-shutil-py.patch)

This is a patch to fix my issue.(setxattr bug)

**Comment by a1489632** [comment]
> I'm trying to use python in Ubuntu to translate the pypy sources rather than the one in termux-docker. It works for pypy2 but not for pypy3. I'm trying to find out why it doesn't work on pypy3, but I havn't made it so far.

Please try pypy3 (in Ubuntu) instead of (c)python.

**Comment by licy183** [comment]
> Please try pypy3 (in Ubuntu) instead of (c)python.

Not possible. pypy sources needs python2 to translate.

**Pull request closed without merging**
