### PR TITLE
libgc: update to 8.2.8

### PR DESCRIPTION
**Pull request by ivmai**

### CODE REVIEW

**Comment by Biswa96** [comment]
Would it be possible to enable auto update? CI can automatically update packages here.

**Comment by ivmai** [comment]
> Would it be possible to enable auto update? CI can automatically update packages here.

How to?

**Comment by TomJo2000** [comment]
Just adding `TERMUX_PKG_AUTO_UPDATE=true` should be enough.
For further questions you can reference:
https://github.com/termux/termux-packages/wiki/Auto-updating-packages
Or any other package builds with auto updates enabled.

**Comment by ivmai** [comment]
Based on the description and source code of autoupdate script, I don't see 2 thing to work correctly with libgc:
- there should be a semantic versions comparison so that to pickup only newly released version is OS greater than the current one
- experimental (alpha) releases should be ignored (in case of libgc an alpha release is identified by 0 micro version).

**Comment by TomJo2000** [comment]
The `termux_pkg_auto_update()` function.
The one for the `taplo` package looks like it ticks a couple of the boxes you mentioned above.
https://github.com/termux/termux-packages/blob/7de5407c8ea1e557901bac5f324cd0a3a8a583ff/packages/taplo/build.sh#L13-L36
It would probably be a good starting point.

**Comment by ivmai** [comment]
Okay, for now I've just set TERMUX_PKG_AUTO_UPDATE. Let's see how it goes on update.
Thank you!

**Review by TomJo2000 — APPROVED** [review]

**Comment by Biswa96** [comment]
> experimental (alpha) releases should be ignored (in case of libgc an alpha release is identified by 0 micro version).

According to https://semver.org/, "A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version."

With the above semver rule, we can use `TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"` to block alpha versions.

**Comment by ivmai** [comment]
> With the above semver rule, we can use TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+" to block alpha versions.

libgc uses a non-standard indication of an alpha release: micro version is equal to 0, e.g. 8.4.0.
I will add the proper regexp.
Thank you!

**Comment by TomJo2000** [comment]
> Some github actions jobs failed because of No space left on device.

It seems like it tried building all packages that were update between the previous and current rebase.
This can happen when you select `Update branch` (Update with merge commit) instead of `Rebase branch` (Update with rebase).
I saw it and applied a "update with rebase" to the PR.
You may need to use `git -c pull.rebase=true pull` to update your local branch.

**Comment by ivmai** [comment]
> You may need to use git -c pull.rebase=true pull to update your local branch.

Done

**Comment by ivmai** [comment]
I've added TERMUX_PKG_UPDATE_VERSION_REGEXP

**Review by TomJo2000 — APPROVED** [review]
LGTM

**Pull request merged**
