### PR TITLE
OpenCL: framework and POCL implementation

### PR DESCRIPTION
**Pull request by rnauber**
This PR adds olc-icd, which acts as a switch for multiple implementations of OpenCl. One of which is POCL, an open source llvm-based engine that should run nearly everywhere on the CPU(s). Furthermore there are two diagnostic tools:  clinfo and clpeak.
Please test this,
Richard

PS: On my device (aarch64) pocl segfaults on half-precision tests. So please consider this as an pre-alpha release for termux...

### CODE REVIEW

**Comment by kuburan** [comment]
required package already installed include hwloc. need help here, what am missing ?

-- ----------- -------------------------------- --------                 -- system libs libpocl will be linked to (LLVM_SYSLIBS):                 --                                                                       -- ----------- -------------------------------- --------
-- ******* Enabled features:                                             --                                                                       -- CLANG_SPIR: 0
-- ENABLE_ICD: 1
-- ENABLE_TCE: 0                                                         -- ENABLE_TCEMC: 0
-- ENABLE_HSA: OFF                                                       -- ENABLE_ASAN (address sanitizer): 0
-- INSTALL_OPENCL_HEADERS (Install our headers): 0
-- OCL_DRIVERS (Drivers built): basic pthreads                           -- OCL_TARGETS (Targets built): host
-- OCS_AVAILABLE: ON
-- SINGLE_LLVM_LIB: ON
-- TESTS_USE_ICD: 1
-- USE_VECMATHLIB: 1
-- Available testsuites: AMD;AMDSDK2.9;AMDSDK3.0;ASL;arrayfire;clBLAS;clFFT;CloverLeaf;Halide;IntelSVM;opencl-book-samples;OpenCV;Parboil;piglit;PyOpenCL;Rodinia;VexCL;ViennaCL
-- Enabled testsuites:
-- Disabled testsuites: AMD;AMDSDK2.9;AMDSDK3.0;ASL;arrayfire;clBLAS;clFFT;CloverLeaf;Halide;IntelSVM;opencl-book-samples;OpenCV;Parboil;piglit;PyOpenCL;Rodinia;VexCL;ViennaCL
-- Kernel caching: ON
-- Kernel library CPU variants: native
-- Kernel library distro build: 0
-- Use fake address space IDs: 0
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
C_LIBFILE_clangAST
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangAnalysis
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangBasic
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangCodeGen
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangDriver
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangEdit
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangFrontend
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangFrontendTool
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangLex
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangParse
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangRewrite
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangRewriteFrontend
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangSema
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangSerialization
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangStaticAnalyzerCheckers
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangStaticAnalyzerCore
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL
C_LIBFILE_clangStaticAnalyzerFrontend
    linked by target "pocl" in directory /data/data/com.termux/files/home/pocl-0.14/lib/CL

-- Configuring incomplete, errors occurred!
See also "/data/data/com.termux/files/home/pocl-0.14/CMakeFiles/CMakeOutput.log".
$

**Comment by rnauber** [comment]
Hi kuburan,
your are building pocl on your device, in contrast to using the cross-compiled version with "dpkg -i pocl...deb". This is fine, but pocl uses llvm and there are some pieces of that not yet packaged for termux. @fornwall should I try to prepare a PR that includes this?
@kuburan , did you also tried the pocl package?

Bye,
Richard

**Comment by kuburan** [comment]
so, my compiler is not yet supported to buiding pocl ? or i missing some header and libraries files.
should i build libclang-dev first to fix the problem ?

**Comment by vishalbiswas** [comment]
can you provide an arm package for testing? I'm currently away from my desk

**Comment by rnauber** [comment]
Sorry for my latency, I did not find the time to fix pocl for LLVM 5.0. 
Please try these patches, precompiled debs are here: https://github.com/rnauber/termux_packages_bin

Have fun, 
Richard

**Comment by kuburan** [comment]
i have segfaulf too.

screenshot_20171002-094042

**Comment by kuburan** [comment]
this is normal or not ?

$ clinfo
Number of platforms                               1
  Platform Name                                   Portable Computing Language
  Platform Vendor                                 The pocl project
  Platform Version                                OpenCL 1.2 pocl 0.15-pre, LLVM 5.0
  Platform Profile                                  FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             POCL

  Platform Name                                 Portable Computing Language
Number of devices                            1
  Device Name                                     pthread-AArch64 Processor rev 4 (aarch64)
  Device Vendor                                   Unknown x86
  Device Vendor ID                              0x6c636f70
  Device Version                                  OpenCL 1.2 pocl HSTR: pthread-aarch64--linux-android-cortex-a73
  Driver Version                                    0.15-pre
  Device OpenCL C Version                OpenCL C 1.2 pocl
  Device Type                                        CPU
  Device Available                                 Yes
  Device Profile                                       FULL_PROFILE
  Max compute units                             4
  Max clock frequency                           988MHz
  Device Partition                                    (core)
    Max number of sub-devices                 4
    Supported partition types                     equally, by counts
  Max work item dimensions                        3
  Max work item sizes                             4096x4096x4096
  Max work group size                             4096
  Compiler Available                                 Yes
  Linker Available                                       Yes
  Preferred work group size multiple              8
  Preferred / native vector sizes
    char                                                 1 / 1
    short                                                1 / 1
    int                                                     1 / 1
    long                                                  1 / 1
    half                                                    1 / 1        (n/a)
    float                                                   1 / 1
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                         No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                    No
    Round to infinity                                No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software                No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                        Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                   Yes
    Round to infinity                               Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software                 No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                           64, Little-Endian
  Global memory size                              1519125504 (1.415GiB)
  Error Correction support                       No
  Max memory allocation                         536870912 (512MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             2 bytes
  Alignment of base address                       16 bits (2 bytes)
  Global Memory cache type                        None
  Image support                                               Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            33554432 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             8192x8192 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                128
  Local memory type                               Global
  Local memory size                               8388608 (8MiB)
  Max constant buffer size                        8388608 (8MiB)
  Max number of constant args                     8
  Max size of kernel argument                     1024
  Queue properties
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_3d_image_writes cl_khr_fp64

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Portable Computing Language
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [POCL]
  clCreateContext(NULL, ...) [default]            Success [POCL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-AArch64 Processor rev 4 (aarch64)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-AArch64 Processor rev 4 (aarch64)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-AArch64 Processor rev 4 (aarch64)

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.10
  ICD loader Profile                              OpenCL 2.1
$

**Comment by rnauber** [comment]
@kuburan well, the clinfo looks good to me and the segfault is at least reproducible :)  
So any help fixing that nasty bug is appreciated!

**Comment by vishalbiswas** [comment]
arm? with dev packages

**Comment by rnauber** [comment]
@vishalbiswas  I added the binaries for arm to https://github.com/rnauber/termux_packages_bin 
... please test them!

**Comment by vishalbiswas** [comment]
@rnauber I successfully compiled hascat, but, am unable to run it. I always get `/data/data/com.termux/files/usr/bin/ld: cannot find /system/lib64/crtbegin_so.o: No such file or directory`
Your arm binaries may not be proper.

**Comment by rnauber** [comment]
@vishalbiswas could you please try the hashcat package at https://github.com/rnauber/termux_packages_bin ?

**Comment by vishalbiswas** [comment]
@rnauber you forgot arm

**Comment by kuburan** [comment]
@rnauber @vishalbiswas . i try install  hashcat binary from @rnauber branch, but cannot run in my phone 
(exec error) . and i compiled the older version (3.6.0). it work stable , but always failed to restore mode after checkpoint. maybe you can investigate this.

**Comment by kuburan** [comment]
$ hashcat --session test -m 3200 3200.hash ~/wordlist/rockyou.txt

hashcat (v3.6.0) starting...

OpenCL Platform #1: The pocl project
====================================
* Device #1: pthread-AArch64 Processor rev 4 (aarch64), 512/1448 MB allocatable, 4MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Watchdog: Temperature abort trigger disabled.
Watchdog: Temperature retain trigger disabled.

* Device #1: build_opts '-I /data/data/com.termux/files/usr/share/hashcat/OpenCL -D VENDOR_ID=64 -D CUDA_ARCH=0 -D VECT_SIZE=1 -D DEVICE_TYPE=2 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D DGST_R3=3 -D DGST_ELEM=6 -D KERN_TYPE=3200 -D _unroll -cl-std=CL1.2'

* Device #1: Kernel m03200.1482e451.kernel not found in cache! Building may take a while...
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/.cache/pocl/kcache/JF/KPDDFKMPFDNPDMOGABFOKDCHBGPJEDOAPOPGP/m03200_init/8-1-1/m03200_init.so.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `c_sbox0' which may bind externally can not be used when making a shared object; recompile with -fPIC

/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/.cache/pocl/kcache/JF/KPDDFKMPFDNPDMOGABFOKDCHBGPJEDOAPOPGP/m03200_init/8-1-1/m03200_init.so.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `c_sbox1' which may bind externally can not be used when making a shared object; recompile with -fPIC

* Device #1: Kernel amp_a0.1482e451.kernel not found in cache! Building may take a while...

Dictionary cache building /data/data/com.termux/files/home/wordlist/rockyou.txDictionary cache building /data/data/com.termux/files/home/wordlist/rockyou.txDictionary cache building /data/data/com.termux/files/home/wordlist/rockyou.txDictionary cache building /data/data/com.termux/files/home/wordlist/rockyou.txDictionary cache built:

* Filename..: /data/data/com.termux/files/home/wordlist/rockyou.txt
* Passwords.: 14344391
* Bytes.....: 139921497
* Keyspace..: 14343296
* Runtime...: 56 secs

- Device #1: autotuned kernel-accel to 2
- Device #1: autotuned kernel-loops to 1
[s]tatus [p]ause [r]esume [b]ypass [c]heckpoint [q]uit => c

Checkpoint enabled. Will quit at next restore-point update.
Session..........: test
Status...........: Aborted (Checkpoint)
Hash.Type........: bcrypt $2*$, Blowfish (Unix)
Hash.Target......: $2y$10$pJJw0ybbqkVLM.PG.7fkbOfR.ZUnQUwX8jXaMS6x4./N...XorE6.
Time.Started.....: Tue Nov  7 17:21:00 2017 (31 secs)
Time.Estimated...: Sat Dec 16 23:13:16 2017 (39 days, 5 hours)
Guess.Base.......: File (/data/data/com.termux/files/home/wordlist/rockyou.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.Dev.#1.....:        4 H/s (9.63ms)
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 192/14343296 (0.00%)
Rejected.........: 0/192 (0.00%)
Restore.Point....: 192/14343296 (0.00%)
Candidates.#1....: carolina -> november

Started: Tue Nov  7 17:18:06 2017
Stopped: Tue Nov  7 17:21:32 2017


$ hashcat --session test --restore

hashcat (v3.6.0) starting in restore mode...

Changing current working directory to '/data/data/com.termux/files/home/hash'

OpenCL Platform #1: The pocl project
====================================
* Device #1: pthread-AArch64 Processor rev 4 (aarch64), 512/1448 MB allocatable, 4MCU

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Watchdog: Temperature abort trigger disabled.
Watchdog: Temperature retain trigger disabled.

* Device #1: build_opts '-I /data/data/com.termux/files/usr/share/hashcat/OpenCL -D VENDOR_ID=64 -D CUDA_ARCH=0 -D VECT_SIZE=1 -D DEVICE_TYPE=2 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D DGST_R3=3 -D DGST_ELEM=6 -D KERN_TYPE=3200 -D _unroll -cl-std=CL1.2'
Segmentation fault
$

**Comment by kuburan** [comment]
run debuging.

(gdb) file /data/data/com.termux/files/usr/bin/hashcat
Reading symbols from /data/data/com.termux/files/usr/bin/hashcat...done.

(gdb) run --session test --restore
Starting program: /data/data/com.termux/files/usr/bin/hashcat --session test --restore
hashcat (v3.6.0) starting in restore mode...

Changing current working directory to '/data/data/com.termux/files/home/hash'

[New LWP 3493]
[New LWP 3494]

OpenCL Platform #1: The pocl project
====================================
* Device #1: pthread-AArch64 Processor rev 4 (aarch64), 512/1448 MB allocatable, 4MCU

[New LWP 3495]
Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
Rules: 1

Applicable optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt

Watchdog: Temperature abort trigger disabled.
Watchdog: Temperature retain trigger disabled.

* Device #1: build_opts '-I /data/data/com.termux/files/usr/share/hashcat/OpenCL -D VENDOR_ID=64 -D CUDA_ARCH=0 -D VECT_SIZE=1 -D DEVICE_TYPE=2 -D DGST_R0=0 -D DGST_R1=1 -D DGST_R2=2 -D DGST_R3=3 -D DGST_ELEM=6 -D KERN_TYPE=3200 -D _unroll -cl-std=CL1.2'

Thread 1 "hashcat" received signal SIGSEGV, Segmentation fault.
0x0000007fb21756b8 in llvm::Module::getNamedMetadata(llvm::Twine const&) const () from /data/data/com.termux/files/usr/lib/libLLVM-5.0.so
(gdb)

**Comment by Auxilus** [comment]
@kuburan Got hashcat working in my device too... but I get following warnings...

```
ATTENTION! Pure (unoptimized) OpenCL kernels selected.
This enables cracking passwords and salts > length 32 but for the price of drastical reduced performance.
If you want to switch to optimized OpenCL kernels, append -O to your commandline.  
Watchdog: Hardware monitoring interface not found on your system.                  Watchdog: Temperature abort trigger disabled.
Watchdog: Temperature retain trigger disabled.                                     
INFO: Removed 35 hashes found in potfile.                                          
* Device #1: build_opts '-I /data/data/com.termux/files/usr/share/hashcat/OpenCL -D VENDOR_ID=2147483648 -D CUDA_ARCH=0 -D AMD_ROCM=0 -D VECT_SIZE=1 -D DEVICE_TYPE=4 -D DGST_R0=0 -D DGST_R1=3 -D DGST_R2=2 -D DGST_R3=1 -D DGST_ELEM=4 -D KERN_TYPE=0 -D _unroll'
* Device #1: Kernel m00000_a1.e3f9f446.kernel not found in cache! Building may take a while...
```

**Comment by kuburan** [comment]
@Auxilus . i was told you the latest version (4.0.0)  always segfault in my phone. the older version (3.6.0) work stable but cannot restore.
when i run debuging . showed segfault in libLLVM. it hard to me to fix that segfault

**Comment by Auxilus** [comment]
i am not getting any segfaults with v4.0.0

**Comment by Auxilus** [comment]
I had to modify line 129 and 130 in src/Makefile

**Comment by kuburan** [comment]
can you try restore mode ? it segfault or not in the latest version?

**Comment by Auxilus** [comment]
how do  i run restore mode?

**Comment by kuburan** [comment]
example:
crack MD5
 $ hashcat --session testing -a 0 -m 0 your_password your_wordlist

before hashcat finish guessing hit "c" or "q"

and run

$ hashcat --session testing --restore

and see seqfault or not.

**Comment by Auxilus** [comment]
I didn't get any segfault, but.. 
```
[16:59] ~/w/hashcat-4.0.0 > hashcat --session testing --restore
hashcat (v4.0.0) starting in restore mode...

Restore file '/data/data/com.termux/files/home/.hashcat/sessions/testing.restore': No such file or directory

Started: Tue Nov  7 16:59:31 2017
Stopped: Tue Nov  7 16:59:31 2017
```

**Comment by kuburan** [comment]
yes, no such file or directory because hashcat is finished guessing , status is Cracked . not Checkpoint or Abort.

try to make some slower hash type. like Blowfish or TrueCrypt .

here the example 
https://hashcat.net/wiki/doku.php?id=example_hashes

**Comment by rnauber** [comment]
Hi, I have incorporated #1764 from @Auxilus into this PR, so please test hashcat and report your findings...

**Comment by Auxilus** [comment]
@rnauber I was able to use pocl for hashcat with the deb files you provided, It throws some warnings, and looks like it doesn't crack the hash eventually.

**Comment by rnauber** [comment]
@Auxilus what warnings? during install or execution?

You could adittionally try your native opencl:

``
echo /system/vendor/lib64/libOpenCL.so >  $PREFIX/etc/OpenCL/vendors/vendor.icd
LD_LIBRARY_PATH=/system/lib64/:/system/vendor/lib64/:/data/data/com.termux/files/usr/lib hashcat -b 
``

**Comment by fornwall** [comment]
We are closing old pull requests as a cleanup action.

If you are interested in picking this work up, please submit a new pull request with up to date content and we promise to be more responsive with the proposed change!

**Pull request closed without merging**
