### PR TITLE
tree-wide: remove pthread/rt patches and workarounds

### PR DESCRIPTION
**Pull request by Grimler91**
Commit af18f1dac0b5 ("scripts: start_build: create libpthread and librt as well") added helper libs so that packages that try to find these libs can do so.

Let's let CI check if I messed up the manual editing of any patches. It seems some packages do not build for un-related reasons.

### CODE REVIEW

**Comment by xtkoba** [comment]
Is revbump for packages `hping3`, `libfuse3`, `pixiewps` and `v4l-utils` intentional?

The change in `rust` package looks like bogus. At least it is apparently not related to `lib{rt,pthread}`.

**Comment by Grimler91** [comment]
Ah, nope, that's some un-related changes, thanks for pointing it out

**Comment by Grimler91** [comment]
There are a few additional places where we could drop -lpthread related patches, but it was not trivial to directly edit the patch so I left it out of this tree-wide cleanup

**Review by xtkoba — COMMENTED** [review]
Modifications to the following packages are excluded due to build breakage:

- <a href="https://github.com/termux/termux-packages/actions/runs/4160117390">portaudio</a> (#15145)
- <a href="https://github.com/termux/termux-packages/actions/runs/4160156209">quickjs</a> (#15146)
- <a href="https://github.com/termux/termux-packages/actions/runs/4160219889">srelay</a> (#15147)
- <a href="https://github.com/termux/termux-packages/actions/runs/4160346381">z3</a> (#15148)

**Pull request merged**
