### PR TITLE
new package: lsix

### LINKED ISSUE #9650: [Package]: lsix
### Package description

Like "ls", but for images. Shows thumbnails in terminal using sixel graphics.

### Home page URL

https://github.com/hackerb9/lsix

### Source code URL

https://github.com/hackerb9/lsix

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Note: it needs a sixel-supporting terminal like foot termux/x11-packages#709

### PR DESCRIPTION
**Pull request by xtkoba**
Closes #9650.

### CODE REVIEW

**Comment by aicynide** [comment]
It should be run in foot terminal, can you try to to add foot please? https://github.com/termux/x11-packages/issues/709

**Comment by xtkoba** [comment]
I suppose `foot` is not a "hard" dependency, that is, `TERMUX_PKG_DEPENDS` for `lsix` does not need to contain `foot`.

**Comment by aicynide** [comment]
Foot is not required but to view image properly it should be used a sixel supporting terminal such as foot

**Comment by hackerb9** [comment]
@xtkoba Are you the person who packaged ImageMagick for Android? I got a bug report that `lsix` is not working on Android with termux due to an incorrect font setting.

**Pull request merged**
