### PR TITLE
fix(ndk-multilib): don't link the libraries that are in /system/lib/ already

### PR DESCRIPTION
**Pull request by buttaface**
When cross-compiling for armv7 on AArch64, C and other basic libraries are already installed, so use those instead.

Just as linking against these libraries for the host arch didn't work, as reported in #15802, they don't work when cross-compiling:
```
> cat m.c
#include <stdio.h>
int main(){puts("for the rig");}
> clang m.c -o run -target armv7-linux-android24 -Xlinker --verbose
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/crtbegin_dynamic.o
ld.lld: /data/data/com.termux/files/usr/tmp/m-842ca5.o
ld.lld: /data/data/com.termux/files/usr/lib/clang/16/lib/linux/libclang_rt.builtins-arm-android.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libunwind.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libdl.so
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libc.so
ld.lld: /data/data/com.termux/files/usr/lib/clang/16/lib/linux/libclang_rt.builtins-arm-android.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libunwind.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libdl.so
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/crtend_android.o
> ./run
Segmentation fault
> rm /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libc.so
> clang m.c -o run -target armv7-linux-android24 -Xlinker --verbose
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/crtbegin_dynamic.o
ld.lld: /data/data/com.termux/files/usr/tmp/m-4d9972.o
ld.lld: /data/data/com.termux/files/usr/lib/clang/16/lib/linux/libclang_rt.builtins-arm-android.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libunwind.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libdl.so
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libc.a
ld.lld: /data/data/com.termux/files/usr/lib/clang/16/lib/linux/libclang_rt.builtins-arm-android.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libunwind.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libdl.so
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/crtend_android.o
> ./run
error: "./run": executable's TLS segment is underaligned: alignment is 8, needs to be at least 32 for ARM Bionic
Aborted
> rm /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libc.a
> clang m.c -o run -target armv7-linux-android24 -Xlinker --verbose
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/crtbegin_dynamic.o
ld.lld: /data/data/com.termux/files/usr/tmp/m-cd611e.o
ld.lld: /data/data/com.termux/files/usr/lib/clang/16/lib/linux/libclang_rt.builtins-arm-android.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libunwind.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libdl.so
ld.lld: /system/lib/libc.so
ld.lld: /data/data/com.termux/files/usr/lib/clang/16/lib/linux/libclang_rt.builtins-arm-android.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libunwind.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libdl.so
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/crtend_android.o
> ./run
CANNOT LINK EXECUTABLE "./run": cannot locate symbol "android_get_application_target_sdk_version" referenced by "/apex/com.android.runtime/lib/bionic/libc.so"...
> rm /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libdl.so
> clang m.c -o run -target armv7-linux-android24 -Xlinker --verbose
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/crtbegin_dynamic.o
ld.lld: /data/data/com.termux/files/usr/tmp/m-b7b89d.o
ld.lld: /data/data/com.termux/files/usr/lib/clang/16/lib/linux/libclang_rt.builtins-arm-android.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libunwind.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libdl.a
ld.lld: /system/lib/libc.so
ld.lld: /data/data/com.termux/files/usr/lib/clang/16/lib/linux/libclang_rt.builtins-arm-android.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libunwind.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/libdl.a
ld.lld: /data/data/com.termux/files/usr/arm-linux-androideabi/lib/crtend_android.o
> ./run
for the rig
```
I don't bother installing the 32-bit links in a separate subpackage, as I doubt anybody wants them. I assume the same problem hits i686, so removed those links on x86_64 too, but I haven't tried that.

### CODE REVIEW

**Comment by buttaface** [comment]
Doesn't work in dash shell, need to look into the right syntax.

**Comment by landfillbaby** [comment]
fixed it :)
could also use both variables concatenated to a single string in this case

**Comment by buttaface** [comment]
Thanks, rebased and canceled the last CI workflow as it was rebuilding libllvm on the CI, which takes hours.

**Comment by buttaface** [comment]
Installed and uninstalled this from the CI on aarch64, appears to work now.

@Grimler91 or @xtkoba, let me know what you think.

**Comment by buttaface** [comment]
Merging since other maintainers had no comment; @landfillbaby, I don't see the connection to that clang wrapper?

**Comment by buttaface** [comment]
No, [`native_triple` is set in these trigger scripts](https://github.com/termux/termux-packages/blob/master/packages/ndk-multilib/postinst-header.in#L13), that pull won't have any effect on ndk-multilib.

**Comment by landfillbaby** [comment]
oops!

**Pull request merged**
