### PR TITLE
texlive: update to 20190410 and add texlive-full

### PR DESCRIPTION
**Pull request by Grimler91**
I've created a subpackage for each texlive collection and written some small python scripts to obtain the list of files for each subpackage from the texlive.tlpdb file. 

The CI will timeout (downloading texlive's texmf and extracting + re-archiving it takes too much time) so I'll build and upload the packages manually.

### CODE REVIEW

**Comment by Grimler91** [comment]
I'm getting an `Request Entity Too Large` error during bintray upload. I guess our current limit is 250 mb. I'll send an email to bintray and see if it's possible to increase it

**Comment by xeffyr** [comment]
Rebased on latest changes from master branch (switching CI).

**Comment by Grimler91** [comment]
@xeffyr Thanks! Seems it trieds to build more packages than just texlive, build timed out on libkbsa, which shouldn't be one of the dependencies

**Comment by Grimler91** [comment]
Packages are now uploaded so I am merging this!

**Pull request merged**
