### PR TITLE
vulkan-tools: build cube

### PR DESCRIPTION
**Pull request by licy183**
`vkcube` is a test program for vulkan. This program is disabled in the past because it is unable to work on Android vulkan loader.
We've added the generic vulkan loader so I think it's time to enable it.

### CODE REVIEW

**Comment by truboxl** [comment]
Curious how do you test this? What is your test environment?

**Comment by licy183** [comment]
> Curious how do you test this? What is your test environment?

I built the swrast ICD driver and used that to test. (PR: https://github.com/termux/termux-packages/pull/15350)

**Comment by truboxl** [comment]
`libwayland` is in `x11-repo`, may want to move `libwayland` to `main-repo` to prevent install failure

**Comment by truboxl** [comment]
Does `vkcube-wayland` work? I can't seem to find any way to test this...

**Comment by licy183** [comment]
> Does `vkcube-wayland` work? I can't seem to find any way to test this...

I didn't compile the lavapipe ICD with wayland support, so I don't know whether it will work or not too. Compiling with wayland support will make `vulkaninfo` linked against `libwayland.so` and let it have the ability to detect `VK_KHR_wayland_surface`. But anyway, I don't think that Termux will enable wayland for mesa in the near future. So what's your opinion on whether this option should be enabled or not?

**Comment by truboxl** [comment]
Can leave Wayland support in just in case we need it.

Hurm didn't realise `vulkaninfo` changed and added dependency on `libwayland-client.so`, `libxcb.so`, `libX11.so`. Seems a bit excessive for primarily a CLI tool. But it still works with system `libvulkan.so` when all deps are installed so I guess its fine...

Now to decide whether to:
1. keep `vulkan-tools` in `main` and move `libwayland` to `main`
2. move `vulkan-tools` to `x11` to match `mesa-demos` in `x11`, leaving `libwayland` intact

**Review by truboxl — APPROVED** [review]
LGTM thanks

Pinging @xtkoba if there's any objection moving libwayland and friends to `main` repo

**Comment by licy183** [comment]
If there is no more review, I will merge this PR at 8:00 tomorrow (UTC+8). Thanks!

**Pull request merged**
