### PR TITLE
fix path

### PR DESCRIPTION
**Pull request by yozman**

### CODE REVIEW

**Comment by Grimler91** [comment]
Thanks for spotting this, could you also bump TERMUX_PKG_REVISION of the package?

**Review by buttaface — APPROVED** [review]
Looks good, bump the package revision so people get updated.

**Comment by buttaface** [comment]
Heh, didn't see Henrik's comment saying the same. 😄

**Comment by xeffyr** [comment]
Merging despite it needs `TERMUX_PKG_REVISION` be incremented. For some reason I no longer have permission to edit forks, so can't do it within PR manually...

**Comment by kcubeterm** [comment]
> For some reason I no longer have permission to edit forks, so can't do it within PR manually...

Because he didn't give  permission to edit PR while submitting.

IMG_20201217_232735

**Comment by xeffyr** [comment]
> Because he didn't give permission to edit PR while submitting

In this case author should pay extra attention to https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#fixing-issues.

**Pull request merged**
