### PR TITLE
php: enabled intl extension

### LINKED ISSUE #696: Package request: php-intl
Hello,

I want to run a PHP script that requires the intl extension. Would it be possible to add it?

### PR DESCRIPTION
**Pull request by vaites**
I applied some patches to phpize and php-config commands (grep path and tmp location), so users can compile extensions not included in distribution (like ImageMagick).

It also fixes #696

### CODE REVIEW

**Comment by vaites** [comment]
Merged changes made for 7.1.2 release

**Comment by fornwall** [comment]
Nice!

libicu is a rather large dependency to bring in for everyone. Could you have a look at building the intl extension as a shared library module, and split it up into a php-intl subpackage?

**Comment by vaites** [comment]
Of course, as many distributions made... Should we split other extensions
too?

**Comment by fornwall** [comment]
> Of course, as many distributions made... Should we split other extensions too?

We can start with just separating the new php-intl extension and leave the other extensions as is for now.

**Comment by vaites** [comment]
Ok, will try!

**Pull request closed without merging**
