### PR TITLE
rust: update to 1.46.0

### PR DESCRIPTION
**Pull request by coolreader18**

### CODE REVIEW

**Comment by buttaface** [comment]
Can you update the host version used to cross-compile rust packages too?

**Comment by coolreader18** [comment]
Like for `termux_setup_rust.sh`? It seems like that's taken from the `rust/build.sh` script.

**Comment by buttaface** [comment]
You're right, I got it confused with the Golang setup.

**Comment by buttaface** [comment]
Btw, is there some issue with cross-compiling Termux packages that are written in rust lately? Because I tried updating the nushell package and it fails because cargo also strangely natively compiles some of the crate dependencies for linux x86_64, which errors because we're passing it all the Android flags.

**Comment by coolreader18** [comment]
Oh, hmm, those might be for procedural macros -- it needs to compile and run rust code at compile time in order to handle some sorts of macro calls. I haven't looked at the build script, but it might be possible to just change an env variable like `RUSTFLAGS` to `TARGET_aarch64_androidwhatever_RUSTFLAGS`

**Comment by buttaface** [comment]
Alright, thanks for the tip, will see if that's it.

**Comment by coolreader18** [comment]
Oh, if you're talking about this build: https://github.com/termux/termux-packages/runs/1063466031

I think that's still just a openssl issue, you probably have to set OPENSSL_DIR to where the headers are

**Comment by coolreader18** [comment]
And here's [the documentation for env variables](https://doc.rust-lang.org/cargo/reference/environment-variables.html#configuration-environment-variables) -- near the bottom of that list there's info on `CARGO_TARGET_<triple>_RUSTFLAGS`

**Comment by buttaface** [comment]
That CI run is related, but I'm building for AArch64 locally so it fails at a different point for me.

I think the OpenSSL headers it complains about in that CI log is misleading, it probably just says that no matter what when that crate fails. If you scroll up a bit, [it shows the build variables and compiler error](https://github.com/termux/termux-packages/runs/1063466031#step:5:1105), where it compiles for the linux x86_64 host but passes the C flags with `-march=i686` and errors because of the discrepancy.

I see a similar issue on AArch64, where it builds one of the nushell plugins for the host then complains that the libraries from the Termux sysroot are AArch64 and can't link against them.

This might be related to a recent Rust version update, I'll try going back to the old nushell version and see if I can reproduce.

**Comment by dram** [comment]
Seems that `cargo`, `rustc` are uninstalled after upgrade.

**Comment by its-pointless** [comment]
> Seems that `cargo`, `rustc` are uninstalled after upgrade.

yeah im going to have to fix it. 
Rust needs to be very tested before commiting in future. I have made the same mistakes.

**Comment by buttaface** [comment]
OK, I don't use the rust package. I wondered if I should commit given the past issues, but it passed the CI and I figured he had it working.

I will leave the rust pulls to you from now on, let me know if I can help get this fixed.

**Comment by coolreader18** [comment]
I should also actually test that the package works when a Rust version is released instead of just making a PR and leaving you to deal with the issues @its-pointless :grimacing:

**Pull request merged**
