### PR TITLE
mkvtoolnix: bump version

### PR DESCRIPTION
**Pull request by spookyahell**
from 53 to 59

### CODE REVIEW

**Comment by suhan-paradkar** [comment]
Looks like Qt5-qtbase package is required for the never version of this package....

**Comment by xeffyr** [comment]
Yes, that was a reason why I didn't updated it. Probably we can move it to x11 repo

**Comment by spookyahell** [comment]
I just checked, apparently version 58 doesn't require this. Would it be possible to bump it to that version?

**Comment by suhan-paradkar** [comment]
> I just checked, apparently version 58 doesn't require this. Would it be possible to bump it to that version?

@spookyahell Better would be moving this package to x11-repo as @xeffyr mentioned...
You won't be able to get further updates without doing so

**Comment by xeffyr** [comment]
While we have Qt5 in X11 repo which allows to pass configure issue, there is another problem:
```
ld.lld: error: undefined symbol: std::__ndk1::__fs::filesystem::__create_directories(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code*)
>>> referenced by unix.cpp
>>>               unix.o:(mtx::fs::create_directories(std::__ndk1::__fs::filesystem::path const&, std::__ndk1::error_code&)) in archive src/common/libmtxcommon.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

This package uses `std::filesystem` which is not available in libc++ version provided by Termux. So no updates possible for now. Once we upgrade NDK, then may give it a try but not now.

**Comment by xeffyr** [comment]
Added as disabled package in https://github.com/termux/x11-packages/commit/4eb7aaadb5ab519fcf44ea57abafe6ab5bcb8dac

**Pull request closed without merging**
