### PR TITLE
add libcrypt to apr-util dependencies

### PR DESCRIPTION
**Pull request by stephengroat**
build process looks for crypt.h

### CODE REVIEW

**Comment by fornwall** [comment]
The apr-util build process looks for crypt.h, but even if it finds the file it doesn't use it since it doesn't pick up the shared library:

```
configure:23652: checking for library containing crypt
configure:23683: aarch64-linux-android-clang -o conftest  -Oz -I/data/data/com.termux/files/usr/include -DLINUX -D_REENTRANT -D_GNU_SOURCE -L/data/data/com.termux/files/usr/lib conftest.c  >&5
/tmp/conftest-bde432.o:conftest.c:function main: error: undefined reference to 'crypt'
clang50: error: linker command failed with exit code 1 (use -v to see invocation)
```

So if we really want to enable crypt functionality in apr-util I guess we need to modify the build further - but I'm not sure of the benefits.

**Comment by stephengroat** [comment]
@fornwall can you compile without building `crypt` first? my compilation using #1169 fails without libcrypt

**Comment by fornwall** [comment]
@stephengroat Yes, the build works as it just configures apr-util to be built without crypt support. Can you post the error message?

**Comment by stephengroat** [comment]
```shell
checking build system type... x86_64-pc-linux-gnu
checking host system type... aarch64-unknown-linux-android
checking target system type... aarch64-unknown-linux-android
checking for a BSD-compatible install... /usr/bin/install -c
checking for working mkdir -p... yes
APR-util Version: 1.6.1
checking for chosen layout... apr-util
checking for aarch64-linux-android-gcc... aarch64-linux-android-clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether aarch64-linux-android-clang accepts -g... yes
checking for aarch64-linux-android-clang option to accept ISO C89... none needed
Applying apr-util hints file rules for aarch64-unknown-linux-android
checking for APR... yes
  adding "-DLINUX" to CPPFLAGS
  adding "-D_REENTRANT" to CPPFLAGS
  adding "-D_GNU_SOURCE" to CPPFLAGS
checking how to run the C preprocessor... aarch64-linux-android-cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for ldap support...
checking for default DBM... sdbm (default)
checking for pg_config... no
checking libpq-fe.h usability... no
checking libpq-fe.h presence... no
checking for libpq-fe.h... no
checking postgresql/libpq-fe.h usability... no
checking postgresql/libpq-fe.h presence... no
checking for postgresql/libpq-fe.h... no
checking sqlite.h usability... no
checking sqlite.h presence... no
checking for sqlite.h... no
checking for odbc_config... no
checking sql.h usability... no
checking sql.h presence... no
checking for sql.h... no
checking odbc/sql.h usability... no
checking odbc/sql.h presence... no
checking for odbc/sql.h... no
checking Expat 1.95.x... yes
  setting APRUTIL_EXPORT_LIBS to "-lexpat"
  setting APRUTIL_LIBS to "-lexpat"
checking iconv.h usability... yes
checking iconv.h presence... yes
checking for iconv.h... yes
  setting LIBS to "-liconv"
  nulling LIBS
checking for iconv.h... (cached) yes
checking langinfo.h usability... no
checking langinfo.h presence... no
checking for langinfo.h... no
checking for nl_langinfo... no
checking for CODESET in langinfo.h... no
checking whether APR has DSO support... yes
checking for library containing crypt... no
checking if system crypt() function is threadsafe... no
checking for crypt_r... no
checking whether the compiler handles weak symbols... no
checking for memset_s support... no
checking for explicit_bzero support... no
  adding "-L/data/data/com.termux/files/usr/lib" to APRUTIL_LIBS
  adding "-R/data/data/com.termux/files/usr/lib" to APRUTIL_LIBS
  adding "-lapr-1" to APRUTIL_LIBS
  adding "-luuid" to APRUTIL_LIBS
  adding "-lm" to APRUTIL_LIBS
configure: creating ./config.status
config.status: creating Makefile
config.status: creating export_vars.sh
config.status: creating build/pkg/pkginfo
config.status: creating apr-util.pc
config.status: creating apu-1-config
config.status: creating include/private/apu_select_dbm.h
config.status: creating include/apr_ldap.h
config.status: creating include/apu.h
config.status: creating include/apu_want.h
config.status: creating test/Makefile
config.status: creating include/private/apu_config.h
config.status: executing default commands
configure: WARNING: unrecognized options: --disable-dependency-tracking, --disable-rpath, --disable-rpath-hack, --disable-nls, --enable-shared, --disable-static
make[1]: Entering directory '/home/builder/.termux-build/apr-util/build'
mawk -f /data/data/com.termux/files/usr/share/apr-1/build/make_exports.awk /home/builder/.termux-build/apr-util/src/include/apr_anylock.h /home/builder/.termux-build/apr-util/src/include/apr_base64.h /home/builder/.termux-build/apr-util/src/include/apr_buckets.h /home/builder/.termux-build/apr-util/src/include/apr_crypto.h /home/builder/.termux-build/apr-util/src/include/apr_date.h /home/builder/.termux-build/apr-util/src/include/apr_dbd.h /home/builder/.termux-build/apr-util/src/include/apr_dbm.h /home/builder/.termux-build/apr-util/src/include/apr_hooks.h /home/builder/.termux-build/apr-util/src/include/apr_ldap_init.h /home/builder/.termux-build/apr-util/src/include/apr_ldap_option.h /home/builder/.termux-build/apr-util/src/include/apr_ldap_rebind.h /home/builder/.termux-build/apr-util/src/include/apr_ldap_url.h /home/builder/.termux-build/apr-util/src/include/apr_md4.h /home/builder/.termux-build/apr-util/src/include/apr_md5.h /home/builder/.termux-build/apr-util/src/include/apr_memcache.h /home/builder/.termux-build/apr-util/src/include/apr_optional.h /home/builder/.termux-build/apr-util/src/include/apr_optional_hooks.h /home/builder/.termux-build/apr-util/src/include/apr_queue.h /home/builder/.termux-build/apr-util/src/include/apr_redis.h /home/builder/.termux-build/apr-util/src/include/apr_reslist.h /home/builder/.termux-build/apr-util/src/include/apr_rmm.h /home/builder/.termux-build/apr-util/src/include/apr_sdbm.h /home/builder/.termux-build/apr-util/src/include/apr_sha1.h /home/builder/.termux-build/apr-util/src/include/apr_siphash.h /home/builder/.termux-build/apr-util/src/include/apr_strmatch.h /home/builder/.termux-build/apr-util/src/include/apr_thread_pool.h /home/builder/.termux-build/apr-util/src/include/apr_uri.h /home/builder/.termux-build/apr-util/src/include/apr_uuid.h /home/builder/.termux-build/apr-util/src/include/apr_xlate.h /home/builder/.termux-build/apr-util/src/include/apr_xml.h /home/builder/.termux-build/apr-util/src/include/apu_errno.h /home/builder/.termux-build/apr-util/src/include/apu_version.h /home/builder/.termux-build/apr-util/src/include/private/apr_crypto_internal.h /home/builder/.termux-build/apr-util/src/include/private/apr_dbd_internal.h /home/builder/.termux-build/apr-util/src/include/private/apr_dbd_odbc_v2.h /home/builder/.termux-build/apr-util/src/include/private/apr_dbm_private.h /home/builder/.termux-build/apr-util/src/include/private/apu_internal.h > exports.c
mawk -f /data/data/com.termux/files/usr/share/apr-1/build/make_var_export.awk /home/builder/.termux-build/apr-util/src/include/apr_anylock.h /home/builder/.termux-build/apr-util/src/include/apr_base64.h /home/builder/.termux-build/apr-util/src/include/apr_buckets.h /home/builder/.termux-build/apr-util/src/include/apr_crypto.h /home/builder/.termux-build/apr-util/src/include/apr_date.h /home/builder/.termux-build/apr-util/src/include/apr_dbd.h /home/builder/.termux-build/apr-util/src/include/apr_dbm.h /home/builder/.termux-build/apr-util/src/include/apr_hooks.h /home/builder/.termux-build/apr-util/src/include/apr_ldap_init.h /home/builder/.termux-build/apr-util/src/include/apr_ldap_option.h /home/builder/.termux-build/apr-util/src/include/apr_ldap_rebind.h /home/builder/.termux-build/apr-util/src/include/apr_ldap_url.h /home/builder/.termux-build/apr-util/src/include/apr_md4.h /home/builder/.termux-build/apr-util/src/include/apr_md5.h /home/builder/.termux-build/apr-util/src/include/apr_memcache.h /home/builder/.termux-build/apr-util/src/include/apr_optional.h /home/builder/.termux-build/apr-util/src/include/apr_optional_hooks.h /home/builder/.termux-build/apr-util/src/include/apr_queue.h /home/builder/.termux-build/apr-util/src/include/apr_redis.h /home/builder/.termux-build/apr-util/src/include/apr_reslist.h /home/builder/.termux-build/apr-util/src/include/apr_rmm.h /home/builder/.termux-build/apr-util/src/include/apr_sdbm.h /home/builder/.termux-build/apr-util/src/include/apr_sha1.h /home/builder/.termux-build/apr-util/src/include/apr_siphash.h /home/builder/.termux-build/apr-util/src/include/apr_strmatch.h /home/builder/.termux-build/apr-util/src/include/apr_thread_pool.h /home/builder/.termux-build/apr-util/src/include/apr_uri.h /home/builder/.termux-build/apr-util/src/include/apr_uuid.h /home/builder/.termux-build/apr-util/src/include/apr_xlate.h /home/builder/.termux-build/apr-util/src/include/apr_xml.h /home/builder/.termux-build/apr-util/src/include/apu_errno.h /home/builder/.termux-build/apr-util/src/include/apu_version.h /home/builder/.termux-build/apr-util/src/include/private/apr_crypto_internal.h /home/builder/.termux-build/apr-util/src/include/private/apr_dbd_internal.h /home/builder/.termux-build/apr-util/src/include/private/apr_dbd_odbc_v2.h /home/builder/.termux-build/apr-util/src/include/private/apr_dbm_private.h /home/builder/.termux-build/apr-util/src/include/private/apu_internal.h > export_vars.c
sed 's,^\(location=\).*$,\1installed,' < apu-1-config > apu-config.out
aarch64-linux-android-cpp -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    exports.c | grep "ap_hack_" | sed -e 's/^.*[)]\(.*\);$/\1/' >> aprutil.exp
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_brigade.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_brigade.c && touch buckets/apr_brigade.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_buckets.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_buckets.c && touch buckets/apr_buckets.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_buckets_alloc.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_buckets_alloc.c && touch buckets/apr_buckets_alloc.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_buckets_eos.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_buckets_eos.c && touch buckets/apr_buckets_eos.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_buckets_file.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_buckets_file.c && touch buckets/apr_buckets_file.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_buckets_flush.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_buckets_flush.c && touch buckets/apr_buckets_flush.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_buckets_heap.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_buckets_heap.c && touch buckets/apr_buckets_heap.lo
aarch64-linux-android-cpp -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    export_vars.c | sed -e 's/^\#[^!]*//' | sed -e '/^$/d' >> aprutil.exp
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_buckets_mmap.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_buckets_mmap.c && touch buckets/apr_buckets_mmap.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_buckets_pipe.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_buckets_pipe.c && touch buckets/apr_buckets_pipe.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_buckets_pool.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_buckets_pool.c && touch buckets/apr_buckets_pool.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_buckets_refcount.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_buckets_refcount.c && touch buckets/apr_buckets_refcount.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_buckets_simple.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_buckets_simple.c && touch buckets/apr_buckets_simple.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o buckets/apr_buckets_socket.lo -c /home/builder/.termux-build/apr-util/src/buckets/apr_buckets_socket.c && touch buckets/apr_buckets_socket.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o crypto/apr_crypto.lo -c /home/builder/.termux-build/apr-util/src/crypto/apr_crypto.c && touch crypto/apr_crypto.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o crypto/apr_md4.lo -c /home/builder/.termux-build/apr-util/src/crypto/apr_md4.c && touch crypto/apr_md4.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o crypto/apr_md5.lo -c /home/builder/.termux-build/apr-util/src/crypto/apr_md5.c && touch crypto/apr_md5.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o crypto/apr_passwd.lo -c /home/builder/.termux-build/apr-util/src/crypto/apr_passwd.c && touch crypto/apr_passwd.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o crypto/apr_sha1.lo -c /home/builder/.termux-build/apr-util/src/crypto/apr_sha1.c && touch crypto/apr_sha1.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o crypto/apr_siphash.lo -c /home/builder/.termux-build/apr-util/src/crypto/apr_siphash.c && touch crypto/apr_siphash.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o crypto/crypt_blowfish.lo -c /home/builder/.termux-build/apr-util/src/crypto/crypt_blowfish.c && touch crypto/crypt_blowfish.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o crypto/getuuid.lo -c /home/builder/.termux-build/apr-util/src/crypto/getuuid.c && touch crypto/getuuid.lo
/bin/bash /data/data/com.termux/files/usr/share/apr-1/build/libtool --silent --mode=compile aarch64-linux-android-clang   -Oz -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -I/data/data/com.termux/files/usr/include -I/home/builder/.termux-build/apr-util/build/include -I/home/builder/.termux-build/apr-util/build/include/private -I/home/builder/.termux-build/apr-util/src/include/private -I/home/builder/.termux-build/apr-util/src/include  -I/data/data/com.termux/files/usr/include/apr-1    -o crypto/uuid.lo -c /home/builder/.termux-build/apr-util/src/crypto/uuid.c && touch crypto/uuid.lo
/home/builder/.termux-build/apr-util/src/crypto/apr_passwd.c:28:10: fatal error: 'crypt.h' file not found
#include <crypt.h>
         ^~~~~~~~~
1 error generated.
/home/builder/.termux-build/apr-util/build/build/rules.mk:206: recipe for target 'crypto/apr_passwd.lo' failed
make[1]: *** [crypto/apr_passwd.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/builder/.termux-build/apr-util/build'
/home/builder/.termux-build/apr-util/build/build/rules.mk:118: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by stephengroat** [comment]
@fornwall any thoughts on this?

**Comment by Grimler91** [comment]
@stephengroat I tried building with this build-package.sh (`./build-package -a arm -i apr-util`) after doing a `./clean.sh` and it finished just fine. Could you try it again on your system?

**Comment by Grimler91** [comment]
Simply commenting out `#include <crypt.h>` makes it build for aarch64 as well (no surprise there really). 
I don't understand why aarch64 fails but not arm, it's pretty interesting.

**Comment by stephengroat** [comment]
@Grimler91 looking into now with all different `archs` and will report back

thought that `aarch64` would be the most stable, now I just look stupid

**Comment by fornwall** [comment]
Closed by https://github.com/termux/termux-packages/commit/ff9747dfd08def90738f271d133da9076622f357

**Pull request closed without merging**
