### PR TITLE
initial version of kona package

### PR DESCRIPTION
**Pull request by jhbadger**
I have created a package for kona (open source version of the K programming language). Let me know if you have any questions or suggestions (this is my first termux package).

### CODE REVIEW

**Comment by fornwall** [comment]
Nice! Will look into it a bit more later today!

One thing is that `packages/termux-tools/termux-elf-cleaner.cpp` was changed - why did you need that? Did you get a compiler error?

**Comment by jhbadger** [comment]
I did get an error and that's why I commented out those lines in termux-elf-cleaner.cpp -- but that might be because I'm on OSX and not Linux on the computer side. I didn't actually mean to include that change in the kona package though -- if it works for you without those comments then great.

**Comment by fornwall** [comment]
Ok, I'll take a look if it needs fixing on OSX! Could you remove the termux-elf-cleaner.cpp change from this pull request in the meantime?

Otherwise it looks great! Additional work (x86 support, avoid defining PREFIX path hardcoded in favour of @TERMUX_PREFIX@ and usng the predefined general CFLAGS and LDFLAGS) can be made in followup patches.

Do you want to stand as the package maintainer? By definining

    TERMUX_PKG_MAINTAINER="firstname lastname <your@email.com>

your name will be visible to users running `apt show kona` and you may get support questions. It's optional, you may submit and work on the package without being maintainer if you want to!

**Comment by jhbadger** [comment]
Removed changes to termux-elf-cleaner.cpp and added myself as maintainer for kona

**Comment by fornwall** [comment]
@jhbadger Nice work! I made minor changes in https://github.com/termux/termux-packages/commit/9a0f600ca2004e49d5b3cacf4d8dd6896aed153e (to also build on non-arm) and have pushed the build to the apt repo, so the package can now be installed with

    apt install kona

I also fixed the error in termux-elf-cleaner.cpp on OS X in https://github.com/termux/termux-packages/commit/131bb40101933a98edc4b471515f663c68394d6d, so you shouldn't need to modify that anymore!

**Pull request merged**
