### PR TITLE
unbound: Update to 1.15.0 and enable Python support

### PR DESCRIPTION
**Pull request by xtkoba**

### CODE REVIEW

**Comment by DasSkelett** [comment]
This isn't really ideal given that libgnutls depends on unbound since #8065. This inflates installations a lot now, requiring several hundred megabytes for all the dependencies:

```
Start-Date: 2022-04-08  22:23:22
Commandline: apt upgrade
Install: libandroid-posix-semaphore:arm (0.1-3, automatic), lld:arm (13.0.1, automatic), libllvm:arm (13.0.1, automatic), libcompiler-rt:arm (13.0.1, automatic), 
libxml2:arm (2.9.13, automatic), llvm:arm (13.0.1, automatic), gdbm:arm (1.22, automatic), libcrypt:arm (0.2-5, automatic), 
glib:arm (2.72.0-1, automatic), make:arm (4.3-2, automatic), ndk-sysroot:arm (23b-7, automatic), pkg-config:arm (0.29.2-1, automatic), 
clang:arm (13.0.1, automatic), libffi:arm (3.4.2, automatic), python:arm (3.10.4, automatic), ncurses-ui-libs:arm (6.3, automatic)
Upgrade: unbound:arm (1.13.2-3, 1.15.0)
End-Date: 2022-04-08  22:23:36
```

**Comment by buttaface** [comment]
Maybe better to remove the Python support then, @xtkoba?

**Comment by Grimler91** [comment]
Or move the python part (and python dependency) to a subpackage called unbound-python or similar, I can make a PR for this

**Comment by DasSkelett** [comment]
Shall I open a issue to track this and as a place for related discussions, given that the approach from #9931 didn't work?

**Comment by yan12125** [comment]
Here is yet another idea: create a package `unbound-python`, remove python support from `unbound`, and then use `TERMUX_PKG_DEPENDS="..., unbound | unbound-python"` in libgnutls. This approach requires keeping versions of unbound and unbound-python in sync, and that may not be trivial.

**Comment by yan12125** [comment]
Oh, found that clang is in `Recommends:` instead of `Depends:` for python. `apt remove clang && apt autoremove` saves me 371MB :)

**Comment by cbrt64** [comment]
Update workaround until this is sorted: for those like me deferring 67 MiB of updates due to slow connection, `pkg up clang-` or `apt upgrade clang-` (notice the hyphen) will update everything except `unbound`. Add `python-` if you don't want that either. Found [here](https://askubuntu.com/a/1151099).

**Comment by yan12125** [comment]
Nice tip! But I guess `python-` will not work as it's a mandatory dependency of the current unbound package instead of a recommended/suggested one.

**Comment by Grimler91** [comment]
Situation should improve with https://github.com/termux/termux-packages/pull/9973, if you are curious you can download debs from https://github.com/termux/termux-packages/actions/runs/2147282942 and install `unbound-python`.

**Pull request merged**
