### PR TITLE
upgpkg(libllvm): 14.0.6 to 15.0.0

### LINKED ISSUE #11861: [Information]: llvm 15 has been released
LLVM 15 has been released, I think we should update this package.

FYI: https://discourse.llvm.org/t/llvm-15-0-0-release/65099

CC: @buttaface @Grimler91

### PR DESCRIPTION
**Pull request by buttaface**
Close #11861

### CODE REVIEW

**Comment by licy183** [comment]
Great! I also want to add a commit (https://github.com/llvm/llvm-project/commit/ef5ede52efbff6ffa9f8c40dc3c6276146e6ff45) from upstream to add `PIC` support for `flang`, and then we will be able to add llvm-flang for Termux.

Patch file: https://github.com/llvm/llvm-project/commit/ef5ede52efbff6ffa9f8c40dc3c6276146e6ff45.patch

**Comment by buttaface** [comment]
Fine by me, you need the clang portions of that patch because flang links against libclang?

**Comment by licy183** [comment]
> 

Yes, `flang` needs to link with `libclang`.

**Comment by buttaface** [comment]
Alright, added the clang portions of that patch and restarted this build: let me know if I missed anything.

**Comment by licy183** [comment]
> Alright, added the clang portions of that patch and restarted this build: let me know if I missed anything.

OK, Thanks!

**Comment by buttaface** [comment]
Sigh, how many of these stupid generator executables for the build are they going to keep adding?

**Comment by buttaface** [comment]
Alright, this pull is ready to go in. I've tested an earlier AArch64 build on Android 12 without a problem: I will leave this open till tomorrow so that anyone willing to test other architectures or earlier Android versions can do so.

Simply download [the zip file for your arch from the CI](https://github.com/termux/termux-packages/actions/runs/3034630119) after the build finishes in 15 mins. ([earlier builds that work the same are available here](https://github.com/termux/termux-packages/actions/runs/3033121302)), then remove any existing LLVM packages with `apt remove libllvm`, and install these with `dpkg -i *15.0.0*.deb`.

**Comment by licy183** [comment]
> Alright, this pull is ready to go in. I've tested an earlier AArch64 build on Android 12 without a problem: I will leave this open till tomorrow so that anyone willing to test other architectures or earlier Android versions can do so.
> 
> Simply download [the zip file for your arch from the CI](https://github.com/termux/termux-packages/actions/runs/3034630119) after the build finishes in 15 mins. ([earlier builds that work the same are available here](https://github.com/termux/termux-packages/actions/runs/3033121302)), then remove any existing LLVM packages with `apt remove libllvm`, and install these with `dpkg -i *15.0.0*.deb`.

I think we have to hold this until we find out why `rust` doesn't work. `librustc_driver.so` links against `libLLVM-14.so` and if we update `libllvm` from 14 to 15 then `rust` will not work.

**Comment by buttaface** [comment]
> I think we have to hold this until we find out why rust doesn't work.

Fine by me. Swift 5.7 will be releasing in the next couple weeks, so that and a couple libllvm-dependent packages will need to be updated too.

**Comment by zorro** [comment]
@buttaface @licy183 Also note that implicit function declarations became an error in ```clang 15```. 

https://discourse.llvm.org/t/configure-script-breakage-with-the-new-werror-implicit-function-declaration/65213/

**Comment by zorro** [comment]
> > Alright, this pull is ready to go in. I've tested an earlier AArch64 build on Android 12 without a problem: I will leave this open till tomorrow so that anyone willing to test other architectures or earlier Android versions can do so.
> > Simply download [the zip file for your arch from the CI](https://github.com/termux/termux-packages/actions/runs/3034630119) after the build finishes in 15 mins. ([earlier builds that work the same are available here](https://github.com/termux/termux-packages/actions/runs/3033121302)), then remove any existing LLVM packages with `apt remove libllvm`, and install these with `dpkg -i *15.0.0*.deb`.
> 
> I think we have to hold this until we find out why `rust` doesn't work. `librustc_driver.so` links against `libLLVM-14.so` and if we update `libllvm` from 14 to 15 then `rust` will not work.

The rust build is fixed now by @xtkoba .

**Comment by buttaface** [comment]
Alright, @Grimler91 and @PeroSar, I'm going to go ahead and merge this, then Rust, Swift, and a few other dependencies will need to be rebuilt with LLVM 15. I will take care of Swift and the others, one of you will have to rebuild Rust.

**Pull request merged**
