### PR TITLE
rust to 1.57

### PR DESCRIPTION
**Pull request by xyllery-7**

### CODE REVIEW

**Comment by sk0kanik** [comment]
You may also want to change to BOOTSTRAP_VERSION=1.56.1 on line 22 rust/build.sh

**Comment by xyllery-7** [comment]
Done @sk0kanik

**Comment by xyllery-7** [comment]
Build finished with errors:

```/home/builder/termux-packages/scripts/build/termux_create_debian_subpackages.sh: line 96: AR: unbound variable
Error: Process completed with exit code 1.```

termux_create_debian_subpackages.sh line 96:

`$AR cr "$TERMUX_SUBPKG_DEBFILE" \`

Changing $AR to just `ar` would probably fix it

**Comment by Grimler91** [comment]
> Changing $AR to just ar would probably fix it

Or perhaps removing AR from the list of variables to unset in rust's build.sh

**Comment by xyllery-7** [comment]
Done 😅

**Comment by Grimler91** [comment]
Thanks, let's see if it works!

**Comment by xyllery-7** [comment]
It worked :)

**Pull request merged**
