### PR TITLE
build mu4e with emacs on device via postinst

### LINKED ISSUE #6394: mu package does not include mu4e
It's not clear to me if this is a bug or a package request. 

> pkg install mu  

appears to not include mu4e, the popular email client for emacs users, as expected (forr mu, most distros seem to include mu4e with it), which leads to the following error within emacs when attempting to run mu4e:

> Cannot open load file: No such file or directory, mu4e. 

For Ubuntu/Debian, it *seems* mu4e may be included in the 'maildir-utils' package (https://github.com/djcb/mu). However, if a "mu" package exists in the termux pkg manager, makes me wonderr why mu4e isn't a part of it.

So I'm a bit confused. Can someone clarify what's going on here? What's the path to getting mu4e installed in termux?

### PR DESCRIPTION
**Pull request by m4lvin**
This should fix #6394.

Edit: As discussed below, we no longer need emacs in the docker image, but do the following:

- we let `mu` depend on `emacs`
- include the [mu4e-dont-bytecompile patch](https://sources.debian.org/patches/maildir-utils/1.6.9-1/mu4e-dont-bytecompile/) from Debian to include `.el` files of mu4e but not yet compile them
- use a postinst script to compile the `.el` files to `.elc` on the device at install time.

### CODE REVIEW

**Comment by thunder-coding** [comment]
Can you better do both the things in same PR? It would be much better

**Comment by m4lvin** [comment]
You mean triggering a rebuilt? Would that be done by bumping `TERMUX_PKG_REVISION`? Before I add this, can we be sure that the docker image to build the package is then updated before the package is rebuilt?

**Comment by thunder-coding** [comment]
No need, see https://github.com/termux/termux-packages/blob/3174161748d35ca837e6702f28e720112f9b3ec7/.github/workflows/packages.yml#L66

**Comment by thunder-coding** [comment]
the mu debs are still missing mu4e binary

**Comment by m4lvin** [comment]
afaik there is no mu4e binary. mu4e is an emacs package and that is now included in the deb (at least in arm)

**Comment by Grimler91** [comment]
It uses stuff in `/etc/emacs` (which is expected since it uses /usr/bin/emacs), and we end up with compiled .elc files that probably are not compatible with emacs on the device. We should probably use the files in $PREFIX/etc/emacs instead, maybe there is a flag for this in mu4e's Makefile.

Otherwise, to ensure that the files are compatible with our emacs we might be able to either:

* add mu4e as a subpackage of emacs instead, and use emacs's [bootstrap binary](https://github.com/termux/termux-packages/blob/master/packages/emacs/build.sh#L106) for compiling mu4e's elc files

* add a postinst script to mu4e which compiles the mu4e elc files on device, similar to how we are currently creating the [emacs.pdmp file](https://github.com/termux/termux-packages/blob/master/packages/emacs/build.sh#L131)

**Comment by m4lvin** [comment]
Thank you @Grimler91 for the notes and suggestions! I noticed that [the Debian package mu4e](https://packages.debian.org/bullseye/all/mu4e/filelist) also does not contain `.elc` files but those are generated after the package is installed via scripts in `emacsen-common`.

This makes me think that your second option would be the way to go, though that would mean `mu` depends on `emacs`.
Or could we make `mu4e` a subpackage of `mu`, to reflect that mu depends on emacs but mu4e does?

I changed this PR to a draft for now - it will take a while but I will try to make a `postinst` script usable via `termux_step_create_debscripts`.

**Comment by m4lvin** [comment]
Can this be merged or should I do anything else before? I have used the resulting package on device and mu4e works fine now.

**Comment by Grimler91** [comment]
Nice work, thanks!

**Comment by robertkirkman** [comment]
> Can this be merged or should I do anything else before? I have used the resulting package on device and mu4e works fine now.

hello, unfortunately for some reason it seems like recently, the `$PREFIX/share/emacs/site-lisp/` folder has stopped working to load Emacs addons, while the `$PREFIX/share/emacs/30.2/site-lisp/` has continued to work, but I don't know why.

Screenshot_20260824-081951_Termux_X11


```
~ $ cat .emacs
(require 'exwm)
(exwm-wm-mode)
(require 'mu4e)
~ $ 
```

- #31259 


```bash
dpkg -L mu
```

...

```
/data/data/com.termux/files/usr/share/emacs/site-lisp/mu4e/mu4e-compose.el
/data/data/com.termux/files/usr/share/emacs/site-lisp/mu4e/mu4e-config.el
/data/data/com.termux/files/usr/share/emacs/site-lisp/mu4e/mu4e-contacts.el
/data/data/com.termux/files/usr/share/emacs/site-lisp/mu4e/mu4e-context.el
/data/data/com.termux/files/usr/share/emacs/site-lisp/mu4e/mu4e-contrib.el
/data/data/com.termux/files/usr/share/emacs/site-lisp/mu4e/mu4e-dbus.el
/data/data/com.termux/files/usr/share/emacs/site-lisp/mu4e/mu4e-draft.el
```

```bash
dpkg -L emacs-exwm
```

...

```
/data/data/com.termux/files/usr/share/emacs/30.2/site-lisp/exwm/exwm-background.el
/data/data/com.termux/files/usr/share/emacs/30.2/site-lisp/exwm/exwm-core.el
/data/data/com.termux/files/usr/share/emacs/30.2/site-lisp/exwm/exwm-floating.el
/data/data/com.termux/files/usr/share/emacs/30.2/site-lisp/exwm/exwm-input.el
/data/data/com.termux/files/usr/share/emacs/30.2/site-lisp/exwm/exwm-layout.el
/data/data/com.termux/files/usr/share/emacs/30.2/site-lisp/exwm/exwm-manage.el
```

If I use this command, it works, but I don't know why.

```bash
mv $PREFIX/share/emacs/site-lisp/mu4e/ $PREFIX/share/emacs/30.2/site-lisp/
```

Screenshot_20260824-082253_Termux_X11

does this package still work for you without using the `mv` command, and if not, do you know what could have happened?

**Comment by m4lvin** [comment]
Starting `mu4e` still works fine for me, but I also do not use any X11 version of emacs - how is that even possible with Termux? :eyes: 

Maybe you have a different `emacs` package? I am on `30.2-5`.
EDIT: Ah, I guess you use `emacs-x`?

In `/data/data/com.termux/files/usr/share/emacs/30.2/site-lisp/` I only have one very short `subdirs.el` and no other files or subdirectories whatsoever.

**Comment by robertkirkman** [comment]
Yes, I am using `emacs-x` from the `pkg install x11-repo` repository; It works using the Termux:X11 addon app. https://github.com/termux/termux-x11

Just now, I switched to `emacs` as a test, and interestingly, testing shows that `emacs` is not affected by this problem, only `emacs-x`.

I've also noticed that the problem is connected with the `subdirs.el` file, definitely.

For some reason, `emacs` has a `$PREFIX/share/emacs/site-lisp/subdirs.el` file, but the build of `emacs-x` that's currently in the repository doesn't...

```
~ $ dpkg -L emacs | grep subdirs
/data/data/com.termux/files/usr/share/emacs/30.2/lisp/subdirs.el
/data/data/com.termux/files/usr/share/emacs/30.2/site-lisp/subdirs.el
/data/data/com.termux/files/usr/share/emacs/site-lisp/subdirs.el
~ $ 
```

```
~ $ dpkg -L emacs-x | grep subdirs
/data/data/com.termux/files/usr/share/emacs/30.2/lisp/subdirs.el
/data/data/com.termux/files/usr/share/emacs/30.2/site-lisp/subdirs.el
~ $ 
```

And even stranger, for some reason, when I recompile the `emacs-x` package on a PC using `scripts/run-docker.sh build-package.sh -I -f emacs-x`, and then I transfer it to my Android device and install it, the problem stops being reproducible and the `$PREFIX/share/emacs/site-lisp/subdirs.el` appears in `emacs-x`,

```
~ $ dpkg -L emacs-x | grep subdirs
/data/data/com.termux/files/usr/share/emacs/30.2/lisp/subdirs.el
/data/data/com.termux/files/usr/share/emacs/30.2/site-lisp/subdirs.el
/data/data/com.termux/files/usr/share/emacs/site-lisp/subdirs.el
~ $ 
```

but then, if I _rebuild the package again_ without deleting the Docker container, then transfer it and install it again on my device, the problem actually returns again:

```
~ $ dpkg -L emacs-x | grep subdirs
/data/data/com.termux/files/usr/share/emacs/30.2/lisp/subdirs.el
/data/data/com.termux/files/usr/share/emacs/30.2/site-lisp/subdirs.el
~ $ 
```

Thanks for pointing out that the problem varies in a subtle way based on which build of `emacs` is installed, since it seems like that has given me a clue to track down what is causing this.

**Comment by m4lvin** [comment]
Ugh, that sounds like an annoying race condition if building the package twice results in different behavior :-/
But probably it's not specifically related to mu4e then but any thing going into site-lisp. And I guess it should be a separate issue about the `emacs-x` package?

**Comment by robertkirkman** [comment]
I believe I have found the root cause; this seems to entirely fix the problem for me, no matter how many times I recompile the packages, both `emacs` and `emacs-x`. Unfortunately, this problem class occurs because Termux has what the "Linux From Scratch" project's documentation refers to as a "[timestamp-based package build system](https://www.linuxfromscratch.org/lfs/view/development/chapter08/pkgmgt.html)". However, Termux is one of the only significant distros remaining that has a timestamp-based package build system, so I believe it is important for me to continue making patches like this in order to preserve the Termux example for the long term of how a timestamp-based package build system should operate.

```diff
--- a/Makefile.in
+++ b/Makefile.in
@@ -610,7 +610,7 @@ install: actual-all install-arch-indep install-etcdoc install-arch-dep install-$
 ## world-readable.
 ## TODO it might be good to warn about non-standard permissions of
 ## pre-existing directories, but that does not seem easy.
-write_subdir=if [ -f "$${subdir}/subdirs.el" ]; \
+write_subdir=if false; \
 	then true; \
 	else \
 	 umask 022; \
```

**Pull request merged**
