### PR TITLE
bump(main/tmux): 3.5

### PR DESCRIPTION
**Pull request by TomJo2000**
We'll need to remove `htonll.patch`, I've already confirmed that locally,
and it was noted last time around <sub>https://github.com/termux/termux-packages/pull/19736#discussion_r1561105711</sub> since the patch was upstreamed.
But I'd like to enable autoupdates for `tmux` while we're here.

### CODE REVIEW

**Comment by TomJo2000** [comment]
There is a new `--enable-jemalloc` build option.
- https://github.com/tmux/tmux/blob/3.5/CHANGES#L45

It's not enabled by default, and I suspect we won't want to make use of it seeing as `libjemalloc` has been sitting in the disabled packages for 9 years.

**Comment by fornwall** [comment]
> There is a new --enable-jemalloc build option.
>
> https://github.com/tmux/tmux/blob/3.5/CHANGES#L45
>
> It's not enabled by default, and I suspect we won't want to make use of it seeing as libjemalloc has been sitting in the disabled packages for 9 years.

Background note: Android 7 to 10 actually uses jemalloc as system malloc, while in Android 11 it was switched to [scudo](https://source.android.com/docs/security/test/scudo) for most devices. So no, indeed there is most likely no need to switch to a custom malloc here or in other packages - the `since glibc malloc is so poor` [comment](https://github.com/tmux/tmux/blob/3.5/CHANGES#L45) is not applicable for bionic.

From [the Bionic Wikipedia entry](https://en.wikipedia.org/wiki/Bionic_(software)#Components):
> The [dynamic memory allocator](https://en.wikipedia.org/wiki/C_dynamic_memory_allocation) implementation has changed over time. Before [Lollipop](https://en.wikipedia.org/wiki/Android_Lollipop) there was a single native memory allocator, Doug Lea's [dlmalloc](https://en.wikipedia.org/wiki/Dlmalloc). For Lollipop and Marshmallow there were two implementations: dlmalloc and [jemalloc](https://en.wikipedia.org/wiki/Jemalloc). jemalloc gives much higher performance than dlmalloc, but at the cost of extra memory required for bookkeeping. Most devices used jemalloc but low-memory devices still used dlmalloc. For [Nougat](https://en.wikipedia.org/wiki/Android_Nougat) through [Android 10](https://en.wikipedia.org/wiki/Android_10), all devices use jemalloc. Low-memory devices use a "svelte" configuration of jemalloc that disables the tcache to nearly match the lower memory overhead of dlmalloc while keeping most of the speed of jemalloc. In [Android 11](https://en.wikipedia.org/wiki/Android_11), the memory allocator for most devices was switched to Scudo, which sacrifices some of jemalloc's high performance for additional security hardening features.[[6]](https://en.wikipedia.org/wiki/Bionic_(software)#cite_note-6) Low-memory devices, however, are still permitted to use jemalloc.[[7]](https://en.wikipedia.org/wiki/Bionic_(software)#cite_note-7)

**Comment by TomJo2000** [comment]
> the `since glibc malloc is so poor` [comment](https://github.com/tmux/tmux/blob/3.5/CHANGES#L45) is not applicable for bionic.

That was my assessment as well.

**Comment by TomJo2000** [comment]
If there's no further concerns I'd like to merge this in 8-12 hours.

**Review by licy183 — APPROVED** [review]

**Review by truboxl — APPROVED** [review]

**Pull request merged**
