### PR TITLE
python 3.9.2, take 2

### PR DESCRIPTION
**Pull request by landfillbaby**
i gave up too easily lol

### CODE REVIEW

**Comment by landfillbaby** [comment]
it work lol

**Comment by Grimler91** [comment]
@landfillbaby are you using/checking the outlook mail address that is connected to (some of) your github commits? 

I sent you an email a week ago or two, and just wondering if you received it?

**Comment by landfillbaby** [comment]
oh sorry, the main reason i recently switched to gmail is that outlook kept deleting messages without telling me, not even putting them in the spam folder first, and apparently it's a known issue
maybe that's what happened to your message, sorry

**Comment by landfillbaby** [comment]
i thought i'd updated my git, github, and gpg emails, but i guess i missed one

**Comment by landfillbaby** [comment]
my gmail is the same as my outlook but with a 69 on the end of the username lol

**Comment by landfillbaby** [comment]
ok yeah i forgot to update one of my .gitconfigs! oops!

**Comment by landfillbaby** [comment]
i now actually have contact info on github too

**Comment by landfillbaby** [comment]
btw, you said "(some of)", were the others just the ones with the noreply@github or was my gmail actually in some? i need to set up a dotfile manager lol

**Comment by landfillbaby** [comment]
in case i was unclear, you'll need to forward the email to my new account, sorry

**Comment by Grimler91** [comment]
@landfillbaby most of your commits were associated with noreply@github, yeah, but some (mostly older) had @outlook.com. 

Anyways, no worries, we were wondering if you would like to join the termux organization here at github and get push/write access to the repositories? You have contributed quite a lot of updates and info over the last years so we think you would be a valuable member of the team. 

There's not really any strings attached, members are free to work as much or as little as they want on updates and improvements so please do not see it as a big commitment.

If you are interested I'll send you an invite through github!

**Comment by landfillbaby** [comment]
ooh ok sounds good! i'll just have to make sure to avoid my bad habit of pushing directly to the main branch and rebasing if it fails lol

**Comment by Grimler91** [comment]
You should have received an email, or a notification through github, now :)

> i'll just have to make sure to avoid my bad habit of pushing directly to the main branch and rebasing if it fails lol

I am sure it will be fine! :)

**Comment by landfillbaby** [comment]
:) thanks, i will do my best!

**Pull request merged**
