### PR TITLE
python: Update from 3.8.6 to 3.9.0

### PR DESCRIPTION
**Pull request by Deshdeepak1**

### CODE REVIEW

**Review by xeffyr — CHANGES_REQUESTED** [review]
Please update the supplied patches.

**Comment by xeffyr** [comment]
I have added python3.9 interpreter to Docker image. Its build & upload is in progress but you can rebase your branch on top of `master`.

**Comment by Deshdeepak1** [comment]
Thanks for the merge. Will you add hacktoberfest-accepted label ?

**Comment by xeffyr** [comment]
Ok, labeled. I also added topic "hacktoberfest" to the repository, so it will count even for unlabeled pull requests.

**Comment by Deshdeepak1** [comment]
Thanks. But I have heard that increases spam.

**Pull request merged**
