### PR TITLE
Various Build Fixes

### PR DESCRIPTION
**Pull request by agnostic-apollo**

### CODE REVIEW

**Review by Grimler91 — COMMENTED** [review]
Thanks for the PR, please add `%ci:no-build` as last row to head commit after issues has been ironed out, as we don't want CI to build the packages with modified host build step

**Comment by agnostic-apollo** [comment]
Build failure was from 773a0294d and not for package builds, apparently github action sets `PS1`, but using a different way 06f734a39 to fix the issue now anyways.

And can't set `%ci:no-build` since need to actually test host build steps.

**Comment by agnostic-apollo** [comment]
Thanks @landfillbaby for the performance enhancement code ;)

The test build succeeded at https://github.com/termux/termux-packages/actions/runs/2738273868 and I checked the debs built and they seem to have `bin` and `lib` files, so hopefully host build changes are fine.

Unless someone objects or finds issues with any changes, will merge this after some waiting period.

**Comment by EMMANUEL-ALX** [comment]
Want be path of your team here.
New to Github

**Pull request merged**
