### PR TITLE
Additional dependencies.

### PR DESCRIPTION
**Pull request by Wetitpig**
Add more dependencies required for python scripts.

### CODE REVIEW

**Comment by fornwall** [comment]
> Add more dependencies required for python scripts.

Which python scripts?

**Comment by Wetitpig** [comment]
I forgot... it had been a long time ago.

**Comment by fornwall** [comment]
Ok, let's wait with these until we have an actual need for them!

**Comment by Wetitpig** [comment]
Ok. It seems that it is not required

**Pull request closed without merging**
