### PR TITLE
Add package tvheadend

### LINKED ISSUE #3066: Package Request: tvheadend
(or 'How can i compile it from source?')

### PR DESCRIPTION
**Pull request by MrAdityaAlok**
- closes #3066
- moved from #7563 

TODO:
- [x] Add `tvheadend` itself
- [x] Add `libdvbcsa` (optional)
- [ ] Add `avahi` (optional) I will add it some day later.

### CODE REVIEW

**Comment by MrAdityaAlok** [comment]
This should now be ready to be merged. I will add `avahi(optional)` library some day later.

**Comment by xeffyr** [comment]
@MrAdityaAlok Could you squash commits to leave only "add package" ones?

**Comment by MrAdityaAlok** [comment]
> @MrAdityaAlok Could you squash commits to leave only "add package" ones?

@xeffyr  done

**Comment by wsnake65** [comment]
tvheadend crashes when descrambling (Code Word Client (newcamd)) : **Bus Error**
Amlogic s922x ( Android TV 9 )

**Comment by MrAdityaAlok** [comment]
@wsnake65 I will look into it tonight.(it's 8:20 AM in my zone)

BTW I have never used tvheadend, can you provide steps to reproduce this?

**Comment by wsnake65** [comment]
Scheme for test: minisatip tuner (192.168.5.30) -> tvheadend (192.168.5.10) -> KODI (on my PC 192.168.5.2)
In the log file you can see the steps of the work TVH.

1. Turned on not encrypted channel:
2021-09-27 07:42:55.908 [  DEBUG]:htsp: 192.168.5.2 [  | Kodi Media Center ] - subscribe to 8 канал using profile htsp
2021-09-27 07:42:55.909 [  DEBUG]:service: 2: 8 канал si 0xb04d86c0 SAT>IP DVB-S Tuner #1 (192.168.5.30) weight 0 prio 11 error 0 (OK) 
.....
2021-09-27 07:42:57.759 [  DEBUG]:service: 36i/11976.82R/8 канал: Status changed to [Hardware input] [Input on service] [Demuxed packets] ---> Channel is running

2. Turned on encrypted channel:
2021-09-27 07:43:13.265 [  DEBUG]:htsp: 192.168.5.2 [  | Kodi Media Center ] - subscribe to BRIDGE TV using profile htsp
2021-09-27 07:43:13.266 [  DEBUG]:service: 2: BRIDGE TV si 0xb04d86c0 SAT>IP DVB-S Tuner #1 (192.168.5.30) weight 0 prio 11 error 0 (OK)
...
2021-09-27 07:43:13.403 [  DEBUG]:service: 36i/11976.82R/BRIDGE TV: Status changed to [Hardware input] [Input on service] [Demuxed packets] 
...
2021-09-27 07:43:15.682 [  DEBUG]:service: 36i/11976.82R/BRIDGE TV: Status changed to [Hardware input] [Input on service] [Demuxed packets] [No access]
 
Request for descrambling
2021-09-27 07:43:15.682 [  DEBUG]:cwc: ECM state INIT
2021-09-27 07:43:15.682 [  DEBUG]:cwc: Insert new ECM (PID 6221) for service "BRIDGE TV"
...
Received the key to descrambling the channel
2021-09-27 07:43:15.822 [  DEBUG]:cwc: Saving prefered PID 6021 for cwc-s15.1cent.in-4000-0500
2021-09-27 07:43:15.822 [  DEBUG]:cwc: Received ECM reply (PID 6021) for service "BRIDGE TV" [0] even: a3.37.f5.cf.17.62.ad.26 odd: 0c.61.d0.3d.8b.24.23.d2 (seqno: 2 Req delay: 48 ms)
2021-09-27 07:43:15.822 [  DEBUG]:cwc: Obtained DES keys for service "BRIDGE TV" in 48 ms, from cwc-s15.1cent.in-4000-0500
2021-09-27 07:43:15.822 [  DEBUG]:descrambler: Obtained keys from cwc-s15.1cent.in-4000-0500 for service "BRIDGE TV"
2021-09-27 07:43:15.822 [  DEBUG]:descrambler: info - service='BRIDGE TV' caid=0500(Viaccess) provid=000A00 ecmtime=48 hops=1 reader='' from='s15.1cent.in:4000' protocol='newcamd'

tvheadend crashes : Bus Error

[tvh.log](https://github.com/termux/termux-packages/files/7233728/tvh.log)

**Comment by MrAdityaAlok** [comment]
@wsnake65 could you chek if new build works by downloading zip file from [github actions](https://github.com/termux/termux-packages/actions/runs/1279757378) for your respective cpu architecture and installing deb file using `dpkg -i {DEBFILE_NAME}`

**Comment by wsnake65** [comment]
> 
> 
> @wsnake65 could you chek if new build works by downloading zip file from [github actions](https://github.com/termux/termux-packages/actions/runs/1279757378) for your respective cpu architecture and installing deb file using `dpkg -i {DEBFILE_NAME}`

**Pull request merged**
