### PR TITLE
tvheadend: fix bus error

### PR DESCRIPTION
**Pull request by MrAdityaAlok**

### CODE REVIEW

**Comment by MrAdityaAlok** [comment]
@wsnake65 I need some help from you.
I have enabled debug build. Please download and install it from [github actions](https://github.com/termux/termux-packages/actions/runs/1282073930).
 Then 
- install `gdb` using `pkg i gdb`
- run `tvheadend` with gdb as `gdb --args tvheadend {WHATEVER ARGS YOU WISH  TO GIVE TO TVHEADEND}`
- when it crashes use `bt` command to get backtrace.
- please provide me that backtrace.

**Comment by wsnake65** [comment]
> 
> 
> @wsnake65 I need some help from you. I have enabled debug build. Please download and install it from [github actions](https://github.com/termux/termux-packages/actions/runs/1282120170). Then
> 
>     * install `gdb` using `pkg i gdb`
> 
>     * run `tvheadend` with gdb as `gdb --args tvheadend {WHATEVER ARGS YOU WISH  TO GIVE TO TVHEADEND}`
> 
>     * when it crashes use `bt` command to get backtrace.
> 
>     * please provide me that backtrace.

bt:
Thread 26 "tvh:mi-main" received signal SIGBUS, Bus error.
[Switching to LWP 14717]
decrypt_packets_32int (keys=0xb10e4000, cluster=<optimized out>) at src/descrambler/ffdecsa/FFdecsa.c:834
834     src/descrambler/ffdecsa/FFdecsa.c: (undocumented errno 2).
(gdb) bt
#0  decrypt_packets_32int (keys=0xb10e4000, cluster=<optimized out>) at src/descrambler/ffdecsa/FFdecsa.c:834
#1  0x7d69af60 in tvhcsa_des_flush (csa=0xb36d8f04, s=0xb209fe00) at src/descrambler/tvhcsa.c:75
#2  tvhcsa_des_descramble (csa=0xb36d8f04, s=0xb209fe00, tsb=0xaf93f430 "G", tsb_len=<optimized out>)
    at src/descrambler/tvhcsa.c:150
#3  0x7d65940e in descrambler_descramble (t=<optimized out>, st=<optimized out>, tsb=<optimized out>,
    len=<optimized out>) at src/descrambler/descrambler.c:765
#4  0x7d660072 in ts_recv_packet1 (t=0xb209fe00, tsb=0xb1062011 "G", len=1316, table=1)
    at src/input/mpegts/tsdemux.c:233
#5  0x7d65f4c4 in mpegts_input_process (mi=<optimized out>, mpkt=<optimized out>)
    at src/input/mpegts/mpegts_input.c:1415
#6  mpegts_input_thread (p=<optimized out>) at src/input/mpegts/mpegts_input.c:1556
#7  0x7d5dc488 in thread_wrapper (p=0xb1032280) at src/wrappers.c:159
#8  0xb3d32c16 in __pthread_start(void*) () from /system/lib/libc.so
#9  0xb3ced066 in __start_thread () from /system/lib/libc.so
#10 0x00000000 in ?? () from /data/data/com.termux/files/usr/bin/tvheadend
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) q

**Comment by MrAdityaAlok** [comment]
@wsnake65  Thankyou!

**Comment by xtkoba** [comment]
Maybe we need `-DMEMALIGN=__attribute__((aligned(8)))` for `CFLAGS`.

**Comment by wsnake65** [comment]
> 
> 
> @wsnake65 Thankyou!

Is there a solution to this problem (tvheadend crashes)?

**Comment by MrAdityaAlok** [comment]
@wsnake65 can you check if new build works. Download from here https://github.com/termux/termux-packages/actions/runs/1297584678

If it does not work then please provide me backtrace again.

**Comment by MrAdityaAlok** [comment]
@wsnake65  do not try it now. I am building from master branch, which should fix the issue.

**Comment by MrAdityaAlok** [comment]
@wsnake65  you can download from https://github.com/termux/termux-packages/actions/runs/1297703431 and check if build works.

**Comment by wsnake65** [comment]
> 
> 
> @wsnake65 you can download from https://github.com/termux/termux-packages/actions/runs/1297718826 and check if build works.

I can not download - no files

**Comment by xtkoba** [comment]
Ah, `CFLAGS` (or other variables for `make`) containing parenthesis is problematic...

It would be much easier to modify the definition of `MEMALIGN` in the source directly instead:

```diff
--- a/src/descrambler/ffdecsa/FFdecsa.c
+++ b/src/descrambler/ffdecsa/FFdecsa.c
@@ -106,7 +106,7 @@
 #define FREE(X) free(X)
 #endif
 #ifndef MEMALIGN
-#define MEMALIGN
+#define MEMALIGN __attribute__((aligned(8)))
 #endif
 
 //// debug tool
```

**Comment by MrAdityaAlok** [comment]
> Ah, `CFLAGS` (or other variables for `make`) containing parenthesis is problematic...
> 
> It would be much easier to modify the definition of `MEMALIGN` in the source directly instead:
> 
> ```diff
> --- a/src/descrambler/ffdecsa/FFdecsa.c
> +++ b/src/descrambler/ffdecsa/FFdecsa.c
> @@ -106,7 +106,7 @@
>  #define FREE(X) free(X)
>  #endif
>  #ifndef MEMALIGN
> -#define MEMALIGN
> +#define MEMALIGN __attribute__((aligned(8)))
>  #endif
>  
>  //// debug tool
> ```

Yes, yes was doing that only.

**Comment by MrAdityaAlok** [comment]
@wsnake65 https://github.com/termux/termux-packages/actions/runs/1297994529 you can test now.

**Comment by wsnake65** [comment]
> 
> 
> @wsnake65 https://github.com/termux/termux-packages/actions/runs/1297994529 you can test now.

Thank you, everything works fine! Also checked the timeshift and recording - everything is fine. Please compile the package without debugs in termux.

**Comment by MrAdityaAlok** [comment]
@xtkoba thankyou! For your help.

**Comment by MrAdityaAlok** [comment]
This PR should be ready to be merged.

**Review by xeffyr — APPROVED** [review]

**Pull request merged**
