### PR TITLE
chore(main/vlc, x11/vlc-qt): set default video output to xcb

### LINKED ISSUE #19613: [Bug]: vlc defaults to opengl
### Problem description

Hello. It seems like vlc-qt (and possibly vlc too) defaults to use OpenGL video output, but its performance is very low in the case if only swrast/llvmpipe is installed. Can we make it fallback to X11 video output (XCB) in the case if llvmpipe is the only available driver? Vlc's performance will be much higher in that case.

### What steps will reproduce the bug?

Just install vlc-qt and open 1080p video.

### What is the expected behavior?

It should run faster like in the case of X11 video output.

### System information

termux-info:

```
Irrelevant
```

### LINKED ISSUE #20671: [Bug]: vlc H265/HEVC Performance
### Problem description

When playing `4K@30fps H265/HEVC video` using `vlc-qt`, the video screen is broken.

With the performance of the latest flagship SoC's CPU (`Snapdragon 8 Gen2`, `Exynos 2400`, `Snapdragon 8 Gen3`), playback would be sufficient without hardware decoding, but strangely, symptoms of screen crash are occurring separately from frame drops.

Screenshot_2024-06-25_23-24-05

Is it possible to fix the screen crash and performance above?

### What steps will reproduce the bug?

[4K@30fps H265/HEVC Sample](https://drive.google.com/file/d/1xsd4C7ZWpCncsYU5IZs5w0WMaU59SKvB/view?usp=sharing)

video sample above

On `Snapdragon 8 Gen2`, `Exynos 2400`, `Snapdragon 8 Gen3` host devices
Symptoms occur when playing through `vlc-qt`

`zink`, `virpipe`, `llvmpipe` are all the same

### What is the expected behavior?

_No response_

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=18475
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.sjtu.edu.cn/termux/termux-main/ stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://mirror.sjtu.edu.cn/termux/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.42.4
Android version:
14
Kernel build information:
Linux localhost 6.1.43-android14-11-abS926NKSU2AXE4 #1 SMP PREEMPT Tue May 28 05:26:39 UTC 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S926N
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.x11 versionCode:14
com.termux.api versionCode:51
```

### PR DESCRIPTION
**Pull request by twaik**
Fixes #19613
Fixes #20671 

It is a patch update improving performance by setting XCB video output as default.

I will merge it in 72 hours if no one minds.
Or anyone else can merge it earlier.

### CODE REVIEW

**Review by TomJo2000 — APPROVED** [review]
Would something similar be sensible for `mpv-x` as well, or does that already default to XCB?

**Comment by twaik** [comment]
TBH I have no idea. I did not dive deep to mpv sources.

**Comment by TomJo2000** [comment]
Gonna look into it on my own time then.

**Comment by TomJo2000** [comment]
- I'd wager this issue is also related.
resolves #20671

**Review by truboxl — APPROVED** [review]

**Pull request merged**
