### PR TITLE
redis: use TCSANOW instead of TCSAFLUSH

### PR DESCRIPTION
**Pull request by xeffyr**
Fix for https://github.com/termux/termux-packages/issues/2783

screenshot_20180828-185118_termux

### CODE REVIEW

**Comment by fornwall** [comment]
Thanks! I bumped the revision to 4.0.11-1 and pushed to updated package to the apt repo.

**Comment by fornwall** [comment]
@xeffyr Do you have a reference of why this fixes the issue? I guess the [seccomp filter in Android 8.0] (https://android-developers.googleblog.com/2017/07/seccomp-filter-in-android-o.html) is the reason?

**Comment by xeffyr** [comment]
I'm not sure that this is related to seccomp, tcsaflush/tcsanow is just a numbers passed to tcsetattr(). Maybe something in bionic.

**Comment by xeffyr** [comment]
I guess denies here caused by SELinux:
```
<36>[ 3075.023654] type=1400 audit(1535474589.754:82): avc: denied { ioctl } for pid=6148 comm="test" path="/dev/pts/1" dev="devpts" ino=4 ioctlcmd=5404 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:untrusted_app_all_devpts:s0:c512,c768 tclass=chr_file permissive=0
```

**Pull request merged**
