### PR TITLE
Make has(android/termux) return true in neovim/vim

### LINKED ISSUE #2346: has('android') should return v:true in vim and neovim
You can pretty much determinate the platform by using `has('mac')`, `has('win32')` and such but since there is no such feature as `android` (or `has('termux')`), it returns `v:false` under Termux. I think this should be fixed.

### PR DESCRIPTION
**Pull request by shadmansaleh**
closes #2346

### CODE REVIEW

**Comment by Grimler91** [comment]
Please set `TERMUX_PKG_REVISION=1` as well, so that apt detects the updated package as newer than the current one

**Comment by shadmansaleh** [comment]
> Please set TERMUX_PKG_REVISION=1 as well

I was just doing that.
I did a early pr to see if it builds well . I've tested the artifact it works correctly .

**Comment by shadmansaleh** [comment]
@Grimler91 do you think [stylua](https://github.com/JohnnyMorganz/StyLua) makes sence in termux ? It's a lua formatter . I have a [working build](https://github.com/shadmansaleh/termux-packages/pull/13) of it. If it makes sense to be included . I can submit a pr.

**Comment by Grimler91** [comment]
@shadmansaleh I have no objections against it, feel free to open a PR. It is great that you have marked yourself as maintainer, none of us here really use lua so the lua packages have not really been given any attention.

Please document, with a comment next to TERMUX_PKG_BLACKLISTED_ARCHES, what the issue seem to be for i686 and x86_64 as well

**Comment by shadmansaleh** [comment]
> Please document, with a comment next to TERMUX_PKG_BLACKLISTED_ARCHES, what the issue seem to be for i686 and x86_64 as well

There's no issue . I was building it for myself since I have only arm & aarch64 devices I avoided building for those arches .

I've opened #7546

**Pull request merged**
