### PR TITLE
chore(main/openjdk-21): add rule to fetch only stable tags during auto-update

### LINKED ISSUE #22029: Auto update failing for openjdk-21
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [openjdk-21](https://github.com/termux/termux-packages/blob/e13177845bc79f6b7aabf63b7a5375daad1c44d7/packages/openjdk-21) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating openjdk-21 [Current version: 21.0.5]
INFO: package being updated to 21.0.6.
Downloading https://github.com/openjdk/jdk21u/archive/refs/tags/jdk-21.0.6-ga.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

openjdk-21: failed to calculate the new checksum
Already up to date.
ERROR: failed to update checksum.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-10-30 12:26:53 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/11592849407">11592849407</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by twaik**
Fixes #22029.

I will merge it in 72 hours if no objections or after it gets 2+ approves.

### CODE REVIEW

**Comment by truboxl** [comment]
Remove your [no ci]

**Comment by twaik** [comment]
But in this case it will trigger package rebuild.

**Comment by truboxl** [comment]
It also checks auto update is working or not

**Comment by twaik** [comment]
Oh, right.

**Comment by truboxl** [comment]
https://github.com/termux/termux-packages/actions/runs/11681126796/job/32525538078?pr=22100#step:4:110

**Review by truboxl — APPROVED** [review]
Auto update works
Can merge without revbump and put back [no ci]

**Comment by twaik** [comment]
I though upload action will throw error in the case if version already exists in repos. I had problems with this before.

**Comment by truboxl** [comment]
I fixed the bug. Please use `%ci:no-build` moving forward. I also moved auto update function to the middle top.

**Pull request merged**
