### PR TITLE
Add package oleo

### PR DESCRIPTION
**Pull request by Wetitpig**
Oleo is a GNU spreadsheet program. It is unique in Termux and suits all those who need command line spreadsheet programs.

### CODE REVIEW

**Comment by Wetitpig** [comment]
The html file is unnecessary for manpage

**Comment by Wetitpig** [comment]
Oleo to SC is just like Nano to VI. Both are spreadsheets, suited for different kinds of users.

**Comment by Wetitpig** [comment]
sc-im, sc, oleo are spreadsheets, just like vim, vi, nano are text editors.

**Comment by sdrausty** [comment]
+1 looks like a good addition to Termux Packages.  Thank you @Wetitpig

**Comment by xeffyr** [comment]
Implemented in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install oleo
```

**Pull request closed without merging**
