### PR TITLE
feat: bump duckdb version

### PR DESCRIPTION
**Pull request by Mause**

### CODE REVIEW

**Comment by 2096779623** [comment]
Why not use Release?
CC @xtkoba

**Comment by Mause** [comment]
> Why not use Release? CC @xtkoba

I'm not sure what you're asking sorry, can you expand?

**Comment by 2096779623** [comment]
> > Why not use Release? CC @xtkoba
> 
> I'm not sure what you're asking sorry, can you expand?

TERMUX_PKG_SRCURL can be changed to https://github.com/duckdb/duckdb/archive/refs/tags/v0.4.0.tar.gz and enable automatic updates, but I don't know why xtkoba doesn't.

**Comment by Mause** [comment]
> > > Why not use Release? CC @xtkoba
> > 
> > 
> > I'm not sure what you're asking sorry, can you expand?
> 
> `TERMUX_PKG_SRCURL` can be changed to `https://github.com/duckdb/duckdb/archive/refs/tags/v0.4.0.tar.gz` and enable automatic updates, but I don't know why xtkoba doesn't.

I explained this already in the comment in the build script - the version doesn't get populated using that method

**Comment by 2096779623** [comment]
> > > > Why not use Release? CC @xtkoba
> > > 
> > > 
> > > I'm not sure what you're asking sorry, can you expand?
> > 
> > 
> > `TERMUX_PKG_SRCURL` can be changed to `https://github.com/duckdb/duckdb/archive/refs/tags/v0.4.0.tar.gz` and enable automatic updates, but I don't know why xtkoba doesn't.
> 
> I explained this already in the comment in the build script - the version doesn't get populated using that method

oh sorry i didn't see it.

**Pull request merged**
