### PR TITLE
Bump Radare2 Version From 5.2.1 to 5.3.1

### PR DESCRIPTION
**Pull request by apkunpacker**

### CODE REVIEW

**Review by suhan-paradkar — COMMENTED** [review]
The patches need to be updated

**Comment by trufae** [comment]
For 5.4 all those patches will go away https://github.com/radareorg/radare2/pull/18841

**Comment by xeffyr** [comment]
Then remove patch which is no longer necessary.

**Comment by trufae** [comment]
Should be safe to remove all the patches for the upcoming 5.4.0. But for packaging 5.3.1 you can pick one of those two options:

* Remove the libr-core-cconfig.c.patch

or

* Update the patch to make it work with this one:

```
$ base64 < libr-core-cconfig.c.patch
ZGlmZiAtcnUgcmFkYXJlMi01LjMuMS5vcmlnL2xpYnIvY29yZS9jY29uZmlnLmMgcmFkYXJlMi01LjMuMS9saWJyL2NvcmUvY2NvbmZpZy5jCi0tLSByYWRhcmUyLTUuMy4xLm9yaWcvbGlici9jb3JlL2Njb25maWcuYwkyMDIxLTA2LTIyIDEzOjMwOjM5LjAwMDAwMDAwMCArMDIwMAorKysgcmFkYXJlMi01LjMuMS9saWJyL2NvcmUvY2NvbmZpZy5jCTIwMjEtMDYtMjIgMTM6MzE6MzEuMDAwMDAwMDAwICswMjAwCkBAIC0zMTMwLDcgKzMxMzAsNyBAQAogCQljaGFyICpoID0gcl9zeXNfZ2V0ZW52IChSX1NZU19IT01FKTsKIAkJaWYgKGgpIHsKIAkJCWlmICghc3RyY21wIChoLCAiLyIpKSB7Ci0JCQkJcl9zeXNfc2V0ZW52IChSX1NZU19IT01FLCAiL2RhdGEvbG9jYWwvdG1wIik7CisJCQkJcl9zeXNfc2V0ZW52IChSX1NZU19IT01FLCAiQFRFUk1VWF9IT01FQCIpOwogCQkJfQogCQkJZnJlZSAoaCk7CiAJCX0KQEAgLTM1NzEsNyArMzU3MSw3IEBACiAJCWZyZWUgKHBhdGgpOwogCX0KIAlTRVRDQiAoImRpci5zb3VyY2UiLCAiIiwgJmNiX2RpcnNyYywgIlBhdGggdG8gZmluZCBzb3VyY2UgZmlsZXMiKTsKLQlTRVRQUkVGICgiZGlyLnR5cGVzIiwgIi91c3IvaW5jbHVkZSIsICJEZWZhdWx0IGNvbG9uLXNlcGFyYXRlZCBsaXN0IG9mIHBhdGhzIHRvIGZpbmQgQyBoZWFkZXJzIHRvIGNwYXJzZSB0eXBlcyIpOworIAlTRVRQUkVGICgiZGlyLnR5cGVzIiwgIkBURVJNVVhfUFJFRklYQC9pbmNsdWRlIiwgIkRlZmF1bHQgcGF0aCB0byBsb29rIGZvciBjcGFyc2UgdHlwZSBmaWxlcyIpOwogCVNFVFBSRUYgKCJkaXIubGlicyIsICIiLCAiU3BlY2lmeSBwYXRoIHRvIGZpbmQgbGlicmFyaWVzIHRvIGxvYWQgd2hlbiBiaW4ubGlicz10cnVlIik7CiAJcCA9IHJfc3lzX2dldGVudiAoUl9TWVNfSE9NRSk7CiAJU0VUQ0IgKCJkaXIuaG9tZSIsIHJfc3RyX2dldF9mYWlsIChwLCAiLyIpLCAmY2JfZGlyaG9tZSwgIlBhdGggZm9yIHRoZSBob21lIGRpcmVjdG9yeSIpOwpAQCAtMzU3OSwxMSArMzU3OSw3IEBACiAJcCA9IHJfc3lzX2dldGVudiAoUl9TWVNfVE1QKTsKIAlTRVRDQiAoImRpci50bXAiLCByX3N0cl9nZXQgKHApLCAmY2JfZGlydG1wLCAiUGF0aCBvZiB0aGUgdG1wIGRpcmVjdG9yeSIpOwogCWZyZWUgKHApOwotI2lmIF9fQU5EUk9JRF9fCi0JU0VUQ0IgKCJkaXIucHJvamVjdHMiLCAiL2RhdGEvZGF0YS9vcmcucmFkYXJlLnJhZGFyZTJpbnN0YWxsZXIvcmFkYXJlMi9wcm9qZWN0cyIsICZjYl9kaXJfcHJvamVjdHMsICJEZWZhdWx0IHBhdGggZm9yIHByb2plY3RzIik7Ci0jZWxzZQogCVNFVENCICgiZGlyLnByb2plY3RzIiwgUl9KT0lOXzJfUEFUSFMgKCJ+IiwgUjJfSE9NRV9QUk9KRUNUUyksICZjYl9kaXJfcHJvamVjdHMsICJEZWZhdWx0IHBhdGggZm9yIHByb2plY3RzIik7Ci0jZW5kaWYKIAlTRVRDQiAoImRpci56aWducyIsIFJfSk9JTl8yX1BBVEhTICgifiIsIFIyX0hPTUVfWklHTlMpLCAmY2JfZGlyemlnbnMsICJEZWZhdWx0IHBhdGggZm9yIHppZ25hdHVyZXMgKHNlZSB6byBjb21tYW5kKSIpOwogCVNFVFBSRUYgKCJzdGFjay5yZWciLCAiU1AiLCAiV2hpY2ggcmVnaXN0ZXIgdG8gdXNlIGFzIHN0YWNrIHBvaW50ZXIgaW4gdGhlIHZpc3VhbCBkZWJ1ZyIpOwogCVNFVEJQUkVGICgic3RhY2suYnl0ZXMiLCAidHJ1ZSIsICJTaG93IGJ5dGVzIGluc3RlYWQgb2Ygd29yZHMgaW4gc3RhY2siKTsKQEAgLTM3MjMsOSArMzcxOSw4IEBACiAjZWxzZQogCWlmIChyX2ZpbGVfZXhpc3RzICgiL3Vzci9iaW4vb3BlblVSTCIpKSB7IC8vIGlPUyBlcmljYXV0aWxzCiAJCXJfY29uZmlnX3NldCAoY2ZnLCAiaHR0cC5icm93c2VyIiwgIi91c3IvYmluL29wZW5VUkwiKTsKLQl9IGVsc2UgaWYgKHJfZmlsZV9leGlzdHMgKCIvc3lzdGVtL2Jpbi90b29sYm94IikpIHsKLQkJcl9jb25maWdfc2V0IChjZmcsICJodHRwLmJyb3dzZXIiLAotCQkJCSJMRF9MSUJSQVJZX1BBVEg9L3N5c3RlbS9saWIgYW0gc3RhcnQgLWEgYW5kcm9pZC5pbnRlbnQuYWN0aW9uLlZJRVcgLWQiKTsKKwl9IGVsc2UgaWYgKHJfZmlsZV9leGlzdHMgKCJAVEVSTVVYX1BSRUZJWEAvYmluL3Rlcm11eC1vcGVuIikpIHsKKwkJcl9jb25maWdfc2V0IChjZmcsICJodHRwLmJyb3dzZXIiLCAiQFRFUk1VWF9QUkVGSVhAL2Jpbi90ZXJtdXgtb3BlbiIpOwogCX0gZWxzZSBpZiAocl9maWxlX2V4aXN0cyAoIi91c3IvYmluL3hkZy1vcGVuIikpIHsKIAkJcl9jb25maWdfc2V0IChjZmcsICJodHRwLmJyb3dzZXIiLCAieGRnLW9wZW4iKTsKIAl9IGVsc2UgaWYgKHJfZmlsZV9leGlzdHMgKCIvdXNyL2Jpbi9vcGVuIikpIHsKQEAgLTM3NDUsOCArMzc0MCw2IEBACiAJCVNFVFBSRUYgKCJodHRwLnJvb3QiLCB3d3dyb290LCAiaHR0cCByb290IGRpcmVjdG9yeSIpOwogCQlmcmVlICh3d3dyb290KTsKIAl9Ci0jZWxpZiBfX0FORFJPSURfXwotCVNFVFBSRUYgKCJodHRwLnJvb3QiLCAiL2RhdGEvZGF0YS9vcmcucmFkYXJlLnJhZGFyZTJpbnN0YWxsZXIvd3d3IiwgImh0dHAgcm9vdCBkaXJlY3RvcnkiKTsKICNlbHNlCiAJU0VUUFJFRiAoImh0dHAucm9vdCIsIFIyX1dXV1JPT1QsICJodHRwIHJvb3QgZGlyZWN0b3J5Iik7CiAjZW5kaWYKT25seSBpbiByYWRhcmUyLTUuMy4xL2xpYnIvY29yZTogY2NvbmZpZy5jLm9yaWcKT25seSBpbiByYWRhcmUyLTUuMy4xL2xpYnIvY29yZTogY2NvbmZpZy5jLnJlago=
$
```

**Pull request merged**
