### PR TITLE
bump(main/boost): 1.83.0

### PR DESCRIPTION
**Pull request by twaik**
@finagolfin should I use auto-update for the base system library like boost?

### CODE REVIEW

**Comment by licy183** [comment]
I don't think you should enable its update. Every time libboost is updated, its revdeps should be rebuilt too, because the soversion of libboost changes.

**Comment by twaik** [comment]
Should I rebuild all revdeps too?

**Comment by licy183** [comment]
Yes. FYI: https://github.com/termux/termux-packages/pull/16223

**Comment by twaik** [comment]
Ok. Current revdeps: 
```
boost-headers
  quassel
  pulseeffects
  inkscape
  hugin
  vera
  tome2
  tizonia
  solidity
  ravencoin
  qrsspig
  povray
  osmium-tool
  osm2pgsql
  openscad
  openfoam
  ncmpcpp
  monero
  mkvtoolnix
  libupscaledb
  libtorrent-rasterbar
  libtins
  librime
  libpagmo
  libc++utilities
  lgogdownloader
  ledger
  innoextract
  i2pd
  boost-static
```

Should I revbump them in the same PR? Or should do that separately?

**Comment by licy183** [comment]
Revbumping all of them in the same PR will reach out the limit of CI time. You can revbump some of them in the same PR...

**Pull request closed without merging**
