### PR TITLE
Libtorrent : 

### PR DESCRIPTION
**Pull request by kcubeterm**
#5205

### CODE REVIEW

**Comment by xeffyr** [comment]
configure script patches are needed as this package does not support cross-compilation:
```
 configure: error: in `/home/builder/.termux-build/libtorrent/build':
configure: error: cannot run test program while cross compiling
See `config.log' for more details
```

**Comment by kcubeterm** [comment]
@xeffyr if this time ,it fails,then i will try to patch configure.

**Comment by xeffyr** [comment]
@kcubeterm Do not specify `--host`! That's already done in https://github.com/termux/termux-packages/blob/master/scripts/build/configure/termux_step_configure_autotools.sh and you specify it incorrectly anyway.

**Comment by xeffyr** [comment]
Can be fixed by `--enable-aligned=true`.

**Comment by xeffyr** [comment]
Now lots of C++ errors:
```
In file included from /home/builder/.termux-build/libtorrent/src/src/torrent/peer/client_list.cc:40:
In file included from /home/builder/.termux-build/libtorrent/src/rak/string_manip.h:47:
In file included from /home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/random:1638:
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:314:9: error: no member named 'signbit' in the global namespace; did you mean '__signbit'?
using ::signbit;
      ~~^
/usr/include/bits/mathcalls-helper-functions.h:25:20: note: '__signbit' declared here
__MATHDECL_1 (int, __signbit,, (_Mdouble_ __value))
                   ^
In file included from /home/builder/.termux-build/libtorrent/src/src/torrent/peer/client_list.cc:40:
In file included from /home/builder/.termux-build/libtorrent/src/rak/string_manip.h:47:
In file included from /home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/random:1638:
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:315:9: error: no member named 'fpclassify' in the global namespace; did you mean '__fpclassify'?
using ::fpclassify;
      ~~^
/usr/include/bits/mathcalls-helper-functions.h:21:20: note: '__fpclassify' declared here
__MATHDECL_1 (int, __fpclassify,, (_Mdouble_ __value))
                   ^
In file included from /home/builder/.termux-build/libtorrent/src/src/torrent/peer/client_list.cc:40:
In file included from /home/builder/.termux-build/libtorrent/src/rak/string_manip.h:47:
In file included from /home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/random:1638:
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:316:9: error: no member named 'isfinite' in the global namespace
using ::isfinite;
      ~~^
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:317:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:318:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:319:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:320:7: error: no member named 'isgreater' in the global namespace; did you mean '::std::greater'?
using ::isgreater;
      ^~
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/functional:728:29: note: '::std::greater' declared here
struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                            ^
In file included from /home/builder/.termux-build/libtorrent/src/src/torrent/peer/client_list.cc:40:
In file included from /home/builder/.termux-build/libtorrent/src/rak/string_manip.h:47:
In file included from /home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/random:1638:
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:321:7: error: no member named 'isgreaterequal' in the global namespace; did you mean
      '::std::greater_equal'?
using ::isgreaterequal;
      ^~
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/functional:757:29: note: '::std::greater_equal' declared here
struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                            ^
In file included from /home/builder/.termux-build/libtorrent/src/src/torrent/peer/client_list.cc:40:
In file included from /home/builder/.termux-build/libtorrent/src/rak/string_manip.h:47:
In file included from /home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/random:1638:
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:322:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:323:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:324:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/home/builder/.termux-build/_cache/android-r20-api-24-v3/bin/../sysroot/usr/include/c++/v1/cmath:326:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
```

**Comment by kcubeterm** [comment]
I hope it will work.

**Pull request merged**
