### PR TITLE
new package: distant

### LINKED ISSUE #15604: [Package]:  distant
### Why do you want to add this package to Termux?

Hi,

I would like to request the addition of the distant package to Termux. Distant is a binary tool that allows Neovim users to edit files remotely, which is very useful for remote project development on Android devices. Unfortunately, the distant binary is not currently available in Termux, which limits its usefulness for Termux users who use Neovim for their development work.

By adding the distant package to Termux, users would be able to take advantage of remote project development features and use apps that are not available for aarch64 but only for x86_64 (`nvidia`, `conda` ...). This would greatly benefit the Termux community of Neovim users.

Thank you for considering this request.

Best regards,

### Home page URL

https://github.com/chipsenkbeil/distant

### Source code URL

https://github.com/chipsenkbeil/distant

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

<details>
<summary> Specifically, I have encountered issues.</summary>

```
   Compiling num_cpus v1.15.0
   Compiling termios v0.2.2
   Compiling serial-core v0.4.0
error[E0432]: unresolved import `os::target`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:116:15
    |
116 | pub use ::os::target::{cc_t,speed_t,tcflag_t}; // types
    |               ^^^^^^ could not find `target` in `os`

error[E0432]: unresolved import `os::target`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:117:15
    |
117 | pub use ::os::target::{VEOF,VEOL,VERASE,VINTR,VKILL,VMIN,VQUIT,VSTART,VSTOP,VSUSP,VTIME}; // c_cc subscripts
    |               ^^^^^^ could not find `target` in `os`

error[E0432]: unresolved import `os::target`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:118:15
    |
118 | pub use ::os::target::{BRKINT,ICRNL,IGNBRK,IGNCR,IGNPAR,INLCR,INPCK,ISTRIP,IXANY,IXOFF,IXON,PARMRK}; // input modes
    |               ^^^^^^ could not find `target` in `os`

error[E0432]: unresolved import `os::target`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:119:15
    |
119 | pub use ::os::target::{OPOST,ONLCR,OCRNL,TAB3,ONOCR,ONLRET}; // output modes
    |               ^^^^^^ could not find `target` in `os`

error[E0432]: unresolved import `os::target`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:120:15
    |
120 | pub use ::os::target::{B0,B50,B75,B110,B134,B150,B200,B300,B600,B1200,B1800,B2400,B4800,B9600,B19200,B38400}; // baud rate selection
    |               ^^^^^^ could not find `target` in `os`

error[E0432]: unresolved import `os::target`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:121:15
    |
121 | pub use ::os::target::{CSIZE,CS5,CS6,CS7,CS8,CSTOPB,CREAD,PARENB,PARODD,HUPCL,CLOCAL}; // control modes
    |               ^^^^^^ could not find `target` in `os`

error[E0432]: unresolved import `os::target`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:122:15
    |
122 | pub use ::os::target::{ECHO,ECHOE,ECHOK,ECHONL,ICANON,IEXTEN,ISIG,NOFLSH,TOSTOP}; // local modes
    |               ^^^^^^ could not find `target` in `os`

error[E0432]: unresolved import `os::target`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:123:15
    |
123 | pub use ::os::target::{TCSANOW,TCSADRAIN,TCSAFLUSH}; // attribute selection
    |               ^^^^^^ could not find `target` in `os`

error[E0432]: unresolved import `os::target`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:124:15
    |
124 | pub use ::os::target::{TCIFLUSH,TCIOFLUSH,TCOFLUSH,TCIOFF,TCION,TCOOFF,TCOON}; // line control
    |               ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
 --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:9:55
  |
9 |     pub fn tcgetattr(fd: c_int, termios_p: *mut ::os::target::termios) -> c_int;
  |                                                       ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:10:82
   |
10 |     pub fn tcsetattr(fd: c_int, optional_actions: c_int, termios_p: *const ::os::target::termios) -> c_int;
   |                                                                                  ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:15:44
   |
15 |     pub fn cfmakeraw(termios_p: *mut ::os::target::termios);
   |                                            ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:16:48
   |
16 |     pub fn cfgetispeed(termios_p: *const ::os::target::termios) -> ::os::target::speed_t;
   |                                                ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:16:74
   |
16 |     pub fn cfgetispeed(termios_p: *const ::os::target::termios) -> ::os::target::speed_t;
   |                                                                          ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:17:48
   |
17 |     pub fn cfgetospeed(termios_p: *const ::os::target::termios) -> ::os::target::speed_t;
   |                                                ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:17:74
   |
17 |     pub fn cfgetospeed(termios_p: *const ::os::target::termios) -> ::os::target::speed_t;
   |                                                                          ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:18:46
   |
18 |     pub fn cfsetispeed(termios_p: *mut ::os::target::termios, speed: ::os::target::speed_t) -> c_int;
   |                                              ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:18:76
   |
18 |     pub fn cfsetispeed(termios_p: *mut ::os::target::termios, speed: ::os::target::speed_t) -> c_int;
   |                                                                            ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:19:46
   |
19 |     pub fn cfsetospeed(termios_p: *mut ::os::target::termios, speed: ::os::target::speed_t) -> c_int;
   |                                              ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:19:76
   |
19 |     pub fn cfsetospeed(termios_p: *mut ::os::target::termios, speed: ::os::target::speed_t) -> c_int;
   |                                                                            ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:20:45
   |
20 |     pub fn cfsetspeed(termios_p: *mut ::os::target::termios, speed: ::os::target::speed_t) -> c_int;
   |                                             ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/ffi.rs:20:75
   |
20 |     pub fn cfsetspeed(termios_p: *mut ::os::target::termios, speed: ::os::target::speed_t) -> c_int;
   |                                                                           ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:167:18
    |
167 |     inner: ::os::target::termios
    |                  ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:183:31
    |
183 |     fn inner(&self) -> &::os::target::termios {
    |                               ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:187:43
    |
187 |     fn inner_mut(&mut self) -> &mut ::os::target::termios {
    |                                           ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:193:25
    |
193 |     type Target = ::os::target::termios;
    |                         ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:195:31
    |
195 |     fn deref(&self) -> &::os::target::termios {
    |                               ^^^^^^ could not find `target` in `os`

error[E0433]: failed to resolve: could not find `target` in `os`
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/termios-0.2.2/src/lib.rs:201:43
    |
201 |     fn deref_mut(&mut self) -> &mut ::os::target::termios {
    |                                           ^^^^^^ could not find `target` in `os`

   Compiling grep-matcher v0.1.6
Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `termios` due to 28 previous errors
warning: build failed, waiting for other jobs to finish...
^C  Building [=========>               ] 163/379: openssl-sys...
~ $ cargo install distant --target=
```

</details>

### ISSUE ON chipsenkbeil/distant

https://github.com/chipsenkbeil/distant/issues/163

### PR DESCRIPTION
**Pull request by xtkoba**
Closes #15604.

### CODE REVIEW

**Comment by 2096779623** [comment]
```
~ $ distant generate completion --help
Usage: distant generate completion [OPTIONS] <SHELL>

Arguments:
  <SHELL>  Specific shell to target for the generated output [possible values: bash, elvish, fish, powershell, zsh]

Options:
      --file <FILE>            If specified, will output to the file at the given path instead of stdout
      --log-level <LOG_LEVEL>  Log level to use throughout the application [possible values: off, error, warn, info, debug, trace]
      --log-file <LOG_FILE>    Path to file to use for logging
  -c, --config <CONFIG_PATH>   Configuration file to load instead of the default paths
  -h, --help                   Print help information
```
It has shell completion, please install it.

**Comment by 2096779623** [comment]
```bash
~ $ distant manager listen
Failed to start manager

Caused by:
    0: Failed to create socket directory "/run"
    1: Read-only file system (os error 30)
```
Looks like there are has some hardcoded paths.

**Comment by chipsenkbeil** [comment]
Hi there, I'd like to add official support for Termux in an upcoming release. Saw this PR with the patches, and want to work to getting [distant](https://github.com/chipsenkbeil/distant) able to compile & run without the extra work. I own some of the libraries, so I can fix those directly, and hopefully upgrade libraries or add patches directly during distant's build to resolve the others.

Is there a good way to test a termux build using Github actions? Ideally, I'd like to both compile and run my test suite (Rust using Cargo). Any recommendations?

cc @xtkoba, @2096779623

**Comment by 2096779623** [comment]
> Is there a good way to test a termux build using Github actions? Ideally, I'd like to both compile and run my test suite (Rust using Cargo). Any recommendations? Tracking issue: [chipsenkbeil/distant#163](https://github.com/chipsenkbeil/distant/issues/163).

Building it in the distant repository is simple, just point `target` to `<arch>-linux-android`, if you want to test this in GitHub actions, you can take a look at [termux-docker](https://github.com/termux/termux-docker), so far it looks like We have not yet made a marketplace package to allow other repositories to run in a simulated termux environment.
My suggestion is to let users test it.

I see someone already mentioned this in our developer group chat: 
https://matrix.to/#/!rrHhKvLYtBVDOISphu:gitter.im/$P0sAX9kzUSxcLWCyVT0w8I7p83e-6I8rtAEgg9hWQbU?via=matrix.org&via=t2bot.io&via=gitter.im

**Pull request merged**
