### PR TITLE
scripts|main/termux-tools: Package manager updates and fixes

### LINKED ISSUE #10778: [Bug]: pkg: line 142: syntax error in expression (error token is "8 9 11 12 13 14 16")
### Problem description

When I try to use <kbd>pkg</kbd> it shows following error:

```
Checking availability of current mirror: bad
Testing the available mirrors:
[*] https://mirror.mwt.me/termux/main: ok
[*] https://termux.sahilister.in/apt/termux-main: ok
[*] https://plug-mirror.rcac.purdue.edu/termux/termux-main: ok
[*] https://termux.mentality.rip/termux-main: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://termux.librehat.com/apt/termux-main: bad
[*] https://termux.astra.in.ua/apt/termux-main: ok
[*] https://packages-cf.termux.org/apt/termux-main: ok
[*] https://dl.kcubeterm.com/termux-main: ok
/data/data/com.termux/files/usr/bin/pkg: line 142: 7
8
9
11
12
13
14
16: syntax error in expression (error token is "8
9
11
12
13
14
16")
```

### What steps will reproduce the bug?

When mirrors aren't updated running `pkg upgrade` or `pkg install [something]` or `pkg update`. I haven't tested anything else.

### What is the expected behavior?

To complete job without error

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=6266
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.kcubeterm.com/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.186-g759c88b6c5dc #1 SMP PREEMPT Wed Jan 12 11:21:08 WIB 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 8 Pro
```

### LINKED ISSUE #10782: [Bug]: pkg is not working anymore
### Problem description

when I try to install or update packages using pkg, it show me the following error:-

/data/data/com.termux/files/usr/bin/pkg: line 197: TERMUX_MAIN_PACKAGE_FORMAT: unbound variable

### Steps to reproduce the behavior.

All I found in the internet is to use apt instead of pkg.

### What is the expected behavior?

It should install or update packages.

### System information

* Termux application version: v0.118
* Android OS version: 9
* Device model: Oppo A1k

### PR DESCRIPTION
**Pull request by agnostic-apollo**
Supersedes #10780

Closes #10782
Closes #10778

If someone wants to test the changes or make suggestions before I merge, let me know.

Also, on-device build users should preferably pull changes from `master` branch for build scripts updates after merger.

### CODE REVIEW

**Comment by Maxython** [comment]
One line of logic doesn't work on pacman based termux ([link](https://github.com/termux/termux-packages/pull/10783/files#diff-afc04ee40a244a5e944e2062606068ba8021a099dcc7c5e064fe067cc7396a14R27)).

**Comment by agnostic-apollo** [comment]
Ah, `dpkg` wouldn't exist. You have `vercmp`, right?

https://archlinux.org/pacman/vercmp.8.html

**Comment by agnostic-apollo** [comment]
So `vercmp` does exist. You can check now.

**Comment by agnostic-apollo** [comment]
You are welcome. And thanks for reporting the `dpkg` issue.

>The only thing I want to say is that in pkg from line 281 to 339 there are a lot of case commands that can be shortened.

Feel free to suggest a way that keeps code readable, the single array wasn't. There is no harm in using a few extra lines to keep code easily understandable. Perhaps two case statements for `$CMD` can be nested under a single `$TERMUX_APP_PACKAGE_MANAGER` case statement, that should reduce `case`/`esac` lines.

**Pull request merged**
