### PR TITLE
pngquant: add package

### LINKED ISSUE #1887: Package Request: pngquant
## Description:
*(taken from pngquant.org)*

***pngquant*** is a command-line utility and a library for lossy compression of PNG images.

The conversion reduces file sizes significantly (often as much as 70%) and preserves full alpha transparency. Generated images are compatible with all web browsers and operating systems.

#### Features
- High-quality palette generation using a combination of vector quantization algorithms.
- Unique adaptive dithering algorithm that adds less noise to images than the standard Floyd-Steinberg.
- Easy to integrate with shell scripts, GUIs and server-side software.
- Fast mode for real-time processing/large numbers of images.

Homepage: https://pngquant.org/
GitHub: https://github.com/pornel/pngquant

## Notes:
*libimagequant* is the only dependency that I am aware of. I am not sure if it is included with *pngquant*'s source. I only recently started using it.

#### libimagequant links:
About page: https://pngquant.org/lib
GitHub: https://github.com/ImageOptim/libimagequant

I read over #1831 & saw that Arch for Termux was referenced. *pngquant* does not appear to be included with it (at least, I didn't find it), so I decided to make this package request.

If I felt that I would have the time soon, I would attempt compiling & create a pull request myself. But I honestly don't know when I would be able to get to it.

Also, there is a GUI Android app available called [Atomize](https://play.google.com/store/apps/details?id=com.wrmndfzzy.atomize), but I would still like to have the command line utility.

I would add the *Package Request* label, but I guess I can't.

**Edit:** I just found the [Termux Create Package](https://github.com/termux/termux-create-package) repo. I may check this out & see if I can create the package myself if it's not too difficult... if I get time to do so.

**Edit:** Made a mistake. *libpng* is required too. Should have known that.

### PR DESCRIPTION
**Pull request by vishalbiswas**
fixes #1887 
Please note that I have globally disabled SSE support (x86), because I don't know anything about SSE.

### CODE REVIEW

**Comment by fornwall** [comment]
Nice - the package is now available for installation!

**Comment by sdrausty** [comment]
@vishalbiswas @fornwall bra jobb! Bra jobb! Tack.

**Comment by sdrausty** [comment]
@ व्हाइटलबिसवास @ फारॉर्नॉल छान काम! छान काम! धन्यवाद.

**Comment by SamSanuch** [comment]
Ohh Hindi?

**Comment by sdrausty** [comment]
Marathi

**Pull request merged**
