### PR TITLE
Initial liblmdb packaging

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
> Uses host compiler:
> https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/Makefile#L21

Also need to change AR?

**Comment by xeffyr** [comment]
Yes, `ar` should be changed too.
```
CC ?= gcc
AR ?= ar
```

**Comment by craigcomstock** [comment]
Ok. I did a similar change locally with docker environment and am now faced with some clang errors. I am investigating:

```
mdb.c:4890:53: error: use of undeclared identifier 'PTHREAD_MUTEX_ROBUST'
                if (!rc) rc = pthread_mutexattr_setrobust(&mattr, PTHREAD_MUTEX_ROBUST);
                                                                  ^
mdb.c:4890:53: error: use of undeclared identifier 'PTHREAD_MUTEX_ROBUST'
                if (!rc) rc = pthread_mutexattr_setrobust(&mattr, PTHREAD_MUTEX_ROBUST);
                                                                  ^
```

**Comment by buttaface** [comment]
Oh yeah, I hit that recently, [see my downstream patch](https://github.com/apple/indexstore-db/pull/61/files#diff-bd2168c511242e78bf16dd6fb964b62a).

**Comment by xeffyr** [comment]
Can be fixed with `-DMDB_USE_ROBUST=0`.

**Comment by craigcomstock** [comment]
Wow. That experience was amazing. Thanks for all the help @xeffyr!

**Pull request merged**
