### PR TITLE
chore(x11/libadwaita): Switch to GNOME Gitlab source URL.

### PR DESCRIPTION
**Pull request by TomJo2000**
Should avoid a repeat of #21803

<details><summary><code>download.gnome.org/sources</code>[...] SRCURL's are also used by an additional 67 packages.</summary>
<p>

```zig
// ~$ rg 'download.gnome.org/sources'
x11-packages/clutter-gtk/build.sh
x11-packages/clutter-gst/build.sh
x11-packages/eog/build.sh
x11-packages/gnumeric/build.sh
x11-packages/gnome-desktop4/build.sh
x11-packages/gnome-font-viewer/build.sh
x11-packages/gcr/build.sh
x11-packages/gtksourceview4/build.sh
x11-packages/libatkmm-1.6/build.sh
x11-packages/gspell/build.sh
x11-packages/gsettings-desktop-schemas/build.sh
x11-packages/gtk2-engines-murrine/build.sh
x11-packages/zenity/build.sh
x11-packages/libwnck/build.sh
x11-packages/gtkmm4/build.sh
x11-packages/rhythmbox/build.sh
x11-packages/pyatspi/build.sh
x11-packages/gtkmm3/build.sh
x11-packages/gtk2/build.sh
x11-packages/gnome-desktop3/build.sh
x11-packages/gtk4/build.sh
x11-packages/libgedit-tepl/build.sh
x11-packages/evince/build.sh
x11-packages/libpeas/build.sh
x11-packages/orca/build.sh
x11-packages/clutter/build.sh
x11-packages/goffice/build.sh
x11-packages/libgedit-amtk/build.sh
x11-packages/libnotify/build.sh
x11-packages/gedit/build.sh
x11-packages/libgtksourceviewmm-3.0/build.sh
x11-packages/gtksourceview3/build.sh
x11-packages/adwaita-icon-theme-legacy/build.sh
x11-packages/glade/build.sh
x11-packages/gtkmm2/build.sh
x11-packages/file-roller/build.sh
x11-packages/libhandy/build.sh
x11-packages/cogl/build.sh
x11-packages/libxml++-2.6/build.sh
x11-packages/libgedit-gtksourceview/build.sh
x11-packages/adwaita-icon-theme/build.sh
x11-packages/gvfs/build.sh
x11-packages/gcr4/build.sh
x11-packages/epiphany/build.sh
packages/graphene/build.sh
packages/json-glib/build.sh
packages/libgedit-gfls/build.sh
packages/gexiv2/build.sh
packages/at-spi2-core/build.sh
packages/libgsf/build.sh
packages/libsigc++-2.0/build.sh
packages/totem-pl-parser/build.sh
packages/libsigc++-3.0/build.sh
packages/gobject-introspection/build.sh
packages/pygobject/build.sh
packages/libgxps/build.sh
packages/libsoup/build.sh
packages/libxml2/build.sh
packages/libglibmm-2.68/build.sh
packages/valac/build.sh
packages/libpangomm-1.4/build.sh
packages/gdk-pixbuf/build.sh
packages/libpangomm-2.48/build.sh
packages/libsoup3/build.sh
packages/glib/build.sh
packages/libsecret/build.sh
packages/libglibmm-2.4/build.sh
```

</p>
</details>

I'm not entirely sure if #21803 was caused by Adwaita's specific release process,
or if it could happen for any package from `download.gnome.org/sources`.

CC: @Biswa96

### CODE REVIEW

**Review by twaik — APPROVED** [review]

**Comment by TomJo2000** [comment]
@twaik do you happen to know if this problem is Adwaita specific, or are tarballs for all projects hosted on `download.gnome.org` delayed compared to the release tags on the GNOME gitlab?

**Comment by twaik** [comment]
Idk. It just happens for some packages if auto-updater checks newest available version using repology, it is not adwaita specific.

**Comment by TomJo2000** [comment]
Which is being used implicitly since the source URL is neither from GitHub nor Gitlab.

**Comment by TomJo2000** [comment]
Sidenote, does the `scripts/updates/api/termux_gitlab_api_get_tag.sh` update method only apply to the main GitLab instance or does it also work for project Gitlabs.
E.g gnome.gitlab.com, free desktop.gitlab.com, etc.

**Comment by TomJo2000** [comment]
I think we can safely assume it's an isolated problem until proven otherwise.

**Pull request merged**
