### PR TITLE
upgpkg(main/samba): from 4.14.13 to 4.16.2

### PR DESCRIPTION
**Pull request by tjhexf**

### CODE REVIEW

**Comment by tjhexf** [comment]
I'd love some help here. All the patches related to changing the heimdal TMPdir seem to not apply anymore, as the patched code does not exist anymore. However, i can't find the code anywhere else, either it has been completely rewritten or just doesn't exist at all now

**Comment by buttaface** [comment]
@thunder-coding, you last updated this, any input?

**Comment by tjhexf** [comment]
Oops, just realized I've put the wrong version in the commit message. Will fix it after work, aswell as beggining to re-do the patches that don't apply anymore. It seems that patch was only re-assigning the /tmp directory to the right place, so it should just be a job of changing the new references to /tmp to @TERMUX_PREFIX@/tmp

**Comment by tjhexf** [comment]
another one working, now onto the 0005 patch

**Comment by tjhexf** [comment]
File "/home/builder/.termux-build/samba/src/wscript_configure_embedded_heimdal", line 3
    def check_system_heimdal_binary(name):
    ^
IndentationError: expected an indented block

so close... yet so far. What does this even mean? It seems to be properly indented, there's no need for an indentation there. I did not even change the code from the original. Ugh. I'll try to patch that whole function out tommorrow, seems to not be necessary as we're not using the system heimdal, we're using the patched provided one we built in the build process

**Comment by tjhexf** [comment]
File "/home/builder/.termux-build/samba/src/wscript_configure_embedded_heimdal", line 3
    def check_system_heimdal_binary(name):
    ^
IndentationError: expected an indented block

what does that even mean, i can't see any indentation problem. Ugh.

**Comment by tjhexf** [comment]
@thunder-coding I'd appreciate some help here, please

**Comment by tjhexf** [comment]
this might have been a dumb oversight of mine.

**Comment by tjhexf** [comment]
finally. All patches are working. Now, just need to debug this, which i have no idea yet how it works or what means:

Checking for gnutls fips mode support: UNKNOWN

**Comment by thunder-coding** [comment]
Everything seems good, you now need to re-generate the cross-answers.txt file which is in build.sh:31. If you want you can just leave this PR, I'll do it myself :)

Also squash your commits, and ammend the message to some meaningful thing than multiple "fix this"es.


Everything else seems good though

**Comment by tjhexf** [comment]
yes yes, thanks. I'll squash the commits, that was the final step after fixing up everything :)
the commit messages for now are just temporary, as i was too lazy to come up with something insightful as i tried and tested, rinse and repeat
i'll try to regen the cross-answers file, thanks!

**Comment by tjhexf** [comment]
One question, do i squash it all, and only leave the commit message as this PR's title?

**Comment by 2096779623** [comment]
> One question, do i squash it all, and only leave the commit message as this PR's title?

Yes.

**Comment by tjhexf** [comment]
Yep, this is now one of those errors which i don't really know what to do. Would love some help

**Comment by 2096779623** [comment]
> Yep, this is now one of those errors which i don't really know what to do. Would love some help

https://rt.cpan.org/Public/Bug/Display.html?id=131313

**Comment by tjhexf** [comment]
> > Yep, this is now one of those errors which i don't really know what to do. Would love some help
> 
> https://rt.cpan.org/Public/Bug/Display.html?id=131313

Oh, that was quick. Thank you, I'll try those

**Comment by tjhexf** [comment]
ok, now i really don't know what to do

**Comment by 2096779623** [comment]
@Grimler91 You forgot `-y`!

**Comment by Grimler91** [comment]
Indeed :)

**Pull request closed without merging**
