### PR TITLE
New package:ovmf

### PR DESCRIPTION
**Pull request by ifurther**
#5730

### CODE REVIEW

**Comment by ifurther** [comment]
In build.sh file has one src is git link, but I don't know how do to fix sha256sum variable.

**Comment by Grimler91** [comment]
Mixing archives + git is not supported, but it should be possible to specify`https://github.com/tianocore/edk2-platforms/archive/69009e5b91a70b6fc15cdf4bc410256052cb5752.tar.gz` as SRCURL

**Comment by xeffyr** [comment]
This is a subject for full host-based compilation. Use prebuilt binaries instead and package them into .deb file.

**Comment by ifurther** [comment]
How could I do ?

**Comment by xeffyr** [comment]
@ifurther Download from https://www.kraxel.org/repos/jenkins/edk2/, extract and copy files to Termux prefix.

**Comment by Grimler91** [comment]
@xeffyr if pre-compiled binaries are to be packaged then I think ovmf should go into unstable-packages. We do that for very few packages, and I think it would be good to keep it that way as pre-compiled binaries makes our build system less transparent

**Comment by xeffyr** [comment]
@Grimler91 OVMF is just UEFI firmware blob for use with QEMU which already has bunch of prebuilt firmware.

**Comment by oofnikj** [comment]
Amazing! Thank you both @xeffyr @ifurther, record turnaround

**Pull request merged**
