### PR TITLE
Add new package: lsd

### PR DESCRIPTION
**Pull request by kcubeterm**
Next generation ls command

### CODE REVIEW

**Comment by xeffyr** [comment]
> Next generation ls command

Then what's generation of ls provides package `exa` ?

**Comment by kcubeterm** [comment]
Next gen because it have themes and icon features like nnn

**Comment by landfillbaby** [comment]
note: the icons don't work as termux doesn't include the required fonts. doesn't make it unusable though

**Comment by kcubeterm** [comment]
Working on that, it requires nerd font , will add doc soon.

**Pull request merged**
