### PR TITLE
New package: Csh

### PR DESCRIPTION
**Pull request by Krush206**
https://github.com/termux/termux-packages/pull/12122#issuecomment-1259943273
Patch file is now present.

### CODE REVIEW

**Comment by Krush206** [comment]
It's complaining of `<bsd/vis.h>` missing, even though I set `libbsd` as dependency.

**Comment by Krush206** [comment]
Appending CFLAGS, CPPFLAGS and LDFLAGS results in segmentation fault (on armv7; don't know for other architectures), hence I disabled appending.
As I see in `CONTRIBUTING.md`, CFLAGS, CPPFLAGS and LDFLAGS shouldn't be overriden, but is that a strict rule? Are there no options?

**Comment by Krush206** [comment]
Thanks, `-0s` helps not to cause segmentation fault. The bot still fails to find the includes, though.

**Comment by Hoshiryu5646** [comment]
i need help

**Comment by xtkoba** [comment]
Looks like abandoned. @Krush206 Still work in progress?

**Comment by Krush206** [comment]
Was hoping for some help. Will try once again.

**Comment by xtkoba** [comment]
Please describe the problem you want to solve.

**Comment by Krush206** [comment]
Already figured out. The Makefile should have `-I` and `-L` pointing to `/data/data/com.termux/files/usr`.

The errors are different, but I'll figure them out.

**Comment by Krush206** [comment]
Looks like `setpwent()` and `getpwent()` aren't part of Bionic, but I found [this](https://gitlab.com/ataraxialinux/bionic-libc-extras/-/blob/master/src/getpwent.c).

Should I omit these functions or is it okay to include them?

**Comment by Krush206** [comment]
I have these functions omitted. They're only used to obtain all users in the system after a tilde followed by Ctrl+D [`~^D`].

**Comment by Krush206** [comment]
How are we supposed to install manpages? Can I pass `mkdir` in the Makefile?

**Comment by Grimler91** [comment]
> How are we supposed to install manpages? Can I pass `mkdir` in the Makefile?

That is fine, put it in a `termux_step_post_make_install()` function

**Review by PraveenNanda124 — COMMENTED** [review]
Great work

**Comment by xtkoba** [comment]
I will clean up and merge this in PR #14371. Thanks.

**Pull request closed without merging**
