### PR TITLE
New package: phpmyadmin

### PR DESCRIPTION
**Pull request by ifurther**
#5715

### CODE REVIEW

**Review by xeffyr — CHANGES_REQUESTED** [review]
What you did here is just extracted the official phpmyadmin tarball, however it requires more things to work.

So:
* Where is a PHP dependency?
* Where is Apache 2 dependency?
* Where is a drop-in Apache 2 configuration file to get phpMyAdmin working out-of-box?

Fix all these 3 things, otherwise I'm closing pull request - if you decided to package this kind of thing, make sure it works properly just after installation.

**Comment by ifurther** [comment]
Sorry it is my problem. I added the depend package for php and apache2. Can I directly modified the httpd.conf file ?

**Comment by xeffyr** [comment]
> Can I directly modified the httpd.conf file ?

As I wrote, you need to create a drop-in config. This means a separate file placed to:
```
/data/data/com.termux/files/usr/etc/apache2/extra
```

***

Optionally you can make a following change to default `apache2` config:
``` .diff
--- /data/data/com.termux/files/usr/etc/apache2/httpd.conf.orig	2020-08-28 22:08:53.477223484 +0000
+++ /data/data/com.termux/files/usr/etc/apache2/httpd.conf	2020-08-28 22:09:54.241605016 +0000
@@ -482,6 +482,9 @@
 # the server, or you may simply copy their contents here and change as 
 # necessary.
 
+# PHPMyAdmin
+#Include etc/apache2/extra/phpmyadmin.conf
+
 # Server-pool management (MPM specific)
 #Include etc/apache2/extra/httpd-mpm.conf
 
```
But of course, that modification should be performed in `apache2` package and not this one.

**Comment by ifurther** [comment]
@xeffyr or add conf.d directory? some distribution linux apache uses this.

**Comment by xeffyr** [comment]
@ifurther Ok, you can patch it to use `conf.d`.

**Comment by amm834** [comment]
Oh Dear,
I face cannot unpack and cannot overwrite to conf.d
<code>
Preparing to unpack .../phpmyadmin_5.0.2_aarch64.deb ...
Unpacking phpmyadmin (5.0.2) ...
dpkg: error processing archive /data/data/com.termux/cache/apt/archives/phpmyadmin_5.0.2_aarch64.deb (--unpack):
 trying to overwrite directory '/data/data/com.termux/files/usr/etc/apache2/conf.d' in package apache2 2.4.46-1 with nondirectory
Errors were encountered while processing:
 /data/data/com.termux/cache/apt/archives/phpmyadmin_5.0.2_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
</code>

**Comment by xeffyr** [comment]
@amm834 Thanks, fixed in https://github.com/termux/termux-packages/commit/47cf758e46ae5beaf6586bb7085fe3d319c9cd14.

**Comment by amm834** [comment]
When I run <code>apachectl</code>
Conf.d cannot find.But exist.
<code>
httpd: Syntax error on line 535 of /data/data/com.termux/files/usr/etc/apache2/httpd.conf: Include/IncludeOptional: Could not open directory /data/data/com.termux/files/usr/conf.d: No such file or directory
</code>

**Comment by ifurther** [comment]
@amm834 Could you show me the `line 535 of /data/data/com.termux/files/usr/etc/apache2/httpd.conf' ?

**Comment by xeffyr** [comment]
@ifurther This should be fixed now. https://github.com/termux/termux-packages/commit/37844d18d20ec7dbe8b5453378f1e5d7e986b233

**Pull request merged**
