### PR TITLE
add(main): new package esbuild

### LINKED ISSUE #11873: [Package]: esbuild
### Why do you want to add this package to Termux?

An extremely fast JavaScript and CSS bundler and minifier

### Home page URL

https://esbuild.github.io

### Source code URL

https://github.com/evanw/esbuild

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Package is written in Go and compiles without any issues on Termux.

### PR DESCRIPTION
**Pull request by 2096779623**
Close #11873 .

### CODE REVIEW

**Comment by ravener** [comment]
1. Why are you doing `termux_setup_nodejs` Node is not needed.
2. Why are you blacklisting `arm`?

**Comment by 2096779623** [comment]
> 1. Why are you doing `termux_setup_nodejs` Node is not needed.

```bash
https://github.com/evanw/esbuild/blob/3e2374cb011a47482b415f84716afa13ea88f3ce/Makefile#L222
```

https://github.com/termux/termux-packages/runs/8297765977?check_suite_focus=true#step:6:444

**Comment by 2096779623** [comment]
https://github.com/evanw/esbuild/issues/2068#issuecomment-1057654160

**Comment by ravener** [comment]
That is really weird cause it builds on arm without issues on-device, I don't know what is esbuild doing differently from other packages which termux cross-compiles all the time.

**Comment by ravener** [comment]
Can you perhaps try what is mentioned here? https://github.com/golang/go/issues/48246#issue-991066436

**Comment by 2096779623** [comment]
> Edit: Actually in termux's build context, `CC` should already be set, right?

CC is not passed in the Makefile, it needs to be set manually.

**Comment by ravener** [comment]
> > Edit: Actually in termux's build context, `CC` should already be set, right?
> 
> CC is not passed in the Makefile, it needs to be set manually.
> 

Really? All other packages that invoke a makefile, never passes `CC` it's probably set by the package builder.

> Edit: Same result.
Ah too bad. I'm running out of ideas.

**Comment by ravener** [comment]
Closing this because someone else already added the package.

**Pull request closed without merging**
