### PR TITLE
qt6-qtbase: use posix ipc

### PR DESCRIPTION
**Pull request by licy183**
See #17789 and #20514

### CODE REVIEW

**Comment by knyipab** [comment]
Thanks a lot the patch on Qt6 `QSharedMemory`! Indeed I am packaging `qpwgraph` which uses QSharedMemory to implement the system tray. But unfortunately running into some problems. 

According to Qt6 [official docs on QSharedMemory](https://doc.qt.io/qt-6/qsharedmemory.html): 
> By default, QSharedMemory automatically destroys the shared memory segment when the last instance of QSharedMemory is [detached](https://doc.qt.io/qt-6/qsharedmemory.html#detach) from the segment, and no references to the segment remain.

However, it is likely not the case. `qpwgraph` never show up again after closing, likely due to the shared memory not released after closing, and then when reopening, it thinks there is another instance running. 

I also tested the official example here and verified that the QSharedMemory is not released: https://github.com/qt/qtbase/tree/v6.7.1/examples/corelib/ipc/sharedmemory

I can still load the stored image in that example after closing all instances and reopening. You may compile on-device with commands below. 
```
cmake -DQT_HOST_PATH=$PREFIX/lib/qt6 -DQT_HOST_PATH_CMAKE_DIR=$PREFIX/lib/cmake -DQT_DEBUG_FIND_PACKAGE=ON -B build
cmake --build build
```

`qt5-qtbase` may encounter the same case, because I built `qpwgraph` with Qt5 few days ago and saw the same issue with its system tray feature.

**Comment by licy183** [comment]
`QSharedMemoryPosix` leaks the named POSIX shared memory file on non-QNX systems. This may reproducible on a normal Linux environment too.

See https://github.com/qt/qtbase/blob/c195fe7d33decbd5ddd47ae46dbf8e0d9c20ba85/src/corelib/ipc/qsharedmemory_posix.cpp#L184-L188

```cpp
#else
    // On non-QNX systems (tested Linux and Haiku), the st_nlink field is always 1,
    // so we'll simply leak the shared memory files.
    cleanHandle(self);
#endif
```

**Comment by knyipab** [comment]
I see, thanks. 

Perhaps lemme disable the system tray feature of `qpwgraph` and `qjackctl` for now, and wait for the sysv semaphore implementation or a `QSharedMemoryPosix` fix in the future.

**Comment by licy183** [comment]
I'm not sure whether Qt will fix this. It seems that someone has reported it ([1](https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-111855)) and these APIs are marked as deprecated and will be removed in Qt 7.0 ([2](https://lists.qt-project.org/pipermail/development/2023-November/044680.html)).

[1] https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-111855
[2] https://lists.qt-project.org/pipermail/development/2023-November/044680.html

**Review by truboxl — APPROVED** [review]
Thanks!

**Pull request merged**
