### PR TITLE
update binutils, doxygen, ed

### PR DESCRIPTION
**Pull request by distobs**

### CODE REVIEW

**Review by thunder-coding — CHANGES_REQUESTED** [review]
See 110631b642942680d280205faa5db11c487e6946b8a269822ae8090664096ee5R31, where I had added lines to force regeneration of manpages. The bug seems to have been fixed and those lines can now be removed

**Comment by distobs** [comment]
oops, misclick

sorry

**Comment by distobs** [comment]
Done

**Comment by thunder-coding** [comment]
Can you please, instead of merging the master branch into your branch, rebase against it.

These merge commits cause some weird problem in master branch.

**Comment by distobs** [comment]
That was not on purpose — it was a misclick.

Should I revert that commit? I'm new to git, sorry for the stupid question.

**Comment by thunder-coding** [comment]
> That was not on purpose — it was a misclick.
> 
> Should I revert that commit? I'm new to git, sorry for the stupid question.

You need to rebase your branch

```
# This will open up your editor, follow the instructions in the file
# and save and close the file
$ git rebase HEAD~<number of commits in your PR> -i

# Get latest changes from master
# First make sure that your master branch is up to date with our master branch.
# If not use the GitHub Web UI to do so
$ git fetch

$ git rebase origin/master
```

**Comment by distobs** [comment]
I hope I've done this right

**Comment by Grimler91** [comment]
@distobs look good, but could you please rebase to get rid of the merge commit? This should do it: https://stackoverflow.com/a/7929499

**Comment by distobs** [comment]
It just spits out "Everything up-to-date"

**Comment by distobs** [comment]
What the hell did I just do...

**Comment by distobs** [comment]
I think I will refork it, copy the patches and submit a new PR.

**Pull request closed without merging**
