### PR TITLE
fix(profanity): update to 0.12.0 and add `libstrophe` to depends

### PR DESCRIPTION
**Pull request by MrAdityaAlok**
Signed-off-by: Aditya Alok <dev.aditya.alok@gmail.com>

### CODE REVIEW

**Comment by jugendhacker** [comment]
@MrAdityaAlok hi, I'm the one who originally tried to improve the python configure.ac stuff in upstream, may I ask you why e87944c492f6f619339ca081d85f075eacb33c65 is still needed? (At least in my local termux setup it worked without patching the python check)

**Comment by Grimler91** [comment]
> CI did not run for previous commit (both commits were pushed simultaneously) , so it should not happen... I guess?

It was run and uploaded for the commit on master: https://github.com/termux/termux-packages/runs/5775364688

**Comment by MrAdityaAlok** [comment]
@jugendhacker previously this had problems, so I thought it might still have. I will remove that patch.

**Comment by jugendhacker** [comment]
@MrAdityaAlok as it's now based on pkg-config it should work like any other c library

**Comment by MrAdityaAlok** [comment]
@Grimler91 I am really confusing something. CI ran and uploaded 0.12.0 in https://github.com/termux/termux-packages/pull/9712/commits/e87944c492f6f619339ca081d85f075eacb33c65 for the first time.... Has it uploaded before too..?

Although what you asked should be done by #9736

**Comment by Grimler91** [comment]
@MrAdityaAlok oh, sorry, I didn't see that the version was changed, somehow. 

Please disregard my crazy rambling..

**Pull request merged**
