### PR TITLE
libllvm: update from 10.0.0 to 10.0.1

### PR DESCRIPTION
**Pull request by buttaface**
Let's see if this builds on the CI.

### CODE REVIEW

**Comment by buttaface** [comment]
@xeffyr, any idea why three of the arch builds didn't run?

**Comment by landfillbaby** [comment]
sorry, that was my fault, i think i've been using up all of the bandwidth
if you do a `rebase -f HEAD~; git push --force` it'll trigger another build

**Comment by buttaface** [comment]
Alright, this builds fine, [looks like rust links against it](https://github.com/termux/termux-packages/blob/master/packages/rust/build.sh#L65) but should be fine since all its files link against the underlying `libLLVM-10.so`.

@its-pointless, any reason that full version number was used in the symbolic link when building the rust package? If not needed, it should be changed to just the major version number, to avoid a pointless bump so that package script can build again after this is merged.

**Comment by buttaface** [comment]
@xeffyr, good to merge? I don't see any packages that directly link to `libLLVM-10.0.0.so`, so I think this should be fine but not sure what experiences you had in the past.

**Comment by its-pointless** [comment]
update binutils first since a library in libllvm compiles against it.

**Comment by buttaface** [comment]
@its-pointless, alright, pulled in your commit from #5589 into this pull so they can be built against each other, and truncated the version number in the Rust symbolic link. I will submit separate pulls to update lldb and Swift to use 10.0.1 once this is in.

Anything else to consider before this hours-long CI run?

**Comment by its-pointless** [comment]
I can't think of anything so go ahead.

**Comment by buttaface** [comment]
Yikes, I didn't know simply touching the Rust build script would trigger a build, hope this finishes.

**Pull request merged**
