### PR TITLE
bump(main/libx265): 4.0

### PR DESCRIPTION
**Pull request by Biswa96**
* Test command:
  - ffmpeg -i Big_Buck_Bunny_360_10s_1MB.webm -vcodec libx265 -crf 28 output.mp4
* Before:
  - encoded 300 frames in 18.75s (16.00 fps), 395.58 kb/s, Avg QP:33.43
* After:
  - encoded 300 frames in 15.53s (19.32 fps), 395.58 kb/s, Avg QP:33.43

### CODE REVIEW

**Comment by Biswa96** [comment]
This creates an update cycle. Current handbrake version can not be built with newer libx265 and older ffmpeg v6. So, ffmpeg, libx264 and handbrake need to be built at once.

**Comment by robertkirkman** [comment]
@Biswa96 I forked this PR and uploaded a version I made to this branch,
https://github.com/termux/termux-packages/compare/master...robertkirkman:termux-packages:bump-libx265-ffmpeg-handbrake
I think this does what you want, this is

- libx265 4.1
- ffmpeg 7.1
- handbrake 1.9.0
- all reverse dependencies' revisions bumped
- 8 packages require additional patches to build with ffmpeg 7, which are included here
   - aubio: patch copied from Arch Linux
   - gpac: patch cherry-picked from upstream development repository
   - minidlna: patch copied from Arch Linux
   - mplayer: one patch copied from Arch Linux, other patch cherry-picked from upstream development repository
   - pianobar: patch cherry-picked from upstream development repository
   - vlc: patch coped from Debian Testing
   - deadbeef: patch cherry-picked from upstream development repository
   - oshu: I wrote and tested this patch on my own. I did not find any other preexisting implementation of ffmpeg 7 support for this app.

You can use this branch to copy things from into this PR, or I could make it a separate PR, or if there are too many packages revbumped in the branch, maybe I should open a group of numbered PRs so that not too many packages are built at once.

**Comment by Biswa96** [comment]
Thank you. I shall roll the update slowly as mentioned in the issue tracker.

**Comment by TomJo2000** [comment]
> @Biswa96 I forked this PR and uploaded a version I made to this branch, [master...robertkirkman:termux-packages:bump-libx265-ffmpeg-handbrake](https://github.com/termux/termux-packages/compare/master...robertkirkman:termux-packages:bump-libx265-ffmpeg-handbrake)

I'll start a local validation run on this shortly.
Is that all of the reverse dependencies?

**Comment by robertkirkman** [comment]
> > @Biswa96 I forked this PR and uploaded a version I made to this branch, [master...robertkirkman:termux-packages:bump-libx265-ffmpeg-handbrake](https://github.com/termux/termux-packages/compare/master...robertkirkman:termux-packages:bump-libx265-ffmpeg-handbrake)
> 
> I'll start a local validation run on this shortly. Is that all of the reverse dependencies?

Technically, `kdenlive` is marked as depending on `fflplay` , and the `ffplay` package does contain an additional copy of `libavdevice.so` at `$PREFIX/opt/ffplay/lib/libavdevice.so`. I don't really think `kdenlive` is directly linked to or ever directly `dlopen()`s that file, I think it is more likely that it only `popen()`s `$PREFIX/bin/ffplay` or similar operations that do not depend on linking symbols, but to be on the safe side, now I added a revision bump for it to the branch.

**Comment by TomJo2000** [comment]
I'll try to get a full validation run started after I get some sleep.

**Comment by truboxl** [comment]
> I forked this PR and uploaded a version I made to this branch, [master...robertkirkman:termux-packages:bump-libx265-ffmpeg-handbrake](https://github.com/termux/termux-packages/compare/master...robertkirkman:termux-packages:bump-libx265-ffmpeg-handbrake)

All seems to build fine except handbrake fails lint-packages.sh

**Comment by Biswa96** [comment]
I have rebased the PR to update x265 to version 4.0 for now.
* handbrake 1.9.0 does not build with ffmpeg 7.1 due to custom ffmpeg patch.
* Also, handbrake 1.8.2 does not build with libx265 4.1.

So, ffmpeg and handbrake can be updated separately.

**Pull request merged**
