### PR TITLE
Updates to a few packages

### PR DESCRIPTION
**Pull request by suhan-paradkar**

### CODE REVIEW

**Comment by kcubeterm** [comment]
You should create another PR now.

**Comment by suhan-paradkar** [comment]
> You should create another PR now. 

I didn't understand... You mean.. for more package updates??

**Comment by kcubeterm** [comment]
Any specific reasons to pushing many package updates in single PR ? Keep under 3-5 commits.

**Comment by suhan-paradkar** [comment]
> Any specific reasons to pushing many package updates in single PR ? Keep under 3-5 commits. 

Yeah... I will then need to create a lot of branches and a lot of pull requests

**Pull request merged**
