### PR TITLE
Bundle intl extension with php

### LINKED ISSUE #2173: PHP with intl extension
I am not sure if this used in many places or not, but I don't see why we can't have a php built with flag  `--enable-intl` on.

### PR DESCRIPTION
**Pull request by shaqman**
Build php with --enable-intl flag to enable bundled Internationalization extension.

Fixes #2173

### CODE REVIEW

**Comment by shaqman** [comment]
Does anyone have a better idea to pass the build, rather than disabling warnings? If all loggings are as it is, travis would stop due to long of a log message.

**Comment by shaqman** [comment]
@fornwall Are these enough to get it merged with the main branch?

**Comment by theScrabi** [comment]
I was really interested in this :) Because it would make it possible to run the ownCloud server direclty on your phone.

@shaqman 
Thank you.

**Comment by viktorprogger** [comment]
Any updates?

**Comment by fornwall** [comment]
We are closing old pull requests as a cleanup action.

If you are interested in picking this work up, please submit a new pull request with up to date content and we promise to be more responsive with the proposed change!

**Comment by theScrabi** [comment]
AAAh push this pls.

**Pull request closed without merging**
