### PR TITLE
new package: thunderbird

### LINKED ISSUE #10093: [Package]: Thunderbird
### Package description

Thunderbird is an email, newsgroup, news feed, and chat ([XMPP](https://en.m.wikipedia.org/wiki/XMPP)/[IRC](https://en.m.wikipedia.org/wiki/IRC)) client with [personal information manager](https://en.m.wikipedia.org/wiki/Personal_information_manager) (PIM) functionality, inbuilt since version 78.0 and previously available from the [Lightning](https://en.m.wikipedia.org/wiki/Mozilla_Lightning) calendar extension. Additional features are available from [extensions](https://en.m.wikipedia.org/wiki/Add-on_(Mozilla)).

### Home page URL

https://www.thunderbird.net/

### Source code URL

https://hg.mozilla.org/comm-central

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/x11-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by licy183**
Closes #10093

### CODE REVIEW

**Review by truboxl — APPROVED** [review]
Verified binaries are opening fine. Thanks! I think Firefox also need to move over to mach build and apply unofficial branding later.

Can remove `|| bash` if it's unnecessary.

**Comment by licy183** [comment]
I'll merge this PR tomorrow if there is no more review. Thanks!

**Comment by TGSMLM** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by myates23** [comment]
Next step - an Android (and iOS) Thunderbird app?

**Pull request merged**
