### PR TITLE
libandroid-support: place headers directly under include

### LINKED ISSUE #3047: metaflac needs --no-utf8-convert to work properly while it shouldn't
I built flac in Termux with and without `/data/data/com.termux/files/usr/include/langinfo.h -> libandroid-support/langinfo.h` and confirmed that it is the source of the problem.

@fornwall I had PRs that fixes it in different manners but they were never accepted (for whatever reason, maybe it was only because you were busy and missed them). Would you mind fix *libandroid-support-dev* (and rebuild flac) in whichever way you find best (e.g. add the missing symlink or even just put the headers directly under `include/`)? https://github.com/termux/termux-packages/blob/master/build-package.sh#L628 can probably go afterwards either way.

### PR DESCRIPTION
**Pull request by tomty89**
Also rebuild libflac to fix #3047

### CODE REVIEW

**Comment by its-pointless** [comment]
Only issue is do we change linker scripts?

**Comment by tomty89** [comment]
What linker scripts are you referring to?

**Comment by fornwall** [comment]
I guess what @its-pointless is asking is if packages also needs to link against libandroid-support as well, or if some packages are improved just by having the headers available, without linking to libandroid-support.so?

**Comment by tomty89** [comment]
@fornwall Theoretically, if a package checks for the headers but do not know to link to libiconv (e.g. expect the functions to be provided by libc), there could be undefined reference issue. But since we've been having iconv.h under `include/` without problem, I assume it would be "safe" to do that for langinfo.h as well. (Even if it is not, it still doesn't hurt anyway since it tells us that we need to link to the library manually).

P.S. `nl_langinfo{,_l}` are provided by libc since Android O, so langinfo.h alone changes things if one are building on-site. In our build system that doesn't matter though, and the functions are provided by libandroid-support, since we target at Android L.

**Comment by fornwall** [comment]
Thanks, let's try this :)!

**Pull request merged**
