### PR TITLE
fix(root/ettercap): permission denied

### PR DESCRIPTION
**Pull request by 123z45**
Disable permission downgrades (Fix https://github.com/termux/termux-packages/issues/20082)

### CODE REVIEW

**Review by 2096779623 — CHANGES_REQUESTED** [review]
Please add `TERMUX_PKG_REVISION=1` under `TERMUX_PKG_VERSION` in `build.sh` .

**Comment by 123z45** [comment]
> Please add `TERMUX_PKG_REVISION=1` under `TERMUX_PKG_VERSION` in `build.sh` .

Now I have changed TERMUX_PKG_REVISION=7 to TERMUX_PKG_REVISION=8 . Please check https://github.com/123z45/termux-packages/commit/20cb0ed92ddce105af88c4a0553caee553109d08 . Thank you.

**Review by 2096779623 — APPROVED** [review]

**Comment by 123z45** [comment]
No need to approve workflow in https://github.com/123z45/termux-packages/commit/3af4964876d057f90f79f811e53bd669b65fd3df . I just merged upstream changes. I tested the deb generated last time and now the bug in #20082 has been fixed. Now we can merge directly.

**Comment by TomJo2000** [comment]
Please [squash the commits](https://www.baeldung.com/ops/git-squash-commits#squashing-by-interactive-rebase), this doesn't need to be 3 commits.
(Squashing by rebase is preferred, as a merge would create a useless merge commit )

**Comment by 123z45** [comment]
> Please [squash the commits](https://www.baeldung.com/ops/git-squash-commits#squashing-by-interactive-rebase), this doesn't need to be 3 commits. (Squashing by rebase is preferred, as a merge would create a useless merge commit )

I squared three commits. Please check. Thank you.

**Review by TomJo2000 — APPROVED** [review]
:shipit:LGTM

**Comment by TomJo2000** [comment]
Thank you for your contribution.

**Comment by 123z45** [comment]
You're welcome.

**Pull request merged**
