### PR TITLE
Add libandroid-support as BUILD_DEPENDS to the packages that need it

### PR DESCRIPTION
**Pull request by Grimler91**
Still a work in progress since I haven't gone through all packages yet

### CODE REVIEW

**Comment by tomty89** [comment]
I think `libandroid-support` should be added to DEPENDS instead of BUILD_DEPENDS. While practically it may not be necessary because some essential packages are already pulling it in, it doesn't really make sense to have it in BUILD_DEPENDS because of the dynamic linkage. There's no reason we want such inconsistency anyway.

Certainly the "side effect" would be `-landroid-support` would be used even for packages that doesn't really need it (i.e. those that links to it "out of the box" via the libiconv.so symlink), but I don't think it could ever be problematic (and we can always remove it where it is).

**Comment by fornwall** [comment]
`libandroid-support-dev` has now been removed (both iconv.h and langinfo.h is provided as a system header due to them being in ndk-patches/), so this shouldn't be needed, right?

**Comment by fornwall** [comment]
Or hm, perhaps we do, unless we special case and always install the libandroid-support in the build?

**Comment by Grimler91** [comment]
I tried building all the packages in this PR without libandroid-support (and with the download option), with the new ndk-patches, and it builds fine for all of them. I'll update this PR to only remove libandroid-support from buildorder.py

**Pull request closed without merging**
