### PR TITLE
android-tools: fix typos in fastboot patch

### PR DESCRIPTION
**Pull request by ookiineko**
I am really sorry about this...

Basically I shouldn't use `ANDROID` compiler option...

vanilla NDK doesn't have it,
I was passing `-DANDROID=1` to the CMake in my local test env, so I didn't realize it until just now..
`__ANDROID__` is the correct one, this will fix my typos in the last PR #10339

Luckily this didn't break anything else, rooted users are still able to use fastboot normally
just Termux-usb support was not included.. (due to the wrong compiler option)

now I've comfirmed it is working

##### Screenshot

please blame it on me..

### CODE REVIEW

**Comment by Grimler91** [comment]
Thanks, merged: https://github.com/termux/termux-packages/commit/67ceadbb4ee04cd15c80ba07d61352d20dcd6f9b

(seems like I can't edit the PR due to it not originating from your username, not because of master branch/protected branches)

**Comment by ookiineko** [comment]
> Thanks, merged: [67ceadb](https://github.com/termux/termux-packages/commit/67ceadbb4ee04cd15c80ba07d61352d20dcd6f9b)
> 
> (seems like I can't edit the PR due to it not originating from your username, not because of master branch/protected branches)

Thank you sir! It's finally working now!

#### Screenshots

|   |  |
| -- | -- |

**Comment by RohitVermaOP** [comment]
termux-usb support added in adb?

**Comment by ookiineko** [comment]
> termux-usb support added in adb?

not yet, maybe u can give a try?

**Comment by RohitVermaOP** [comment]
> > termux-usb support added in adb?
> 
> not yet, maybe u can give a try?

No

**Comment by RohitVerma882** [comment]
I have finally found a way to patch the adb binary to add support for USB devices for non-rooted users using the Termux-USB API. This means that you no longer need to run the termux-usb -r -e "adb ..." -E "..." command to use adb with USB devices.

IMG_20230715_114130

**Pull request closed without merging**
