### PR TITLE
feat(libllvm/lldb): enable python support

### PR DESCRIPTION
**Pull request by thunder-coding**
rust-lldb does require python support in lldb. Or else rust-lldb will
simply fail with "error: module importing failed: This script interpreter
does not support importing modules." This should be fixed by enabling
python support for lldb. Also "command script import /path/to/script"
should now work.

Also see 72d3b537a988d60774909471af5d49b7910d6eb8 where Python support
for lldb was explicitly disabled (probably because it's disabled by
default?)

### CODE REVIEW

**Comment by xtkoba** [comment]
72d3b537a988d60774909471af5d49b7910d6eb8 was to avoid automagic (#9245). No problem if explicitly enabled. Thanks!

**Comment by thunder-coding** [comment]
> 72d3b537a988d60774909471af5d49b7910d6eb8 was to avoid automagic (#9245). No problem if explicitly enabled. Thanks!

Thanks for clarifying. That makes sense!

Although building lldb with python support doesn't seem to require any kind of patching work, but this creates a huge overhead when updating major version of python, as entire libllvm will need to be rebuilt for just lldb!

**Comment by buttaface** [comment]
I'm fine with adding this, but have you installed this lldb package and tried it out?

**Comment by thunder-coding** [comment]
> I'm fine with adding this, but have you installed this lldb package and tried it out?

Just tested it out, seems to work well. With rust-lldb, it seems to give much more details when printing out variables using `expr`. (Perhaps the 24x build binary bloat during debug builds with rust is worth it). Couldn't text more but seems good to go!

**Comment by buttaface** [comment]
Alright, I will try it out myself a bit and let you know.

**Comment by buttaface** [comment]
14.0.2 just released, pulling this into that update at #10371.

**Pull request closed without merging**
