### PR TITLE
libicu: revbump revdeps(1)

### PR DESCRIPTION
**Pull request by 2096779623**

### CODE REVIEW

**Comment by truboxl** [comment]
PostgreSQL bumped in #19780. Thanks.

**Comment by TomJo2000** [comment]
I just tested it locally, and `samba` seems to build fine.
So we should be good to merge this batch.

**Review by licy183 — APPROVED** [review]

**Comment by TomJo2000** [comment]
`arm`, `i686` and `x86_64` on this failed due to a random fluke cURL issue.
(We've been getting too many of those today...)

I've re-run them manually, they should be done in 3 hours.
AArch64 ***was successful***, but did not trigger the upload workflow, I'm not sure why.

**Comment by thunder-coding** [comment]
> I've re-run them manually, they should be done in 3 hours.
AArch64 was successful, but did not trigger the upload workflow, I'm not sure why.

Upload step depende all architecture builds

**Comment by TomJo2000** [comment]
Ah figures.

**Pull request merged**
