### PR TITLE
scripts: indicate git urls with git+[...] instead of [...].git

### PR DESCRIPTION
**Pull request by Grimler91**
Not all source code hosts support the .git suffix (for example sourcehut).  Use a git+ prefix instead to indicate that a url is a git repo.

### CODE REVIEW

**Comment by truboxl** [comment]
LGTM but I think need to check auto update as well, there's still ".git" references there.

**Comment by T-Dynamos** [comment]
Can't we support both formats?

**Comment by Grimler91** [comment]
> LGTM but I think need to check auto update as well, there's still ".git" references there.

Thanks for pointing that out, should be fixed now, have verified that auto-updates work from github and gitlab

**Comment by Grimler91** [comment]
> Can't we support both formats?

We could, but that would make the checks for https and git repos more complicated, I don't think that it is worth it

**Comment by Grimler91** [comment]
Merged in https://github.com/termux/termux-packages/commit/3ec82277d7773e29aac53d525fdf519f74246bd4

**Pull request closed without merging**
