### PR TITLE
termux-tools: Add multiple sources.

### LINKED ISSUE #10379: [New Mirror] NJUPT
Main | deb https://mirrors.njupt.edu.cn/termux/apt/termux-main stable main
-- | --
Root | deb https://mirrors.njupt.edu.cn/termux/apt/termux-root root stable
X11 | deb http://mirrors.njupt.edu.cn/termux/apt/termux-x11 x11 main

The mirror from Nanjing University of Posts and Communications.

### LINKED ISSUE #10400: [New Mirror]SUSTech
|  Repository   | sources.list entry  |
|  ----  | ----  |
| [Main](https://github.com/termux/termux-packages)  | `deb https://mirrors.sustech.edu.cn/termux/apt/termux-main stable main` |
| [Root](https://github.com/termux/termux-root-packages)  | `deb https://mirrors.sustech.edu.cn/termux/apt/termux-root root stable` |
| [X11](https://github.com/termux/x11-packages)  |`deb http://mirrors.sustech.edu.cn/termux/apt/termux-x11 x11 main` |

The mirror from Southern University of Science and Technology.

### LINKED ISSUE #10411: [New Mirror] SAU
|  Repository   | sources.list entry  |
|  ----  | ----  |
| [Main](https://github.com/termux/termux-packages)  | `deb https://mirrors.sau.edu.cn/termux/apt/termux-main stable main` |
| [Root](https://github.com/termux/termux-root-packages)  | `deb https://mirrors.sau.edu.cn/termux/apt/termux-root root stable` |
| [X11](https://github.com/termux/x11-packages)  |`deb http://mirrors.sau.edu.cn/termux/apt/termux-x11 x11 main` |

The mirror from Shenyang Aerospace University,Supports IPV4 and IPV6.

@Grimler91

### LINKED ISSUE #10635: [New Mirror] SCAU
|  Repository   | sources.list entry  |
|  ----  | ----  |
| [Main](https://github.com/termux/termux-packages)  | `deb https://mirrors.scau.edu.cn/termux/apt/termux-main stable main` |
| [Root](https://github.com/termux/termux-root-packages)  | `deb https://mirrors.scau.edu.cn/termux/apt/termux-root root stable` |
| [X11](https://github.com/termux/x11-packages)  |`deb http://mirrors.scau.edu.cn/termux/apt/termux-x11 x11 main` |

The mirror from South China Agricultural University,Supports IPV4.

### LINKED ISSUE #10652: New Termux apt Mirror
| Repository        | Sources.list entry |
| ------------- |:-------------:|
| [Main](https://github.com/termux/termux-packages)      | `deb https://packages.nscdn.top/termux-main/ stable main` |
| [Root](https://github.com/termux/termux-root-packages) | `deb https://packages.nscdn.top/termux-root/   root stable `  |
| [X11](https://github.com/termux/x11-packages) | `deb https://packages.nscdn.top/termux-x11/ x11 main`  |

Termux apt repo synced every 6 hours hosted in AWS in Mumbai, India

### LINKED ISSUE #10691: [New Mirror] SDU
|  Repository   | sources.list entry  |
|  ----  | ----  |
| [Main](https://github.com/termux/termux-packages)  | `deb https://mirrors.sdu.edu.cn/termux/termux-main stable main` |
| [Root](https://github.com/termux/termux-root-packages)  | `deb https://mirrors.sdu.edu.cn/termux/termux-root root stable` |
| [X11](https://github.com/termux/x11-packages)  |`deb http://mirrors.sdu.edu.cn/termux/termux-x11 x11 main` |

The mirror from Shandong University,Supports IPV4 and IPV6.

### PR DESCRIPTION
**Pull request by 2096779623**
There are currently too many sources in issues and need to be added at one time.

Source list:  

closes #10652
closes #10635
closes #10411
closes #10400
closes #10379
closes #10691

### CODE REVIEW

**Comment by thunder-coding** [comment]
You could have forced pushed your branch in  #10692 itself. Please refrain from creating new PRs for suggested changes as it breaks review workflow. Closing this PR and re-opening your earlier one. See https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message, and in case you need some help, feel free to ask for it. Also you seem to be a regular contributor, so you ought not to be told this again

**Comment by 2096779623** [comment]
> You could have forced pushed your branch in #10692 itself. Please refrain from creating new PRs for suggested changes as it breaks review workflow. Closing this PR and re-opening your earlier one. See https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message, and in case you need some help, feel free to ask for it. Also you seem to be a regular contributor, so you ought not to be told this again

image

**Comment by thunder-coding** [comment]
I don't see any force pushes on the master branch in the last few hours. Seems like your master branch is either out of date or has experienced force pushes recently. I'm allowing you to continue in this PR with the sole aim that in future you'll consider not opening new PRs when changes are suggested for the same reason I highlighted.

**Comment by 2096779623** [comment]
> ~I don't see any force pushes on the master branch in the last few hours. Seems like your master branch is either out of date or has experienced force pushes recently.~ **See note below**. I'm allowing you to continue in this PR with the sole aim that in future you'll consider not opening new PRs when changes are suggested for the same reason I highlighted.
> 
> It seems like probably GitHub PRs have recently got a bug where re-opening PRs isn't possible, feel free to open a new PR

OK, I promise I won't make the same mistake next time :)

**Pull request closed without merging**
