### PR TITLE
Zls

### PR DESCRIPTION
**Pull request by SunPodder**

### CODE REVIEW

**Review by licy183 — APPROVED** [review]

**Comment by licy183** [comment]
`zls` exists in Arch Linux, Gentoo Linux and FreeBSD Ports, so I think it is acceptable to be added for Termux too.

I'd like to merge this PR tomorrow night (UTC+8) if there is no more review.

**Review by truboxl — CHANGES_REQUESTED** [review]
Nvm, please hold on while I try to fix the other zig issue

**Comment by SunPodder** [comment]
> Nvm, please hold on while I try to fix the other zig issue

The zls binary works fine and is ready to be merged. Nothing to be changed on this end.

However, about the zig issues, I also couldn't build zls locally with the zig compiler available in termux. Both of these commands failed

```
zig build -Dtarget=aarch64-linux-mscl -Doptimize=ReleaseSafe
warning: Encountered error: FileNotFound, falling back to default ABI and dynamic linker.

error: TemporaryNameServerFailure
```

```
zig build -Doptimize=ReleaseSafe
warning: Encountered error: FileNotFound, falling back to default ABI and dynamic linker.

error: TemporaryNameServerFailure
```
CI builds works fine though

**Comment by truboxl** [comment]
> warning: Encountered error: FileNotFound, falling back to default ABI and dynamic linker.

https://github.com/ziglang/zig/issues/14146

> error: TemporaryNameServerFailure

https://github.com/ziglang/zig/issues/14636

Likely to be fixed in next version.

But somebody need to step up maintain zig. The original maintainer seems to MIA.
I only bump the zig version because I don't like that [last version was left hanging which otherwise would be retired](https://github.com/termux/termux-packages/issues/17202#issuecomment-1616525928).

Allow me to merge #17768 first so that it fixes x86_64 zls issue too then you can rebase

**Review by truboxl — APPROVED** [review]

**Pull request merged**
