### PR TITLE
Add package cc65

### PR DESCRIPTION
**Pull request by omecamtiv**
Add Package "cc65" as requested in  #7340 
Package compiled successfully in Termux in built environment.

### CODE REVIEW

**Comment by omecamtiv** [comment]
Added some fix. Run the build successfully in forked repo. Tested the aarm64 version of the deb artifacts in Termux. And all seems to be working fine.

**Comment by Grimler91** [comment]
Great, nice work!

Could you squash the commits? Having 18 commits, of which many has the non-descriptive message "fix", to add one package is a bit unnecessary. See for example https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git on how to do it

**Comment by omecamtiv** [comment]
Ok... I'll see the documentation and trying to do as you have said.

**Comment by omecamtiv** [comment]
I messed up the whole thing... May i submit a fresh pull request? I think it will be better.

**Comment by Grimler91** [comment]
> May i submit a fresh pull request?

Sure

**Pull request closed without merging**
