### PR TITLE
Fix undefined TERMUX_MAIN_PACKAGE_FORMAT variable

### PR DESCRIPTION
**Pull request by Wetitpig**
This commit tries to fix the undefined variable error at the start of every build:
```
/home/builder/termux-packages/scripts/build/termux_step_setup_variables.sh: line 2: TERMUX_MAIN_PACKAGE_FORMAT: unbound variable
```

### CODE REVIEW

**Comment by Wetitpig** [comment]
Actually I am wondering if there is a need to assign 2 variables `TERMUX_PACKAGE_FORMAT` and `TERMUX_MAIN_PACKAGE_FORMAT`? There seems to be no need to keep both in the script 🤔

**Comment by Maxython** [comment]
> Actually I am wondering if there is a need to assign 2 variables `TERMUX_PACKAGE_FORMAT` and `TERMUX_MAIN_PACKAGE_FORMAT`? There seems to be no need to keep both in the script 🤔

Let's start with a definition.  
TERMUX_PACKAGE_FORMAT - this is a value for the compiler that specifies in what format the package will be compiled.  
TERMUX_MAIN_PACKAGE_FORMAT - this is a system value in the device that indicates which package (i.e. package format) is used as the main one, it is needed for scripts that work with the package manager.  

Now let's start with the change.  
The value of TERMUX_MAIN_PACKAGE_FORMAT need not be changed at compile time as this would break the logic for working with the package manager.

**Comment by Maxython** [comment]
And what else did you try to compile that got the error?

**Comment by Grimler91** [comment]
> And what did you try to compile that got the error?

Warning appear for all builds: https://github.com/termux/termux-packages/runs/5257050452?check_suite_focus=true#step:3:197

That said, should be properly fixed in https://github.com/termux/termux-packages/commit/51df4c1c083130019b25694cb806221dd4f5a03c.

**Comment by Wetitpig** [comment]
> And what did you try to compile that got the error?

That error is not specific to a package. I think every Github CI build starts with this error when `build-package.sh` is executed.

**Comment by Grimler91** [comment]
> Actually I am wondering if there is a need to assign 2 variables `TERMUX_PACKAGE_FORMAT` and `TERMUX_MAIN_PACKAGE_FORMAT`? There seems to be no need to keep both in the script thinking

@Maxython also explained how they work in https://github.com/termux/termux-packages/pull/8899#discussion_r799542832, but maybe variable names could be more intuitive

**Comment by Maxython** [comment]
> > And what did you try to compile that got the error?
> 
> Warning appear for all builds: https://github.com/termux/termux-packages/runs/5257050452?check_suite_focus=true#step:3:197
> 
> That said, should be properly fixed in [51df4c1](https://github.com/termux/termux-packages/commit/51df4c1c083130019b25694cb806221dd4f5a03c).

Got it.  Thanks

**Pull request closed without merging**
