### PR TITLE
Update imagemagick to version 7.0.7.32

### PR DESCRIPTION
**Pull request by Neo-Oli**
I was checking if it might fix the segfault problems, as the changelog
indicated that several memory overflows have been fixed, but they still
happen for me.
But at least it fixes the compliance bug present in version .29, that has been annoying me.

### CODE REVIEW

**Comment by Grimler91** [comment]
Isn't v32 available as well? Any particular reason why you haven't updated to it instead?

**Comment by Neo-Oli** [comment]
Apperantly so. I didn't realize because they haven't updated their [Changelog](https://www.imagemagick.org/script/changelog.php). ಠ_ಠ

**Comment by Neo-Oli** [comment]
There we go. it still doesn't fix #1314 thought.

**Comment by Grimler91** [comment]
Seems like `--without-ltdl` isn't a valid configure option either (and haven't been in IM7 according to git history) so we might just as well remove it.

**Comment by fornwall** [comment]
Nice! The updated package is now available for installation.

**Pull request merged**
