### PR TITLE
miniserve: add postrm hooks to remove shell completion helpers

### PR DESCRIPTION
**Pull request by pvonmoradi**
Add `postrm` hook to clear out shell completion functions

### CODE REVIEW

**Comment by truboxl** [comment]
Need to use `TERMUX_PKG_RM_AFTER_INSTALL`?

**Comment by pvonmoradi** [comment]
> Looks like it doesn't clean up the directories made by `mkdir -p`

They shouldn't be cleaned up. Those should be handled by their own packages (bash-completion, fish etc)

**Comment by truboxl** [comment]
I recommend changing to https://github.com/truboxl/termux-packages/pull/47/files which allow dpkg handle removing shell completions files and dirs when needed

**Comment by pvonmoradi** [comment]
> I recommend changing to https://github.com/truboxl/termux-packages/pull/47/files which allow dpkg handle removing shell completions files and dirs when needed

In that case if `miniserve [subcommand]` fails, there would be empty shell completion functions for miniserve hanging around in that path.

**Comment by truboxl** [comment]
Looks like those packages also suffer from the same problem

postinst will run after each install and upgrade, eliminating the chance of shell completion functions

**Comment by pvonmoradi** [comment]
> Looks like those packages also suffer from the same problem

For example Debian rules for [github-cli](https://salsa.debian.org/go-team/packages/gh/-/blob/debian/sid/debian/rules#L36) also use `mkdir -p` but does not clean it up.

**Comment by truboxl** [comment]
> For example Debian rules for [github-cli](https://salsa.debian.org/go-team/packages/gh/-/blob/debian/sid/debian/rules#L36) also use mkdir -p but does not clean it up.

The listed shell completions are generated on the host after build completed and in turn packaged without having to use any postinst. dpkg will handle cleaning the directories as the files are installed there as part of normal package installation.

Note that I am not reviewing so the PR can merge anyway by others. These are just my nitpicks.

**Comment by licy183** [comment]
Actually, I’d like to agree with truboxl's suggestion. I think other packages should apply the same processing logic later.

**Comment by licy183** [comment]
I think if we dummy files like `"$TERMUX_PREFIX"/share/bash-completion/completions/miniserve`, there is no need to add a `prerm` script.

**Pull request merged**
