### PR TITLE
Texlive: fix #1068, #1069 by upgrading to texlive 2017

### LINKED ISSUE #1068: texlive install fails because of year mismatch in paths
Hello,
I have been trying to reinstall TeXLive recently. While this had worked partially in the past, I now encounter an error during the postinstall script.

Namely, errors with ```sed``` complaining about non-existing paths (eg. ```/data/data/com.termux/files/usr/opt/texlive/2016/tlpkg``` and so on).  I suspect this is related to the fact that the termux texlive package now installs texlive 2017 (as shown earlier in the log).

### PR DESCRIPTION
**Pull request by Grimler91**
Also various improvements: split package into texlive and texlive-dev, remove most of the files in the texlive tree on uninstall.

### CODE REVIEW

**Comment by fornwall** [comment]
Awesome work! The update packages will be available shortly in the apt repository.

**Comment by Grimler91** [comment]
Thanks for merging. I see that the new version is still not available in the repo, did the build fail?

**Comment by its-pointless** [comment]
Could be the version script isn't seeing version number as higher

**Comment by Grimler91** [comment]
@its-pointless Shouldn't `TERMUX_PKG_VERSION=20170524` be seen as higher than `TERMUX_PKG_VERSION=20160523b`?

Maybe the b in 20160523b messes it up.

**Comment by fornwall** [comment]
The apt repo wasn't updated until a few minutes ago - try updating now and it should work!

**Comment by Grimler91** [comment]
@fornwall Great, it works now. 

Seems to be a small path issue in the current version. Users need to source profile.d/texlive.sh manually after installation or open a new shell to have texlive working as it should. 
Not sure if this was the case before as well. 

I'm working on a new, properly packaged version of texlive anyways (branch [here](https://github.com/Grimler91/termux-packages/tree/texlive-dev)). I'll try to take care of this issue there as well.

**Comment by sdrausty** [comment]
Thanks for your time and the great work. Installation of `texlive/stable,now 20170524 aarch64 [installed]` did not go smoothly:
```
Automated TeX Live installation using profile: texlive_inst.profile
Loading http://mirror.unl.edu/ctan/systems/texlive/tlnet/tlpkg/texlive.tlpdb
=============================================================================
./install-tl: The TeX Live versions of the local installation
and the repository being accessed are not compatible:
      local: 2017
 repository: 2016
Perhaps you need to use a different CTAN mirror?
(For more, see the output of install-tl --help, especially the
 -repository option.  Online via http://tug.org/texlive/doc.)
=============================================================================
sed: can't read /data/data/com.termux/files/usr/opt/texlive/2017/tlpkg/TeXLive/TLUtils.pm: No such file or directory
sed: can't read /data/data/com.termux/files/usr/opt/texlive/2017/bin/custom/*: No such file or directory
/data/data/com.termux/files/usr/bin/termux-install-tl[63]: texlinks: not found

termux-install-tl

running mktexlsr /data/data/com.termux/files/usr/opt/texlive/2017/texmf-dist ...
mktexlsr: Updating /data/data/com.termux/files/usr/opt/texlive/2017/texmf-dist/ls-R...
mktexlsr: Done.
writing fmtutil.cnf to /data/data/com.termux/files/usr/opt/texlive/2017/texmf-dist/web2c/fmtutil.cnf
writing updmap.cfg to /data/data/com.termux/files/usr/opt/texlive/2017/texmf-dist/web2c/updmap.cfg
writing language.dat to /data/data/com.termux/files/usr/opt/texlive/2017/texmf-var/tex/generic/config/language.dat
writing language.def to /data/data/com.termux/files/usr/opt/texlive/2017/texmf-var/tex/generic/config/language.def
writing language.dat.lua to /data/data/com.termux/files/usr/opt/texlive/2017/texmf-var/tex/generic/config/language.dat.lua
running mktexlsr /data/data/com.termux/files/usr/opt/texlive/2017/texmf-var /data/data/com.termux/files/usr/opt/texlive/2017/texmf-config /data/data/com.termux/files/usr/opt/texlive/2017/texmf-dist ...
mktexlsr: Updating /data/data/com.termux/files/usr/opt/texlive/2017/texmf-config/ls-R...
mktexlsr: Updating /data/data/com.termux/files/usr/opt/texlive/2017/texmf-dist/ls-R...
mktexlsr: Updating /data/data/com.termux/files/usr/opt/texlive/2017/texmf-var/ls-R...
mktexlsr: Done.
running updmap-sys --nohash ...done
./install-tl: updmap-sys --nohash failed: No such file or directory
re-running mktexlsr /data/data/com.termux/files/usr/opt/texlive/2017/texmf-var /data/data/com.termux/files/usr/opt/texlive/2017/texmf-config ...
mktexlsr: Updating /data/data/com.termux/files/usr/opt/texlive/2017/texmf-config/ls-R...
mktexlsr: Updating /data/data/com.termux/files/usr/opt/texlive/2017/texmf-var/ls-R...
mktexlsr: Done.
pre-generating all format files, be patient...
running fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-strict --all ...done
./install-tl: fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-strict --all failed: No such file or directory
running package-specific postactions
finished with package-specific postactions

./install-tl: errors in installation reported above

Summary of warnings:
./install-tl: updmap-sys --nohash failed: No such file or directory
./install-tl: fmtutil-sys --no-error-if-no-engine=luajittex,mfluajit --no-strict --all failed: No such file or directory
```
https://github.com/sdrausty/HoTTbook failed to build. HOTTbook built on 2016 texlive in Termux without index.

https://github.com/sdrausty/hpmor built OK - all ~1982 pages.

**Comment by Grimler91** [comment]
@sdrausty Seems like `http://mirror.unl.edu/ctan/systems/texlive/tlnet` hasn't been updated to support TL2017 yet. I don't understand why running termux-install-tl again helped though.

`texlinks` need to be after `tlmgr install scheme-full` for the xelatex symlink to be created, does that work?

**Comment by sdrausty** [comment]
`cd /data/data/com.termux/files/usr/opt/texlive/`
`ln -s 2017 2016`
Had to be run too, to obtain:
```
Output written on out/hpmor.pdf (1985 pages).
Transcript written on out/hpmor.log.                
```
Thank you 😋
screenshot_20170611-160037

**Comment by sdrausty** [comment]
Hott Book https://github.com/sdrausty/HoTTbook
```
Transcript written on hott-online.log.
=== TeX engine is 'pdfTeX'
Latexmk: Index file 'hott-online.idx' was written
Latexmk: References changed.
Latexmk: References changed.
Latexmk: Log file says output to 'hott-online.pdf'
Latexmk: Found bibliography file(s) [references.bib]
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'hott-online.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
make: *** [Makefile:83: hott-online.pdf] Error 12
$ p
/data/data/com.termux/files/home/git/sdrausty/book0/book
```
screenshot_20170611-162928

**Comment by sdrausty** [comment]
$ which texlinks

 /data/data/com.termux/files/usr/opt/texlive/2017/bin/custom//texlinks
$ which xelatex
/data/data/com.termux/files/usr/opt/texlive/2017/bin/custom//xelatex

**Pull request merged**
