### PR TITLE
Add package: termux-gui-bash

### PR DESCRIPTION
**Pull request by tareksander**

### CODE REVIEW

**Comment by 2096779623** [comment]
Looks like there's an extra "p" here: https://github.com/tareksander/termux-gui-bash/blob/main/src/tgui-bash.sh#L110

**Comment by tareksander** [comment]
Thanks, fixed that now. I don't think I need to make a new tag for that now, that message was for installing it from source, since `apt` should ensure `jq` is installed when installing otherwise. That spelling fix can wait for the next release.

**Comment by Grimler91** [comment]
Thanks! Possibly bash should be added to TERMUX_PKG_DEPENDS as well, but as bash is an essential package for now it doesn't matter

**Comment by tareksander** [comment]
> Possibly bash should be added to TERMUX_PKG_DEPENDS as well, but as bash is an essential package for now it doesn't matter

Yeah, I looked if bash is an essential package before, and I though I don't have to depend on it in that case. What is the general course of action for this? Should you include all dependencies, even essential ones?

**Comment by Grimler91** [comment]
It's good practise at least, we want to declare all dependencies so that it is easy the check which packages that are affected when a dependency is upgraded for example (though in this case

**Pull request merged**
