### PR TITLE
pulseaudio: process rewind in the realtime loop

### LINKED ISSUE #7389: [Bug]: Pulseaudio crashes when changing OpenSL ES volume
### Problem description

When i'm trying to change my sound output volume from my termux pulseaudio server in my linux computer, The server suddenly crashed then disconnected from pulse

### What steps will reproduce the bug?

* Make sure you have Pulseaudio daemon running
* In your Linux Computer/Proot, Make sure you're using plasma. Then Connect to your Termux PulseAudio server (In same network)
* Change volume with "Audio Volume" window at toolbar (Not using pavucontrol)

### What is the expected behavior?

```
E: [sles-sink] sink-input.c: Assertion 'PA_SINK_INPUT_IS_LINKED(i->thread_info.state)' failed at /home/builder/.termux-build/pulseaudio/src/src/pulsecore/sink-input.c:1085, function void pa_sink_input_process_rewind(pa_sink_input *, size_t)(). Aborting.
```

Full log:
```
I: [pulseaudio] client.c: Created 2 "Native client (UNIX socket client)"
I: [pulseaudio] protocol-native.c: Got credentials: uid=10851 gid=10851 success=1
I: [pulseaudio] sink-input.c: Created input 0 "audio-volume-change" on OpenSL_ES_sink with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] sink-input.c:     media.name = "audio-volume-change"
I: [pulseaudio] sink-input.c:     event.id = "audio-volume-change"
I: [pulseaudio] sink-input.c:     media.role = "event"
I: [pulseaudio] sink-input.c:     event.description = "Volume Control Feedback Sound"
I: [pulseaudio] sink-input.c:     media.filename = "/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
I: [pulseaudio] sink-input.c:     application.name = "libcanberra"
I: [pulseaudio] sink-input.c:     native-protocol.peer = "UNIX socket client"
I: [pulseaudio] sink-input.c:     native-protocol.version = "34"
I: [pulseaudio] sink-input.c:     application.version = "0.30"
I: [pulseaudio] sink-input.c:     application.id = "org.freedesktop.libcanberra"
I: [pulseaudio] sink-input.c:     application.process.id = "3948"
I: [pulseaudio] sink-input.c:     application.process.user = "yonle"
I: [pulseaudio] sink-input.c:     application.process.host = "localhost"
I: [pulseaudio] sink-input.c:     application.process.binary = "plasmashell"
I: [pulseaudio] sink-input.c:     application.language = "C"
I: [pulseaudio] sink-input.c:     window.x11.display = ":0"
I: [pulseaudio] sink-input.c:     application.process.machine_id = "ba49104ed2bfef49a4cf04e4611e1608"
I: [pulseaudio] sink-input.c:     module-stream-restore.id = "sink-input-by-media-role:event"
E: [sles-sink] sink-input.c: Assertion 'PA_SINK_INPUT_IS_LINKED(i->thread_info.state)' failed at /home/builder/.termux-build/pulseaudio/src/src/pulsecore/sink-input.c:1085, function void pa_sink_input_process_rewind(pa_sink_input *, size_t)(). Aborting.
```

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
termux-tools/stable 0.134 all [upgradable from: 0.133-1]
Android version:
8.1.0
Kernel build information:
Linux localhost 4.9.77+ #1 SMP PREEMPT Fri May 28 23:13:48 CST 2021 aarch64 Android
Device manufacturer:
vivo
Device model:
vivo 1820
```

### PR DESCRIPTION
**Pull request by tomty89**
An attempt to fix #7389, in case my call of making use of `u->sink->request_rewind` is wrong. Please test before merging if interested. Not sure if it will actually help or make things worse. @Yonle

### CODE REVIEW

**Comment by Yonle** [comment]
Well. Buikd is passed. I'm testing `aarch64` ones :^)

**Comment by Yonle** [comment]
👍Well done! It's working now!
Screenshot_2021_0906_091752

**Comment by tomty89** [comment]
Rebased and should be ready for merging.

**Comment by tomty89** [comment]
@Grimler91 Hi, I just realized that I forgot to bump the revision. Could you help make a commit on that? Thanks!

**Comment by Grimler91** [comment]
Fixed

**Pull request merged**
