### PR TITLE
bump(x11/angle-android): 2024.07.15

### PR DESCRIPTION
**Pull request by rhjdvsgsgks**
seems like it failed ci due to out of space. im not sure how it been built at last time

### CODE REVIEW

**Comment by TomJo2000** [comment]
> seems like it failed ci due to out of space. im not sure how it been built at last time

Random fluke, I've triggered a manual CI rerun.
image

**Comment by TomJo2000** [comment]
Okay, same problem again.

Once is a coincidence.
Twice is odd...

**Review by licy183 — APPROVED** [review]
Tests fine on all of my devices.

Should wait for NDK r27 before merging as it is in `big-pkgs.list`.

**Comment by licy183** [comment]
Thanks!

**Pull request merged**
