### PR TITLE
Adds French dictionnary for hunspell.

### PR DESCRIPTION
**Pull request by mclbn**

### CODE REVIEW

**Comment by ifurther** [comment]
Maybe you should use git to download the file, it is more easy.

**Comment by Grimler91** [comment]
> Maybe you should use git to download the file, it is more easy.

All the other dictionary packages uses termux_download, since we only need two files from the repo we also save time and disk space in this way

**Review by Grimler91 — COMMENTED** [review]
There's a github merge commit here that should be removed (by rebasing) (see for example [this message](https://lore.kernel.org/lkml/CAHk-=wjbtip559HcMG9VQLGPmkurh5Kc50y5BceL8Q8=aL0H3Q@mail.gmail.com/) on why they are bad).

Also note that the email in the commits isn't associated with your github account, so the web UI doesn't detect that you are the author (doesn't matter, so just a FYI)

**Comment by Grimler91** [comment]
Rebased and merged in https://github.com/termux/termux-packages/commit/7bec235ec572ee4a19d05520e00bc964c3abce24, thanks!

**Pull request merged**
