### PR TITLE
rust: update to 1.52.1

### PR DESCRIPTION
**Pull request by coolreader18**
Hopefully this should be pretty easy, since the bump to LLVM 12 was done already.

### CODE REVIEW

**Review by suhan-paradkar — CHANGES_REQUESTED** [review]
Seems that the patches need to be updated

**Comment by coolreader18** [comment]
Huh... I don't think that failure is related to my changes

**Comment by Grimler91** [comment]
No, looks like ncurses needs some updated URLs and/or versions

**Comment by Grimler91** [comment]
Should build after rebasing against origin/master, after https://github.com/termux/termux-packages/commit/08bcc88e4bae291017e453f0243d10d2e64e48b7

**Comment by coolreader18** [comment]
Oh, jeez, it timed out... and I think it was almost done, too...

**Comment by coolreader18** [comment]
Should llvm 12 be cached in the repositories already?

**Comment by coolreader18** [comment]
Is it possible to increase Actions timeouts?

**Comment by Grimler91** [comment]
> Is it possible to increase Actions timeouts?

Unfortunately not. What we can do is to download the dependencies instead of building them (which I added a commit for), but github actions has issues with downloading stuff (since the last ~2 weeks), so build is still failing. 

We will need to build and upload it manually.

**Comment by coolreader18** [comment]
Ach, yeah, it looks like the build just failed cause of that

**Comment by Grimler91** [comment]
Built and [uploaded manually](https://grimler.se/termux-packages-24/pool/main/r/rust/)

**Pull request merged**
