### PR TITLE
new package: duckdb

### LINKED ISSUE #8266: [Package]: duckdb database
### Package description

DuckDB is a high-performance analytical database system. It is designed to be fast, reliable and easy to use. DuckDB provides a rich SQL dialect, with support far beyond basic SQL. DuckDB supports arbitrary and nested correlated subqueries, window functions, collations, complex types (arrays, structs), and more. 

### Home page URL

duckdb.org

### Source code URL

https://github.com/duckdb/duckdb/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No response_

### LINKED ISSUE #8317: [Package]: duckdb
### Package description

```
TERMUX_PKG_HOMEPAGE=https://www.duckdb.org
TERMUX_PKG_DESCRIPTION="DuckDB is an in-process SQL OLAP Database Management System"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_VERSION=0.3.1
TERMUX_PKG_SRCURL=https://github.com/duckdb/duckdb/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=ae2367d0a393be59e137ffa975f48f60b113b2a72aacc24fbc59afa0cbc3a511
termux_step_pre_configure() {
	LDFLAGS=" -llog"
}
```

### Home page URL

--

### Source code URL

--

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Closes #8266

### PR DESCRIPTION
**Pull request by xtkoba**
Closes #8266, closes #8317.

### CODE REVIEW

**Review by xeffyr — APPROVED** [review]

**Comment by Mause** [comment]
How long does it take for new packages to be available?
I noticed in the build logs it mentions:
```
[16:15:41] Error: got http_status_code == '504', packages may not appear in repository.
```

**Comment by l1t1** [comment]
not available yet. 
```
~ $ pkg ins duckdb
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package duckdb
```

**Comment by Grimler91** [comment]
Should be available from main repo now

**Comment by l1t1** [comment]
it can be installed.  but failed to run duckdb 
```
~ $ pkg ins duckdb
Checking availability of current mirror: ok
Hit:1 https://termux.librehat.com/apt/termux-main stable InRelease
Hit:2 https://packages.termux.org/apt/termux-games games InRelease
Hit:3 https://packages.termux.org/apt/termux-science science InRelease
Reading package lists... Done
Building dependency tree... Done
39 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  libduckdb
The following NEW packages will be installed:
  duckdb libduckdb
0 upgraded, 2 newly installed, 0 to remove and 39 not upgraded.
Need to get 5835 kB of archives.
After this operation, 43.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 https://termux.librehat.com/apt/termux-main stable/main aarch64 libduckdb aarch64 0.3.1 [3227 kB]
Get:2 https://termux.librehat.com/apt/termux-main stable/main aarch64 duckdb aarch64 0.3.1 [2608 kB]
Fetched 5835 kB in 6min 31s (14.9 kB/s)
Selecting previously unselected package libduckdb.
(Reading database ... 3711 files and directories currently installed.)
Preparing to unpack .../libduckdb_0.3.1_aarch64.deb ...
Unpacking libduckdb (0.3.1) ...
Selecting previously unselected package duckdb.
Preparing to unpack .../duckdb_0.3.1_aarch64.deb ...
Unpacking duckdb (0.3.1) ...
Setting up libduckdb (0.3.1) ...
Setting up duckdb (0.3.1) ...
~ $ duckdb
CANNOT LINK EXECUTABLE "duckdb": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/bin/duckdb"...
```

**Comment by sk0kanik** [comment]
@l1t1 Try by upgrading packages. Similar issue #8415 .

**Comment by l1t1** [comment]
it works.  thank you. a small question. the version of duckdb didn't show correct value. 
```
apt list --upgradable

~ $ pkg upd libc++

~ $ duckdb
v0.0.1-dev0
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select * from generate_series(1,3);
┌─────────────────┐
│ generate_series │
├─────────────────┤
│ 1               │
│ 2               │
│ 3               │
└─────────────────┘
D
```

**Comment by l1t1** [comment]
version 0.32 released

**Comment by thunder-coding** [comment]
> version 0.32 released

Consider opening a new issue requesting to update to new version. You're also free to send us PR doing the same :)

Also note that people maintaining packages here are volunteers who also have other responsibilities in their life.

**Comment by l1t1** [comment]
thank you.

**Pull request merged**
