### PR TITLE
Remove fosshost repo

### PR DESCRIPTION
**Pull request by Grimler91**
Use grimler.se mirror as main repo for now. 

This is done since Fosshost will unfortunately decommission its service on 28th of August.

Some more things need to be done:

* Update termux-tools after merging https://github.com/termux/termux-tools/pull/9
* DNS settings for packages.termux.dev should be changed so that it redirect to grimler.se mirror, but lets wait with changing that until Saturday
* Github CI uploads to packages.termux.dev need to be removed, but lets wait with dropping that until Saturday 

Fosshost statement with some more info: https://cdn.discordapp.com/attachments/742089740643205174/1011718189903786054/23_Aug_CEO_Memo_-_Tenants_Update.pdf

### CODE REVIEW

**Comment by 2096779623** [comment]
Don't forget to update the wiki :) .

**Comment by Grimler91** [comment]
> Don't forget to update the wiki :) .

Done!

**Comment by buttaface** [comment]
What percent of our traffic was Fosshost serving? Does that mean Cloudflare will no longer serve Termux packages through their CDN also, or is that separate? Does grimler.se have enough bandwidth to make up the loss for long?

**Comment by Grimler91** [comment]
> What percent of our traffic was Fosshost serving? Does that mean Cloudflare will no longer serve Termux packages through their CDN also, or is that separate? Does grimler.se have enough bandwidth to make up the loss for long?

Last 30 days have had 11 TB of traffic on packages.termux.dev, of which 255 GB was cached. Cloudflare cache (packages-cf.termux.dev) will no longer work. grimler.se has unlimited bandwidth, but speed might be throttled. I have served around 4 - 6 TB of traffic monthly in previous months.

We are in a much better situation these days compared to during bintray days, with many mirrors, so we should be able to handle this quite gracefully. 11 TB is easier to handle compared to ~60 TB when we were using bintray's services

**Comment by Grimler91** [comment]
No objections so far, so lets merge this

**Comment by buttaface** [comment]
So packages-cf.termux.dev was only serving 2% of the traffic at Fosshost? Seems completely pointless to use a CDN then.

> grimler.se has unlimited bandwidth

No such thing, as I pointed out in that earlier thread.

> but speed might be throttled.

Right, that is how I mentioned that they limit you.

> We are in a much better situation these days compared to during bintray days, with many mirrors, so we should be able to handle this quite gracefully. 11 TB is easier to handle compared to ~60 TB when we were using bintray's services

Yes, that is good to hear. Do you know how much of that 11 TB was github CI traffic? We can probably cut that down a lot by caching packages on the CI.

**Comment by buttaface** [comment]
I don't understand how there were more cached requests than uncached, but uncached used 50X the bandwidth. They're not counting the cached packages somehow or most of it was 404 requests?

**Comment by agnostic-apollo** [comment]
Our site https://termux.dev is also hosted on same domain but is not cached itself. So those would have lot of uncached requests. Secondly, `pkg` would also be using lot of cached requests for mirror availability and `apt` for package release file/cache syncing. Didn't look much into packages cache settings of cloudflare, grimler set those up while we were moving domain and should likely be same as termux.org settings. Cloudflare may not always be caching packages depending on strategies set, and frequent updates would affect that too. So different things would add up to give us the stats. Will check settings later.

**Comment by agnostic-apollo** [comment]
Our page rules are.

https://developers.cloudflare.com/cache/about/cache-control/

https://developers.cloudflare.com/cache/how-to/create-page-rules/#cache-everything

termux-dev-page-rules

But they are not working. One million imaginary dollars to first human who figures out one main issue above. :D

https://developers.cloudflare.com/cache/about/default-cache-behavior/#cloudflare-cache-responses

```
curl -svo /dev/null http://packages-cf.termux.dev/apt/termux-main/dists/stable/Release 2>&1 | grep "CF-Cache-Status"
< CF-Cache-Status: DYNAMIC
$ curl -svo /dev/null http://packages-cf.termux.dev/apt/termux-main/dists/stable/main/binary-aarch64/Packages 2>&1 | grep "CF-Cache-Status"
< CF-Cache-Status: DYNAMIC
$ curl -svo /dev/null http://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-tools/termux-tools_1.29.2_all.deb 2>&1 | grep "CF-Cache-Status"
< CF-Cache-Status: DYNAMIC
```

Our site https://termux.dev will also now not be backed by cloudflare. Check https://matrix.to/#/!rrHhKvLYtBVDOISphu:gitter.im/$ZZv83FvosBzo485rCf1oKKILVeRwiGuJr9zhlIw4AnA

**Comment by agnostic-apollo** [comment]
Seems to be a historical issue, eh @Grimler91... ;)

termux-org-page-rules

**Comment by Grimler91** [comment]
Prooobably! :)

**Comment by agnostic-apollo** [comment]
Lolz, figured it out yet? ;)

**Comment by sylirre** [comment]
`packages-cf.termux.dev` should be used as domain for cache-everything rule.

**Comment by agnostic-apollo** [comment]
And we have a winner! Now prove you are human ;)

**Comment by agnostic-apollo** [comment]
I have fixed the url and it seems to be working now.

```
$ curl -svo /dev/null http://packages-cf.termux.dev/apt/termux-main/dists/stable/main/binary-aarch64/Packages 2>&1 | grep "CF-Cache-Status"
< CF-Cache-Status: MISS
$ curl -svo /dev/null http://packages-cf.termux.dev/apt/termux-main/dists/stable/main/binary-aarch64/Packages 2>&1 | grep "CF-Cache-Status"
< CF-Cache-Status: HIT
$ curl -svo /dev/null http://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-tools/termux-tools_1.29.2_all.deb 2>&1 | grep "CF-Cache-Status"
< CF-Cache-Status: MISS
$ curl -svo /dev/null http://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-tools/termux-tools_1.29.2_all.deb 2>&1 | grep "CF-Cache-Status"
< CF-Cache-Status: HIT
$ curl -svo /dev/null http://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-tools/termux-tools_1.29.2_all.deb 2>&1 | grep "CF-Cache-Status"
< CF-Cache-Status: HIT
```

**Pull request merged**
