### PR TITLE
zpaq: new package

### PR DESCRIPTION
**Pull request by tjhexf**
Greetings, i need some advice here. The Makefile passes the LDFLAGS to g++ when compiling, however, it also passes the -static-openmp flag that is in the LDFLAGS, which g++ just, doesn't know what do with and fails the build. 

How can i specifically remove only that argument from the LDFLAGS instead of setting the whole thing manually like i ended up doing? Which just seems wrong

### CODE REVIEW

**Comment by tjhexf** [comment]
hmm, running it gives "illegal hardware instructions"
will experiment more.

**Comment by tjhexf** [comment]
yep, still no clue. Tries many times illegal hardware instruction.

**Comment by tjhexf** [comment]
but hey, atleast now it runs. Sorta
i'm gonna keep trying to see what cflags could fix this, but i have no clue.

**Comment by tjhexf** [comment]
Annnddd... It works now. Apparently all i was missing was one space before the added cppflag.
Anyways, all up for review. Seems to normally compress and decompress on my arm64 device

**Comment by MrAdityaAlok** [comment]
There has been no commit since 2016. Is it worth getting it in?

**Comment by truboxl** [comment]
Using `-msse3` on Arm is really questionable
Also would prefer to avoid tuning to break compatibility

**Comment by tjhexf** [comment]
I will try. It took a lot of trial and error to see what flags managed to compile successfully and *then* work on my arm64 device. I'll see what flags are actually necessary for proper functioning

**Comment by tjhexf** [comment]
Removed the questionable stuff and rebased. Seems to work perfectly on my arm64, and compiles properly, thanks!

**Comment by MrAdityaAlok** [comment]
> It is a very slow compressor, but it does produce the best compression ratio I've tested compared to other archivers. There are plenty of available benchmarks. So i'd say it's still pretty worth it


Okay, I'm getting it in.

**Pull request merged**
