### PR TITLE
Feature/add hcloud

### PR DESCRIPTION
**Pull request by confund0**

### CODE REVIEW

**Review by 2096779623 — CHANGES_REQUESTED** [review]
https://github.com/termux/termux-packages/wiki/Coding-guideline

Fix your indentation.

Don't create multiple PRs for the same request.

**Comment by confund0** [comment]
Little issues while squashing commits, however should be fine now. Please check.

**Comment by 2096779623** [comment]
Enable auto update: https://github.com/termux/termux-packages/wiki/Auto-updating-packages

**Comment by licy183** [comment]
Thanks for this Pull Request! Please set your name and email (the same to the email you used to register the Github) to the git config and update the commit. See https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git.

```
git config --global user.name "Your Username"
git config --global user.email "example@example.com"
```

**Comment by confund0** [comment]
> Enable auto update: https://github.com/termux/termux-packages/wiki/Auto-updating-packages

==> hcloud
[+] Checking if package can be updated from github...
[!] GITHUB_TOKEN is not set.

**Comment by 2096779623** [comment]
> > Enable auto update: https://github.com/termux/termux-packages/wiki/Auto-updating-packages
> 
> ==> hcloud [+] Checking if package can be updated from github... [!] GITHUB_TOKEN is not set.

You just need to add, no need to run it yourself.

**Comment by licy183** [comment]
Please squash these 2 commits into one commit.

**Comment by confund0** [comment]
When can I expect this package available for _pkg install_ on a phone?

**Review by 2096779623 — APPROVED** [review]

**Pull request merged**
