### PR TITLE
Ndk 19 pointless

### PR DESCRIPTION
**Pull request by its-pointless**
For r19b

### CODE REVIEW

**Comment by Wetitpig** [comment]
Maybe we should build a new version of docker image under the tag `ndk19` first in order to check if the branch works.

**Comment by xeffyr** [comment]
@Wetitpig Remove `~/lib` folder and execute `scripts/setup-android-sdk.sh` - this should update NDK installation and no need to wait for docker image.

**Comment by Wetitpig** [comment]
@its-pointless [This document](https://developer.android.com/ndk/guides/other_build_systems) describes that `make_standalone_toolchain.py` is no longer required. Do we still need to run this script? I see that the corresponding line is not yet deleted.

**Comment by its-pointless** [comment]
It would require redoing a lot of stuff. Would have to talk with fornwall about changes first.

**Comment by Grimler91** [comment]
@its-pointless setup-android-sdk.sh currently fails with `mv: cannot stat 'android-ndk-r19': No such file or directory` (missing b in r19b)

**Comment by fornwall** [comment]
Nice work! This has now been merged, so we'll fix eventual problems on the master branch.

**Pull request merged**
