### PR TITLE
new package: trurl

### LINKED ISSUE #18591: [Package]: trurl
### Why is it worth to add this package?

It's an cli tool to parse/manipulate URLs rebustly.

### Home page URL

https://curl.se/trurl/

### Source code URL

https://github.com/curl/trurl

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

https://repology.org/project/trurl/versions

### PR DESCRIPTION
**Pull request by 185264646**
close #18591 

upstream forgot to increment the version to 0.9, added a patch for that.

Also added the curl license and changed the license of curl to that.

### CODE REVIEW

**Comment by 185264646** [comment]
> Both tcurl and libcurl should use the same `MIT` license.
> 
> https://github.com/termux/termux-packages/blob/33af2da36946784e4c80ed3b3b12fad5409f14ea/packages/libcurl/build.sh#L3. 

Sorry, but I'm against it. Both trurl and curl are licensed under "The curl License". According to the official statement, it's similar to MIT but not identical. https://curl.se/docs/copyright.html

**Comment by 185264646** [comment]
> > Sorry, but I'm against it. Both trurl and curl are licensed under "The curl License". According to the official statement, it's similar to MIT but not identical. https://curl.se/docs/copyright.html
> > I think we should change the license specifier for libcurl in our repo to curl too.
> 
> Agree, I recommend splitting tcurl and adding the curl license into two commits/prs. What still needs to be modified: https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_install_license.sh#L38
> 
> https://github.com/termux/termux-packages/blob/7f446b13ae386a6a5d5a1319d00001ae8245b3c3/packages/termux-licenses/ (Bump revision and add the curl license)

Done in the latest version. Also bumped curl for changing license.

**Comment by 2096779623** [comment]
Can you break them down into three specific commits?
The first one: `addpkg(main): tcurl`
Second: `linter: add X11 license (https://spdx.org/licenses/curl)`
Third: `licenses: install license file for curl`
Also please remove all changes to termux-licenses as only commonly used licenses are stored there.

https://git-scm.com/docs/git-rebase

**Comment by 185264646** [comment]
> Can you break them down into three specific commits? The first one: `addpkg(main): tcurl` Second: `linter: add X11 license (https://spdx.org/licenses/curl)` Third: `licenses: install license file for curl` Also please remove all changes to termux-licenses as only commonly used licenses are stored there.
> 
> https://git-scm.com/docs/git-rebase



> Can you break them down into three specific commits? The first one: `addpkg(main): tcurl` Second: `linter: add X11 license (https://spdx.org/licenses/curl)` Third: `licenses: install license file for curl` Also please remove all changes to termux-licenses as only commonly used licenses are stored there.
> 
> https://git-scm.com/docs/git-rebase

rebased and force-pushed

**Comment by 185264646** [comment]
> Can you break them down into three specific commits? The first one: `addpkg(main): tcurl` Second: `linter: add X11 license (https://spdx.org/licenses/curl)` Third: `licenses: install license file for curl` Also please remove all changes to termux-licenses as only commonly used licenses are stored there.
> 
> https://git-scm.com/docs/git-rebase

rebased and force-pushed

**Pull request merged**
