### PR TITLE
chore(main/zstd): Use CMake to build

### PR DESCRIPTION
**Pull request by Biswa96**
Need .cmake files to find zstd in libtiledb
https://github.com/TileDB-Inc/TileDB/blob/2.26.0/cmake/Modules/FindZstd.cmake

### CODE REVIEW

**Comment by Biswa96** [comment]
This is duplicate of #17335 which was abandoned. We now need .cmake files as explained above.

**Comment by TomJo2000** [comment]
Judging from `rg '.*DEPENDS.*zstd'` here's the rebuild list.
```yml
karchive kf6-karchive wireshark-qt oshu qemu-system-x86-64 godot qt6-qtbase squashfuse tshark kphp btrfs-progs qt6-qttools wget2 mariadb dar links squashfs-tools-ng gdal libarrow-cpp weechat
apt uv rsync mesa-vulkan-icd-freedreno-dri3 libblosc libtiledb mesa mesa mesa libzim borgbackup libelf apache-orc n2n mtd-utils ugrep binutils-libs binutils-libs neomutt libxmlb dpkg libtiff
libzip waypipe gnurl gdk-pixbuf rpm android-tools qemu-system-x86-64-headless qemu-system-x86-64-headless appstream libllvm libllvm rizin qemu-system-x86-64-headless graphicsmagick groonga lfortran ccache gdb
```

**Comment by Biswa96** [comment]
> I'll kick off local builds and report back.

Did things build fine? I am just anxious about apt. If there is any issue with other package it can be fixed without breaking termux installation.

**Comment by TomJo2000** [comment]
`apt` builds fine for all architectures though I have not tested it on device yet.

**Pull request merged**
