### PR TITLE
update debootstrap

### PR DESCRIPTION
**Pull request by SamSanuch**
Update package debootstrap to version 1.0.93

### CODE REVIEW

**Comment by fornwall** [comment]
Thanks - debootstrap is now available at version 1.0.93 from the package repository!

Note that this was mode in a commit that just updated build.sh: https://github.com/termux/termux-packages/commit/ea00df0737ef2579d63863e8848e6dc548d9a226 - I'm unsure of the other changed files in this PR, open a new one if those are needed!

**Comment by SamSanuch** [comment]
@fornwall
Some lines bit changed but when i make PR with changes in patches(only like number) Travis checks always fails! But no problem because patches are correct!

**Comment by sdrausty** [comment]
Aarch64 all is well, until...
```
[23:11 ~ ]$ ./r/debian_on_termux.sh
.
.
.
I: Extracting zlib1g...
I: Keyring file not available at /usr/share/keyrings/debian-archive-keyring.gpg; switching to https mirror https://deb.debian.org/debian
I: Installing core packages...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.43_arm64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/base-passwd_3.5.43_arm64.deb is at fault)
update-alternatives: error: no alternatives for editor
info: Trying to set 'debconf/frontend' [select] to 'Editor'
info: Loading answer for 'debconf/frontend'
info: Trying to set 'debconf/priority' [select] to 'low'
info: Loading answer for 'debconf/priority'
info: Trying to set 'locales/locales_to_be_generated' [select] to 'en_US.UTF-8 UTF-8'
info: Loading answer for 'locales/locales_to_be_generated'
info: Trying to set 'locales/default_environment_locale' [select] to 'en_US.UTF-8'
info: Loading answer for 'locales/default_environment_locale'
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: package 'tzdata' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
/usr/sbin/dpkg-reconfigure: tzdata is not installed
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: package 'debconf' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
/usr/sbin/dpkg-reconfigure: debconf is not installed
/tmp/dot_tmp.sh: 26: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 27: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 28: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 29: /tmp/dot_tmp.sh: update-locale: not found
/tmp/dot_tmp.sh: 34: /tmp/dot_tmp.sh: apt: not found

installation successfully completed
to enter the guest system type:
$HOME/bin/enter_deb

[23:26 ~ ]$ debootstrap --version
debootstrap 1.0.93
```

This issue might not been addressed upstream, if it is an upstream issue.

**Comment by SamSanuch** [comment]
@sdrausty it's working well! checked✓

**Comment by sdrausty** [comment]
Not on arm64 it's not.
```
Extracting liblzma5...
I: Extracting zlib1g...
I: Keyring file not available at /usr/share/keyrings/debian-archive-keyring.gpg; switching to https mirror https://deb.debian.org/debian
I: Installing core packages...
W: Failure trying to run:  dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.43_arm64.deb
W: See //debootstrap/debootstrap.log for details (possibly the package /var/cache/apt/archives/base-passwd_3.5.43_arm64.deb is at fault)
update-alternatives: error: no alternatives for editor
info: Trying to set 'debconf/frontend' [select] to 'Editor'
info: Loading answer for 'debconf/frontend'
info: Trying to set 'debconf/priority' [select] to 'low'
info: Loading answer for 'debconf/priority'
info: Trying to set 'locales/locales_to_be_generated' [select] to 'en_US.UTF-8 UTF-8'
info: Loading answer for 'locales/locales_to_be_generated'
info: Trying to set 'locales/default_environment_locale' [select] to 'en_US.UTF-8'
info: Loading answer for 'locales/default_environment_locale'
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: package 'tzdata' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
/usr/sbin/dpkg-reconfigure: tzdata is not installed
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing description
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 24 package 'dpkg':
 missing architecture
dpkg-query: package 'debconf' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
/usr/sbin/dpkg-reconfigure: debconf is not installed
/tmp/dot_tmp.sh: 26: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 27: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 28: /tmp/dot_tmp.sh: apt: not found
/tmp/dot_tmp.sh: 29: /tmp/dot_tmp.sh: update-locale: not found
/tmp/dot_tmp.sh: 34: /tmp/dot_tmp.sh: apt: not found

installation successfully completed
to enter the guest system type:
$HOME/bin/enter_deb

$ uname -mo
aarch64 Android
$ debootstrap --version
debootstrap 1.0.93
```

**Pull request closed without merging**
