### PR TITLE
pypy{,3}: Add build for arm

### PR DESCRIPTION
**Pull request by licy183**

### CODE REVIEW

**Comment by Grimler91** [comment]
Please set `TERMUX_PKG_REVISION=1` for the packages as well

**Comment by licy183** [comment]
> Please set `TERMUX_PKG_REVISION=1` for the packages as well

Sorry, I forgot that.

**Comment by Grimler91** [comment]
Was the seccomp profile needed for just arm and/or just for pypy?
(building pypy3 for aarch64 locally seemed to work fine without it)

**Comment by truboxl** [comment]
maybe want to isolate option `--security-opt` to only for Linux
https://github.com/docker/for-mac/issues/1946

**Comment by licy183** [comment]
> Was the seccomp profile needed for just arm and/or just for pypy? (building pypy3 for aarch64 locally seemed to work fine without it)

It's for arm only. Execute binary linked against bionic libc on arm will perform system call `personality` and needs the custom seccomp for docker.

> maybe want to isolate option `--security-opt` to only for Linux [docker/for-mac#1946](https://github.com/docker/for-mac/issues/1946)

OK, thank you for your reminding.

**Comment by Grimler91** [comment]
Thanks!

**Pull request merged**
