### PR TITLE
Add ZNC and libbthread

### PR DESCRIPTION
**Pull request by raku-cat**
ZNC is an irc bouncer, swig and bthread are used to build it.

### CODE REVIEW

**Comment by raku-cat** [comment]
Not sure why the build failed or if it matters, I rebuilt swig and znc though and they both build fine on my machine.

**Comment by Hax4us** [comment]
I think u should look into configure script of `znc` because I can see logs where znc's configure script was trying to execute `swig` command for any reason

**Comment by raku-cat** [comment]
It was probably trying to check swig, znc does compile with swig support. I'm not sure what I would check because I don't encounter any such error, I did get one with perl so I just compiled without perl support, but other than that it compiles fine for me, I forced a rebuild of swig and znc and it compiled succesfully.

**Comment by tomty89** [comment]
Does it really need this swig thing though?
```
$ cmake -DWANT_PYTHON=true -DWANT_PERL=true -DWANT_TCL=true ..
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking for C++11 support
-- Checking for C++11 support - supported
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Checking for 64-bit off_t
-- Checking for 64-bit off_t - present
-- Checking for fseeko/ftello
-- Checking for fseeko/ftello - present
-- Found PkgConfig: /data/data/com.termux/files/usr/bin/pkg-config (found version "0.29.2")
-- Found OpenSSL: /data/data/com.termux/files/usr/lib/libcrypto.so (found version "1.0.2o")
-- Found ZLIB: /data/data/com.termux/files/usr/lib/libz.so (found version "1.2.8")
-- Checking for module 'libsasl2'
--   Variable 'exec_prefix' not defined in '/data/data/com.termux/files/usr/lib/pkgconfig/libsasl2.pc'
-- Looking for sasl_server_init
-- Looking for sasl_server_init - found
-- Checking for module 'icu-uc'
--   Found icu-uc, version 61.1
-- Found PerlLibs: /data/data/com.termux/files/usr/lib/perl5/5.26.2/aarch64-android/CORE (found suitable version "5.26.2", minimum required is "5.10")
-- Found Perl: /data/data/com.termux/files/usr/bin/perl (found suitable version "5.26.2", minimum required is "5.10")
-- Checking for module 'python3'
--   Found python3, version 3.6
-- Found Tclsh: /data/data/com.termux/files/usr/bin/tclsh (found version "8.6")
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   locale
-- Found Gettext: /data/data/com.termux/files/usr/bin/msgmerge (found version "0.19.8")
-- Looking for getopt_long
-- Looking for getopt_long - found
-- Looking for lstat
-- Looking for lstat - found
-- Looking for getpassphrase
-- Looking for getpassphrase - not found
-- Looking for tcsetattr
-- Looking for tcsetattr - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for AI_ADDRCONFIG
-- Looking for AI_ADDRCONFIG - found
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- GoogleTest not found, testing will be disabled. You can set environment variables GTEST_ROOT and GMOCK_ROOT
+------------------------+
| ZNC 1.7.0 configured   |
|                        |
| Prefix    : /usr/local |
| SSL       : yes        |
| IPv6      : yes        |
| Async DNS : yes        |
| Perl      : yes        |
| Python    : yes        |
| Tcl       : yes        |
| Cyrus     : yes        |
| Charset   : yes        |
| Zlib      : yes        |
| i18n      : yes        |
+------------------------+

Now you can run 'make' to compile ZNC

-- Configuring done
-- Generating done
-- Build files have been written to: /data/data/com.termux/files/home/znc-1.7.0/build
$
```
I don't see znc in Arch built with swig either, even though it appears to have perl and python support.

Also perhaps perl/python/tcl should be build dep (maybe you should even use the builds of them on the host). They are only useful for the corresponding modules. Not sure if you want to always have them pulled. (On Arch they are "optional dependencies", pretty much like "Recommends" in Debian).

**Comment by raku-cat** [comment]
Im not sure how you even managed to get that to all say yes @tomty89, I still get the same error trying to use perl, even with swig not explicitly requested in a flag.
I can build with or without the swig flag there though still, so this is odd cause we basically it seems like it hasn't acted consistently even once :s 
Does it build for you @Hax4us ?

**Comment by raku-cat** [comment]
Okay, I did some testing. You do not need swig at all, I was building from git before but now it's not needed.
I also didn't realize build deps were a thing, so I moved everything to it except the ones that the arch package doesn't have as optional or a make depend(boost, libsasl, libicu), and it makes fine and installs and runs fine. 
I still can't get it to build with perl enabled, it gives me some weird errors that seem like it's trying to run the perl executable in bash rather than execute it directly, other than that I think this should be a working one.

**Comment by raku-cat** [comment]
Boo, terminated cause the log was too long.

**Comment by fornwall** [comment]
We are closing old pull requests as a cleanup action.

If you are interested in picking this work up, please submit a new pull request with up to date content and we promise to be more responsive with the proposed change!

**Comment by dontdieych** [comment]
Any hope to get irc bouncer? Thanks.

**Pull request closed without merging**
