### PR TITLE
add(x11): new package gtkcord4

### PR DESCRIPTION
**Pull request by T-Dynamos**

### CODE REVIEW

**Review by 2096779623 — APPROVED** [review]

**Comment by aicynide** [comment]
Webcord and armcord when?

**Comment by OrdinaryEnder** [comment]
Screenshot_2022_0917_181618
@aicynide

**Comment by T-Dynamos** [comment]
Can this be merged?

**Comment by truboxl** [comment]
TUR maybe a better choice per https://github.com/termux/termux-packages/issues/11948#issuecomment-1250055211

**Comment by T-Dynamos** [comment]
Ok

**Pull request closed without merging**
