### PR TITLE
fix for preprocessing assembly with -fno-integrated-as

### PR DESCRIPTION
**Pull request by its-pointless**
For things that require gnu as.

### CODE REVIEW

**Comment by fornwall** [comment]
Could you describe this change some more? What does it fix?

**Comment by its-pointless** [comment]
it fixes what happens  when using bin utils "as" instead if the integrated
clang one when compiling assembly that requires preprocessing (usually with
the suffix .S) as it uses the c preproessor. By default this leaves the
first few lines starting with #. Before this patch it interprets the entire
file a comment because it starts in # and it creates an empty binary. After
this patch it correctly detects the newline \n character. and actually uses
ths provided assembly.

**Comment by its-pointless** [comment]
Basically its a workaround for bionic libc ...

**Comment by fornwall** [comment]
This sounds like a serious bug! Is it fixed (or reported/discussed) anywhere? If not, could you create an issue in the binutils issue tracker about it, so we can put a link to it with the patch?

**Comment by fornwall** [comment]
Thanks for all the explanation!

Aha, it's bionic specific? If so, I guess the binutils project is not keen of fixing it :).

Not understanding this code - but why is it bionic specific?

**Comment by fornwall** [comment]
@its-pointless Could you describe why this is bionic specific - I'm unable to figure out why, sorry if I'm being dumb :).

**Comment by its-pointless** [comment]
yeah its because bionic implementation getc fgets etc...
when it gets to the part i patched if it continues it sees it as end of file so the ungetc('#', f_in); is a new file or the end of the last file rather than a continuation of the file stream. By getting the first line loaded and put a \n at the end it reinitializes the file stream.

**Comment by fornwall** [comment]
We are closing old pull requests as a cleanup action.

If you are interested in picking this work up, please submit a new pull request with up to date content and we promise to be more responsive with the proposed change!

**Pull request closed without merging**
