### PR TITLE
python: update to 3.9.2

### PR DESCRIPTION
**Pull request by landfillbaby**

### CODE REVIEW

**Comment by landfillbaby** [comment]
ooh that's a fun error

**Comment by landfillbaby** [comment]
hmm....

**Comment by landfillbaby** [comment]
ok i can't figure it out, sorry

**Comment by ChiefMikeK** [comment]
# 🤔
3.9.0 = `MAJOR VERSION`  
.1 AND .2 should = `MINOR VERSION`

**Pull request closed without merging**
