### PR TITLE
feat(ghc-libs): link against libandroid-posix-semaphore

### PR DESCRIPTION
**Pull request by MrAdityaAlok**
Signed-off-by: Aditya Alok <dev.aditya.alok@gmail.com>

### CODE REVIEW

**Comment by MrAdityaAlok** [comment]
@xtkoba would you please confirm that now it links against `libandroid-posix-semaphore`. It should now...

Here's result of my testing:

```sh
$ readelf -s ./data/data/com.termux/files/usr/lib/ghc-8.10.7/unix-2.7.2.2/libHSunix-2.7.2.2-ghc8.10.7.so | grep "sem"
   235: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND sem_close
   236: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND sem_getvalue@LIBC (2)
   237: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND sem_open
   238: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND sem_post@LIBC (2)
   239: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND sem_trywait@LIBC (2)
   240: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND sem_unlink
   241: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND sem_wait@LIBC (2)
```

**Comment by xtkoba** [comment]
Apparently it fails to do so. Symbols that appear there should be prefixed by `libandroid_`, e.g. `libandroid_sem_close` instead of `sem_close`.

**Comment by MrAdityaAlok** [comment]
> Apparently it fails to do so. Symbols that appear there should be prefixed by `libandroid_`, e.g. `libandroid_sem_close` instead of `sem_close`.

Ahh..ok. Then trying something else.

**Comment by MrAdityaAlok** [comment]
@xtkoba Finally found. GHC unix lib uses `ccall` ffi which ignores include indirection. It directly links to available symbols. 

Here, since we define alias and `libandroid-posix-semaphore` is linked before `libc` these symbols are from `libandroid-posix-semaphore` , otherwise symbols are suffixed with version as `sem_open@LIBC`. 
To confirm my belief I wrote a simple Haskell program to use `sem_open`. When linked with lib compiled with `-landroid-posix-semaphore` flag, it works as expected. Otherwise,  it throws error that `sem_open` is not implemented.

Although this should work but to be sure that same library loading order is during runtime, I'll patch it to use `capi` ffi which considers include indirections.

**Comment by MrAdityaAlok** [comment]
Merged.

**Pull request closed without merging**
