### PR TITLE
Android 4

### PR DESCRIPTION
**Pull request by jotbyte**
Backward compatibility for android API 16 - 19

### CODE REVIEW

**Comment by xeffyr** [comment]
**What is this ???**

 Official support is only Android 5 and higher.

**Comment by xeffyr** [comment]
Useless changes that break everything.

**Comment by jotbyte** [comment]
Lol idk how to use git that well. It was supposed to be a personal project to add backward compatibility. I didn't think this was visible in your repo.

**Comment by jotbyte** [comment]
Well in one of duplicate #6 issues it was mentioned that it's not impossible.

**Comment by jotbyte** [comment]
I noticed what the changes did. I'm still looking through the scripts and docs and learning. It was meant to be and android-4-only branch.

**Comment by buttaface** [comment]
Probably not worth the effort, @jotbyte, as [Android 4 and below have less than 11% share at this point](https://developer.android.com/about/dashboards). You're better off porting packages that you want to Termux and submitting PRs for that.

**Pull request closed without merging**
