### PR TITLE
Update tergent to 1.0.0

### PR DESCRIPTION
**Pull request by lennonhill**

### CODE REVIEW

**Comment by landfillbaby** [comment]
i would recommend including a preinst script that warns before upgrading from < 1.0.0

**Comment by landfillbaby** [comment]
I'd recommend doing something like this in the build.sh:
```
termux_step_create_debscripts() {
	cat <<- EOF > ./preinst
	#!$TERMUX_PREFIX/bin/sh
	if [ "\$1" = upgrade -a "\${2%%.*}" = 0 ]; then
		echo 'Upgrading tergent breaks compatibility!'
		echo See
		echo 'https://github.com/aeolwyr/tergent/blob/master/'\
			'README.md#upgrading-from-01'
		echo 'for details on how to prepare before upgrading.'
		read -p 'Are you sure you're ready to upgrade? [yN]' yn
		case \$yn in
			[Yy]* ) exit 0;;
			* ) exit 1;;
		esac
	fi
	EOF
}
```

**Comment by xeffyr** [comment]
Done in https://github.com/termux/termux-packages/commit/79069bdeafe71e0b95e882164fec7ee9cf25ba64.

Take care on what you are submitting. Don't expect that maintainers would fix your pull request for you.

As https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#fixing-issues states:
> **Contributors should take full responsibility about submitted changes. Pull requests containing incomplete work** or disruptive changes **will NOT be merged**.

**Comment by landfillbaby** [comment]
@xeffyr i see you added the warning as a postinst rather than preinst with option to cancel, this might lock people out their ssh servers due to the key incompatibility

**Pull request closed without merging**
