### PR TITLE
android-tools: improve fastboot patch

### PR DESCRIPTION
**Pull request by ookiineko**
### Changes
* cleaned up some code
* read interface name
#### Bugfix
* correct disconnect detection
* `fastboot reboot fastboot` now won't wait for the device forever
* ignore invalid fd

### CODE REVIEW

**Comment by MrAdityaAlok** [comment]
I think `disconn` is typo in this https://github.com/termux/termux-packages/pull/10816/commits/efba828ce30556321c9bc6587ed1774488034b53 commit's message. Please correct it. 

Also rebase against master.

Everything else looks good.

**Comment by ookiineko** [comment]
> I think `disconn` is typo in this [efba828](https://github.com/termux/termux-packages/commit/efba828ce30556321c9bc6587ed1774488034b53) commit's message. Please correct it.
> 
> Also rebase against master.
> 
> Everything else looks good.

thank you sir, done

**Comment by MrAdityaAlok** [comment]
Merged.

> thank you sir, done

Please do not call me sir 😄 . I am still a teenager and most probably younger than you.

**Comment by ookiineko** [comment]
> Merged.
> 
> > thank you sir, done
> 
> Please do not call me sir smile . I am still a teenager and most probably younger than you.

oh..i am sorry

**Comment by Biswa96** [comment]
@ookiineko Could you rebase the patches for android-tools version 34.0.5 ? The fastboot code was changed significantly.

**Comment by ookiineko** [comment]
> Could you rebase the patches for android-tools version 34.0.5 ?

sorry for the slow response, i can try at some point, but idk when

**Comment by ookiineko** [comment]
just have made some cleanups for my old code in #20073, i guess i will try porting the patch to 34.0.5 tomorrow

**Comment by Biswa96** [comment]
The latest release is 35.0.1.

**Comment by ookiineko** [comment]
> The latest release is 35.0.1.

humm i think i should upgrade versions one by one (?

**Comment by ookiineko** [comment]
looks like ＠twaik have done pretty nice job rebasing the patch in https://github.com/termux/termux-packages/commit/794aeceaafe25a329f03ff7725fc7e85291c223c before me, oops

**Pull request merged**
