### PR TITLE
notify-send: add a wrapper script over termux-notification

### PR DESCRIPTION
**Pull request by pvonmoradi**
This PR adds a wrapper script over `termux-notification` to mimic freedesktop's `notify-send`
https://github.com/termux/termux-packages/issues/9923

### CODE REVIEW

**Comment by MrAdityaAlok** [comment]
@pvonmoradi please increase version count to `0.183` add `notify-send` in 'script for loop' in build.sh.

**Comment by MrAdityaAlok** [comment]
@pvonmoradi please increase version count to `0.183` add `notify-send` in 'script for loop' in build.sh.

**Review by MrAdityaAlok — COMMENTED** [review]
Also, chnage commit message to something like:
```
enhance(termux-tools): add `notify-send` script as wrapper over termux-notification 
```

**Comment by MrAdityaAlok** [comment]
> @pvonmoradi please increase version count to `0.183`

Forgot?

**Comment by pvonmoradi** [comment]
> 

should I revert it to '0.1' in the `notify-send` script?

**Comment by MrAdityaAlok** [comment]
> @MrAdityaAlok should I revert it to '0.1' in the `notify-send` script?

Yes.

**Pull request merged**
