### PR TITLE
add package krb5

### PR DESCRIPTION
**Pull request by vishalbiswas**
This is the MIT Kerberos. Its required as a dependency for many others, and enables optional features in many others/

### CODE REVIEW

**Comment by qmfrederik** [comment]
@vishalbiswas Having this package in Termux would help the port of .NET Core to Android. 
I've compiled this package from your branch and confirmed it works.
Anything I can do to help speed up getting this packaged as an official Termux package?

**Comment by vishalbiswas** [comment]
Currently, there are no packages that require this as a dependency. I think that's the reason this hasn't been merged yet.
Your comment alone may be enough to include this. 
I would like to enable krb support in existing packages, but the list is very exhaustive on my side. Without other packages which actually use it, it will just be sitting in the repo for nothing.

**Comment by qmfrederik** [comment]
@fornwall Any chance you could have a look at this package? Would help us with the .NET Core on Android bring up :)

**Comment by fornwall** [comment]
Thanks! There is now a `krb5` package available (I guess we could split it up into a `libkrb5` when we have users of it).

**Comment by DajianXu** [comment]
krb5 is not avaliable in 2025.09.16

**Pull request merged**
