### PR TITLE
Fix auto update failing for psutils

### PR DESCRIPTION
**Pull request by MrAdityaAlok**
- feat: add new package libpaper-rrthomas
- chore(psutils): update to 2.09

### CODE REVIEW

**Comment by MrAdityaAlok** [comment]
Someone please review whether naming `libpaper-rrthomas` is acceptable or not?

**Comment by xtkoba** [comment]
For `libpaper-rrthomas`:

* License should be `GPL-3.0, LGPL-3.0`.

* If upward-compatible with `libpaper` then set `TERMUX_PKG_REPLACES="libpaper"`. Otherwise please do add some hack so that it does not conflict with `libpaper`. Note that currently `texlive-bin` and `tuxpaint` depend on `libpaper`.

**Comment by xtkoba** [comment]
I suppose there is no compatibility between `libpaper` and `libpaper-rrthomas`.

**Comment by MrAdityaAlok** [comment]
> * If upward-compatible with `libpaper` then set `TERMUX_PKG_REPLACES="libpaper"`.

Doesn't seems to be. 

> Otherwise please do add some hack so that it does not conflict with `libpaper`. Note that currently `texlive-bin` and `tuxpaint` depend on `libpaper`.

It only uses `paper` binary from `libpaper` package, so statically linking and shipping with `psutils` itself should work too.

**Comment by MrAdityaAlok** [comment]
> I suppose there is no compatibility between `libpaper` and `libpaper-rrthomas`.

Sorry missed your comment and posted same thing again.

**Pull request merged**
