### PR TITLE
Fix(main/id3ted): typo

### PR DESCRIPTION
**Pull request by dntsdnts**

### CODE REVIEW

**Comment by 2096779623** [comment]
This repository has been archived by the owner on Sep 23, 2021. It is now read-only.

**Comment by xtkoba** [comment]
@2096779623 Please don't. It is by my decition that `id3ted` is packaged. You know what I mean?

**Comment by 2096779623** [comment]
> @2096779623 Please don't. It is by my decition that `id3ted` is packaged. You know what I mean?

Of course,maybe we need bump revision to update this info.
Similar to https://github.com/termux/termux-packages/pull/11851#issuecomment-1241717392 .

**Comment by xtkoba** [comment]
Not worth it.

**Pull request merged**
