### PR TITLE
Add Redis package

### PR DESCRIPTION
**Pull request by vaites**
Widely used cache server:

> [Redis](https://redis.io) is an open source (BSD licensed), in-memory data structure store, used as a database, cache and message broker. It supports data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs and geospatial indexes with radius queries. Redis has built-in replication, Lua scripting, LRU eviction, transactions and different levels of on-disk persistence, and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster.

Has both server and client... It can be tested with `redis-benchmark` command included in package (my OnePlus 3 reaches 11.000 requests/second).

screenshot_20170302-225133

### CODE REVIEW

**Comment by vishalbiswas** [comment]
I've got to ask. Where do you get ideas for adding packages?

**Comment by vaites** [comment]
It's a boring response: software I use for development on Linux...

**Comment by vishalbiswas** [comment]
@vaites anything related to software dev isn't boring to me.
Nice work! You have been doing great with these packages.

**Comment by vaites** [comment]
Thanks, the goal is to get a full featured mobile dev environment...

**Comment by vishalbiswas** [comment]
Sounds awesome. I have a similar goal: create Android apps on Android using termux easily.
Anyways, ever thought of creating your own repo? We have been discussing having custom repos in the gitter chat. Termux has a shortage of games it seems.

**Comment by vaites** [comment]
Making alternative repository makes no sense for me. I prefer to contribute to Termux community. 

Anyway, an official but separate repo for software that needs root is a good option, I have several packages that requires administrative permissions...

**Comment by fornwall** [comment]
Awesome work @vaites! The package is now available in the apt repository.

**Comment by vaites** [comment]
Thanks!

**Pull request merged**
