### PR TITLE
Add pacman

### PR DESCRIPTION
**Pull request by Maxython**
The time has come.

### CODE REVIEW

**Comment by Maxython** [comment]
I added them by accident.  I delete them.

**Comment by xeffyr** [comment]
@Maxython Host build won't make the difference. Issue happens when generating manpages and this step uses host tools only. I guess problem is with `a2x` utility version which could be lower than expected by pacman makefile.

**Comment by xeffyr** [comment]
```
builder@e1175f239a63:~/termux-packages$ a2x --version
a2x 9.0.0rc1
```

**Comment by Maxython** [comment]
It seems to me that you can already do a merge...

**Comment by Grimler91** [comment]
> It seems to me that you can already do a merge...

Please squash all your commits, we don't want to have ~15 commits with commit message "Fix bug" or "Test". Either leave @xeffyr's commits as they are, or squash them as well if he is fine with giving up authorship of them

**Pull request merged**
