### PR TITLE
bump(main/zig): 0.12.0

### LINKED ISSUE #19877: Zig 0.12.0
Update the Zig package to 0.12.0

### LINKED ISSUE #19958: Auto update failing for zig
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [zig](https://github.com/termux/termux-packages/blob/b9b67c0da75c32e4475b1615cb071d0040a6c921/packages/zig) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating zig [Current version: 0.11.0]
INFO: package being updated to 0.12.0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 17129    0 17129    0     0  45836      0 --:--:-- --:--:-- --:--:-- 45836
100 7088k    0 7088k    0     0  5195k      0 --:--:--  0:00:01 --:--:-- 7135k
100 13.7M    0 13.7M    0     0  5937k      0 --:--:--  0:00:02 --:--:-- 7044k
100 20.6M    0 20.6M    0     0  6271k      0 --:--:--  0:00:03 --:--:-- 7047k
100 27.5M    0 27.5M    0     0  6461k      0 --:--:--  0:00:04 --:--:-- 7061k
100 34.4M    0 34.4M    0     0  6573k      0 --:--:--  0:00:05 --:--:-- 7061k
100 40.7M    0 40.7M    0     0  6551k      0 --:--:--  0:00:06 --:--:-- 6922k
100 47.3M    0 47.3M    0     0  6586k      0 --:--:--  0:00:07 --:--:-- 6893k
100 53.8M    0 53.8M    0     0  6590k      0 --:--:--  0:00:08 --:--:-- 6805k
100 61.3M    0 61.3M    0     0  6707k      0 --:--:--  0:00:09 --:--:-- 6920k
100 65.5M    0 65.5M    0     0  6716k      0 --:--:--  0:00:10 --:--:-- 6882k

You are about to commit these changes:

--------------------
diff --git a/packages/zig/build.sh b/packages/zig/build.sh
index 4ddd41451..762c88be0 100644
--- a/packages/zig/build.sh
+++ b/packages/zig/build.sh
@@ -3,10 +3,9 @@ TERMUX_PKG_DESCRIPTION="General-purpose programming language and toolchain"
 TERMUX_PKG_LICENSE="MIT"
 TERMUX_PKG_LICENSE_FILE="zig/LICENSE"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION=0.11.0
-TERMUX_PKG_REVISION=2
+TERMUX_PKG_VERSION="0.12.0"
 TERMUX_PKG_SRCURL=https://github.com/ziglang/zig-bootstrap/archive/${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=046cede54ae0627c6ac98a1b3915242b35bc550ac7aaec3ec4cef6904c95019e
+TERMUX_PKG_SHA256=2c89261b7ba09c68bf0ccd0f5e081f10992f159ffc1dd4ea6959b91f56648c62
 TERMUX_PKG_BUILD_IN_SRC=true
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
--------------------

bump(main/zig): 0.12.0

Not committing to Git!

INFO: Trying to build package.
INFO: Package zig exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building zig for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  72314      0 --:--:-- --:--:-- --:--:-- 72563
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1979      0 --:--:-- --:--:-- --:--:--  1983
gpg: Signature made Fri 26 Apr 2024 12:20:47 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  30332      0 --:--:-- --:--:-- --:--:-- 30272
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   4875      0 --:--:-- --:--:-- --:--:--  4900
gpg: Signature made Thu 25 Apr 2024 12:58:02 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  73870      0 --:--:-- --:--:-- --:--:-- 74124
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2007      0 --:--:-- --:--:-- --:--:--  2007
gpg: Signature made Fri 26 Apr 2024 06:15:18 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://github.com/ziglang/zig-bootstrap/archive/0.12.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 6245k    0 6245k    0     0  4984k      0 --:--:--  0:00:01 --:--:-- 6939k
100 12.9M    0 12.9M    0     0  5864k      0 --:--:--  0:00:02 --:--:-- 6952k
100 19.8M    0 19.8M    0     0  6240k      0 --:--:--  0:00:03 --:--:-- 6996k
100 26.6M    0 26.6M    0     0  6414k      0 --:--:--  0:00:04 --:--:-- 6994k
100 33.5M    0 33.5M    0     0  6541k      0 --:--:--  0:00:05 --:--:-- 7011k
100 40.5M    0 40.5M    0     0  6617k      0 --:--:--  0:00:06 --:--:-- 7025k
100 46.9M    0 46.9M    0     0  6631k      0 --:--:--  0:00:07 --:--:-- 6977k
100 53.7M    0 53.7M    0     0  6660k      0 --:--:--  0:00:08 --:--:-- 6933k
100 61.1M    0 61.1M    0     0  6765k      0 --:--:--  0:00:09 --:--:-- 7064k
100 65.5M    0 65.5M    0     0  6769k      0 --:--:--  0:00:09 --:--:-- 7027k
Applying patch: build.patch
Applying patch: zig-lib-libc-musl-src.patch
Applying patch: zig-lib-std-os-linux.zig.patch
1 out of 3 hunks FAILED -- saving rejects to file zig/lib/std/os/linux.zig.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-04-27 00:34:23 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/8855729734">8855729734</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by TomJo2000**
Closes #19877
Closes #19958

### CODE REVIEW

**Comment by truboxl** [comment]
Thanks. I did not know need this little effort to upgrade. 😅

Unfortunately termux_setup_zig 0.12.0 breaks building ncdu2, outfieldr, zls.

If those packages are not updated or cannot be patched to build with zig 0.12.0.
we need to keep separate patches for 0.11.0 and 0.12.0 in packages/zig,
have those packages pinned to zig 0.11.0,
and let termux_setup_zig handle 0.11.0 and 0.12.0.

We can get inspiration from termux_setup_rust, termux_setup_golang.

**Comment by truboxl** [comment]
`zig init && zig build` is broken. Might want to hold off for now.

**Comment by TomJo2000** [comment]
Hi thanks for testing this, yeah I think we might wanna just hold off on this for a while.
I'll convert the PR to a draft for the time being.

**Comment by truboxl** [comment]
It seems the latest zig is more strict on the steps of compiling so no more short cuts in the compiling steps. `zig build` works now so let's merge this.

Outfieldr is disabled as the current one in the repo doesn't work at all. No revbump will help. The last commit only works with zig 0.9.1.

**Pull request merged**
