### PR TITLE
Add telegram-bot-api package

### PR DESCRIPTION
**Pull request by rom38**
Add telegram-bot-api package. Patch make redirect text to stdin  on android

### CODE REVIEW

**Review by Grimler91 — CHANGES_REQUESTED** [review]
Why are the vagrant changes necessary? Commit message doesn't provide any explanation

**Comment by rom38** [comment]
Vagrant changes not necessary, this is my own file. I am use vagrant for package building

**Review by Grimler91 — CHANGES_REQUESTED** [review]
Commit messages need to be squashed/rewritten. See [git history](https://github.com/termux/termux-packages/commits/master) to see format of previous commit messages, and/or pending guidelines in https://github.com/termux/termux-packages/pull/10748

**Comment by Grimler91** [comment]
> Vagrant changes not necessary, this is my own file. I am use vagrant for package building

Then leave it out of this PR

**Pull request closed without merging**
