### PR TITLE
mvpkg(x11/{angle-android/libepoxy,virglrenderer{,-android}}): move to main repo

### PR DESCRIPTION
**Pull request by twaik**
`angle-android` has no dependencies.
`libepoxy` depends only on `main/opengl`
`virglrenderer-android` depends only on `angle-android`
`virglrenderer` depends on `main/libdrm`, `libepoxy`, `main/libglvnd`, `main/libx11`, `main/mesa`
Since these libraries do not have X11 dependencies except `libx11` (which is in `main`) we can move all of them to main repo.

### CODE REVIEW

**Comment by twaik** [comment]
Ping @truboxl @Grimler91 @licy183 @TomJo2000 because you commited to virglrenderer{,-android}.

**Comment by licy183** [comment]
Please revbump them before merging.

**Comment by twaik** [comment]
Done

**Comment by twaik** [comment]
I will merge this in 96 hours if no one minds or after it gets 2+ approves.

**Review by licy183 — APPROVED** [review]
LGTM

**Pull request merged**
