### PR TITLE
ci: switch to 22.04

### PR DESCRIPTION
**Pull request by licy183**

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
hmm, maybe `docker` process is properly killed in latest version since trace is showing `+ DOCKER_PROCESS=`, so `set -e` is causing failure since `ps` is failing.

Try changing 

https://github.com/termux/termux-packages/blob/30ec184fb6aded58564119393613517e3b24b0f9/scripts/utils/docker/docker.sh#L41-L54

to

```
docker_process="$(ps -efww --pid "$pid" --no-headers -o pid:1,cmd || :)" && \
test -n "$docker_process" && \

DOCKER_PROCESS="$(ps -efww --pid "$DOCKER_PID" --no-headers -o pid:1,cmd || :)" && \
test -n "$DOCKER_PROCESS" && \
```

**Comment by agnostic-apollo** [comment]
Damn `set -u` too. Use `${DOCKER_PROCESS-}` and `${docker_process-}`.

**Comment by agnostic-apollo** [comment]
`docker_killtree "'"$signal"'" "$DOCKER_PID" || :` would be better.

**Comment by agnostic-apollo** [comment]
Also use a more descriptive commit message than `scripts/util/docker/docker.sh: fix bugs`. Something like `scripts/util/docker/docker.sh: Fix trap failing if docker process or subprocesses have already been killed or not found`

**Comment by licy183** [comment]
Thanks a lot @agnostic-apollo! I think this PR is ready for review now!

**Comment by agnostic-apollo** [comment]
You are very welcome. :)

The review part should be handled by package maintainers who are working on the update.

**Pull request merged**
