### PR TITLE
updates phase3

### PR DESCRIPTION
**Pull request by MrAdityaAlok**
- [x] feat(php-redis): enable auto-update, upgrade to 5.3.7
- [x] feat(php-psr): enable auto-update, upgrade to 1.2.0
- [x] feat(php-imagick): enable auto-update, upgrade to 3.7.0
- [x] feat(pdftk): enable auto-update, upgrade to 3.3.2
- [x] feat(p11-kit): enable auto-update, upgrade to 0.24.1
- [x] feat(osmium-tool): enable auto-update, upgrade to 1.14.0
- [x] feat(onefetch): enable auto-update, upgrade to 2.12.0
- [x] feat(nlopt): enable auto-update, upgrade to 2.7.1
- [x] feat(netcdf-c): enable auto-update, upgrade to 4.8.1
- [x] feat(ne): enable auto-update, upgrade to 3.3.1
- [x] feat(mpdscribble): enable auto-update, upgrade to 0.24
- [x] feat(mpd): enable auto-update, upgrade to 0.23.6
- [x] feat(miller): enable auto-update, upgrade to 6.2.0
- [x] feat(mdbook-toc): enable auto-update, upgrade to 0.8.0
- [x] feat(mdbook-open-on-gh): enable auto-update, upgrade to 2.0.2
- [x] feat(mdbook-mermaid): enable auto-update, upgrade to 0.10.0
- [x] feat(mdbook): enable auto-update, upgrade to 0.4.17
- [x] feat(mcfly): enable auto-update, upgrade to 0.6.0
- [x] feat(mbedtls): enable auto-update, upgrade to 3.1.0
- [x] feat(matterbridge): enable auto-update, upgrade to 1.25.0
- [x] feat(libzim): enable auto-update, upgrade to 7.2.0
- [x] feat(libwebsockets): enable auto-update, upgrade to 4.3.1
- [x] feat(libvpx): enable auto-update, upgrade to 1.11.0
- [x] feat(libvmaf): enable auto-update, upgrade to 2.3.1

### CODE REVIEW

**Comment by xtkoba** [comment]
Upgrading `libvpx` from `1.10.0` to `1.11.0` causes `SOVERSION` change (from `6` to `7`). Please also revbump revdeps and rebuild them:

* `ffmpeg`
* `gst-plugins-good`
* `tizonia`
* `tvheadend`
* `vlc`

**Comment by MrAdityaAlok** [comment]
> Upgrading `libvpx` from `1.10.0` to `1.11.0` causes `SOVERSION` change (from `6` to `7`). Please also revbump revdeps and rebuild them:
> 
> * `ffmpeg`
> * `gst-plugins-good`
> * `tizonia`
> * `tvheadend`
> * `vlc`

Sure! Will do that too.

**Comment by MrAdityaAlok** [comment]
@xtkoba would you please help in this. This is the error generated while building `quick-js-lint`:
```
/home/builder/.termux-build/quick-lint-js/src/vendor/boost/libs/container/src/pool_resource.cpp:240:21: error: out-of-line definition of 'do_is_equal' does not match any declaration in 'boost::container::pmr::pool_resource'
bool pool_resource::do_is_equal(const memory_resource& other) const BOOST_NOEXCEPT //virtual
                    ^~~~~~~~~~~
1 error generated.
```
I do not know much about `c++`.

**Comment by thunder-coding** [comment]
> @xtkoba would you please help in this? This is the error generated while building quick-js-lint

Can you share the full command invoked by make/ninja with all the command line flags passed to clang along with some surrounding lines of logs. I guess it's adding `-I/usr/include` to the flags passed to clang and hence it is causing this error.

**Comment by MrAdityaAlok** [comment]
>I guess it's adding `-I/usr/include` to the flags passed to clang and hence it is causing this error.

Thank you! Indeed that was the problem. ;) Fixed now.

**Comment by xtkoba** [comment]
Please do not upgrade `openexr2` to `3.1.5`. This package is kept for `2.x.y` series only. If necessary provide the `openexr` package (without `2` suffix) instead.

**Comment by MrAdityaAlok** [comment]
> Please do not upgrade `openexr2` to `3.1.5`. This package is kept for `2.x.y` series only. If necessary provide the `openexr` package (without `2` suffix) instead.

Yes, yes. I read your comment in your PR and removed it locally.

**Pull request merged**
