### PR TITLE
Move libusb to termux-root-packages

### PR DESCRIPTION
**Pull request by Wetitpig**
I have built libusb for all 4 arches and I cannot find any errors. I don't see why do we put them in the disabled-packages section.

Attached is the [log](https://github.com/termux/termux-packages/files/1742783/libusb.log) for the build of libusb for all 4 arches.

Thanks!

### CODE REVIEW

**Comment by joakim-noah** [comment]
In order to use this library to actually access USB on your Android device, would the Termux app need extra permissions?

**Comment by Wetitpig** [comment]
So should we move this to root-packages?

**Comment by tomty89** [comment]
Probably
```
$ /system/bin/lsusb
lsusb: No /sys/bus/usb/devices/: Permission denied
$
```

**Comment by Wetitpig** [comment]
Ok I will try now

**Comment by Auxilus** [comment]
Do we need two PRs for the same package?

**Comment by Wetitpig** [comment]
@Auxilus where

**Comment by Auxilus** [comment]
Oh, okay 😅

**Comment by Grimler91** [comment]
Wouldn't libusb still be useful for compiling packages requiring libusb? 
Those packages wouldn't work without root however, as you've discussed.
I guess it depends on how we draw the line between termux-packages and termux-root-packages.

**Comment by Wetitpig** [comment]
Then won’t those packages also require root access?

**Comment by Wetitpig** [comment]
@Grimler91 Is there a function that can run without root in the library?

**Comment by Auxilus** [comment]
@Wetitpig  libusb is a `library` it's not a front end package, so it doesn't require root to install, like @Grimler91  said it depends on how we draw the line between termux-packages and termux-root-packages

**Comment by Auxilus** [comment]
I think the libraries should be in `termux-packages`

**Comment by Wetitpig** [comment]
@Auxilus @Grimler91 Install never requires root. It’s only using it that requires root. The main point should be whether it can function without root.

**Comment by Grimler91** [comment]
@Wetitpig then it depends on how we define "to function", I see it as that libusb's function is to enable other packages to be linked to it with `-lusb`, this will work without errors. 
Those other packages would require root to function though (currently, termux-api can include usb functionality in the future).

**Comment by Wetitpig** [comment]
So not **ALL** programs linked with libusb require root?

**Comment by Wetitpig** [comment]
Otherwise, it is quite useless to keep the lbrary only while it cannot compile any packages that do not need root.

**Comment by Grimler91** [comment]
Libusb is now available from the [root repo](https://github.com/termux/termux-root-packages/commit/a10e4194ee809bfc2c069fa38dd82c6ad402ed33) so this can be merged.

**Pull request merged**
