### PR TITLE
New Package: Chafa

### PR DESCRIPTION
**Pull request by Yonle**
Fixed mess of #7488

### CODE REVIEW

**Comment by xeffyr** [comment]
Does it provide something new besides what `termimage`, `timg`, `jp2a` can do?

**Comment by Yonle** [comment]
Yes. There's a difference between those package with `Chafa`

**Comment by xeffyr** [comment]
Which exactly?

**Comment by Yonle** [comment]
Gah. Can't tell the difference between those package with Chafa. But there's also a test:
Screenshot_2021_0908_110314
Screenshot_2021_0908_110609

**Comment by xeffyr** [comment]
`timg` has similar, if not exact or even better, image quality. Also supports animations and video output (quite smooth btw). Additionally `timg` has image gallery feature. So I'm curious, *why need another one image viewer if it doesn't add anything new*?

https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy
> ...requested packages should met these conditions:
> * Not serving duplicated functionality
> 
>    Please avoid submitting packages which duplicate functionality of already present ones

**Comment by Yonle** [comment]
After some search, Chafa, has a feature like 

* `watch` that used to watch a file then change output whenever the file content is changed
* color mode which can reduces how many color thatvwe should view
* There's also a way to change output format like `iterm`, `kitty`, `sixel`, and more so like that.
* There's also a option to invert a video.

Well, maybe opening this PR to put some alternative.

**Comment by xeffyr** [comment]
Ok, merging it now. Just know that I'm against any duplicate stuff, unless there is a strong reason to have it added. Repository size is already went beyond the expected disk space usage
```
/dev/vda1        32G   17G   15G  52% /
```
I really what will be if we decide will add repository with Android APK package format (for https://github.com/termux/termux-app/issues/2155), as that effectively will use 2x more space than we're using now.

So next time please add things that will be useful for everyone and not because you've just discovered it and was able to compile. There are still a lot of packages pending to be added.

**Pull request merged**
