### PR TITLE
Updates for some disabled packages and add net-tools

### PR DESCRIPTION
**Pull request by vishalbiswas**
I'm thinking about enabling squid.
openvpn is still broken

### CODE REVIEW

**Comment by fornwall** [comment]
Thanks! I made two follow up commits:

- https://github.com/termux/termux-packages/commit/5d0b5cf9702f9032c0f775e03c02678215b54c33: Remove the custom `termux_step_make`, the default should do what we want here (let me know if I'm missing something!).

- https://github.com/termux/termux-packages/commit/fb4b3a2a75d70b21ee57ba657243460d86f55e5e: Fix `SBINDIR` to be `$PREFIX/bin`, not `$PREFIX`.

**Comment by Wetitpig** [comment]
net-tools build is failing now. Does anyone know what happened?

It happened at the `patch --silent -p1` command.

**Comment by fornwall** [comment]
Hm, for me the problem is the download step.

I think the problem is that the URL for downloading a snapshot from a commit,

    https://sourceforge.net/code-snapshots/git/n/ne/net-tools/code.git/net-tools-code-$_commit.zip

only works for a time after someone requested it to be generated (by pressing the download button on sourceforge) - perhaps sourceforge puts that in a cache that is purged after some time.

**Comment by Wetitpig** [comment]
I have changed the URL to `https://downloads.sourceforge.net/project/net-tools/net-tools-${TERMUX_PKG_VERSION}.tar.bz2?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fnet-tools%2Ffiles%2F%3Fsource%3Dnavbar&ts=1492253513&use_mirror=nchc`

and SHA256 sum to `7ae4dd6d44d6715f18e10559ffd270511b6e55a8900ca54fbebafe0ae6cf7d7b`.

Then it fails at the patch step.

**Comment by fornwall** [comment]
@Wetitpig You are probably downloading something else than the desired source, which is why you needed to change the checksum and the patch step fails.

**Comment by fornwall** [comment]
@Wetitpig I've pushed https://github.com/termux/termux-packages/commit/51e8d739a152f4cf1f4fffcb95a6547b2e808527 which switches net-tools to use a mirror, so it should work now if you pull in that update.

Thanks for reporting!

**Pull request merged**
