### PR TITLE
new package: iwyu (include-what-you-use)

### LINKED ISSUE #5382: Package request: include-what-you-use
**Package description**
IWYU is another static analysis tool for C/C++ languages where it examines every symbol and adds the appropriate `#include` directives for you.

**Link to home page and sources**
1. [Home page:](https://github.com/include-what-you-use/include-what-you-use)
2. [Source code:](https://github.com/include-what-you-use/include-what-you-use)

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
```
 ~/www/cpp/include-what-you-use/build   master  cmake -G "Unix Makefiles" -DIWYU_LLVM_ROOT_PATH=/usr/lib/llvm-6.0 ../                                                                                   127 ↵
-- IWYU: out-of-tree configuration
CMake Error at /data/data/com.termux/files/usr/lib/cmake/llvm/LLVMExports.cmake:1265 (message):
  The imported target "LLVMDemangle" references the file

     "/data/data/com.termux/files/usr/lib/libLLVMDemangle.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/data/data/com.termux/files/usr/lib/cmake/llvm/LLVMExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /data/data/com.termux/files/usr/lib/cmake/llvm/LLVMConfig.cmake:243 (include)
  CMakeLists.txt:19 (find_package)


-- Configuring incomplete, errors occurred!
See also "/data/data/com.termux/files/home/www/cpp/include-what-you-use/build/CMakeFiles/CMakeOutput.log".
```

Latest clang, cmake, llvm and libllvm installed.
* If it did work then please share any patches that you had to apply.

### PR DESCRIPTION
**Pull request by landfillbaby**
closes #5382

currently just testing build

### CODE REVIEW

**Comment by landfillbaby** [comment]
i really should have split this into 2 PRs. i have no idea if i have the dependencies right

**Comment by landfillbaby** [comment]
maybe i should name the package just iwyu, like debian does

**Comment by xeffyr** [comment]
Yes, `iwyu` name is much shorter.

**Comment by xeffyr** [comment]
@buttaface Do you know if there was a specific reason for `clang-import-test` being removed?

**Comment by buttaface** [comment]
No idea, it was always removed before, so I just kept it that way, d6e574615c.

**Comment by landfillbaby** [comment]
currently testing building this without clang-import-test. it's never directly referenced in the current code

**Comment by xeffyr** [comment]
Absent `clang-import-test` causes some \*.cmake files of libllvm to fail. I had fixed this in https://github.com/termux/termux-packages/commit/44e01053304950e5fa5780fd270eb3e20afd2283, but `clang-import-test` was added again into removal list.

**Comment by buttaface** [comment]
I think this was a mixup, because my commit was written April 10, two months before your fix, but only merged as part of the NDK 21 update last month, #5251. You can probably include those now, assuming @fornwall never had a good reason to remove them or that's outdated.

**Comment by landfillbaby** [comment]
alright then. should any of the remaining rm_after_install stuff be left in too?

**Comment by landfillbaby** [comment]
i guess actually i should leave clang-offload-wrapper too since according to the lldb build script it breaks. idk about the multiprocessing libs though

**Comment by landfillbaby** [comment]
i know from an earlier push that it builds, but is it good for merging? idk

**Comment by landfillbaby** [comment]
might open separate issues about the lib[g]omp stuff and maybe about splitting up more llvm subpackages, like, clang-extras or something

**Pull request merged**
