### PR TITLE
Add package : gperf

### PR DESCRIPTION
**Pull request by Auxilus**

### CODE REVIEW

**Comment by Auxilus** [comment]
dependency for https://github.com/termux/termux-packages/pull/1769

**Comment by Auxilus** [comment]
dependency for https://github.com/termux/termux-packages/pull/1769

**Comment by Auxilus** [comment]
dependency for https://github.com/termux/termux-packages/pull/1769

**Comment by xeffyr** [comment]
When using gperf in termux, there may be errors about 'size_t'.

Example (test.gperf):
```
%ignore-case
%language=C++
%define lookup-function-name Lookup
%define class-name Functions
struct TType
%%
####
ONE,    Test::One
TWO,    Test::Two
THREE,  Test::Three
####
%%
```
Generating test.cpp with ```gperf test.gperf > test.cpp```.
And compiling:
```
~/gperf ➤ clang++ -c test.cpp
test.cpp:84:53: error: unknown type name 'size_t'
  static inline unsigned int hash (const char *str, size_t len);
                                                    ^
test.cpp:86:47: error: unknown type name 'size_t'
  static const char *Lookup (const char *str, size_t len);
                                              ^
test.cpp:90:35: error: unknown type name 'size_t'
Functions::hash (const char *str, size_t len)
                                  ^
test.cpp:125:37: error: unknown type name 'size_t'
Functions::Lookup (const char *str, size_t len)
                                    ^
4 errors generated.
```

**Patch to fix errors:**
```
diff -uNr gperf-3.1/src/output.cc gperf-3.1.mod/src/output.cc
--- gperf-3.1/src/output.cc	2017-01-02 13:35:39.000000000 +0200
+++ gperf-3.1.mod/src/output.cc	2017-10-26 16:11:06.170061729 +0300
@@ -2083,6 +2083,16 @@
     }
   printf ("\n");
 
+  // Include stdlib.h or cstdlib header to fix errors about size_t
+  if (option[KRC] || option[C] || option[ANSIC])
+    {
+      printf("#include <stdlib.h>\n\n");
+    }
+  else if (option[CPLUSPLUS])
+    {
+      printf("#include <cstdlib>\n\n");
+    }
+
   if (_charset_dependent
       && (_key_positions.get_size() > 0 || option[UPPERLOWER]))
     {
```

**Comment by Auxilus** [comment]
@xeffyr Thanks for the review!

**Comment by fornwall** [comment]
Thanks - the updated package is now available for installation!

**Pull request merged**
