### PR TITLE
termux-tools: setting for working with pacman (for pacman format)

### PR DESCRIPTION
**Pull request by Maxython**
#8250

### CODE REVIEW

**Review by tvfmmfvt — COMMENTED** [review]
No.

**Comment by Maxython** [comment]
> Нет.

Why no?

**Review by xeffyr — CHANGES_REQUESTED** [review]
Use **one** script for both package types. You can preprocess it with `sed` to enable/disable specific parts. Any duplicates are strongly discouraged as probably won't be maintained.

Btw I thought that we already discussed this. If you really need a script copy, please keep it in your fork.

**Comment by xeffyr** [comment]
Replaced by https://github.com/termux/termux-packages/commit/05d57dc5cb48a0b1ea90b1a02d6aee977fd0e568.

**Comment by Maxython** [comment]
> Btw I thought that we already discussed this. If you really need a script copy, please keep it in your fork.

I don't do this because file conflicts can occur.  They are created when the repo is updated from the root repo.  In case of a conflict, they change the content so that compilation cannot compile the package or the command itself will not work.

And yes thanks for did my job :)

**Pull request closed without merging**
