### PR TITLE
new package: gpac

### LINKED ISSUE #6708: Add mp4box and gpac package
Request to add the package mp4box (GPAC), which is a multimedia processor similar to ffmpeg.
https://github.com/gpac/gpac/wiki/MP4Box

### PR DESCRIPTION
**Pull request by xtkoba**
Closes #6708.

### CODE REVIEW

**Review by xeffyr — APPROVED** [review]

**Comment by superbonaci** [comment]
How to I install this package, already available to `pkg install gpac`?

**Comment by buttaface** [comment]
It may not have gotten uploaded properly by the CI.

**Comment by Grimler91** [comment]
Hopefully fixed once build in https://github.com/termux/termux-packages/actions/runs/1699407414 finishes

**Comment by superbonaci** [comment]
Latest compilation has failed.

**Comment by Grimler91** [comment]
@superbonaci yepp, but should be fixed now

**Comment by superbonaci** [comment]
Now it's working.

**Pull request merged**
