### PR TITLE
Enable more util-linux programs

### PR DESCRIPTION
**Pull request by Grimler91**
This PR enables libmount, libfdisk and libuuid. All libraries are also split into subpackages, to allow finer control of installed packages, e2fsprogs only needs to depend on libblkid, and not the full util-linux package for example.

Enabling libuuid means that we have to remove our standalone libuuid package, and all packages depending on libuuid rebuilt.
util-linux's libuuid comes with uuidgen, which is a required tool for building some packages on device. 

TODO:

* [x] test and iron out any remaining issues with the modified packages
* [x] remove mount and umount from termux-tools
* [x] bump/modify qt5-qtbase and swift as well (not included here, will check so these packages are buildable first)
* [ ] check if bootstrap script needs to be updated
* [x] ~~remove or change util-linux dependency from termux-tools (?)~~

Fixes termux/termux-packages#10207

### CODE REVIEW

**Comment by Grimler91** [comment]
I can't reproduce the current build error locally. $CPP check fails, seems to be same/similar error as I saw for ndk-r25 branch before.

In CI we got:
```
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking how to run the C preprocessor... x86_64-linux-android-cpp
checking for x86_64-linux-android-cpp... /home/builder/.termux-build/_cache/android-r23c-api-24-v0/bin/x86_64-linux-android-cpp
clang-12: error: no input files
clang-12: error: no input files
clang-12: error: no input files
configure: error: /home/builder/.termux-build/_cache/android-r23c-api-24-v0/bin/x86_64-linux-android-cpp defines unix with or without -undef.  I don't know what to do.
checking if /home/builder/.termux-build/_cache/android-r23c-api-24-v0/bin/x86_64-linux-android-cpp requires -undef... 
Error: Process completed with exit code 1.
```

while locally, where it works:

```
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for cpp... /usr/bin/cpp
checking if /usr/bin/cpp requires -undef... yes
checking if /usr/bin/cpp requires -traditional... yes
```

so let's try again after unsetting CPP for tigervnc I guess

**Comment by Grimler91** [comment]
Upgrades should work without conflict now, and packages seem to work. I'll aim to merge this in around 12 hours.

Update of bootstrap scripts will be done after merging.

**Comment by buttaface** [comment]
This pull broke the Swift compiler when bumping it:
```
CANNOT LINK EXECUTABLE "swift": library "libandroid-execinfo.so" not found: needed by main executable
```
My guess is that one of the other packages modified by this pull leaks adding that library somewhere, and that has corrupted other packages like Swift built in the same CI run.

@Grimler91 or @xtkoba, any idea which one that is? May be a quick fix for one of you, will require bumping Swift and perhaps other packages from this pull again.

**Comment by Grimler91** [comment]
I would guess it swift linked opportunistically against libexecinfo.so, my bad. Maybe there is a way to prevent this from happening for swift (I had a look but didn't see any obvious --disable-execinfo flag or env var).

Lets bump it again to get rid of the dependency

**Comment by buttaface** [comment]
> I would guess swift's configure system checked for libexecinfo.so, found it and linked against it.

No, Swift uses CMake exclusively, and I bet none of its build is aware of our libandroid-execinfo. More likely some other Termux package is adding `-landroid-execinfo` somewhere and that is leaking into building subsequent packages somehow, but that is just a guess.

**Comment by buttaface** [comment]
Looked into this and you are probably right, @Grimler91, [previously a standalone Swift build wouldn't find a backtrace library](https://github.com/termux/termux-packages/actions/runs/3694686509/jobs/6256523981#step:6:2559), whereas this pull's build does:
```
 -- Found Backtrace: /data/data/com.termux/files/usr/lib/libexecinfo.so
```
I was unaware that we were adding a `libexecinfo.so` also, looks like the Swift CMake build is picking that up because postgresql was built first in this CI run. The standalone Swift bump you just committed should fix this.

**Pull request merged**
