### PR TITLE
new package: manim

### PR DESCRIPTION
**Pull request by nguynkhn**

### CODE REVIEW

**Comment by nguynkhn** [comment]
Didn't see `python-scipy` blacklisting some architectures...

**Comment by Biswa96** [comment]
Did it work in your setup?

**Comment by nguynkhn** [comment]
It does run properly but can only be built in the host machine. I'm not really sure since I can build manually on Termux Android device without any problems.
I'm still thinking of some way to install the pip dependency without having to compile Skia to static library and then remove it (to avoid collision I guess) after installation.

**Comment by nguynkhn** [comment]
GitHub Actions said there wasn't enough free space to build package so it's not my fault.

**Pull request closed without merging**
