### PR TITLE
Added youtube-dl

### PR DESCRIPTION
**Pull request by MD5HashBrowns**
youtube-dl is a python program that lets you download videos from YouTube as well as some other sites.

### CODE REVIEW

**Comment by mklein994** [comment]
This program can also be installed with pip via `pip install youtube-dl`. See #604.

@fornwall what should be the rule with these kind of pull requests? Should we leave these up to their respective package managers, or include them as `apt` packages for convenience? The same could be said for Ruby gems, Perl CPAN modules, JavaScript npm packages, etc.

**Comment by TheDiamondYT1** [comment]
Keep them to the respective package managers.

**Comment by TheDiamondYT1** [comment]
An interesting idea would be to add a load of known python dependency names to `command_not_found` and then show the user the command to install it. And maybe even add a patch to `apt` to check the pip repository or somethig idk.

**For example:**
```bash
$ youtube-dl
Package 'youtube-dl' not found.
Install it by executing 'pip install youtube-dl'

-- OR --

$ apt install youtube-dl
The package 'youtube-dl' cannot be found in the APT repository, however it is available in the PIP repository. 
Install it by executing 'pip install youtube-dl'
```

**Comment by fornwall** [comment]
In general it would be best to avoid packaging things available from pip/gem/npm/cpan/etc - it's simply too much duplicated work to keep up with.

We can make rare exceptions, especially if

1. The program is usually not installed from the language-specific package manager (users install it without knowing which language it's written in).
2. The program is popular.
3. The program is easy to build (and thus maintain&update as a Termux package).

I guess `youtube-dl` could be one of these exceptions, as it's rather popular and not normally installed from pip (or is it? how do people normally install it)?

**Comment by MD5HashBrowns** [comment]
@fornwall I've always installed youtube-dl through a package manager in the past, however their site does suggest using pip (or curl/wget). I think youtube-dl could qualify as an exception, but using pip works just as good.

**Comment by tinydynamite00** [comment]
The version of youtube-dl I see in Debian repositories, where it's treated as a package, is always outdated. The module is updated frequently, sometimes daily. Installing and upgrading with either pip 2 or 3 is preferable to ensure users are on the most up-to-date version.

**Comment by MD5HashBrowns** [comment]
Alright, seems like the best idea is to leave it up to pip.

**Comment by TheDiamondYT1** [comment]
M8

**Pull request closed without merging**
