### PR TITLE
addpkg(x11/gedit): Add gedit package

### LINKED ISSUE #19985: [Package]: gedit and NEdit (nirvana text editor)
### Why is it worth to add this package?

NEdit(Nirvana text editor) is a great editor and it's especially great at loading huge files, it supports Unicode and lots of features and it's fast.
gedit is also a well-known text editor which is quite useful when you plan on using x11/ a desktop along with termux.
I checked and none of these text editors are available at the time of writing this request 

### Home page URL

_No response_

### Source code URL

https://sourceforge.net/projects/nedit/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

here's nedits project page : 
https://sourceforge.net/projects/nedit/

and here's gedit website: 
https://www.gedit.org/

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes #19985

### CODE REVIEW

**Comment by Biswa96** [comment]
The only thing that these build scripts are missing is soversion check. Please feel free to add those soversion check. Someone from Feiyun Commerce Guild helped to add those check previously :slightly_smiling_face:

**Comment by licy183** [comment]
I'll merge this PR tomorrow morning if there is no more review. Thanks!

**Comment by Biswa96** [comment]
GitHub Actions failed in the merged commit.

**Comment by Grimler91** [comment]
Re-running

**Pull request merged**
