### PR TITLE
bump(libllvm): 16.0.6 to 17.0.2

### PR DESCRIPTION
**Pull request by finagolfin**
Once this passes CI, download these candidate packages from the CI and test them out for yourself in preparation for the upcoming LLVM 17 release.

### CODE REVIEW

**Comment by finagolfin** [comment]
Downloaded and ran [the AArch build from the CI](https://github.com/termux/termux-packages/actions/runs/6068162512) with the following commands, no problem:
```
unzip ~/storage/downloads/debs-aarch64-82d065063eda3363d5f2ac7c193d9cac0d08606c.zip
tar xf debs-aarch64-82d065063eda3363d5f2ac7c193d9cac0d08606c.tar
apt remove libllvm
dpkg -i debs/*.deb
apt install swift
git clone https://github.com/apple/swift-crypto.git
cd swift-crypto
swift test
```
Let me know if you have any issues with any of these LLVM 17 builds, I will keep updating these RC tags until the release.

**Comment by finagolfin** [comment]
I still need to update the libraries in the `llvm-config.in` b

**Comment by finagolfin** [comment]
Damn mobile keyboard.

**Comment by finagolfin** [comment]
@xJonathanLEI or @truboxl, merging this will break the rust package, any one going to get that updated next? I will be updating the Swift package in the next couple days.

**Comment by xJonathanLEI** [comment]
IIUC the `rust` package is maintained by @xtkoba?

**Comment by finagolfin** [comment]
He has left the Termux org and does not contribute any more: [his last commit was two and a half months ago](https://github.com/termux/termux-packages/commits?author=xtkoba).

**Comment by xJonathanLEI** [comment]
Ah that's said to know. I only ever made two small patches to the `rust` package but I can take a stab at it.

**Comment by xJonathanLEI** [comment]
Have been wondering how come we're still on `1.70.0` lol.

**Comment by finagolfin** [comment]
Great, if you are building locally, I suggest applying this pull, downloading these deb files from the CI and putting them in `.termux-build/_cache-aarch64/`, then updating the rust package.

**Comment by xJonathanLEI** [comment]
Sorry if this is obvious. Can I just checkout to this PR, build `libllvm`, then test the `rust` package by `./build-package.sh -I rust`?

**Comment by finagolfin** [comment]
Sure, that works too, just trying to save you time and disk space by downloading the CI-built packages. 😃

**Comment by truboxl** [comment]
Rust need 1.73.0 to work with LLVM 17
https://github.com/rust-lang/rust/pull/114048

Can make an exception to use latest git for Rust I think since I don't see it releasing until October...
https://releases.rs/docs/1.73.0/

**Comment by finagolfin** [comment]
Can that upstream pull simply be applied to the latest rust release instead?

**Comment by truboxl** [comment]
Sure. I can bump Rust to 1.72.1 first to unblock #17868 then work on Rust 1.72.1 + LLVM 17 patch...

**Comment by finagolfin** [comment]
Alright, this pull is ready, just giving everyone time to work on bumping dependent packages like rust and swift, which I'm working on updating to 5.9, before merging.

**Comment by finagolfin** [comment]
17.0.2 is out, Swift 5.9 is ready to go. Once rust 1.73.0 is released this week and @truboxl says it is ready to go, I will merge this, then we can get those dependent package updates in.

**Comment by finagolfin** [comment]
Huh, libllvm builds were not completing in Docker anymore, but just did once I shifted the build to the github VM instead. Going to go ahead and merge that pull, while this will wait until rust 1.73 is ready.

**Comment by finagolfin** [comment]
We need to look into bumping all other llvm-dependent packages, like zig or iwyu. @twaik, any interest in helping out with those?

**Comment by twaik** [comment]
My current priority is to catch al low hanging fruits and bump all the packages that is easy to bump. I can fix patch in the case if source of package was modified insignificantly, but I am not sure I am skilled enough to patch such a complicated thing as llvm.

**Comment by finagolfin** [comment]
> I am not sure I am skilled enough to patch such a complicated thing as llvm.

LLVM is done: the issue now is finding all packages that depend on it and bumping those to rebuild against 17.0.2, if possible. The two major ones, rust and swift, are done, now need to try all the smaller ones that depend on LLVM.

**Comment by twaik** [comment]
Reverse dependencies are:
```
  binutils-is-llvm
  ccls
  clang
  crystal
  flang
  ghc
  libcompiler-rt
  libllvm-static
  libpolly
  lld
  lldb
  llvm
  llvm-mingw-w64
  llvm-tools
  llvmgold
  mlir
  qt-creator
  rust
  wasmedge
```

Should I rebuild all of them?

**Comment by finagolfin** [comment]
Many of those are already done; we need to open pulls for the few remaining like ccls and update them if possible.

**Comment by twaik** [comment]
Done. There is some problem with wasmedge, for some reason arm build failed. I am not revbumbing it.

**Comment by twaik** [comment]
Ghc does not want to be built on arm... https://github.com/termux/termux-packages/actions/runs/6529314922/job/17726795890

**Comment by finagolfin** [comment]
Anything that doesn't work, we'll have to talk to those who maintained it before. We just need to try buildinh each one and check if upstream has a new version that works with LLVM 17, that's it.

**Pull request merged**
