### PR TITLE
ndk-stl: include libstdc++ headers

### LINKED ISSUE #2273: can't compile berkeley-db with cxx support
This should reproduce the issue:

```
pkg install make clang proot
wget http://download.oracle.com/berkeley-db/db-6.2.32.tar.gz
tar xvf db-6.2.32.tar.gz
cd db-6.2.32/build_unix
termux-chroot ../dist/configure --enable-cxx
termux-chroot make -j30
```

Once the build has run to error, you can reproduce quickly by running the command directly:
```
bash-4.4$ g++ -c -I. -I../src -D_GNU_SOURCE -D_REENTRANT -O3 ../lang/cxx/cxx_channel.cpp  -fPIC -DPIC -o .libs/cxx_channel.o
In file included from ../lang/cxx/cxx_channel.cpp:13:
In file included from ./db_cxx.h:55:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/iostream:38:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/ios:216:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/__locale:15:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/string:470:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/string_view:169:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/__string:56:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/algorithm:643:
In file included from /data/data/com.termux/files/usr/bin/../include/c++/v1/memory:658:
/data/data/com.termux/files/usr/bin/../include/c++/v1/atomic:1184:13: error: expected unqualified-id
atomic_init(volatile atomic<_Tp>* __o, _Tp __d) _NOEXCEPT
            ^
```

I've tried changing the standards version (e.g. `-std=c++98`) and tried changing the stdlib (`--stdlib=libstdc++`). The standards version has no effect and the libstdc++ seems to be missing entirely.

The compile seems to be sad about `/usr/include/c++/v1/atomic` which is from the `ndk-stl` package.

### PR DESCRIPTION
**Pull request by tomty89**
Fixes #2273

### CODE REVIEW

**Comment by tomty89** [comment]
Hmm seems like the path were different in r16? (I have only r16b at the moment)

**Comment by tomty89** [comment]
Or is it just Travis CI acting up? #2274 has similar error as well, but it shouldn't.

**Comment by bukzor** [comment]
@tomty89 A trick that might be helpful here: do a noop amend and push -f to force travis to re-run the pull request. 

```
git commit --amend --no-edit
git push -f origin HEAD
```

**Comment by tomty89** [comment]
I confirmed that the paths are the same in NDK r16, so it should be good to be merged.

@bukzor I don't think it's gonna help coz it doesn't appear to be some timeout error. No idea what's broken exactly though. In any case I re-pushed once yesterday because of some comestic issue, and it still failed to build the second time.

**Comment by tomty89** [comment]
Ahh there's a script that strips files from the docker image. Updated the commit for that.

It probably won't take effect in Travis CI automatically, just like the case in the ecj PR (where the `sdkmanager` line in the setup script is updated).

**Comment by tomty89** [comment]
Commits are updated to ship libstdc++ headers in a split package since they are kind of huge

**Comment by tomty89** [comment]
Added a commit to fix the subpackage creation.

**Comment by fornwall** [comment]
Note that gnustl (which is called libstdc++) has the following problems:

- The version included in the NDK has not been updated in a long time.
- It does not work very well with clang.
- Google is dropping support for using gnustl on Android (it has already been removed from NDK git master, to be released as NDK r18).

So I don't think it is worthwhile to introduce temporary support of gnustl here - it's better to focus on improving how libc++ works (patching software if necessary).

**Comment by bukzor** [comment]
Good to know. Thanks!

**Pull request closed without merging**
