### PR TITLE
apt: fix build on ndk r27

### LINKED ISSUE #21116: [Bug]: apt fails to build with ndk r27
### Problem description

apt 2.8.1 fails to compile with ndk r27 but it was successfully compiled with previous ndk r26. The actual compiler error is as following.

```
depcache.cc:1343:12: note: in instantiation of function template specialization 'std::sort<APT::Container_iterator<APT::VersionContainerInterface, std::vector<pkgCache::VerIterator>, APT::VersionContainer<std::vector<pkgCache::VerIterator>>>, CompareProviders>' requested here
 1343 |       std::sort(verlist.begin(), verlist.end(), CompareProviders{Cache, Start});
      |            ^
```

Full error output can be found in this report https://lists.debian.org/deity/2024/08/msg00013.html

### What steps will reproduce the bug?

Just run `./build-package.sh -I apt` in package builder container.

### What is the expected behavior?

apt should compile without any error.

### System information

```shell
¯\_(シ)_/¯
```

### PR DESCRIPTION
**Pull request by licy183**
Closes #21116

### CODE REVIEW

**Comment by fornwall** [comment]
Nice! @licy183, can you submit a merge request upstream (https://salsa.debian.org/apt-team/apt) as well?

**Comment by licy183** [comment]
Emmm... I just registered an account at Debian Salsa.

**Comment by fornwall** [comment]
To be clear, I think this PR is fine and low risk and can be merged now, and the upstream submission can be made async.

**Comment by licy183** [comment]
I'll merge this tomorrow if there is no more review. Thanks!

**Comment by Biswa96** [comment]
The patch was added in upstream https://salsa.debian.org/apt-team/apt/-/commit/b4488583424b33f51cb031562a9e8df820ffda23 🎉

**Pull request merged**
