### PR TITLE
Add libusb and gpsbabel

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
Hi @fornwall, it's not super important to me, but could you at least give a reason instead of closing this without a comment? Thanks :).

**Comment by fornwall** [comment]
@jspricke Sorry, I was going through old PR:s and may have been to quick here!

I thought I remembered that libusb did not work on Android - what is the status there?

**Comment by jspricke** [comment]
I had libusb and gpsbabel running on Android 4, as documented here:

http://gpsbabel.2324879.n4.nabble.com/gpsbabel-on-Android-including-Garmin-USB-td10312.html

As far as I remember, I wasn't able to make usb work with termux on
Android 5, but maybe this could serve as a start. Also, gpsbabel is
useful without usb access, So I would be happy if this could be merged.

**Comment by fornwall** [comment]
Ok, thanks for the information, and sorry for the huge delay here - I will be more responsive in the future!

gpsbabel is now finally available as a package available for installation. It's built without libusb support, it could be added in the future if it can be made to work.

**Pull request closed without merging**
