### PR TITLE
libarrow-cpp: upgrade to 9.0.0 and enable parquet feature

### PR DESCRIPTION
**Pull request by Mause**

### CODE REVIEW

**Comment by 2096779623** [comment]
Update to [9.0.0](https://github.com/apache/arrow/tags) .

**Comment by Mause** [comment]
@2096779623 it hasn't been released yet, it's still the dev version

**Comment by Mause** [comment]
> @2096779623 it hasn't been released yet, it's still the dev version

Or at least it's listed in the docs as the dev version 🤔

**Comment by Mause** [comment]
> I suppose it's fine. They don't even have 7.0.1 and 8.0.1 updated on their website.
> 
> Btw in case you are not aware of it, revision should be (re)set to `0` (instead of `1`) for new release. (There's some ongoing discussion on whether the line should be removed in case of `0`, I suppose either way is fine for now.) I missed it when I had your commit merged.

I assume you mean in my previous PR?

**Comment by tomty89** [comment]
Yes. And just in case you are ultimately bumping to 9.0.0 with this one.

**Comment by Mause** [comment]
@2096779623 @tomty89 was there something you wanted changed before you merged this?

**Comment by tomty89** [comment]
Isn't dataset enabled by default though? (It doesn't hurt much to set the option explicitly, although I'd prefer not to myself.)

**Comment by Mause** [comment]
> Isn't dataset enabled by default though? (It doesn't hurt much to set the option explicitly, but I'd prefer not to myself.)

I can check, but the reason I submitted this pr was that it was missing from the Python bindings

**Comment by tomty89** [comment]
Are you talking about the cpython so that are not being built when you install pyarrow with pip?

AFAICT, the current libarrow-cpp package is built with dataset enabled (but not parquet), and if you set `PYARROW_WITH_DATASET=1` when you install pyarrow, you'll see that the missing parquet is the road blocker.

**Comment by Mause** [comment]
Arrow version 9.0.0 has been released since I opened this pr, so I've updated that, and removed the dataset flag

**Comment by Mause** [comment]
> I suppose it's fine. They don't even have 7.0.1 and 8.0.1 updated on their website.
> 
> Btw in case you are not aware of it, revision should be (re)set to `0` (instead of `1`) for new release. (There's some ongoing discussion on whether the line should be removed in case of `0`, I suppose either way is fine for now.) I missed it when I had your commit merged.

Looks like the linter forbids this?

**Comment by tomty89** [comment]
Yeah. Apparently you should remove or comment the line. I recommended the latter with the value set to 1 to make it convenient for the rev bump.

**Comment by Grimler91** [comment]
This conflicts with [ndk-r25 update](https://github.com/termux/termux-packages/pull/11422) so I will pull it into that branch instead

**Comment by Grimler91** [comment]
And should probably change linter to allow TERMUX_PKG_REVISION=0, looks better than having a commented line IMO

**Comment by Mause** [comment]
Merged as part of the above pr

**Pull request closed without merging**
