### PR TITLE
chore(main/mariadb): remove test files

### PR DESCRIPTION
**Pull request by zorro**
%ci:no-build

### CODE REVIEW

**Comment by TomJo2000** [comment]
Part of #21130
(I assume, unless you are just looking at the package randomly)

**Comment by zorro** [comment]
@TomJo2000 Just noticed the test files directory name changed. Looks like the package built fine.

**Comment by TomJo2000** [comment]
That'd probably do it.

**Comment by Biswa96** [comment]
Would you like to bump the revision as well? This commit changes the actual package.

**Pull request merged**
