### PR TITLE
new package: octave, octave-x

### LINKED ISSUE #387: Package request: GNU Octave
There are a few Octave "distros" for Android so maybe it's simple to bring Octave into Termux too. I might give it a shot in a few weeks (but don't let that stop you, feel free to try anyway :))

### PR DESCRIPTION
**Pull request by licy183**
Closes #387

### CODE REVIEW

**Comment by licy183** [comment]
Tests fine locally. I'll merge this PR after 3 days if there is no more review. Thanks!

**Review by Grimler91 — APPROVED** [review]
Nice work!

**Comment by m-r-s** [comment]
I tried the octave-x package with termux-x11 but the version states that the build misses gui features.

**Comment by licy183** [comment]
> I tried the octave-x package with termux-x11 but the version states that the build misses gui features.

QT-GUI is disabled because it is hard to cross-compile.

**Comment by m-r-s** [comment]
okay, fltk for plotting seems to work.

How about packages, and liboctave-dev?
I tried to install the signal package from the forge, but it failed.

**Pull request merged**
