### PR TITLE
gnupg: workaround for %n

### PR DESCRIPTION
**Pull request by Krush206**

### CODE REVIEW

**Comment by xtkoba** [comment]
The proposed patches are not maintainable. Please make it more simple.

**Comment by xtkoba** [comment]
The reason why the patches should be simple is that some maintainers tend to remove the whole patch if it is not applied cleanly, leading to a regression.

The change should be minimal. No complete solution is required at all. Just a workaround is needed.

**Comment by xtkoba** [comment]
If you prefer a complete solution, then please submit the patch to upstream.

**Comment by Grimler91** [comment]
We probably should patch agent/protect.c as well though, so thanks for pointing that out. I haven't encountered the error crom there, under what conditions is the error triggered from agent/protect.c?

**Comment by xtkoba** [comment]
Yeah, we need test case(s) to confirm that a PR actually fixes something. I recommend filing a bug report.

**Comment by Krush206** [comment]
[`xtryasprintf()`](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=agent/protect.c;h=1084ee20807c2353314e0d1d78dd950735015b41;hb=refs/heads/master#l582) calls [`gpgrt_vasprintf()`](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=common/xasprintf.c;h=00ff66a7549d7172f690841b88ae4ac5eb3fe7a1;hb=refs/heads/master#l65), which isn't part of the C library, but part of [`libgpg-error`](https://github.com/gpg/libgpg-error/blob/master/src/visibility.c#L712), which [contains `%n`](https://github.com/gpg/libgpg-error/blob/master/src/estream-printf.c#L651), @Grimler91.

```c
#include <stdio.h>
#include <gpg-error.h>

int main(void)
{
  int n;

  gpgrt_printf("Hello, world!\n%n", &n);
  printf("%d\n", n);
}
```
This works, even though the compiler generates a warning.

Perhaps the functions containing `%n` could be replaced with `gpgrt_[...]`.

**Pull request closed without merging**
