### PR TITLE
add package jdupes

### PR DESCRIPTION
**Pull request by Efreak**
jdupes is like fdupes, but better.

Hardlink support is disabled, since Android disallows creation of hardlinks.

jdupes has no dependencies and takes a single command to install, and builds/works fine inside termux. `make CMAKE_EXTRA=-DNO_HARDLINKS PREFIX=$PREFIX install`

While it duplicates functionality from fdupes, the binary and manpage are 172kb combined; strip the binary to remove 100kb.

### CODE REVIEW

**Comment by Efreak** [comment]
Bleh. I thought make would be run automatically? Or is that only if there's a configure script?

**Comment by Grimler91** [comment]
It needs `TERMUX_PKG_BUILD_IN_SRC=true`, otherwise it looks for a non-existent Makefile in the build directory

**Comment by xtkoba** [comment]
Looks like abandoned. @Efreak Still work in progress?

**Comment by Efreak** [comment]
Abandoned, sorry. Should have closed myself

**Comment by Efreak** [comment]
I've updated jdupes on my tablet, it currently needs another library.

If anyone else wants it the following set of commands works to build it (I'm not packaging anymore, I'm just syncing my devices...)

```bash
git clone https://github.com/jbruchon/jdupes
git clone https://GitHub.com/jbruchon/libjodycode
cd libjodycode
make staticlib
cd ../jdupes
# jdupes doesn't use a configure script, doesn't build properly on Android... Binary needs patching
wget https://gist.github.com/Efreak/9e244392bbc472294b1bff314bd450cb/raw/75e7ed43866e66179472779a1350809d54fd5eb7/0001-add-alignment-fixer-step-and-align_fix.py.patch
git apply 0001-add-alignment-fixer-step-and-align_fix.py.patch
USE_NEARBY_JC=1 PREFIX=$HOME/.local make static install
```

**Pull request closed without merging**
