### PR TITLE
Provide official gpg.rc for mutt

### PR DESCRIPTION
**Pull request by Neo-Oli**
Ours no longer works as of 1.10.1, but there is now an official one.
However that assumes Gnupg2 and doesn't work with Gnupg1. So it replaces
the commands. This is only necessairy as long as our canonical gpg is
Gnupg1. There is no longer an example file for Gnupg1, since I assume
anyone who actually uses PGP for email will want to use Gnupg2 anyway
(also I haven't found one that works with 1.10.1 anyway)

### CODE REVIEW

**Comment by Grimler91** [comment]
Seems that travis failed to download the tar.

I opened #2691 to (finally) remove gnupg1 and it's subpackages, so a gpg.rc for gnupg1 might have been redundant anyways.. :)

**Comment by fornwall** [comment]
#2691 is now live, so gnupg1 is no more! The `gnupg` package is now actuall version 2 of gnupg. and provides the `gpg` binary.

So you should be able to replace

    sed 's/command="gpg/&2/g' $TERMUX_PKG_SRCDIR/contrib/gpg.rc  > $TERMUX_PREFIX/share/examples/mutt/gpg2.rc

with

    cp $TERMUX_PKG_SRCDIR/contrib/gpg.rc  $TERMUX_PREFIX/share/examples/mutt/gpg.rc

**Comment by Neo-Oli** [comment]
Great to hear! I updated the PR accordingly.

**Comment by fornwall** [comment]
Nice! The updated package is now available for installation.

**Pull request merged**
