### PR TITLE
android-5: add generate-bootstrap script

### PR DESCRIPTION
**Pull request by Grimler91**
Adapted from the one on master branch. Not tested on an actual device yet, the list of packages probably have to be adjusted a bit.

### CODE REVIEW

**Comment by Grimler91** [comment]
> ```
> $ termux-am --am-help
> CANNOT LINK EXECUTABLE: empty/missing DT_HASH in "termux-am-socket" (built with --hash-style=gnu?)
> ```

Was this on android 5 or 6? Did you compile it on device?

It's the same error as for [frida](https://github.com/termux/termux-packages/issues/10129) on master branch, though perhaps more or less a coincidence.

> The termux-keyring also needs to be synced with master. Currently, xeffyr's deprecated key exists there too.

Some mirror out there somewhere might have a copy of x11-repo or unstable-repo for android-5, from before xeffyr removed them. I think keeping fornwall's and xeffyr's keys make sense just in case some user somehow is subscribed to such repos

**Comment by agnostic-apollo** [comment]
Cool, thanks. Take your time.

And any reason for `termux-keyring` not synced with `master` in case some other maintainer signs repos instead of you?

**Comment by Grimler91** [comment]
Was mostly thinking that support has been dropped, and that there hasn't been much interest in maintaining it, but yeah, can add all keys in case that changes. 

The repos are not set up to work with aptly, so for now any package update would have to be built, uploaded and the repo signed manually. If someone wants to maintain the repos for real they should probably create new repos that are handled by aptly instead (I haven't done that since users that are subscribed to the current repos would get a warning/prompt when the repo metadata changes, and plan seem to still be to only do the bare minimum for android 5)

**Comment by agnostic-apollo** [comment]
Fair enough.

**Pull request merged**
