### PR TITLE
libcompiler-rt: Reland "libcompiler-rt: add trigger for llvm-mingw-w64"

### PR DESCRIPTION
**Pull request by licy183**

### CODE REVIEW

**Comment by xtkoba** [comment]
Would you please don't touch `libcompiler-rt` anymore?

**Comment by licy183** [comment]
`llvm-mingw-w64` toolchain will not work without the symlink created in `postinst`, just like `ndk-multilib`.

**Comment by xtkoba** [comment]
Symlinking to external blob is allowed only for NDK. Keep in mind that this is pretty much an exceptional case. In other cases compiler-rt should be built along with libllvm.

**Comment by xtkoba** [comment]
Along with `libllvm`, or as a separate package if possible.

**Comment by licy183** [comment]
IMO adding it as a separate package is not possible. If it provides this symlink in `llvm-mingw-libcompiler-rt`, then this package should be revbumped every time `libllvm` updates.

**Comment by xtkoba** [comment]
Did you try? I strongly believe it is possible.

Yes the package should be bumped with every minor `libllvm` bump. That is the nature.

**Comment by licy183** [comment]
I'll submit a PR for this if you think that's the nature way...

**Comment by xtkoba** [comment]
Modularized `libllvm` is proposed in #2282 and I'm in favor of it. Along this line something like `libcompiler-rt-mingw-w64` becomes just one component of the suite.

**Comment by xtkoba** [comment]
And aligning the version of the components in `libllvm` is required regardless of building it on our own or borrowing from midstream.

**Comment by licy183** [comment]
Yeah. I also think that the sub-projects of libllvm should be built separately. It will save lots of build time and make it easier to maintain. I've separate `flang` from it because compiling `flang` needs lots of  memory and running it parallelly will not work because of OOM.

**Comment by buttaface** [comment]
We would save build time building LLVM separately, but it's more work setting all that up and maintaining it, so I don't think it is worth it, as build time is much cheaper than our time.

**Pull request closed without merging**
