### PR TITLE
Simplify openjdk-17 patches

### PR DESCRIPTION
**Pull request by Grimler91**
Patch changes are roughly: 

* Squash some commits where applicable, the git tree contained quite a few fixup commits.

* Drop clang compatibility patches, and hack to pretend clang is gcc, specify that /usr/bin/clang should be used for host compilation instead

* Re-write some commit messages that were using the standard "Update foo.cpp" message

* Termux has iconv, spawn, resolv-conf and several other headers/libraries available, so quite a few patches to fix/add those can be dropped.  Also add necessary dependencies to our openjdk package.

* Termux supports android >=7 so drop patches related to lower android versions

* Use termux path's in some places, specifically /data/data/com.termux/files/usr/tmp for tmpdir and /data/data/com.termux/files/usr/bin/java as default path java might be run from.

* Add our patches from termux-packages/ and rebase/squash were applicable.

All of this brings number of patches we need to maintain down to
around 35, from 105 (in openjdk repo) + 12 (kept in termux-packages).

On top of that I've also changed so package is installed to $PREFIX/lib/jvm/java-17-openjdk, and made it use update-alternatives (to make it possible to have both openjdk-17 and -19 installed).

Packages need some testing, simple hello-world examples run fine on aarch64 (will test on arm as well when artifacts are available), but maybe some java master can run some more realistic use case tests.

### CODE REVIEW

**Comment by xtkoba** [comment]
I won't approve `openjdk-19` unless specific maintainer is named. Also please clarify why we need two versions of OpenJDK packaged.

**Comment by 2096779623** [comment]
> I won't approve `openjdk-19` unless specific maintainer is named. Also please clarify why we need two versions of OpenJDK packaged.

Perhaps for backward compatibility, to test if other java packages can build/run on `openjdk-19` before removing `openjdk-17` .

**Comment by xtkoba** [comment]
Are we planning to remove `openjdk-17` shortly? I assumed that we only package the latest LTS version of OpenJDK. IIUC 17 is LTS but 19 is not.

**Comment by Grimler91** [comment]
That's fair. We could drop 17 and just have 19, or add 19 to TUR instead.

If we drop 17 we also no longer have to add an extra repo to get openjdk-17 in docker image: 

https://github.com/termux/termux-packages/blob/c4db683e0c337c1c9246c1c4b43252554e28b72d/scripts/setup-ubuntu.sh#L301

I think main reason we have had 17 and not latest is that repo has been such a mess...

**Comment by agnostic-apollo** [comment]
>Also please clarify why we need two versions of OpenJDK packaged.

Having both LTS and latest version is not a bad idea. Not everyone may want to use LTS or latest. `node` also has LTS and latest. In my opinion LTS should be prioritized since it allows stability for projects for a longer time, assuming we decide not to have two packages and can then move `openjdk-19` to TUR.

>I won't approve openjdk-19 unless specific maintainer is named. 

Yeah, your concern is valid, would be lot of work to maintain something as big as `openjdk`.

**Comment by truboxl** [comment]
Need to check ca-certificates as well
https://github.com/termux/termux-packages/blob/c4db683e0c337c1c9246c1c4b43252554e28b72d/packages/ca-certificates/build.sh#L23-L39

**Comment by Grimler91** [comment]
The host built tool `$TERMUX_PKG_SRCDIR/build/linux-arm-server-release/buildjdk/jdk/bin/jmod` fails to find `$TERMUX_PKG_SRCDIR/build/linux-arm-server-release/buildjdk/jdk/lib/libnet.so` on arm/i686 for some unknown reason. 

strace seem to indicate that there is some variable substitution issue, on aarch64 it looks at these paths to find libnet.so:

```
14638 openat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/glibc-hwcaps/x86-64-v3/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14638 newfstatat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/glibc-hwcaps/x86-64-v3", 0x7f32007e6760, 0) = -1 ENOENT (No such file or directory)
14638 openat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/glibc-hwcaps/x86-64-v2/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14638 newfstatat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/glibc-hwcaps/x86-64-v2", 0x7f32007e6760, 0) = -1 ENOENT (No such file or directory)
14638 openat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/tls/haswell/x86_64/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14638 newfstatat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/tls/haswell/x86_64", 0x7f32007e6760, 0) = -1 ENOENT (No such file or directory)
14638 openat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/tls/haswell/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14638 newfstatat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/tls/haswell", 0x7f32007e6760, 0) = -1 ENOENT (No such file or directory)
14638 openat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/tls/x86_64/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14638 newfstatat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/tls/x86_64", 0x7f32007e6760, 0) = -1 ENOENT (No such file or directory)
14638 openat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/tls/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14638 newfstatat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/tls", 0x7f32007e6760, 0) = -1 ENOENT (No such file or directory)
14638 openat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/haswell/x86_64/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14638 newfstatat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/haswell/x86_64", 0x7f32007e6760, 0) = -1 ENOENT (No such file or directory)
14638 openat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/haswell/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14638 newfstatat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/haswell", 0x7f32007e6760, 0) = -1 ENOENT (No such file or directory)
14638 openat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/x86_64/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14638 newfstatat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/x86_64", 0x7f32007e6760, 0) = -1 ENOENT (No such file or directory)
14638 openat(AT_FDCWD, "/home/builder/.termux-build/openjdk-17/src/build/linux-aarch64-server-release/buildjdk/jdk/lib/libnet.so", O_RDONLY|O_CLOEXEC) = 3
``` 

While for arm:

```
14619 openat(AT_FDCWD, "$/glibc-hwcaps/x86-64-v3/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "$/glibc-hwcaps/x86-64-v2/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "$/tls/haswell/x86_64/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "$/tls/haswell/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "$/tls/x86_64/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "$/tls/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "$/haswell/x86_64/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "$/haswell/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "$/x86_64/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "$/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
14619 newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=47323, ...}, AT_EMPTY_PATH) = 0
14619 mmap(NULL, 47323, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f6274081000
14619 close(3)                          = 0
14619 openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "/lib/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
14619 openat(AT_FDCWD, "/usr/lib/libnet.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

The prefixed `$` in those paths look pretty weird, I suppose it might come from the RUNPATH of jmod, which is set to `$ORIGIN:$ORIGIN/../lib` on both arm and aarch64.

I can't see any obvious difference with previous version of package that might cause this, so need to debug it further.

**Comment by agnostic-apollo** [comment]
Such beauty! 😍

-`postinst`

```shell
#!/data/data/com.termux/files/usr/bin/sh
if [ "debian" = "pacman" ] || [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
if [ -x "/data/data/com.termux/files/usr/bin/update-alternatives" ]; then
update-alternatives --install /data/data/com.termux/files/usr/etc/profile.d/java.sh java-profile	/data/data/com.termux/files/usr/lib/jvm/java-19-openjdk/etc/profile.d/java.sh 60
for tool in bin
jwebserver
jdb
jstatd
jstat
jdeps
jps
jmod
keytool
javac
javap
jlink
jcmd
jhsdb
jarsigner
jdeprscan
jinfo
jshell
jmap
jimage
jar
jpackage
jconsole
javadoc
jfr
serialver
rmiregistry
java
jstack
jrunscript; do
update-alternatives --install 						/data/data/com.termux/files/usr/bin/$tool $tool 						/data/data/com.termux/files/usr/lib/jvm/java-19-openjdk/bin/$tool 60
done

for manpage in ; do
update-alternatives --install 						/data/data/com.termux/files/usr/share/man/man1/$manpage.gz $manpage 						/data/data/com.termux/files/usr/lib/jvm/java-19-openjdk/man/man1/$manpage.gz 60
done
fi
fi
```

- `prerm`

```shell
#!/data/data/com.termux/files/usr/bin/sh
if [ "debian" = "pacman" ] || [ "$1" != "upgrade" ]; then
if [ -x "/data/data/com.termux/files/usr/bin/update-alternatives" ]; then
for tool in bin
jwebserver
jdb
jstatd
jstat
jdeps
jps
jmod
keytool
javac
javap
jlink
jcmd
jhsdb
jarsigner
jdeprscan
jinfo
jshell
jmap
jimage
jar
jpackage
jconsole
javadoc
jfr
serialver
rmiregistry
java
jstack
jrunscript; do
update-alternatives --remove $tool /data/data/com.termux/files/usr/bin/$tool
done

for manpage in ; do
update-alternatives --remove $manpage /data/data/com.termux/files/usr/share/man/man1/$manpage.gz
done
fi
fi
```

**Comment by Grimler91** [comment]
@agnostic-apollo thanks, I'll fix it!

**Comment by AlirezaParsi** [comment]
i think it's better have lts and last version of jdk on repo.
do you have plan for that? if yes when it happens?

**Comment by Grimler91** [comment]
Alright, I think I have finally fixed arm build error now as well (previously we faked that we had gcc instead of clang, and [when building with gcc it sets -DARM=1](https://github.com/openjdk/mobile/blob/90e182ac16fb002cde4279cde4203c94462f5c3c/make/autoconf/flags-cflags.m4#L751). When building with clang that flag was not set though). 

Have dropped openjdk-19 (lets stick with LTS versions). Will merge this in a day or so if everything seems fine, and then start working on updating to next LTS, openjdk-21.

**Comment by agnostic-apollo** [comment]
>Have dropped openjdk-19 (lets stick with LTS versions). Will merge this in a day or so if everything seems fine, and then start working on updating to next LTS, openjdk-21.

Makes sense, thanks!.

Will you re-number all patches again if a patch is removed or let some people live with their OCD of missing numbers? :p

**Comment by Grimler91** [comment]
@agnostic-apollo well I have at least created the patches with `--no-numbered` so that there is no number in the subject of the patches :)

Probably I'll create a branch or tag in github.com/termux/openjdk-mobile-termux and build from that one instead in next update so that we don't have that problem :)

Speaking of patches, do you have some way to reproduce issue you fixed in the [getCanonicalPath patch](https://github.com/termux/termux-packages/blob/master/packages/openjdk-17/fix-bugs-in-File-getCanonicalPath.patch)? The patch doesn't apply anymore in openjdk-21 ([the `joinNames` function is gone](https://github.com/openjdk/mobile/blob/bb377b26730f3d9da7c76e0d171517e811cef3ce/src/java.base/unix/native/libjava/canonicalize_md.c)), so would like to check if issue is still happening and needs to be fixed somewhere else

**Comment by agnostic-apollo** [comment]
lolz, okay, good work for now.

Those functions have been moved to `path_util.c`, bugs still exist, I have not been getting time last couple of months to report them to upstream, have to modify patch files, plan to to do it after finalizing termux-exec, likely later this week.

- https://github.com/openjdk/mobile/commit/88bbf3c2e6ac9f6d88cbb361cfbb4c16bb8eafc1
- https://github.com/openjdk/mobile/blob/bb377b26730f3d9da7c76e0d171517e811cef3ce/src/java.base/unix/native/libjava/path_util.c

**Comment by nexplorer-3e** [comment]
What is the current status of jdk 21? It's possible to release a beta version for testing?

**Pull request merged**
