### PR TITLE
ghc: Adapt to current NDK

### PR DESCRIPTION
**Pull request by xtkoba**
Supersedes #7996.

### CODE REVIEW

**Review by xeffyr — APPROVED** [review]

**Comment by buttaface** [comment]
Nice work, cool that we now a Haskell compiler for Termux. 😄

Any reason this doesn't use [the latest version, 9.2.1](https://repology.org/project/ghc/versions)?

**Comment by danwdart** [comment]
Of course it should definitely be 9.2.1... were there ABI issues for it?

**Comment by danwdart** [comment]
Seems like the website hasn't any binaries for 9.2.1 either - "No files for aarch64-deb9-linux"

**Comment by Randomxdp** [comment]
> Seems like the website hasn't any binaries for 9.2.1 either - "No files for aarch64-deb9-linux"

There is now

**Comment by danwdart** [comment]
Ah, nice. Since 9.2.2 I see it.

**Pull request merged**
