### PR TITLE
Fix for curl timeout in GitHub Actions

### PR DESCRIPTION
**Pull request by truboxl**
See https://github.com/actions/virtual-environments/issues/1187

Maybe a potential fix for the curl timeouts in GitHub Actions

### CODE REVIEW

**Comment by truboxl** [comment]
Unfortunately I have no idea how to test this besides running one build run

Any comments are welcome

**Comment by kcubeterm** [comment]
Look like it fixed the issue. https://github.com/kcubeterm/termux-packages/actions/runs/877115624

**Comment by truboxl** [comment]
Looks like some jobs still having problems...
I think @termux needs to report over https://github.com/actions/virtual-environments as I am out of ideas currently

**Comment by kcubeterm** [comment]
It is happening for termux but not in personal CI. Very strange.

**Comment by xeffyr** [comment]
That's rather https://github.com/actions/virtual-environments/issues/2890 than old https://github.com/actions/virtual-environments/issues/1187

**Pull request merged**
