### PR TITLE
bump(main/starship): 1.20.1

### PR DESCRIPTION
**Pull request by TomJo2000**
- set maintainer
- add elvish completions
- clean up build script

> PR Checklist:
> - [x] builds locally
> - [x] builds on CI
> - [x] tested on device (Aarch64, Android 14, Fairphone 5)

### CODE REVIEW

**Comment by TomJo2000** [comment]
Would like to get this merged in time for the next auto-update cycle.
So t-minus 4 hours or so.

**Comment by TomJo2000** [comment]
Oh also, this PR closes #20971

**Review by Biswa96 — APPROVED** [review]

**Comment by Biswa96** [comment]
I wonder if the starship-battery dependency can be removed with sed/awk. Then the patch rebase will not require in future version.

**Comment by TomJo2000** [comment]
If you wanna hack something together for that feel free to do a package revision.
I'm fairly happy for the time being that the `libz.so.1` workaround is no longer needed.

**Pull request merged**
