### PR TITLE
split libllvm builds

### PR DESCRIPTION
**Pull request by its-pointless**
this splits into sperate builds libllvm libclang lld and libomp.

### CODE REVIEW

**Comment by tomty89** [comment]
I think it's a bad idea to have libclang as the main package and split a clang subpackage. It may not even be necessary or sensical to have a libclang subpackage (not until we have any package actually depending on clang but only needed its shared libraries).

Same goes for llvm. The only difference is we do want its shared libraries to be split to a subpackage.

We should really fix build-package.sh so that the main package can depends on a subpackage of itself, then we can have clang and llvm as the main packages.

**Comment by tomty89** [comment]
**libomp:**

Why does it have to be consistent with the NDK on that though?

Is the removal of `TERMUX_PKG_NINJA=yes` intentional? Or did you just want to correct the typo `yew`?

**clang:**

If you insists on spliting a libclang package, please include only `lib/lib*.so`, although I have no idea what's the point of / sense in that.

`include`, `lib/cmake` should either just stay in clang or clang-dev (depending on if you want to do the auto devsplit).

As a reference, the clang package in Arch ships only `lib/lib*.so` since 6.0. We may want to do the same. If not, we should do the auto devsplit and let `lib/lib*.a` be in clang-dev.

If `lib/lib*.so` are not necessary for the using the compiler, we may want to include them in clang-dev.

I think you missed `bin/` for `c-index*` in clang-tools.subpackage.sh.

**llvm:**

There are a few more files to be included in libllvm subpackage:
https://www.archlinux.org/packages/extra/x86_64/llvm-libs/files/

**Comment by tomty89** [comment]
I am not sure about the idea of clang-tools as well. Not only that you'll have to handpick the files in `bin/` (not to mention that the current globbing is kind of ugly to me), there are also corresponding files in `share/`. Are they really so big that it worths a split?

**Comment by tomty89** [comment]
I think the libclang package may make some sense if the main package **does not** depend on it (so that the installation size can be reduced), as we don't need them to use `clang`.

**Comment by tomty89** [comment]
Allow me to further clarity on the `lib/lib*` files (sorry if I've been making too much noise)

First thing is, I don't think we need both `lib/lib*.so` and `lib/lib*.a`, as essentially they are equivalent.

As I mentioned, we don't (at least not for most of time, afaict) need either of the two sets of files to use clang, so I would *assume* they are "devel" files.

Therefore, we should do either do:

A. Add `lib/lib*.a` to `TERMUX_PKG_INCLUDE_IN_DEVPACKAGE` and add `lib/lib*.so` to `TERMUX_PKG_RM_AFTER_INSTALL`.

B. Split `lib/lib*.so` into libclang and add `lib/lib*.a` to `TERMUX_PKG_RM_AFTER_INSTALL`; add `libclang` to `TERMUX_PKG_DEVPACKAGE_DEPENDS` but not `TERMUX_PKG_DEPENDS`, so that clang-dev depends on libclang but not clang.

**Comment by its-pointless** [comment]
"Why does it have to be consistent with the NDK on that though?"
because people  use things compiled in termux elsewhere in android in non termux ways. Having a reasonably consistent android env is a feature....

"include, lib/cmake should either just stay in clang or clang-dev (depending on if you want to do the auto devsplit)."
no matter where i put that that it won't make sense to someone. 

"I am not sure about the idea of clang-tools either. Not only that you'll have to handpick the files in bin/ (not to mention that the current globbing is kind of ugly to me, and EDIT: you missed some of them, e.g. clang-f*, already), there are also corresponding files in share/. Are they really so big that it worths a split?"

its more so people download a compiler clang they get clang. I don't know what to do i will think about it.


"s the removal of TERMUX_PKG_NINJA=yes intentional? Or did you just want to correct the typo yew?"
yeah i have ninja working as needed with cmake automaticaly using just an addition non empty TERMUX_PKG_NINJA="". Doesn't need to be spelled correctly. I haven't bothered to upload it since its really quite minor. 

"There are a few more files to be included in libllvm subpackage:
https://www.archlinux.org/packages/extra/x86_64/llvm-libs/files/"
its different in debian. 
In the end its always rather arbitrary.

**Comment by tomty89** [comment]
Hmm looks like I have made some mistakes. Apparently:

1. There will always be and only be a `lib/libclang.so`, but not a `lib/libclang.a`.
2. There will only be other `lib/lib*.so` if we enable shared. Whether there will still be any `lib/lib*.a` produced and if so, whether they are still necessary to keep, are unknown. (Though at the very least, the Arch clang package does not have them.)

Anyway, I think:
1. We **do not** need to split `lib/lib*.a` to a dedicated subckage as they are always used with other files in clang-dev (i.e. `include` and `lib/cmake`), so we can just add it to `TERMUX_PKG_INCLUDE_IN_DEVPACKAGE`.
2. `lib/libclang.so` can either be added to `TERMUX_PKG_INCLUDE_IN_DEVPACKAGE`, or split into a libclang subpackage; for the latter case, the subpackage should be added to `TERMUX_PKG_DEVPACKAGE_DEPENDS` but **not** `TERMUX_PKG_DEPENDS`, as `lib/cmake/clang/ClangTargets-minsizerel.cmake` needs it, while the executables has no linkage to it. (In fact, nothing seem to do so far; that's why I think it can be put into clang-dev)

Things might change if we enabled shared. I am not sure why we don't enable shared in clang and libomp though.

**Comment by tomty89** [comment]
> "include, lib/cmake should either just stay in clang or clang-dev (depending on if you want to do the auto devsplit)."
no matter where i put that that it won't make sense to someone

Not really. Devsplit for `include` and `lib/cmake` is already done in `build-package.sh`. The only package-specific thing in this case are `lib/lib*`, which is because they ARE devel files and required by `lib/cmake/clang/ClangTargets-minsizerel.cmake`, and we have `TERMUX_PKG_INCLUDE_IN_DEVPACKAGE`. There's no point in making a dedicated subpackage for `lib/lib*.a` as they are static libraries and nothing will/can have runtime linkage to it.

Split package for `lib/libclang.so` is acceptable as there *might* be runtime linkage to it (though I'm quite sure it's rare). But we don't want the main package to depend on it as clang itself does not need it. If we do, it may loses its only point, that is to reduce the installation size for typical use cases. clang-dev needs it though, and thankfully we have `TERMUX_PKG_DEVPACKAGE_DEPENDS`.

> its different in debian.
In the end its always rather arbitrary.

I also have a bit of doubt in Arch's llvm split package, as some of the `*.so` are left in the llvm main package as well, so fair enough, I guess we can stick with your current split until we notice something is broken.

**Comment by tomty89** [comment]
Ahh right we should also have `TERMUX_PKG_INCLUDE_IN_DEVPACKAGE="lib/lib*.a` for llvm.

**Comment by joakim-noah** [comment]
Can you update so we can get this in? It's ridiculous how many packages are built together now.

**Comment by fornwall** [comment]
We are closing old pull requests as a cleanup action.

If you are interested in picking this work up, please submit a new pull request with up to date content and we promise to be more responsive with the proposed change!

**Pull request closed without merging**
