### PR TITLE
fix for pyfftw enable threads use gettimeofday instead of clock_gettime

### PR DESCRIPTION
**Pull request by its-pointless**
also added long and float
0

### CODE REVIEW

**Comment by fornwall** [comment]
Interesting!

What does using `gettimeofday` instead of `clock_gettime` fix?

**Comment by its-pointless** [comment]
from http://www.fftw.org/fftw3.pdf
FFTW’s planner actually executes and times different possible FFT algorithms in order
to pick the fastest plan for a given n. In order to do this in as short a time as possible,
however, the timer must have a very high resolution, and to accomplish this we employ
the hardware cycle counters that are available on most CPUs. Currently, FFTW supports
the cycle counters on x86, PowerPC/POWER, Alpha, UltraSPARC (SPARC v9), IA64,
PA-RISC, and MIPS processors.
Access to the cycle counters, unfortunately, is a compiler and/or operating-system dependent
task, often requiring inline assembly language, and it may be that your compiler is
not supported. If you are not supported, FFTW will by default fall back on its estimator
(effectively using FFTW_ESTIMATE for all plans).
You can add support by editing the file kernel/cycle.h; normally, this will involve adapting
one of the examples already present in order to use the inline-assembler syntax for your C
compiler, and will only require a couple of lines of code. Anyone adding support for a new
system to cycle.h is encouraged to email us at fftw@fftw.org.
If a cycle counter is not available on your system (e.g. some embedded processor), and you
don’t want to use estimated plans, as a last resort you can use the --with-slow-timer
option to configure (on Unix) or #define WITH_SLOW_TIMER in config.h (elsewhere).
This will use the much lower-resolution gettimeofday function, or even clock if the former
is unavailable, and planning will be extremely slow.

**Comment by fornwall** [comment]
Thanks! I just pushed https://github.com/termux/termux-packages/commit/604f8e4b18273c7cd45b007b843bb6504ac66d75, which builds all the variants in the same package (we could split it up into subpackages in the future).

About clock_gettime: Some quick googling didn't find issues about clock_gettime on android, do you have a reference about the problem? Is it still an issue on modern android versions (5.0 or later)?

**Comment by its-pointless** [comment]
http://www.vesperix.com/arm/fftw-arm/source/

**Comment by ackalker** [comment]
How about this? http://stackoverflow.com/a/17216789

> 
10
down vote
It's best not to use gettimeofday() or currentTimeMillis() on a mobile device. These return "wall clock" time, which can jump forward or backward suddenly if the network updates the time.

> Use the monotonic clock instead for performance measurements -- System.nanoTime() or clock_gettime() with CLOCK_MONOTONIC. Note this returns a struct timespec rather than a struct timeval; primary difference is that the clock resolution is nanoseconds rather than microseconds.

(code example in the SO answer.)

**Comment by its-pointless** [comment]
yeah i already mentioned this to him yesterday in irc... android phones get time from mobile towers. Its why getting ntp time can speed up gps sync times.

**Comment by ackalker** [comment]
Ah, okay, I understand.

**Comment by fornwall** [comment]
It seems that the problem here is not that wall clock time is used - fftw is using `clock_gettime(CLOCK_SGI_CYCLE, &t)`, which is supposed to be monotonic.

The problem seems to be that `CLOCK_SGI_CYCLE` is not supported on Android. The clock_gettime() call fails with a non-zero error code, but fftw does not check the return code so doesn't detect it and gets invalid values instead.

I've pushed https://github.com/termux/termux-packages/commit/9d934fbc74a32e1f349e5631194b4b868a8d9c0d which uses `ac_cv_func_clock_gettime=no` to avoid that problem - thanks @its-pointless!

The updated 3.3.6-2 version of the package is now available in the package repository.

**Pull request closed without merging**
