### PR TITLE
LDC: Upgrade to v1.18

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by xeffyr** [comment]
@kinke Is PR ready ?

**Comment by kinke** [comment]
@xeffyr Nope, I've just abused your CI to check for Android regressions with the first beta (won't be necessary anymore, I'm setting up proper Android CI for LDC). I'll update this once 1.18 final is released.

**Comment by xeffyr** [comment]
Ok.

**Comment by kinke** [comment]
Ready now.

**Pull request merged**
