### PR TITLE
poppler: update from 0.72.0 to 0.74.0

### PR DESCRIPTION
**Pull request by tomty89**

### CODE REVIEW

**Comment by Grimler91** [comment]
We also need to update the texlive-bin patches before merging this. I'll look at it (later today probably)

**Comment by tomty89** [comment]
For the record texlive-bin in Arch was merely rebuilt for poppler 0.73.0 and 0.74.0: https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/texlive-bin

**Comment by tomty89** [comment]
@fornwall I don't know if you build prebuilt packages via fast build though. If you don't, perhaps this should wait until a CI pass after #3397 is applied to the binary.

**Comment by tomty89** [comment]
Let's wait until at least #3474 is available is binary and see if the CI will finally pass with fast build.

**Pull request closed without merging**
