### PR TITLE
ndk-patches: implement getpass()

### PR DESCRIPTION
**Pull request by xeffyr**

### CODE REVIEW

**Comment by its-pointless** [comment]
coreutils needs to be fixed as well like wget

**Comment by its-pointless** [comment]
its annoying that gnulib decides to replace our getpass as it does by default then fails to compile. I guess since they declare gnu_getpass we could not define our getpass if gnu_getpass is defined?
put in the headers 
#ifndef gnu_getpass 


that way gnulib doesn't need patching?

**Comment by its-pointless** [comment]
AVOID_GNULIB+=" ac_cv_func_getpass=yes" 
Or something like that needs to be added by default.

**Comment by its-pointless** [comment]
Mtools won't compile without it for one thing

**Comment by xeffyr** [comment]
AVOID_GNULIB+=" ac_cv_func_getpass=yes" breaks libgnutls build and possible other.

I have removed `#ifndef GETPASS_H` condition and added definition of HAVE_GETPASS. Now packages building without error (including mtools).

**Comment by its-pointless** [comment]
Ok i have a few workarounds that get everything built in termux just need a tad more testing.

**Comment by its-pointless** [comment]
Lftp is doing its own thing that no one else uses. So add this
CXXFLAGS+=" -DNO_INLINE_GETPASS=1"
To lftp build.sh in preconfigure stage.

**Comment by xeffyr** [comment]
@its-pointless I have added this, but still same error:
```
/bin/bash ../libtool --silent  --tag=CXX   --mode=compile aarch64-linux-android-clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I/home/builder/.termux-build/lftp/src/src -I../lib  -I/home/builder/.termux-build/lftp/src/lib -I/home/builder/.termux-build/lftp/src/trio -I/data/data/com.termux/files/usr/include  -Oz -DNO_INLINE_GETPASS=1 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -c -o GetPass.lo /home/builder/.termux-build/lftp/src/src/GetPass.cc
/bin/bash ../libtool --silent  --tag=CXX   --mode=compile aarch64-linux-android-clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I/home/builder/.termux-build/lftp/src/src -I../lib  -I/home/builder/.termux-build/lftp/src/lib -I/home/builder/.termux-build/lftp/src/trio -I/data/data/com.termux/files/usr/include  -Oz -DNO_INLINE_GETPASS=1 -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -c -o ConnectionSlot.lo /home/builder/.termux-build/lftp/src/src/ConnectionSlot.cc
/home/builder/.termux-build/lftp/src/src/GetPass.cc:58:26: error: use of undeclared identifier 'readline_from_file'
   oldpass.set_allocated(readline_from_file(tty_fd));
                         ^
1 error generated.
Makefile:2276: recipe for target 'GetPass.lo' failed
```

**Comment by its-pointless** [comment]
Oh i thought mentioned this
Change it from 
+#ifndef GETPASS_H
to
#if !defined GETPASS_H

**Comment by xeffyr** [comment]
@its-pointless Ok, now lftp rebuilds without error.

Something else needed ? Or PR is ready for merging ?

**Comment by xeffyr** [comment]
Looks like not ready. At least `rsync` shows this:
```
/home/builder/.termux-build/rsync/src/lib/getpass.c:26:7: error: redefinition of 'getpass'
char *getpass(const char *prompt)
      ^
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../sysroot/usr/include/unistd.h:310:25: note: previous definition is here
static __inline__ char* getpass(const char* prompt) {
                        ^
1 error generated
```

**Comment by xeffyr** [comment]
@fornwall Now packages don't show getpass()-related errors when doing ./build-all.sh so I think the PR is ready for merging.

**Comment by xeffyr** [comment]
Closing in favor of https://github.com/termux/termux-packages/pull/2816: many things was changed from the time when this PR was opened so it is better to have a new PR.

**Pull request closed without merging**
