### PR TITLE
nethack working

### PR DESCRIPTION
**Pull request by its-pointless**
proper unix environment needs a working nethack.

### CODE REVIEW

**Comment by kenneth-Q** [comment]
It placed in the disabled-packages folder.
In fast, I do not know why they have put into that folder. It might be a good idea to create any `todo`  file for each packages and note why they are here. Have any other idea?

**Comment by kenneth-Q** [comment]
> #1023

**Comment by xeffyr** [comment]
> In fast, I do not know why they have put into that folder.

Because nethack doesn't support cross-compilation by default. This PR fixes that and enables package.

**Comment by kenneth-Q** [comment]
That may have a lot of things to work.😱

**Comment by kenneth-Q** [comment]
I got an error:

` Program initialization has failed.
To report this error, contact root or games.
Dungeon description not valid. `

**Comment by kenneth-Q** [comment]
It is progress stalled yet?
Shall we move it into the unstable-packages?
The game is interesting, keep move!😎

**Comment by xeffyr** [comment]
> Shall we move it into the unstable-packages?

I thought that it should be in https://github.com/termux/game-packages...

**Comment by kenneth-Q** [comment]
You are right! Move into game package should be better.

**Comment by xeffyr** [comment]
Package is now available in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install nethack
```

Let's hope that @Grimler91 will prepare https://github.com/termux/game-packages and add nethack to it.

**Pull request closed without merging**
