### PR TITLE
libgeos: enable package

### PR DESCRIPTION
**Pull request by rnauber**
As suggested by @fornwall  in #2348, this PR uses a stable location (github) to fetch the source. 
Thanks for merging,
Richard

### CODE REVIEW

**Comment by rnauber** [comment]
Well, I assumed, that this is required for the python-bindings (at least with autoconf/configure). Maybe we can remove it now...

**Comment by its-pointless** [comment]
The binding requires swig to compile if im not mistaken?

**Comment by rnauber** [comment]
Well, I assumed, that this is required for the python-bindings (at least with autoconf/configure). Maybe we can remove it now...

**Comment by rnauber** [comment]
Hm, I do not know, could you try it without a dependency?

**Comment by xeffyr** [comment]
Available at https://github.com/termux/science-packages/tree/master/packages/libgeos.
Installable with:
```
pkg install libgeos
```
If errored that package is not found, do `pkg install science-repo && pkg install libgeos`.

**Pull request closed without merging**
