### PR TITLE
Add package: Opam

### PR DESCRIPTION
**Pull request by bluelightning32**
This commit sets up an ocaml cross compiler and uses it to build opam, the
package manager for ocaml.

The packages in the default repository still try to use /bin/sh. So the
alternative repository described at http://ygrek.org.ua/p/ocaml-termux.html
must be used.

### CODE REVIEW

**Comment by its-pointless** [comment]
Still only aarch64 support though?

**Comment by its-pointless** [comment]
I have ocaml + opam builds compiled on all 4 termux archs i kind of need someone to test..

**Comment by bluelightning32** [comment]
Sorry, I should have commented sooner. This is my first time doing any android development. I didn't realize you supported other arches until you mentioned it in here. You should consider mentioning it in README.md.

I have an arm phone, and I'm trying to port it to that now. I had to do some large changes to get the .text relocation warning messages to go away. Now the mod operator is returning the wrong results, so opam crashes. I'm still debugging it.

As for the i686 and x86_64 android, which devices even run that? The Asus Zenphone?

How do people usually test those platforms? With emulators?

**Comment by its-pointless** [comment]
The x86 archs are used on chrome books by a lot of people. Allows dev work without installing linux. 
Iv got it working on both those archs i also have issue with the text relocation on arm. If you want to test on i686 or x86_64 i use android images on virtualbox on pc.

**Comment by its-pointless** [comment]
We recently had an increase in chromebook users due to [this post](https://blog.lessonslearned.org/building-a-more-secure-development-chromebook).

**Comment by bluelightning32** [comment]
Where do I download the virtualbox android images?

**Comment by its-pointless** [comment]
http://www.osboxes.org/android-x86/

**Comment by bluelightning32** [comment]
I think the relocation errors are really just warnings. Opam didn't seem to run any better when I fixed them. I'll bundle the patch up when I fix the mod operator.

I tracked down where the mod errors are coming from. ocamlopt is using some algorithm to turn integer division by a constant and integer mod by a constant into a combination of multiplication, shift, subtraction, and addition. It has to precompute a constant do multiply by.

For example
```
  let m = n mod 1062 in _
```
Turns into
```
     let
       m/1010
         (+
           (<<
             (let dividend/1013 (>>s n/1009 1)
               (- dividend/1013
                 (*
                   (+ (>>s (*h dividend/1013 8893345542127392117) 9)
                     (>>u dividend/1013 63))
                   1062)))
             1)
           1)
```

The problem is that large number it is using for the multiplication is 64 bit and the arm arch is 32 bit. The constant is coming from [here](https://github.com/ocaml/ocaml/blob/7257acb4f31d5845183008bf07fd0386e917f686/asmcomp/cmmgen.ml#L331). The problem is that it's using Nativeint to compute the constants. So it's using the integer size of the host system, not the integer size of the target system. I'll try to fix it.

**Comment by its-pointless** [comment]
Hmm would using 32bit version of build ocaml for build fix that? 
its needed to get i686 byte compiler working...

**Comment by bluelightning32** [comment]
Hmm, yes setting the host for the arm cross compiler to be i686 would probably work, and it's a lot simpler than patching the compiler.

Do you want to try it? Here's an easy repro of the problem you can use for testing:
```
$ arm-linux-androideabi-ocamlopt -g -o mod_example mod_example.ml
$ scp ...
$ ./mod_example 
5 mod 1062 = 1067
```

You can also check the cmm output to see if the constant is correct. Here's what the incorrect constant looks like:
```
$ arm-linux-androideabi-ocamlopt -dcmm -o mod_example mod_example.ml 2>&1 | less
...
(function camlMod_example__f_1008 (n/1009: addr)
 (let
   m/1010
     (+
       (<<
         (let dividend/1013 (>>s n/1009 1)
           (- dividend/1013
             (*
               (+ (>>s (*h dividend/1013 8893345542127392117) 9)
                 (>>u dividend/1013 63))
               1062)))
         1)
       1)
...
```

**Comment by bluelightning32** [comment]
I added the arm relocation fix to the branch. I didn't my script changes to get it to compile on arm, because they would probably conflict with yours.

How can I get a copy of your x86_64 opam binary to test?

**Comment by its-pointless** [comment]
https://github.com/its-pointless/gcc_termux
here is the file dump i use to share stuff
the the  i haven't added opam to repo yet due to a few things. 
im using 4.05 instead of 4.02.3 so the arm assembly doesn't fix it.

**Comment by its-pointless** [comment]
still wondering the best method to distribute ocaml. i think expecting people to compile the full ocaml compiler on their arm phone is a tad much.

**Comment by its-pointless** [comment]
its odd that arm opam doesn't pick up local ocamlc version but the 2.00 beta version on arm does..

**Comment by bluelightning32** [comment]
If you have a version of ocaml locally installed on the phone, opam should be able to use it. I didn't do that, because it was too much work to get ocamlc built right for the phone from the docker image.

I had a problem with the 2.00 beta, but I forget what it was. If you build it correctly, either version is good enough to install packages.

**Comment by bluelightning32** [comment]
I tried your opam-arm.zip file.

1. It has the relocation warnings. You said you're using a newer version of ocaml. Do you want me to adjust the patch for that version? Or you could enable opam first, and I could fix it with a different commit.

2. opam isn't working because it claims I don't have the required dependencies installed, even though I do. Strace shows it is using the wrong sh path:

> 9430  execve("/bin/sh", ["/bin/sh", "-c", "command -v tar"], 0xb6351c40 /* 18 vars */) = -1 ENOENT (No such file or directory)

It appears you did not apply the opam/sh-path.patch file from my PR.

**Comment by its-pointless** [comment]
About the /bin/sh stuff. For opam i am going to have termux-exec added as a dependency. It makes all /bin/sh /usr/bin/bash etc commands work. This should help negate the need for a seperate opam repository. (some things like jbuilder failing whilst looking up directory /data/data is another thing though) 
To use termux-exec apt install termux-exec and restart termux.

**Comment by its-pointless** [comment]
With regards to versions to use. Termux takes the "newest stable" approach which would mean 4.05 as far as i can tell. 
i686 is also giving relocation warnings. For now im ignoring that until i can work out how i want to distribute ocaml. First things first a working attributable opam

**Comment by its-pointless** [comment]
Also i have ocaml building right from the docker image. I get a 37mb deb file.

**Comment by bluelightning32** [comment]
I'm testing opam init with a clean installation. It's failing trying to write to /tmp. It worked on my primary phone because I already had this in .profile:

> export TMPDIR=/data/data/com.termux/files/usr/tmp

I think the default /tmp is coming from [ocaml](https://github.com/ocaml/ocaml/blob/39072e97bc850335c7d96ab90edc44cc395bb82a/stdlib/filename.ml#L87). Do you want me to send a patch to change the default, or is it easier for you to do it?

**Comment by bluelightning32** [comment]
I tested x86_64. Your opam worked! It was even able to build the standard version of ocaml instead of the 4.03.0+termux one.

```
$ export TMPDIR=/data/data/com.termux/files/usr/tmp
$ opam init --comp=4.05.0
...
$ eval `opam config env`
$ ocamlc -o hello hello.ml
$ ./hello 
Hello world!
```

**Comment by bluelightning32** [comment]
I tested i686. Aside from the relocation warnings, it works too.

**Comment by bluelightning32** [comment]
Only my old phone is arm. It's running Android 5.1. Building ocaml 4.05.0 through opam failed because it tried to pass the RTLD_NODELETE flag to dlopen.
```
Error: Error on dynamically loaded library: ../otherlibs/unix/dllunix.so: dlopen failed: invalid flags to dlopen: 1002
```

Apparently that [flag](https://issuetracker.google.com/issues/36986668) was added in Android 6.0.1, which is why it worked on my other devices.

Ocaml stopped using that flag in 4.06.0:
https://github.com/ocaml/ocaml/commit/4ac705ce49fbfca762575458e7b893d3ba0f6e80

Opam did sucessfully install version 4.06.0:
```
$ export TMPDIR=/data/data/com.termux/files/usr/tmp
$ opam init --comp=4.06.0+beta2
...
$ eval `opam config env`
$ ocamlc -o hello hello.ml
$ ./hello 
Hello world!
```

**Comment by its-pointless** [comment]
i guess that could be back ported?

**Comment by bluelightning32** [comment]
If you're distributing ocaml, you should either distribute 4.06 beta 2, or backport the fix. The commit message on the fix implies that it is safe to backport.

If you distribute opam but not ocaml, tell users to install 4.06 beta 2 or newer for old versions of Android.

**Comment by alexozer** [comment]
Any progress?

**Comment by its-pointless** [comment]
Yes opam and ocaml are on my repo ...
Iv got pull requests as well for termux

**Comment by bluelightning32** [comment]
@its-pointless, this is your [PR](https://github.com/termux/termux-packages/pull/1757)?

**Comment by its-pointless** [comment]
umm yes?
its based on what you have done but worse. I know.

**Comment by bluelightning32** [comment]
@its-pointless, haha, no the quality's great. I just wanted to make sure there was a link from this PR to your PR, since your PR will probably get merged instead.

**Comment by fornwall** [comment]
We are closing old pull requests as a cleanup action.

If you are interested in picking this work up, please submit a new pull request with up to date content and we promise to be more responsive with the proposed change!

**Pull request closed without merging**
