### PR TITLE
neovim-nightly: update package version

### LINKED ISSUE #11274: Auto update failing for neovim-nightly
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the neovim-nightly package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating neovim-nightly [Current version: 0.8.0-dev+608-g778541067]</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2022-07-18 06:14:08 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/2688478804">2688478804</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by licy183**
Closes #11274.

### CODE REVIEW

**Review by 2096779623 — APPROVED** [review]

**Comment by licy183** [comment]
> neovim-nughtly updates are broken after this . apt no longer updates the package beyond this version even though several updates have already been committed in the repo

I have no idea why this happens, maybe because of the version number extracted from upstream release log. It seems that we should use some other things in the version number, such as the commit date.

**Comment by sylirre** [comment]
This happens because version format has been changed. Adding the epoch to version should solve issue with apt.

https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#downgrading-the-package-or-changing-versioning-scheme

**Comment by truboxl** [comment]
I think what shadmansaleh meant is https://github.com/termux/termux-packages/commit/a38648e5464af8ef0a15726a1cb741b38ef1713b

**Comment by licy183** [comment]
`neovim-nightly`'s version number parsed from the release log doesn't follow what it means before. In the past, it follows a format like `0.8.0-dev+608-g778541067`, and the number after symbol `+` pluses automatically when it updates. But since https://github.com/termux/termux-packages/issues/11274, something has changed in the upstream, which makes the version number parsed from the release log changed from `0.8.0-dev-nightly-9-g1ef84547a` to `0.8.0-dev-nightly-7-gd0ced2a12` and from `0.8.0-dev-nightly-7-gd0ced2a12` to `0.8.0-dev-nightly-2-gea13dce3b`. If we don't use some other information (like the timestrap) to the package version number, because of `9>2` and `9>7`, the package versions will not compare as what we expected.

**Pull request merged**
