### PR TITLE
Update KDE frameworks 6.3.0

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
Should there be two versions of KDE framework packages - with qt5 and with qt6? Lxqt depends on the qt6 ones and some other programs like nextcloud-client depends on the qt5 ones.

**Comment by TomJo2000** [comment]
As long as the Qt6 transition isn't completed we should probably keep both.

**Comment by Biswa96** [comment]
> As long as the Qt6 transition isn't completed we should probably keep both.
> Or as long as we still have packages that depend on kf-qt5, and don't build with kf-qt6.

Those two statements seems contradicting. Should I postpone kde and lxqt updates with qt6?

**Comment by TomJo2000** [comment]
> Those two statements seems contradicting. Should I postpone kde and lxqt updates with qt6?

No I don't think we should delay those.
But we may want to keep separate qt5 versions around if there is packages depending on the Qt5 KDE Frameworks that can't be built against Qt6 yet.

**Comment by Biswa96** [comment]
What package name do you suggest for KDE frameworks? for example,
* karchive/karchive5
* karchive-qt5/karchive-qt6
* kf6-karchive/kf5-karchive
(those names are taken from repology)

**Comment by TomJo2000** [comment]
Those seem fine to me.

**Comment by truboxl** [comment]
Prefer kf6-karchive/kf5-karchive

**Comment by Biswa96** [comment]
> Prefer kf6-karchive/kf5-karchive

It is not required to rename older KDE framework packages, right? The new ones can be prefixed with kf6-

**Comment by TomJo2000** [comment]
> > Prefer kf6-karchive/kf5-karchive
> 
> It is not required to rename older KDE framework packages, right? The new ones can be prefixed with kf6-

It would probably be good to make the distinction.
Though that's gonna necessitate rebuilds of all `kf5-` packages, all `kf6-` packages and all revdeps thereof.
But I think that's a bullet we should just bite.
On the one hand for a better overview.
And on the other hand for consistency with the `qt5-*`/`qt6-*` packages.
`kf5-*`/`kf6-*` should probably follow the same naming convention.

**Comment by Biswa96** [comment]
Coming soon...

**Pull request closed without merging**
