### PR TITLE
add liblzma to libunwind

### PR DESCRIPTION
**Pull request by stephengroat**
build dependency

#1169

### CODE REVIEW

**Comment by stephengroat** [comment]
@fornwall to fix issues like this, the `Build-Depends` tag could also be added to the `build.sh` and `build-package.sh` system

https://www.debian.org/doc/debian-policy/ch-relationships.html#s-sourcebinarydeps

**Comment by fornwall** [comment]
I've added support for setting build dependencies using `TERMUX_PKG_BUILD_DEPENDS` which `scripts/buildorder.py` respects.

Does libunwind really have a build dependency on liblzma, but not a runtime one? Do you know why?

**Comment by stephengroat** [comment]
i'm not sure, but i think it might be runtime. i've found an ubuntu ppa that has `libunwind`, and it looks like it's a runtime dependency for the library (https://launchpad.net/ubuntu/artful/arm64/libunwind8/1.1-4.1ubuntu2)

**Comment by fornwall** [comment]
It seems that libunwind links against liblzma if available unless `--disable-minidebuginfo` is passed to configure.

I've added this flag to the build now (as the libunwind package distributed in Termux has never linked to liblzma previously, due to it by accident not being available when built), so this PR should no longer be needed.

**Pull request closed without merging**
