### PR TITLE
update ndk to 17 and switch some packages to clang build

### PR DESCRIPTION
**Pull request by vishalbiswas**
I've tried to update the build process to use Android NDK 17 released on May 8th, 2018 according to the changes mentioned in #1905.

Please note that https://github.com/android-ndk/ndk/issues/294 has not been included in r17 and as such we still have to use `gcc` for emacs and m4 to work around `Undefined reference to '__muloti4'`.

### CODE REVIEW

**Comment by Grimler91** [comment]
I tried an ./clean.sh; ./build-all.sh

Initial findings:

- libidn now needs `termux_step_pre_configure () {LDFLAGS=" -liconv"}`
- netinet/in.h no longer does `typedef uint32_t in_addr_t;` which causes `In file included from /home/builder/.termux-build/libnl/src/include/netlink-private/netlink.h:32:
/home/builder/.termux-build/_lib/17-aarch64-21-v1/bin/../sysroot/usr/include/arpa/inet.h:39: 
In file included from :/home/builder/.termux-build/libnl/src/lib/addr.c: 
unknown type name 'in_addr_t'` for libnl and probably others. Should we patch this in the headers or patch it in affected packages?

I'll update the list when find more

**Comment by vishalbiswas** [comment]
@Grimler91 

- Didn't encounter any errors with libidn
- Should not be a problem but it is. `in_addr_t` is defined in `bits/in_addr.h` which is included by `linux/in.h` which is included by `netinet/in.h` which is included by `arpa/inet.h`. Looking into this.

**Comment by Grimler91** [comment]
@vishalbiswas 

> Didn't encounter any errors with libidn

Weird, I'm still seeing it:
```
/home/builder/.termux-build/_lib/17-aarch64-21-v1/bin/aarch64-linux-android-ld: warning: libiconv.so, needed by ../lib/.libs/libidn.so, not found (try using -rpath or -rpath-link)
../lib/.libs/libidn.so: undefined reference to `iconv_open'                                                 
../lib/.libs/libidn.so: undefined reference to `iconv_close'                                              
../lib/.libs/libidn.so: undefined reference to `iconv'
clang60: error: linker command failed with exit code 1 (use -v to see invocation)                          
Makefile:1444: recipe for target 'idn' failed
```

Can confirm your libnl patch works.
Next error I encountered was with libpixman. I'll open a PR with a patch in a minute (to your branch).

**Comment by Grimler91** [comment]
I get "the same" error with libisl:
```
/home/builder/.termux-build/_lib/17-aarch64-21-v1/bin/aarch64-linux-android-ld: warning: libgmp.so, needed by ./.libs/libisl.so, not found (try using -rpath or -rpath-link)              
/home/builder/.termux-build/_lib/17-aarch64-21-v1/bin/aarch64-linux-android-ld: warning: libgmp.so, needed by ./.libs/libisl.so, not found (try using -rpath or -rpath-link)
./.libs/libisl.so: undefined reference to `__gmpz_mul'        
./.libs/libisl.so: undefined reference to `__gmpz_get_d'     
./.libs/libisl.so: undefined reference to `__gmpz_swap'
./.libs/libisl.so: undefined reference to `__gmpz_cdiv_q'
...
```

Solved with LDFLAGS+=" -lgmp" so seems something fundamental has changed.

**Comment by vishalbiswas** [comment]
@Grimler91 that libisl error occurs in aarch64. arm build works fine. working on it

**Comment by Grimler91** [comment]
Interesting. 

Seems like `LDFLAGS+=" -liconv"` doesn't help. Building tracepath (which depends on libidn) gives error again: 
```
/home/builder/.termux-build/_lib/17-aarch64-21-v1/bin/aarch64-linux-android-ld: warning: libandroid-support.so, needed by /data/data/com.termux/files/usr/lib/libidn.so, not found (try using -rpath or -rpath-link)
/home/builder/.termux-build/_lib/17-aarch64-21-v1/bin/aarch64-linux-android-ld: warning: libiconv.so, needed by /data/data/com.termux/files/usr/lib/libidn.so, not found (try using -rpath or -rpath-link)
/data/data/com.termux/files/usr/lib/libidn.so: undefined reference to `iconv_open'
/data/data/com.termux/files/usr/lib/libidn.so: undefined reference to `nl_langinfo'
/data/data/com.termux/files/usr/lib/libidn.so: undefined reference to `iconv_close'
/data/data/com.termux/files/usr/lib/libidn.so: undefined reference to `iconv'
clang60: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by vishalbiswas** [comment]
@Grimler91 pull latest changes, delete existing toolchain and build again.
was probably due to not using gold

**Comment by Grimler91** [comment]
Yeah, works now. 

Next error is on libzmq: 
```
/home/builder/.termux-build/libzmq/src/src/v1_decoder.cpp:113:28: error: comparison 'unsigned long' > 18446744073709551615 is always false [-Werror,-Wtautological-constant-compare]
    if (payload_length - 1 > std::numeric_limits<size_t>::max ()) {
        ~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by its-pointless** [comment]
grimler add  --disable-Werror and libzmq compiles

**Comment by its-pointless** [comment]
remove gio-gsocket.c.patch from glib not needed?

**Comment by vishalbiswas** [comment]
Strangely I don't get the error when building for arm

**Comment by vishalbiswas** [comment]
I this when building elinks. Can anybody else try and see if they get the same errors?
```lib.o:vs.c:function getifaddrs: error: undefined reference to '__errno_location'
lib.o:getifaddrs.c:function getifaddrs2: error: undefined reference to '__errno_location'
lib.o:getifaddrs.c:function getifaddrs2: error: undefined reference to '__errno_location'
lib.o:getifaddrs.c:function getifaddrs2: error: undefined reference to '__errno_location'
lib.o:vs.c:function set_window_title: error: undefined reference to 'stdout'```

**Comment by vishalbiswas** [comment]
```/home/vishal/.termux-build/ltrace/src/sysdeps/linux-gnu/arm/plt.c:65:32: error: use of undeclared identifier 'SHT_ARM_ATTRIBUTES'
        if (elf_get_section_type(lte, SHT_ARM_ATTRIBUTES, &scn, &shdr) < 0```
guess that elf.h won't be going away after all

**Comment by Grimler91** [comment]
@vishalbiswas I get no error for elinks when building for aarch64.

**Comment by vishalbiswas** [comment]
@Grimler91 probably occurring because I don't build inside docker. I used to get similar errors previously.

**Comment by tomty89** [comment]
> this ax_cv_PTHREAD_PRIO_INHERIT=no
needs to be added to libpulseaudio configure args as it detects it in libc but its only available at api 28.

Hmm, doesn't the build system of Termux has a general approach that make sure only features of API 21 are available?

**Comment by its-pointless** [comment]
--disable-gst_v4l2 to be added to gst-plugins-good

**Comment by Grimler91** [comment]
torsocks needs a patch. I've opened a PR.

**Comment by vishalbiswas** [comment]
All packages can now be built on this branch except `ltrace` on arm.
Since this is the only instance where the old elf.h is required, hardcoding the required symbol is easier than bringing back elf.h.

What are your thoughts on this?

**Comment by vishalbiswas** [comment]
@its-pointless why?

**Comment by fornwall** [comment]
> Since this is the only instance where the old elf.h is required, hardcoding the required symbol is easier than bringing back elf.h.
> 
> What are your thoughts on this?

Sounds like a good idea!

**Comment by vishalbiswas** [comment]
@its-pointless I haven't had any issues like that. Can you upload the deb file of the package?

**Comment by its-pointless** [comment]
on i686 i install new libc++ and apt no longer works. New libc++ was only change.

**Comment by vishalbiswas** [comment]
@its-pointless I cannot reproduce this behaviour. I installed `libc++` built with new ndk and nothing changed.

**Comment by its-pointless** [comment]
It could depend on api level of rom.

**Comment by vishalbiswas** [comment]
@its-pointless could be. I'm on 25.
If possible can you try the same steps on a fresh install of termux?

**Comment by vishalbiswas** [comment]
@its-pointless can you `ldd` libs needed by libapt-pkg.so?

**Comment by its-pointless** [comment]
libdl.so                                                                           libz.so                                                                            liblzma.so                                                                         libc++_shared.so                                                                   libm.so                                                                            libc.so

**Comment by vishalbiswas** [comment]
and `ldd libm.so`?

**Comment by its-pointless** [comment]
ldd /system/lib/libm.so 
libc.so
ldd /system/lib/libz.so
libc.so
libm.so
libstdc++.so

**Comment by vishalbiswas** [comment]
@its-pointless I wonder why don't we supply our own libz.

**Comment by its-pointless** [comment]
Too many symbol conflicts.

**Comment by vishalbiswas** [comment]
@its-pointless does installing packages with newer ndk17 build (without newer libc++) work?
and do the same work with newer libc++?

**Comment by xeffyr** [comment]
@Grimler91 I set dropbear to build with GCC because on clang I'm getting this:
```
In file included from atomicio.c:30:
In file included from ./includes.h:127:
In file included from ./libtomcrypt/src/headers/tomcrypt.h:83:
./libtomcrypt/src/headers/tomcrypt_cfg.h:45:28: error: redeclaration of 'memcpy' must have the 'overloadable' attribute
LTC_EXPORT void * LTC_CALL XMEMCPY(void *dest, const void *src, size_t n);
                           ^
./libtomcrypt/src/headers/tomcrypt_custom.h:33:18: note: expanded from macro 'XMEMCPY'
#define XMEMCPY  memcpy
```

I will try to update docker image and check if it will build without errors.

**Comment by xeffyr** [comment]
@Grimler91 If it builds with NDK 17, then we can just unset `TERMUX_PKG_CLANG=no`.

**Comment by its-pointless** [comment]
yeah so far testing on i686 on android 5.1  for the new libc++_shared.so to work need to recompile libllvm apt boost.  This should deal with most stuff.
Not updating libc++_shared.so straight away and stagger updates might be an option.

**Comment by its-pointless** [comment]
If it only needs apt llvm and boost ...
llvm needs to update to correct the arm triple, boost needs update to 1.67 as well as compiling the needed assembly from that for coroutine and context, as well and we could update apt to 1.61 anyway.

**Comment by its-pointless** [comment]
also put arm cflags back to Oz from Os the bug should be fixed right @fornwall?

**Comment by vishalbiswas** [comment]
@its-pointless **libc++** is not installable through the repo.
`-Oz` for arm was fixed https://reviews.llvm.org/rL321996. But I still get https://github.com/termux/termux-packages/issues/1680 when building with `-Oz`.
#282 seems to have been fixed (at least when configuring llvm), I'll remove the custom triple from **libllvm** if nobody has any objections.

@Grimler91 Inside **elfutils**' config.log `conftest.c:25:18: error: fields must have a constant size: 'variable length array in structure' extension will never be supported`
and if trying to bypass this test `src/libdwfl/elf-from-memory.c:228:2: error: function definition is not allowed here`
Is there no other way?

**Comment by vishalbiswas** [comment]
@tomty89 This [line](https://github.com/termux/termux-packages/blob/master/packages/libc%2B%2B/build.sh#L3) makes sure you don't need to manually update it.

**Comment by Grimler91** [comment]
@vishalbiswas I was going to say that it doesn't seem to be possible to compile elfutils with clang, [this old bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1211357) discusses it. The same report hints at a couple of patches though and looking at the elfutils git history patches to make elfutils work with clang were applied back in 2015. 

It shouldn't be impossible to fix the error you showed, we have a bunch of patches/git commits that we can look at for inspiration. 
The git MASTER doesn't seem to have any additional commits that would solve this error.

I can ask in their irc channel if someone has tried compiling it with clang6.

**Comment by vishalbiswas** [comment]
@Grimler91 Last year from their mailing list https://sourceware.org/ml/elfutils-devel/2017-q3/msg00102.html

**Comment by Grimler91** [comment]
@vishalbiswas Well look at that, your google-fu is superior to mine.. :)
I'll test it out. Looks promising.

**Comment by vishalbiswas** [comment]
@Grimler91 its actually the one's from 2015 but the mailer has made changes to work with newer versions.
The amount of patching is too much though.
Maybe we should wait until they actually remove gcc before porting this one.
Who knows maybe the folks at llvm will decide to add more options to `-fheinous-gnu-extensions` or the ones at elfutils may actually start writing portable code (who-am-i-kidding)

**Comment by Grimler91** [comment]
I've managed to build elfutils on arm and i686 by adding libobjc2 and linking elfutils to it. 
libobjc2 fails to configure on aarch64 and x86_64 though with:
```
CMake Error at /home/builder/.termux-build/_lib/17-aarch64-21-v1/lib64/cmake
/llvm/LLVMExports.cmake:839 (message):
The imported target "LLVMDemangle" references the file
"/home/builder/.termux-build/_lib/17-aarch64-21-v1/lib64/libLLVMDemangle.a"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
"/home/builder/.termux-build/_lib/17-aarch64-21-v1/lib64/cmake/llvm/LLVMExports.cmake"
but not all the files it references.
Call Stack (most recent call first):
/home/builder/.termux-build/_lib/17-aarch64-21-v1/lib64/cmake/llvm/LLVMConfig.cmake:169 (include)
CMakeLists.txt:129 (find_package)
-- Configuring incomplete, errors occurred!
```
So it needs a bit more love. WIP here: https://github.com/grimler91/termux-packages/tree/ndk17

**Comment by its-pointless** [comment]
sysroot/usr/lib/aarch64-linux-android/libcompiler_rt-extras.a
Might be of some interest concerning clang compatibility
Add it to ndk sysroot?

**Comment by tomty89** [comment]
@Grimler91 I don't think it really has something to do with the architectures. It's just somehow you have files of libllvm-dev (but not libclang-dev) in the build directories of the 64-bit ones. See my tests here: https://ptpb.pw/2H3a
This is probably partly because our current llvm/clang packaging are broken. See #2282 for details, if interested.
I am not sure if the libobjc2 solution makes sense though. Smells a bit like the opencv/libbboost_python case.

**Comment by its-pointless** [comment]
emacs now builds on clang

**Comment by its-pointless** [comment]
termux_step_pre_configure() {
        export LIBS=" -lcompiler_rt-extras"
} 
seems to get it to compile

**Comment by tomty89** [comment]
Makes me wonder if `-rtlib=compiler-rt` should be used with / instead of it.

**Comment by its-pointless** [comment]
no all of the compiler_rt stuff neccesary to replace libgcc is not there. Or we could just add all the stuff from libcompiler_rt-extras into libgcc

**Comment by its-pointless** [comment]
contents of libcompiler_rt-extras 
mulodi4.o


fuck it just add that file to libgcc.a and we are done

**Comment by its-pointless** [comment]
nope this won't work consistently m4 on aarch64 using clang requires __muloti4 which is not in libcompiler_rt-extras.a for aarch64.

**Comment by vishalbiswas** [comment]
@its-pointless `_muloti` is not something I'm terribly worried about. If worse comes to worst, we can use an unoptimised version of a similar function.

**Comment by tomty89** [comment]
@Grimler91 `libLLVMDemangle.a` is currently in `libclang-dev` (a "fake" `-dev` package, i.e. split manually from `libllvm` with a subpackage script) while `LLVMExports.cmake` is currently in `libllvm-dev` (the "real" `-dev` package, i.e. split automatically for libllvm)

Both files are products of the llvm source and has nothing to do with clang.

**Comment by fornwall** [comment]
@vishalbiswas @its-pointless:

> -Oz for arm was fixed https://reviews.llvm.org/rL321996. But I still get #1680 when building with -Oz.

The fix seems to be in r321996, but the [NDK r17 changelog](https://github.com/android-ndk/ndk/wiki/Changelog-r17) says `Updated Clang to build 4691093, based on r316199`, so I guess we'll have to wait for the next NDK update to get this fix.

**Comment by fornwall** [comment]
About gcc->clang transitions: We don't need to have any more of these in this PR, that can be made in separate ones (and some may wait till NDK r18).

**Comment by fornwall** [comment]
> Oh right I missed that, but still anything linked to it should have their revision bumped.

I can make a script which finds all packages that links against `libc++_shared.so` and revision bump them. Should I do that or is anyone else working on it?

**Comment by its-pointless** [comment]
Do that.

**Comment by fornwall** [comment]
@vishalbiswas You can remove `gst-plugins-good/build.sh` from this PR, it has already been applied there when updating the package!

Besides the version bump of libc++-using packages, is there anything else remaining here that we know of?

**Comment by vishalbiswas** [comment]
@fornwall 

> You can remove gst-plugins-good/build.sh from this PR, it has already been applied there when updating the package!

Done!
I don't think anything else is remaining.

**Comment by fornwall** [comment]
@vishalbiswas Could you fix the conflicts, and I'll merge this PR ASAP (and bump the libc++-using packages on master)? This is a large and important change, so it will be good having it on master!

**Comment by fornwall** [comment]
The docker image has been updated - run `scripts/update-docker.sh` to pull it.

**Comment by bensh4** [comment]
@fornwall , @Grimler91 , @xeffyr Can you guys please help me with this, because I currently stopped my project due to this errorr. Kindly help 
https://github.com/termux/termux-packages/issues/2451

**Pull request merged**
