### PR TITLE
aapt: Update to 8.1.0.81 / Include aidl

### LINKED ISSUE #8886: [Package]: Aidl for arm64 and armv7la
### Package description

Aidl  is a build tool for making apps in android and it's very useful for Android developers but it's not launched for arm64 but one guy named Lzhiyong already launched it for arm64 and armv7la for sdk31  but I don't know when he stop updating it so I request termux developer to add aidl(sdk32)  in termux and keep 
Updating it and thanks for aapt2 also Sir 🙏🙏 , You are really helpful sir ☺️

### Home page URL

https://android.googlesource.com/platform/frameworks/base/+/1a008c1/tools

### Source code URL

https://android.googlesource.com/platform/frameworks/base/+/1a008c1/tools/aidl/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I Don't have pc to Compile it and don't know how to compile it for arm64 and armv7la 😅😅

### LINKED ISSUE #8887: [Bug]: Got a Error When Using aapt2 with gradle
### Problem description

Termux recently added aapt2 Support and I use aapt2 in gradle to make apk and got a error 
Screenshot_20220203-095959
I didn't get error if I use  Lzhiyong aapt2 Here is the link https://github.com/Lzhiyong/sdk-tools but the guy is giving sdk31 aapt2 and maybe he didn't update it so I use termux aapt2 , Plz Fix this error.
I want aapt2 from this site for arm64 and armv7la
https://maven.google.com/web/m_index.html?q=aapt2#com.android.tools.build:aapt2
I am 80% sure this site aapt2 will fix the error if you guys launched it for arm64 from this site 

### What steps will reproduce the bug?

Running The Gradle Will Reproduce Error

### What is the expected behavior?

The Expected Behaviour is Gradle runs successfully

### System information

termux-info:

```

```

### PR DESCRIPTION
**Pull request by xtkoba**
Hopefully fixes #8887.

Closes #8886.

### CODE REVIEW

**Comment by xtkoba** [comment]
TODO: Include `aidl` as a subpackage (and supersede #8900).

**Comment by mr-from-us** [comment]
I tested aapt2 and aidl but both not working and giving error
Screenshot_20220205-185044

**Comment by freindlytech** [comment]
I tested  aapt2 and aidl  download from https://github.com/termux/termux-packages/actions/runs/1798941385  , Both are not Working and giving error.

Screenshot_20220205-185044

**Comment by Grimler91** [comment]
@freindlytech it depends on aapt, so you need to install the updated aapt as well

**Comment by freindlytech** [comment]
You Are Right Bro I again Tested it and it runs But I get Error when I use it with gradle , Plz Fix The new issue sir.

Here is the pic of successfully running aapt2 and aidl
Screenshot_20220206-082449

Here Are The Error When I Run aapt2  with gradle as Android Gradle plugin 
Screenshot_20220206-083254
Screenshot_20220206-083303
Screenshot_20220206-083308

**Comment by xtkoba** [comment]
OK. I will borrow a potential fix from https://github.com/Lzhiyong/termux-ndk/issues/53.

**Comment by freindlytech** [comment]
Buddy  you should Have to see my comment on issue maybe it can help you  https://github.com/termux/termux-packages/issues/8887#issuecomment-1030743644

**Comment by xtkoba** [comment]
The comment https://github.com/termux/termux-packages/issues/8887#issuecomment-1030743644 does not make sense to me. What should I do?

**Comment by freindlytech** [comment]
Buddy Just Download and tested aapt2 with gradle from https://github.com/termux/termux-packages/actions/runs/1801416378

But still it giving error 

Screenshot_20220206-110835
Screenshot_20220206-110844
Screenshot_20220206-110851
Screenshot_20220206-110901
Screenshot_20220206-110905

**Comment by xtkoba** [comment]
So `aapt2 link` command should just ignore `--proguard-minimal-keep-rules` option, maybe?

**Comment by freindlytech** [comment]
Don't Know Much more 😅 but I just want a perfect aapt2 that will run with no error with gradle, So sir plz provide it

**Comment by freindlytech** [comment]
Just tested your aapt2 with gradle downloaded from - 
  https://github.com/termux/termux-packages/actions/runs/1801515185
 Still it giving error , You have to launch aapt2 version -7.3.0-alpha01  which give support of sdk32(android 12)  and keep updating it , just like google launches aapt2 for pc  and they update aapt2 regularly here -https://maven.google.com/web/m_index.html?q=aapt2#com.android.tools.build:aapt2

Here is the error I face 

Screenshot_20220206-115405
Screenshot_20220206-115412
Screenshot_20220206-115421
Screenshot_20220206-115428
Screenshot_20220206-115433

**Comment by xtkoba** [comment]
I won't be surprised if there are other "unknown" options. Yeah, it would be better if I could test it by myself.

**Comment by freindlytech** [comment]
Hey buddy this time I face this error when I tested aapt2 from here - https://github.com/termux/termux-packages/actions/runs/1801590880

Here is the Error - 
Screenshot_20220206-123304

**Comment by xtkoba** [comment]
Seems like further update is required. I will try to do it but I cannot assure it will be successful.

**Comment by freindlytech** [comment]
Ok 😞,Thanks For You Help You are really Very Very  Helpful 
Trust me You have to check this site - https://maven.google.com/web/m_index.html?q=aapt2#com.android.tools.build:aapt2

This site provide aapt2(7.3.0-alpha01(latest) and much more ) 
 for pc and I just want it for arm64

**Pull request closed without merging**
