### PR TITLE
Add solidity compiler

### PR DESCRIPTION
**Pull request by Wetitpig**
This is the original compiler for solidity, a programming language for Ethereum smart contracts.

### CODE REVIEW

**Comment by Grimler91** [comment]
What's the reason for removing Werror? What error did you get otherwise?

**Comment by Wetitpig** [comment]
All warnings became errors
As you see, there were like 210k lines of logs and they were mostly warnings.

The final executable seems to be working still.

**Comment by Wetitpig** [comment]
> What's the reason for removing Werror? What error did you get otherwise?

As I have checked most warnings come from the `boost` library, on sign conversion problems. There are also a few warnings on unused arguments. They are NOT from the `solidity` package itself.

**Comment by Grimler91** [comment]
Could you please add this patch:
```
--- ../EthCompilerSettings.cmake.orig   2020-08-09 18:45:50.190024571 +0200                                                                                                           +++ ./cmake/EthCompilerSettings.cmake   2020-08-09 18:49:55.612385181 +0200
@@ -208,9 +208,6 @@                                                                                                                                                                    if (("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU") OR ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang"))
        option(USE_LD_GOLD "Use GNU gold linker" ON)
        if (USE_LD_GOLD)                                                                                                                                                              -               execute_process(COMMAND ${CMAKE_CXX_COMPILER} -fuse-ld=gold -Wl,--version ERROR_QUIET OUTPUT_VARIABLE LD_VERSION)
-               if ("${LD_VERSION}" MATCHES "GNU gold")                                                                                                                               -                       set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fuse-ld=gold")
-               endif ()
+               set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fuse-ld=gold")                                                                                                         endif ()
 endif ()
```
to fix the 
```
clang++: error: argument unused during compilation: '-fuse-ld=gold' [-Werror,-Wunused-command-line-argument]
```
errors.

But as you said, -Werror still has to be removed since boost gives a lot of warnings.

**Comment by Wetitpig** [comment]
By the way, something peculiar is that all such warnings do not appear when `solidity` is built on device (not a package). Is it just the behaviour of `make` to silence all warnings on device or be verbose in the `build-package.sh`?

**Comment by xeffyr** [comment]
@Wetitpig I guess that's compiler-related. Termux doesn't use NDK toolchain.

**Comment by buttaface** [comment]
Ready to merge?

**Comment by Grimler91** [comment]
Yeah, I am satisfied

**Pull request merged**
