### PR TITLE
rust: update to 1.45

### PR DESCRIPTION
**Pull request by coolreader18**
Split off from #5387

### CODE REVIEW

**Comment by coolreader18** [comment]
HAHA, Progress! ` nm -D ~/.termux-build/_cache/android-r20-api-24-v3/sysroot/usr/lib/x86_64-linux-android/*/libc.so | grep __res_init` returns _nothing_! The issue IS with the android toolchain, though I really have no idea why it only started happening with 1.44. Maybe more of the "rustc sees it's the same arch for host and target, so it has different behavior than with the other targets" thing?

**Comment by its-pointless** [comment]
yeah it when it builds tools for build host it might not find android sysroot libc.so or for local build it doesn't find local libc.so but finds sysroot. It has done that on and off when building for termux for years.

**Comment by coolreader18** [comment]
Looks like Rust 1.45 resolves this issue!

**Comment by coolreader18** [comment]
We could probably try seeing if it fixes the issue with x86_64 as well, but maybe in another pr.

**Comment by its-pointless** [comment]
> We could probably try seeing if it fixes the issue with x86_64 as well, but maybe in another pr.

i think i have a fix for x86_64

**Comment by its-pointless** [comment]
can't get it done unfortunately, cargo fails to build for me and i have no more free time.

**Comment by dram** [comment]
How about have a try without `res_init-symbol-name.patch`, I think it is not necessary, just as 1.43.

**Comment by its-pointless** [comment]
I have and patch is not needed to compile.
As a hint here is how it built everything until the tools like cargo wtih x86_64-linux-android i added 
export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/:/data/data/com.termux/files/usr/lib

**Comment by its-pointless** [comment]
try adding 
export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/:/data/data/com.termux/files/usr/lib 
for x86_64 build to see if it works.

**Comment by its-pointless** [comment]
fixed version https://github.com/its-pointless/termux-packages/blob/rustaaaa/packages/rust/build.sh

**Comment by coolreader18** [comment]
Weird... libxml isn't building for some reason. Is that an issue on master?

**Comment by landfillbaby** [comment]
just a couple of guesses here but, you could try adding libxml2 as a dependency?
or it might be that it's searching the wrong include paths, since the missing header is actually in `libxml2/libxml/parser.h` and it's looking for it in just `libxml/parser.h`

**Comment by coolreader18** [comment]
I think it's failing while building libxml as a dependency, though. Specifically while building cfengine, maybe? Does that vendor libxml?

**Comment by its-pointless** [comment]
Probably need to rebase it to latest master commit

**Comment by coolreader18** [comment]
Oh, good idea lol

**Comment by landfillbaby** [comment]
maybe try rebasing to master again?

**Comment by coolreader18** [comment]
Ah, looks like it's fine now.

**Comment by its-pointless** [comment]
This needs to be merged

**Comment by roalyr** [comment]
Maybe previous branch shouldn't have been deleted so soon? Clippy doesn't work #5614
And there is no way to roll back to previous version (according to `apt policy`).

**Comment by coolreader18** [comment]
We could try updating to 1.45.2, that just came out yesterday

**Comment by roalyr** [comment]
It will be great to have clippy working on the next week, when I am resuming refactoring my code.

Also, is this a problem to keep a single previous stable version in repo at all times as a measure of redundancy?

Thanks for your response and thanks in advance for you work!

**Pull request merged**
