### PR TITLE
Enable pulseaudio in mpv

### PR DESCRIPTION
**Pull request by Neo-Oli**
Since pulseaudio is available now, it would be cool if all our media
players would support it.

### CODE REVIEW

**Comment by tomty89** [comment]
Consider adding this: https://github.com/mpv-player/mpv/pull/6047. Fixes the `--pulse-buffer` option.

**Comment by Neo-Oli** [comment]
@tomty89 How is `--pulse-buffer` broken?

**Comment by Neo-Oli** [comment]
@tomty89 fair enough. Added your patch to this PR.

**Comment by fornwall** [comment]
Thanks! The updated package is now available for installation.

**Pull request merged**
