### PR TITLE
neovim: remove patch for `man` command

### PR DESCRIPTION
**Pull request by licy183**

### CODE REVIEW

**Comment by thunder-coding** [comment]
If you're force pushing to the master branch please consider notifying via Gitter/Matrix channel on https://gitter.im/termux/dev

**Comment by licy183** [comment]
> If you're force pushing to the master branch please consider notifying via Gitter/Matrix channel on https://gitter.im/termux/dev

OK, I see. I force-pushed branch `issue-16720`, and I think I haven't pushed on the master branch so far...

**Comment by thunder-coding** [comment]
> OK, I see. I force-pushed branch issue-16720, and I think I haven't pushed on the master branch so far...

:sweat_smile: Sorry, I seem to have misread the activity page :)

**Comment by xtkoba** [comment]
Superseded by #16821.

**Pull request closed without merging**
