### PR TITLE
ldc-beta: add package

### PR DESCRIPTION
**Pull request by joakim-noah**
This is an updated version of the ldc package, built from the recently released ldc 1.4 beta1.  I want to use it alongside the ldc package, so I added the `-beta` designation to executables, directories, libraries, and the config file.  If you diff it against the latest version of ldc in #1311, that's basically all that changed.

### CODE REVIEW

**Comment by joakim-noah** [comment]
Updated this pull with some `-beta` designations I missed and to package the `ldc-build-runtime` tool also.

**Comment by its-pointless** [comment]
So you are only able to build on arm due to runtime?
Looking at source i think i686 runtime should build as well
aarch64 and x86_64 runtime not supported?

**Comment by joakim-noah** [comment]
x86 should work, but [as noted before, I wasn't able to test it](https://github.com/termux/termux-packages/pull/1078#issuecomment-312609273), so didn't want to add a potentially broken package.  I'm currently trying out AArch64, having some issues with TLS, which apparently works differently.  I've never run x64, as the isos I tried wouldn't run properly in kvm.

**Comment by its-pointless** [comment]
If you need testing just make a branch that i686, aarch64 builds and i can test it.

**Comment by joakim-noah** [comment]
I wanted to actually run the full testsuite on Android/x86 by compiling ldc natively in Termux, which meant compiling my patched llvm in there too, but ran into issues with the clang toolchain in Termux and the bugginess of the android-x86 builds.  Perhaps I was being too ambitious though, I could just cross-compile the D standard library's tests and quickly run them in android-x86.  I'll try that today.

As for AArch64, I have access to some hardware now, so I'm in the process of porting it.  I will update this package when that's done, no need to hold off on making it available for ARM until then though.

Android/x64 is the only one I have no access to, so I'd need someone to run the tests for me there.

**Comment by joakim-noah** [comment]
Just built the stdlib tests for Android/x86 without a problem with no source modifications, then ran them in Android-x86 running in a kvm VPS, but it looks like something broke in the emulated TLS I put together, as it's getting incorrect pointers passed to `___tls_get_addr`.  It used to work at one point, as I first got ldc for Android working on Android/x86.  I'm disinclined to debug this low-level stuff and figure it out now, given almost nobody is using this platform.

**Comment by joakim-noah** [comment]
@fornwall, this package is ready to go, similar to nodejs-current in conception, let me know what you think.

**Comment by joakim-noah** [comment]
Updated this pull to use [a lightly modified version of the `llvm-config.in` from `libllvm`](https://github.com/termux/termux-packages/blob/master/packages/libllvm/llvm-config.in) and a few other tweaks.  Once the first ldc 1.5 beta is out, I'll update with that and this pull will be ready to merge.

**Comment by joakim-noah** [comment]
Updated this pull to use [the new ldc 1.5 beta that was just released](https://github.com/ldc-developers/ldc/releases/tag/v1.5.0-beta1), this PR is now ready to merge.  @fornwall, let me know.

**Comment by joakim-noah** [comment]
@fornwall, if you're okay with the concept of having an ldc-beta package, can you just merge this pull, even though the ldc package is ahead now?  If you're okay with this, I'll submit another pull when the 1.6 beta comes out later this month.

**Comment by fornwall** [comment]
@joakim-noah Sorry for the late reply here.

I'm a bit hesitant to add these kind of packages to the main repo, in the interest of keeping the build times and maintenance burden down.

I just pushed some work to make it easier to maintain packages out-of-tree, see https://groups.io/g/termux/topic/building_out_of_tree_packages/6290526. Do you think that is an alternative for ldc-beta - maintaining it out of tree, building and distributing it yourself (perhaps with https://github.com/termux/termux-apt-repo if you want to maintain an apt repo so that users can more easily update)?

An advantage for you would be that you can update and try out things quicker, without having to go through this central repository.

**Comment by joakim-noah** [comment]
OK, not a big deal, I can just build and distribute this package myself.  Thanks for considering and responding.

**Pull request closed without merging**
