### PR TITLE
added dbus package

### PR DESCRIPTION
**Pull request by RossComputerGuy**
Required for dbus-glib by telepathy-glib for zeistgeist by midori.

### CODE REVIEW

**Comment by RossComputerGuy** [comment]
For once, it actually doesnt have a red cross. We could decrease build times by adding `--disable-tests` to the configure arguments.

**Comment by RossComputerGuy** [comment]
Just noticed this command needs to be ran to get dbus working `dbus-uuidgen >

**Comment by RossComputerGuy** [comment]
User needs to run `export $(dbus-launch)` to start dbus, wiki should include a page about dbus.

**Comment by xeffyr** [comment]
> Just noticed this command needs to be ran to get dbus working

Post-installation script can do this.

**Comment by RossComputerGuy** [comment]
I dont know how to do post install scripts.

**Comment by xeffyr** [comment]
> I dont know how to do post install scripts.

I'll do it.

**Comment by RossComputerGuy** [comment]
Everything seems to work so I think this is ready, i ran some tests and i was able to do stuff.

**Pull request merged**
