### PR TITLE
htop: update to 3.0.5 from root-repo

### PR DESCRIPTION
**Pull request by wmcbtech30**
To keep `htop` atleast up-to-date, instead of restricting users to use the old version of htop or rooting their device just to view process list. we can provide a dummy status file for htop to continue getting updates as a workaround and usability for stock devices

but there's a caveat:
CPU usage information will give inaccurate results. but since Android 8+ restricts this probably we can only view and kill processes, root users may not be a benefit but I patched htop to read contents in `$PREFIX/var/htop` instead.

Users can symlink the actual proc files if they wanted to. do not merge this until `htop` is usable within this update

### CODE REVIEW

**Comment by Grimler91** [comment]
With htop-legacy non-root users were able to get accurate information, while root users could also use htop and get accurate information. 

With this change no user can get accurate cpu info anymore. I think it is better to keep a htop-legacy and separate htop package, I'm not sure what the benefit of merging them again is (other than decreasing disk space usage on fosshost)

**Comment by wmcbtech30** [comment]
I haven't tested the theory of inaccurate information but i'm sure it's a tradeback. i don't have such test devices but i'm testing it on virtual device

**Comment by thunder-coding** [comment]
Rebase against master so that the CI only builds the affected packages and not others

**Comment by thunder-coding** [comment]
Seems like you rebased against upstream/master and hence commits are being spammed. Reset to previous state and first make sure your origin/master is up to date with upstream, then rebase against origin/master

**Comment by wmcbtech30** [comment]
Ok i rebased and squashed all messed up commits that i made, please forgive me 😂

**Comment by wmcbtech30** [comment]
I think this can be merged now, seems this change is consistent enough. unless there's an objection

**Comment by Grimler91** [comment]
Build recipe looks alright, package should be removed from root-repo then also

**Pull request merged**
