### PR TITLE
fix docker volume read/write permission

### PR DESCRIPTION
**Pull request by hacknox**
Docker container builder users uid and gid to 1000, if the root user or other users run run-docker.sh will appear permission denied

### CODE REVIEW

**Comment by Wetitpig** [comment]
Good. I have been receiving permission denied messages.

**Comment by fornwall** [comment]
> Docker container builder users uid and gid to 1000, if the root user or other users run run-docker.sh will appear permission denied

Sorry if missing the problem here. We want to run as the `builder` user inside the docker container, and that happens regardless of who runs `run-docker.sh`, root or not, right?

**Comment by hacknox** [comment]
Yes

在 2017年3月5日，下午12:04，Fredrik Fornwall <notifications@github.com<mailto:notifications@github.com>> 写道：


Docker container builder users uid and gid to 1000, if the root user or other users run run-docker.sh will appear permission denied

Sorry if missing the problem here. We want to run as the builder user inside the docker container, and that happens regardless of who runs run-docker.sh, root or not, right?

**Comment by fornwall** [comment]
Sorry, I'm not understanding what problem this fixes - let me know and I'll reopen it!

**Comment by rnauber** [comment]
Hi there,

```
./scripts/run-docker.sh ./build-package.sh libpng
[...]
src/musl-multibyte/internal.c:21:18: note: expanded from macro 'F'
             | ( R(0x80,0xc0) >> 12 ) \
                 ^~~~~~~~~~~~
src/musl-multibyte/internal.h:19:52: note: expanded from macro 'R'
#define R(a,b) ((uint32_t)((a==0x80 ? 0x40-b : -a) << 23))
                           ~~~~~~~~~~~~~~~~~~~~~~~ ^
119 warnings generated.
ar: /home/builder/termux-packages/debs/libandroid-support-dev_15_aarch64.deb: Permission denied
```


The problem is that my user that runs the container has not uid=1000:

```
olg@arbeitstierchen:~/scratch/android/termux-packages$ id
uid=1002(olg) gid=1002(olg) groups=1002(olg),4(adm),20(dialout),21(fax),24(cdrom),25(floppy),26(tape),33(www-data),46(plugdev),100(users),112(lpadmin),121(admin),123(sambashare),153(docker)
```

And this prevents the user inside the container (with uid=1000) from writing to the /debs directory.

@fornwall could you please merge the patches of @hacknox ? I have tested them and they work (after you recreate the container with `docker stop termux-package-builder; docker rm termux-package-builder`)...

Thanks!

**Comment by rnauber** [comment]
@fornwall: there were still some pieces missing, which I fixed on top of @hacknox commits. So please merge #1132 ...
Thanks,
Richard

**Pull request closed without merging**
