### PR TITLE
fix(main/luvi): fix incompatible bytecode error

### PR DESCRIPTION
**Pull request by mbekkomo**
```
$ luvi . --
init.lua: cannot load incompatible bytecode
stack traceback:
        [C]: at 0x61b25d8c94
        [C]: in function 'require'
        [string "return require('init')(...)"]:1: in main chunk
```

A little bit note: I bumped the pinned commit to latest one because the commit it was referring to did not exist.

### CODE REVIEW

**Comment by cattokomo** [comment]
Once this PR is merged, can you also rebuild the `luvit` and `lit` package?

**Comment by Biswa96** [comment]
It would be better to put the error in commit message.

```
$ echo 'print "hello"' > main.lua

$ luvi . --
init.lua: cannot load incompatible bytecode
stack traceback:
        [C]: at 0x61b25d8c94
        [C]: in function 'require'
        [string "return require('init')(...)"]:1: in main chunk
```

**Comment by cattokomo** [comment]
> It would be better to put the error in commit message.
> 
> ```
> $ echo 'print "hello"' > main.lua
> 
> $ luvi . --
> init.lua: cannot load incompatible bytecode
> stack traceback:
>         [C]: at 0x61b25d8c94
>         [C]: in function 'require'
>         [string "return require('init')(...)"]:1: in main chunk
> ```

I will do that once this PR is confirmed to be merge.

**Comment by Biswa96** [comment]
I have tested the aarch64 package from CI artifact and it's working fine in my phone.

```
$ luvi . --
hello
```

**Comment by TomJo2000** [comment]
> See [this message in Termux Discord server](https://discord.com/channels/641256914684084234/641256914684084237/1291994033832591362).

Reproduced here in full because not everyone uses discord.

<h1><em></em></h1>  

> ```
> $ luvi . --
> init.lua: cannot load incompatible bytecode
> stack traceback:
>         [C]: at 0x61b25d8c94
>         [C]: in function 'require'
>         [string "return require('init')(...)"]:1: in main chunk
> ```

**Review by TomJo2000 — APPROVED** [review]
LGTM I would just like to clean up the patch name before merging.

Numbered patches usually have 4 digits.
See: https://github.com/termux/termux-packages/tree/master/x11-packages/wine-stable

So either rename the patch to `0001-skip-script-compiling.patch`
or `skip-script-compiling.patch`.

I'll also do the rebuilds for `lit` and `luvit` after this is merged.

**Comment by mbekkomo** [comment]
For some reason, the CI tries to build another packages. I'll close this an open a new one

**Comment by Biswa96** [comment]
You could also rebase the branch with master branch.

**Comment by TomJo2000** [comment]
> For some reason, the CI tries to build another packages. I'll close this an open a new one

You probably hit update branch instead of rebase branch.

**Comment by mbekkomo** [comment]
> > For some reason, the CI tries to build another packages. I'll close this an open a new one
> 
> You probably hit update branch instead of rebase branch.

Can't quite remember about that.

**Pull request closed without merging**
