### PR TITLE
tealdeer: add shell completions

### PR DESCRIPTION
**Pull request by flipee**

### CODE REVIEW

**Review by TomJo2000 — APPROVED** [review]
Thanks for the contribution.

**Comment by Biswa96** [comment]
Please add `TERMUX_PKG_REVISION=1` after pkg version.

**Review by TomJo2000 — CHANGES_REQUESTED** [review]
Hold on, you forgot to bump the package revision.
Apt won't see it as a newer version without setting
`TERMUX_PKG_REVISION=1` so it builds as 1.6.1-1

**Comment by TomJo2000** [comment]
> Please add `TERMUX_PKG_REVISION=1` after pkg version.

jinx, just noticed the same thing.

**Review by TomJo2000 — APPROVED** [review]

**Review by TomJo2000 — APPROVED** [review]

**Comment by flipee** [comment]
Whoops. Done, thanks!

**Comment by TomJo2000** [comment]
Eh no worries, I forget revbumping packages constantly.

**Comment by TomJo2000** [comment]
All right this is just add completions and bump, so we're good to merge.

**Pull request merged**
