### PR TITLE
Add privoxy package

### PR DESCRIPTION
**Pull request by vaites**
Another interesting package: 

> [Privoxy](https://www.privoxy.org/) is a non-caching web proxy with advanced filtering capabilities for enhancing privacy, modifying web page data and HTTP headers, controlling access, and removing ads and other obnoxious Internet junk. Privoxy has a flexible configuration and can be customized to suit individual needs and tastes. It has application for both stand-alone systems and multi-user networks. 

Why is interesting? You can proxy all device traffic through this proxy, making a [system-wide ad blocker](http://blog.vanutsteen.nl/2014/01/05/installing-privoxy-with-adblock-filters-on-openwrt/) or you can use the hotspot and filter the traffic of connected devices...

Daemon needs to be launched with user detected with `whoami`. Example running from `$HOME`:

```
privoxy --user u0_a94.u0_a94 --no-daemon ../usr/etc/privoxy/config
```

### CODE REVIEW

**Comment by its-pointless** [comment]
It doesn't install if you are root. Which is annoying because the people using docker image are using root. So perhaps you could patch GNUmakefiles.in ?

**Comment by vaites** [comment]
@its-pointless this worth the effort? I mean, if this package is added repository there's no need to build it... why spend some time to enable something that will be used one or two times?

**Comment by its-pointless** [comment]
People rebuild entire tree using docker image. This bug prevents installing into the local build /data/ within the docker image which means build-all.sh fails when using docker image.

**Comment by vaites** [comment]
@its-pointless didn't think in rebuilding entire tree... but don't know how to fix this problem, my C knowledge is limited...

**Comment by its-pointless** [comment]
Just commenting out the user checks in GNUmake.in fixes it. comment out line 875 to 909. Not really c just scripts.

**Comment by vaites** [comment]
@its-pointless done, hope it works!

**Comment by vaites** [comment]
Thanks!

**Comment by fornwall** [comment]
Thanks yourself, and sorry for the delay here! The built package is now available for installation:

    apt update && apt install privoxy

**Pull request merged**
