### PR TITLE
fix(main/{plantuml,procyon-decompiler}): Update gradle versions to 8.10.2

### PR DESCRIPTION
**Pull request by robertkirkman**
Fixes gradle hanging under certain conditions in the two remaining packages where the issue could be reproduced. See:

- https://github.com/termux/termux-packages/issues/21130#issuecomment-2422331542
- https://github.com/gradle/gradle/issues/14961
- https://github.com/termux/termux-packages/commit/a7627acf5a8104ff5634330110ff9acd661c09d8

[no ci]

### CODE REVIEW

**Comment by twaik** [comment]
You must bump TERMUX_PKG_REVISION or use `[no ci]` in commit description, otherwise CI will fail after merging to master.

**Comment by twaik** [comment]
Is there a reason to use `gradle-8.10` for one package and `gradle-8.10.2` for another? Should not they be the same version?

**Comment by robertkirkman** [comment]
> Is there a reason to use `gradle-8.10` for one package and `gradle-8.10.2` for another? Should not they be the same version?

The reason is because the plantuml upstream is currently set at gradle 8.10, so I cherry picked that comnmit which they used to set it there. On the other hand, procyon-decompiler's upstream repository does not have as much active development, so the patch for gradle 7 which fornwall placed on it a while ago is still not merged upstream. Therefore I first applied all preexisting termux-packages patches to a clone of the procyon-decompiler repository, then I read the [upgrading gradle version from 7 to 8 documentation](https://docs.gradle.org/current/userguide/upgrading_version_7.html) and followed the steps until I got to the command `gradle wrapper --gradle-version 8.10.2`. I copied and pasted that command it and caused the gradle version for that package to update all the way to 8.10.2 and there were no errors, and the resulting package worked, so I assumed that no further action was necessary.

If you think that it would be better to update them both to the exact same version regardless of the status of the upstream projects, let me know and I will change and test the plantuml patch so that it uses gradle version 8.10.2 also, to match.

**Comment by twaik** [comment]
I think if it will work with `8.10.2` for both packages on your device it will be fine to have same versions. Also I have to say `8.10.2` is a patch release compared to `8.10` so it should be fine.

**Comment by robertkirkman** [comment]
> I think if it will work with `8.10.2` for both packages on your device it will be fine to have same versions. Also I have to say `8.10.2` is a patch release compared to `8.10` so it should be fine.

Ok thank you, it will take a little while to fully repatch and retest the plantuml package and then I will mark this for review again when it is ready.

**Review by twaik — APPROVED** [review]

**Pull request merged**
