### PR TITLE
new package: mdns-scan

### PR DESCRIPTION
**Pull request by msoose**
#4906

### CODE REVIEW

**Comment by msoose** [comment]
Is this an accepted way of setting the correct path?

**Comment by xploitednoob** [comment]
Your Build Is Not Working Add Required Patch File

**Comment by msoose** [comment]
@xploitednoob I can see it's not building, I want to know why adding `DESTDIR` to `TERMUX_PKG_EXTRA_MAKE_ARGS` and `TERMUX_PKG_MAKE_INSTALL_TARGET` doesn't work in the pipeline when it builds in Docker for me.

**Comment by msoose** [comment]
Isn't `TERMUX_PREFIX` set to `/data/data/com.termux/files/usr/`?, I need to be up one directory, so this is what I came up with.

**Comment by xploitednoob** [comment]
> Isn't `TERMUX_PREFIX` set to `/data/data/com.termux/files/usr/`?, I need to be up one directory, so this is what I came up with.
```
$TERMUX_PREFIX/..Should Work Same

**Comment by msoose** [comment]
Both work fine, one is a bit ugly to me.

I would like to know what the acceptable and preferred way of doing it, according to Termux guidelines.

**Comment by xploitednoob** [comment]
> Both work fine, one is a bit ugly to me.
> 
> I would like to know what the acceptable and preferred way of doing it, according to Termux guidelines.Lets 

This build.sh should be okkkkk.

**Comment by Grimler91** [comment]
@msoose `$TERMUX_PREFIX/..` as suggested by @xploitednoob would be better so that the prefix can be changed by editing https://github.com/termux/termux-packages/blob/44d00107d3240b7da48506bf8cfce3a3add3df33/scripts/build/termux_step_setup_variables.sh#L5 only. That being said, it is a bit ugly. I would probably patch the [Makefile](https://github.com/alteholz/mdns-scan/blob/ccab0bcc673ca4fbeb3db633e7524d93745fd5f3/Makefile#L21) to make it install to `$(PREFIX)/bin` instead of `$(DESTDIR)/usr/bin`

**Comment by xploitednoob** [comment]
> @msoose `$TERMUX_PREFIX/..` as suggested by @xploitednoob would be better so that the prefix can be changed by editing
> 
> https://github.com/termux/termux-packages/blob/44d00107d3240b7da48506bf8cfce3a3add3df33/scripts/build/termux_step_setup_variables.sh#L5
> 
> only. That being said, it is a bit ugly. I would probably patch the [Makefile](https://github.com/alteholz/mdns-scan/blob/ccab0bcc673ca4fbeb3db633e7524d93745fd5f3/Makefile#L21) to make it install to `$(PREFIX)/bin` instead of `$(DESTDIR)/usr/bin`

I Have Already Patched The Makefile But When I Saw This PR. I Deleted Them.
@msoose you should patch the makefile

**Pull request merged**
