### PR TITLE
hugo: Update from 0.55.6 to 0.57.2

### PR DESCRIPTION
**Pull request by danobr**
Update hugo package from 0.55.6 to 0.57.2.

This is my first contribution to termux-packages so please tell me if I am forgetting something in the contribution guidelines.

TODO
- [x] Follow-up on CI status
- [ ] Manual test with hugo 0.57.2 (using my blog https://alarencontredumonde.gitlab.io)

### CODE REVIEW

**Comment by danobr** [comment]
Fail... :( 

I get the same error on Termux when trying to build hugo 0.57.2 from the sources in the tar.gz (build command `go install`):
```build google.golang.org/grpc/internal/syscall: cannot load google.golang.org/grpc/internal/syscall: no Go source files```

It seems to be an issue already documented here:
https://github.com/grpc/grpc-go/issues/2667

Still need to investigate more...

**Comment by danobr** [comment]
Hi @fornwall and @xeffyr !

I'm tagging you because you are the two contributors of the Hugo package on Termux.
I love Termux and Hugo as it allows me to work on my travel blog while traveling so I decided to try to contribute. :)

A couple of questions for my first PR:
- Is it possible to download the Hugo binary from CirrusCI to do a manual test on my side?
- What do you think of my patch to make the build work (the - tags Linux option)? I know it is not ideal...

Thanks in advance for your help and please do not hesitate to give me feedback to improve future PRs.

**Comment by xeffyr** [comment]
> Is it possible to download the Hugo binary from CirrusCI to do a manual test on my side?

Did you checked CI's log page ? There prompt with artifacts download.

> What do you think of my patch to make the build work (the - tags Linux option)? I know it is not ideal.

Its okay.

I'm merging this now since I don't see any reason why new version of `hugo` shouldn't work.

**Comment by danobr** [comment]
Thanks @xeffyr for merging! :)

> Did you checked CI's log page ? There prompt with artifacts download.

The CirrusCI log page isn't very Android friendly for downloading the artifacts. I just figured out how to do it using an app called "Advanced Download Manager". I did my manual tests.

**Comment by danobr** [comment]
@xeffyr

There seems to be a problem with the `hugo` binaries on https://dl.bintray.com/termux/termux-packages-24/

A `pkg search hugo` still finds `hugo/stable,now 0.55.6-1 aarch64` on my Android devices.

Looking at dl.bintray.com, I notice that the results differ depending on the platform (some have 2 deb packages!).

*arm*
- https://dl.bintray.com/termux/termux-packages-24/arm/:hugo_0.55.6-1_arm.deb
- https://dl.bintray.com/termux/termux-packages-24/arm/:hugo_0.57.2_arm.deb

*aarch64*
- https://dl.bintray.com/termux/termux-packages-24/aarch64/:hugo_0.55.6-1_aarch64.deb

*i686*
- https://dl.bintray.com/termux/termux-packages-24/i686/:hugo_0.55.6-1_i686.deb

*x86_64*
- https://dl.bintray.com/termux/termux-packages-24/x86_64/:hugo_0.55.6-1_x86_64.deb
- https://dl.bintray.com/termux/termux-packages-24/x86_64/:hugo_0.57.2_x86_64.deb

Is there something wrong with my PR? Please tell me if I can investigate more.

**Comment by danobr** [comment]
Given platform `aarch64`:

On the CI, task "Upload packages to Bintray":
https://cirrus-ci.com/task/5340194159460352
`[!] Empty archive '/tmp/debs-aarch64-c4893382a9ba247efaf45022c6418dd15a284e85.tar.gz'.`

However, to me, everything seems normal in the "Build" task:
https://cirrus-ci.com/task/5480931647815680
`[*] Archiving packages into 'debs-aarch64-c4893382a9ba247efaf45022c6418dd15a284e85.tar.gz'.`

**Comment by xeffyr** [comment]
To pass packages between tasks we need to use http cache which is unreliable. So missing packages happen sometimes.

**Pull request merged**
