### PR TITLE
add ncurses to gdb depends and build depends

### PR DESCRIPTION
**Pull request by stephengroat**
#1169

### CODE REVIEW

**Comment by fornwall** [comment]
Hm, what is the advantage of `group: deprecated-2017Q3`?

**Comment by fornwall** [comment]
Ah, I saw the linked #1403 now.

**Comment by fornwall** [comment]
I've pushed `group: deprecated-2017Q3` in .travis.yml in a separate commit now!

About adding `ncurses-ui-libs` to the dependencies of gdb: I cannot see that gdb links against any of the provided libraries (libmenu, libform or libpanel) from `ncurses-ui-libs`.

**Comment by stephengroat** [comment]
seems to be linking against ncurses libs, and the `WINDOW` call makes me think i need the UI libs. might still compile with just the `ncurses-dev` library (since it'll have the `ncurses-ui-libs` headers), but will probably fail linking

```
aarch64-linux-android-clang++ -std=gnu++11 -Oz   -I. -I. -I./common -I./config -DLOCALEDIR="\"/data/data/com.termux/files/usr/share/locale\"" -DHAVE_CONFIG_H -I./../include/opcode -I./../opcodes/..  -I./../zlib -I../bfd -I./../bfd -I./../include -I../libdecnumber -I./../libdecnumber  -I./gnulib/import -Ibuild-gnulib/import   -DTUI=1 -I/data/data/com.termux/files/usr/include   -Wall -Wpointer-arith -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wunused-but-set-parameter -Wunused-but-set-variable -Wno-sign-compare -Wno-narrowing -Wformat-nonliteral  -c -o tui-data.o -MT tui-data.o -MMD -MP -MF .deps/tui-data.Tpo tui/tui-data.c
tui/tui.c:409:7: error: unknown type name 'WINDOW'
      WINDOW *w;
      ^
tui/tui.c:410:7: error: unknown type name 'SCREEN'
      SCREEN *s;
      ^
tui/tui.c:425:11: error: use of undeclared identifier 'newterm'
      s = newterm (NULL, stdout, stdin);
          ^
clang50++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
tui/tui.c:437:11: error: use of undeclared identifier 'stdscr'; did you mean 'strstr'?
      w = stdscr;
          ^~~~~~
          strstr
/home/builder/.termux-build/_lib/15.2-aarch64-21-v12/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../include/c++/4.9.x/string.h:106:13: note: 'strstr' declared here
      char* strstr(      char* __s1, const char* __s2) {return __libcpp_strstr(__s1, __s2);}
            ^
tui/tui.c:442:13: error: use of undeclared identifier 'tigetstr'
      cap = tigetstr ((char *) "cup");
            ^
15 warnings generated.
warning: unknown warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Wunknown-warning-option]
warning: unknown warning option '-Wunused-but-set-variable'; did you mean '-Wunused-const-variable'? [-Wunknown-warning-option]
tui/tui.c:445:4: error: use of undeclared identifier 'endwin'
          endwin ();
          ^
tui/tui.c:453:7: error: use of undeclared identifier 'cbreak'
      cbreak ();
      ^
tui/tui.c:454:7: error: use of undeclared identifier 'noecho'
      noecho ();
      ^
tui/tui.c:457:7: error: use of undeclared identifier 'nl'
      nl();
      ^
aarch64-linux-android-clang++ -std=gnu++11 -Oz   -I. -I. -I./common -I./config -DLOCALEDIR="\"/data/data/com.termux/files/usr/share/locale\"" -DHAVE_CONFIG_H -I./../include/opcode -I./../opcodes/..  -I./../zlib -I../bfd -I./../bfd -I./../include -I../libdecnumber -I./../libdecnumber  -I./gnulib/import -Ibuild-gnulib/import   -DTUI=1 -I/data/data/com.termux/files/usr/include   -Wall -Wpointer-arith -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wunused-but-set-parameter -Wunused-but-set-variable -Wno-sign-compare -Wno-narrowing -Wformat-nonliteral  -c -o tui-disasm.o -MT tui-disasm.o -MMD -MP -MF .deps/tui-disasm.Tpo tui/tui-disasm.c
tui/tui.c:460:31: error: use of undeclared identifier 'LINES'
      tui_set_term_height_to (LINES);
                              ^
tui/tui.c:461:30: error: use of undeclared identifier 'COLS'
      tui_set_term_width_to (COLS);
                             ^
tui/tui.c:462:7: error: use of undeclared identifier 'def_prog_mode'
      def_prog_mode ();
      ^
clang50++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
fatal error: too many errors emitted, stopping now [-ferror-limit=]
48 warningswarning and : 20 errorsunknown generated.
 warning option '-Wunused-but-set-parameter'; did you mean '-Wunused-parameter'? [-Wunknown-warning-option]
warning: unknown warning option '-Wunused-but-set-variable'; did you mean '-Wunused-const-variable'? [-Wunknown-warning-option]
Makefile:1950: recipe for target 'tui.o' failed
make[2]: *** [tui.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from tui/tui-command.c:22:
In file included from ./defs.h:53:
./ui-file.h:93:28: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern int ui_file_isatty (struct ui_file *);
                           ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./ui-file.h:93:28: note: did you mean class here?
extern int ui_file_isatty (struct ui_file *);
                           ^~~~~~
                           class
./ui-file.h:95:28: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern void ui_file_write (struct ui_file *file, const char *buf,
                           ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./ui-file.h:95:28: note: did you mean class here?
extern void ui_file_write (struct ui_file *file, const char *buf,
                           ^~~~~~
                           class
./ui-file.h:98:39: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern void ui_file_write_async_safe (struct ui_file *file, const char *buf,
                                      ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./ui-file.h:98:39: note: did you mean class here?
extern void ui_file_write_async_safe (struct ui_file *file, const char *buf,
                                      ^~~~~~
                                      class
./ui-file.h:101:27: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern long ui_file_read (struct ui_file *file, char *buf, long length_buf);
                          ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./ui-file.h:101:27: note: did you mean class here?
extern long ui_file_read (struct ui_file *file, char *buf, long length_buf);
                          ^~~~~~
                          class
In file included from tui/tui-command.c:22:
./defs.h:327:8: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
                                   struct ui_file *, int,
                                   ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./defs.h:327:8: note: did you mean class here?
                                   struct ui_file *, int,
                                   ^~~~~~
                                   class
./defs.h:339:57: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern void print_address (struct gdbarch *, CORE_ADDR, struct ui_file *);
                                                        ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./defs.h:339:57: note: did you mean class here?
extern void print_address (struct gdbarch *, CORE_ADDR, struct ui_file *);
                                                        ^~~~~~
                                                        class
In file included from tui/tui-command.c:22:
In file included from ./defs.h:631:
In file included from ./gdbarch.h:38:
In file included from ./frame.h:72:
In file included from ./language.h:26:
In file included from ./symtab.h:25:
./gdbtypes.h:1938:14: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
                                    int, struct ui_file *);
                                         ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./gdbtypes.h:1938:14: note: did you mean class here?
                                    int, struct ui_file *);
                                         ^~~~~~
                                         class
In file included from tui/tui-command.c:22:
In file included from ./defs.h:631:
In file included from ./gdbarch.h:38:
In file included from ./frame.h:72:
In file included from ./language.h:26:
In file included from ./symtab.h:27:
./common/function-view.h:208:1: warning: 'function_view' defined as a class template here but previously declared as a struct template [-Wmismatched-tags]
class function_view<Res (Args...)>
^
./common/function-view.h:205:1: note: did you mean class here?
struct function_view;
^~~~~~
class
In file included from tui/tui-command.c:22:
In file included from ./defs.h:631:
In file included from ./gdbarch.h:38:
In file included from ./frame.h:72:
In file included from ./language.h:26:
./symtab.h:30:1: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
struct ui_file;
^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./symtab.h:30:1: note: did you mean class here?
struct ui_file;
^~~~~~
class
In file included from tui/tui-command.c:22:
In file included from ./defs.h:751:
In file included from ./utils.h:24:
In file included from ./exceptions.h:23:
./ui-out.h:81:1: warning: 'ui_out' defined as a class here but previously declared as a struct [-Wmismatched-tags]
class ui_out
^
./gdbarch.h:68:1: note: did you mean class here?
struct ui_out;
^~~~~~
class
./frame.h:80:1: note: did you mean class here?
struct ui_out;
^~~~~~
class
In file included from tui/tui-command.c:22:
In file included from ./defs.h:751:
In file included from ./utils.h:24:
In file included from ./exceptions.h:23:
./ui-out.h:200:21: warning: struct 'ui_out' was previously declared as a class [-Wmismatched-tags]
  ui_out_emit_type (struct ui_out *uiout, const char *id)
                    ^
./ui-out.h:81:7: note: previous use is here
class ui_out
      ^
./ui-out.h:200:21: note: did you mean class here?
  ui_out_emit_type (struct ui_out *uiout, const char *id)
                    ^~~~~~
                    class
./ui-out.h:217:3: warning: struct 'ui_out' was previously declared as a class [-Wmismatched-tags]
  struct ui_out *m_uiout;
  ^
./ui-out.h:81:7: note: previous use is here
class ui_out
      ^
./ui-out.h:217:3: note: did you mean class here?
  struct ui_out *m_uiout;
  ^~~~~~
  class
In file included from tui/tui-command.c:22:
In file included from ./defs.h:751:
In file included from ./utils.h:24:
./exceptions.h:67:1: warning: struct 'ui_out' was previously declared as a class [-Wmismatched-tags]
struct ui_out;
^
./ui-out.h:81:7: note: previous use is here
class ui_out
      ^
./exceptions.h:67:1: note: did you mean class here?
struct ui_out;
^~~~~~
class
In file included from tui/tui-command.c:24:
./tui/tui-data.h:42:3: error: unknown type name 'WINDOW'
  WINDOW *handle;           /* Window handle.  */
  ^
In file included from tui/tui-command.c:25:
./tui/tui-win.h:40:8: error: unknown type name 'chtype'; did you mean 'type'?
extern chtype tui_border_ulcorner;
       ^~~~~~
       type
./gdbtypes.h:731:8: note: 'type' declared here
struct type
       ^
In file included from tui/tui-command.c:25:
./tui/tui-win.h:41:8: error: unknown type name 'chtype'; did you mean 'type'?
extern chtype tui_border_urcorner;
       ^~~~~~
       type
./gdbtypes.h:731:8: note: 'type' declared here
struct type
       ^
In file included from tui/tui-command.c:25:
./tui/tui-win.h:42:8: error: unknown type name 'chtype'; did you mean 'type'?
extern chtype tui_border_lrcorner;
       ^~~~~~
       type
./gdbtypes.h:731:8: note: 'type' declared here
struct type
       ^
In file included from tui/tui-command.c:25:
./tui/tui-win.h:43:8: error: unknown type name 'chtype'; did you mean 'type'?
extern chtype tui_border_llcorner;
       ^~~~~~
       type
./gdbtypes.h:731:8: note: 'type' declared here
struct type
       ^
In file included from tui/tui-command.c:25:
./tui/tui-win.h:44:8: error: unknown type name 'chtype'; did you mean 'type'?
extern chtype tui_border_vline;
       ^~~~~~
       type
./gdbtypes.h:731:8: note: 'type' declared here
struct type
       ^
In file included from tui/tui-command.c:25:
./tui/tui-win.h:45:8: error: unknown type name 'chtype'; did you mean 'type'?
extern chtype tui_border_hline;
       ^~~~~~
       type
./gdbtypes.h:731:8: note: 'type' declared here
struct type
       ^
tui/tui-command.c:59:10: error: use of undeclared identifier 'KEY_NPAGE'
    case KEY_NPAGE:
         ^
tui/tui-command.c:62:10: error: use of undeclared identifier 'KEY_PPAGE'
    case KEY_PPAGE:
         ^
tui/tui-command.c:65:10: error: use of undeclared identifier 'KEY_DOWN'
    case KEY_DOWN:
         ^
tui/tui-command.c:66:10: error: use of undeclared identifier 'KEY_SF'
    case KEY_SF:
         ^
tui/tui-command.c:69:10: error: use of undeclared identifier 'KEY_UP'
    case KEY_UP:
         ^
tui/tui-command.c:70:10: error: use of undeclared identifier 'KEY_SR'
    case KEY_SR:
         ^
tui/tui-command.c:73:10: error: use of undeclared identifier 'KEY_RIGHT'
    case KEY_RIGHT:
         ^
tui/tui-command.c:76:10: error: use of undeclared identifier 'KEY_LEFT'
    case KEY_LEFT:
         ^
tui/tui-command.c:97:3: error: unknown type name 'WINDOW'
  WINDOW *w = TUI_CMD_WIN->generic.handle;
  ^
15 warnings and 16 errors generated.
Makefile:1950: recipe for target 'tui-command.o' failed
make[2]: *** [tui-command.o] Error 1
In file included from tui/tui-data.c:22:
In file included from ./defs.h:53:
./ui-file.h:93:28: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern int ui_file_isatty (struct ui_file *);
                           ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./ui-file.h:93:28: note: did you mean class here?
extern int ui_file_isatty (struct ui_file *);
                           ^~~~~~
                           class
./ui-file.h:95:28: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern void ui_file_write (struct ui_file *file, const char *buf,
                           ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./ui-file.h:95:28: note: did you mean class here?
extern void ui_file_write (struct ui_file *file, const char *buf,
                           ^~~~~~
                           class
./ui-file.h:98:39: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern void ui_file_write_async_safe (struct ui_file *file, const char *buf,
                                      ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./ui-file.h:98:39: note: did you mean class here?
extern void ui_file_write_async_safe (struct ui_file *file, const char *buf,
                                      ^~~~~~
                                      class
./ui-file.h:101:27: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern long ui_file_read (struct ui_file *file, char *buf, long length_buf);
                          ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./ui-file.h:101:27: note: did you mean class here?
extern long ui_file_read (struct ui_file *file, char *buf, long length_buf);
                          ^~~~~~
                          class
In file included from tui/tui-data.c:22:
./defs.h:327:8: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
                                   struct ui_file *, int,
                                   ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./defs.h:327:8: note: did you mean class here?
                                   struct ui_file *, int,
                                   ^~~~~~
                                   class
./defs.h:339:57: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern void print_address (struct gdbarch *, CORE_ADDR, struct ui_file *);
                                                        ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./defs.h:339:57: note: did you mean class here?
extern void print_address (struct gdbarch *, CORE_ADDR, struct ui_file *);
                                                        ^~~~~~
                                                        class
In file included from tui/tui-disasm.c:22:
In file included from ./defs.h:53:
./ui-file.h:93:28: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern int ui_file_isatty (struct ui_file *);
                           ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./ui-file.h:93:28: note: did you mean class here?
extern int ui_file_isatty (struct ui_file *);
                           ^~~~~~
                           class
./ui-file.h:95:28: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern void ui_file_write (struct ui_file *file, const char *buf,
                           ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./ui-file.h:95:28: note: did you mean class here?
extern void ui_file_write (struct ui_file *file, const char *buf,
                           ^~~~~~
                           class
./ui-file.h:98:39: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern void ui_file_write_async_safe (struct ui_file *file, const char *buf,
                                      ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./ui-file.h:98:39: note: did you mean class here?
extern void ui_file_write_async_safe (struct ui_file *file, const char *buf,
                                      ^~~~~~
                                      class
./ui-file.h:101:27: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern long ui_file_read (struct ui_file *file, char *buf, long length_buf);
                          ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./ui-file.h:101:27: note: did you mean class here?
extern long ui_file_read (struct ui_file *file, char *buf, long length_buf);
                          ^~~~~~
                          class
In file included from tui/tui-disasm.c:22:
./defs.h:327:8: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
                                   struct ui_file *, int,
                                   ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./defs.h:327:8: note: did you mean class here?
                                   struct ui_file *, int,
                                   ^~~~~~
                                   class
./defs.h:339:57: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
extern void print_address (struct gdbarch *, CORE_ADDR, struct ui_file *);
                                                        ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./defs.h:339:57: note: did you mean class here?
extern void print_address (struct gdbarch *, CORE_ADDR, struct ui_file *);
                                                        ^~~~~~
                                                        class
In file included from tui/tui-data.c:22:
In file included from ./defs.h:631:
In file included from ./gdbarch.h:38:
In file included from ./frame.h:72:
In file included from ./language.h:26:
In file included from ./symtab.h:25:
./gdbtypes.h:1938:14: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
                                    int, struct ui_file *);
                                         ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./gdbtypes.h:1938:14: note: did you mean class here?
                                    int, struct ui_file *);
                                         ^~~~~~
                                         class
In file included from tui/tui-data.c:22:
In file included from ./defs.h:631:
In file included from ./gdbarch.h:38:
In file included from ./frame.h:72:
In file included from ./language.h:26:
In file included from ./symtab.h:27:
./common/function-view.h:208:1: warning: 'function_view' defined as a class template here but previously declared as a struct template [-Wmismatched-tags]
class function_view<Res (Args...)>
^
./common/function-view.h:205:1: note: did you mean class here?
struct function_view;
^~~~~~
class
In file included from tui/tui-data.c:22:
In file included from ./defs.h:631:
In file included from ./gdbarch.h:38:
In file included from ./frame.h:72:
In file included from ./language.h:26:
./symtab.h:30:1: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
struct ui_file;
^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./symtab.h:30:1: note: did you mean class here?
struct ui_file;
^~~~~~
class
In file included from tui/tui-disasm.c:22:
In file included from ./defs.h:631:
In file included from ./gdbarch.h:38:
In file included from ./frame.h:72:
In file included from ./language.h:26:
In file included from ./symtab.h:25:
./gdbtypes.h:1938:14: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
                                    int, struct ui_file *);
                                         ^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./gdbtypes.h:1938:14: note: did you mean class here?
                                    int, struct ui_file *);
                                         ^~~~~~
                                         class
In file included from tui/tui-disasm.c:22:
In file included from ./defs.h:631:
In file included from ./gdbarch.h:38:
In file included from ./frame.h:72:
In file included from ./language.h:26:
In file included from ./symtab.h:27:
./common/function-view.h:208:1: warning: 'function_view' defined as a class template here but previously declared as a struct template [-Wmismatched-tags]
class function_view<Res (Args...)>
^
./common/function-view.h:205:1: note: did you mean class here?
struct function_view;
^~~~~~
class
In file included from tui/tui-disasm.c:22:
In file included from ./defs.h:631:
In file included from ./gdbarch.h:38:
In file included from ./frame.h:72:
In file included from ./language.h:26:
./symtab.h:30:1: warning: struct 'ui_file' was previously declared as a class [-Wmismatched-tags]
struct ui_file;
^
./ui-file.h:26:7: note: previous use is here
class ui_file
      ^
./symtab.h:30:1: note: did you mean class here?
struct ui_file;
^~~~~~
class
In file included from tui/tui-data.c:22:
In file included from ./defs.h:751:
In file included from ./utils.h:24:
In file included from ./exceptions.h:23:
./ui-out.h:81:1: warning: 'ui_out' defined as a class here but previously declared as a struct [-Wmismatched-tags]
class ui_out
^
./gdbarch.h:68:1: note: did you mean class here?
struct ui_out;
^~~~~~
class
./frame.h:80:1: note: did you mean class here?
struct ui_out;
^~~~~~
class
In file included from tui/tui-data.c:22:
In file included from ./defs.h:751:
In file included from ./utils.h:24:
In file included from ./exceptions.h:23:
./ui-out.h:200:21: warning: struct 'ui_out' was previously declared as a class [-Wmismatched-tags]
  ui_out_emit_type (struct ui_out *uiout, const char *id)
                    ^
./ui-out.h:81:7: note: previous use is here
class ui_out
      ^
./ui-out.h:200:21: note: did you mean class here?
  ui_out_emit_type (struct ui_out *uiout, const char *id)
                    ^~~~~~
                    class
./ui-out.h:217:3: warning: struct 'ui_out' was previously declared as a class [-Wmismatched-tags]
  struct ui_out *m_uiout;
  ^
./ui-out.h:81:7: note: previous use is here
class ui_out
      ^
./ui-out.h:217:3: note: did you mean class here?
  struct ui_out *m_uiout;
  ^~~~~~
  class
In file included from tui/tui-data.c:22:
In file included from ./defs.h:751:
In file included from ./utils.h:24:
./exceptions.h:67:1: warning: struct 'ui_out' was previously declared as a class [-Wmismatched-tags]
struct ui_out;
^
./ui-out.h:81:7: note: previous use is here
class ui_out
      ^
./exceptions.h:67:1: note: did you mean class here?
struct ui_out;
^~~~~~
class
In file included from tui/tui-data.c:25:
./tui/tui-data.h:42:3: error: unknown type name 'WINDOW'
  WINDOW *handle;           /* Window handle.  */
  ^
In file included from tui/tui-disasm.c:22:
In file included from ./defs.h:751:
In file included from ./utils.h:24:
In file included from ./exceptions.h:23:
./ui-out.h:81:1: warning: 'ui_out' defined as a class here but previously declared as a struct [-Wmismatched-tags]
class ui_out
^
./gdbarch.h:68:1: note: did you mean class here?
struct ui_out;
^~~~~~
class
./frame.h:80:1: note: did you mean class here?
struct ui_out;
^~~~~~
class
In file included from tui/tui-data.c:26:
./tui/tui-wingeneral.h:39:29: error: unknown type name 'WINDOW'
extern void tui_delete_win (WINDOW *window);
                            ^
In file included from tui/tui-disasm.c:22:
In file included from ./defs.h:751:
In file included from ./utils.h:24:
In file included from ./exceptions.h:23:
./ui-out.h:200:21: warning: struct 'ui_out' was previously declared as a class [-Wmismatched-tags]
  ui_out_emit_type (struct ui_out *uiout, const char *id)
                    ^
./ui-out.h:81:7: note: previous use is here
class ui_out
      ^
./ui-out.h:200:21: note: did you mean class here?
  ui_out_emit_type (struct ui_out *uiout, const char *id)
                    ^~~~~~
                    class
./ui-out.h:217:3: warning: struct 'ui_out' was previously declared as a class [-Wmismatched-tags]
  struct ui_out *m_uiout;
  ^
./ui-out.h:81:7: note: previous use is here
class ui_out
      ^
./ui-out.h:217:3: note: did you mean class here?
  struct ui_out *m_uiout;
  ^~~~~~
  class
In file included from tui/tui-disasm.c:22:
In file included from ./defs.h:751:
In file included from ./utils.h:24:
./exceptions.h:67:1: warning: struct 'ui_out' was previously declared as a class [-Wmismatched-tags]
struct ui_out;
^
./ui-out.h:81:7: note: previous use is here
class ui_out
      ^
./exceptions.h:67:1: note: did you mean class here?
struct ui_out;
^~~~~~
class
tui/tui-data.c:685:36: error: use of undeclared identifier 'WINDOW'
  if (win_info->generic.handle != (WINDOW *) NULL)
                                   ^
tui/tui-data.c:685:44: error: expected expression
  if (win_info->generic.handle != (WINDOW *) NULL)
                                           ^
tui/tui-data.c:738:36: error: use of undeclared identifier 'WINDOW'
  if (win_info->generic.handle != (WINDOW *) NULL)
                                   ^
tui/tui-data.c:738:44: error: expected expression
  if (win_info->generic.handle != (WINDOW *) NULL)
                                           ^
15 warnings and 6 errors generated.
Makefile:1950: recipe for target 'tui-data.o' failed
make[2]: *** [tui-data.o] Error 1
In file included from tui/tui-disasm.c:31:
./tui/tui-data.h:42:3: error: unknown type name 'WINDOW'
  WINDOW *handle;           /* Window handle.  */
  ^
In file included from tui/tui-disasm.c:32:
./tui/tui-win.h:40:8: error: unknown type name 'chtype'
extern chtype tui_border_ulcorner;
       ^
./tui/tui-win.h:41:8: error: unknown type name 'chtype'
extern chtype tui_border_urcorner;
       ^
./tui/tui-win.h:42:8: error: unknown type name 'chtype'
extern chtype tui_border_lrcorner;
       ^
./tui/tui-win.h:43:8: error: unknown type name 'chtype'
extern chtype tui_border_llcorner;
       ^
./tui/tui-win.h:44:8: error: unknown type name 'chtype'
extern chtype tui_border_vline;
       ^
./tui/tui-win.h:45:8: error: unknown type name 'chtype'
extern chtype tui_border_hline;
       ^
15 warnings and 7 errors generated.
Makefile:1950: recipe for target 'tui-disasm.o' failed
make[2]: *** [tui-disasm.o] Error 1
make[2]: Leaving directory '/home/builder/.termux-build/gdb/src/gdb'
Makefile:9126: recipe for target 'all-gdb' failed
make[1]: *** [all-gdb] Error 2
make[1]: Leaving directory '/home/builder/.termux-build/gdb/src'
Makefile:849: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by fornwall** [comment]
@stephengroat `WINDOW` is provided by the base ncurses package, so you don't need the additional `ncurses-ui-libs`.

I've added ncurses to `TERMUX_PKG_DEPENDS`, so I think this should now build with the #1169 setup - can you check?

In practice gdb already depends on gdb indirectly through readline, but adding ncurses as a dependency causes the build setup to install the headers, just as you have done for other packages. Can you verify that it works building gdb now?

**Comment by stephengroat** [comment]
looks like fix in baf5799 did it. thanks again and for the info on `ncurses`!

**Pull request closed without merging**
