### PR TITLE
new package: zola

### PR DESCRIPTION
**Pull request by valium007**
A fast static site generator in a single binary with everything built-in.
https://www.getzola.org/

### CODE REVIEW

**Comment by valium007** [comment]
Hello, i hope the devs merge it cause its been a long time.

**Comment by TomJo2000** [comment]
This is the first time I have seen this PR.
Sorry for the delay.

Let me do a quick review.

**Review by TomJo2000 — CHANGES_REQUESTED** [review]
Let me just grab the Package Request template as a reference really quick.

<h1><em></em></h1> 

### Why is it worth to add this package?

Zola is a static site generator written in Rust

### Home page URL

https://www.getzola.org/

### Source code URL

https://github.com/getzola/zola

### Packaging policy acknowledgement

- [x] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [ ] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

- Not available through a language package manager
is gonna have to be a no since it builds without any patches.
But there would still be value in providing a package by including shell completions with it.

- Not duplicating the functionality of existing packages
Is also gonna have to be a no as we already package `hugo`,
also not a dealbreaker though as the feature sets seems to differ between the two.

---

I'm happy to merge the package,
but would like to request that we include the Shell completions.
See `just` for an example of how to generate the completions.
https://github.com/termux/termux-packages/blob/bb43cdd30af640522dac005582fb76506eddd002/packages/just/build.sh#L11-L22
<sub>Since zola doesn't have a Man page lines 12 and 17 from the example don't apply to it.</sub>
<sub>I am also unsure if it supports all 4 of the shells supported by `just` for completions
</sub>

**Comment by TomJo2000** [comment]
Oh my bad, it looks like `zola` uses `zola completions`[^1] to generate the completions.
[^1]:https://gitlab.archlinux.org/archlinux/packaging/packages/zola/-/blob/main/PKGBUILD?ref_type=heads

**Comment by TomJo2000** [comment]
I added the completions and fixed up the commit message.
Just waiting on the CI to finish and then it's good to merge.

**Review by TomJo2000 — APPROVED** [review]

**Comment by TomJo2000** [comment]
Thank you for your contribution.

**Pull request merged**
