### PR TITLE
[Merge order 050] Update package graphviz

### PR DESCRIPTION
**Pull request by vhqtvn**
Update to make graphviz buildable again.

### CODE REVIEW

**Comment by xeffyr** [comment]
@vhqtvn If you want to contribute and submit a set of updates to some packages, please do that **in ONE pull request**. That's would be easier to review and won't require 50+ parallel Github Actions tasks for building PR.

Also, "commit" is not a valid description for commits and I won't rewrite description for you.

https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#fixing-issues:
> Contributors should take full responsibility about submitted changes. Pull requests containing incomplete work or disruptive changes will NOT be merged.

**Comment by vhqtvn** [comment]
Nope i has to recompile termux using a different prefix so i has to build all packages from scratch, these are the changes that i need to made to make these packages compiles.

**Comment by vhqtvn** [comment]
> @vhqtvn If you want to contribute and submit a set of updates to some packages, please do that **in ONE pull request**. That's would be easier to review and won't require 50+ parallel Github Actions tasks for building PR.
> 
> Also, "commit" is not a valid description for commits and I won't rewrite description for you.
> 
> https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#fixing-issues:
> 
> > Contributors should take full responsibility about submitted changes. Pull requests containing incomplete work or disruptive changes will NOT be merged.

Ok i thought a large request will be ignored so just split them out so you can look each small changes, i'll prepare the combined one soon.

**Comment by Grimler91** [comment]
> these are the changes that i need to made to make these packages compiles

Example checks: I just built graphviz without TERMUX_PKG_BUILD_IN_SRC, and just downloaded [libpcap's .tar.xz archive](https://github.com/termux/termux-packages/pull/6871/files#diff-a873e110ed5cbdb11836b819454686bd61d963cabf489ceb9c188a676d151fa3L6), so no idea why that did not work for you

**Comment by xeffyr** [comment]
> i'll prepare the combined one soon.

Ok and please add proper description for each of change because its unclear what you have tried to fix. I saw lots of additions of `autoreconf -vfi` which is not necessary for the most of packages.

**Comment by xeffyr** [comment]
Some of your changes are completely invalid and break things, for example this one: https://github.com/termux/termux-packages/pull/6891/files - you are setting a wrong checksum for the package.

**Comment by vhqtvn** [comment]
> > these are the changes that i need to made to make these packages compiles
> 
> Example checks: I just built graphviz without TERMUX_PKG_BUILD_IN_SRC, and just downloaded [libpcap's .tar.xz archive](https://github.com/termux/termux-packages/pull/6871/files#diff-a873e110ed5cbdb11836b819454686bd61d963cabf489ceb9c188a676d151fa3L6), so no idea why that did not work for you

Took too much changes i dont remember the actual reason, but there's only one cause for TERMUX_PKG_BUILD_IN_SRC that a new source file is generated, but it isnt in build directory (it's in src directory).



> > i'll prepare the combined one soon.
> 
> Ok and please add proper description for each of change because its unclear what you have tried to fix. I saw lots of additions of `autoreconf -vfi` which is not necessary for the most of packages.

That addition is when building the package which is too old results in error of missing ac tools 1.15 1.14 etc, so i need to add autoreconf.

> Some of your changes are completely invalid and break things, for example this one: https://github.com/termux/termux-packages/pull/6891/files - you are setting a wrong checksum for the package.
> 
> ```
> curl http://www.ibiblio.org/pub/Linux/apps/financial/spreadsheet/sc-7.16.tar.gz | sha256sum -
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  205k  100  205k    0     0   238k      0 --:--:-- --:--:-- --:--:--  238k
> 1997a00b6d82d189b65f6fd2a856a34992abc99e50d9ec463bbf1afb750d1765  -
> ```
> 
> - valid checksum.
> 
> You are inserting `0eb360a6f24099517f63a32a2de11cc9e7bee60287159347ce57770c32cf5ab4` instead.

Hmm yes, i updated these hash when the wrong hash error popped up, maybe it's my vpn that time. I'll double check changes that change hash and update again soon.

**Pull request closed without merging**
