### PR TITLE
libdart: fix update to 6.13.0

### PR DESCRIPTION
**Pull request by pvonmoradi**
https://github.com/termux/termux-packages/issues/14617

### CODE REVIEW

**Comment by pvonmoradi** [comment]
Apparently dart no longer supports 32-bit plaforms:
https://github.com/dartsim/dart/issues/1671#issuecomment-1200457339
> It's intended. DART used to support and be tested in 32-bit up to 6.8.5 (only on GCC), but not afterward. We could reconsider this if needed, but 32-bit is not currently supported. Would it be possible to disable the 32-bit build for DART in vcpkg?

Blacklisting `arm` and `i686`

**Comment by pvonmoradi** [comment]
@xtkoba 
Any ideas on this?
`ERROR: Package contains directory "$PREFIX/$PREFIX" (/data/data/com.termux/files/usr/data/data/com.termux/files/usr)`

**Comment by xtkoba** [comment]
> `ERROR: Package contains directory "$PREFIX/$PREFIX" (/data/data/com.termux/files/usr/data/data/com.termux/files/usr)`

Ah that may be unfriendly. But you can `find` that directory in `termux_step_post_make_install` to see what are in.

**Comment by xtkoba** [comment]
Hunk number 3 of `CMakeLists.txt.patch` contained the fix for `$PREFIX/$PREFIX`. Why did you delete that file entirely?

**Comment by pvonmoradi** [comment]
> Why did you delete that file entirely?

I had to create the patch again since the upstream introduced a switch to disable dartpy component.
The build problem was that the "patch" had a "diff" extention so it was not applied. I can't figure this out, should git diffs have the `patch` extension (not `diff`) so termux build sees them? Also I was generating the git diff based on the wrong branch of upstream

**Pull request merged**
