### PR TITLE
(WIP)Made Neovim build with luajit insted of lua5.3

### PR DESCRIPTION
**Pull request by shadmansaleh**
This PR is addressing #6212 .

### CODE REVIEW

**Comment by shadmansaleh** [comment]
Ok build works . 

Acording to logs
>Uploaded '3891200' bytes from '/home/runner/work/termux-packages/termux-packages/artifacts' to server
Associated artifact termux-packages (19299400) with run #7177

artifact was uploaded somewhere .Is it possible to download and install the deb/artifact from somewhere ?

**Comment by xeffyr** [comment]
Here are your deb files: https://github.com/termux/termux-packages/suites/1898754616/artifacts/37210750

**Comment by shadmansaleh** [comment]
>Here are your deb files: https://github.com/termux/termux-packages/suites/1898754616/artifacts/37210750

Thanks . I've tested the artifact but libluajit sigfaults it . I'm not sure why I'll try to figure it out later.

**Comment by shadmansaleh** [comment]
I have no idea why segfaults are occuring . I also curently donn't have free time . This PR can be closed . If I figure out why it's happening I'll create another one . Or this can stay open.

**Pull request closed without merging**
