### PR TITLE
fdupes: New package

### PR DESCRIPTION
**Pull request by phcoder**
fdupes allows to easily find and remove duplicates

### CODE REVIEW

**Comment by sdrausty** [comment]
This program does what it says it says it does. It sounds like a great addition to Termux. Thanks for packing it @phcoder Did you package fdupes on device in Termux?

**Comment by phcoder** [comment]
@sdrausty I compiled it on Debian machine, then moved .deb to a phone and tested it there

**Comment by fornwall** [comment]
Thanks! The built package is now available in the apt package repository.

**Comment by sdrausty** [comment]
Thank you. 👍

**Pull request merged**
