### PR TITLE
update packages

### PR DESCRIPTION
**Pull request by vishalbiswas**

### CODE REVIEW

**Comment by Auxilus** [comment]
What does the line `TERMUX_PKG_SHA256=a41854fa0ac35b9c309ad692aaee67c8d4495c3546f11cb4cdd0a124195d3f15`means?

**Comment by vishalbiswas** [comment]
its the sha256 sum of the file to be downloaded

**Comment by Auxilus** [comment]
K

**Comment by fornwall** [comment]
A nice solid round of updates, thanks! The updated packages are now built and available in the apt repository.

**Pull request merged**
