### PR TITLE
Add PKGBUILD for libtalloc

### PR DESCRIPTION
**Pull request by Maxython**

### CODE REVIEW

**Comment by xeffyr** [comment]
Branch data.tar.xz-structure doesn't accept PKGBUILDs.

**Comment by xeffyr** [comment]
For PKGBUILD variant I can make a separate branch, but only if you will provide a ready binary package repository and minimal set of packages (like in our bootstrap archives) with their build scripts.

**Comment by Maxython** [comment]
Ok, I agree (we discussed this in discord).  There is already a repository with several PKGBUILDs (one of them is this one), here is the [repo](https://github.com/Maxython/termux-packages-in-pacman-format).

**Comment by xeffyr** [comment]
If you want pacman packages branch to be included, please do at least bare minimum:
* Base packages (shell, coreutils, etc).
* Corresponding build scripts, including scripts for cross-compilation.
* Binary package repository. Just like our https://packages.termux.org.

**Comment by Maxython** [comment]
Ok, I understand you.  The request will be again when I make the minimum requirements.  And one more question, did you yourself make a repo for storing the collection or are there any services for this?

**Comment by xeffyr** [comment]
You can start with using GitHub Pages for binary repository hosting, but when it will be quite big, you will need a VPS or something like.

**Comment by Maxython** [comment]
Thank

**Pull request closed without merging**
