### PR TITLE
feat(syncthing): fix build, update to 1.19.2

### PR DESCRIPTION
**Pull request by MrAdityaAlok**
Signed-off-by: Aditya Alok <dev.aditya.alok@gmail.com>

### CODE REVIEW

**Comment by MrAdityaAlok** [comment]
@Grimler91 I had to delete vendor dir to build successfully, is that ok (I am not too much familiar with go build system).

**Comment by MrAdityaAlok** [comment]
@Grimler91 is there some problem in build system?

**Comment by Grimler91** [comment]
Yeah, should be fixed by @xtkoba in https://github.com/termux/termux-packages/commit/ae7f540379cc276c1999ea475c5c5cec0857f6f3, please rebase

**Comment by MrAdityaAlok** [comment]
> Yeah, should be fixed by @xtkoba in [ae7f540](https://github.com/termux/termux-packages/commit/ae7f540379cc276c1999ea475c5c5cec0857f6f3), please rebase

Done.

**Pull request closed without merging**
