### PR TITLE
ldc: Bump revision to rebuild

### LINKED ISSUE #8363: [Bug]: `ldc` build failure
### Problem description

Building `ldc` package fails with this error:
```
/usr/bin/ld.bfd: unrecognised emulation mode: aarch64linux
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu elf_l1om elf_k1om i386pep i386pe
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
[110/116] Generating obj/ldc2.o
```

### What steps will reproduce the bug?

Submit a package build via GitHub Actions. Also should be reproducible locally via `./build-package.sh -I ldc`.

### System information

Termux official build system via GitHub Actions.

### PR DESCRIPTION
**Pull request by xtkoba**
Fixes #8363.

### CODE REVIEW

**Comment by sk0kanik** [comment]
I have tested and found runtime error on my arm (32bit) phone.
```
~ $ ldc2
Aborting from rt/sections_android.d(263) expected .tdata and .tbss sections to be adjacent (hint: try ld.bfd linker)Aborted
```

**Comment by sk0kanik** [comment]
Latest LDC [v1.28.0 supports LLVM 6.0 - 12.0](https://github.com/ldc-developers/ldc/releases/tag/v1.28.0) but Termux has LLVM 13.0.

**Comment by xtkoba** [comment]
So, we need to build cross-binutils, maybe?

**Comment by sk0kanik** [comment]
Seems like Github Action is stuck on 'Set up job'.

**Comment by sk0kanik** [comment]
It is working. Thanks.
```
~ $ cat test.d
import std.stdio;
import std.algorithm;
import std.range;
void main()
{
    int[] arr1 = [5, 2, 1, 10];
    int[] arr2 = [6, 8, 3];
    sort(chain(arr1, arr2));
    writefln("%s\n%s\n", arr1, arr2);
}
~ $ ldc2 --linker=ld test.d
~ $ ./test
[1, 2, 3, 5]
[6, 8, 10]
```

**Comment by Grimler91** [comment]
Thanks!

**Pull request merged**
