### PR TITLE
libmediainfo,mediainfo: Use Custom termux_pkg_auto_update

### LINKED ISSUE #19832: Auto update failing for mediainfo
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [mediainfo](https://github.com/termux/termux-packages/blob/88d2a0662b9d800e06dbbe763bec09280298dac6/packages/mediainfo) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating mediainfo [Current version: 24.04]
INFO: package being updated to 24.4.0.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   196    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

mediainfo: failed to calculate the new checksum
Already up to date.
ERROR: failed to update checksum.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-04-19 00:30:06 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/8746393611">8746393611</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by 2096779623**
Close #19832 .

### CODE REVIEW

**Comment by Biswa96** [comment]
Would not it be possible to check latest stable version from GitHub release tags?

**Comment by tqfx** [comment]
> Would not it be possible to check latest stable version from GitHub release tags?

See https://github.com/MediaArea/MediaInfo/releases

**Comment by 2096779623** [comment]
> Would not it be possible to check latest stable version from GitHub release tags?

In fact, the update speed on the website is the fastest.

https://github.com/MediaArea/MediaArea-Website/commits/3abd7ccce42fac30138aae9b9065d789ec5c37b4/src/MediaInfoBundle/Lib/DownloadInfo/MediaInfoDownloadInfo.php

**Comment by TomJo2000** [comment]
It looks like we have a problem here.
https://github.com/termux/termux-packages/actions/runs/8771738903/job/24070391450#step:4:65

**Comment by TomJo2000** [comment]
I think we need to bump the package revision for it to not conflict.

**Comment by 2096779623** [comment]
> I think we need to bump the package revision for it to not conflict.

https://github.com/termux/termux-packages/commit/adf144f0c3c892fe8d3ea02f71022f8a238b6b2a
No, I just forgot to add `%ci:no-build` to commit message.

**Comment by truboxl** [comment]
rl and r1 #19876 #19875

**Comment by tqfx** [comment]
> > Would not it be possible to check latest stable version from GitHub release tags?
> 
> In fact, the update speed on the website is the fastest.
> 
> https://github.com/MediaArea/MediaArea-Website/commits/3abd7ccce42fac30138aae9b9065d789ec5c37b4/src/MediaInfoBundle/Lib/DownloadInfo/MediaInfoDownloadInfo.php

See #20383 and #20385

**Comment by tqfx** [comment]
I think we should check the latest stable version from GitHub releases tag. See #20383 and #20385

**Pull request merged**
