### PR TITLE
toolchain: add API guard for `timezone_t`

### LINKED ISSUE #21113: [Bug]: Failed to build package 'coreutils'
### Problem description

Since the NDK was bumped to version 27, compiling `coreutils` gives this error

```
...
  CC       lib/libcoreutils_a-nstrftime.o
  CC       lib/libcoreutils_a-obstack.o
  CC       lib/libcoreutils_a-openat-die.o
  CC       lib/libcoreutils_a-openat-safer.o
In file included from /home/builder/.termux-build/coreutils/src/lib/nstrftime.c:19:
/home/builder/.termux-build/coreutils/src/lib/strftime.c:1725:17: error: call to undeclared function 'mktime_z'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1725 |             t = mktime_z (tz, &ltm);
      |                 ^
/home/builder/.termux-build/coreutils/src/lib/strftime.c:1725:17: note: did you mean 'mktime'?
/home/builder/.termux-build/_cache/android-r27-api-24-v0/bin/../sysroot/usr/include/time.h:159:8: note: 'mktime' declared here
  159 | time_t mktime(struct tm* _Nonnull __tm);
      |        ^
1 error generated.
make[2]: *** [Makefile:16274: lib/libcoreutils_a-nstrftime.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/builder/.termux-build/coreutils/build'
make[1]: *** [Makefile:22447: all-recursive] Error 1
make[1]: Leaving directory '/home/builder/.termux-build/coreutils/build'
make: *** [Makefile:8865: all] Error 2
Failed to build package 'coreutils' for arch 'aarch64'
[*] Building 'coreutils' exited with exit code 2
Error: Process completed with exit code 2.
```

### What steps will reproduce the bug?

`coreutils` should be in `PACKAGES` in `build-bootstraps.sh`:

```
./scripts/run-docker.sh ./clean.sh
./scripts/run-docker.sh ./scripts/build-bootstraps.sh --android10
```

### What is the expected behavior?

_No response_

### System information

```shell
N/A
```

### PR DESCRIPTION
**Pull request by licy183**
Closes #21113

### CODE REVIEW

**Comment by Grimler91** [comment]
I guess this issue is not specific to termux, i.e. should we report it to android/ndk team?

**Comment by gouravkhunger** [comment]
Looks like this PR does [fix the issue](https://github.com/jekyllex/ruby-android/actions/runs/10382604220/job/28745962448). Thank you!

**Comment by TomJo2000** [comment]
Heads up, it seems like this also effects `cpio` from what I can tell as part of the NDK 27 build testing I'm currently doing.

Here's the relavant part of the log file.
`~/.termux-build/_buildall-aarch64/cpio.out`
```styl
In file included from /home/builder/.termux-build/tar/src/gnu/fprintftime.c:19:
/home/builder/.termux-build/tar/src/gnu/nstrftime.c:1189:17: error: call to undeclared function 'mktime_z'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1189 |             t = mktime_z (tz, &ltm);
      |                 ^
/home/builder/.termux-build/tar/src/gnu/nstrftime.c:1189:17: note: did you mean 'mktime'?
/home/builder/.termux-build/_cache/android-r27-api-24-v0/bin/../sysroot/usr/include/time.h:159:8: note: 'mktime' declared here
  159 | time_t mktime(struct tm* _Nonnull __tm);
      |        ^
  CC       libgnu_a-group-member.o
1 error generated.
  CC       libgnu_a-hard-locale.o
make[4]: *** [Makefile:4628: libgnu_a-fprintftime.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/builder/.termux-build/tar/build/gnu'
make[3]: *** [Makefile:7657: all-recursive] Error 1
make[3]: Leaving directory '/home/builder/.termux-build/tar/build/gnu'
make[2]: *** [Makefile:2975: all] Error 2
make[2]: Leaving directory '/home/builder/.termux-build/tar/build/gnu'
make[1]: *** [Makefile:1882: all-recursive] Error 1
make[1]: Leaving directory '/home/builder/.termux-build/tar/build'
make: *** [Makefile:1822: all] Error 2
```

**Comment by fornwall** [comment]
I think this PR makes sense and should be ready to merge.

Then we can propose it at https://github.com/android/ndk/issues (do you want to do that @licy183)?

**Comment by TomJo2000** [comment]
This seems to be effecting everything that depends on `coreutils`, I'll spare you the list.
- (You can check #21130 for that)

It would be good to get this resolved soon.
Since by my current count this issue accounts for 36 out of the 148 build problems I've found so far as part of the rebuilds.

**Comment by truboxl** [comment]
I am thinking of adding mktime_z and friends instead...

**Comment by licy183** [comment]
Emmm.... These symbols exist in too many packages (almost every package depending on gnulib) and `libandroid-timezone` (possible name) will have to be linked against explicitly in all of them.

Anyway, adding them makes sense if some package must use them.

**Comment by fornwall** [comment]
I think this is fine to merge, as it basically adds back the behaviour from earlier NDK versions, where `timezone_t` was not detected - a potential `libandroid-timezone` addition (if necessary) can come later as a separate PR.

**Review by TomJo2000 — APPROVED** [review]

**Comment by licy183** [comment]
Yeah. I'll merge this now. `libandroid-timezone` can be added in a seperate PR.

**Pull request merged**
