### PR TITLE
newpkg(main/abootimg)

### PR DESCRIPTION
**Pull request by Grimler91**
Requested in termux/termux-packages#12567.

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
Note that this hasn't been updated since 2012 and will not work on all android versions/devices like recently ones.

**Comment by Grimler91** [comment]
> Note that this hasn't been updated since 2012 and will not work on all android versions/devices like recently ones.

Yeah, might want to add osm0sis's mkbootimg as well, it is better maintained

**Comment by agnostic-apollo** [comment]
Yeah, that would be better, used that recently for my A11 device.

**Comment by agnostic-apollo** [comment]
Yeah, we do, @Grimler91 seems to be having persistent memory corruption issues ;)

I built mine on laptop for my A11 device.

https://github.com/termux/termux-packages/blob/master/packages/mkbootimg/build.sh

**Comment by Grimler91** [comment]
> We already have `mkbootimg`, isn't it?

Cool, apparently I added it

> Yeah, we do, @Grimler91 seems to be having persistent memory corruption issues ;)

Definitely, I blame stress

**Comment by agnostic-apollo** [comment]
>Definitely, I blame stress

Well, that sucks. Please feel free to file an expense for a day at the spa or something ;)

**Comment by Grimler91** [comment]
Haha, spas are kinda overpriced here, not worth it :)

My current employment ends in December though, that should give me the possibility to relax for a bit

**Pull request merged**
