### PR TITLE
Perl : Enable Multiplicity

### PR DESCRIPTION
**Pull request by mjuned47**

### CODE REVIEW

**Review by xtkoba — COMMENTED** [review]
IIRC, `-Dusethreads` implies `-Duseithreads` and `-Dusemultiplicity`. This PR effectively changes nothing.

**Comment by mjuned47** [comment]
> IIRC, `-Dusethreads` implies `-Duseithreads` and `-Dusemultiplicity`. This PR effectively changes nothing.

Compiling perl module(mod_perl) reporting that perl is not build with Multiplicity support , after this change ,it continues building and doesn't report such thing

**Comment by xtkoba** [comment]
Curious. How can we reproduce it?

**Comment by xtkoba** [comment]
Ah, my assumption may not apply when cross-building.

OK, then please cleanup the PR. Use tabs for indentation. Put one option per line. Bump revision.

**Comment by mjuned47** [comment]
> Curious. How can we reproduce it?

Install perl 
type cpan (to get in cpan shell)
Type install SHAY/mod_perl-2.0.12.tar.gz

**Review by xtkoba — CHANGES_REQUESTED** [review]
Increase the `TERMUX_PKG_REVISION` by one, that is, in this case put the line `TERMUX_PKG_REVISION=1` right under the `TERMUX_PKG_VERSION` definition.

Also rebuild the packages listed in `build.sh`:

```
# Packages which should be rebuilt after version change:
# - exiftool
# - irssi
# - libapt-pkg-perl
# - libregexp-assemble-perl
# - psutils
# - subversion
```

by increasing the `TERMUX_PKG_REVISION` value by one for each of these package.

Finally squash the commits appropriately.

**Comment by mjuned47** [comment]
@xtkoba will you do that please ? Because I'm mobile user and not much familiar with git commands

**Comment by xtkoba** [comment]
Huh, OK then I will do that in another PR. Please close this.

**Pull request closed without merging**
