### PR TITLE
Test System with Efficiency Increase

### PR DESCRIPTION
**Pull request by Wetitpig**
For the changes, please see the commit title. This includes the addition of zlib and rzip.
And here is the test result: https://gitlab.com/Wetitpig/termux-packages/pipelines/7819157

### CODE REVIEW

**Comment by Wetitpig** [comment]
New test pipeline: https://gitlab.com/Wetitpig/termux-packages/pipelines/7822169

**Comment by Wetitpig** [comment]
Some dependencies have been removed. An option has been added to specify whether building the artifacts or not.

**Comment by Wetitpig** [comment]
New pipeline: https://gitlab.com/Wetitpig/termux-packages/pipelines/7825153

**Comment by Wetitpig** [comment]
New pipeline: https://gitlab.com/Wetitpig/termux-packages/pipelines/7843423

**Comment by Wetitpig** [comment]
With the Gitlab system, everyone could test packages with Gitlab CI.

**Comment by vishalbiswas** [comment]
@Wetitpig can you do a travis-ci to build updated packages? It would be really helpful

**Comment by Wetitpig** [comment]
Ok I start a new branch to test later.

**Comment by Wetitpig** [comment]
How to set up Travis CI? There is only ubunti 14.04

**Comment by Wetitpig** [comment]
By the way, building all packages currently taked around 8 hours to 12 hours. Can the speed of build-package.sh be increased by increasing number of parallel builds in GNU make?

**Comment by vishalbiswas** [comment]
@Wetitpig it already uses 4 parallel processes. If you want to increase it, then set it in .termuxrc as `TERMUX_MAKE_PROCESSES=<value>`
As for ubuntu 14.04, I don't think it'll matter much

**Comment by Wetitpig** [comment]
So for Travis CI... How to set up?

**Comment by Wetitpig** [comment]
Using nproc rather than fixing the process limit can speed up the build. For me it's around 20%

Test carried out here: https://gitlab.com/Wetitpig/termux-packages/pipelines/7869820

**Comment by vishalbiswas** [comment]
@Wetitpig You can visit https://docs.travis-ci.com/ to learn how to setup travis builds. It uses yml format, which is very similar to gitlab-ci's.
Building all packages takes far too long and as such is highly inefficient when only a specific package is changed.
A custom step could be added to check for the paths changed.
```bash
for pkg in `git diff --name-only HEAD HEAD~1 -- packages | cut -d'/' -f2 | uniq`; do
  ./build-package.sh $pkg
done
```
This will build only the packages changed in that commit. This doesn't apply to disabled-packages

**Comment by Wetitpig** [comment]
New pipwline with commit functionality: https://gitlab.com/Wetitpig/termux-packages/pipelines/7876871

**Comment by Wetitpig** [comment]
It will build only the package changed when there is a change in `packages/`, or else it will build all.

**Comment by Wetitpig** [comment]
By the way, have yoi ever thought of moving the whole repo to gitlab?

**Comment by vishalbiswas** [comment]
I'm not the author. @fornwall is.
I'm just a contributor like you.

I would ditch the build-all function, because if a disabled package is updated then the whole repo will be built. Also, we don't need to upload the artifacts.
This travis build system should provide us with a good pre-merge verifications on pull requests.

**Comment by Wetitpig** [comment]
But just building libllvm takes at least 60 minutes, which is longer than the Travis limit.

**Comment by vishalbiswas** [comment]
Oh! Yes, we'll have to limit for only two arches then?
This wouldn't have been a problem if llvm and clang were truly separate packages.

**Comment by Wetitpig** [comment]
No. I mean building for 1 arch takes at least 60 minutes.

**Comment by vishalbiswas** [comment]
aren't all jobs executed simultaneously in a single container?

**Comment by Wetitpig** [comment]
We build it in 4 containers simultaneously. All 4 containers are run at the same time, with one for each arch.

**Comment by fornwall** [comment]
Nice work! @Wetitpig In general it would be nice to use separate PR:s for different changes, to more easily understand, give feedback and accept changes individually:

The different changes as I understand them now:

1. Setting up Gitlab CI: Cool! I've never used that myself so cannot give much feedback, but looks nice!

2. Minor change in `build-all.sh` output and output logging: Seems fine.

3. Using `nproc` as default for number of parallel make jobs instead of 4: Seems fine.

4. Removing `--silent` from patching - could you explain why you're doing this (in general we want to avoid too verbose builds)?

5. Adding `python3-setuptools` to `setup-ubuntu.sh`: It's already there a couple of lines down.

6. Adding `python-setuptools`, `python-pip`, `python-dev` and `build-essential` to `setup-ubuntu.sh`: Why, I don't see that it's needed by anything here?

7. Adding a `rzip` package: Two questions here, (1) is anyone actually using rzip? (2) It looks like you're replacing `#include "bzlib.h"` with an inlined copy of `bzlib.h`, which looks strange. After building `libbz2` that include file is available in `$TERMUX_PREFIX/include/` and should be available when building (perhaps patching the build to use `$CPPFLAGS` if necessary).

**Comment by Wetitpig** [comment]
Reply to 4: we want to know why patching is unsuccessful in case it fails.

Reply to 8: this is a more stable mirror.

Reply to 7: the configure file of this package is quite primitive. It cannot handle special options.

New commit: using aria2c enables us to download with multiple connections, using the whole bandwidth available.

**Comment by Wetitpig** [comment]
Speed up ndk test: https://gitlab.com/Wetitpig/termux-packages/pipelines/7901947

**Comment by Wetitpig** [comment]
The version number of ne seemed to be wrong.

Also, now the build is triggered by Travis CI and carried out by Gitlab CI. Statuses will be sent thriugh Github API. This should be more convenient.

**Comment by Wetitpig** [comment]
Anyone have any ideas?

**Comment by Wetitpig** [comment]
Now there is a Gitlab CI status returning.

**Comment by Wetitpig** [comment]
Still the same commits but different content.

**Comment by Wetitpig** [comment]
This pull request is closed, to be replaced by the following:

#994 #995 #996 #997 #998 #999

**Pull request closed without merging**
