### PR TITLE
Add package: maven

### PR DESCRIPTION
**Pull request by ghost**
Maven is a popular build and library manipulation system for Java softwares after Gradle. It follows Project Object Model (POM) structure to build softwares and artifacts. Maven is developed and managed by the Apache Organisation.

Maven depends on a library called [jansi](https://github.com/fusesource/jansi), which has an JNI native library ```libjansi.so```. This library provides some extra features to Maven, like giving formated (bold, italic, underlined) colored output using ANSI escape characters if its running directly from the terminal, otherwise if the output is redirected, it gives only stripped raw text output. It also helps Maven getting the terminal's height and width, clearing terminal etc. in the native way.

jansi has this native library in it's JAR file for different Linux and macOS architectures, and in a directory (containing the DLL library) for the Windows architecture. jansi doesn't support any Android architectures like armv7l, aarch64, i686 or x86_64. So when Maven starts in Termux (i.e. Android), jansi thinks it to be Linux (because it uses ```System.getProperty("os.name")``` to determine OS, which returns "Linux" in openjdk-17 package in Termux), so tries to load the built-in native library for the equivalent Linux architecture (uses ```System.getProperty("os.arch")``` and ```uname -m``` to determine architecture, which overall evaluates to armv7 for my device) and fails, showing a message that the library was incompatible. However, this doesn't stop Maven from working. Maven works as regular, just without the colored output and bold, italic, underline formatting.

By the way, I have patched and built the library for my Android architecture (armv7l). But I can't provide it to other Termux users because of "Trust Issues".

### CODE REVIEW

**Comment by masterjavaofficial** [comment]
> openjdk-17 for ubuntu/the docker image? Add it to [setup-ubuntu.sh](https://github.com/termux/termux-packages/blob/master/scripts/setup-ubuntu.sh)

OpenJDK-17 not for docker image. It needs to be on users phone before building libjansi.

**Comment by masterjavaofficial** [comment]
> @masterjavaofficial how well does the package work for you? I tried compiling a simple [hello-world project](https://github.com/pdurbin/maven-hello-world), but it fails with:

@Grimler91 the repo you cloned is very old (about 6-7 years). Many plugins are deprecated / removed, many updated, and many new came. You should rely on latest versions of the plugins which builds agains latest Java versions (in this case, its openjdk-17). That older compiler plugin can't compile for openjdk-17. You've to configure the hello world project.

Details: https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html

Screenshot_2021-10-19-18-53-29-568_com android chrome

**Comment by masterjavaofficial** [comment]
@Grimler91 won't this package will be added? ☹️

**Comment by xeffyr** [comment]
@masterjavaofficial maybe wait? We're finally not 24x7 there...

**Pull request merged**
