### PR TITLE
[WIP] ffmpeg: update to 5.1

### PR DESCRIPTION
**Pull request by tomty89**
We can wait until some distro has introduced the update so that we can have some idea on whether it causes any breakage, but it shouldn't hurt to start the work now.

### CODE REVIEW

**Comment by tomty89** [comment]
Note: the vulkan test is pointless as libvulkan.so is `dlopen()`ed instead of linked against.

**Comment by tomty89** [comment]
@Grimler91 mpv seems to build fine at least. Do you remember which exact ffmpeg/libavutil-linking packages was problematic? Or have I missed something?

**Comment by Grimler91** [comment]
Re-running build for failed packages and saving logs now. Might have been mpd, or one of its dependencies that failed

**Comment by Grimler91** [comment]
mpd fails with:

```
[600/602] Linking target mpd
FAILED: mpd 
aarch64-linux-android-clang++  -o mpd mpd.p/meson-generated_.._GitVersion.cxx.o mpd.p/src_Main.cxx.o mpd.p/src_protocol_ArgParser.cxx.o mpd.p/src_command_CommandError.cxx.o mpd.p/src_command_PositionArg.cxx.o mpd.p/src_command_AllCommands.cxx.o mpd.p/src_command_QueueCommands.cxx.o mpd.p/src_command_TagCommands.cxx.o mpd.p/src_command_PlayerCommands.cxx.o mpd.p/src_command_PlaylistCommands.cxx.o mpd.p/src_command_FileCommands.cxx.o mpd.p/src_command_OutputCommands.cxx.o mpd.p/src_command_MessageCommands.cxx.o mpd.p/src_command_ClientCommands.cxx.o mpd.p/src_command_PartitionCommands.cxx.o mpd.p/src_command_OtherCommands.cxx.o mpd.p/src_command_CommandListBuilder.cxx.o mpd.p/src_Idle.cxx.o mpd.p/src_IdleFlags.cxx.o mpd.p/src_decoder_Thread.cxx.o mpd.p/src_decoder_Control.cxx.o mpd.p/src_decoder_Bridge.cxx.o mpd.p/src_decoder_DecoderPrint.cxx.o mpd.p/src_client_Listener.cxx.o mpd.p/src_client_Client.cxx.o mpd.p/src_client_Config.cxx.o mpd.p/src_client_Domain.cxx.o mpd.p/src_client_Event.cxx.o mpd.p/src_client_Expire.cxx.o mpd.p/src_client_Idle.cxx.o mpd.p/src_client_List.cxx.o mpd.p/src_client_New.cxx.o mpd.p/src_client_Process.cxx.o mpd.p/src_client_Read.cxx.o mpd.p/src_client_Write.cxx.o mpd.p/src_client_Message.cxx.o mpd.p/src_client_Subscribe.cxx.o mpd.p/src_client_File.cxx.o mpd.p/src_client_Response.cxx.o mpd.p/src_client_ThreadBackgroundCommand.cxx.o mpd.p/src_Listen.cxx.o mpd.p/src_LogInit.cxx.o mpd.p/src_ls.cxx.o mpd.p/src_Instance.cxx.o mpd.p/src_MusicBuffer.cxx.o mpd.p/src_MusicPipe.cxx.o mpd.p/src_MusicChunk.cxx.o mpd.p/src_MusicChunkPtr.cxx.o mpd.p/src_Mapper.cxx.o mpd.p/src_Partition.cxx.o mpd.p/src_Permission.cxx.o mpd.p/src_player_CrossFade.cxx.o mpd.p/src_player_Thread.cxx.o mpd.p/src_player_Control.cxx.o mpd.p/src_PlaylistError.cxx.o mpd.p/src_PlaylistPrint.cxx.o mpd.p/src_PlaylistSave.cxx.o mpd.p/src_playlist_PlaylistStream.cxx.o mpd.p/src_playlist_PlaylistMapper.cxx.o mpd.p/src_playlist_PlaylistAny.cxx.o mpd.p/src_playlist_PlaylistSong.cxx.o mpd.p/src_playlist_PlaylistQueue.cxx.o mpd.p/src_playlist_Print.cxx.o mpd.p/src_db_PlaylistVector.cxx.o mpd.p/src_queue_Queue.cxx.o mpd.p/src_queue_QueuePrint.cxx.o mpd.p/src_queue_QueueSave.cxx.o mpd.p/src_queue_Playlist.cxx.o mpd.p/src_queue_PlaylistControl.cxx.o mpd.p/src_queue_PlaylistEdit.cxx.o mpd.p/src_queue_PlaylistTag.cxx.o mpd.p/src_queue_PlaylistState.cxx.o mpd.p/src_ReplayGainGlobal.cxx.o mpd.p/src_LocateUri.cxx.o mpd.p/src_SongUpdate.cxx.o mpd.p/src_SongLoader.cxx.o mpd.p/src_SongPrint.cxx.o mpd.p/src_SongSave.cxx.o mpd.p/src_StateFile.cxx.o mpd.p/src_StateFileConfig.cxx.o mpd.p/src_Stats.cxx.o mpd.p/src_TagPrint.cxx.o mpd.p/src_TagSave.cxx.o mpd.p/src_TagFile.cxx.o mpd.p/src_TagStream.cxx.o mpd.p/src_TagAny.cxx.o mpd.p/src_TimePrint.cxx.o mpd.p/src_mixer_Volume.cxx.o mpd.p/src_PlaylistFile.cxx.o mpd.p/src_CommandLine.cxx.o mpd.p/src_unix_SignalHandlers.cxx.o mpd.p/src_unix_Daemon.cxx.o mpd.p/src_queue_PlaylistUpdate.cxx.o mpd.p/src_command_StorageCommands.cxx.o mpd.p/src_command_DatabaseCommands.cxx.o mpd.p/src_RemoteTagCache.cxx.o mpd.p/src_command_StickerCommands.cxx.o mpd.p/src_sticker_Database.cxx.o mpd.p/src_sticker_Print.cxx.o mpd.p/src_sticker_SongSticker.cxx.o mpd.p/src_command_NeighborCommands.cxx.o mpd.p/src_TagArchive.cxx.o mpd.p/src_db_update_Archive.cxx.o -L/data/data/com.termux/files/usr/lib -Wl,--as-needed -Wl,--no-undefined -pie -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--start-group -lOpenSLES libbasic.a src/config/libfs.a liblog.a subprojects/fmt-8.1.1/libfmt.a src/fs/libfs.a src/lib/zlib/libzlib.a src/io/libio.a src/system/libsystem.a src/lib/icu/libicu.a src/util/libutil.a src/lib/dbus/libdbus.a src/event/libevent.a src/thread/libthread.a src/net/libnet.a src/neighbor/libneighbor_glue.a src/neighbor/plugins/libneighbor_plugins.a src/input/libinput_glue.a src/input/plugins/libinput_plugins.a src/lib/curl/libcurl.a src/lib/ffmpeg/libffmpeg.a src/lib/nfs/libnfs.a src/lib/crypto/libcrypto_md5.a src/input/libinput_api.a src/pcm/libpcm.a src/pcm/libpcm_basic.a src/tag/libtag.a src/time/libtime.a src/archive/libarchive_glue.a src/archive/plugins/libarchive_plugins.a src/archive/libarchive_api.a src/output/liboutput_glue.a src/filter/libfilter_glue.a src/filter/plugins/libfilter_plugins.a src/filter/libfilter_api.a src/mixer/plugins/libmixer_plugins.a src/lib/pulse/libpulse.a src/output/plugins/liboutput_plugins.a src/output/liboutput_api.a src/mixer/libmixer_glue.a src/decoder/libdecoder_glue.a src/decoder/plugins/libdecoder_plugins.a src/lib/xiph/libflac.a src/lib/xiph/libxiph.a src/lib/xiph/libvorbis.a src/lib/xiph/libogg.a src/lib/crypto/libcrypto_base64.a src/decoder/libdecoder_api.a src/encoder/libencoder_glue.a src/encoder/plugins/libencoder_plugins.a src/playlist/libplaylist_glue.a src/playlist/plugins/libplaylist_plugins.a src/lib/expat/libexpat.a src/playlist/libplaylist_api.a src/db/libdb_glue.a src/db/plugins/libdb_plugins.a src/lib/pcre/libpcre.a src/db/libdb_api.a src/storage/libstorage_api.a src/storage/libstorage_glue.a src/storage/plugins/libstorage_plugins.a src/song/libsong.a src/lib/sqlite/libsqlite.a /data/data/com.termux/files/usr/lib/libdbus-1.so /data/data/com.termux/files/usr/lib/libavformat.so /data/data/com.termux/files/usr/lib/libavcodec.so /data/data/com.termux/files/usr/lib/libavfilter.so /data/data/com.termux/files/usr/lib/libavutil.so /data/data/com.termux/files/usr/lib/libpcre2-8.so /data/data/com.termux/files/usr/lib/libsqlite3.so /data/data/com.termux/files/usr/lib/libz.so /data/data/com.termux/files/usr/lib/libicui18n.so /data/data/com.termux/files/usr/lib/libicuuc.so /data/data/com.termux/files/usr/lib/libicudata.so -pthread /data/data/com.termux/files/usr/lib/libcurl.so /data/data/com.termux/files/usr/lib/libnfs.so /data/data/com.termux/files/usr/lib/libsoxr.so /data/data/com.termux/files/usr/lib/libid3tag.so -lbz2 /data/data/com.termux/files/usr/lib/libpulse.so /data/data/com.termux/files/usr/lib/libao.so /data/data/com.termux/files/usr/lib/libopenal.so -lOpenSLES /data/data/com.termux/files/usr/lib/libFLAC.so -lgme -lmad /data/data/com.termux/files/usr/lib/libopus.so /data/data/com.termux/files/usr/lib/libsndfile.so /data/data/com.termux/files/usr/lib/libogg.so /data/data/com.termux/files/usr/lib/libvorbis.so /data/data/com.termux/files/usr/lib/libvorbisenc.so -lmp3lame /data/data/com.termux/files/usr/lib/libexpat.so /data/data/com.termux/files/usr/lib/libmpdclient.so -Wl,--end-group
ld: error: undefined symbol: av_free(void*)
>>> referenced by FfmpegIo.cxx:31 (../src/src/decoder/plugins/FfmpegIo.cxx:31)
>>>               libdecoder_plugins.a.p/FfmpegIo.cxx.o:(AvioStream::~AvioStream()) in archive src/decoder/plugins/libdecoder_plugins.a
>>> referenced by FfmpegIo.cxx:32 (../src/src/decoder/plugins/FfmpegIo.cxx:32)
>>>               libdecoder_plugins.a.p/FfmpegIo.cxx.o:(AvioStream::~AvioStream()) in archive src/decoder/plugins/libdecoder_plugins.a
>>> did you mean: extern "C" av_free
>>> defined in: /data/data/com.termux/files/usr/lib/libavutil.so

ld: error: undefined symbol: av_malloc(unsigned long)
>>> referenced by FfmpegIo.cxx:102 (../src/src/decoder/plugins/FfmpegIo.cxx:102)
>>>               libdecoder_plugins.a.p/FfmpegIo.cxx.o:(AvioStream::Open()) in archive src/decoder/plugins/libdecoder_plugins.a
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
[601/602] Generating doc/Manpage documentation with a custom command
WARNING: html_static_path entry '_static' does not exist
/home/builder/.termux-build/mpd/src/doc/plugins.rst:2: WARNING: Duplicate explicit target name: "more information".
/home/builder/.termux-build/mpd/src/doc/plugins.rst:2: WARNING: Duplicate explicit target name: "more information".
/home/builder/.termux-build/mpd/src/doc/user.rst:657: WARNING: Unexpected indentation.
/home/builder/.termux-build/mpd/src/doc/user.rst:660: WARNING: Unexpected indentation.
/home/builder/.termux-build/mpd/src/doc/mpd.1.rst: WARNING: document isn't included in any toctree
/home/builder/.termux-build/mpd/src/doc/mpd.conf.5.rst: WARNING: document isn't included in any toctree
[602/602] Generating doc/HTML documentation with a custom command
WARNING: html_static_path entry '_static' does not exist
/home/builder/.termux-build/mpd/src/doc/plugins.rst:2: WARNING: Duplicate explicit target name: "more information".
/home/builder/.termux-build/mpd/src/doc/plugins.rst:2: WARNING: Duplicate explicit target name: "more information".
/home/builder/.termux-build/mpd/src/doc/user.rst:657: WARNING: Unexpected indentation.
/home/builder/.termux-build/mpd/src/doc/user.rst:660: WARNING: Unexpected indentation.
/home/builder/.termux-build/mpd/src/doc/mpd.1.rst: WARNING: document isn't included in any toctree
/home/builder/.termux-build/mpd/src/doc/mpd.conf.5.rst: WARNING: document isn't included in any toctree
/home/builder/.termux-build/mpd/src/doc/user.rst:1249: WARNING: unknown option: --verbose
/home/builder/.termux-build/mpd/src/doc/user.rst:1342: WARNING: unknown option: --verbose
ninja: build stopped: subcommand failed.
```

**Comment by tomty89** [comment]
@Grimler91 https://github.com/MusicPlayerDaemon/MPD/commit/59792cb0b801854ee41be72d33db9542735df754

**Comment by Grimler91** [comment]
Thanks, that's probably it!

**Comment by tomty89** [comment]
@Grimler91 So I worked around the weird linking issue on arm with `--disable-neom-asm`. If you are okay with it you can sqaush and apply 0f8a8e7 and da4471d and enable libvpx again in ffmpeg.

**Comment by Grimler91** [comment]
@tomty89 great, thanks for looking into it!

**Pull request merged**
