### PR TITLE
new package: kphp

### LINKED ISSUE #8529: add kphp for termux
### Package description

Vk kphp information https://ru.m.wikipedia.org/wiki/KPHP used Google translate English 

### Home page URL

https://github.com/vkcom/kphp

### Source code URL

https://github.com/vkcom/kphp

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

about KPHP — a PHP compiler

### PR DESCRIPTION
**Pull request by xtkoba**
Closes #8529.

### CODE REVIEW

**Review by xeffyr — APPROVED** [review]

**Comment by ExtinctDrift19** [comment]
kphp why not published yet not ready

**Comment by xeffyr** [comment]
It is published:
```
~ $ apt search kphp
Sorting... Done
Full Text Search... Done
kphp/stable 2021.12.30 aarch64
  A PHP compiler

kphp-static/stable 2021.12.30 aarch64
  Static libraries for kphp

kphp-timelib/stable 2021.03.01 aarch64
  timelib 2020.02 library fork for KPHP
```

It is not available for `arm` - intended.

**Comment by ExtinctDrift19** [comment]
aarrch32 only available kphp-timelib

**Comment by xeffyr** [comment]
Right, not every package can be built for all architectures. Thus `kphp` is available only for 64 bit: aarch64 and x86_64. `kphp-timelib` is available for all architectures.

**Pull request merged**
