### PR TITLE
Update zsh from 5.4.1 to 5.4.2

### PR DESCRIPTION
**Pull request by Auxilus**

### CODE REVIEW

**Comment by Grimler91** [comment]
You need to update the sha256 as well, otherwise the download step will complain that there is a mismatch and fail

**Comment by Auxilus** [comment]
Ive commented it for now, ill add sha256 after i get it from travis logs

**Comment by Grimler91** [comment]
Great 👍

**Comment by fornwall** [comment]
Thanks! The built package will be available in about 15 minutes for installation from the package repository.

**Pull request merged**
