### PR TITLE
fix(main/coreutils): fix `cp -a` permission denied on symlink

### LINKED ISSUE #21597: [Bug]: "cp -a" fails on symbolic links
### Problem description

'cp' with "-a" on a symbolic link gives:
cp: failed to restore the default file creation context: Permission denied

### What steps will reproduce the bug?
<sup>Maintainer note: example edited for clarity</sup>
```bash
ln -s foo foo.ln
cp -a foo.ln foo.copy
# cp: failed to restore the default file creation context: Permission denied
```

### What is the expected behavior?

Should succeed

### System information

```shell
coreutils/stable,now 9.5-2 aarch64
(Android 14 on Pixel Fold)
```

### PR DESCRIPTION
**Pull request by kyufie**
SELinux affairs are now limited to root user

Fixes #21597

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
This should be fine, but other utilities would be affected too.

https://github.com/search?q=repo%3Acoreutils%2Fcoreutils%20selinux_enabled&type=code

**Comment by kyufie** [comment]
Here's what I got so far.
I've disabled SELinux support for `install` since it tries to restorecon files by default which is not possible at the moment.

```diff
--- coreutils-9.5.orig/src/cp.c
+++ coreutils-9.5/src/cp.c
@@ -994,7 +994,7 @@
 
   atexit (close_stdin);
 
-  selinux_enabled = (0 < is_selinux_enabled ());
+  selinux_enabled = (0 < is_selinux_enabled () && geteuid () == 0);
   cp_option_init (&x);
 
   while ((c = getopt_long (argc, argv, "abdfHilLnprst:uvxPRS:TZ",
@@ -1201,7 +1201,7 @@
             {
               error (0, 0,
                      _("warning: ignoring --context; "
-                       "it requires an SELinux-enabled kernel"));
+                       "it requires an SELinux-enabled kernel and root access"));
             }
           break;
 
@@ -1277,7 +1277,7 @@
   if (x.require_preserve_context && ! selinux_enabled)
     error (EXIT_FAILURE, 0,
            _("cannot preserve security context "
-             "without an SELinux-enabled kernel"));
+             "without an SELinux-enabled kernel and root access"));
 
   /* FIXME: This handles new files.  But what about existing files?
      I.e., if updating a tree, new files would have the specified context,
--- coreutils-9.5.orig/src/install.c
+++ coreutils-9.5/src/install.c
@@ -789,7 +789,7 @@
   bool strip_program_specified = false;
   char const *scontext = nullptr;
   /* set iff kernel has extra selinux system calls */
-  selinux_enabled = (0 < is_selinux_enabled ());
+  selinux_enabled = 0;
 
   initialize_main (&argc, &argv);
   set_program_name (argv[0]);
--- coreutils-9.5.orig/src/mkdir.c
+++ coreutils-9.5/src/mkdir.c
@@ -228,7 +228,7 @@
               /* We don't yet support -Z to restore context with SMACK.  */
               scontext = optarg;
             }
-          else if (is_selinux_enabled () > 0)
+          else if (is_selinux_enabled () > 0 && geteuid () == 0)
             {
               if (optarg)
                 scontext = optarg;
@@ -244,7 +244,7 @@
             {
               error (0, 0,
                      _("warning: ignoring --context; "
-                       "it requires an SELinux/SMACK-enabled kernel"));
+                       "it requires an SELinux/SMACK-enabled kernel and must be run as root"));
             }
           break;
         case_GETOPT_HELP_CHAR;
--- coreutils-9.5.orig/src/mkfifo.c
+++ coreutils-9.5/src/mkfifo.c
@@ -102,7 +102,7 @@
               /* We don't yet support -Z to restore context with SMACK.  */
               scontext = optarg;
             }
-          else if (is_selinux_enabled () > 0)
+          else if (is_selinux_enabled () > 0 && geteuid () == 0)
             {
               if (optarg)
                 scontext = optarg;
@@ -118,7 +118,7 @@
             {
               error (0, 0,
                      _("warning: ignoring --context; "
-                       "it requires an SELinux/SMACK-enabled kernel"));
+                       "it requires an SELinux/SMACK-enabled kernel and must be run as root"));
             }
           break;
         case_GETOPT_HELP_CHAR;
--- coreutils-9.5.orig/src/mknod.c
+++ coreutils-9.5/src/mknod.c
@@ -119,7 +119,7 @@
               /* We don't yet support -Z to restore context with SMACK.  */
               scontext = optarg;
             }
-          else if (is_selinux_enabled () > 0)
+          else if (is_selinux_enabled () > 0 && geteuid () == 0)
             {
               if (optarg)
                 scontext = optarg;
@@ -135,7 +135,7 @@
             {
               error (0, 0,
                      _("warning: ignoring --context; "
-                       "it requires an SELinux/SMACK-enabled kernel"));
+                       "it requires an SELinux/SMACK-enabled kernel and must be run as root"));
             }
           break;
         case_GETOPT_HELP_CHAR;
--- coreutils-9.5.orig/src/mv.c
+++ coreutils-9.5/src/mv.c
@@ -120,7 +120,7 @@
 static void
 cp_option_init (struct cp_options *x)
 {
-  bool selinux_enabled = (0 < is_selinux_enabled ());
+  bool selinux_enabled = (0 < is_selinux_enabled () && geteuid () == 0);
 
   cp_options_default (x);
   x->copy_as_regular = false;  /* FIXME: maybe make this an option */
@@ -326,7 +326,7 @@
   bool no_target_directory = false;
   int n_files;
   char **file;
-  bool selinux_enabled = (0 < is_selinux_enabled ());
+  bool selinux_enabled = (0 < is_selinux_enabled () && geteuid () == 0);
   bool no_clobber = false;
 
   initialize_main (&argc, &argv);
--- coreutils-9.5.orig/src/runcon.c
+++ coreutils-9.5/src/runcon.c
@@ -190,8 +190,8 @@
       usage (EXIT_CANCELED);
     }
 
-  if (is_selinux_enabled () != 1)
-    error (EXIT_CANCELED, 0, _("%s may be used only on a SELinux kernel"),
+  if (is_selinux_enabled () != 1 || geteuid () != 0)
+    error (EXIT_CANCELED, 0, _("%s may be used only on a SELinux kernel and must be run as root"),
            program_name);
 
   if (context)
```

**Comment by agnostic-apollo** [comment]
All the others look good.

>  I've disabled SELinux support for install since it tries to restorecon files by default which is not possible at the moment.

The `install` should also have the same standard root check added. The `setdefaultfilecon()` function returns without doing anything if selinux is not enabled, in our case it would do the same if root wasn't enabled. There are also other `-Z` and `--preserve-context` flags that use it, and their error message would need to be updated like done for others.

- https://github.com/coreutils/coreutils/blob/0619c4a49130a9ea09ca8ac7774d6810f641aab5/src/install.c#L328
- https://github.com/coreutils/coreutils/blob/0619c4a49130a9ea09ca8ac7774d6810f641aab5/src/install.c#L875-L906

**Comment by kyufie** [comment]
Screenshot_2024-10-01-01-44-03-451_com termux-edit
Currently, calling `setdefaultfilecon` is not possible.
There could be a workaround for this since android has `restorecon` which behaves similarly.
https://cs.android.com/android/platform/superproject/main/+/main:external/selinux/libselinux/src/label_file.c;drc=219e32ac3960fa9429692783d80dc93e202150e5;l=890
Would it be okay to return from the function unconditionally as a temporary fix?

**Comment by agnostic-apollo** [comment]
Ah right, system selinux library should be able to do it somehow, but not ours.

> Would it be okay to return from the function unconditionally as a temporary fix?

Yes, do that.

**Comment by agnostic-apollo** [comment]
Looks good to me, thanks. Unreachable code could be an issue during build, if it succeeds, I'll merge.

**Comment by kyufie** [comment]
Thanks.

**Pull request merged**
