### PR TITLE
android-tools: Bump to 33.0.3p2

### PR DESCRIPTION
**Pull request by MrAdityaAlok**
- Remove no longer required `pthread` patches:
    * vendor_CMakeLists.adb.txt.patch
    * vendor_CMakeLists.fastboot.txt.patch
See: https://github.com/nmeum/android-tools/commit/8d839f86359b90ed61942e04a0041a61b9792bc8

- Update patch `vendor_CMakeLists.mke2fs.txt.patch`.

Signed-off-by: Aditya Alok <alok@termux.dev>

### CODE REVIEW

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/pull/12427

**Comment by MrAdityaAlok** [comment]
> #12427

Oh, sorry! I didn't see that (sinc eno pr's were linked to the issue).

**Comment by ifurther** [comment]
Maybe could try remove `#define _REALLY_INCLUDE_SYS__SYSTEM_PROPERTIES_H_` in android_common.h

**Comment by MrAdityaAlok** [comment]
> Maybe could try remove `#define _REALLY_INCLUDE_SYS__SYSTEM_PROPERTIES_H_` in android_common.h

But then including <sys/_system_properties.h> will fail.
```cpp
#ifndef _REALLY_INCLUDE_SYS__SYSTEM_PROPERTIES_H_
#error you should #include <sys/system_properties.h> instead
#endif
```

**Comment by Lzhiyong** [comment]
IMG_20221029_145308

the `libc.so` does not contain this symbol, but `libc.a` dose, you need to link statically.

[https://android.googlesource.com/platform/bionic/+/0d787c1fa18c6a1f29ef9840e28a68cf077be1de/libc/bionic/system_properties.c](https://android.googlesource.com/platform/bionic/+/0d787c1fa18c6a1f29ef9840e28a68cf077be1de/libc/bionic/system_properties.c)

**Comment by ifurther** [comment]
the `_system_properties.h` is in the ~/lib/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sys/

**Comment by MrAdityaAlok** [comment]
> the `libc.so` does not contain this symbol, but `libc.a` dose, you need to link statically.
>
Tried that before, but statically linking won't work. We need to exclude `<sys/system_properties>` functions in `libbase/properties.cpp` because two of them is only defined for `__ANDROID_API__ >= 26`. On excluding them it (`libbase/properties.cpp`) defines it's own version of `__system_property_get` and `__system_property_set` which conflicts with libc's. We cannot even disable them because few functions defined in `libbase/properties.cpp` depends on variables handled by these custom functions.

For more clarity see:
- https://android.googlesource.com/platform/system/libbase/+/refs/heads/master/properties.cpp
- then this patch https://github.com/termux/termux-packages/blob/master/packages/android-tools/vendor_libbase_properties.cpp.patch

**Comment by xtkoba** [comment]
Note that submodules of 33.0.3 are not actually 33.0.3. I noticed that because CVE patches applied to 33.0.3 cleanly (which should be rejected as reverse patches.) Bump should be to 33.0.3p2 (or newer.)

**Pull request merged**
