### PR TITLE
change: bump proton-bridge version to 1.5.0

### PR DESCRIPTION
**Pull request by exander77**

### CODE REVIEW

**Comment by exander77** [comment]
Hmm, it didn't build on arm. Have to check new parser.

**Comment by exander77** [comment]
@xeffyr Can a platform be removed on specific package?

**Comment by exander77** [comment]
This is really strange, it built ok inside docker using:
```
./build-package.sh -a all -I proton-bridge
```
How so?

**Comment by Grimler91** [comment]
You can use `TERMUX_PKG_BLACKLISTED_ARCHES="arm"` to skip building for arm.
But if it builds in the docker image it should build here, strange

**Comment by xeffyr** [comment]
> This is really strange, it built ok inside docker using:

Just use clean Docker image and this "strange behavior" will gone.

CI creates a new container each time and does builds for AArch64, ARM, i686, x86_64 separately.

```
go: downloading github.com/ssor/bom v0.0.0-20170718123548-6386211fdfcf
go: downloading github.com/mattn/go-runewidth v0.0.9
go: downloading github.com/emersion/go-message v0.12.1-0.20200903165315-e1abe21f389a
go: downloading github.com/golang/mock v1.4.4
go: downloading github.com/google/go-cmp v0.5.1
go: downloading github.com/mattn/go-colorable v0.1.4
go: downloading github.com/PuerkitoBio/goquery v1.5.1
go: downloading github.com/go-resty/resty/v2 v2.3.0
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/emersion/go-sasl v0.0.0-20200509203442-7bfe0ed36a21
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/emersion/go-imap-move v0.0.0-20190710073258-6e5a51a5b342
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/emersion/go-textwrapper v0.0.0-20160606182133-d0e65e56babe
go: downloading github.com/andybalholm/cascadia v1.1.0
# github.com/ProtonMail/proton-bridge/pkg/message/rfc5322/parser
pkg/message/rfc5322/parser/rfc5322_parser.go:2763: constant 4230534781 overflows int
pkg/message/rfc5322/parser/rfc5322_parser.go:2787: constant 4230534781 overflows int
pkg/message/rfc5322/parser/rfc5322_parser.go:6671: constant 2740715144 overflows int
pkg/message/rfc5322/parser/rfc5322_parser.go:6671: constant 4294965233 overflows int
pkg/message/rfc5322/parser/rfc5322_parser.go:6836: constant 3011247752 overflows int
pkg/message/rfc5322/parser/rfc5322_parser.go:6836: constant 4294965233 overflows int
pkg/message/rfc5322/parser/rfc5322_parser.go:11550: constant 4244674173 overflows int
pkg/message/rfc5322/parser/rfc5322_parser.go:11975: constant 4292870143 overflows int
make: *** [Makefile:65: build-nogui] Error 2
builder@8fd383dfa0c3:~/termux-packages$ ls debs
proton-bridge_1.5.0_aarch64.deb
builder@8fd383dfa0c3:~/termux-packages$
```

Use `TERMUX_PKG_BLACKLISTED_ARCHES="arm"` here.

**Comment by exander77** [comment]
I disable both arm and i686 and it still fails for x86_64:
```
Error: Process completed with exit code 1.
```
Works in my cleaned docker.

**Comment by xeffyr** [comment]
> still fails for x86_64

It failed to download Docker image.

**Comment by xeffyr** [comment]
Idk what is happening with CI... merging anyway.

**Comment by exander77** [comment]
It should build for aarch64 and x86_64 for sure. I have retested twice. I will need to fix arm and i686 in antl4 which apparently creates code incompatible with 32 bit even though the issue is fixed for 3 years.

**Comment by xeffyr** [comment]
@exander77 That was due to recent change of `scripts/properties.sh`. Fixed in https://github.com/termux/termux-packages/commit/61860b93a6d7bfe2953451d586b35d27dfb80337, so `proton-bridge` update will be available shortly.

**Pull request merged**
