### PR TITLE
new package: wtfutil

### LINKED ISSUE #15318: [Package]: wtf
### Why do you want to add this package to Termux?

The personal information dashboard for your terminal
  

### Home page URL

wtfutil.com

### Source code URL

https://github.com/wtfutil/wtf

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xtkoba**
Closes #15318.

### CODE REVIEW

**Comment by 2096779623** [comment]
It doesn't matter though that it won't fetch the correct version.
```bash
~ $ wtfutil -v
dev (now)
~ $ 
```
Run it on my pc:
```bash
root@kev1n8w:/mnt/d/wtf_0.43.0_linux_amd64# ./wtfutil -v
ea7f6ed1ce0e3a96c7ce7aa337bfdae9cfc27a93 (2023-02-24T05:33:54Z)
```

There are also some features that don't work/display incorrectly(default settings):
image
Run it on my pc:
image

**Comment by xtkoba** [comment]
What are incorrect?

**Comment by 2096779623** [comment]
> What are incorrect?

uptime and source, the result of running on pc is the same, I think this is not a bug that must be fixed by us, it may need to be manually configured by the user to display correctly.

**Comment by xtkoba** [comment]
Ah, maybe due to access to `/proc` being restricted? Yes that is something we cannot fix.

Is this still useful then?

**Comment by 2096779623** [comment]
> Ah, maybe due to access to `/proc` being restricted? Yes that is something we cannot fix.

When I use `sudo` and vpn:
Screenshot_20230312-221609

**Comment by 2096779623** [comment]
[a.log](https://github.com/termux/termux-packages/files/10951088/a.log)

It does access to `/proc`, but it doesn't seem to have any effect(without sudo).

**Pull request merged**
