### PR TITLE
new package: wine-stable

### LINKED ISSUE #1423: Package request wine
Hello,
it would be nice to be able to run simple windows console programs like botvs.
However wine is difficult to compile and have many dependecies like mono. Of course, in order to make things simpler, building graphic support is not needed.

### PR DESCRIPTION
**Pull request by licy183**
This package is tested on MIX2s (aarch64) and MEIZU Pro 6S (arm), but it doesn't seem to work on arm, so disable building on arm.

Explorer:
image

Notepad:
image

Closes #1423

### CODE REVIEW

**Comment by licy183** [comment]
> This version only runs ARM applications?

Yes. I haven't make it to enable ARM64EC support.

> I would wait a few weeks, as we are at the stage of Wine 9.0, which will be stable. Unless the new version doesn't run on Termux.

Wine on Termux is broken since 8.18. I've reported it upstream, see https://bugs.winehq.org/show_bug.cgi?id=56130
. I found a [patch](https://github.com/termux-user-repository/tur/blob/master/tur-multilib/wine-staging/0004-set-space_limit.patch) which seems resolving this issue but it doesn't get merged yet.

**Comment by IntinteDAO** [comment]
@licy183 Check WineHQ bugzilla, you've got response

**Comment by licy183** [comment]
Wine 9.0 has released. I'll try to comile it later.

**Comment by zavocc** [comment]
That wine version would include the emulation layer module?

**Comment by licy183** [comment]
> That wine version would include the emulation layer module?

I suppose wine 9.0 doesn't have the emulation layer module. It's waiting for the LLVM toolchain to be ready.

> There is initial support for building Wine for the ARM64EC architecture, using an experimental LLVM toolchain. Once the toolchain is ready, this will be used to do a proper ARM64X build and enable 64-bit x86 emulation.

**Comment by licy183** [comment]
I'll merge this PR tomorrow if there is no more review. Thanks!

**Comment by AndreRH** [comment]
Hangover would be more reasonable as it includes emulation and you already have it in tur, no?

**Comment by licy183** [comment]
> Hangover would be more reasonable as it includes emulation and you already have it in tur, no?

Emmm... I'll add it later.

**Comment by Saikatsaha1996** [comment]
@AndreRH @licy183 can you updated your hangover please? Without those patch we can't use vulkan in hangover for our snapdragon device..

In your box64 haven't this mmap32 features.. & even those wine patches also missing 

https://github.com/ptitSeb/box64/blob/main/docs/USAGE.md#box64_mmap32-

[hook_mmap1.diff.txt](https://github.com/termux/termux-packages/files/15242230/hook_mmap1.diff.txt)
[fix-address.diff.txt](https://github.com/termux/termux-packages/files/15242231/fix-address.diff.txt)

I already created issue 

https://github.com/AndreRH/hangover/issues/151


Without this

**Comment by SwuduSusuwu** [comment]
```
pkg install wine
Hit:1 https://termux.net stable InRelease
All packages are up to date.
Error: Unable to locate package wine
~/win32 $ pkg install hangover
Error: Unable to locate package hangover
~/win32 $ date
Sun Oct  6 16:16:36 PDT 2024
```

**Comment by TomJo2000** [comment]
> ```
> pkg install wine
> Hit:1 https://termux.net stable InRelease
> All packages are up to date.
> Error: Unable to locate package wine
> ~/win32 $ pkg install hangover
> Error: Unable to locate package hangover
> ~/win32 $ date
> Sun Oct  6 16:16:36 PDT 2024
> ```

The package is `wine-stable`

**Comment by SwuduSusuwu** [comment]
> > ```
> > pkg install wine
> > Hit:1 https://termux.net stable InRelease
> > All packages are up to date.
> > Error: Unable to locate package wine
> > ~/win32 $ pkg install hangover
> > Error: Unable to locate package hangover
> > ~/win32 $ date
> > Sun Oct  6 16:16:36 PDT 2024
> > ```
> 
> The package is `wine-stable`

```
$ pkg install wine-stable
Hit:1 https://termux.net stable InRelease
All packages are up to date.
Error: Unable to locate package wine-stable
```

**Comment by truboxl** [comment]
`termux.net` is Google Play version repo. Need @fornwall to check. I suggest @SwuduSusuwu to file new reports at https://github.com/termux-play-store/termux-issues instead of necro bump old issues.

**Pull request merged**
