### PR TITLE
vtm: remove unnecessary patches

### PR DESCRIPTION
**Pull request by UltraStudioLTD**
> In previous #10432 PR I forgot to add proper description which cause PR to be closed. So here is description and reason to why remove those 2 patches.

Removes unnecessary patches from [**vtm**](https://github.com/netxs-group/vtm) package.

Reason is that since commit [**e9e1483600eb72422eab249043f852d348ed2a0e**](https://github.com/netxs-group/vtm/commit/e9e1483600eb72422eab249043f852d348ed2a0e) [**vtm**](https://github.com/netxs-group/vtm) supports **Android** system and during compilation it [automatically detects if host OS is **Android** system](https://github.com/netxs-group/vtm/commit/5516a782e182cda0cd32470bcba74a6e34c7ad56).

This makes 2 patches in [**vtm package**](https://github.com/termux/termux-packages/tree/master/packages/vtm), [*CMakeLists.txt.patch*](https://github.com/termux/termux-packages/blob/master/packages/vtm/CMakeLists.txt.patch) and [*netxs-os-system.hpp.patch*](https://github.com/termux/termux-packages/blob/master/packages/vtm/netxs-os-system.hpp.patch) unnecessarily.

### CODE REVIEW

**Comment by UltraStudioLTD** [comment]
I don't know why build fails. As far as I know **libandroid-spawn** includes **spawn.h**.

**Comment by UltraStudioLTD** [comment]
If anyone wants to close this PR please give me explanation of why

**Comment by UltraStudioLTD** [comment]
At least on my **aarch64** device it builds and runs without problems.

**Comment by Grimler91** [comment]
Doesn't seem like the android check works as intended. Looks like CMAKE_CXX_FLAGS is overridden with `-pthread`, removing our `-I$PREFIX/include` flag. I guess [`CMAKE_HOST_SYSTEM_NAME`](https://github.com/netxs-group/vtm/blob/f9c5fd7d00a035ab7d24959c2d0e3ff4e646fc2c/src/CMakeLists.txt#L16) isn't set to android when cross-compiling for android/termux

**Comment by Grimler91** [comment]
Commits should also be squashed and message(s) prefixed with `vtm:`. The first line should summarise the commit, right now we have `Removal of unnecessary CMakeLists.txt patch` which doesn't say which package it is that is modified

`TERMUX_PKG_REVISION` also needs to be bumped/set to 1

**Comment by UltraStudioLTD** [comment]
> Commits should also be squashed and message(s) prefixed with `vtm:`. The first line should summarise the commit, right now we have `Removal of unnecessary CMakeLists.txt patch` which doesn't say which package it is that is modified

I didn't knew that I should have added **vtm:** prefix.
Sorry 😐

**Comment by UltraStudioLTD** [comment]
> Doesn't seem like the android check works as intended. Looks like CMAKE_CXX_FLAGS is overridden with `-pthread`, removing our `-I$PREFIX/include` flag. I guess [`CMAKE_HOST_SYSTEM_NAME`](https://github.com/netxs-group/vtm/blob/f9c5fd7d00a035ab7d24959c2d0e3ff4e646fc2c/src/CMakeLists.txt#L16) isn't set to android when cross-compiling for android/termux

I tried using https://github.com/termux/termux-packages/issues/151#issuecomment-327272203 here for detection

**Comment by Grimler91** [comment]
> I tried using [#151 (comment)](https://github.com/termux/termux-packages/issues/151#issuecomment-327272203) here for detection

The example there checks `CMAKE_SYSTEM_NAME` instead of `CMAKE_HOST_SYSTEM_NAME` which could be the issue

**Comment by UltraStudioLTD** [comment]
I will test vtm with `CMAKE_HOST_SYSTEM_NAME STREQUAL "Android"`, but problem is that even after I PR this change in detection system (if it works), v0.7.4 will not become available for at least 3~4 days I think since currently there are no huge updates in vtm's repo

**Comment by Grimler91** [comment]
Add it as a patch in this PR instead

**Comment by UltraStudioLTD** [comment]
I will do it tomorrow since right now it's bedtime for me 😅

**Comment by buttaface** [comment]
> I will test vtm with CMAKE_HOST_SYSTEM_NAME STREQUAL "Android"

You shouldn't be using `CMAKE_HOST_SYSTEM_NAME` as that refers to the host system on which the build occurs. Since these packages are built on our linux x86_64 CI, that will be set to `Linux`, while `CMAKE_SYSTEM_NAME` is set to `Android`.

**Comment by UltraStudioLTD** [comment]
> > I will test vtm with CMAKE_HOST_SYSTEM_NAME STREQUAL "Android"
> 
> You shouldn't be using `CMAKE_HOST_SYSTEM_NAME` as that refers to the host system on which the build occurs. Since these packages are built on our linux x86_64 CI, that will be set to `Linux`, while `CMAKE_SYSTEM_NAME` is set to `Android`.

So that means that my method is correct right?

**Comment by buttaface** [comment]
I don't know, as I don't see either used in this pull, so I don't know what you two are referring to.

**Comment by Grimler91** [comment]
> So that means that my method is correct right?

It means that your method is not correct, and it explains why vtm needs that patch

**Comment by UltraStudioLTD** [comment]
> > So that means that my method is correct right?
> 
> It means that your method is not correct, and it explains why vtm needs that patch

I don't get it 😅. If <kbd>CMAKE_HOST_SYSTEM_NAME</kbd> is unable to detect/different **Android** from **Linux**, while <kbd>CMAKE_SYSTEM_NAME</kbd> is able to *DETECT* **Android**, why does **vtm** needs patch?

**Comment by UltraStudioLTD** [comment]
**vtm** uses <kbd>CMAKE_SYSTEM_NAME</kbd> to detect **Android**

**Comment by UltraStudioLTD** [comment]
I am confused by what method should **vtm** use.
<kbd>CMAKE_HOST_SYSTEM_NAME</kbd> or <kbd>CMAKE_SYSTEM_NAME</kbd> and which is correct (I think <kbd>CMAKE_SYSTEM_NAME</kbd> since 1. It works; 2. It was used in few discussions about **cmake** on **Android**)

**Comment by Grimler91** [comment]
@UltraStudioLTD provide links to support your claims. 

> vtm uses CMAKE_SYSTEM_NAME to detect Android

Where? I see only a [`CMAKE_HOST_SYSTEM_NAME` check](https://github.com/netxs-group/vtm/blob/f9c5fd7d00a035ab7d24959c2d0e3ff4e646fc2c/src/CMakeLists.txt#L16)

> why does vtm needs patch?

Well it needs a patch since without a patch building vtm for termux clearly doesn't work, as CI test builds show

> I am confused by what method should vtm use.
CMAKE_HOST_SYSTEM_NAME or CMAKE_SYSTEM_NAME and which is correct (I think CMAKE_SYSTEM_NAME since 1. It works; 2. It was used in few discussions about cmake on Android)

cmake docs are the best place to learn more about what the variables actually do:

https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_NAME.html
https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_NAME.html

**Comment by UltraStudioLTD** [comment]
Alright. I will switch to <kbd>CMAKE_SYSTEM_NAME</kbd> but for it let's wait for next release. In meantime I will PR **vtm**. I will draft this PR for now

**Comment by Grimler91** [comment]
> Alright. I will switch to CMAKE_SYSTEM_NAME but for it let's wait for next release. In meantime I will PR vtm

Have you tested if it works? Adding the patch to this PR would show if that is enough to make vtm build for termux. 
Always a good idea to test the changes before opening PRs

**Comment by UltraStudioLTD** [comment]
I don't have time for it currently. Sorry 😐
I am busy with homework, but as soon as I have time, I will test it

**Comment by UltraStudioLTD** [comment]
I Pulled Request this patch in **vtm** in https://github.com/netxs-group/vtm/pull/213
Hope it fixes it.
Just want to know - what does <kbd>CMAKE_HOST_SYSTEM_NAME</kbd> and <kbd>CMAKE_SYSTEM_NAME</kbd> "output" or are set to in **CI**

**Comment by buttaface** [comment]
CMAKE_HOST_SYSTEM_NAME - Linux
CMAKE_SYSTEM_NAME - Android

**Comment by xtkoba** [comment]
Partially merged as f21c111e946f17d27bfde7c7fa52881160e8c39c.

**Pull request closed without merging**
