### PR TITLE
libpaper: remove _NL_PAPER_{WIDTH,HEIGHT}

### PR DESCRIPTION
**Pull request by knyipab**
Discovered that `_NL_PAPER_WIDTH` and `_NL_PAPER_HEIGHT` are not the size but they are C++ `enum` items (e.g. [defined in langinfo.h](https://sites.uclouvain.be/SystInfo/usr/include/langinfo.h.html)) that is the input of std c lib func [`nl_langinfo()`](https://man7.org/linux/man-pages/man3/nl_langinfo_l.3.html) . Feeding 210 and 297 into that func may have unknown behavior. 

I discovered this as I am trying to build libreoffice and I encountered the similar issue in their `paper.cxx`. 

It may not have material impact on existing package, but just for correctness.

### CODE REVIEW

**Comment by Biswa96** [comment]
> Discovered that `_NL_PAPER_WIDTH` and `_NL_PAPER_HEIGHT` are not the size but they are C++ `enum` items

That explains the removal of `CFLAGS+=" -D_NL_PAPER_WIDTH=210 -D_NL_PAPER_HEIGHT=297"` 👍 

Could you explain why the patch file was added?

**Comment by knyipab** [comment]
Cuz android's bionic does not define or use `_NL_PAPER_WIDTH` and `_NL_PAPER_HEIGHT` at all, so there is no such thing calling `nl_langinfo(_NL_PAPER_WIDTH)`. Libreoffice's implementation basically skip that part of locale paper size detection with `&& !defined(ANDROID)`. See: 
https://github.com/LibreOffice/core/blob/7db1150b2c4a9adb993084d2dceedb450781b1dc/i18nutil/source/utility/paper.cxx#L308-L317

Note; libreoffice's `ANDROID` is probably configured by their makefile and does not work, so I patch that to `!defined(__ANDROID__)`

**Comment by Biswa96** [comment]
Thanks for the explanation. I think this change can be added in upstream.

`__ANDROID__` is the correct one https://android.googlesource.com/platform/bionic/+/HEAD/docs/defines.md

**Comment by knyipab** [comment]
Okay, made one here: https://github.com/rrthomas/libpaper/pull/59
Last commit is six months ago and will see if they will merge and make a new release.

**Comment by landfillbaby** [comment]
alternatively, partially revert https://github.com/termux/termux-packages/commit/2148a3e1a616f90bfa80bd85848d9558e37802f0, to this:

```sh
termux_step_pre_configure() {
	# 210x297 is A4 size. Hard code as default.
	sed -i \
		-e "s|NL_PAPER_GET(_NL_PAPER_WIDTH)|210|g" \
		-e "s|NL_PAPER_GET(_NL_PAPER_HEIGHT)|297|g" \
		"${TERMUX_PKG_SRCDIR}"/lib/libpaper.c.in.in
}
```

**Comment by knyipab** [comment]
I do not hold strong view nor any preference on which approach. I just want to flag it. Feel free to change this PR.

**Review by TomJo2000 — APPROVED** [review]

**Review by twaik — APPROVED** [review]

**Comment by twaik** [comment]
Tuxpaint works fine, no errors.

**Comment by twaik** [comment]
I'll push these changes in 48 hours if no one minds.
Or someone else can do that earlier.

**Pull request merged**
