### PR TITLE
poppler: Update from 0.67.0 to 0.72.0

### PR DESCRIPTION
**Pull request by tomty89**

### CODE REVIEW

**Comment by Grimler91** [comment]
We also need to bump all the packages depending on poppler and update the [texlive-bin patches](https://github.com/termux/termux-packages/tree/master/packages/texlive-bin) to [new ones](https://github.com/TeX-Live/texlive-source/commit/67290f70d8143b18f24ffd6a1827def9bdc21108) supporting poppler 0.72. 

It would probably be a good idea to gather the updates under one PR, I can look at updating the patches and open a PR against your branch.

**Comment by tomty89** [comment]
Yeah would be great if you can help bump texlive-bin. It should be the only package the deps on poppler.

**Comment by tomty89** [comment]
@Grimler91 Merge. Thank you so much : )

**Comment by fornwall** [comment]
The updated poppler and texlive-bin packages are now available for installation!

**Pull request merged**
