### PR TITLE
Add ragel package

### PR DESCRIPTION
**Pull request by ebraminio**
It is based on my https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-ragel/PKGBUILD but I didn't test if it works honestly, would be nice if someone else do as my PC screen just got break :)

### CODE REVIEW

**Comment by ebraminio** [comment]
Hmm, when I tried to manually compile it, it raises
```
../aapl/vector.h:711:25: error: exception handling disabled, use -fexceptions to enable
    throw std::bad_alloc();
```
Does this mean something it should be changed when compiling on this patch or it will be OK while cross compiling?

**Comment by fornwall** [comment]
Thanks for the pull request! See [my notes on the diff](https://github.com/ebraminio/termux-packages/commit/6dab9b40d8663727d30bcfda72a04c322e8bbf06).

About test compiling, to cross compile you should use `./build-package.sh ragel` (seems to compile fine when I test)!

**Comment by ebraminio** [comment]
Fascinating, I just did a commit ammend using termux, who believes it? :) As mentioned I can not do that right now, can you check that just if it works?

**Comment by fornwall** [comment]
Merged, great work! You should be able to install the package with `apt update && apt install ragle` now.

Sorry, I did not understand that you were doing this in Termux itself :). All scripts assume that we're cross compiling from a separate host computer now, I will look into adding support for developing Termux packages on Termux itself in the future!

**Pull request merged**
