### PR TITLE
Build static libraries. No more develsplit.

### PR DESCRIPTION
**Pull request by xeffyr**
This pull request will enable packaging of static libraries into separate packages (named like `{package name}-static`) and will disable splitting of development files into `*-dev`.

Since such PR will be a major change, about 270 packages will require rebuilding.

***

PR is ready now.
There may be some packages with shared-only libraries, but they can be fixed later.

### CODE REVIEW

**Comment by tomty89** [comment]
Looks like the static-split approach is not good enough:
```
$ dpkg -L libpulseaudio-static | grep '\..*a$'
/data/data/com.termux/files/usr/lib/libpulse.a
/data/data/com.termux/files/usr/lib/libpulse-simple.a
/data/data/com.termux/files/usr/lib/libpulse-simple.la
/data/data/com.termux/files/usr/lib/libpulse.la
$ dpkg -L libpulseaudio | grep '\..*a$'
/data/data/com.termux/files/usr/lib/pulseaudio/libpulsecore-12.2.a
/data/data/com.termux/files/usr/lib/pulseaudio/libpulsecommon-12.2.a
/data/data/com.termux/files/usr/lib/pulseaudio/libpulsecommon-12.2.la
/data/data/com.termux/files/usr/lib/pulseaudio/libpulsecore-12.2.la
$
```

**Comment by xeffyr** [comment]
Current static-split approach doesn't care about files in subdirectories. I can fix that.

**Comment by stalkerned** [comment]
please return dev packages. without dev, almost nothing works in termux. many python libraries do not work without python-dev. Metasploit does not work at all. return dev. your decision is wrong !!! many people will stop using termux.

**Comment by xeffyr** [comment]
> many python libraries do not work without python-dev

`disable splitting of development files into *-dev` means that -dev packages are no longer needed. All development files provided within one package.

**Pull request merged**
