### PR TITLE
gmic: build with cmake

### PR DESCRIPTION
**Pull request by tomty89**

### CODE REVIEW

**Comment by tomty89** [comment]
Haven't got the slightest idea why the Travis CI fails anyway. Cannot reproduce such problem by building with cmake on Termux.

**Comment by Grimler91** [comment]
CMakeError.log show lots of: 
```
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/clang++
Build flags: ;-Oz;-I/data/data/com.termux/files/usr/include
Id flags:

The output was:
1
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'memcpy', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to '__cxa_atexit', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'toupper_l', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'memchr', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to '__ctype_get_mb_cur_max', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'freelocale', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'btowc', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'mbrtowc', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'strtold_l', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'pthread_detach', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'pthread_mutex_destroy', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'strxfrm_l', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'close', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'syslog', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'wmemmove', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'pthread_mutexattr_settype', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'wcstoull', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'pthread_join', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'strtoll_l', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'wcsxfrm_l', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'islower_l', version 'LIBC'
/home/builder/.termux-build/_cache/17-aarch64-21-v1/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/libc++_shared.so: error: undefined reference to 'wcslen', version 'LIBC'
...
```

Can't remember how we solved that one, maybe with `-std=`?

**Comment by Grimler91** [comment]
Or just `-L/data/data/com.termux/files/usr/lib`: https://github.com/termux/termux-packages/issues/1190

**Comment by tomty89** [comment]
That is not the error found in the Travis CI log though. The problem there seems to be the inclusion of CImg.h does not have / have only partial effect in gmic_cli.cpp. Doesn't even seem to make sense to me.

@Grimler91 At what point do you get the errors? The final linking of the gmic executable? So you didn't bump into the Travis errors on your build host either?

**Comment by Grimler91** [comment]
I bumped into the exact travis error as well. Played around with including CImg.h a bit but it didn't seem to fix the underlying problem, I instead got problems with it trying to include X11.h (which `-Dcimg_display=0` should fix but it didn't work out of the box and then I gave up).

**Comment by Grimler91** [comment]
Still same error in CMakeError.log. 
-L/data/data/com.termux/files/usr/lib seems to be there but I can't see that it is using -std=c++11, maybe it needs to be given in another variable?

**Comment by tomty89** [comment]
Never mind then. I created this just because cmake works like a charm on Termux. Apparently making the switch here doesn't worth the effort.

**Comment by Grimler91** [comment]
CMake errors & logs are awful.. 

Should be possible to get it working, can look at it again when I have more time.

**Pull request closed without merging**
