### PR TITLE
bump(main/1oom): 1.8.1

### PR DESCRIPTION
**Pull request by TomJo2000**
* switch to maintained fork

Same source used by Debian, Ubuntu, Raspbian and Nixpkgs.

### CODE REVIEW

**Comment by TomJo2000** [comment]
This built fine locally...
Will investigate.

**Comment by twaik** [comment]
Probably you should add `libandroid-shmem` to TERMUX_PKG_DEPENDS, `-landroid-shmem` to `LDFLAGS`. `sys/shm.h` is not available in NDK so it should be requested manually in every package that needs it.

**Comment by twaik** [comment]
Probably that update will require moving it to x11-repo.

**Comment by TomJo2000** [comment]
> `sys/shm.h` is not available in NDK so it should be requested manually in every package that needs it.

Yep just noticed the relavant comment in the NDK setup.
https://github.com/termux/termux-packages/blob/c9061645bf4fbf9516f572eff6f1a3722fc9358b/scripts/build/toolchain/termux_setup_toolchain_26b.sh#L219

**Comment by TomJo2000** [comment]
I guess if I forget to add `libandroid-shmem` to dependencies I don't need to be surprised if it fails with the same error again.

**Comment by twaik** [comment]
Ok, it is ready for final force-push and merge. Or you can squash-and-merge it.

**Comment by TomJo2000** [comment]
Thanks for the assist.
I'll look this over and merge it

**Pull request merged**
