### PR TITLE
Update units to 2.16

### PR DESCRIPTION
**Pull request by Auxilus**

### CODE REVIEW

**Comment by fornwall** [comment]
Note that the build seems to be failing.

**Comment by Auxilus** [comment]
It compiled on my device without any errors... 
screenshot_20171101-205022

**Comment by Auxilus** [comment]
screenshot_20171101-205128

**Comment by fornwall** [comment]
Aha! It seems that the new units version doesn't handle building outside of the src dir.

Add `TERMUX_PKG_BUILD_IN_SRC=yes` to make the build happen in the src directory and it should work (and I'll merge it)!

**Comment by Auxilus** [comment]
👍

**Comment by Auxilus** [comment]
Done

**Comment by fornwall** [comment]
Nice work! The updated package is now available for installation.

**Pull request merged**
