### PR TITLE
Switching to different implementation of iconv()

### PR DESCRIPTION
**Pull request by xeffyr**

### CODE REVIEW

**Comment by Grimler91** [comment]
Decrypting something with gnupg fails with 
```
gpg: public key decryption failed: A locale function failed
gpg: decryption failed: No secret key
``` 
(possibly related bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866023)

I've tried rebuilding gnupg, and rebuilding after removing `agent-agent.h.patch` but it didn't change anything

**Comment by xeffyr** [comment]
@Grimler91 Is gnupg was liked with libiconv ? I haven't tested packages with libiconv, though one of potential problem sources can be nl_langinfo from musl-libc.

**Comment by Grimler91** [comment]
@xeffyr hm, no, `ldd` shows that it hasn't linked against libiconv, so we need a small patch for that. gpg is probably trying to use iconv form libc on my (android-9) device and failing, as [for ncmpcpp](https://github.com/termux/termux-packages/issues/3333).

**Comment by Grimler91** [comment]
This is probably the culprit: https://github.com/gpg/gnupg/blob/d5443b918dd3b8ccb3c4fdd8fe9d70d84aa312ff/configure.ac#L732

**Comment by Grimler91** [comment]
Linking against libiconv (by patching configure script I linked to) didn't help either, I still get the same "locale function failed" error

**Comment by xeffyr** [comment]
@Grimler91 Everything works. Just rebuild pinentry.

**Comment by xeffyr** [comment]
Should this be added to always deps via buildorder.py like libandroid-support ?

**Comment by Grimler91** [comment]
> Should this be added to always deps via buildorder.py like libandroid-support ?

_If_ we want want to go down that road then there is no need for @fornwall to write a script to find programs using unversioned iconv

**Comment by xeffyr** [comment]
Looks like I have to make iconv-checing script on my own.

**Comment by xeffyr** [comment]
Okay, got list of packages that should be rebuilt:
```
apr-util
bash
boost
cmus
coreutils
ctags
diffutils
doxygen
elinks
ffmpeg
finch
flac
gettext
ghostscript
git
glib
gnuplot
gst-plugins-bad
gtypist
hunspell
iconv
irssi
lftp
libandroid-support
libarchive
libgd
libgmime
libidn
libunistring
libxml2
lynx
mariadb
mc
minicom
mpv
mtools
mutt
ncdc
neovim
newsboat
parted
php
php-apache
php-fpm
pinentry
poppler
qalc
rsync
stfl
tar
texinfo
tig
vim
vorbis-tools
weechat
weechat-perl-plugin
wget
xorriso
zbar
```

**Comment by Grimler91** [comment]
@xeffyr Could you share the script? (So i can check my repos)

**Comment by xeffyr** [comment]
Just installed all packages and executed:
```
#!/data/data/com.termux/files/usr/bin/bash

: "${PREFIX:=/data/data/com.termux/files/usr}"

while read binary; do
    if [ "$(dd if="$binary" bs=1 skip=1 count=3 status=none)" = "ELF" ]; then
        iconv_symbols=$(objdump -T "$binary" 2>/dev/null | grep iconv)
        if [ -n "$iconv_symbols" ]; then
            pkg=$(dpkg -S "$binary" 2>/dev/null | cut -d: -f1)
            if [ ! -z "$pkg" ]; then
                echo "$pkg: $binary"
            fi
        fi
    fi
done <<< $({ find "$PREFIX"/bin "$PREFIX"/libexec -type f; find "$PREFIX"/lib -type f -iname \*.so\*; } | sort)
```

**Comment by xeffyr** [comment]
Another variant of script: [check-iconv.sh.txt](https://github.com/termux/termux-packages/files/3145635/check-iconv.sh.txt)

Will download all packages from Bintray and check them for iconv. At the end it will place log file with package list.
Based on https://github.com/termux/termux-packaging/blob/master/scripts/generate-bootstraps.sh

**Comment by xeffyr** [comment]
glib fails:
```
 /home/builder/.termux-build/glib/src/glib/gconvert.c:59:2: error: GNU libiconv not in use but included iconv.h is from libiconv
#error GNU libiconv not in use but included iconv.h is from libiconv
 ^
4 warnings generated.
1 error generated.
```

**Pull request merged**
