### PR TITLE
Bump nodejs

### PR DESCRIPTION
**Pull request by suhan-paradkar**
Update nodejs to latest version... had to update the patches too..

### CODE REVIEW

**Review by xeffyr — CHANGES_REQUESTED** [review]
Keep the patch split on multiple files.

**Comment by suhan-paradkar** [comment]
@xeffyr.. It gives bad register name errors for i686.... and those register errors are specific to ia32(saw it at stackoverflow.. ofcourse)...
Does it mean thaat nodejs now has to be disabled for i686??

**Comment by xeffyr** [comment]
I have disabled it for i686, but let's enable build for x86_64 to see how its status changes by comparing to previous version.

In general, it is preferred to keep popular packages on outdated version rather than disabling for specific arches due to error. Disabling i686 nodejs will most likely lead to complaints from Chromebook people using Termux as development environment.

**Comment by suhan-paradkar** [comment]
I guess chromebook users will have to revert back to nodejs-lts then.....

**Comment by suhan-paradkar** [comment]
Closing as these assembly errors are persistent for arm cpus also....

**Comment by Leif-W** [comment]
Hello.  I came to termux-packages to see if nodejs could be bumped and found this recently closed issue.  I do nit understand the reason.  @suhan-paradkar can you provide the link to StackOverflow for the issue referenced above?  Bad register name errors for i686 specific to ia32?  What is the cause of the errors?  What was done to try to fix this?  Can something else be tried to fix this?  Has this type of error ever occurred on any other package?  If yes, how was that resolved?  Is this possible to update on-device with clang?  The nodejs build docs specifically mention gcc as a requirement.  Is this an actual requirement?  Or is it just an assumed/normative/de-facto standard?  Does gcc generate compatible assembly in this case?  Or is clang known for a fact to be compatible?  I don't care either way, I'm just trying to understand the situation, but using clang would possibly be easier and less error prone if building on device.

**Comment by suhan-paradkar** [comment]
@Leif-W 
>can you provide the link to StackOverflow for the issue referenced above? Bad register name errors for i686 specific to ia32?

Here's one example....
https://stackoverflow.com/questions/33193551/x86-ia32-assembly-bad-register-name

Also... note that there are several other bad registers encountered while compiling....
You can see those in the github action check logs of the above commits....

>Is this possible to update on-device with clang?

I guess that would be possible... but would take a lot of resources... even github actions CI runs out of memory sometimes while building nodejs

>The nodejs build docs specifically mention gcc as a requirement. Is this an actual requirement? Or is it just an assumed/normative/de-facto standard?

That is a requirement of most packages but aince gcc is unsupported, we use clang...

>Does gcc generate compatible assembly in this case? Or is clang known for a fact to be compatible?

About compatibility with gcc in termux...I don't think anyone haas tried it yet....
clang has helped us create so many packages... of course..with its own problems tho

>but using clang would possibly be easier and less error prone 

that is true since we are cross compiling...
I hapo you have got the answers you've been looking for...

**Comment by Leif-W** [comment]
Thank you for the explanations!

> I guess that would be possible... but would take a lot of resources... even github actions CI runs out of memory sometimes while building nodejs

How much memory does the CI have when it runs out?  And how much disk space is required?  My new phone has almost as good specs as my 10-yr old PC, so... :)  There is one way to find out, I guess.

> that is true since we are cross compiling...
> I hapo you have got the answers you've been looking for...

Some answers, and more questions, but thanks for the SO example, now I know where to begin looking.

**Comment by sayantan300** [comment]
I was just searching around the stackoverflow, so I'm wondering whether is this of any help?
https://stackoverflow.com/a/11841965/13712189

**Comment by sayantan300** [comment]
Also I'm wondering, I checked my arm info via this command: `cat /proc/cpuinfo | more` and it showed arm7l,
So can I use this tar file and unzip it to run nodejs v16?
https://nodejs.org/dist/v16.6.2/node-v16.6.2-linux-armv7l.tar.gz

**Comment by xeffyr** [comment]
https://wiki.termux.com/wiki/Differences_from_Linux

Even if youanage to run it, there no guarantee that it will work properly. Termux is not standard Linux distribution, that's a custom userspace for Android.

**Comment by Leif-W** [comment]
@sayantan300 Regarding the file, `'Linux' == 'Android'` but `! 'Linux' === 'Android'`.  Yes, the same core OS source code, but vast differences in file locations, SELinux, tool chains, encironment, etc.  Besides, why ask when you can try it and see?  I tried with the Arm64 aka v8 aka Aarch build, and it immediately exits with a file not found error.

**Comment by sayantan300** [comment]
Eh

**Comment by sayantan300** [comment]
I'm noob when it comes to those parts

**Comment by sayantan300** [comment]
@xeffyr so you're sure I can use nodejs 16 with proot? Lemme try it out and hope it doesn't fills up my storage

**Comment by xeffyr** [comment]
Yes, you should be able to use it under proot. I haven't tried it, but if that's a static binary (and linked with Musl libc, not GNU), `termux-chroot` from  package `proot` should be sufficient. Also you may need `resolv-conf` package installed.

In case if it was linked with GNU libc (no matter statically or not), you will need at least basic installation of Ubuntu or Debian under proot. That's needed because GNU libc splits DNS resolver into separate component often distributed as shared library only.

**Comment by xeffyr** [comment]
I have checked it myself - it won't work in Termux directly even with `termux-chroot`. You need to setup Ubuntu chroot, e. g. with `proot-distro install ubuntu-20. 04` and use node inside this system.

**Comment by sayantan300** [comment]
@xeffyr noice! We can actually run nodejs v16 somehow then!
Maybe you can make docs on how to upgrade nodejs to v16 then 😄

I shall be sharing this with everyone for now!

**Comment by sayantan300** [comment]
@xeffyr noice! We can actually run nodejs v16 somehow then!
Maybe you can make docs on how to upgrade nodejs to v16 then 😄

I shall be sharing this with everyone for now!

**Comment by sayantan300** [comment]
Actually wondering how can I contribute to termux docs so I can add there how to upgrade to nodejs v16 like how you did...

**Comment by xeffyr** [comment]
Actually this isn't upgrading the Termux Node.js but custom installation inside chroot. Termux docs are only about Termux and things officially packaged.

**Comment by sayantan300** [comment]
Oh sorry, but maybe we everyone about this though

**Comment by sayantan300** [comment]
Doesn't work rip

**Comment by Leif-W** [comment]
Also confirmed using proot-distro with ubuntu-21.04, at least `node -v` ran.  Hadn't played with, or realized what proot allowed.  Learned something new, thanks for the tips.

This is almost like a Linux/Android/Termux System for Linux inside Termux inside Android inside Linux (on a phone).  If I tried this level of nesting on my desktop, it would struggle.  Phone seems to handle it ok.

**Comment by xeffyr** [comment]
> If I tried this level of nesting on my desktop, it would struggle.

This isn't nesting. The only overhead there is proot, everything else is just userspace switch (`export PATH=/path/to/dir`) and binaries are executed by Linux directly and not by Android. On desktop system the closest approach would be Docker, even though it works differently from proot.

**Comment by sayantan300** [comment]
Yay I finally installed it on my mobile!
Btw, the distros of proot are a lot bigger than the anlinux ones, so I found that proot-distros also have some problem with sudo stuff and it installs some packages from start too, making it 2x times larger. Maybe you can remove those useless stuff like neofetch etc, and let users install it themselves?

**Comment by suhan-paradkar** [comment]
Currently about nodejs16... Its stuck at v8.. which is a depenency and is causing the assembly errors...

**Comment by Leif-W** [comment]
@suhan-paradkar Is it something that was fixed upstream?  Obviously, Node.js and V8 engine has been compiled successfully on ARM v7 and ARMv8, because it runs just fine on ARMv7 and ARMv8 using proot as demonstrated here.

**Comment by suhan-paradkar** [comment]
@Leif-W 
Well.. further digging into the issue showed that the issue is with the incorrect identification of cpu arch by the bundled v8 in nodejs...
Thats why currently work is in progress in compiling v8 into termux after which we may bump nodejs using prebuilt v8

**Comment by Yonle** [comment]
> @suhan-paradkar Is it something that was fixed upstream?  Obviously, Node.js and V8 engine have been compiled successfully on ARMv7 and ARMv8, because it runs just fine on ARMv7 and ARMv8 using proot as demonstrated here.

Please. https://wiki.termux.com/wki/Difference_of_linux

**Comment by thunder-coding** [comment]
About a seperate V8 package, the progress can be seen in #7290

**Comment by Leif-W** [comment]
> > @suhan-paradkar Is it something that was fixed upstream?  Obviously, Node.js and V8 engine have been compiled successfully on ARMv7 and ARMv8, because it runs just fine on ARMv7 and ARMv8 using proot as demonstrated here.
> 
> Please know the [Differences from Linux](https://wiki.termux.com/wiki/Differences_from_Linux).

I know the differences.  I've used Linux 25+ years.  V8 compiles and runs on ARM, so it's not a problem with code or assembly or registers.  It is a problem with paths, tools, detection, configuration.

**Pull request closed without merging**
