### PR TITLE
new package : libebur

### PR DESCRIPTION
**Pull request by mjuned47**
Dependency of Easy effects #10417

### CODE REVIEW

**Comment by xtkoba** [comment]
* Wrong license.

* Remove `TERMUX_PKG_REVISION` for initial packaging.

**Comment by mjuned47** [comment]
How to determine correct licence?

**Comment by xtkoba** [comment]
Read the documents (typically `README` or `LICENSE` or `COPYRIGHT` or something) in the tarball for the license.

**Comment by xtkoba** [comment]
Also I would say it is not a good practice submitting a PR associated with the main branch.

**Comment by xtkoba** [comment]
`itstool` is installable through `pip`, and is not a run-time dependency of `easyeffects`. We won't package it.

**Comment by xtkoba** [comment]
Package name `libebur128` is suggested. Note that `128` is not a version number.

**Comment by xtkoba** [comment]
The libgcc hack in `termux_step_pre_configure()` should not be needed (though not harmful). It is for libtool (autoconf), whereas `libebur128` adopts CMake.

**Review by xtkoba — APPROVED** [review]

**Review by xtkoba — CHANGES_REQUESTED** [review]
Don't touch the workflows.

**Comment by xtkoba** [comment]
Merged as commit ec1b01703503859cbf761deaa9a81029786cdd9a.

**Comment by mjuned47** [comment]
> Don't touch the workflows.

Sorry this was perticular for my repo 
Btw 
Can you help me for this :
If there is new package that i want to build with my

**Pull request closed without merging**
