### PR TITLE
openjpeg: disable static libs

### PR DESCRIPTION
**Pull request by tomty89**
Probably prerequisite of #3396.

### CODE REVIEW

**Comment by Grimler91** [comment]
Weird build error, I suppose `-DBUILD_STATIC_LIBS=OFF` disabled all libraries for some reason

**Comment by tomty89** [comment]
```
[30/49] Linking C shared library bin/libopenjp2.so[K
[31/49] Linking C shared library bin/libopenjp2.so[K
```
Looks like it has gone to bin/ somehow

**Comment by tomty89** [comment]
It still links to bin/ but now
```
-- Installing: /data/data/com.termux/files/usr/lib/libopenjp2.so
```
So it worked

**Comment by Grimler91** [comment]
> It still links to bin/ but now

We probably want to unlink that if it still happens, don't you think? 
(in termux_step_post_make_install or so)

**Comment by tomty89** [comment]
Uhm I don't think the bin is the same bin of the final destination.

**Comment by fornwall** [comment]
The updated package is now available for installation.

**Pull request merged**
