### PR TITLE
update profanity to 0.6.0

### PR DESCRIPTION
**Pull request by Neo-Oli**

### CODE REVIEW

**Comment by Grimler91** [comment]
@Neo-Oli I opened a PR against your branch with some dependencies to make travis succeed

**Comment by Neo-Oli** [comment]
@Grimler91 I merged your PR. Thanks. Is there a particular way you figured out which dependencies are missing?

**Comment by Grimler91** [comment]
@Neo-Oli basically 

- building with -i
- looking at the errors in the config.log file
- adding some package as dependency
- repeat until build succeeds

**Comment by fornwall** [comment]
Thanks! The updated package is now available for installation.

**Pull request merged**
