### PR TITLE
build-bootstraps: bump to 0.2.0

### PR DESCRIPTION
**Pull request by truboxl**
Part of an initiative from https://github.com/termux/termux-packages/discussions/8927

* add support building for ARM without Neon
* add support building additional packages first

Note that not all packages currently can be built without problems, notably ffmpeg and its deps. Have to delve deeper separately.

### CODE REVIEW

**Comment by truboxl** [comment]
CC @agnostic-apollo as well for review

**Comment by agnostic-apollo** [comment]
Seems fine otherwise from an overlook. This won't affect normal builds, so have you ensured that reversal with `sed` is working fine for you?

And ideally, version bump commit should be separate from code change commits themselves.

**Comment by Grimler91** [comment]
Maybe add a comment in the bootstrap script or ffmpeg and deps' build.sh that they cannot be built without neon. Does the build of those packages just fail, or do they give an error when run on device?

**Comment by MohammadTariq13** [comment]
I can't open Termux in Samsung galaxy J7 prime
It shows bootstrap was enable

**Pull request closed without merging**
