### PR TITLE
fix(main/samba): disable root only check log size

### LINKED ISSUE #21899: [Bug]: Samba server won't honnor max log file = 50
### Problem description

This morning I find my phone is out of storage.
du -a .| sort -nr| head -n20 ran from com.termux/files dir shows the culprit is usr/var/log/samba/log.smbd (190GB)

Removed then restarting some crashed apps and everything seems OK.

### What steps will reproduce the bug?

I imagine maybe just restart smbd -i and let run until phone turns into sleep mode or something similar, because I saw twice the termux screen spitting error messages I couldn't stop (Ctrl+C did not work) and I had to force-kill from Android Settings Application

### What is the expected behavior?

Don't fill the storage, respect the directive

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=15607
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
c-ares/stable 1.34.2 aarch64 [upgradable from: 1.34.1]
command-not-found/stable 2.4.0-47 aarch64 [upgradable from: 2.4.0-45]
libnettle/stable 3.10 aarch64 [upgradable from: 3.9.1]
libssh2/stable 1.11.1 aarch64 [upgradable from: 1.11.0]
libtirpc/stable 1.3.6 aarch64 [upgradable from: 1.3.5]
libunbound/stable 1.22.0 aarch64 [upgradable from: 1.21.1-1]
libunistring/stable 1.3 aarch64 [upgradable from: 1.1]
termux-am/stable 0.8.0-1 all [upgradable from: 0.8.0]
termux-tools/stable 1.44.1 aarch64 [upgradable from: 1.43.6]
termux-tools version:
1.43.6
Android version:
14
Kernel build information:
Linux localhost 5.4.242-qgki-g3f7ff67280a0 #1 SMP PREEMPT Fri Jul 5 16:49:09 CST 2024 aarch64 Android
Device manufacturer:
Nothing
Device model:
A063
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
```

### PR DESCRIPTION
**Pull request by truboxl**
Fix #21899

### CODE REVIEW

**Review by TomJo2000 — APPROVED** [review]
LGTM.

I assume this is ready to merge?

**Comment by truboxl** [comment]
I think should be fine to merge unless @bugith has any last minute issue

**Comment by truboxl** [comment]
I will merge this in and move on to #22501

**Comment by bugith** [comment]
Hi @truboxl & @bigbio2002 & @TomJo2000 
It seems we have other samba package issues around running as root or not-root/termux user:
https://github.com/termux/termux-packages/issues/22501
https://github.com/termux/termux-packages/issues/22933

**Pull request merged**
