### PR TITLE
libicu: revbump revdeps (11)

### PR DESCRIPTION
**Pull request by licy183**

### CODE REVIEW

**Comment by licy183** [comment]
Seems a bug of clang.

Ping @finagolfin as the maintainer of swift

**Comment by finagolfin** [comment]
Hmm, the NDK 27b clang is crashing when cross-compiling a C++ source file in the Swift compiler: can you try applying the 27c patches from your #21920 to this pull and see if it's fixed in the latest NDK?

The good news is that I plan to update to Swift 6.0 this week, which ships with its own vendored libicu and will remove this dependency on the Termux libicu.

**Comment by licy183** [comment]
Actually packages in `big-pkg.list` will use Android NDK provided by GitHub Action...

https://github.com/termux/termux-packages/blob/eef638de3cc9c6c7366d8e0b7bf69a41ed9d718d/.github/workflows/packages.yml#L219

**Comment by finagolfin** [comment]
[Github runners are still using NDK 27b](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#environment-variables-2): they've delayed updating. You could download 27c in the CI runner and try using it with your pull, [as I do on my Swift CI](https://github.com/finagolfin/swift-android-sdk/blob/c397007a5a4d1baa28b3079b653c2bd7965f973b/.github/workflows/sdks.yml#L86).

**Comment by licy183** [comment]
Emmm... It still can't pass the CI...

**Comment by finagolfin** [comment]
OK, add [this source mod before compiling, as I do on my CI](https://github.com/finagolfin/swift-android-sdk/blob/main/.github/workflows/sdks.yml#L234). You can do it in our Termux build script, right before the Swift `build-script` is invoked.

**Comment by finagolfin** [comment]
I have [submitted that change upstream](https://github.com/swiftlang/swift/pull/76460/files#diff-e2e2a250882f66d531f2a42c201e013fa2d8be892b2880a32d6596710761f470), should be the only one needed for 5.10.

**Comment by finagolfin** [comment]
Yep, I'm seeing this crash when cross-compiling the Swift 6 compiler with NDK 27b also, simply swapping the `clang-18` from NDK 27c into the cached Termux NDK 27b toolchain fixed it for me.

I think we should get your 27c pull in first before moving forward with this libicu bump.

**Pull request closed without merging**
