### PR TITLE
bump(main/bash): 5.2.32

### PR DESCRIPTION
**Pull request by TomJo2000**
and set a maintainer.

### CODE REVIEW

**Review by fornwall — APPROVED** [review]
👍 Looks good, have smoke tested it by running it locally and run various bash shell scripts, and looked through the patches:

- https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-027
- https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-028
- https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-029
- https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-030
- https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-031
- https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-032

**Comment by TomJo2000** [comment]
Haven't found any issues with in smoke testing either.

Arch Linux does ship a couple memory leak patches,
though I'm not sure how severe those are.
https://gitlab.archlinux.org/archlinux/packaging/packages/bash/-/blob/main/bash-5.2_p32-memory-leaks.patch?ref_type=heads

**Comment by fornwall** [comment]
> Arch Linux does ship a couple memory leak patches, though I'm not sure how severe those are. https://gitlab.archlinux.org/archlinux/packaging/packages/bash/-/blob/main/bash-5.2_p32-memory-leaks.patch?ref_type=heads

Doesn't look like too serious issues - can IMHO be updated in a separate PR if we decide to take them in before they are fixed upstream.

**Comment by TomJo2000** [comment]
That was my assessment as well, just wanted a second opinion on it before merging.

**Pull request merged**
