### PR TITLE
Added some generic configs for vim.

### PR DESCRIPTION
**Pull request by GreenJoey**
Added thae standard Vim config that is done on the Debian System. 

- [ ]

### CODE REVIEW

**Comment by fornwall** [comment]
Right, the vim packages had some vim settings put together ad-hoc by myself, which was recently removed due to some complaints.

The proposed config here should be more safe than the previous one, as it doesn't do as much and should be common if Debian does it.

Are they still needed on vim 8 - I thought vim 8 improved default config a bit?

**Comment by natebass** [comment]
I'm not sure if we should merge this; Termux might want to a different default than debian. Specifically, line numbers off is kind of nice for a small phone screen. @GreenJoey What do you think?

**Comment by natebass** [comment]
@fornwall 
https://github.com/vim/vim/blob/master/runtime/doc/version8.txt#L416-L429
>Better defaults without a vimrc ~
>
>When no vimrc file is found, the |defaults.vim| script is loaded to set more
>useful default values for new users.  That includes setting 'nocompatible'.
>Thus Vim no longer starts up in Vi compatible mode.  If you do want that,
>ither create a .vimrc file that does "set compatible" or start Vim with
>"Vim -C".

So if the user has no vimrc then it loads https://github.com/vim/vim/blob/master/runtime/doc/version8.txt#L416-L429

**Comment by fornwall** [comment]
@natebass Aha, thanks! So it's still needed to avoid turning everything off when a .vimrc file is found.

What about https://github.com/tpope/vim-sensible, the file at https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim? I guess that could be a modern sensible setup to include as the system vim config in Termux, to make vim as friendly as possible for newcomers?

**Comment by GreenJoey** [comment]
@notebass line numbers are help full when editing code.. I feel so...

**Comment by fornwall** [comment]
The latest vim package now uses [sensible.vim](https://github.com/tpope/vim-sensible) as the system vimrc - let me know if that causes any issue!

**Pull request closed without merging**
