### PR TITLE
add llvm subpackage clang-tidy

### PR DESCRIPTION
**Pull request by ifurther**
#5381

it has clang-tidy , but it includes in clang package.
./data/data/com.termux/files/usr/bin/clang-tidy

### CODE REVIEW

**Comment by xeffyr** [comment]
It includes clang-tidy into clang because of packaging order. Clang subpackage needs fix or I guess we can remove clang-tidy subpackage at all.

**Comment by xeffyr** [comment]
clang-tidy is now part of `clang` package because of dependency.

**Comment by Wetitpig** [comment]
@xeffyr Do you mean that `clang` is a dependency of `clang-tidy`?
And also all `clang-tools`?
Thanks

**Comment by ifurther** [comment]
I think @xeffyr mean clang-tidy dependency clang, and clang-tidy is a tool for clang.

**Comment by xeffyr** [comment]
Debian dependency graph for clang-tidy (quite unexpected, isn't it?): 
clang-tidy-deps

Why clang-tidy relies on clang? At least for compiler-specific headers located at
```
/data/data/com.termux/files/usr/lib/clang/9.0.1/include
```

With no clang:
```
~ $ clang-tidy test.c
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "test.c"
No compilation database found in /data/data/com.termux/files/home or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
1 error generated.
Error while processing /data/data/com.termux/files/home/test.c.
/data/data/com.termux/files/usr/include/sys/types.h:32:10: error: 'stddef.h' file not found [clang-diagnostic-error]
#include <stddef.h>
         ^
Found compiler error(s).
```

And with clang:
```
~ $ clang-tidy test.c
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "test.c"
No compilation database found in /data/data/com.termux/files/home or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
```

**Comment by xeffyr** [comment]
I also should note that in future all Termux packages will be *unsplitted* to assist new packaging way https://github.com/termux/termux-app/pull/1427.

**Pull request merged**
