### PR TITLE
Update to ndk r25b

### LINKED ISSUE #11771: [Information]: Android NDK r25b has released
https://github.com/android/ndk/wiki/Changelog-r25.
So should we update?

### PR DESCRIPTION
**Pull request by licy183**
Also re-add `$TERMUX_HOST_PLATFORM-cpp`. Closes #11771.

### CODE REVIEW

**Comment by licy183** [comment]
Forget to add a space between `-E` and `--target`...
```
#!/bin/bash
bin_dir=`dirname "$0"`
if [ "$1" != "-cc1" ]; then
    "$bin_dir/clang" -E--target=aarch64-linux-android24 "$@"
else
    # Target is already an argument.
    "$bin_dir/clang" -E"$@"
fi
```

**Comment by tomty89** [comment]
But
```
's|"$bin_dir/clang"|"$bin_dir/clang" -E|'
```
should do? Or even
```
's|"$bin_dir/clang"|& -E|'
```

Not that it matters much though.

**Comment by licy183** [comment]
> But
> 
> ```
> 's|"$bin_dir/clang"|"$bin_dir/clang" -E|'
> ```
> 
> should do? Or even
> 
> ```
> 's|"$bin_dir/clang"|& -E|'
> ```
> 
> Not that it matters much though.

Thanks! Fixed now.

**Comment by licy183** [comment]
I have just tested building `rust` with NDK r25b and it doesn't work either. We may update libllvm to 15 later and it will break rust because it depends on `libllvm`. Should we add a function like `termux_setup_gnu_as_23c` to make it possible for `packages/xxx/build.sh` to override the building toolchain?

**Comment by Grimler91** [comment]
> Should we add a function like `termux_setup_gnu_as_23c` to make it possible for `packages/xxx/build.sh` to override the building toolchain?

I don't think that is a good idea, opening up for different packages to use different ndk versions will surely lead to issues sooner or later since ndk headers are (somewhat) ndk specific. 

We™ should try to investigate the rust issue first. A gdb/lldb backtrace and/or logcat output with or without a debug build of rust would be useful (I'll have a look at fixing the pkg-config error now again, and then the arm error)

**Comment by Grimler91** [comment]
This PR looks good to me otherwise, and build works with CPP wrapper again, so feel free to drop that test commit

**Pull request merged**
