### PR TITLE
picom: Bump to 10.1

### PR DESCRIPTION
**Pull request by xtkoba**
* Disable OpenGL support now that it requires EGL.

### CODE REVIEW

**Comment by xtkoba** [comment]
Ah, maybe EGL can be enabled after #13809?

**Comment by licy183** [comment]
> Ah, maybe EGL can be enabled after #13809?

I will have a local test this night (GMT+8).

Anyway, I think making a package depend on the current `mesa` package is ambiguous. It doesn't show clearly which libraries they really depend on (libGLESv1, libGLESv2 or OSMesa). Should we spilt the packages as [`debian`](https://packages.debian.org/source/sid/mesa) or [`archlinux`](https://github.com/archlinux/svntogit-packages/tree/packages/mesa/trunk) do?

**Comment by xtkoba** [comment]
Please open new issue(s) if further discussion is needed. This is not the right place for that.

**Comment by xtkoba** [comment]
Closing as I am not the right person to bump this package. Thanks.

**Pull request closed without merging**
