### PR TITLE
add tcsh

### LINKED ISSUE #1342: Package request: tcsh
Tcsh

C shell with file name completion and command line editing

https://github.com/tcsh-org/tcsh
https://wiki.termux.com/wiki/Main_Page#Init_Files
https://www.google.com/search?q=popular+unix+shells
screenshot_20170902-011723

### PR DESCRIPTION
**Pull request by stephengroat**
closes #1342

### CODE REVIEW

**Comment by Auxilus** [comment]
Awesome work @stephengroat!!

**Comment by fornwall** [comment]
Thanks - the package is now available for installation!

**Comment by sdrausty** [comment]
Great work! Thank you!
```
$ tcsh
> echo "Hello, World!"
Hello, World!
```

**Comment by stephengroat** [comment]
@sdrausty perfect. glad everything works well. if you find issues (i didn't do exhaustive testing, just a little bit) open an issue and i'll try to address it

**Pull request merged**
