### PR TITLE
bump(main/sqlcipher): 4.5.7

### LINKED ISSUE #19925: Auto update failing for sqlcipher
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [sqlcipher](https://github.com/termux/termux-packages/blob/b974cd3a47523ee35a2858760f243e9d07c74cd4/packages/sqlcipher) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating sqlcipher [Current version: 4.5.6]
INFO: package being updated to 4.5.7.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 9680k    0 9680k    0     0  9780k      0 --:--:-- --:--:-- --:--:-- 9780k
100 14.9M    0 14.9M    0     0  7391k      0 --:--:--  0:00:02 --:--:-- 5204k
100 18.1M    0 18.1M    0     0  7053k      0 --:--:--  0:00:02 --:--:-- 5410k

You are about to commit these changes:

--------------------
diff --git a/packages/sqlcipher/build.sh b/packages/sqlcipher/build.sh
index 320112724..78148d9b4 100644
--- a/packages/sqlcipher/build.sh
+++ b/packages/sqlcipher/build.sh
@@ -2,9 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://github.com/sqlcipher/sqlcipher
 TERMUX_PKG_DESCRIPTION="SQLCipher is an SQLite extension that provides 256 bit AES encryption of database files"
 TERMUX_PKG_LICENSE="BSD"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="4.5.6"
+TERMUX_PKG_VERSION="4.5.7"
 TERMUX_PKG_SRCURL=https://github.com/sqlcipher/sqlcipher/archive/v$TERMUX_PKG_VERSION.tar.gz
-TERMUX_PKG_SHA256=e4a527e38e67090c1d2dc41df28270d16c15f7ca5210a3e7ec4c4b8fda36e28f
+TERMUX_PKG_SHA256=b670845f28da0a3c717e991e9f18a334e08f6bc977190bbce6be864ca229f96d
 TERMUX_PKG_DEPENDS="libedit, openssl"
 TERMUX_PKG_BUILD_DEPENDS="tcl"
 TERMUX_PKG_AUTO_UPDATE=true
--------------------

bump(main/sqlcipher): 4.5.7

Not committing to Git!

INFO: Trying to build package.
INFO: Package sqlcipher exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building sqlcipher for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  19680      0 --:--:-- --:--:-- --:--:-- 19691
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1949      0 --:--:-- --:--:-- --:--:--  1946
100   833  100   833    0     0   1949      0 --:--:-- --:--:-- --:--:--  1946
gpg: Signature made Wed 24 Apr 2024 06:13:07 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/main/binary-aarch64/Packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  4 1576k    4 71880    0     0  90744      0  0:00:17 --:--:--  0:00:17 90643
100 1576k  100 1576k    0     0  1260k      0  0:00:01  0:00:01 --:--:-- 1260k
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  31201      0 --:--:-- --:--:-- --:--:-- 31267
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   4589      0 --:--:-- --:--:-- --:--:--  4576
100   833  100   833    0     0   4586      0 --:--:-- --:--:-- --:--:--  4576
gpg: Signature made Sat 20 Apr 2024 12:39:53 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  30688      0 --:--:-- --:--:-- --:--:-- 30725
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1927      0 --:--:-- --:--:-- --:--:--  1923
100   833  100   833    0     0   1927      0 --:--:-- --:--:-- --:--:--  1923
gpg: Signature made Wed 24 Apr 2024 07:32:19 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency libandroid-support@28-3 if necessary...
Found libandroid-support in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libandroid-support to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses@6.4.20231001-3 if necessary...
Found ncurses in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-utils@6.4.20231001-3 if necessary...
Found ncurses-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs@6.4.20231001-3 if necessary...
Found ncurses-ui-libs in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-ui-libs to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs-static@6.4.20231001-3 if necessary...
Found ncurses-ui-libs-static in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-ui-libs-static to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libedit@20221030-3.1-0 if necessary...
Found libedit in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libe/libedit/libedit_20221030-3.1-0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 77692  100 77692    0     0  1173k      0 --:--:-- --:--:-- --:--:-- 1167k
extracting libedit to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ca-certificates@1:2024.03.11-2 if necessary...
Found ca-certificates in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ca-certificates to /home/builder/.termux-build/_cache-all...
Downloading dependency ca-certificates-java@1:2024.03.11-2 if necessary...
Found ca-certificates-java in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ca-certificates-java to /home/builder/.termux-build/_cache-all...
Downloading dependency zlib@1.3.1 if necessary...
Found zlib in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting zlib to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openssl@1:3.2.1-1 if necessary...
Found openssl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting openssl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openssl-tool@1:3.2.1-1 if necessary...
Found openssl-tool in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting openssl-tool to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency tcl@8.6.14 if necessary...
Found tcl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/tcl/tcl_8.6.14_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2209k  100 2209k    0     0  20.5M      0 --:--:-- --:--:-- --:--:-- 20.7M
extracting tcl to /home/builder/.termux-build/_cache-aarch64...
Downloading https://github.com/sqlcipher/sqlcipher/archive/v4.5.7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 6211k    0 6211k    0     0  7182k      0 --:--:-- --:--:-- --:--:-- 7182k
100 14.4M    0 14.4M    0     0  7871k      0 --:--:--  0:00:01 --:--:-- 8463k
100 18.1M    0 18.1M    0     0  7094k      0 --:--:--  0:00:02 --:--:-- 7053k
Applying patch: android_log.patch
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
1 out of 1 hunk ignored -- saving rejects to file src/crypto.h.rej
3 out of 3 hunks FAILED -- saving rejects to file src/crypto_impl.c.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-04-24 18:13:58 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/8821176056">8821176056</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by tqfx**
Close #19925

### CODE REVIEW

**Comment by truboxl** [comment]
I believe the patch was added so that you don't have to pull up a logcat to see errors

**Comment by tqfx** [comment]
> I believe the patch was added so that you don't have to pull up a logcat to see errors

The previous patch only deleted the android-log part. android_log can now be disabled by defining SQLCIPHER_OMIT_LOG_DEVICE.

**Comment by truboxl** [comment]
We prefer logging to console. See https://github.com/termux/termux-packages/pull/19491

**Comment by truboxl** [comment]
Thanks!

**Pull request merged**
