### PR TITLE
libcompiler-rt: Add hook for ndk-multilib

### LINKED ISSUE #10526: [Bug]: clang and ndk-multilib conflicts?
### Problem description

I tried usual pkg update and it stuck with
```
Preparing to unpack .../archives/clang_14.0.3_arm.deb ...
Unpacking clang (14.0.3) over (14.0.1) ...
dpkg: error processing archive /data/data/com.termux/cache/apt/archives/clang_14.0.3_arm.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/lib/clang/14', which is also in package ndk-multilib 23b-4
Errors were encountered while processing:
 /data/data/com.termux/cache/apt/archives/clang_14.0.3_arm.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
$

```

### What steps will reproduce the bug?

pkg up

### What is the expected behavior?

update successfull

### System information

termux-info:

```
$ termux-info
Termux Variables:
unsupported
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.org/apt/termux-x11 x11 main
Updatable packages:
clang/stable 14.0.3 arm [upgradable from: 14.0.1]
mc/stable 4.8.27-4 arm [upgradable from: 4.8.25-3]
Android version:
10
Kernel build information:
Linux localhost 4.14.141+ #1 SMP PREEMPT Tue Mar 8 11:58:12 CST 2022 armv8l Android
Device manufacturer:
HUAWEI
Device model:
KOB2-L09
```

### PR DESCRIPTION
**Pull request by xtkoba**
Closes #10526.

### CODE REVIEW

**Comment by buttaface** [comment]
I think we should just make `libcompiler-rt` ship all of these other arches' libraries too and ditch this symlink approach altogether. That will make that package fatter- [from 1-2 MB to 5-10 MB](https://packages-cf.termux.org/apt/termux-main/pool/main/libc/libcompiler-rt/)- but avoid all these symlinks.

What do you think, @Grimler91?

**Comment by xtkoba** [comment]
@buttaface

> I think we should just make `libcompiler-rt` ship all of these other arches' libraries too and ditch this symlink approach altogether. That will make that package fatter- [from 1-2 MB to 5-10 MB](https://packages-cf.termux.org/apt/termux-main/pool/main/libc/libcompiler-rt/)- but avoid all these symlinks.

Yeah, that would be acceptable to me. Then please close #10538 (which is totally unacceptable) and propose a new PR. Thanks!

**Comment by buttaface** [comment]
I just tested #10538 and I think it will work well, what do you find wrong with it?

This approach may work too, but I have not tested it, have you?

**Comment by xtkoba** [comment]
Yes, mine works as expected. Try the following command sequence:

```bash
dpkg -i libllvm_14.0.3-1_aarch64.deb libcompiler-rt_14.0.3-1_aarch64.deb
apt install -f
dpkg -i ndk-multilib_23b-6_all.deb
```

The hook is triggered and the symlinks are created as expected:

```
~ $ dpkg -i ndk-multilib_23b-6_all.deb
Selecting previously unselected package ndk-multilib.
(Reading database ... 7088 files and directories currently installed.)
Preparing to unpack ndk-multilib_23b-6_all.deb ...
Unpacking ndk-multilib (23b-6) ...
Setting up ndk-multilib (23b-6) ...
Processing triggers for libcompiler-rt (14.0.3-1) ...
~ $
```

**Comment by buttaface** [comment]
What if you then uninstall libcompiler-rt then sometime later uninstall ndk-multilib, will the symlinks be left behind? Or if they're removed, when are they removed?

**Comment by xtkoba** [comment]
Note that this hook must belong to `libcompiler-rt`, not `clang`. Because `clang` does not have the directory `lib/clang/14.0.3/lib/linux/`.

**Comment by xtkoba** [comment]
Why don't you try yourself? When `libcompiler-rt` is uninstalled the symlinks are removed as per `prerm`.

**Comment by buttaface** [comment]
> Note that this hook must belong to libcompiler-rt, not clang. Because clang does not have the directory lib/clang/14.0.3/lib/linux/

That may be true here, but I was asking about #10538 which uses the symlink `lib/clang/14/` instead, so that the current ndk-multilib symlinks won't depend on clang patch version bumps, and that directory symlink is installed by the clang package, so clang is the right dependency for #10538.

> Why don't you try yourself?

I don't want to download a 150 MB zip file just to run a few commands.

> When libcompiler-rt is uninstalled the symlinks are removed as per prerm.

OK, that means ndk-multilib will no longer work properly if libcompiler-rt is removed, which is a problem with this pull.

I currently favor #10538, as

1. It keeps the non-host compiler-rt libraries and symlinks as part of ndk-multilib, where they belong.
2. It depends on `clang`, which is the right dependency for that pull.
3. It should fix most of these installation issues, though I'm not sure if it catches them all.

You may be able to better this pull a little by making libcompiler-rt a dependency of ndk-multilib here, but that is a workaround for this artificial situation of putting ndk-multilib symlinks in libcompiler-rt.

**Comment by xtkoba** [comment]
> OK, that means ndk-multilib will no longer work properly if libcompiler-rt is removed, which is a problem with this pull.

This does not make sense to me. What situation do you assume?

**Comment by xtkoba** [comment]
The problem of #10538 is that it does not support multiple versions of Clang/LLVM. Yes we do not and will not package two versions simultaneously. But it should be allowed for third-party repos. Users should be allowed to use a lower version of Clang/LLVM and yet install our official `ndk-multilib`.

**Comment by buttaface** [comment]
> This does not make sense to me. What situation do you assume?

The symlinks would be removed when libcompiler-rt is removed, so the still installed ndk-multilib libraries would no longer have symlinks in a directory where they'd be found by a compiler.

> The problem of https://github.com/termux/termux-packages/pull/10538 is that it does not support multiple versions of Clang/LLVM.

I don't think that's something we have to worry about, plus since this pull installs symlinks in `lib/clang/14.0.3/` only, it will not support other clang versions either.

**Comment by xtkoba** [comment]
> The symlinks would be removed when libcompiler-rt is removed, so the still installed ndk-multilib libraries would no longer have symlinks in a directory where they'd be found by a compiler.

Such a compiler should either depend on `libcompiler-rt` or have its own hook.


> I don't think that's something we have to worry about, plus since this pull installs symlinks in lib/clang/14.0.3/ only, it will not support other clang versions either.

Not only in `lib/clang/14.0.3/`. For example, `libcompiler-rt-13` that `clang-13` depends on is able to have a hook that populates symlinks in `lib/clang/13.0.1/`.

**Comment by xtkoba** [comment]
IMO, ideally `libllvm` package should build its own version of compiler-rt libraries for all 4 architecutures. Is it impossible?

**Comment by buttaface** [comment]
> Such a compiler should either depend on libcompiler-rt or have its own hook.

That would work, but is more work than just keeping everything in ndk-multilib.

> Not only in lib/clang/14.0.3/. For example, libcompiler-rt-13 that clang-13 depends on is able to have a hook that populates symlinks in lib/clang/13.0.1/.

Sure, and you could set up something similar externally to get ndk-multilib working with clang-13 under my original approach in #10538 too, so both our approaches would require external workarounds to accommodate a clang-13.

**Comment by buttaface** [comment]
> IMO, ideally libllvm package should build its own version of compiler-rt libraries for all 4 architecutures. Is it impossible?

I don't know.

**Comment by Grimler91** [comment]
Upgrading from either `{llvm 14.0.1, ndk-multilib 23b-4}` or `{llvm 14.0.3, ndk-multilib 23b-5}` to the debs in this PR both works fine, so this PR looks good to me

**Review by Grimler91 — APPROVED** [review]

**Pull request merged**
