### PR TITLE
Update lua lsp

### PR DESCRIPTION
**Pull request by MrAdityaAlok**

### CODE REVIEW

**Comment by MrAdityaAlok** [comment]
@thunder-coding please merge this.

**Review by thunder-coding — CHANGES_REQUESTED** [review]
Bump revision. 

And also squash your commits and rebase against master instead of merging the master branch (It causes troubled while building on master branch but not on PRs)

**Comment by MrAdityaAlok** [comment]
> Bump revision.
> 
> And also squash your commits and rebase against master

Ok, doing...

**Comment by MrAdityaAlok** [comment]
@thunder-coding done.

**Comment by thunder-coding** [comment]
> @thunder-coding done.

You forgot to bump revision

**Review by thunder-coding — APPROVED** [review]

**Comment by MrAdityaAlok** [comment]
> > @thunder-coding done.
> 
> You forgot to bump revision

Oh!. Did it.

**Pull request merged**
