### PR TITLE
Add libass and enable libass support in ffmpeg

### PR DESCRIPTION
**Pull request by Hax4us**

### CODE REVIEW

**Comment by Hax4us** [comment]
https://github.com/termux/termux-packages/issues/2399

**Comment by Hax4us** [comment]
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

What's wrong ?

**Comment by Hax4us** [comment]
Btw build was successful but this error is coming while `make install`

**Comment by seisdr** [comment]
Hmm

**Comment by seisdr** [comment]
How to install freetype2

**Comment by xeffyr** [comment]
https://github.com/termux/termux-packages/commit/58f641f5ed148279a6b7a2f0f4fad5df9b0b84d3

**Pull request closed without merging**
