### PR TITLE
addpkg(main/seanime): 2.1.1

### PR DESCRIPTION
**Pull request by aicynide**
closes: https://github.com/termux/termux-packages/issues/21331

### CODE REVIEW

**Comment by TomJo2000** [comment]
Who is @johan0021 and why is that account listed as the commit author of your PR?

**Comment by TomJo2000** [comment]
Oh well.

**Comment by 2096779623** [comment]
> Seriously its github bug I set name as "Name" using git `git config --global user.name "Name"` Email `git config --global user.email "name123@123.com`

You should remove the `--global` parameter, global variables will not be applied to the .git repository that has been set.

**Comment by TomJo2000** [comment]
I have been handling the supervision of this PR, and I simply had not gotten around to doing a final review after your previous comment.

---

As a brief aside I would like to make it crystal clear that all the maintainers and contributors to Termux are unpaid volunteers.
Your Pull Request will be reviewed, evaluated, and merged or denied when a member of the package maintenance team takes the time to do so.
We have no contractual, legal or monetary obligations to you as the author of this pull request,
and neither do you have the above mentioned obligations towards the Termux project and its maintainers in turn.
Complaining will not effectuate faster review, we're only human.

**Review by TomJo2000 — APPROVED** [review]
Looks fine to me.
I will be taking out the changes to `termux_setup_nodejs.sh` as Node 18.17.0 is not the current release of Node 18.x
- That being [18.20.4](https://github.com/nodejs/node/releases/tag/v18.20.4) currently.

Updating the version in the node setup function can be done in a separate PR and will require additional testing and validation which would block merging this PR.

**Comment by TomJo2000** [comment]
Even managed to fixup the commit authorship.

**Pull request merged**
