### PR TITLE
termux-tools: Add NYIST mirror and add #10652 to pkg

### LINKED ISSUE #10714: [New Mirror] NYIST
|  Repository   | sources.list entry  |
|  ----  | ----  |
| [Main](https://github.com/termux/termux-packages)  | `deb https://mirror.nyist.edu.cn/termux/apt/termux-main stable main` |
| [Root](https://github.com/termux/termux-root-packages)  | `deb https://mirror.nyist.edu.cn/termux/apt/termux-root root stable` |
| [X11](https://github.com/termux/x11-packages)  |`deb http://mirror.nyist.edu.cn/termux/apt/termux-x11 x11 main` |

The mirror from Nanyang Institute of Technology,Supports IPV4 and IPV6.

### PR DESCRIPTION
**Pull request by 2096779623**
closes #10714.

#10652 's repo hosted in AWS in Mumbai, India,so I think it should be added to the timeout test list.

@Grimler91 Please add mirrors for #10696 and mirrors for #10714 to the [wiki page](https://github.com/termux/termux-packages/wiki/Mirrors), thanks!

### CODE REVIEW

**Comment by guesmib771** [comment]
https://www.facebook.com/profile.php?id=100009507615598

**Comment by 2096779623** [comment]
> https://www.facebook.com/profile.php?id=100009507615598

@xtkoba

**Comment by xtkoba** [comment]
See discussion in https://github.com/termux/termux-packages/pull/9553#discussion_r834899388 (only login users can see this.)

Align the indentation with other lines. `termux-change-repo` uses 4 spaces. There are cases where <a href="https://github.com/termux/termux-packages/wiki/Coding-guideline">Coding guideline</a> should not be applied.

**Comment by 2096779623** [comment]
> See discussion in [#9553 (comment)](https://github.com/termux/termux-packages/pull/9553#discussion_r834899388) (only login users can see this.)
> 
> Align the indentation with other lines. `termux-change-repo` uses 4 spaces. There are cases where [Coding guideline](https://github.com/termux/termux-packages/wiki/Coding-guideline) should not be applied.

Fixed.

**Comment by 2096779623** [comment]
> See discussion in [#9553 (comment)](https://github.com/termux/termux-packages/pull/9553#discussion_r834899388) (only login users can see this.)
> 
> Align the indentation with other lines. `termux-change-repo` uses 4 spaces. There are cases where [Coding guideline](https://github.com/termux/termux-packages/wiki/Coding-guideline) should not be applied.

Fixed.

**Comment by 2096779623** [comment]
> See discussion in [#9553 (comment)](https://github.com/termux/termux-packages/pull/9553#discussion_r834899388) (only login users can see this.)
> 
> Align the indentation with other lines. `termux-change-repo` uses 4 spaces. There are cases where [Coding guideline](https://github.com/termux/termux-packages/wiki/Coding-guideline) should not be applied.

Fixed,Thanks!

**Comment by thunder-coding** [comment]
Kindly rebase against master, you seem to have merge conflicts

**Pull request merged**
