### PR TITLE
libllvm/clang: add option `openmp-implicit-rpath`

### LINKED ISSUE #19766: [Bug]: clang++: error: unknown argument: '-fno-openmp-implicit-rpath'
### Problem description

Dear Termux team,
I am trying to bring GPU computing to Termux in Octave using the OpenCL based package I created at https://sourceforge.net/projects/octave-ocl-extra/files/ .
However, it produced the following errors. I would be grateful if you could help me look at it.
Best wishes,
Jinchuan

```
182 |   DECLARE_OV_TYPEID_FUNCTIONS_AND_DATA2 (OCTAVE_EMPTY_CPP_ARG)                                     |   ^
/data/data/com.termux/files/usr/include/octave-8.4.0/octave/../octave/ov-base.h:191:58: note:              expanded from macro 'DECLARE_OV_TYPEID_FUNCTIONS_AND_DATA2'                                      191 |     VIRTUAL std::string class_name (void) const { return c_name; }      \                          |                                                          ^                                   50 warnings generated.                                                                               14 warnings generated.                                                                               38 warnings generated.
2 warnings generated.                                                                                38 warnings generated.
clang++: error: unknown argument: '-fno-openmp-implicit-rpath'
clang++: error: no such file or directory: '/home/builder/.termux-build/_cache/android-r26b-api-24-v2/lib/clang/17/lib/linux/libclang_rt.builtins-aarch64-android.a'
make: *** [Makefile:48: ocl_bin.oct] Error 1                                                         make: Entering directory '/data/data/com.termux/files/usr/tmp/oct-XGEMDO/ocl-1.2.0-Termux/src'
/data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_constant.cc                               /data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_lib.cc
/data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_context.cc                                /data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_context_obj.cc
/data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_program.cc
/data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_memobj.cc
/data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_array.cc
/data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_array_prog.cc
/data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_ov_matrix.cc
/data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_ov_matrix_ops.cc
/data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_ov_matrix_fcns.cc
/data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_ov_program.cc
/data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 -c ocl_ov_types.cc
/data/data/com.termux/files/usr/bin/mkoctfile-8.4.0 ocl_constant.o ocl_lib.o ocl_context.o ocl_context_obj.o ocl_program.o ocl_memobj.o ocl_array.o ocl_array_prog.o ocl_ov_matrix.o ocl_ov_matrix_ops.o ocl_ov_matrix_fcns.o ocl_ov_program.o ocl_ov_types.o -o ocl_bin.oct
make: Leaving directory '/data/data/com.termux/files/usr/tmp/oct-XGEMDO/ocl-1.2.0-Termux/src'        
error: pkg: error running 'make' for the ocl package                                                 error: called from
    configure_make at line 117 column 9                                                                  install at line 202 column 7
    pkg at line 619 column 9                                                                         octave:2>
```

### What steps will reproduce the bug?

1 install Ocatve 8.4 via 
pkg install ocatve

2 Inside Ocatve, type
pkg install https://sourceforge.net/projects/octave-ocl-extra/files/ocl-1.2.0-Termux.tar.gz/download

### What is the expected behavior?

_No response_

### System information

termux-info:

```
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=31118
TERMUX_IS_DEBUGGABLE_BUILD=1                                                                         TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.nevacloud.com/applications/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirror.nevacloud.com/applications/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.42.0                                                                                               Android version:
13
Kernel build information:
Linux localhost 4.19.157-perf+ #1 SMP PREEMPT Tue Dec 19 02:13:01 CST 2023 aarch64 Android
Device manufacturer:
Lenovo                                                                                               Device model:
TB138FC                                                                                              LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

### LINKED ISSUE #20039: [Python py project unable to build wheel]:
### Problem description

I've been having problems with installing python packages that are are py project toml based, regular packages work fine. Here's the error 
```
copying aiohttp/_helpers.pyx -> build/lib.linux-aarch64-cpython-311/aiohttp
      copying aiohttp/_http_parser.pyx -> build/lib.linux-aarch64-cpython-311/aiohttp
      copying aiohttp/_http_writer.pyx -> build/lib.linux-aarch64-cpython-311/aiohttp
      copying aiohttp/_websocket.pyx -> build/lib.linux-aarch64-cpython-311/aiohttp
      copying aiohttp/py.typed -> build/lib.linux-aarch64-cpython-311/aiohttp
      creating build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_cparser.pxd.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_find_header.pxd.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_helpers.pyi.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_helpers.pyx.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_http_parser.pyx.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_http_writer.pyx.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/_websocket.pyx.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      copying aiohttp/.hash/hdrs.py.hash -> build/lib.linux-aarch64-cpython-311/aiohttp/.hash
      running build_ext
      building 'aiohttp._websocket' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/aiohttp
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.11 -c aiohttp/_websocket.c -o build/temp.linux-aarch64-cpython-311/aiohttp/_websocket.o
      aarch64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib build/temp.linux-aarch64-cpython-311/aiohttp/_websocket.o -L/data/data/com.termux/files/usr/lib -lpython3.11 -o build/lib.linux-aarch64-cpython-311/aiohttp/_websocket.cpython-311.so
      aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build Pillow aiohttp
ERROR: Could not build wheels for Pillow, aiohttp, which is required to install pyproject.toml-based projects

 itsCyberToast  termux  ~ 
```

### What steps will reproduce the bug?

Install python 
Install any py project toml example: aiohttp, pillow 

### What is the expected behavior?

It's supposed to install normally but it does this.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=9174
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.42.0
Android version:
14
Kernel build information:
Linux localhost 4.19.191-27944104-abA146USQS6CXC2 #1 SMP PREEMPT Fri Mar 8 17:06:37 KST 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A146U
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
com.termux.api versionCode:51
```

### LINKED ISSUE #20445: [Bug]: unable to update gems on android 10
### Problem description

This issue is a continuation from #20359. Once I fixed that and tried `gem update`, the gems that have native C based implementations and need to compile things on device caused errors. To keep it concise, my hunch is that it is related to the `-fno-openmp-implicit-rpath` argument on clang. Related: #20039, #19766

Some gems that I faced issue with were `bigdecimal`, `ffi` and `nokogiri`. All of them had these lines in their `mkmf.log` that describes the error caused while updating:

```
...
aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
aarch64-linux-android-clang: error: unable to make temporary file: No such file or directory
...
```

More precisely, there were some specifics issues too:

`bigdecimal`:

```
current directory: /data/data/sh.gourav.jekyllex/files/usr/lib/ruby/gems/3.2.0/gems/bigdecimal-3.1.8/ext/bigdecimal
/data/data/sh.gourav.jekyllex/files/usr/bin/ruby extconf.rb
checking for __builtin_clz()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

...

/data/data/sh.gourav.jekyllex/files/usr/lib/ruby/3.2.0/mkmf.rb:490:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

	from /data/data/sh.gourav.jekyllex/files/usr/lib/ruby/3.2.0/mkmf.rb:616:in `block in try_compile'
	from /data/data/sh.gourav.jekyllex/files/usr/lib/ruby/3.2.0/mkmf.rb:565:in `with_werror'
...
```

`nokogiri`

```
current directory: /data/data/sh.gourav.jekyllex/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.16.5/ext/nokogiri
/data/data/sh.gourav.jekyllex/files/usr/bin/ruby extconf.rb
checking for whether -std=c99 is accepted as CFLAGS... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

...

/data/data/sh.gourav.jekyllex/files/usr/lib/ruby/3.2.0/mkmf.rb:490:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

	from /data/data/sh.gourav.jekyllex/files/usr/lib/ruby/3.2.0/mkmf.rb:616:in `block in try_compile'
	from /data/data/sh.gourav.jekyllex/files/usr/lib/ruby/3.2.0/mkmf.rb:563:in `with_werror'
...
```

Issue with `__builtin_clz()`, `-std=c99`, I guess something is wrong with clang. Do I need to downgrade, patch something, or add some other development tools to my bootstrap? Any help would be really appreciated. Thanks!

### What steps will reproduce the bug?

I have a custom prefixed bootstrap so maybe it is hard to build and reproduce my exact setup. But this specific issue can be replicated using the android 10 ruby demo I have for `com.termux` prefixed bootstraps and termux apk I built using workflows [here](https://github.com/gouravkhunger/android10-ruby-termux-demo/releases/tag/bootstrap-2024.06.07-r2). It is caused when running `gem update` in the `app-debug.apk` linked in the release.

### What is the expected behavior?

_No response_

### System information

```shell
:/data/data/sh.gourav.jekyllex/files/home $ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [aarch64-linux-android]
:/data/data/sh.gourav.jekyllex/files/home $ gem -v
3.4.10
:/data/data/sh.gourav.jekyllex/files/home $ make -v
make: TMPDIR value /data/data/sh.gourav.jekyllex/files/usr/tmp: No such file or directory
make: using default temporary directory '/data/data/sh.gourav.jekyllex/files/usr/tmp/'
GNU Make 4.4.1
Built for aarch64-unknown-linux-android
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
:/data/data/sh.gourav.jekyllex/files/home $ clang -v
clang version 18.1.6
Target: aarch64-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/sh.gourav.jekyllex/files/usr/bin


My bootstrap has: git, tar, dash, make, ruby, libxslt, libllvm, coreutils, binutils-libs
```

### PR DESCRIPTION
**Pull request by licy183**
There are so many packages that will bundle the cross-compiling CFLAGS in their binaries. It seems better to reintroduce this option for compatibility and remove it in next NDK major bumps.

Closes #20445, closes #20039, closes #19766

### CODE REVIEW

**Comment by finagolfin** [comment]
I think this is the wrong approach. My understanding is that the issue here is that compilation flags from the CI are being applied to local builds on device also? If so, the correct solution is to not blindly copy cross-compilation flags from the original build on the CI to on-device builds, because the latter is natively compiling and the clang versions are different. Better to modify these projects to change which flags are applied on device.

As for the specific issue of this `-openmp-implicit-rpath` flag, I think I will just wait till the next NDK 27 release, which uses a newer clang without it, and then remove the use of that flag altogether.

**Comment by licy183** [comment]
Yeah, it is strange to add this option back, but it is really difficult to modify other applications, either what I have already done on Python, modifying the file storing LDFLAGS, or what you mentioned, modifying the building system of each package and do not copying this option.
Take Python, which I am familiar with, for example. Python stores these flags in `_sysconfigdata__linux_.py` and it is stored in plain text. However, since Python will precompile these py files when distributing, it will fail to load the file if the bytecode is not recompiled after the file is modified. Of course, we can modify `_sysconfigdata__linux_.py` in the `post_make_install` step and delete the corresponding bytecode files (`__pycache__/_sysconfigdata__linux_.cpython-311.*.pyc`), but this will not only make apt unable to clean up the bytecode files generated later, but also break Python's cross-compilation - in builder, `crossenv` will use `CFLAGS` in `_sysconfigdata__linux_.py`, but will use NDK's `clang-17`. So, finally, I deleted all the bytecode files and patch `_sysconfigdata__linux_.py` in `postinst` script. (#20246)
In fact, doing such modification to Python is relatively simple, because at least these flags are not bundled in the binary file. Another example is octave, which bundles these compile-time flags in `lib/octave/8.4.0/liboctinterp.so`, making it even more difficult to patch.
As you mentioned, modifying the building system of each package and do not copying `-fopenmp-implicit-rpath` is more difficult. As reported, `python` (#20039), `ruby` (#20445), `octave` (#19766), `ecl` (https://github.com/termux/termux-packages/issues/19766#issuecomment-2111674993) are all affected. Among these, I have only used Python and octave, and I am not very familiar with other software. It is even more difficult to figure out their compiling logic and then modify them.
Based on the reasons above, I finally chose to modify clang options.

**Comment by finagolfin** [comment]
OK, I don't want you and other Termux devs wasting time on these packages that simply clone cross-compilation flags for native compilation when they're run. Go ahead and fix this simple build error and once it passes CI, you can merge.

**Comment by finagolfin** [comment]
Thanks @licy183, maybe this was the best approach all along.

**Pull request merged**
