### PR TITLE
ruby: fix segmentation fault

### PR DESCRIPTION
**Pull request by xeffyr**
See https://github.com/termux/termux-packages/issues/3380.

### CODE REVIEW

**Comment by handsomebeast** [comment]
server started
/data/data/com.termux/files/usr/bin/msfconsole: line 3: 18079 Segmentation fault      ruby /data/data/com.termux/files/home/metasploit-framework/msfconsole
$
How to solve this
Plz

**Comment by handsomebeast** [comment]
An error occurred while installing nokogiri
(1.10.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.1' --source
'https://rubygems.org/'` succeeds before bundling

How to solve this ?

**Comment by fornwall** [comment]
This updated package is now available.

**Comment by novalnaif** [comment]
pkg install unstable-repo
pkg upgrade

**Pull request merged**
