### PR TITLE
Bug fix (with depends value).

### PR DESCRIPTION
**Pull request by Maxython**
I noticed a bug due to which `depends` incorrectly specified in the `.PKGINFO` file.  

Also one more question: why create two packages but with different depends values?  A package named static is set to the value of a regular package.  
#### Example
```
file-5.40-aarch64.pkg.tar.xz
-> depends=zlib

file-static-5.40-aarch64.pkg.tar.xz
-> depends=file
```

### CODE REVIEW

**Comment by xeffyr** [comment]
1. Static package must depend on parent package. This means `file-static` depends on `file`. Static packages are split from parent and contain static libraries. *Not really Arch way, but Termux is not Arch either. It has own roadmap and view how packages should be managed.*
2. Why removing comma in TERMUX_SUBPKG_DEPENDS? Are you sure you properly understand how build-package.sh works?

Even though this PR fixes a typo in `$TERMUX_SUBPKG_DEPENDS`, I could not accept it.

Issue will be fixed separately.

**Comment by xeffyr** [comment]
Everything that had to be done is in https://github.com/termux/termux-packages/pull/7440/commits/026315055439a488ef116d2cb62880a2c71531eb

**Comment by Maxython** [comment]
> Why removing comma in TERMUX_SUBPKG_DEPENDS?

This comma gives two depends.  One empty other with a package name.  
Screenshot_20210902-090419_Termux
Screenshot_20210902-090345_Termux

**Comment by xeffyr** [comment]
> This comma gives two depend

Then it has to be fixed differently. TERMUX_SUBPKG_DEPENDS may be set in build.sh. But your change completely breaks it.

Expected:
```
TERMUX_SUBPKG_DEPENDS="liba, mainpkg"
```

Yours:
```
TERMUX_SUBPKG_DEPENDS=libamainpkg
```

**Comment by Maxython** [comment]
Ok

**Pull request closed without merging**
