### PR TITLE
Add package : Exiv2

### PR DESCRIPTION
**Pull request by Hax4us**

### CODE REVIEW

**Comment by Grimler91** [comment]
Please squash all of these commits, or redo it cleanly. The history is a mess, most of these commits aren't related to exiv2.

You have commits adding hping for example and then commits to remove hping, those can be taken out completely. 

I think it would be easiest to start from a fresh branch checked out from master and then [cherry-pick commits](https://stackoverflow.com/questions/41057333/git-how-to-pull-only-some-commits) from here related to exiv2, but see also this about [deleting commits](https://stackoverflow.com/questions/1338728/delete-commits-from-a-branch-in-git).

**Comment by Grimler91** [comment]
After you have a clean branch you can [force-update](https://stackoverflow.com/questions/13561004/merging-upstream-git-changes-with-pending-pull-requests) this pending pull request to change it.

**Comment by Hax4us** [comment]
Ohh thnx @Grimler91 I will do as you suggested

**Comment by xeffyr** [comment]
Implemented in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install exiv2
```

**Pull request closed without merging**
