### PR TITLE
fix(main/mesa): Rebuild after llvm 19 update

### LINKED ISSUE #21642: [Bug]: link error when intializing mesa-zink
### Problem description

mesa zink (dri3?) seems to be not working after recent clang/llvm 19 update

this log appeared:
```
MESA-LOADER: failed to open zink: dlopen failed: cannot locate symbol "LLVMLinkInMCJIT" referenced by "/data/data/com.termux/files/usr/lib/dri/kms_swrast_dri.so"... (search paths /data/data/com.termux/files/usr/lib/dri, suffix _dri)
failed to load driver: zink
```

firefox failed to generate webgl context because of this
```
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libEGL initialize failed (t=0.511605) [GFX1-]: glxtest: libEGL initialize failed                                   Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libEGL initialize failed (t=0.511605) |[1][GFX1-]: glxtest: No visuals found (t=0.511605) [GFX1-]: glxtest: No visuals found
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libEGL initialize failed (t=0.511605) |[1][GFX1-]: glxtest: No visuals found (t=0.511605) |[2][GFX1-]: No GPUs detected via PCI
 (t=0.511605) [GFX1-]: No GPUs detected via PCI
                                                           console.error: ({})                                        JavaScript warning: https://webglsamples.org/tdl/webgl.js, line 159: Failed to create WebGL context: WebGL creation failed:
* AllowWebgl2:false restricts context creation on this system. ()                                                     JavaScript warning: https://webglsamples.org/tdl/webgl.js, line 159: Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()                                       * Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)
JavaScript warning: https://webglsamples.org/tdl/webgl.js, line 159: Failed to create WebGL context: WebGL creation failed:                                                      * WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)                                              JavaScript error: https://webglsamples.org/aquarium/aquarium.js, line 893: TypeError: gl is null
```

`blender` in tur-repo also seems to fail after this update
```
CANNOT LINK EXECUTABLE "blender": cannot locate symbol "_ZNK16OpenColorIO_v2_316GpuShaderCreator10getCacheIDEv" referenced by "/data/data/com.termux/files/usr/bin/blender"...
```

### What steps will reproduce the bug?

run xfce4 desktop with `mesa-vulkan-icd-freedreno-dri3` zink icd enabled

### What is the expected behavior?

no error is emitted and GPU acceleration could be used 

### System information

```shell
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__APK_FILE=/data/app/~~rpJQ_zUeRmOHDy7kdIq9uA==/com.termux-CqDST-cpqjnpFN2oouuw2w==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__APP_VERSION_CODE=1020
TERMUX_APP__APP_VERSION_NAME=0.119.0-b1+monet36
TERMUX_APP__DATA_DIR=/data/user/0/com.termux
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PID=19402
TERMUX_APP__TARGET_SDK=28
TERMUX_VERSION=0.119.0-b1+monet36
TERMUX__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c77,c257,c512,c768
TERMUX__SE_INFO=default:targetSdkVersion=28:complete
TERMUX__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c77,c257,c512,c768
TERMUX__UID=10333
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.csclub.uwaterloo.ca/termux/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://mirror.csclub.uwaterloo.ca/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.43.6
Android version:
14
Kernel build information:
Linux localhost 5.10.223-aospa-g99cd60f0e337 #1 SMP PREEMPT Thu Aug 29 14:00:41 IST 2024 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
23049RAD8C
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.window versionCode:15
com.termux.styling versionCode:1000
com.termux.api versionCode:51
com.termux.widget versionCode:13
com.termux.boot versionCode:1000
com.termux.x11 versionCode:15
```

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes #21642

### CODE REVIEW

**Comment by Biswa96** [comment]
mesa and swrast depends on llvm. Should llvm be added in dependency list?

**Comment by licy183** [comment]
This is strange. `swrast` should link against libllvm statically. But anyway, if it really link against libLLVM.so, `libllvm` should be added to DEPENDS.

**Comment by Biswa96** [comment]
The arm build failure could be related to this commit https://github.com/llvm/llvm-project/commit/18e70a4d5042299054dae7d3995f6ccd8f4112b3

**Comment by licy183** [comment]
I'd like to merge this now as mesa is a widely-used package.

**Pull request merged**
