### PR TITLE
improvement: adding an ability to process sed regexps for transformating version during automatic updates

### PR DESCRIPTION
**Pull request by twaik**

### CODE REVIEW

**Comment by twaik** [comment]
@termux/package-maintainers If nobody minds in 24 hours I am merging it.

**Comment by truboxl** [comment]
Should add linter to check using one or the other but not both at the same time

**Comment by twaik** [comment]
> Should add linter to check using one or the other but not both at the same time

I am not sure how to make that properly. Maybe better solution will be to make updater script check only sed regexps.

**Comment by Grimler91** [comment]
> > Should add linter to check using one or the other but not both at the same time
> 
> I am not sure how to make that properly. Maybe better solution will be to make updater script check only sed regexps.

Yeah, feels like one should be enough. Either `sed` or `grep -E` so we have extended regex

**Comment by twaik** [comment]
Ok, I am merging this. I'll start rewriting regular expressions for packages and when I finish I'll remove the grep method.

**Comment by twaik** [comment]
It looks like changing all regexps to sed is a bad idea. They are pretty hard to read.

**Comment by twaik** [comment]
https://github.com/openssh/openssh-portable/tags
https://github.com/ukoethe/vigra/tags
https://github.com/ipmitool/ipmitool/tags

I am not sure if we really require sed. I think we can extract all numeriics with `grep -oP '\d+'` trick and replace newlines with decimal points. It will work for simple cases like `Version-1-11-2` or `IPMITOOL_1_8_19` but we still need special processing function for cases like `V_9_5_P1`.

**Comment by twaik** [comment]
And here lies a problem. `TERMUX_PKG_UPDATE_VERSION_REGEXP` should transform string to the form it should appear in `TERMUX_PKG_VERSION`, in any other way we must override `termux_pkg_auto_update` function to transform version string.

**Comment by twaik** [comment]
I think we should add transforming `\n`=>`.` too, not only `_`=>`.`. In this case `grep -oP '\d+'` should cover the most cases we meet. So we will be able to use `sed` only in some special cases.

**Pull request merged**
