### PR TITLE
llvm6.0 + compiles our own libomp.a

### PR DESCRIPTION
**Pull request by its-pointless**
buildhost needs libxml2-dev i believe

### CODE REVIEW

**Comment by tomty89** [comment]
You mind addressing these issues once and for all? https://github.com/termux/termux-packages/issues/2154

**Comment by tomty89** [comment]
Also.I believe it has the corresponding omp.h so it should replace the one from the NDK shipped in ndk-sysroot?

**Comment by its-pointless** [comment]
how we want to deal with libomp with regards to ndk is up for discussion. How i dealt with it in gcc and libgomp is probably too fidgety or silly. In all likely hood replacing ndk omp.h should be fine. 

With regards to .a files. Putting them in dev package makes sense you are right about that.
the current split doesn't make sense in a functional way. 
i will do a bit of research but you are most likely correct.

**Comment by tomty89** [comment]
We build our version of libomp the I suppose we should use the header file taht matches with the library. Why would we want the omp.h from the NDK anyway (it wasn't even from the NDK but like the NDK toolchain, see its source path in build.sh of ndk-sysroot; it's an exception)

**Comment by its-pointless** [comment]
to use the old libomp.a. since its the officially android supported version.

**Comment by tomty89** [comment]
But does that help when we are shipping the new library? I mean, shouldn't we either ship both the new library and header, or both the old library and header? (Or both sets of them if that's possible and necessary)

**Comment by its-pointless** [comment]
Yeah that is what needs to be worked out. 
I ship both libgomp ndk and gcc-7 libgomp. So kind of need to work exactly what we need.
Also need ti hash out how to split llvm properly. Should we just copy debian?

**Comment by tomty89** [comment]
I think we just need a libclang-dev out of libllvm-dev? The files appears to be quite clear cut so it should be easy. Or you can just stuck libclang back to libllvm, which is what Arch does.

**Comment by tomty89** [comment]
Scratch that.In Arch libclang.so is in the clang package, starting from 6.0 clang doesn't share the same build script with llvm anymore.

**Comment by tomty89** [comment]
I think the idea is, only parts of llvm libraries are required by clang, that's why we want llvm split. But does anything requires only parts of clang? Apparently not.

Is it even possible to have devpackage for subpackages in Termux? Coz as per the Arch packaging, we should have libllvm, llvm(-dev), clang(-dev).

**Comment by its-pointless** [comment]
okay so this is about done.

**Comment by fornwall** [comment]
Nice work! The updated packages are now available for installation.

**Pull request merged**
