### PR TITLE
libllvm: update from 11.1.0 to 12.0.0

### PR DESCRIPTION
**Pull request by buttaface**
First, running it through CI to see if it builds, then I'll test and modify it a bit before merging. Rust and Swift will also need to be bumped after this is in.

### CODE REVIEW

**Comment by buttaface** [comment]
@xeffyr, @Grimler91, or anyone else seen [this weird error before](https://github.com/termux/termux-packages/runs/2446521414?check_suite_focus=true#step:4:8847)? It looks like that preprocessor define from `ptrace-abi.h` on i686/x86_64 screws up that lldb file naming another variable `FS`.

**Comment by Grimler91** [comment]
Nope, new to me. As you said, looks like variable name conflicts, so renaming FS to something else in llvm/include/llvm/Support/VirtualFileSystem.h would probably work

**Comment by buttaface** [comment]
Assuming all the arches build fine now, this is ready for testing in a couple hours once the CI finishes.

I noticed that the `clang` package already installed the `omp.h` header in `lib/clang/11.1.0/include/`, so I didn't put another copy in `include/`. Let me know if that causes a problem.

**Comment by buttaface** [comment]
I've built some code with the AArch64 version of clang from the CI for this pull and it seems to work well. lldb still runs. I don't use other packages like libpolly.

@xeffyr, @Grimler91, @its-pointless, and anyone else with a github account, you can test these 8 LLVM packages out by clicking on `Checks` above, then `Artifacts` on the right, before downloading the 400 MB zip file with these LLVM packages built for all four architectures. Unpack the zip file and install the packages with `dpkg -i debs/*.deb` (you may have to remove the ones you already have installed with `apt remove libllvm` or the equivalent), then test them out. I'm particularly interested in hearing about non-AArch64 arches, as I don't use those.

**Comment by Grimler91** [comment]
No conflicts when installing on arm, and a simple hello world programs in both c and c++ compiles without errors. 

Will compile emacs during the evening and see if that still works.

**Comment by landfillbaby** [comment]
i've only tested on aarch64 but it seems good :)

**Comment by Grimler91** [comment]
Compiling emacs works as well as with clang 11 also.

**Pull request merged**
