### PR TITLE
sing-box: Bump to 1.2.3

### PR DESCRIPTION
**Pull request by CHIZI-0618**

### CODE REVIEW

**Comment by 2096779623** [comment]
If you want to use automatic updates, you can take a look at this link: https://github.com/termux/termux-packages/wiki/Auto-updating-packages .

**Comment by CHIZI-0618** [comment]
> If you want to use automatic updates, you can take a look at this link: https://github.com/termux/termux-packages/wiki/Auto-updating-packages .

Tried it before and got this error, which I haven't solved yet
image

**Comment by 2096779623** [comment]
> Tried it before and got this error, which I haven't solved yet image

https://github.com/termux/termux-packages/blob/45ace72628f7ca8237c782935c1a5ef42bd12de7/scripts/bin/check-auto-update#L99

https://github.com/termux/termux-packages/blob/45ace72628f7ca8237c782935c1a5ef42bd12de7/.github/workflows/package_updates.yml#L30

**Comment by CHIZI-0618** [comment]
> > Tried it before and got this error, which I haven't solved yet image
> 
> https://github.com/termux/termux-packages/blob/45ace72628f7ca8237c782935c1a5ef42bd12de7/scripts/bin/check-auto-update#L99
> 
> https://github.com/termux/termux-packages/blob/45ace72628f7ca8237c782935c1a5ef42bd12de7/.github/workflows/package_updates.yml#L30

So I can't run check-auto-update locally?

**Comment by CHIZI-0618** [comment]
> > So I can't run check-auto-update locally?
> > idk, you can try to manually set the `GITHUB_TOKEN` variable in `scripts/bin/check-auto-update` .

The changes after using --enable
image
  
Which method to use for auto-update. Can be github, gitlab or repology. By default it is decided on the basis of TERMUX_PKG_SRCURL
  
Why not github?

**Comment by CHIZI-0618** [comment]
> > So I can't run check-auto-update locally?
> > idk, you can try to manually set the `GITHUB_TOKEN` variable in `scripts/bin/check-auto-update` .

Oh, I see, just add a GITHUB_TOKEN environment variable

**Comment by 2096779623** [comment]
> Since this pr is currently merged, it doesn't seem cost effective to create a new pr just to enable automatic updates, so I'm going to commit the changes together with the next sing-box release, is that okay?
Of course.

**Pull request merged**
