### PR TITLE
add package translate-shell from request #1796

### PR DESCRIPTION
**Pull request by Quasic**
I had some silly problems with this, so let me know if I missed more.

I replaced the shebang in the awk script, as ```termux-fix-shebang``` is for fixing on device.

### CODE REVIEW

**Comment by Quasic** [comment]
Ok, I'll look at the Travis log and reopen later...

**Comment by Grimler91** [comment]
There are a few lines that are mandatory in the build.sh script, 
TERMUX_PKG_SRCURL
TERMUX_PKG_VERSION
maybe some more that I have forgotten.

TERMUX_PKG_HOMEPAGE
TERMUX_PKG_DESCRIPTION
are good to define as well
And TERMUX_PKG_MAINTAINER (pointing at you) if you would like to maintain the package!

**Comment by Quasic** [comment]
I have build.sh working now, I think, though not sure why it wasn't working, before. I'll have to look at the diffs...

I'm currently stuck on how to make sure gawk is installed on the build machine to run build.awk.

**Comment by Quasic** [comment]
#1337 seems about the same problem...

**Comment by vishalbiswas** [comment]
@Quasic the build.sh will work but the resultant deb file will not be installable.
Its a bug in our massage step and nobody remembers to fix it

**Comment by Quasic** [comment]
Wow, build.sh was actually somehow staged as an empty file. Really weird, silly problems.

**Comment by Quasic** [comment]
Thanks, @Grimler91 and @vishalbiswas, I never intended to have an empty build.sh. I can't believe I actually submitted one in a PR. I should have caught the silly (no change) diff. Travis was saying the file didn't exist, so I added test code in another branch to try to figure it out, but build.sh was staged, there, with added test code... I'm sure I'll laugh about it sometime... Anyway, it finally works this far. Any ideas on building with gawk?

**Comment by Quasic** [comment]
https://travis-ci.org/Quasic/termux-packages

**Comment by vishalbiswas** [comment]
@Quasic you can make sure gawk is installed by adding it in setup-ubuntu.sh, setup-archlinux.sh scripts

**Comment by Quasic** [comment]
Correction: my test script, not Travis, was saying the file didn't exist, but that was because it was running in sh instead of bash. The empty file was probably from a combination of sftp/ssh disconnection and Termux service stopping due to high memory usage of other apps I was using. My sftp finally uploaded, but not before it was committed empty. I should've waited until I could pay more attention to it.

@vishalbiswas, #1337 adds gawk to one of those files, but that almost seems overkill... I was thinking of some kind of lazy install, but perhaps that would be too complicated.

**Comment by Quasic** [comment]
Included #1337

**Comment by Quasic** [comment]
It passed in https://travis-ci.org/Quasic/termux-packages/builds/311656548 but I'm running another...

**Comment by Quasic** [comment]
It looks like master is erroring https://travis-ci.org/termux/termux-packages/builds/311209016 so I'll wait on that.

**Comment by Quasic** [comment]
Hmm... Now it builds, but can't find gawk: https://travis-ci.org/Quasic/termux-packages/builds/318440930

**Comment by xeffyr** [comment]
@Quasic gawk should be compiled and/or installed for host.

**Comment by Quasic** [comment]
@xeffyr: Any idea how?

**Comment by Grimler91** [comment]
@Quasic you need to add the package to setup-ubuntu.sh. 
It won't build in docker until Fornwall has updated the docker image to include gawk though. 
The package build without any problems when gawk has been installed in the docker image. 

Are you sure that you need to depend on bash here? I would guess that this is not necessary.

**Comment by Quasic** [comment]
Ah, that's it! It's not in the docker image! Thanks!

I wasn't sure if I needed to depend on bash, either. I think I'm going to try removing it.

**Comment by stephengroat** [comment]
if this is merged (with the addition of `gawk` to `PACKAGES`) it closes #1337

**Comment by xeffyr** [comment]
Implemented in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install translate-shell
```

**Pull request closed without merging**
