### PR TITLE
add(main): new package discordo

### LINKED ISSUE #11607: [Package]: discordo
### Package description

A lightweight, secure, and feature-rich Discord terminal client

### Home page URL

https://github.com/ayntgl/discordo

### Source code URL

https://github.com/ayntgl/discordo

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by T-Dynamos**
I mistakenly deleted the discordo's commit on my master. 
Closes #11607

### CODE REVIEW

**Comment by rihaq** [comment]
@T-Dynamos any update?

**Comment by T-Dynamos** [comment]
> @T-Dynamos any update?

Waiting for pr yo be merged

**Comment by 2096779623** [comment]
Upgrade to the latest commit, then it will be merge.

**Comment by rihaq** [comment]
Kindly merge it

**Comment by Grimler91** [comment]
Please rebase instead of adding merge commits. From checked out branch do something like

```
git fetch https://github.com/utermux/termux-packages
git rebase FETCH_HEAD
git push -f your-remote-here discordo
```

**Comment by T-Dynamos** [comment]
> Please rebase instead of adding merge commits. From checked out branch do something like
> 
> ```
> git fetch https://github.com/utermux/termux-packages
> git rebase FETCH_HEAD
> git push -f your-remote-here discordo
> ```

```
Auto-merging x11-packages/cairo-dock-core/build.sh
CONFLICT (add/add): Merge conflict in x11-packages/cairo-dock-core/build.sh
Auto-merging x11-packages/ncspot-mpris/build.sh
CONFLICT (add/add): Merge conflict in x11-packages/ncspot-mpris/build.sh
Auto-merging x11-packages/rofi/build.sh
CONFLICT (add/add): Merge conflict in x11-packages/rofi/build.sh
Auto-merging x11-packages/sdl2/build.sh
CONFLICT (add/add): Merge conflict in x11-packages/sdl2/build.sh
warning: Cannot merge binary files: x11-packages/sdl2/configure.patch (HEAD vs. ba3833b (z3: update to 4.11.0))
Auto-merging x11-packages/sdl2/configure.patch
CONFLICT (add/add): Merge conflict in x11-packages/sdl2/configure.patch
error: could not apply ba3833b... z3: update to 4.11.0
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply ba3833b... z3: update to 4.11.0
```
`git rebase FETCH_HEAD` returns this

**Comment by 2096779623** [comment]
```shell
git clone https://github.com/T-Dynamos/termux-packages -b discordo
cd termux-packages
git reset --hard f3f800f
git remote add upstream https://github.com/termux/termux-packages
git pull upstream master --rebase
git push origin discordo -f
```

**Comment by T-Dynamos** [comment]
> ```shell
> git clone https://github.com/T-Dynamos/termux-packages -b discordo
> cd termux-packages
> git reset --hard f3f800f
> git remote add upstream https://github.com/termux/termux-packages
> git pull upstream master --rebase
> git push origin discordo -f
> ```

Thanks!

**Comment by 2096779623** [comment]
> Thanks!

Please change #11672 too.

**Comment by T-Dynamos** [comment]
> > Thanks!
> 
> Please change #11672 too.

Done!

**Comment by Grimler91** [comment]
Thanks!

**Pull request merged**
