### PR TITLE
bump(main/apt): 2.7.7

### PR DESCRIPTION
**Pull request by twaik**
Simple bump. Needs some tests before merging.

### CODE REVIEW

**Review by finagolfin — APPROVED** [review]

**Review by licy183 — APPROVED** [review]

**Comment by twaik** [comment]
Does it work? Can I merge it?

**Comment by finagolfin** [comment]
Passed CI but I did not test it locally.

**Comment by licy183** [comment]
I tested on Termux Docker with `apt update && apt upgrade`, and it worked like expected.

**Comment by twaik** [comment]
So I am merging this?

**Pull request merged**
