### PR TITLE
Reopen: Add packages: pianobar, libao

### PR DESCRIPTION
**Pull request by edward-p**
Reopen.

### CODE REVIEW

**Comment by louisgv** [comment]
@edward-p how can I test this?

**Comment by edward-p** [comment]
@louisgv
- Fork the latest [termux-packages](https://github.com/termux/termux-packages)
- Merge my  [termux-packages](https://github.com/edward-p/termux-packages) into yours.
- To build packages for termux you need a Linux computer with Android-SDK and Android-NDK configured, see README of termux-packages

``` sh
#clone your termux-packages
git clone https://github.com/louisgv/termux-packages
#build pianobar
cd termux-packages
./build-package.sh packages/pianobar
```
- install debs you built in folder `debs`.

p.s. there are three more commits ahead of this, see [#665](https://github.com/PromyLOPh/pianobar/pull/665)

**Comment by kira555666** [comment]
#665

**Comment by alxpettit** [comment]
Is this ready to be merged? What more is there to do?

**Comment by edward-p** [comment]
@alxpettit Actually, I have no idea. Maybe we should wait the upstream to merge these patches, so we don't need to do patching here.

**Comment by edward-p** [comment]
[prebuild_debs_aarch64_20190128.zip](https://github.com/termux/termux-packages/files/2803167/prebuild_debs_aarch64_20190128.zip)

**Comment by edward-p** [comment]
[prebuild_debs_aarch64_20190214.zip](https://github.com/termux/termux-packages/files/2865957/prebuild_debs_aarch64_20190214.zip)

**Comment by wokawoka** [comment]
Thanks for the 64bit prebuild_debs. 
Would it be possible for someone to share the rebit ones? I've tried to compiled them but I don't have a suitable machine to do so at the moment. Many thanks

**Comment by edward-p** [comment]
Seems like the new travis-ci build system solve build dependents only in exist packages.

**Comment by edward-p** [comment]
[build_i686.log](https://github.com/termux/termux-packages/files/3539236/build_i686.log)

**Pull request merged**
