### PR TITLE
[WIP] Proposed Documentation

### PR DESCRIPTION
**Pull request by Wetitpig**
As @xeffyr has proposed, there should be some kind of guidelines or documentation for all contributors.

Now I am still working on them. Would anyone like to comment on them?

### CODE REVIEW

**Comment by Wetitpig** [comment]
Further cosmetic changes should be avoided, so I suggest enforcing the new guidelines right away. How do you think?

**Comment by xeffyr** [comment]
I did some fixes where was necessary.
Now looks fine. 👍

**Comment by xeffyr** [comment]
Unfortunately, docs aren't cover following topics:

1. Usage of `su` or `sudo` is disallowed in build.sh
2. Modifying files outside of build & /tmp directories is disallowed in build.sh.
3. Comments style. Something like in https://github.com/termux/termux-packages/blob/7ce2f5151a6b0289c81966d3f70cfb1f06628027/packages/swi-prolog/build.sh#L1-L4 shouldn't be allowed.
4. Custom variables used in build process should be defined in `termux_step_pre_configure()` if possible. If not, they shouldn't contain command/process substitution.
5. Package configuration fields order. I sometimes see something like https://github.com/termux/termux-packages/blob/c0ac50b958e612534875acf40742d24fa96561cf/packages/freetype/build.sh#L1-L9 \- there revision should be placed after version field, also question about why sha256 is placed before srcurl.
Of course, this is absolutely correct, but randomizing field order makes reviewing of multiple harder (imagine that you are switching between 10+ build.sh files).
6. Multiline descriptions like in https://github.com/termux/termux-packages/blob/c0ac50b958e612534875acf40742d24fa96561cf/packages/rcs/build.sh#L1-L8 should be avoided.

**Comment by Grimler91** [comment]
Another suggestion:
Always use $TERMUX_PKG_VERSION where applicable, so avoid
```sh
TERMUX_PKG_VERSION=1.2.3
TERMUX_PKG_SRCURL=https://abc.com/1.2/v1.2.3.tar.gz
[...]
termux_step_post_make_install() {
    install lib.so.1.2 $TERMUX_PREFIX/lib
}
```
Use instead
```sh
TERMUX_PKG_VERSION=1.2.3
TERMUX_PKG_SRCURL=https://abc.com/${TERMUX_PKG_VERSION:0:3}/v${TERMUX_PKG_VERSION}.tar.gz
[...]
termux_step_post_make_install() {
    install lib.so.${TERMUX_PKG_VERSION:0:3} $TERMUX_PREFIX/lib
}
```

**Comment by xeffyr** [comment]
Also, `install` should be preferred over `cp` so we do not need to rely on source file permissions. When @Wetitpig  changed permissions of \*.sh, OpenSSH package became broken and fix https://github.com/termux/termux-packages/commit/7679dd204c0434a459842a5cd501a2bcd782d998 was needed.

**Comment by Wetitpig** [comment]
> Also, `install` should be preferred over `cp` so we do not need to rely on source file permissions. When @Wetitpig changed permissions of *.sh, OpenSSH package became broken and fix [7679dd2](https://github.com/termux/termux-packages/commit/7679dd204c0434a459842a5cd501a2bcd782d998) was needed.

Does it only occur for some packages or all packages? Thank you!

**Comment by xeffyr** [comment]
> Does it only occur for some packages or all packages?

Many packages use `cp` for copying files to $TERMUX_PREFIX. But only OpenSSH was affected by file permissions problem - there copying was done from $TERMUX_PKG_BUILDER_DIR.

Also I don't think that we should fix all build.sh files in this PR. Mixing docs with changes to plenty of build.sh files makes reviewing hard. It is better to do this in a separate PRs after docs will be stabilized and merged.

***

Any other suggestions about coding practices ? @Grimler91 @Wetitpig 

I think that in coding practices we should have only important things as we probably can't handle all (and rare) cases here. Code reviewing of PRs will be done anyway. Maintainers can modify a PR before it will get merged.

**Comment by Wetitpig** [comment]
> > Does it only occur for some packages or all packages?
> 
> Many packages use `cp` for copying files to $TERMUX_PREFIX. But only OpenSSH was affected by file permissions problem - there copying was done from $TERMUX_PKG_BUILDER_DIR.
> 
> Also I don't think that we should fix all build.sh files in this PR. Mixing docs with changes to plenty of build.sh files makes reviewing hard. It is better to do this in a separate PRs after docs will be stabilized and merged.
> 
> Any other suggestions about coding practices ? @Grimler91 @Wetitpig
> 
> I think that in coding practices we should have only important things as we probably can't handle all (and rare) cases here. Code reviewing of PRs will be done anyway. Maintainers can modify a PR before it will get merged.

So I will delete 53329bf

**Comment by xeffyr** [comment]
Ready ?

I can merge this. If there still typos, they can be fixed later. Regarding coding/formatting practices - seems enough for now.
Also
> Code reviewing of PRs will be done anyway.

Build instructions can be improved at any time if necessary.

**Comment by Wetitpig** [comment]
> Ready ?
> 
> I can merge this. If there still typos, they can be fixed later. Regarding coding/formatting practices - seems enough for now.
> Also
> 
> > Code reviewing of PRs will be done anyway.
> 
> Build instructions can be improved at any time if necessary.

Ready now! Thanks!

**Pull request merged**
