### PR TITLE
proxmark3-git: update to latest master

### PR DESCRIPTION
**Pull request by s00se**

### CODE REVIEW

**Comment by MrAdityaAlok** [comment]
@s00se I had this question for long time. Why do you use commit instead of tags for URL?

**Comment by xtkoba** [comment]
@MrAdityaAlok I suppose it is because the commit has no tags.

**Comment by MrAdityaAlok** [comment]
> @MrAdityaAlok I suppose it is because the commit has no tags.

No, I ment that a tag corresponding to current version [exists](https://github.com/RfidResearchGroup/proxmark3/releases/v4.14831), so it should be preferred.

Also repos like fedora too uses this url.

**Comment by xtkoba** [comment]
But this package is not for released version. Released version is packaged as `proxmark3` and uses tag for `TERMUX_PKG_VERSION`.

**Comment by MrAdityaAlok** [comment]
> But this package is not for released version. Released version is packaged as `proxmark3` and uses tag for `TERMUX_PKG_VERSION`.

Ah! Sorry then, I had not seen that package.

**Pull request merged**
