### PR TITLE
termux-tools: pkg: add `info` as `show` alias

### PR DESCRIPTION
**Pull request by vladimyr**
After doing too many unwanted installs by accidentally typing: `pkg info <package>` I finally decided it is time to propose a `show` command alias. :smile:

### CODE REVIEW

**Comment by bing245** [comment]
Pls I am confused about this github and how it works 😟

**Comment by bing245** [comment]
> After doing too many unwanted installs by accidentally typing: `pkg info <package>` I finally decided it is time to propose a `show` command alias. :smile: 

Pls help me out

**Comment by Grimler91** [comment]
Looks good to me. Could you please increase `TERMUX_PKG_VERSION` in the build.sh as well?

**Comment by vladimyr** [comment]
@Grimler91 I should've done it in the first place :facepalm: Thx for reminding me!
Anyway, the version has been updated :heavy_check_mark:

**Comment by Grimler91** [comment]
Great, thanks!

**Pull request merged**
