### PR TITLE
swift: enable package and update to 5.2.1

### PR DESCRIPTION
**Pull request by buttaface**
Depends on #5125, simply builds the base Swift compiler and stdlib for now, though everything up through the package manager is available from the on-device build. I'll look into cross-compiling the rest next, but might as well get the base compiler in now.

### CODE REVIEW

**Comment by buttaface** [comment]
Btw, this build produces 8 GBs of source and build artifacts by the end, including the Swift host compiler and the standalone NDK that Termux creates, was running out of space on my build server by the end. Let me know if that's a problem for the CI, can clean up a couple GBs if needed.

**Comment by xeffyr** [comment]
Your build fails at:
```
/home/builder/termux-packages/packages/swift/build.sh: line 22: TERMUX_STANDALONE_TOOLCHAIN: unbound variable
```
\- you can't reference such variable outside of functions.

**Comment by xeffyr** [comment]
I have rebased your PR after merging https://github.com/termux/termux-packages/pull/5125, so we can see how it builds on CI.

**Comment by xeffyr** [comment]
Now fails at
```
Archive:  /home/builder/.termux-build/swift/tmp/ninja-1.10.0.zip
  inflating: /home/builder/.termux-build/_cache/ninja-1.10.0/ninja  
/home/builder/.termux-build/swift/src/swift/utils/build-script: note: Using toolchain default
/home/builder/.termux-build/swift/src/swift/utils/build-script: fatal error: can't find clang (please install clang-3.5 or a later version)
```

**Comment by buttaface** [comment]
I think it's the issue I mentioned in #5125, the standalone toolchain isn't set up yet. I've tried copying and pasting that before the host build, let's see if that's it.

**Comment by buttaface** [comment]
OK, that's not it. I think it might be that it tries to find and use the system clang for the host build, which works fine on my server but isn't working on the CI for some reason. Dumping some debug output to check why that might be.

**Comment by buttaface** [comment]
@xeffyr, OK, figured it out: [the Swift build-script looks for the host clang](https://github.com/apple/swift/blob/swift-5.2.1-RELEASE/utils/swift_build_support/swift_build_support/toolchain.py#L90) for the host build, but my last test shows there's no clang in the system path. I guess gcc is normally used for the host builds on the CI?

**Comment by xeffyr** [comment]
Yes, clang is not available.
```
builder@8cf42c151156:~/termux-packages$ clang --version
bash: clang: command not found
builder@8cf42c151156:~/termux-packages$ gcc --version
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Is swift expects clang to be installed or gcc may be used instead ? I can add clang if needed.

**Comment by buttaface** [comment]
I've modified it to force it to use gcc/g++, not sure if that will work but let's see what the CI says. If not, I may need the clang package, as I'm not sure the standalone toolchain's clang will work either.

**Comment by buttaface** [comment]
@xeffyr, I'd appreciate it if you can add the clang package to the Docker for the CI, as the Swift build-script passes compiler flags to gcc that it doesn't support. In the meantime, I'll submit a separate pull to allow setting up the standalone toolchain for a host build like this if wanted.

**Comment by buttaface** [comment]
Alright, just made that standalone toolchain setup a different commit here, just need the clang package installed in Docker now and should be ready to test.

**Comment by xeffyr** [comment]
clang-9 is now available, https://github.com/termux/termux-packages/commit/83385be03dbaf2636ccaaf7902a94be007edaf12.

**Comment by buttaface** [comment]
Had to add a couple more packages to the Ubuntu host, but looks like it's finally building the compiler now.

**Comment by buttaface** [comment]
Took 2.5 hours, but looks like it worked, ready to merge.

**Comment by xeffyr** [comment]
Should arm/i686/x86_64 remain to be blacklisted ?

**Comment by buttaface** [comment]
Yes, I've never built those, probably never will.

**Pull request merged**
