### PR TITLE
Adding cli-file-manager, Linux terminal app. Request: https://github.…

### PR DESCRIPTION
**Pull request by confund0**
…com/termux/termux-packages/issues/11180

### CODE REVIEW

**Review by 2096779623 — CHANGES_REQUESTED** [review]
https://github.com/termux/termux-packages/wiki/Coding-guideline

* Fix your indentation.
* Rewrite commit messages to match the formats used in [git history](https://github.com/termux/termux-packages/commits/master), or the format specified in #10748.
* Don't create multiple PRs for the same request.

**Comment by 2096779623** [comment]
Enable auto update: https://github.com/termux/termux-packages/wiki/Auto-updating-packages

**Comment by confund0** [comment]
Is there anything else needed to see package available in _pkg install_ ?

**Review by 2096779623 — APPROVED** [review]

**Comment by 2096779623** [comment]
> Is there anything else needed to see package available in _pkg install_ ?

No.

**Pull request merged**
