### PR TITLE
Add rgbds package (Rednex Game Boy Development System)

### PR DESCRIPTION
**Pull request by kaero**
and byacc as rgbds dependency and self-valuable package.

### CODE REVIEW

**Comment by stephengroat** [comment]
@kaero great idea!

doesn't `rgbds` depend on `libpng` for runtime, not just as a build dependency? If so, you might want to add a `TERMUX_PKG_DEPENDS` line that lists those runtime dependencies

**Comment by kaero** [comment]
> doesn't rgbds depend on libpng for runtime, not just as a build dependency? If so, you might want to add a TERMUX_PKG_DEPENDS line that lists those runtime dependencies

Thanks for attention! I've missed the dependency and have checked on device only the assembler & linker, but not graphics converter, which uses libpng :(

I've updated the commit.

> great idea!

Yep :) It's fun to code something in the way or coffee break & test it on the device itself using some of available GB emulators for Android :)

**Comment by fornwall** [comment]
Thanks! The built package is now available in the apt repository.

I've removed `TERMUX_PKG_BUILD_DEPENDS` as I don't think it's necessary - it works a bit different here than in Debian as packages are cross-compiled:

`TERMUX_PKG_BUILD_DEPENDS` specifies other packages that needs to be built before building this one, but is not a runtime dependency. An example would be header-only parts of boost. But if a package needs to run e.g. pkg-config as part of building, it shouldn't list pkg-config in `TERMUX_PKG_BUILD_DEPENDS` as that would only provide a cross-compiled binary of pkg-config. Same with e.g. yacc, cmake and others.

These programs to be run at build time are instead installed by [scripts/setup-ubuntu.sh](https://github.com/termux/termux-packages/blob/master/scripts/setup-ubuntu.sh) when using the Docker image to build packages.

**Comment by kaero** [comment]
Oh, ok, got it! Thanks for fix & explanation!

**Pull request merged**
