### PR TITLE
libllvm: add llvm-config helper script

### PR DESCRIPTION
**Pull request by vishalbiswas**
This is not a perfect replacement. It is used to get around https://github.com/termux/termux-packages/issues/879
I have left some fields incomplete. I don't really know what they are used for or how to efficiently get the values that they should return.
Its mean't to be a temporary patch until the issue is fixed.
This isn't ready to be merged. I'll update when I get components switch working. I'll need the output of `llvm-config --components` from all arches to do this.

### CODE REVIEW

**Comment by mawatech** [comment]
Something like this?

$ uname -a
Linux localhost 3.18.19+ #1 SMP PREEMPT Tue Dec 6 15:46:33 CST 2016 aarch64 Android
$ llvm-config --components
aarch64 aarch64asmparser aarch64asmprinter aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils all all-targets analysis asmparser asmprinter bitreader bitwriter codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfomsf debuginfopdb demangle engine executionengine globalisel instcombine instrumentation interpreter ipo irreader libdriver lineeditor linker lto mc mcdisassembler mcjit mcparser mirparser native nativecodegen objcarcopts object objectyaml option orcjit passes profiledata runtimedyld scalaropts selectiondag support symbolize tablegen target transformutils vectorize
$

**Comment by vishalbiswas** [comment]
So, I've updated this script to a point at which it compiles rust.
I'll create a pull request for rust after this gets merged.

**Comment by vishalbiswas** [comment]
Now it should be in optimal state to merge. I promise.

**Comment by vishalbiswas** [comment]
Note that I haven't bumped the revision as the built package (deb) remains unchanged. As such, users will have to rebuild libllvm package if they want to use this wrapper.

**Comment by joakim-noah** [comment]
I used this pull to build the Rust pull, had no problem, what else needs to be done to merge this?

**Comment by fornwall** [comment]
Merged, nice work @vishalbiswas !

**Comment by kirillrdy** [comment]
+1 
Does it mean rust can be merged?

**Pull request merged**
