### PR TITLE
(Some) fixes needed after updating docker image to ubuntu 22.04

### PR DESCRIPTION
**Pull request by Grimler91**
openjdk-17 requires openjdk-16 or openjdk-17 in the docker image to build, and for 22.04 we need to get that from ppa. 

Upgrading our openjdk package to openjdk-18 might be a good idea (would require rebasing all the patches onto openjdk-18)

### CODE REVIEW

**Comment by 2096779623** [comment]
You seem to have forgotten about bump REVISION.

**Comment by buttaface** [comment]
What do you think about updating our CI to run directly in the Ubuntu 22.04 environment provided by github Actions instead? I realize that risks the Docker image getting out of date, but I assume enough people are using it that that won't happen.

It just seems a waste to always run an Ubuntu 20.04 Docker image inside an Ubuntu 20.04 VM in our github-provided CI.

**Comment by Grimler91** [comment]
> You seem to have forgotten about bump REVISION :) .

It's on purpose, the changes shouldn't affect the package (well, in an ideal world anyways), patch only affects the build system. Pushed it now with %ci:no-build so that no updated packages are pushed

**Comment by Grimler91** [comment]
> What do you think about updating our CI to run directly in the Ubuntu 22.04 environment provided by github Actions instead? I realize that risks the Docker image getting out of date, but I assume enough people are using it that that won't happen.
> 
> It just seems a waste to always run an Ubuntu 20.04 Docker image inside an Ubuntu 20.04 VM in our github-provided CI.

Would save some time for small builds I suppose, could be nice. What does @sylirre, @truboxl, @licy183 and everyone else think about it?

**Comment by sylirre** [comment]
A Docker image on GitHub Actions was used previously due to Ubuntu versions mismatch. That's not the case anymore, so let's try run builds directly.

Without Docker image we will have more space (~9 GB freed), in addition to reduced build times.

**Pull request merged**
