### PR TITLE
addpkg(x11/qt6-qtdeclarative): 6.7.1

### LINKED ISSUE #20326: [Package]: qt6-qtdeclarative
### Why is it worth to add this package?

Lots of Qt6 apps depends on this package, including the requested shotcut #20021 . 
I don't have the expertise and grateful for help from the community. I suspect that qtquickcontrol is now in qtdeclarative. 

### Home page URL

_No response_

### Source code URL

https://download.qt.io/official_releases/qt/6.7/6.7.1/submodules/
```
TERMUX_PKG_SRCURL="https://download.qt.io/official_releases/qt/${TERMUX_PKG_VERSION%.*}/${TERMUX_PKG_VERSION}/submodules/qtdeclarative-everywhere-src-${TERMUX_PKG_VERSION}.tar.xz"
```
### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [x] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes #20326

### CODE REVIEW

**Review by TomJo2000 — APPROVED** [review]
We don't usually package standalone libraries, but I think we can make an exception in this case, seeing as this is basically updating [`qt5-qtdeclarative`](https://github.com/termux/termux-packages/blob/master/x11-packages/qt5-qtdeclarative/build.sh).

**Comment by Biswa96** [comment]
> We don't usually package standalone libraries

qt6-qtlanguageserver is required by qmlls program. ArchLinux mentioned that as an optional dependency. Should I move qtlanguageserver to dependency list?

**Comment by TomJo2000** [comment]
You can make it a `TERMUX_PKG_RECOMMENDS` or `TERMUX_PKG_SUGGESTS`, although [recommends feels more appropriate in this case](https://github.com/termux/termux-packages/wiki/Creating-new-package#:~:text=TERMUX_PKG_RECOMMENDS).

**Comment by truboxl** [comment]
Please fix qt6-qtdeclarative description

**Comment by Biswa96** [comment]
I have added two required qt6 packages for shotcut program (related to the linked issue).

**Comment by TomJo2000** [comment]
(see #20021)

**Comment by TomJo2000** [comment]
Looks like from `shotcut`'s dependency list, the only thing that's still missing is `qt6-translations`, which I'm not sure we *strictly* need to build the package.
I'll pull down the changes from this PR and give compiling shotcut a go.

**Comment by knyipab** [comment]
I copied those qt6-* and tried to compile `shotcut` here: https://github.com/knyipab/tur/actions/runs/9255472448/job/25459323731
`qt6-translations` seems to be necessary and there do not seems to be arguments to bypass this library.

**Comment by Biswa96** [comment]
qt6-translations requires qt6-tools which I am unable to compile. I was thinking to add those in a separate for adding shotcut.

**Comment by knyipab** [comment]
I found that running `sudo apt install -y libclang-15-dev` beforehand should help to compile `qt6-qttool`. I managed to build it in my local dev container with [this build script](https://github.com/knyipab/tur/blob/67c2f709a17d33ba63b06e4bd9e902db56eb4ab7/tur/qt6-qttools/build.sh). In that script, I am not sure and couldn't be bothered to test if `-DQT_FEATURE_zstd=OFF` and `zstd` are strictly necessary, and what is the correct way to add `sudo apt install -y libclang-15-dev` into the build script (or perhaps `termux-pacakges` should address it??). Your help is appreciated. 

I built `qt6-qttools` and `qt6-qttranslations` in my local machine, and started to test `shotcut`. The shotcut app starts and video preview box works, but the shotcut timeline/track editor runs into problem with frei0r-plugin at [this line of code](https://github.com/mltframework/shotcut/blob/407a34a973771fd5a721f9629bbf82b35d55d4be/src/models/multitrackmodel.cpp#L2548) and I am still figuring out.

**Comment by Biswa96** [comment]
I have added qt6 tools and translations packages. The clang requirement in qt6 tools is disabled which disables qdoc also. We could discuss the shotcut issue in another PRs.

**Comment by TomJo2000** [comment]
Something is very wrong with the last CI run here.
Searching for `build of` brings up the results:
- `termux - build of 'calc' done`
- `termux - build of 'dart' done`
- `termux - build of 'flyctl' done`
- `termux - build of 'gitea' done`
- `termux - build of 'gitea' done`
- `termux - build of 'jql' done`
- `termux - build of 'minio' done`

The CI run then failed trying to build `nodejs` by the looks of it.
Why were any of those packages even getting built?

**Comment by truboxl** [comment]
You need to rebase or update branch if master branch has added commits since then. Otherwise CI will build unrelated packages...

**Comment by TomJo2000** [comment]
> You need to rebase or update branch if master branch has added commits since then. Otherwise CI will build unrelated packages...

Yep that makes sense now.
All those packages did have recent updates.

**Comment by TomJo2000** [comment]
All green, package contents look as expected.
Let's get this merged then so we can give `shotcut` a try.

**Comment by Biswa96** [comment]
Would it be possible to add a qt5 and qt6 package group or meta-package to install all qt5 and qt6 packages respectively? For example, https://archlinux.org/groups/x86_64/qt5/ and https://archlinux.org/groups/x86_64/qt6/

**Comment by TomJo2000** [comment]
> Would it be possible to add a qt5 and qt6 package group or meta-package to install all qt5 and qt6 packages respectively? For example, https://archlinux.org/groups/x86_64/qt5/ and https://archlinux.org/groups/x86_64/qt6/

I think that would be a good idea.
All the Qt6 libraries are currently prefixed with `qt6-`, I'm not sure the same is true for Qt5.

**Comment by truboxl** [comment]
Eventually `qt6-qt5compat` will be packaged which make those ideas obsolete.

**Comment by TomJo2000** [comment]
In the meantime a Qt5 and Qt6 group would still be good to have.
Since I assume `qt6-qt5compat` will require Qt6 versions of all packaged Qt5 packages.

**Pull request merged**
