### PR TITLE
uv: patch venv libc detection

### PR DESCRIPTION
**Pull request by Mause**
This allows uv to detect the termux installed python version, which doesn't use musl or glibc

### CODE REVIEW

**Review by licy183 — APPROVED** [review]
LGTM

**Review by twaik — APPROVED** [review]
Will be merged in 24 hours if no one minds or when it gets one more approve.

**Comment by xronin01** [comment]
Screenshot_20241023-184525_Termux_1
it's not working for me

**Comment by Mause** [comment]
> Screenshot_20241023-184525_Termux_1
> it's not working for me

Have you updated?

**Pull request merged**
