### PR TITLE
q-dns-client: Bump to 0.11.2

### PR DESCRIPTION
**Pull request by CHIZI-0618**

### CODE REVIEW

**Comment by xtkoba** [comment]
Please use version tag.

**Comment by xtkoba** [comment]
I will refactor the current build.sh. Please submit a new PR after that. Thanks.

**Comment by xtkoba** [comment]
Please go ahead.

**Comment by CHIZI-0618** [comment]
> Please go ahead.

https://github.com/termux/termux-packages/pull/17245

**Pull request closed without merging**
