### PR TITLE
luarocks: update to 3.0.4

### PR DESCRIPTION
**Pull request by Grimler91**

### CODE REVIEW

**Comment by Grimler91** [comment]
@xeffyr Do you have any idea why gitlab-CI doesn't pick up that luarocks has been updated here?

**Comment by xeffyr** [comment]
gitlab ci key is not in keyring so upload is manual-only.

**Comment by xeffyr** [comment]
What is https://gitlab.com/termux-mirror/termux-packages/commit/77555134e947c5ed09ba31a614f7379a503190a7 ?

You did a force-push after this commit ? If so, then I know why no changes detected.

**Comment by Grimler91** [comment]
Ah, yes, I hadn't pulled in your android-7 commits so I force pushed. I'll refrain from that in the future then.

I've already uploaded luarocks 3.0.4 to the android-7 repo so I'll merge this despite the build error (due to lua not being in the docker image)

**Pull request merged**
