### PR TITLE
fix(main/bionic-host): fix build issues for local builds

### PR DESCRIPTION
**Pull request by TomJo2000**
Follow up to #21825.
See also: https://github.com/termux/termux-packages/issues/21130#issuecomment-2419213816

CC: @twaik

### CODE REVIEW

**Review by twaik — APPROVED** [review]

**Comment by TomJo2000** [comment]
Hold on before merging, I wanna clean up the shellcheck warnings in the build script while we're here.

**Comment by twaik** [comment]
Take your time.

**Comment by TomJo2000** [comment]
@twaik, what was the idea here;
https://github.com/termux/termux-packages/blob/055c8eb63b81733f4a3f5e96fbb12ab1c09e9408/packages/bionic-host/build.sh#L57
because I'm not quite sure it's working as it should.

**Comment by TomJo2000** [comment]
> This line removes `/home/`whoami`/.cargo/bin` from `$PATH` and adds there `${TERMUX_PKG_SRCDIR}/prefix/usr/bin`. And then mentions `$PATH` again, yeah. Probably `:$PATH` should be removed. If you have better solution to remove `~/.cargo/bin` from `$PATH` you feel free to replace this line.

Right, I got the intention.
The issue is, it doesn't do that.

**Comment by twaik** [comment]
> Why is this not using `termux_download?`
> 
> https://github.com/termux/termux-packages/blob/055c8eb63b81733f4a3f5e96fbb12ab1c09e9408/packages/bionic-host/build.sh#L66

Because `termux-download` performs checksum verefication, it is not really needed. You can invoke `termux-download` with `SKIP_CHECKSUM` here to use package caching if you want but it is not necessary.

**Comment by TomJo2000** [comment]
> Because `termux-download` performs checksum verefication, it is not really needed. You can invoke `termux-download` with `SKIP_CHECKSUM` here to use package caching if you want but it is not necessary.

It's mostly about keeping things consistent.

**Comment by TomJo2000** [comment]
This can get squashed for merger, but for review I think having the build script cleanup in a separate commit is gonna be better.

**Comment by twaik** [comment]
LGTM.
In the case if you feel icky about this you can remove printing `page` and `$PAGE` and print `$PAGE` in the case if `deb_url` is empty. But no one will complaint about this, anyway bionic-host building produces ~11k lines of output.

**Review by twaik — APPROVED** [review]

**Pull request merged**
