### PR TITLE
new package: vivid

### PR DESCRIPTION
**Pull request by Freed-Wu**

### CODE REVIEW

**Review by MrAdityaAlok — CHANGES_REQUESTED** [review]
@Freed-Wu patch this line https://github.com/sharkdp/vivid/blob/af8df7c605be085ea587fa754dca0df6fd43a4fd/src/main.rs#L27

as `@TERMUX_PREFIX@/usr/share/vivid/themes/`

And also this line 
https://github.com/sharkdp/vivid/blob/af8df7c605be085ea587fa754dca0df6fd43a4fd/src/main.rs#L53

**Comment by Freed-Wu** [comment]
Great!

**Review by MrAdityaAlok — APPROVED** [review]
Thanks!

**Comment by MrAdityaAlok** [comment]
Merged in https://github.com/termux/termux-packages/commit/5040651963f33a565e8fc56892f821ce7a38d4ac, though github ui failed to detect it.

**Comment by Grimler91** [comment]
@MrAdityaAlok the source branch needs to be rebased onto origin/master for github to detect the merge, I usually do something like:

```
git checkout master 
git fetch git@github.com:Freed-Wu/termux-packages vivid
git cherry-pick FETCH_HEAD --gpg-sign
git push -f git@github.com:Freed-Wu/termux-packages HEAD:vivid && sleep 2 && git push origin master
```

**Pull request closed without merging**
