### PR TITLE
add support for cmake 3.7.1

### PR DESCRIPTION
**Pull request by vishalbiswas**
This adds support for cmake >= 3.7.1 where cross compiling to Android is officially supported.
I have also added cmake configure support in the build-package.sh and separated configure as configure_autotools and configure_cmake.
First it checks for CMake version (which I shamelessly copied from a stackoverflow answer), and if its less than 3.7.1, sets the `OLD_CMAKE` var.
If we have OLD_CMAKE then it will set `TOOLCHAIN_ARGS` with options that we have used in past packages. Else, we ask cmake to use the standalone toolchain.
By default, CMake will use clang, since there is no manual override yet. We only use clang when `TERMUX_PKG_CLANG` is set.
So, I made a workaround which moves away the clang binary (cmake looks for it when deciding toolchain) when we want gcc and restores it after configuration is complete.

Next step is to port all packages that use cmake to use this function instead of standalone configure functions in each buildscript.

### CODE REVIEW

**Comment by vishalbiswas** [comment]
I add a `TERMUX_PKG_FORCE_CMAKE` option to try cmake straightaway if the source can be configured using autotools, tool.
I've also added some more default arguments to cmake. If you have more in mind, let me know. It will have to be universal in cmake.

One more thing, when using gcc and cmake, the clang binary is now properly restored after a configure failure. But, if the user presses Ctrl+C during configure, then the clang binary file won't be restored. If someone has a more elegant solution, I'm happy to oblige.

**Comment by vishalbiswas** [comment]
The last commit adds another check for misplaced clang if the user manually presses Ctrl+C during configuration that  I described in the previous comment. I'll remove these workarounds as soon as cmake has a method to switch between toolchains.

I have been porting packages that are using cmake configure to this new mechanism. Its going pretty well. Should I continue adding those changes to this PR or create another one?

**Comment by fornwall** [comment]
@vishalbiswas This looks great!

I think it would be nice to be able to require an up to date cmake and specify the used version ourselves. For that I added a `termux_setup_cmake` in https://github.com/termux/termux-packages/commit/bb8baaa26d51f42c0fd1c666dfec122ceddd0b9d, which (if necessary) downloads and extracts cmake 3.7.1 and adds it to the front of `PATH`.

Could you change `termux_step_configure_cmake` to call this function first and remove the fallback for older version, and then I'll merge it?

**Comment by vishalbiswas** [comment]
One thing I failed to mention in the previous commit message is that I've also removed gcc support when configuring with CMake.

**Comment by fornwall** [comment]
@vishalbiswas Merged, great work in seeing this through!

**Pull request merged**
