### PR TITLE
swift: bump clang headers symlink version to 10.0.1 and refactor some flags and patches

### PR DESCRIPTION
**Pull request by buttaface**
The next patch release is taking forever, so get this fixed now.

### CODE REVIEW

**Comment by buttaface** [comment]
Hmm, that is a strange CI error:
```
/home/builder/termux-packages/.termux-builder/_cache/android-r21d-api-24-v3/bin/clang++  -DCMARK_STATIC_DEFINE -DGTEST_HAS_RTTI=0 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/SwiftReflection -I/home/builder/termux-packages/.termux-builder/swift/src/swift/lib/SwiftReflection -Iinclude -I/home/builder/termux-packages/.termux-builder/swift/src/swift/include -I/home/builder/termux-packages/.termux-builder/swift/src/llvm-project/llvm/include -I/home/builder/termux-packages/.termux-builder/swift/build/llvm-android-aarch64/include -I/home/builder/termux-packages/.termux-builder/swift/src/llvm-project/clang/include -I/home/builder/termux-packages/.termux-builder/swift/build/llvm-android-aarch64/tools/clang/include -I/home/builder/termux-packages/.termux-builder/swift/src/cmark/src -I/home/builder/termux-packages/.termux-builder/swift/build/cmark-android-aarch64/src -Wno-unknown-warning-option -Werror=unguarded-availability-new -fno-stack-protector -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++14 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -ffunction-sections -fdata-sections -Werror=switch -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -O3 -DNDEBUG    -fno-exceptions -fno-rtti -target aarch64-unknown-linux-android24 --sysroot=/data/data/com.termux/files -O2 -g0 -DNDEBUG -funwind-tables -nostdinc++ -isystem /data/data/com.termux/files/usr/include/c++/v1 -isystem /data/data/com.termux/files/usr/include -isystem /data/data/com.termux/files/usr/include/aarch64-linux-android -D__ANDROID_API__=24  -Werror=gnu -MD -MT lib/SwiftReflection/CMakeFiles/swiftReflection.dir/__/__/stdlib/public/Reflection/MetadataSource.cpp.o -MF lib/SwiftReflection/CMakeFiles/swiftReflection.dir/__/__/stdlib/public/Reflection/MetadataSource.cpp.o.d -o lib/SwiftReflection/CMakeFiles/swiftReflection.dir/__/__/stdlib/public/Reflection/MetadataSource.cpp.o -c /home/builder/termux-packages/.termux-builder/swift/src/swift/stdlib/public/Reflection/MetadataSource.cpp
In file included from /home/builder/termux-packages/.termux-builder/swift/src/swift/stdlib/public/Reflection/MetadataSource.cpp:13:
In file included from /home/builder/termux-packages/.termux-builder/swift/src/swift/include/swift/Reflection/MetadataSource.h:25:
In file included from /home/builder/termux-packages/.termux-builder/swift/src/llvm-project/llvm/include/llvm/ADT/Optional.h:19:
/home/builder/termux-packages/.termux-builder/swift/src/llvm-project/llvm/include/llvm/Support/Compiler.h:19:10: fatal error: 'new' file not found
#include <new>
         ^~~~~
1 error generated.
```
@xeffyr, I wonder if it has to do with the new CI dependency caching, which I notice is still downloading a lot of packages, like libllvm. Kicking off another CI run to see if it's reproducible, as my refactoring shouldn't be affecting this.

**Comment by xeffyr** [comment]
Now it fails here:
```
Downloading https://cmake.org/files/v3.17/cmake-3.17.3-Linux-x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 20 38.7M   20 8224k    0     0  23.0M      0  0:00:01 --:--:--  0:00:01 23.0M
 35 38.7M   35 13.8M    0     0  32.6M      0  0:00:01 --:--:--  0:00:01 32.6M
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
```

**Comment by xeffyr** [comment]
Defiles caching shouldn't affect builds. There only debfiles download location differs and they should be checked against checksums in package lists anyway.

**Comment by buttaface** [comment]
This time it was building a bunch of packages that were changed upstream, because my branch had fallen behind master. Does the CI not rebase on latest master before building?

**Comment by xeffyr** [comment]
No, it doesn't rebase automatically and since changes are determined by comparing your branch and top commit of base branch, it will pick latest changes from base branch if they are not present in yours.

**Comment by buttaface** [comment]
As usual, the last new flag I added and didn't fully test broke the build: let's see if this fixes it.

**Pull request merged**
