### PR TITLE
nodejs: Bump to 16.x

### PR DESCRIPTION
**Pull request by thunder-coding**

### CODE REVIEW

**Comment by thunder-coding** [comment]
So, let me first explain what changes I have made here and why since this PR is gonna be large

1. The patches have been shamelessly stolen from https://github.com/suhan-paradkar/termux-packages/pull/8

2. About assembly errors for i868 and arm

This is a known upstream issue about the nodejs toolchain suicidally passing `-m32` for host builds of nodejs when cross compiling for 32 bit. See https://github.com/nodejs/node/issues/39736

This needs some special attention

3. The toolchain tries to use shared libraries which are passed to `configure.py` but doesn't pass appropriate linker flags which are fixed by hardcoding host linker to have those linker flags. Luckily it doesn't use the shared libraries compiled for Android.

**Comment by thunder-coding** [comment]
**Problems faced while building node 16.9.1**

~~1. arpa_nameser.h include: The GYP files somehow didn't add `deps/cares/src/lib` as include path~~

~~2. libuv didn't compile with epoll.c.~~ This patch needs to be also sent upstream

Besides these problems, problems with node 16.6.1 were also persistent without patches

**Comment by thunder-coding** [comment]
@xeffyr, I got it working for aarch64 and arm. And I tested the binaries and they worked. And only i686 is failing with undefined references for functions declared in `<atomic>`, I even added a `-latomic` flag but it didn't work. And some weird thing is that it shows these errors in a file while doesn't even use any of the methods declared in `<atomic>`. I need your help with this so that nodejs 16 can be available on Termux as soon as possible

**Comment by Grimler91** [comment]
Flag order could matter (see https://github.com/termux/termux-packages/issues/3092). Try if patching [histograp.gyp](https://github.com/nodejs/node/blob/2765f2af79bd8bdfb2f8e5a6473ac1c278521fd4/deps/histogram/histogram.gyp), adding `'ldflags': [ '-latomic' ],` (or similar) there instead works, and else maybe `-u __atomic_fetch_add_8 -u __atomic_load_8 -u __atomic_compare_exchange_8 -latomic` as suggested in the other issue

**Comment by thunder-coding** [comment]
This PR is now ready to merge. The previous CI passed 🥳. I have also declared myself as a maintainer for this package so that this package stays updated

**Pull request merged**
