### PR TITLE
Add sha256sum to releases

### LINKED ISSUE #11874: Add Termux bootstrap sha256sum to bootstrap releases
It will make checking sha256sum easier

### PR DESCRIPTION
**Pull request by babaric-dev**
Closes #11874

### CODE REVIEW

**Comment by babaric-dev** [comment]
Please merge this PR if there are no problems 😄

**Comment by agnostic-apollo** [comment]
Create a single file with `find . -maxdepth 1 -type f -name "bootstrap-*.zip" -exec sha256sum {} \; | sed "s| ./| |g" | sort -nk2 > bootstraps.sha256sum`

**Comment by babaric-dev** [comment]
> Create a single file with `find . -maxdepth 1 -type f -name "bootstrap-*.zip" -exec sha256sum {} \; | sed "s| ./| |g" | sort -nk2 > bootstraps.sha256sum`

I have done editing. Please check.

**Comment by 2096779623** [comment]
Don't update upstream like this, Revert to the original commit:
```bash
git clone https://github.com/babaric-dev/termux-packages
cd termux-packages
git reset --hard 2035a8f
# Please squash the commit here and refer to https://github.com/termux/termux-packages/commits/master/.github/workflows/bootstrap_archives.yml to rewrite the commit message.
git push origin master -f
```

image

update upstream like this next time :) .

**Comment by babaric-dev** [comment]
I cant setup git (sighs). Can anyone help me run these commands?

**Comment by babaric-dev** [comment]
Made another PR (#11956) because I can't bear the hassle of figuring out `git` on my system. Closing this PR.

**Pull request closed without merging**
