### PR TITLE
fix(main/valgrind): x86_64 syscall patch

### LINKED ISSUE #17359: [Bug]: valgrind bad system call
### Problem description

Self explanatory.

### What steps will reproduce the bug?

Install valgrind and run any program:
```
valgrind --tool=massif ls
```

Even valgrind itself breaks:
```
valgrind --tool=massif valgrind
```

Bad system call

Note this does not happen when running `valgrind --help`

### What is the expected behavior?

Programs run as expected without valgrind (no bad syscall). But this should also be the case when invoking via valgrind

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=1167
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
x86_64
Subscribed repositories:
# sources.list
deb https://mirrors.zju.edu.cn/termux/apt/termux-main stable main
Updatable packages:
command-not-found/stable 2.2.0-6 x86_64 [upgradable from: 2.2.0-5]
libunbound/stable 1.17.1-2 x86_64 [upgradable from: 1.17.1-1]
unbound/stable 1.17.1-2 x86_64 [upgradable from: 1.17.1-1]
zstd/stable 1.5.5-1 x86_64 [upgradable from: 1.5.5]
termux-tools version:
1.38.3
Android version:
13
Kernel build information:
Linux localhost 5.15.94-windows-subsystem-for-android-20230508+ #1 SMP PREEMPT Thu May 11 14:27:58 UTC 2023 x86_64 Android
Device manufacturer:
Microsoft Corporation
Device model:
Subsystem for Android(TM)
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

### PR DESCRIPTION
**Pull request by truboxl**
Fix #17359

### CODE REVIEW

**Comment by truboxl** [comment]
@landfillbaby @Grimler91 can you confirm this issue also happens on aarch64 / arm? If so I think valgrind is broken for all platforms

**Comment by twaik** [comment]
Hmmmm. I am getting almost the same message (with different numbers) on my aarch64 device. I can confirm it is broken.

**Comment by landfillbaby** [comment]
yep it's the same for me too

**Comment by truboxl** [comment]
Ok I will merge this to fix x86_64 valgrind seccomp issue. Supposedly fixing aarch64 should also reflect on other arches.

**Pull request merged**
