### PR TITLE
fish: Update to 3.2.1

### PR DESCRIPTION
**Pull request by saurabhchardereal**

### CODE REVIEW

**Comment by swg0101** [comment]
Is this build broken? I just updated my packages and now fish is crashing (used to work before the package updates):

```~ $ fish
warning: Could not set up terminal.
warning: TERM environment variable not set.
error: Your history will not be saved.
warning-path: Unable to locate data directory derived from $HOME: '/data/.local/share/fish'.
warning-path: The error was 'Permission denied'.
warning-path: Please set $HOME to a directory where you have write access.

error: Your personal settings will not be saved.
warning-path: Unable to locate config directory derived from $HOME: '/data/.config/fish'.
warning-path: The error was 'Permission denied'.
warning-path: Please set $HOME to a directory where you have write access.

~ddata/com.ter.termux/files/usr/share/fish/config.: Invalid token '-n\'
from sourcing file ~ddata/com.ter.termux/files/usr/share/fish/config.
        called during startup
source: Error while reading file '/data/data/com.termux/files/usr/share/fish/config.fish'
~ddata/com.ter.termux/files/usr/etc/fish/config. (line 16): Missing end to balance this function definition
function __fish_command_not_found_handler --on-event fish_command_not_found
^
from sourcing file ~ddata/com.ter.termux/files/usr/etc/fish/config.
        called during startup
source: Error while reading file '/data/data/com.termux/files/usr/etc/fish/config.fish'
fish: Unknown command: e\x00\x00\x00
echo -n "$USER@$hostname $PWD "'> '
^
in command substitution
```

**Comment by Grimler91** [comment]
@swg0101 3.2.1 seem to work on my device. Please open a new issue and fill in the [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=&template=bug_report.md) so that we can reproduce the issue.

Is the error copy pasted correctly? It seem to be trying to access `~ddata/com.ter.termux/files/usr` in multiple places which seems very weird

**Comment by swg0101** [comment]
Yep, it was how it was being displayed on my Pixel 4A 5G. Will create an issue. Thanks.

**Comment by swg0101** [comment]
Issue created: https://github.com/termux/termux-packages/issues/6639

**Pull request merged**
