### PR TITLE
z3: update to 4.8.12

### PR DESCRIPTION
**Pull request by thunder-coding**

### CODE REVIEW

**Comment by thunder-coding** [comment]
The package z3 tries to declare a namespace `user` which is available in `sys/user.h` on Android which is causing build errors. Only `aarch64` builds are passing because `aarch64` doesn't have a `user` namespace

**Comment by xeffyr** [comment]
If it uses this namespace for private api, you can rename it to something like `z3_user`.

**Comment by thunder-coding** [comment]
> If it uses this namespace for private api, you can rename it to something like `z3_user`.

Probably there is no public api for z3, so we can go by renaming the variable

**Comment by xeffyr** [comment]
Public api is a libz3.so headers. `z3` consists of a binary and library.

**Review by xeffyr — APPROVED** [review]

**Pull request merged**
