### PR TITLE
bump(main/nodejs): 22.4.0

### PR DESCRIPTION
**Pull request by thunder-coding**
This PR is to just let @fornwall know that I've started working on the new release so that he doesn't duplicate the effort. I'll try to get the LTS version on track soon after

### CODE REVIEW

**Comment by thunder-coding** [comment]
There is some minor regressions as indicated by the test suite. Here are some tests which are now failing but were previously passing:

```
Done running release test-child-process-default-options: FAIL
Done running release test-child-process-env: FAIL
Done running release test-permission-fs-symlink-target-write: FAIL
Done running release test-runner-output: FAIL
Done running release test-snapshot-reproducible: FAIL
```

Otherwise there is no major regression.

**Comment by thunder-coding** [comment]
I just rechecked with older versions of node, and `test-child-process-{default-options, env}` are failing as well. This is as the test uses hardcoded paths, and internally node executes the child process using `uv_spawn()` which in turn calls `execp()`. So hardcoded paths are not being translated. We're only overriding `execve()` calls with termux-exec. I'll open a new issue to track and also override other `exec*` family of functions.

**Comment by fornwall** [comment]
> I'll open a new issue to track and also override other exec* family of functions.

@thunder-coding That is included in https://github.com/termux/termux-exec/pull/24

**Comment by thunder-coding** [comment]
> > I'll open a new issue to track and also override other exec* family of functions.
> 
> @thunder-coding That is included in [termux/termux-exec#24](https://github.com/termux/termux-exec/pull/24)
> 
> Nice work keeping node.js up to date!

Thanks for linking your PR, I'd have totally missed it (didn't expect it to be with this large change).

And for keeping Node.js upto date, it all started with my needs and now I'm doing it for fun (although it's more of a pain)

**Pull request merged**
