### PR TITLE
openssl: declare that it breaks openssl-tool << 1.1.1b-1

### PR DESCRIPTION
**Pull request by Grimler91**
To not get errors on apt update && apt upgrade

### CODE REVIEW

**Comment by tomty89** [comment]
https://wiki.debian.org/PackageTransition (case #10)
Replaces as well?

**Comment by xeffyr** [comment]
> Replaces as well?

openssl doesn't replace openssl-tool. Only configuration file was moved.
Also in this case it is better to set `conflicts` instead of `breaks` as here only file conflict.

**Comment by tomty89** [comment]
@xeffyr I think you have some misunderstanding about those options. Their names are misleading. According to the wiki page, breaks and replaces are the right ones to use. (Note that they are versioned as well.)

**Comment by Grimler91** [comment]
Yeah, should be case 10 in tomty89's link. https://www.debian.org/doc/debian-policy/ch-relationships.html#packages-which-break-other-packages-breaks also says that Replaces should be used. I've updated the PR.

**Comment by fornwall** [comment]
The updated package is now available for installation, so apt upgrades should work better.

**Pull request merged**
