### PR TITLE
chore(main/procs): Install shell completions and man page

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by licy183** [comment]
Thanks!

**Comment by AminurAlam** [comment]
fish completions dont work they are supposed to go to `$TERMUX_PREFIX/share/fish/completions/procs.fish`
this issue is present in 40 different packages

**Comment by Biswa96** [comment]
The fish shell completions are working fine in my setup. Also, all Linux distributions put the fish shell completions in `$PREFIX/share/fish/vendor_completions.d` directory. See the conventions here https://github.com/fish-shell/fish-shell/blob/master/doc_src/completions.rst#where-to-put-completions

> The completions shipped with fish, usually installed in `/usr/share/fish/completions`
> A directory for third-party software vendors to ship their own completions for their software, usually `/usr/share/fish/vendor_completions.d`

**Comment by Biswa96** [comment]
> this issue is present in 40 different packages

The issues was solved after reinstalling packages https://discord.com/channels/641256914684084234/641256914684084237/1224074916958306425

**Pull request merged**
