### PR TITLE
Bump nnn to 4.1.1

### PR DESCRIPTION
**Pull request by thunder-coding**

### CODE REVIEW

**Comment by thunder-coding** [comment]
The new version of `nnn` requires pthread library. Interesting it complied without errors on my device

**Comment by kcubeterm** [comment]
Recently added in https://github.com/jarun/nnn/commit/284a3c4866b77f0d452d91aaf026068dd1e44cb1

**Comment by Grimler91** [comment]
On android the pthread functions are in libc. On device [libpthread just includes libc](https://github.com/termux/termux-packages/blob/d3a2c86c2397ed2be3b68be74d26d9cb6758b465/packages/ndk-sysroot/build.sh#L49). When cross-compiling we have not set up the libpthread->libc link though, so we have to patch away the attempt to link against pthread

**Comment by thunder-coding** [comment]
Removing the `-lpthread` flag fixed it 😆

**Comment by thunder-coding** [comment]
Ping: This PR is ready to merge

**Pull request merged**
