### PR TITLE
[WIP] add package: zerotier-one-gpl

### PR DESCRIPTION
**Pull request by nexplorer-3e**
package version `1.4.2` to workaround termux license restriction.
fix https://github.com/termux/termux-packages/issues/10123

almost everything (`join`, `peers`, `ping -I`) is working except `zerotier-one` cannot handle route correctly due to difference between Android and standard Linux. manually configure `ip rule` should work but it would probably mess up the routing table.

### CODE REVIEW

**Comment by TomJo2000** [comment]
It would probably be more useful to package the BSL 1.1 licensed "modern" version of the package.
And have it be packaged in the [TUR](https://github.com/termux-user-repository/tur).
That way we're not dealing with 5 year out of date software.
The build script and patches should be drop-in compatible for the TUR's build system.
The patches might need to be regenerated against 1.14.0 though.
Using the "modern" version would also make using [auto updates](https://github.com/termux/termux-packages/wiki/Auto-updating-packages) a possibility.

**Comment by TomJo2000** [comment]
I'm gonna go ahead and convert this PR to a draft pending moving it to the TUR.

**Comment by nexplorer-3e** [comment]
new pr here: https://github.com/termux-user-repository/tur/pull/1112

**Comment by nexplorer-3e** [comment]
> new pr here: [termux-user-repository/tur#1112](https://github.com/termux-user-repository/tur/pull/1112)

as this one is merged, closing the issue.

**Pull request closed without merging**
