### PR TITLE
scripts(setup-ubuntu.sh): Apply system libdirs and pkgconfig dirs to new pkgconf build

### LINKED ISSUE #22060: [Bug]: new pkgconf cannot find the pkgconfig folders during hostbuild-steps yet
### Problem description

As reported by @Biswa96 [here](https://github.com/termux/termux-packages/pull/22027#issuecomment-2450483465), the new `pkgconf`  2.3.0 build in the Dockerfile seems to be not quite ready yet but I went ahead and tried to see if I can help fix it. It was not able to find Ubuntu host's `libpng`  Cflags for a hostbuild-step.

https://github.com/termux/termux-packages/blob/524d5a80f35aa6c548f2e53a0af1a4b779b97369/scripts/setup-ubuntu.sh#L343-L355

### What steps will reproduce the bug?

```bash
scripts/run-docker.sh pkgconf -cflags libpng
```
- Result
```
Package libpng was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpng.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpng' not found
```

### What is the expected behavior?

```
-I/usr/include/libpng16
```

### System information

```shell
N/A
```

### PR DESCRIPTION
**Pull request by robertkirkman**
Fixes #22060

There are also several other methods that could be used to fix this particular problem, but the way I have written this keeps it mostly similar to how fornwall originally wrote this update, without radically changing the method too much from his general idea.

### CODE REVIEW

**Comment by Biswa96** [comment]
Could you upgrade the tuxpaint version also? It would help to check if this fix is working.

**Comment by robertkirkman** [comment]
Sure! with this commit applied to my local container, `scripts/run-docker.sh ./build-package.sh -I tuxpaint` works after I made this change to it:

```diff
--- a/x11-packages/tuxpaint/build.sh
+++ b/x11-packages/tuxpaint/build.sh
@@ -2,10 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://tuxpaint.org/
 TERMUX_PKG_DESCRIPTION="A free, award-winning drawing program for children ages 3 to 12"
 TERMUX_PKG_LICENSE="GPL-2.0"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="0.9.33"
-TERMUX_PKG_REVISION=1
+TERMUX_PKG_VERSION="0.9.34"
 TERMUX_PKG_SRCURL=https://downloads.sourceforge.net/tuxpaint/tuxpaint-${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=8701ec5082d48a00ba2f408c7c48cf592aa82b60f50dd6d4b6574fac6b48dc76
+TERMUX_PKG_SHA256=b761df5ed386a9e04a6809ab3e0cbf2126f10b770527cb2b5f190ff5e370ed03
 TERMUX_PKG_DEPENDS="fontconfig, fribidi, glib, libandroid-wordexp, libcairo, libimagequant, libpaper, libpng, librsvg, pango, sdl2, sdl2-gfx, sdl2-image, sdl2-mixer, sdl2-pango, sdl2-ttf, zlib"
 TERMUX_PKG_BUILD_IN_SRC=true
 TERMUX_PKG_HOSTBUILD=true
```
Should I also make a PR for that or will the termuxbot2 be able to automatically try again after the docker image is fixed?

I tried without `-I` first, but currently the gnome.org download for the `gtk3` dependency has an error 503 so, that will not work for the time being.

image


Also it might be helpful for future reference for anyone, that the way I obtained the values I placed in the variables is by doing this.

```bash
sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
sudo apt update
sudo apt install devscripts
apt source pkgconf
cd pkgconf-*
debian/system-libdirs.sh gcc
grep debian/rules -e pkg-config-dir
``

**Comment by Biswa96** [comment]
> Should I also make a PR for that or will the termuxbot2 be able to automatically try again after the docker image is fixed?

Yeah, termuxbot2 will update tuxpaint automatically after any maintainer close the auto-update issue. Just I was not sure if this change actually fixes the tuxpaint issue. Thanks for checking that.

**Comment by robertkirkman** [comment]
I will temporarily mark it as a draft because I want to test it with the command `scripts/run-docker.sh ./build-package.sh -I -a all nodejs`. If it succeeds then that means that it worked for a package that is marked as having a hostbuild step depending on multiarch host packages in the comments.

**Review by twaik — COMMENTED** [review]
Currently I have some problems with updating kitty (fails to find libxml during host-build step) and this solution completely fixes it.

**Review by twaik — APPROVED** [review]

**Comment by fornwall** [comment]
👍 Nice! I think something like

```sh
HOST_TRIPLET=$(gcc -dumpmachine)
PKG_CONFIG_DIRS=$(grep DefaultSearchPaths: /usr/share/pkgconfig/personality.d/${HOST_TRIPLET}.personality | cut -d ' ' -f 2)
SYSTEM_LIBDIRS=$(grep SystemLibraryPaths: /usr/share/pkgconfig/personality.d/${HOST_TRIPLET}.personality | cut -d ' ' -f 2)
```

could be an alternative to setup the paths, to make it more clear where they come from and working across arches and possible future upstream changes.

**Comment by robertkirkman** [comment]
Thank you, that also works and I applied that change now. I didn't realize before that it is actually possible to obtain those values without downloading the Ubuntu or Debian source package of pkgconf.

**Comment by twaik** [comment]
I'll merge it in 10 hours if nobody minds.

**Pull request merged**
