### PR TITLE
chore(x11/firefox): change to unofficial branding

### PR DESCRIPTION
**Pull request by truboxl**

### CODE REVIEW

**Comment by thunder-coding** [comment]
Did you try reaching out to Mozilla trademark email which I sent via Matrix? Maybe incase we get to keep the branding

**Comment by twaik** [comment]
So what should we do? Wait or merge this?

**Comment by Maxython** [comment]
> Did you try reaching out to Mozilla trademark email which I sent via Matrix? Maybe incase we get to keep the branding

Wouldn't it be better to ping [Mozilla](https://github.com/mozilla) developers right here?

> So what should we do? Wait or merge this?

So I understand it’s better to wait.

**Comment by twaik** [comment]
> Wouldn't it be better to ping [Mozilla](https://github.com/mozilla) developers right here?

I think so.

**Comment by truboxl** [comment]
Closing. Received word that we are good to go on a "trust" basis as long as keeping it as close to "official" as possible.

<details>

```
I'd love to read that.

At this point, I'm going to trust that y'all are doing the right things with regards to Firefox, mainly keeping it as close to "official" as possible.

So you're free to distribute it without an agreement in place.

If y'all need anything in the future, don't hesitate to reach out.

Mike Kaply
```

</details>

**Pull request closed without merging**
