### PR TITLE
some disabled package updates

### PR DESCRIPTION
**Pull request by vishalbiswas**
openjdk now builds for arm, i686 and x86_64.
aarch64 build fails because of `__thread`
I've also removed `libsaproc` and switched jvm back to server.
JVM features are manually tweaked depending on arch.
Ahead-of-time (AOT) compilation is only supported on x86_64 and as such disabled because it requires elfutils.

### CODE REVIEW

**Comment by vishalbiswas** [comment]
If anybody wants to try out the packages and provide feedback you can download them from my drive folder -> https://drive.google.com/drive/folders/0B8Q4yBRb9PSHQ2lfVVYzLU5JelE
These packages will be available until the next time I update them.
Download according to your arch. AArch64 users can use arm binaries as they don't link against any system lib.
I'd like to know your take on the performance. Do you think that its usable?

**Comment by Wetitpig** [comment]
WARNING: linker: /data/data/com.termux/files/usr/lib/jvm/openjdk-9/lib/jli/libjli.so: unsupported flags DT_FLAGS_1=0x81

**Comment by vishalbiswas** [comment]
@Wetitpig which arch are you one? Does the program stop working or continue to run?

**Comment by Harshiv-Patel** [comment]
I too receive the same warnings as @Wetitpig ,
I'm on ARM, (I downloaded the 2nd ARM archive, unpacked it an copied all the stuff. Is that correct method? )
These warnings are given for java, keytool, jserver and jconsole,
The "java" command and keytool seem to run, only issue being the unwanted warnings. Some screenshots may make it clear:
screenshot_2017-05-15-17-57-46
screenshot_2017-05-15-17-58-01
screenshot_2017-05-15-17-58-24
screenshot_2017-05-15-17-59-16
====================================================
How do I use the JDK tools here ? like javac & javah and so on ?
Or they are will be ported in future?

**Comment by Wetitpig** [comment]
Right. I am also on ARM

**Comment by vishalbiswas** [comment]
@Harshiv-Patel
You need to install it with `apt install <file path>`
There are 2 debs for each architecture. The other one contains the javac and other jdk binaries.
You can ignore the warnings, they are not fatal.

**Comment by Wetitpig** [comment]
Well. They are not fatal, but may disrupt normal usage... So not ready to be released right?

**Comment by TheDiamondYT1** [comment]
```
(Reading database ... 12004 files and directories currently installed.)
Preparing to unpack java.deb ...
Unpacking openjdk-9-jdk-headless (9.2017.5.12) over (9.2017.5.12) ...
dpkg: dependency problems prevent configuration of openjdk-9-jdk-headless:
 openjdk-9-jdk-headless depends on openjdk-9-jre-headless; however:
  Package openjdk-9-jre-headless is not installed.

dpkg: error processing package openjdk-9-jdk-headless (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openjdk-9-jdk-headless
```
So apparently the package depends on itself? Downloaded from google drive

**Comment by vishalbiswas** [comment]
@TheDiamondYT1 there is openjdk-9-jre-headless as well in that folder

**Comment by TheDiamondYT1** [comment]
@vishalbiswas 
```
dpkg: dependency problems prevent configuration of openjdk-9-jre-headless:
 openjdk-9-jre-headless depends on ca-certificates-java; however:
  Package ca-certificates-java is not installed.

dpkg: error processing package openjdk-9-jre-headless (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openjdk-9-jre-headless
```

**Comment by TheDiamondYT1** [comment]
Can confirm that maven works (almost)

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project voxelwind-api: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x1850bb7) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x1850bb7 -> [Help 1]
```
This could be a project issue but it doesnt look like it.

**Comment by vishalbiswas** [comment]
@TheDiamondYT1 You need to export that symbol. Its a new thing in Java 9.
And yes, maven, gradle as well as tomcat work.

**Comment by TheDiamondYT1** [comment]
Im guessing it will automatically be exported when download from the termux repository? 

Also, @fornwall should add more maintainers to this repository, since he doesnt read PRs much.

**Comment by vishalbiswas** [comment]
@TheDiamondYT1 he does, but its a lot of work.

**Comment by TheDiamondYT1** [comment]
@vishalbiswas My point was

> @fornwall should add more maintainers to this repository

**Comment by vishalbiswas** [comment]
@TheDiamondYT1 this pr has been way past its bedtime. you are free to continue this conversation at 
https://gitter.im/termux/termux

**Comment by TheDiamondYT1** [comment]
### For anyome who wants to rest some features or this PR, download Java from the google drive folder above and run the following command.

```bash
curl -L https://github.com/TheDiamondYT1/termux-java-test/blob/master/test.sh | bash
```

What it does:

1. Makes sure Java is installed
2. Downloads Maven
3. Compiles a basic "Hello World" Java project
4. Creates a new Maven project
5. Builds [a Minecraft server](https://github.com/voxelwind/voxelwind)

...and i'll add more tests. The hello world test is currently broken :sadface:

**Comment by vishalbiswas** [comment]
That link should be `curl -L https://raw.githubusercontent.com/TheDiamondYT1/termux-java-test/master/test.sh | bash`




Vishal Biswas







On Sun, Jun 11, 2017 at 6:46 AM +0530, "Luke | 14" <notifications@github.com> wrote:










For anyome who wants to rest some features or this PR, download Java from the google drive folder above and run the following command.
curl -L https://github.com/TheDiamondYT1/termux-java-test/blob/master/test.sh | bash


What it does:

Makes sure Java is installed
Downloads Maven
Compiles a basic "Hello World" Java project
Creates a new Maven project
Builds a Minecraft server



...and i'll add more tests. The hello world test is currently broken :sadface:

**Comment by Harshiv-Patel** [comment]
> Well. They are not fatal, but may disrupt normal usage... So not ready to be released right?

Those warnings break 'javacomplete' vim plugin that depends on jdk,
so many applications like that would be broken, 
not Yet ready to release, I suppose.

**Pull request merged**
