### PR TITLE
add jpeg8 to libturbo-jpeg

### LINKED ISSUE #1891: [libjpeg-turbo] enable jpeg8 features?
For that `--with-jpeg8` needs to be stated explicitly to `configure`.

Any reason not to do it in Termux? FYR, Ubuntu built libjpeg-turbo with that and additionally built libjpeg6 and libjpeg9 from ijs. In Arch none of the ijs libjpeg is provided, and the libjpeg-turbo build used by basically every package is built with that.

P.S. Not sure if packages that dep on libjpeg-turbo needs to rebuilt afterwards

### PR DESCRIPTION
**Pull request by stephengroat**
closes #1891

### CODE REVIEW

**Comment by fornwall** [comment]
Does this change the library ABI, so that all packages linking against libturbo-jpeg needs to be revision-bumped and rebuilt?

**Comment by stephengroat** [comment]
@fornwall i'll git diff the dev packages and check it

**Comment by stephengroat** [comment]
diff between the `dev` packages:

```
diff -r new/data/data/com.termux/files/usr/include/jconfig.h old/data/data/com.termux/files/usr/include/jconfig.h
5c5
< #define JPEG_LIB_VERSION 80
---
> #define JPEG_LIB_VERSION 62
49c49
< /* #undef MEM_SRCDST_SUPPORTED */
---
> #define MEM_SRCDST_SUPPORTED 1
```

**Comment by stephengroat** [comment]
also, if you think rebuilding all reverse depends is needed:

```
libjpeg-turbo
Reverse Depends:
  gdk-pixbuf
  zbar
  qpdf
  poppler
  netpbm
  libtiff
  libjpeg-turbo-progs
  libjpeg-turbo-dev
  libjasper
  libgd
  leptonica
  imagemagick
  gst-plugins-good
  graphicsmagick
  gmic
  ghostscript
  gegl
```

**Comment by xeffyr** [comment]
Closing in favor of https://github.com/termux/termux-packages/pull/4105.

**Pull request closed without merging**
