### PR TITLE
gobject-introspection

### PR DESCRIPTION
**Pull request by Ludea**

### CODE REVIEW

**Comment by Ludea** [comment]
Same issue as x11 repo, python is not found

**Comment by Ludea** [comment]
Found into log `|Program python3 found: YES (/usr/bin/python3) `

**Comment by Ludea** [comment]
Mesos doesn't found python header https://gitlab.gnome.org/GNOME/gobject-introspection/-/blob/master/meson.build#L161

**Comment by Ludea** [comment]
@xeffyr maybe an idea ?

**Comment by xeffyr** [comment]
It hardcodes use of python3.8 somewhere. Our version is 3.9.
```
Compiler stderr:
 /home/builder/.termux-build/_cache/android-r21d-api-24-v3/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: error: cannot find -lpython3.8
```

**Comment by Ludea** [comment]
https://gitlab.gnome.org/GNOME/gobject-introspection/-/blob/master/mypy.ini#L3 maybe this ?
I can not build directly on device, get permission issue :(

**Review by RossComputerGuy — COMMENTED** [review]
You forgot the end string character

**Comment by Ludea** [comment]
> You forgot the end string character

Thanks !

**Comment by Ludea** [comment]
I have no idea how to fix issue 😒

**Comment by RossComputerGuy** [comment]
https://github.com/termux/termux-packages/issues/4213#issuecomment-524486759

**Comment by Ludea** [comment]
Thanks for the link, but python-static doesn't fix the issue

**Comment by Ludea** [comment]
@RossComputerGuy what is the command you use to build gi ?

**Comment by RossComputerGuy** [comment]
I believe meson is used to configure then ninja to build.

**Comment by Ludea** [comment]
How do you link python header ?

**Comment by RossComputerGuy** [comment]
I do not remember then

**Comment by Ludea** [comment]
Maybe specify python static path with this option https://gitlab.gnome.org/GNOME/gobject-introspection/-/blob/master/meson_options.txt#L21 ?

**Comment by nikey02** [comment]
try this 
```
apt install autoconf flex bison build-essential gtk-doc pkg-config
pip install meson mako

git clone https://gitlab.gnome.org/GNOME/gobject-introspection.git
cd gobject-introspection

export LD_PRELOAD="$PREFIX/lib/libpython3.9.so"

meson _build

cd _build

meson configure --prefix $PREFIX

ninja

ninja install

```

**Comment by xeffyr** [comment]
@nikey02 This can work inside Termux, but totally useless for cross-compiling the package.

**Comment by suhan-paradkar** [comment]
@nikey02 it doesn't work even inside termux.. fails at step meson configure

**Comment by nikey02** [comment]
what's was error @suhan-paradkar

**Comment by suhan-paradkar** [comment]
@nikey02 
```
Found ninja-1.10.2 at /data/data/com.termux/files/usr/bin/ninja
[1/54] Generating gir-glib with a custom command
FAILED: gir/GLib-2.0.gir
/data/data/com.termux/files/home/downloads/gobject-introspection-master/_build/tools/g-ir-scanner --output=gir/GLib-2.0.gir --no-libtool --quiet --reparse-validate --add-include-path /data/data/com.termux/files/home/downloads/gobject-introspection-master/_build/gir --add-include-path /data/data/com.termux/files/home/downloads/gobject-introspection-master/gir --identifier-prefix=G --symbol-prefix=g --symbol-prefix=glib --c-include=glib.h --namespace=GLib --nsversion=2.0 --library=glib-2.0 --library=gobject-2.0 --external-library --pkg=glib-2.0 --cflags-begin -I/data/data/com.termux/files/usr/include/glib-2.0 -I/data/data/com.termux/files/usr/lib/glib-2.0/include -DGLIB_COMPILATION -D__G_I18N_LIB_H__ -DGETTEXT_PACKAGE=Dummy --cflags-end /data/data/com.termux/files/usr/include/glib-2.0/gobject/glib-types.h /data/data/com.termux/files/usr/lib/glib-2.0/include/glibconfig.h /data/data/com.termux/files/usr/include/glib-2.0/glib-unix.h /data/data/com.termux/files/usr/include/glib-2.0/glib/galloca.h /data/data/com.termux/files/usr/include/glib-2.0/glib/garray.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gasyncqueue.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gatomic.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbacktrace.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbase64.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbitlock.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbookmarkfile.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbytes.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gcharset.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gchecksum.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gconvert.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdataset.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdate.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdatetime.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdir.h /data/data/com.termux/files/usr/include/glib-2.0/glib/genviron.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gerror.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gfileutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ggettext.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghash.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghmac.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghook.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghostutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gi18n-lib.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gi18n.h /data/data/com.termux/files/usr/include/glib-2.0/glib/giochannel.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gkeyfile.h /data/data/com.termux/files/usr/include/glib-2.0/glib/glist.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmacros.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmain.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmappedfile.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmarkup.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmem.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmessages.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gnode.h /data/data/com.termux/files/usr/include/glib-2.0/glib/goption.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gpattern.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gpoll.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gprimes.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gprintf.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gqsort.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gquark.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gqueue.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grand.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grcbox.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grefcount.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grefstring.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gregex.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gscanner.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gsequence.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gshell.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gslice.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gslist.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gspawn.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstdio.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstrfuncs.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstring.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstringchunk.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtestutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gthread.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gthreadpool.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtimer.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtimezone.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtrashstack.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtree.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtypes.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gunicode.h /data/data/com.termux/files/usr/include/glib-2.0/glib/guri.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/guuid.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gvariant.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gvarianttype.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gversion.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gversionmacros.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gwin32.h ../gir/glib-2.0.c
/data/data/com.termux/files/usr/bin/sh: 1: /data/data/com.termux/files/home/downloads/gobject-introspection-master/_build/tools/g-ir-scanner: not found
ninja: build stopped: subcommand failed.
[1/55] Generating gir-glib with a custom command
FAILED: gir/GLib-2.0.gir
/data/data/com.termux/files/home/downloads/gobject-introspection-master/_build/tools/g-ir-scanner --output=gir/GLib-2.0.gir --no-libtool --quiet --reparse-validate --add-include-path /data/data/com.termux/files/home/downloads/gobject-introspection-master/_build/gir --add-include-path /data/data/com.termux/files/home/downloads/gobject-introspection-master/gir --identifier-prefix=G --symbol-prefix=g --symbol-prefix=glib --c-include=glib.h --namespace=GLib --nsversion=2.0 --library=glib-2.0 --library=gobject-2.0 --external-library --pkg=glib-2.0 --cflags-begin -I/data/data/com.termux/files/usr/include/glib-2.0 -I/data/data/com.termux/files/usr/lib/glib-2.0/include -DGLIB_COMPILATION -D__G_I18N_LIB_H__ -DGETTEXT_PACKAGE=Dummy --cflags-end /data/data/com.termux/files/usr/include/glib-2.0/gobject/glib-types.h /data/data/com.termux/files/usr/lib/glib-2.0/include/glibconfig.h /data/data/com.termux/files/usr/include/glib-2.0/glib-unix.h /data/data/com.termux/files/usr/include/glib-2.0/glib/galloca.h /data/data/com.termux/files/usr/include/glib-2.0/glib/garray.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gasyncqueue.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gatomic.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbacktrace.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbase64.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbitlock.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbookmarkfile.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gbytes.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gcharset.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gchecksum.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gconvert.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdataset.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdate.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdatetime.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gdir.h /data/data/com.termux/files/usr/include/glib-2.0/glib/genviron.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gerror.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gfileutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ggettext.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghash.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghmac.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghook.h /data/data/com.termux/files/usr/include/glib-2.0/glib/ghostutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gi18n-lib.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gi18n.h /data/data/com.termux/files/usr/include/glib-2.0/glib/giochannel.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gkeyfile.h /data/data/com.termux/files/usr/include/glib-2.0/glib/glist.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmacros.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmain.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmappedfile.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmarkup.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmem.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gmessages.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gnode.h /data/data/com.termux/files/usr/include/glib-2.0/glib/goption.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gpattern.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gpoll.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gprimes.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gprintf.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gqsort.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gquark.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gqueue.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grand.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grcbox.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grefcount.h /data/data/com.termux/files/usr/include/glib-2.0/glib/grefstring.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gregex.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gscanner.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gsequence.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gshell.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gslice.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gslist.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gspawn.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstdio.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstrfuncs.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstring.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gstringchunk.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtestutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gthread.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gthreadpool.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtimer.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtimezone.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtrashstack.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtree.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gtypes.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gunicode.h /data/data/com.termux/files/usr/include/glib-2.0/glib/guri.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gutils.h /data/data/com.termux/files/usr/include/glib-2.0/glib/guuid.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gvariant.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gvarianttype.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gversion.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gversionmacros.h /data/data/com.termux/files/usr/include/glib-2.0/glib/gwin32.h ../gir/glib-2.0.c
/data/data/com.termux/files/usr/bin/sh: 1: /data/data/com.termux/files/home/downloads/gobject-introspection-master/_build/tools/g-ir-scanner: not found
ninja: build stopped: subcommand failed.
```

**Comment by xeffyr** [comment]
That's expected because of weird command
```
export LD_PRELOAD="$PREFIX/lib/libpython3.9.so"
```
which disables termux-exec. Btw reason of doing so is unclear as `LD_PRELOAD` does nothing for compilation. It is a run time environment variable for dynamic linker to preload specific library into memory.

**Comment by nikey02** [comment]
i just borrow from this issue comment
https://github.com/termux/termux-packages/issues/4213#issuecomment-524483167

which solve `cannot locate symbol` error

**Comment by xeffyr** [comment]
@nikey02 This has to be patched at source level, i.e. linking with python library should be done at build time.

**Comment by nikey02** [comment]
i didn't know how to do that and where in meson

**Comment by Mark-Joy** [comment]
> this should work now @xeffyr @suhan-paradkar
> 
> `apt install autoconf flex bison build-essential gtk-doc pkg-config`
> 
> `pip install meson mako markdown`
> 
> `git clone https://gitlab.gnome.org/GNOME/gobject-introspection.git`
> 
> `cd gobject-introspection`
> 
> * edit tools/meson.build at line 13 & 15
> 
> > `/usr/bin/env` to `/data/data/com.termux/files/usr/bin/env`
> 
> * edit meson.build at root dir i.e gobject-introspection
> 
> > add `'c_link_args=-lpython3.9'` to `default_options`
> 
> `meson _build`
> 
> `cd _build`
> 
> `meson configure --prefix $PREFIX`
> 
> `ninja`
> 
> `ninja test`
> 
> `ninja install`

Works for me on my device.
Thank you.

**Pull request closed without merging**
