### PR TITLE
update to llvm9 and fix tools in rust

### PR DESCRIPTION
**Pull request by its-pointless**
don't merge just yet it should probably be reviewed.

### CODE REVIEW

**Comment by its-pointless** [comment]
@kcotugno want to comment?

**Comment by kcotugno** [comment]
@its-pointless LGTM!

**Comment by xeffyr** [comment]
@its-pointless Do you know why rust build fails with
```
info: checking for self-updates
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.35
   Compiling ryu v1.0.0
   Compiling serde v1.0.92
   Compiling libc v0.2.60
   Compiling fixedbitset v0.1.9
   Compiling itoa v0.4.4
   Compiling cfg-if v0.1.8
   Compiling cc v1.0.35
   Compiling unicode-width v0.1.5
   Compiling ordermap v0.3.5
   Compiling build_helper v0.1.0 (/home/builder/.termux-build/rust/src/src/build_helper)
   Compiling lazy_static v1.3.0
   Compiling getopts v0.2.19
   Compiling cmake v0.1.38
   Compiling petgraph v0.4.13
   Compiling quote v0.6.12
   Compiling filetime v0.2.4
   Compiling time v0.1.40
   Compiling num_cpus v1.8.0
   Compiling serde_derive v1.0.81
   Compiling serde_json v1.0.40
   Compiling toml v0.4.10
   Compiling bootstrap v0.0.0 (/home/builder/.termux-build/rust/src/src/bootstrap)
error: unnecessary `unsafe` block
   --> src/bootstrap/builder.rs:148:19
    |
148 |             name: unsafe { ::std::intrinsics::type_name::<S>() },
    |                   ^^^^^^ unnecessary `unsafe` block
    |
note: lint level defined here
   --> src/bootstrap/lib.rs:107:9
    |
107 | #![deny(warnings, rust_2018_idioms, unused_lifetimes)]
    |         ^^^^^^^^
    = note: `#[deny(unused_unsafe)]` implied by `#[deny(warnings)]`

error: aborting due to previous error

error: Could not compile `bootstrap`.

To learn more, run the command again with --verbose.
failed to run: /home/builder/.cargo/bin/cargo build --manifest-path /home/builder/.termux-build/rust/src/src/bootstrap/Cargo.toml
Build completed unsuccessfully in 0:00:54
cp: cannot stat './build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_macros-*.so': No such file or directory
```
?

**Comment by its-pointless** [comment]
Will look into it tommorow. I can think of several possibilties off top of my head.

**Pull request merged**
