### PR TITLE
rust: bump to link against LLVM 12

### PR DESCRIPTION
**Pull request by buttaface**
Make sure it builds on CI first.

### CODE REVIEW

**Comment by buttaface** [comment]
@its-pointless, I guess Rust 1.51 will need to be modified to work with LLVM 12?

@coolreader18 or @landfillbaby, any interest in getting this updated?

**Comment by coolreader18** [comment]
I could take a stab at this this evening, I think.

**Comment by suhan-paradkar** [comment]
@landfillbaby is right...

**Comment by roalyr** [comment]
@landfillbaby will they link llvm 12 by default?

**Comment by landfillbaby** [comment]
yes. https://github.com/rust-lang/rust/commit/3a961407c89e96811616069fa7030edf2321b159

**Comment by buttaface** [comment]
Alright, let's see if that upstream patch is enough, running it through CI now.

**Comment by landfillbaby** [comment]
oh you pushed it just a minute before i did lol

**Comment by landfillbaby** [comment]
my local docker build with the same patch just succeeded so i'm going to merge it now :)

**Pull request merged**
