### PR TITLE
new package: ghex

### PR DESCRIPTION
**Pull request by ifurther**
#10833

### CODE REVIEW

**Comment by ifurther** [comment]
the error message is 
```
FAILED: src/ghex-resources.c 
/usr/bin/glib-compile-resources ../src/src/ghex.gresource.xml --sourcedir ../src/src --c-name ghex --internal --generate --target src/ghex-resources.c --dependency-file src/ghex-resources.c.d
../src/src/ghex.gresource.xml: Failed to close file descriptor for child process (Operation not permitted).
```

**Comment by rallg** [comment]
I am the person who requested ghex on the issues forum. My build of ghex (modified from an older release, not current git) still works properly. ARM 32, unrooted, with internationalization removed from ghex.

**Comment by Grimler91** [comment]
Thanks!

**Comment by rallg** [comment]
I just installed the recent ghex package. It works on my 32-bit ARM device. Appears to work just like the hacked code I previously built for myself. Good job!

**Pull request merged**
