### PR TITLE
add(x11): new package blender

### LINKED ISSUE #11674: [Package]: Blender
### Package description

A fully integrated 3D graphics creation suite

### Home page URL

https://blender.org

### Source code URL

https://github.com/blender/blender/archive/refs/tags/v3.2.2.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

So these deps I found that are required :

[alembic](https://archlinux.org/packages/community/x86_64/alembic/)
    [boost-libs](https://archlinux.org/packages/extra/x86_64/boost-libs/)
    [desktop-file-utils](https://archlinux.org/packages/extra/x86_64/desktop-file-utils/)
    [draco](https://archlinux.org/packages/community/x86_64/draco/)
    [embree](https://archlinux.org/packages/community/x86_64/embree/)
    [ffmpeg](https://archlinux.org/packages/extra/x86_64/ffmpeg/)
    [fftw](https://archlinux.org/packages/extra/x86_64/fftw/)
    [freetype2](https://archlinux.org/packages/extra/x86_64/freetype2/)
    [glew](https://archlinux.org/packages/extra/x86_64/glew/)
    [hicolor-icon-theme](https://archlinux.org/packages/extra/any/hicolor-icon-theme/)
    jack ([pipewire-jack](https://archlinux.org/packages/extra/x86_64/pipewire-jack/), [jack2](https://archlinux.org/packages/extra/x86_64/jack2/))
    [jemalloc](https://archlinux.org/packages/extra/x86_64/jemalloc/)
    [libharu](https://archlinux.org/packages/community/x86_64/libharu/)
    [libpng](https://archlinux.org/packages/extra/x86_64/libpng/)
    [libsndfile](https://archlinux.org/packages/extra/x86_64/libsndfile/)
    [libspnav](https://archlinux.org/packages/extra/x86_64/libspnav/)
    [libtiff](https://archlinux.org/packages/extra/x86_64/libtiff/)
    [log4cplus](https://archlinux.org/packages/community/x86_64/log4cplus/)
    [openal](https://archlinux.org/packages/extra/x86_64/openal/)
    [opencollada](https://archlinux.org/packages/community/x86_64/opencollada/)
    [opencolorio](https://archlinux.org/packages/extra/x86_64/opencolorio/)
    [openexr](https://archlinux.org/packages/extra/x86_64/openexr/)
    [openimagedenoise](https://archlinux.org/packages/community/x86_64/openimagedenoise/)
    [openimageio](https://archlinux.org/packages/community/x86_64/openimageio/)
    [openjpeg2](https://archlinux.org/packages/extra/x86_64/openjpeg2/)
    [openshadinglanguage](https://archlinux.org/packages/community/x86_64/openshadinglanguage/)
    [opensubdiv](https://archlinux.org/packages/community/x86_64/opensubdiv/)
    [openvdb](https://archlinux.org/packages/community/x86_64/openvdb/)
    [openxr](https://archlinux.org/packages/community/x86_64/openxr/)
    [potrace](https://archlinux.org/packages/extra/x86_64/potrace/)
    [ptex](https://archlinux.org/packages/community/x86_64/ptex/)
    [python](https://archlinux.org/packages/core/x86_64/python/)
    [python-numpy](https://archlinux.org/packages/extra/x86_64/python-numpy/)
    [python-requests](https://archlinux.org/packages/extra/any/python-requests/)
    [sdl2](https://archlinux.org/packages/extra/x86_64/sdl2/)
    [shared-mime-info](https://archlinux.org/packages/extra/x86_64/shared-mime-info/)
    [xdg-utils](https://archlinux.org/packages/extra/any/xdg-utils/)
    [cuda](https://archlinux.org/packages/community/x86_64/cuda/) (optional) - cycles renderer cuda support
    [boost](https://archlinux.org/packages/extra/x86_64/boost/) (make)
    [cmake](https://archlinux.org/packages/extra/x86_64/cmake/) (make)
    [cuda](https://archlinux.org/packages/community/x86_64/cuda/) (make)
    [git](https://archlinux.org/packages/extra/x86_64/git/) (make)
    [llvm](https://archlinux.org/packages/extra/x86_64/llvm/) (make)
    [mesa](https://archlinux.org/packages/extra/x86_64/mesa/) (make)
    [ninja](https://archlinux.org/packages/community/x86_64/ninja/) (make)

### PR DESCRIPTION
**Pull request by T-Dynamos**
Closes #11674 
```python
Blender Configuration
=====================

  Build Options:
  - WITH_ALEMBIC                    ON
  - WITH_BULLET                     ON
  - WITH_CLANG                      ON
  - WITH_CYCLES                     ON
  - WITH_FFTW3                      ON
  - WITH_FREESTYLE                  ON
  - WITH_GMP                        ON
  - WITH_HARU                       OFF
  - WITH_IK_ITASC                   ON
  - WITH_IK_SOLVER                  ON
  - WITH_INPUT_NDOF                 ON
  - WITH_INPUT_IME                  
  - WITH_INTERNATIONAL              ON
  - WITH_OPENCOLLADA                OFF
  - WITH_OPENCOLORIO                ON
  - WITH_OPENIMAGEDENOISE           OFF
  - WITH_OPENVDB                    ON
  - WITH_POTRACE                    ON
  - WITH_PUGIXML                    ON
  - WITH_QUADRIFLOW                 ON
  - WITH_TBB                        ON
  - WITH_USD                        OFF
  - WITH_XR_OPENXR                  OFF

  Compiler Options:
  - WITH_BUILDINFO                  ON
  - WITH_OPENMP                     ON

  System Options:
  - WITH_INSTALL_PORTABLE           ON
  - WITH_MEM_JEMALLOC               OFF
  - WITH_MEM_VALGRIND               OFF
  - WITH_SYSTEM_GLEW                OFF
  - WITH_X11_ALPHA                  ON
  - WITH_X11_XF86VMODE              ON
  - WITH_X11_XFIXES                 ON
  - WITH_X11_XINPUT                 ON

  Image Formats:
  - WITH_IMAGE_CINEON               ON
  - WITH_IMAGE_DDS                  ON
  - WITH_IMAGE_HDR                  ON
  - WITH_IMAGE_OPENEXR              ON
  - WITH_IMAGE_OPENJPEG             ON
  - WITH_IMAGE_TIFF                 ON
  - WITH_OPENIMAGEIO                ON

  Audio:
  - WITH_CODEC_AVI                  ON
  - WITH_CODEC_FFMPEG               ON
  - WITH_CODEC_SNDFILE              ON
  - WITH_COREAUDIO                  OFF
  - WITH_JACK                       OFF
  - WITH_JACK_DYNLOAD               OFF
  - WITH_OPENAL                     ON
  - WITH_PULSEAUDIO                 ON
  - WITH_PULSEAUDIO_DYNLOAD         OFF
  - WITH_SDL                        ON
  - WITH_SDL_DYNLOAD                OFF
  - WITH_WASAPI                     OFF

  Compression:
  - WITH_LZMA                       ON
  - WITH_LZO                        ON

  Python:
  - WITH_PYTHON_INSTALL             ON
  - WITH_PYTHON_INSTALL_NUMPY       OFF
  - WITH_PYTHON_INSTALL_ZSTANDARD   OFF
  - WITH_PYTHON_MODULE              OFF
  - WITH_PYTHON_SAFETY              OFF

  Modifiers:
  - WITH_MOD_FLUID                  ON
  - WITH_MOD_OCEANSIM               ON
  - WITH_MOD_REMESH                 ON

  OpenGL:
  - WITH_GL_EGL                     OFF
  - WITH_GL_PROFILE_ES20            OFF
  - WITH_GLEW_ES                    OFF
```
SEE : https://projects.blender.org/blender/blender/issues/105686

### CODE REVIEW

**Review by PraveenNanda124 — COMMENTED** [review]
Great work

**Comment by T-Dynamos** [comment]
Can somebody tell me why x86_64 build is failing?

**Comment by 2096779623** [comment]
> Can somebody tell me why x86_64 build is failing?

```bash
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   SUPPORT_SSE_BUILD_EXITCODE (advanced)
   SUPPORT_SSE_BUILD_EXITCODE__TRYRUN_OUTPUT (advanced)
For details see /home/builder/.termux-build/blender/build/TryRunResults.cmake
-- Performing Test SUPPORT_SSE_BUILD - Failed
```
SSE should be disable, because it may throw an error like `error: unknown FP unit 'sse'`.

**Comment by T-Dynamos** [comment]
I have one more question, How to run file compiled for specific arch in build system. Here build is failing beacause of this.

**Comment by 2096779623** [comment]
> I have one more question, How to run file compiled for specific arch in build system. Here build is failing beacause of this.

Example:
https://github.com/termux/termux-packages/blob/47746fb1d47dacda97649ab7438297ac1c691bf6/packages/pypy/build.sh#L67-L71

**Comment by T-Dynamos** [comment]
Blender doesn't support cross compiling. So it should be built on device itself. 

Also while running script on arm linux:
```
This script supports only x86_64 GNU/Linux systems.
```

**Comment by Maxython** [comment]
> Blender doesn't support cross compiling. So it should be built on device itself.
> 
> Also while running script on arm linux:
> 
> ```
> This script supports only x86_64 GNU/Linux systems.
> ```

Bro, https://archlinuxarm.org/packages/aarch64/blender

**Comment by T-Dynamos** [comment]
> > Blender doesn't support cross compiling. So it should be built on device itself.
> > Also while running script on arm linux:
> > ```
> > This script supports only x86_64 GNU/Linux systems.
> > ```
> 
> Bro, https://archlinuxarm.org/packages/aarch64/blender

I was taking about termux build scripts.
See : https://app.circleci.com/pipelines/github/T-Dynamos/chromium-build/14/workflows/5531ed0f-9ca7-419c-b3d8-9ae2fc0dd3fa/jobs/10/parallel-runs/0/steps/0-102
This was linux arm.

**Comment by T-Dynamos** [comment]
Switching to tur.

**Comment by astroskyoffical** [comment]
Sorry for bumping this. Can you please consider updating or making a separate version with the latest blender beta.  They have added Vulkan support for the entire gui.   The reason I say this is we now have Vulkan wrapper drivers in termux native.  This exposes prop drivers and the gains in benchmarks are HUGE.  I'm talking 10x.  The only issue is open gl currently doesn't work well with these drivers untill zink is pushed to the latest in termux packages. However anything running in Vulkan works amazingly.   I really am asking you could consider what I'm saying. This setup will enable profound speed increases

**Pull request closed without merging**
