### PR TITLE
swi-prolog: install documentation

### PR DESCRIPTION
**Pull request by erlanger**
Add documentation for swi prolog, hopefully will solve issues detailed in https://github.com/termux/termux-packages/issues/4330

### CODE REVIEW

**Comment by erlanger** [comment]
Should I just wait until setup-ubuntu.sh runs?

**Comment by xeffyr** [comment]
Still fails with:
```
[1059/1079] Generating jpldoc.tex
FAILED: packages/jpl/jpldoc.tex 
cd /home/builder/.termux-build/swi-prolog/build/packages/jpl && /home/builder/.termux-build/swi-prolog/host-build/src/swipl -x /home/builder/.termux-build/swi-prolog/build/man/pldoc2tex -- --out=jpldoc.tex --subsection "library('jpl')"
ERROR: /home/builder/.termux-build/swi-prolog/src/man/pldoc2tex.pl:48: pltotex:main source_sink `library(jpl)' does not exist
[1060/1079] Generating yaml.html
ninja: build stopped: subcommand failed.
```

**Comment by erlanger** [comment]
Ah, I think it needs the i386 openjdk

**Comment by erlanger** [comment]
The problem is with the i686 build, this is the cause:
```
-- Found JNI: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjawt.so  
```
so I get this error:
```
[859/1077] Linking C shared module packages/jpl/libjpl.so
FAILED: packages/jpl/libjpl.so 
: && /usr/bin/cc -fPIC -m32 -O2  -m32 -shared  -o packages/jpl/libjpl.so packages/jpl/CMakeFiles/plugin_libjpl.dir/src/c/jpl.c.o -L/usr/lib/jvm/java-8-openjdk-amd64/include  -L/usr/lib/jvm/java-8-openjdk-amd64/include/linux -Wl,-rpath,/usr/lib/jvm/java-8-openjdk-amd64/include:/usr/lib/jvm/java-8-openjdk-amd64/include/linux:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server:/home/builder/.termux-build/swi-prolog/host-build/src: -lpthread /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so src/libswipl.so.8.1.14 && :
/usr/bin/ld: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
[868/1077] Generating pldoc2tex
ninja: build stopped: subcommand failed.
```
cmake is picking up the wrong JNI directory.

**Pull request closed without merging**
