### PR TITLE
enhance(x11/opencv): Enable GUI features with Qt5 and opencv_contrib modules

### LINKED ISSUE #17542: [Package]: opencv with GUI support
### Why is it worth to add this package?

Hey everyone. 
I'd like to suggest a package addition to the termux. but before that I'd also like to thank all of you for your time and effort in making all of this a reality. thank you all very much. 

now here's my suggestion if you don't mind: 

I noticed termux only offers a headless version of opencv that has no gui support for obvious reason. 

However I also found out there's termux-x11. now knowing that termux also offers supports GUI, it'd be a great idea imho, to also have the GUI version. it allows for complete support of opencv and lots and lots of computer vision related tasks. this allows you to work on the same codebase on the go right from your cell phone. this is not the case with the current headless version. 

I'd like to also ask for the contrib version which has a wealth of algorithms compared to the normal version. 

What do you think? 

### Home page URL

_No response_

### Source code URL

https://opencv.org/

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

Apparently this is doable without much of a hassle and works flawlessly as well ( see ref [here](https://www.reddit.com/r/termux/comments/15drlwt/how_do_you_build_an_opencv_package_supporting/ju7qvf4/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button)  )

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes #17542

### CODE REVIEW

**Comment by Biswa96** [comment]
I copied the idea of two source tarballs from virglrenderer-android's build.sh. I do not know if this can be auto-updated.

**Comment by licy183** [comment]
`python-torch` depends on `opencv`. If `opencv` is moved to `x11-packages`, `python-torch` and its revdumps should also be move to `x11-packages` too.

**Comment by Biswa96** [comment]
> `python-torch` depends on `opencv`. If `opencv` is moved to `x11-packages`, `python-torch` and its revdumps should also be move to `x11-packages` too.

Thanks for the review. I have moved them to x11-packages.

**Comment by Biswa96** [comment]
CI is running out of space. I do not how to fix that.

**Comment by Biswa96** [comment]
CI is running out of space. I think the pytoch packages should be moved one-by-one.

**Comment by truboxl** [comment]
Can add one of the packages that need big space to `scripts/big-pkgs.list`

**Comment by Biswa96** [comment]
Would it be possible to review this pull request please?

**Comment by Coderx7** [comment]
can we expect this to hopefully get merged any time soon?

**Review by licy183 — APPROVED** [review]
LGTM.

I'll merge this 6 hours later if there is nobl more review. Thanks!

**Comment by Coderx7** [comment]
@licy183 could you kindly merge this?

**Pull request merged**
