### PR TITLE
enhance(opencv-python):  depend on python-numpy

### PR DESCRIPTION
**Pull request by T-Dynamos**
And the version in file was 1.23.3 but in repo was 1.23.4

### CODE REVIEW

**Comment by T-Dynamos** [comment]
CI didn't build it

**Comment by 2096779623** [comment]
The numpy version specified by `opencv-python` is `1.23.3`, and the current version of `python-numpy` is `1.23.4`

**Comment by T-Dynamos** [comment]
But 

https://github.com/archlinux/svntogit-packages/blob/6b36b6c076a1ebc8aa57230069831f51dc1d68b0/trunk/PKGBUILD#L107

https://github.com/archlinux/svntogit-packages/blob/10fc7c51547418af2c92a2d79e7ff7b5382a0c1f/trunk/PKGBUILD#L7

**Comment by Grimler91** [comment]
Thanks!

**Pull request merged**
