### PR TITLE
Test branch for Android 7

### PR DESCRIPTION
**Pull request by xeffyr**
A branch with minimal API level 24 to test some things before [dropping Android 5/6](https://github.com/termux/termux-packages/issues/2874) support.

### CODE REVIEW

**Comment by xeffyr** [comment]
Compiled all packages except:
* cpio - problem with downloading sources
* golang - build error
* gst-plugins-good - build error
* imagemagick - build error
* php - tells that iconv library should be reinstalled
* rust - just skipped
* zbar - depends on imagemagick which cannot be compiled

**Comment by fornwall** [comment]
> php - tells that iconv library should be reinstalled

This was a problem on the master branch and has just been fixed there.

**Comment by Grimler91** [comment]
@xeffyr what error(s) did you get for imagemagick? Something like 
```
termux-build/imagemagick/src/MagickCore/fourier.c:815:34: error:
      passing 'fftw_complex' (aka 'double [2]') to parameter of incompatible type
      '_Complex double'
      magnitude_pixels[i]=cabs(forward_pixels[i]);
```
?

**Comment by xeffyr** [comment]
Yes, I get this error.

**Comment by Grimler91** [comment]
@xeffyr Alright, should be fixed with https://github.com/termux/termux-packages/pull/3350. 

Is it okay if I force-push a rebased branch (https://github.com/Grimler91/termux-packages/commits/android-7-testing-rebased) or will that mess up bintray/gitlab-CI?

**Comment by Grimler91** [comment]
@xeffyr Which error did you get for gst-plugins-good? It works for me on rebased branch for all arches

**Comment by xeffyr** [comment]
@Grimler91 It's
```
  CCLD     libgstpng.la
gstvpxdec.c:65:15: error: use of undeclared identifier 'VP8_DEBUG_TXT_FRAME_INFO'
    {C_FLAGS (VP8_DEBUG_TXT_FRAME_INFO),
              ^
gstvpxdec.c:68:15: error: use of undeclared identifier 'VP8_DEBUG_TXT_MBLK_MODES'
    {C_FLAGS (VP8_DEBUG_TXT_MBLK_MODES),
              ^
gstvpxdec.c:71:15: error: use of undeclared identifier 'VP8_DEBUG_TXT_DC_DIFF'
    {C_FLAGS (VP8_DEBUG_TXT_DC_DIFF),
              ^
gstvpxdec.c:74:15: error: use of undeclared identifier 'VP8_DEBUG_TXT_RATE_INFO'
    {C_FLAGS (VP8_DEBUG_TXT_RATE_INFO),
              ^
4 errors generated.
```

**Comment by xeffyr** [comment]
> or will that mess up bintray/gitlab-CI?

Only force-push to protected branches will mess gitlab ci.

**Comment by xeffyr** [comment]
Now everything from [packages/](https://github.com/termux/termux-packages/tree/master/packages) (except pkgs with custom license) is available for installation from https://dl.bintray.com/xeffyr/android-7-packages.

**Comment by xeffyr** [comment]
Further work will be done in https://github.com/termux/termux-packages/tree/android-7.

**Pull request closed without merging**
