### PR TITLE
Add GNU Classpath and JamVM for Java support.

### PR DESCRIPTION
**Pull request by smallpotato000**
Trying to add Java support. Ported GNU Classpath 0.99 and JamVM 2.0.0.

### CODE REVIEW

**Comment by hepin1989** [comment]
I want sbt in my pocket.

**Comment by smallpotato000** [comment]
Deb packages tested on Nexus4 with Android 5.1.1. JamVM can run java HelloWorld compiled by ecj.

**Comment by null-dev** [comment]
What's stopping this from being merged? I would love to have Java in my pocket!

**Comment by TheDiamondYT1** [comment]
@smallpotato000 Can you give me a deb file for jamvm and classpath so i can do some testing

**Comment by fornwall** [comment]
I'm closing this:

- JamVM and GNU Classpath seems to be dead projects.
- They are rather large and complex.
- OpenJDK 9, which will hopefully be available soon, should be a better option for most.

Anyone who wants may host a third-party package repository with packages by using e.g. https://github.com/termux/termux-apt-repo.

**Pull request closed without merging**
