### PR TITLE
fix(main/ngircd): Fix seccomp crashes with setuid and setgid

### LINKED ISSUE #19771: [Bug]: ngircd Bad system call
### Problem description

Bad system call

### What steps will reproduce the bug?

~ $ ngircd
Bad system call
~ $

### What is the expected behavior?

_No response_

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~0e9DjfviBOXWtttd2exIBA==/com.termux-8HYoMe9bYHjivfMffFrpyw==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=4535
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c236,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c236,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10236
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+7b19cd2
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+7b19cd2
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.42.0
Android version:
12
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Tue Nov 28 22:29:36 CST 2023 aarch64 Android
Device manufacturer:
OPPO
Device model:
PDCM00
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

### PR DESCRIPTION
**Pull request by Biswa96**
Here are the strace output from those crashes.
    
    getgid() = 10202
    setgid(9999) = 9999
    SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x745f0e88f8, si_syscall=__NR_setgid, si_arch=AUDIT_ARCH_AARCH64}
    
    getuid() = 10202
    setuid(0) = 0
    SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x7c2c2ff918, si_syscall=__NR_setuid, si_arch=AUDIT_ARCH_AARCH64}

Fixes #19771

### CODE REVIEW

**Comment by twaik** [comment]
I checked both version from repo and version from artifact.
```
~ $ apt install ngircd
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  ngircd
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 157 kB of archives.
After this operation, 631 kB of additional disk space will be used.
Get:1 https://ro.mirror.flokinet.net/termux/termux-main stable/main aarch64 ngircd aarch64 26.1-2 [157 kB]
Fetched 157 kB in 10s (15.3 kB/s)                                                                                                                                                                                                         
Selecting previously unselected package ngircd.
(Reading database ... 89910 files and directories currently installed.)
Preparing to unpack .../ngircd_26.1-2_aarch64.deb ...
Unpacking ngircd (26.1-2) ...
Setting up ngircd (26.1-2) ...
~ $ ngircd
Bad system call
~ $ apt install ./ngircd_26.1-3_aarch64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'ngircd' instead of './ngircd_26.1-3_aarch64.deb'
The following packages will be upgraded:
  ngircd
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/160 kB of archives.
After this operation, 12.3 kB of additional disk space will be used.
Get:1 /data/data/com.termux/files/home/ngircd_26.1-3_aarch64.deb ngircd aarch64 26.1-3 [160 kB]
(Reading database ... 89939 files and directories currently installed.)
Preparing to unpack .../home/ngircd_26.1-3_aarch64.deb ...
Unpacking ngircd (26.1-3) over (26.1-2) ...
Setting up ngircd (26.1-3) ...
~ $ ngircd
~ $ 
```
I can say that bad syscall problem is gone, but I am not familiar with this program so can not do deeper tests.

**Comment by truboxl** [comment]
The fact that the bug has been lingering for so long with nobody reporting means barely anyone is using. This is why we have to limit adding packages. If there are more issues, please file more bug reports. I will merge this.

**Comment by Biswa96** [comment]
I have tested ngircd with the example conf file.

```
$ cat $PREFIX/etc/ngircd.conf
[Global]
Name = irc.example.net

$ ngircd -n
[25479:5    0] ngIRCd 26-IPv6+IRCPLUS+SSL+SYSLOG+ZLIB-aarch64/unknown/linux-android starting ...
[25479:6    0] Using configuration file "/data/data/com.termux/files/usr/etc/ngircd.conf" ...
[25479:3    0] Can't read MOTD file "/data/data/com.termux/files/usr/etc/ngircd.motd": No such file or directory
[25479:4    0] No administrative information configured but required by RFC!
[25479:6    0] Running as user u0_a202(10202), group u0_a202(10202), with PID 25479.
[25479:6    0] Not running with changed root directory.
[25479:6    0] IO subsystem: epoll (hint size 100, initial maxfd 100, masterfd 3).
[25479:2    0] Can't listen on [::]:6667: Failed to parse IP address!
[25479:6    0] Now listening on [0.0.0.0]:6667 (socket 6).
[25479:5    0] Server "irc.example.net" (on "localhost") ready.
```

**Comment by twaik** [comment]
> [25479:3    0] Can't read MOTD file "/data/data/com.termux/files/usr/etc/ngircd.motd": No such file or directory

Probably that should be fixed somewhere in build script.

> Can't listen on [::]:6667: Failed to parse IP address!

Probably it is failing to listen on IPv6.

**Pull request merged**
