### PR TITLE
Add cool-booy-tmux package

### PR DESCRIPTION
**Pull request by IMCOOLHACKERBOOY**
This PR adds the cool-booy-tmux package, which sets up tmux with a custom configuration and theme for users.

### CODE REVIEW

**Review by IMCOOLHACKERBOOY — COMMENTED** [review]
Hi, could you please approve the workflow for my PR #22560? It would be great to proceed with the changes.
Thank you!

**Comment by IMCOOLHACKERBOOY** [comment]
Hi @Grimler91 @TomJo2000, 
Could you please review and approve the workflow for my PR #22560 so I can proceed with the changes? 
Thank you!

**Comment by IMCOOLHACKERBOOY** [comment]
IMG_20241215_040856

**Comment by TomJo2000** [comment]
We don't package personal configurations.
You should look into setting up a dotfiles repository if you want to easily share your configs between multiple machines.

The ArchWiki has a nice write up on the topic.
https://wiki.archlinux.org/title/Dotfiles

**Pull request closed without merging**
