### PR TITLE
nim: update to 1.4.0

### PR DESCRIPTION
**Pull request by richboss**

### CODE REVIEW

**Comment by Grimler91** [comment]
Thanks! 

Just FYI the patch headers does not have to be updated if the patch has not changed, though it is nice to have the [line offset](https://github.com/termux/termux-packages/pull/5981/files#diff-060b7208aa13f1a2f6cdb091b738ebeb34063afe75bfb9ab464aa54d741c6073R4) etc fully correct.

**Comment by richboss** [comment]
Thanks Henrik. This is my first contribution for Termux and I was not sure
about the patches. So I tried to refresh them, which seemed to work and
boosted my confidence, too :-)

I didn't change any names, but one patch is "config-nim.cfg". Aren't all
patch filenames supposed to end with .patch?

Regards,
Richard

Henrik Grimler <notifications@github.com> schrieb am Fr., 30. Okt. 2020,
16:29:

**Comment by xeffyr** [comment]
> but one patch is "config-nim.cfg". Aren't all patch filenames supposed to end with .patch?

Thanks, I just fixed that.

**Comment by richboss** [comment]
Thank you

Leonid Pliushch <notifications@github.com> schrieb am Fr., 30. Okt. 2020,
17:25:

**Pull request merged**
