### PR TITLE
android-tools: add Termux-usb support for fastboot

### PR DESCRIPTION
**Pull request by ookiineko**

### CODE REVIEW

**Comment by Grimler91** [comment]
Please bump TERMUX_PKG_REVISION of android-tools as well

**Comment by ookiineko** [comment]
> Please bump TERMUX_PKG_REVISION of android-tools as well

ok sir, done

**Comment by Grimler91** [comment]
Thanks, nice work, really shows that it is not impossible to get libusb softwares working without root!

**Comment by ookiineko** [comment]
> Thanks, nice work, really shows that it is not impossible to get libusb softwares working without root!

thank you sir!!

fastboot does not require libusb tho xdd, i used it for getting the serial number of the phone
bcs the original /sys/bus/usb/devices/abc/xyz/interface method won't work without root

**Comment by ookiineko** [comment]
Sorry for the embarrassing typo in my last comment......

I'm a little nervous...

**Comment by ookiineko** [comment]
> > Thanks, nice work, really shows that it is not impossible to get libusb softwares working without root!
> 
> thank you sir!!
> 
> fastboot does not require libusb tho xdd, i used it for getting the serial number of the phone bcs the original /sys/bus/usb/devices/xyz/serial method won't work without root

and I found this comment in the original AOSP code

````c++
static int filter_usb_device(
...
    /* Read device serial number (if there is one).
     * We read the serial number from sysfs, since it's faster and more
     * reliable than issuing a control pipe read, and also won't
     * cause problems for devices which don't like getting descriptor
     * requests while they're in the middle of flashing.
     */
if (dev->iSerialNumber) {
...
````

but itk using libusb to get the serial num is probably better than showing nothing like this..

**Comment by Grimler91** [comment]
> > Thanks, nice work, really shows that it is not impossible to get libusb softwares working without root!
> 
> thank you sir!!
> 
> fastboot does not require libusb tho xdd, i used it for getting the serial number of the phone bcs the original /sys/bus/usb/devices/xyz/serial method won't work without root

Yes, true. We can get the serial number straight from termux-api, without involving libusb, if we extend the [UsbAPI](https://github.com/termux/termux-api/blob/master/app/src/main/java/com/termux/api/apis/UsbAPI.java). 

I was looking into this a bit before to try to get some other programs working without root. For just enumerating devices and getting serial numbers it is quite easy to hack together something, but for proper support it seemed better to write a termux-backend to libusb. Clearly fastboot doesn't need such a backend though, so having some termux-api usb functions (as well) for enumeration seems like a good idea, I'll try to clean up my previous work and push it.

**Comment by ookiineko** [comment]
> > > Thanks, nice work, really shows that it is not impossible to get libusb softwares working without root!
> > 
> > 
> > thank you sir!!
> > fastboot does not require libusb tho xdd, i used it for getting the serial number of the phone bcs the original /sys/bus/usb/devices/xyz/serial method won't work without root
> 
> Yes, true. We can get the serial number straight from termux-api, without involving libusb, if we extend the [UsbAPI](https://github.com/termux/termux-api/blob/master/app/src/main/java/com/termux/api/apis/UsbAPI.java).
> 
> I was looking into this a bit before to try to get some other programs working without root. For just enumerating devices and getting serial numbers it is quite easy to hack together something, but for proper support it seemed better to write a termux-backend to libusb. Clearly fastboot doesn't need such a backend though, so having some termux-api usb functions (as well) for enumeration seems like a good idea, I'll try to clean up my previous work and push it.

ok sir, nice to hear!
I'll close this now xdd

**Comment by Grimler91** [comment]
I think we can get this in in the meanwhile and perhaps simplify it later after termux-api has been updated

**Comment by ookiineko** [comment]
I found `fastboot getvar serialno` will print the serial num as well
should I use this and remove the dependency on libusb? xdd

**Comment by ookiineko** [comment]
maybe its possible

**Comment by ookiineko** [comment]
> I found `fastboot getvar serialno` will print the serial num as well should I use this and remove the dependency on libusb? xdd

This seems to make it more complicated......

FastBootDriver::GetVar does not return a string value, but prints it in FastBootDriver::HandleResponse.
Also, a UsbTransport is needed when instantiating FastBootDriver, which should not be used inside filter_usb_device...

**Comment by Grimler91** [comment]
I can't update the branch (probably because PR was opened from master branch), but it has been merged in https://github.com/termux/termux-packages/commit/49eab53c95f038362ce77665a06d6d2ccbb327c7, thanks

**Pull request closed without merging**
