### PR TITLE
Add package idn2

### PR DESCRIPTION
**Pull request by Hax4us**
https://github.com/termux/termux-packages/issues/2437

### CODE REVIEW

**Comment by tomty89** [comment]
Not sure if this helps the OP at all. Termux makes use of Android's `ping`, and apparently the only `whois` is provided by `busybox`. As for dnsutils, in Arch it (known as bind-tools) depends on a package called idnkit instead of libidn or libidn2.

**Comment by Hax4us** [comment]
Ohh thnx ... But I think there is no problem to add this package also ... What u think

**Comment by rybasd** [comment]
I actually need idn2 command tool to encode IDN "президент.рф" to punycode  
XN--D1ABBGF6AIIY.XN--P1AI  and then feed that punycode to whois or dig or ping like
`dig $(idn2 президент.рф)`

I believed idn2 command line tool is packaged with libidn2

**Comment by Hax4us** [comment]
Yes ... idn2 binary  packaged with libidn2

**Comment by rybasd** [comment]
Ok, then please explain: libdn2 has been added or not yet? What I see is

```
$ pkg imstall libidn2
Hit:1 https://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libidn2
```

**Comment by vishalbiswas** [comment]
@rybasd it will be available once this PR is merged

**Comment by rybasd** [comment]
@vishalbiswas thank you, and how do I know it did merge?

**Comment by fornwall** [comment]
@rybasd This pull request has now been merged and the package is now available for installation! Install it by running `pkg in libidn2`.

**Comment by rybasd** [comment]
Thanks all.
Idn2 installed but not working as i expected
```
$
$ idn2 termux.com
idn2: toAscii: could not convert string to UTF-8
$
```
Where do I further ask?

**Comment by rybasd** [comment]
Utf-8 solved by command
LANG=utf-8

**Comment by tomty89** [comment]
#2366 would fix this properly. @fornwall @Hax4us @rybasd

**Comment by tomty89** [comment]
Fixed properly with #2448.

**Comment by rybasd** [comment]
Yes, now idn2 doesn't require to execute `LANG=utf-8` command to work properly

**Pull request merged**
