### PR TITLE
Add package : Links

### PR DESCRIPTION
**Pull request by Hax4us**

### CODE REVIEW

**Comment by Auxilus** [comment]
Doesn't links require X11 support? I've buit it before /w X11 support...

**Comment by Auxilus** [comment]
I doubt the convenience of using browser based on cli, we do have w3m at
the moment, but IIRC it's usage is also not so high..

I wonder if we need another text based browser.

**Comment by Symbian9** [comment]
> Doesn't links require X11 support? I've buit it before /w X11 support...


No, *X11* not required, it is only one of many possible variants how to use Links in graphics mode:

```
$ links2 -g
```

Except *X11*, it's possible to use Links in graphics mode using *SVGAlib* and *Linux Framebuffer* too.

- http://links.twibright.com/features.php
> Links runs in graphics mode (mouse required) on X Window System (UN*X, Cygwin), SVGAlib, Linux Framebuffer, OS/2 PMShell, AtheOS GUI

**Comment by Quasic** [comment]
I primarily use w3m, but would like to try links2, because w3m sometimes falls short.

**Comment by Symbian9** [comment]
So, what still keep out this pull request from merging?

**Comment by xeffyr** [comment]
> So, what still keep out this pull request from merging?

Probably the same as what keeping other package PRs from merging...

**Comment by vishalbiswas** [comment]
Please update this package to latest links2.

Change all hardcoded paths in patches to `@TERMUX_PREFIX@`. This will be automatically substituted while applying the patch.

Probably don't need to specify mandir.

**Comment by alive4ever** [comment]
And here is links 2.18 for arm, packaged using termux-create-package
[links-arm.zip](https://github.com/termux/termux-packages/files/2802325/links-arm.zip)

**Comment by xeffyr** [comment]
Implemented in [unstable-packages](https://github.com/termux/unstable-packages) repository.
```
pkg install unstable-repo
pkg install links
```

**Comment by Symbian9** [comment]
When it could be merged in main repo?

**Comment by xeffyr** [comment]
No one knows when new packages will be merged to main repo (there are reasons preventing new packages). Though, I guess we can replace elinks which is unmaintained.

**Comment by Symbian9** [comment]
Can't launch `links`

```
Setting up ffmpeg (4.1-2) ...
$ links
CANNOT LINK EXECUTABLE DEPENDENCIES: library "libevent.so" not found
$
```

**Comment by xeffyr** [comment]
Fixed and updated.

**Pull request closed without merging**
