### PR TITLE
gstreamer: fix and enable the package

### PR DESCRIPTION
**Pull request by rnauber**
This patch makes gstreamer work with opensles and libcaca, updates it and enables the package.

https://asciinema.org/a/PzclJt6GxVb9FiBfAaVLA0JNz

### CODE REVIEW

**Comment by its-pointless** [comment]
add --with-unwind=no so it builds when you hafe already built libunwind?

**Comment by rnauber** [comment]
Thanks @its-pointless, I fixed that.

Precompiled packages can be found here: https://github.com/rnauber/termux_packages_bin

**Comment by its-pointless** [comment]
Good work on this. Couple of minor things 


also needs --with-dw=no as well for gstreamer otherwise it links with elfutils (if you built it before) which uses liblzma. This causes audio to not work on android 7+ due to standard libs using liblzma. 
This issue also causes gst-libav to fail since it tries to compile its own codecs rather than use system it links or uses lzma meaning no audio. Using --with-system-libav means smaller file and working on android 7+.

 Had to preload --gst-plugin-load=$PREFIX/usr/lib/gstreamer-1.0/libgstopensles.so to get audio. Is that normal?
 Also gst-plugins-good and gst-plugins-ugly conflict so should have TERMUX_PKG_CONFLICTS= set so installing one removes the other?

Should set TERMUX_PKG_SHA256 you can get that value by simply using sha256sum command on the archive.

**Comment by rnauber** [comment]
> Good work on this. Couple of minor things
Thank you!

> also needs --with-dw=no as well for gstreamer otherwise it links with elfutils (if you built it before) which uses liblzma. This causes audio to not work on android 7+ due to standard libs using liblzma.
> This issue also causes gst-libav to fail since it tries to compile its own codecs rather than use system it links or uses lzma meaning no audio. Using --with-system-libav means smaller file and working on android 7+.

> Had to preload --gst-plugin-load=$PREFIX/usr/lib/gstreamer-1.0/libgstopensles.so to get audio. Is that normal?
It worked for me without this, you could try to clean the .cache/gstreamer* directory beforehand... But the --gst-plugin-load-... thing seems like a suitable workaround too.

> Also gst-plugins-good and gst-plugins-ugly conflict so should have TERMUX_PKG_CONFLICTS= set so installing one removes the other? Or probably best to have a single monolithic gst plugins package.

That is very strange! On which file do they conflict?  This might be a result of the additional flags you gave. 

> Should set TERMUX_PKG_SHA256 you can get that value by simply using sha256sum command on the archive.
I did that, did I screw it up somewhere?

Would you please put your improvements in a patch/PR on rnauber/termux_packages ?
Thank you very much,
Richard

**Comment by its-pointless** [comment]
All that is really needed is in gst-libav/build.sh to use --with-system-libav
Without that gst-libav builds its embedded ffmpeg/libav and it doesn't compile for arm and causes issues with android /system/lib/liblzma.so on android 7 and above.

 Rest is me not noticing you updated your commits ... sorry.

**Comment by rnauber** [comment]
Great! Thank you @its-pointless ! I will update the binaries at https://github.com/rnauber/termux_packages_bin for others to test...

**Comment by fornwall** [comment]
Thanks - the built packages are now available for installation!

**Pull request merged**
