### PR TITLE
addpkg(main/pueue): a command-line task management tool

### LINKED ISSUE #8599: [Package]: pueue
### Package description

Pueue is a command-line task management tool for sequential and parallel execution of long-running tasks.

Simply put, it's a tool that processes a queue of shell commands. On top of that, there are a lot of convenient features and abstractions.

Since Pueue is not bound to any terminal, you can control your tasks from any terminal on the same machine. The queue will be continuously processed, even if you no longer have any active ssh sessions.

### Home page URL

_No response_

### Source code URL

https://github.com/Nukesor/pueue#pueue

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stevenxxiu**
Closes #8599.

I tested the binaries that were built.

### CODE REVIEW

**Comment by Biswa96** [comment]
The commit message should start with `addpkg(main/pueue)`. Would it be possible to add a post install script to generate shell completion files? See other rust based packages for example.

**Comment by stevenxxiu** [comment]
I changed the commit message to start with `addpkg(main/pueue)`.

> Would it be possible to add a post install script to generate shell completion files? See other rust based packages for example.

I see there's a `pueue completions` command. For which shells though?

The *Arch Linux* package only includes:

- `/usr/share/bash-completion/completions/pueue.bash`
- `/usr/share/fish/completions/pueue.fish`
- `/usr/share/zsh/site-functions/_pueue`

Won't generating this for all shells add unnecessary files, if a user only uses one shell? In my case I'd just use `pueue completions nushell ~/.local/share/pueue/`.

**Comment by truboxl** [comment]
Just generate for bash, fish and zsh. Can add additional shell completions later when needed.

**Comment by TomJo2000** [comment]
> Just generate for bash, fish and zsh. Can add additional shell completions later when needed.

The build script for `starship` should be a good reference point for that.
https://github.com/termux/termux-packages/blob/df4b49c63779c74411395a396566b7ebc41fed36/packages/starship/build.sh#L36-L61

**Comment by stevenxxiu** [comment]
I added the post-install script now.

**Review by TomJo2000 — APPROVED** [review]
LGTM

**Comment by TomJo2000** [comment]
Thank you for your contribution. :+1:

**Pull request merged**
