### PR TITLE
golang: update to 1.19

### PR DESCRIPTION
**Pull request by MedzikUser**
Update golang to latest version

### CODE REVIEW

**Comment by buttaface** [comment]
Rewrite the commit according to #10748 and we'll get it in.

**Comment by zorro** [comment]
@MedzikUser golang 1.19 has released

**Comment by tomty89** [comment]
In case you are not aware of, check out `reset --soft`, `stash` / `pop` and `push --force` of `git`.

**Comment by luisdavim** [comment]
Is there a reason for not merging this? Is it just the commit message?
Maintainers can amend the commit message with squash and merge...

**Review by 2096779623 — APPROVED** [review]

**Comment by buttaface** [comment]
> Is there a reason for not merging this? Is it just the commit message?

Probably.

> Maintainers can amend the commit message with squash and merge...

We could, but not going to do that for every pull this guy submits. We're asking him to follow a simple commit procedure for his pulls, which we try to follow ourselves for our own pulls.

**Comment by Grimler91** [comment]
Commit message looks alright, thanks

**Pull request merged**
