### PR TITLE
bat: update to 0.16.0

### PR DESCRIPTION
**Pull request by spitlo**

### CODE REVIEW

**Comment by spitlo** [comment]
I reverted a line in my original commit in hopes that the flag `LIBGIT2_SYS_USE_PKG_CONFIG` was somehow corrupted by not having the extra space, but it didn’t help of course.

I next set up a build environment locally as described [here](https://github.com/termux/termux-packages/wiki/Build-environment) and it builds successfully.

Don’t really know what to try next, any ideas?

**Comment by xeffyr** [comment]
Problem happens only when using downloaded dependencies (option `-I`) which enabled for CI.

Try to bump revision of libgit2 package, probably checks will pass at this time.

**Comment by kcubeterm** [comment]
@spitlo By the way update is available for libgit2

**Comment by spitlo** [comment]
@kcubeterm Cool, I guess bumping the version would be better than bumping the revision. Can I bump libgit2 version in this PR or do you prefer that I do it in a separate one?

**Pull request merged**
