### PR TITLE
tree-wide: set TERMUX_PKG_REVISION in all build recipes

### PR DESCRIPTION
**Pull request by Grimler91**
Policy has been to have `TERMUX_PKG_REVISION=0` per default, and remove `TERMUX_PKG_REVISION` on updates (thereby resetting the revision). Doing it this way tends to be a bit confusing for new contributors, and in review process we sometimes have to tell the author to remove the `TERMUX_PKG_REVISION` line on package updates, or to add it on commits that adds patches/fixes.
    
Lets add `TERMUX_PKG_REVISION=0` to all packages per default, and let the policy be to reset counter to 0 on package updates, without removing the line.

Please let me know if you (as in whoever reads this) think this change brings more trouble than benefit, or is bad for some other reason

### CODE REVIEW

**Comment by buttaface** [comment]
I think we'll still have to tell noobs to set it to zero, so I doubt it will help much.

**Comment by 2096779623** [comment]
Add this to [Creating new package](https://github.com/termux/termux-packages/wiki/Creating-new-package#writing-a-package-script) and write a very long comment? 

I don't think this will help much.

**Comment by ravener** [comment]
I don't think it's such a big deal, and as buttaface said we probably still have to tell them to set it to zero.

**Comment by Grimler91** [comment]
Consensus is that this is probably not very helpful, so dropping this. Thanks for the input!

**Comment by tomty89** [comment]
IMHO we can have a guideline / advice somewhere that the line should be commented with the value set to 1 on update. Should make things a bit more convenient and perhaps slightly less confusing.

**Comment by buttaface** [comment]
> IMHO we can have a guideline / advice somewhere that the line should be commented with the value set to 1 on update.

Nobody reads guidelines, including me, 😉 meanwhile we'd have commented revisions littered everywhere.

The only way to do this is to add a rule to the linter on the CI, that when the version is updated, any existing revision must be deleted. Otherwise, the CI run fails and tells them this.

All such rules __have to be enforced by the CI__, it's the only way.

**Pull request closed without merging**
