### PR TITLE
cscope: Add package

### PR DESCRIPTION
**Pull request by yumaokao**
For response to #267, added package cscope and tested on my aarch64 Android 7.1 device.

### CODE REVIEW

**Comment by Wetitpig** [comment]
The packages are designed to be cross-compiled on Ubuntu. Also you need to check if it fails on other arches.

**Comment by its-pointless** [comment]
Works fine wetitpig.

**Comment by Wetitpig** [comment]
Ok

**Comment by fornwall** [comment]
Thanks - the built cscope package is now available in the main apt repository!

**Pull request merged**
