### PR TITLE
dart: update to 2.9.2

### PR DESCRIPTION
**Pull request by xeffyr**

### CODE REVIEW

**Comment by xeffyr** [comment]
Seems it was built successfully but needs few fixes for the installation step.
```
 Running python /home/builder/termux-packages/.termux-builder/dart/src/sdk/tools/generate_buildfiles.py
ninja -C out/ReleaseAndroidIA32 create_sdk
The build took 1301.305 seconds
chmod: cannot access './out/ReleaseAndroidia32/dart-sdk/bin/*': No such file or directory
```

**Comment by Grimler91** [comment]
dart 2.10.0 has been released, so we can also check if that version works with python3

**Comment by xeffyr** [comment]
Ok, I will try it. But even if it don't support python3, a simple fix
```
mkdir -p depot_tools/fakebin
ln -sfr /usr/bin/python2 depot_tools/fakebin/python
export PATH="$(pwd)/depot_tools/fakebin:$(pwd)/depot_tools:${PATH}"
```
will be enough.

**Comment by xeffyr** [comment]
2.10.0 fails:
```
Applying patch: fix-shell-path.patch
Applying patch: sdk-runtime-bin-directory_android.cc.patch
using /tmp/goma_builder as tmpdir
INFO: creating cache dir (/tmp/goma_builder/goma_cache).
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1003 14:21:16.613371  6691 goma_init.cc:67] username mismatch: builder env:
E1003 14:21:16.878197  6691 goma_fetch.cc:234] fetch GET https://clients5.google.com/cxx-compiler-service/ping err=-1  Got HTTP error:401 dest=clients5.google.com:443 url_path_prefix=/cxx-compiler-service/ping oauth2:enabled use_ssl socket_read_timeout=10s retry_backoff=500ms .. 5s
Need to login.  Run `goma_auth login` to login.
ninja: Entering directory `out/ReleaseAndroidIA32'
[1/3139] ACTION //runtime:generate_version_cc_file(//build/toolchain/android:clang_x86)
[2/3139] STAMP obj/runtime/generate_version_cc_file.stamp
[3/3139] CXX obj/runtime/bin/libcrashpad.crashpad.o
FAILED: obj/runtime/bin/libcrashpad.crashpad.o 
/home/builder/termux-packages/.termux-builder/dart/src/depot_tools/.cipd_bin/gomacc ../../buildtools/linux-x64/clang/bin/clang++ -MMD -MF obj/runtime/bin/libcrashpad.crashpad.o.d -DANDROID -DHAVE_SYS_UIO_H -D__compiler_offsetof=__builtin_offsetof -D__GNU_SOURCE=1 -DNDEBUG -DTARGET_ARCH_IA32 -DNDEBUG -DPRODUCT -DTARGET_OS_FUCHSIA -I../../runtime -I../.. -Igen -I../../runtime/include -m32 -msse2 -mfpmath=sse -mno-omit-leaf-frame-pointer -fno-exceptions -fPIC -fcolor-diagnostics -ffunction-sections -funwind-tables -fno-short-enums -nostdinc++ --target=i686-linux-androideabi -mstack-alignment=16 -mstackrealign -Wall -Wextra -Werror -Wendif-labels -Wno-missing-field-initializers -Wno-unused-parameter -Wno-tautological-constant-compare -Wno-extra -Wno-ignored-qualifiers -Wno-type-limits -isystem../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++/include -isystem../../third_party/android_tools/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem../../third_party/android_tools/ndk/sources/android/support/include -isystem../../third_party/android_tools/ndk/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=16 -fdebug-prefix-map=/home/builder/termux-packages/.termux-builder/dart/src/sdk=../.. -no-canonical-prefixes --sysroot=/home/builder/termux-packages/.termux-builder/dart/src/sdk/third_party/android_tools/ndk/sysroot -Wheader-hygiene -Wstring-conversion -Os -fno-ident -fdata-sections -ffunction-sections -g3 -ggdb3 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -O3 -fvisibility=hidden -fvisibility-inlines-hidden -fno-omit-frame-pointer -std=c++11 -Wno-non-virtual-dtor -Wno-sign-promo -fno-rtti -fno-exceptions -c ../../runtime/bin/crashpad.cc -o obj/runtime/bin/libcrashpad.crashpad.o
E1003 14:21:17.020193  6710 gomacc_common.cc:154] failed to connect to: /tmp/goma_builder/goma.ipc: No such file or directory [2]
compiler_proxy isn't running. Run 'goma_ctl.py ensure_start'.
ninja: build stopped: subcommand failed.
Tried to run goma_ctl.py, but it failed. Try running it manually: 
	python /home/builder/termux-packages/.termux-builder/dart/src/depot_tools/.cipd_bin/goma_ctl.py ensure_start
ninja -C out/ReleaseAndroidIA32 -j1 create_sdk
BUILD FAILED
```
Reverting to 2.9.2 since this one builds without issues.

**Comment by zorro** [comment]
@xeffyr build failure of version `2.10.0` can be fixed by adding `--no-goma` option to `build.py`

**Pull request merged**
