### PR TITLE
clvk: Bump to 0.0.20230124.132813g9635d8e0

### PR DESCRIPTION
**Pull request by MrAdityaAlok**
Signed-off-by: Aditya Alok <alok@termux.dev>

### CODE REVIEW

**Comment by xtkoba** [comment]
CC: @truboxl

**Comment by truboxl** [comment]
I think I will revbump this PR once I am free but anyone can feel to fix it

**Review by truboxl — APPROVED** [review]
Thanks. Confirmed working with clinfo and clpeak on my device. I will merge and rebase this as is. May I know how the first few lines are generated?

**Comment by MrAdityaAlok** [comment]
> May I know how the first few lines are generated?

`git diff main --patch-with-stat`

**Pull request merged**
