### PR TITLE
Build termux packages with termux repo dependencies [WIP] [RFC]

### PR DESCRIPTION
**Pull request by stephengroat**
Have the basic idea working, not ready for production yet, just want some feedback

I've managed to get `apt` and `dpkg` to play nicely inside of the docker container to download and install the `.deb` dependencies from termux.net instead of rebuilding each of them individually. Saves a ton of time

Any comments, advice, ideas, etc. would be appreciated!

Remaining issues:

- `ctags`, `krb5`, `lftp`, `libgmime`, `openssh`, `git`, `qalc`, `cadaver`, `serf`, `gettext`, `mpv`, `poppler` #1723 
- `libgrpc`
- `cmake` #1149 
- `apr-util` #1734 
- `apache2`
- `linux-man-pages`, `screenfetch`, `fish`
- `valac`
- `autossh`
- `corckscrew`
- `mosh`
- `rsync`
- `apt`
- `gmic` imagemagik++??????
- `php`
- `asciicinema`, `pastebinit`, `pathpicker`, `ranger`, `termux*`, `vim-python`, `weechat`, `getmail`, `profanity` python post-install problem
- `expect` #1870
- `gst-libav` #1871 
- `gst-plugins-ugly` #1872 
- `pango` #1874 
- `texlive-bin`
- `gst-plugins-good` #1875 
- `texlive`
- `gst-plugins-bad` #1879 
- `imgflo` #1935

### CODE REVIEW

**Comment by stephengroat** [comment]
@

**Comment by vishalbiswas** [comment]
@stephengroat libllvm is a very special case. If you install it from repo, you'll get native llvm-config
I suggest we segregate it into libllvm and clang, or overwrite the native `llvm-config` with our helper script.

**Comment by fornwall** [comment]
Looks interesting! And it's a good to at least start with this as an optional build flag, as you have done.

I'm currently looking at merging the various minor PR:s you are doing about updating -dev packages and similar.

**Comment by vishalbiswas** [comment]
Where does libgprc fails?

**Comment by stephengroat** [comment]
@vishalbiswas it's having a `protobuf` and a `openssl` error (https://travis-ci.org/termux/termux-packages/jobs/262265563#L1331)

i've tried adding `-I$TERMUX_PREFIX/include`, but it still can't seem to find it. any ideas?

**Comment by vishalbiswas** [comment]
@stephengroat sorry for late response. Your reply got drowned in the sea of notifications.

It is failing because libgrpc depends on host-build of protobuf, which does not take place because we install it from termux repo.

There are two ways tp solve this.

1. Add protobuf to `setup-ubuntu.sh` and use that.
2. Add protobuf to `TERMUX_PKG_BUILD_DEPENDS`, and your travis-ci should be configured to always build these packages instead of installing them. This seems like a better solution to me.

**Comment by its-pointless** [comment]
Cmus fails because it tries to build oss support. Since it only supports pulse `export CONFIG_OSS=n` during pre configure needs to be added i believe.

**Comment by its-pointless** [comment]
i was having an issue building notmuch because it was not linking libc++_shared on a certain arch only (arm if i recall).

**Comment by stephengroat** [comment]
@fornwall `tcl` needs a specific `libsqlite` src file to do it's thing. before i do the pr, is there any way that i could copy it into a directory for the dev package?

**Comment by fornwall** [comment]
@stephengroat I think it's best if the tcl build downloads the file itself.

**Comment by stephengroat** [comment]
@fornwall is the file from `libsqlite` version-specific to the version of `libsqlite`?

**Comment by fornwall** [comment]
@stephengroat It seems so, it's being actively developed: https://github.com/mackyle/sqlite/commits/master/src/tclsqlite.c

One possible solution would be to build the file as part of libsqlite, and then extract it into a subpackage like `tcl-sqlite` that would depend on `libsqlite` and `tcl`.

**Comment by stephengroat** [comment]
@fornwall but it's linked against the `tcl` library, wouldn't that be a circular dependency?

**Comment by stephengroat** [comment]
@forwall for `cmake`, I'm seeing this error. Have you ever seen anything like it?

```
Scanning dependencies of target CMakeServerLib
[ 84%] Building CXX object Source/CMakeFiles/CMakeServerLib.dir/cmFileMonitor.cxx.o
In file included from /home/builder/.termux-build/cmake/src/Source/cmFileMonitor.cxx:10:
In file included from /home/builder/.termux-build/_lib/15.2-aarch64-21-v12/lib/gcc/aarch64-linux-android/4.9.x/../../../../include/c++/4.9.x/unordered_map:369:
In file included from /home/builder/.termux-build/_lib/15.2-aarch64-21-v12/lib/gcc/aarch64-linux-android/4.9.x/../../../../include/c++/4.9.x/__hash_table:19:
/home/builder/.termux-build/_lib/15.2-aarch64-21-v12/lib/gcc/aarch64-linux-android/4.9.x/../../../../include/c++/4.9.x/cmath:313:9: error: 
      no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
```

**Comment by stephengroat** [comment]
@fornwall ping https://github.com/termux/termux-packages/pull/1169#issuecomment-323485866

**Comment by fornwall** [comment]
@stephengroat Hm, I don't recognize that `signbit` problem, unfortunately. So that comes when you build cmake using this new build setup?

**Comment by stephengroat** [comment]
@fornwall i've traced it down to #1149, i'll track it.

i've also updated the system to use `apt` to download and install, so it can process all of the necessary dependencies. should eventually stop the need for `buildorder.py`, can convert to using `apt-cache dependes/rdepends` and other tools like it

**Comment by fornwall** [comment]
@stephengroat Impressive work going forward with this! Let me know how I can help and when you want this merged.

**Comment by stephengroat** [comment]
@fornwall thanks. I'm not sure if this is ready yet, I still think it needs some work. i want to do another `build-all` and fix the remaining few packages. once that's done, i'll let you know

**Comment by stephengroat** [comment]
anyone on this thread have any idea why the `minicom` package can't find `iconv.h` now?

**Comment by Grimler91** [comment]
@stephengroat I tried the changes and it worked well, speeding up build time a lot.

However, I ran into troubles when building packages texlive-bin since it recommends texlive which depends on texlive-bin. There are two problems:

- building texlive-bin results in texlive-bin being downloaded instead of build due to the the recommends+depends setup. I though that the option `-o APT::Get::Install-Recommends=false` would solve this (and speeds up build a bit potentially), but there seem to be an additional problem somewhere. I've opened a pull request to your repo anyways.
- texlive-bin has a postinst script which tries to execute binaries in $PREFIX/bin/, which obviously won't work when building for other architectures. texlive is probably not unique in having this problem.

Is it possible to ignore errors from the postinst scripts, or work around this in some other way?

**Comment by stephengroat** [comment]
@Grimler91 i've struggled with the postinit script issue for a while. i've tried everything i can think of, short of patching `apt` (which is what i'm currently looking at doing, adding a flag to `apt` that skips postinit scripts and seeing if I can get that mainlined) 

that's the last major blocker to having this work. if you have any ideas, please let me know

**Comment by fornwall** [comment]
@stephengroat Another possibility could be to sidestep apt/dpkg for installing packages and instead manually setting up and extracting the packages into $TERMUX_PREFIX.

In general, you could run `ar x my.deb` to extract two files:

1. The `control.tar.xz` file containing the `./control` file with fields, from where e.g. dependencies can be obtained with `tar -Oxf control.tar.xz ./control  | grep Depends`.

2. The `data.tar.xz` file containing the files to be installed into `$TERMUX_PREFIX`.

I'm not sure if that's an unreasonable amount of work or not, but at least a possibility :).

**Comment by stephengroat** [comment]
@fornwall it's a possibility, but i'm trying to mirror the actual environment as much as possible. there must be SOME way in `apt` not to run the post-install stuff

how I current have this PR setup is that `travis` will run normal builds and my custom builds for `aarch64`, then run the rest. if you don't have any objections, it would be helpful for me to see what happens when more people use it

**Comment by Grimler91** [comment]
@stephengroat have a look at https://github.com/Grimler91/termux-packages/tree/fast_build_rebased (and in particular https://github.com/Grimler91/termux-packages/blob/1c9b404348f34c5fc02227275155c3877bb8a1ae/build-package.sh#L522 for how bootstrap extraction). 

It works basically the same way as this PR, but without apt

**Comment by xeffyr** [comment]
Closing in favor of https://github.com/termux/termux-packages/pull/3276.

**Pull request closed without merging**
