### PR TITLE
emscripten: update to 2.0.32

### PR DESCRIPTION
**Pull request by truboxl**
This one tries to fix most of the issues to pass `emscripten` test suite
(still left a few failed: either commands are not packaged yet for Termux or `nodejs-lts` is simply too new)
To run the test suite, in emscripten directory, run `tests/runner wasm0 skip:wasm0.test_bigswitch`

Maintaining LLVM has become way too much of a burden. 😭 Pain points:
1. Emscripten keep using the latest snapshot
(using existing `clang` will result in a warning and I am not sure how much have changed between the snapshot and `libllvm`)
1. Build sometimes breaks without any patches (in x86 and x86_64 cases)
1. Update patches from `libllvm` to reuse them in fixing native compile issues (just to pass the tests)

Also since it needs a working `npm`, you will be greeted with an error during install (at the time of writing).
No idea how to fix that, maybe @thunder-coding can look into it. `npm` keep breaking for each new version.
Hopefully this won't lead me into maintaining another `nodejs` just for emscripten. 😅

### CODE REVIEW

**Comment by thunder-coding** [comment]
> Also since it needs a working npm, you will be greeted with an error during install (at the time of writing).
No idea how to fix that, maybe @thunder-coding can look into it. npm keep breaking for each new version.
Hopefully this won't lead me into maintaining another nodejs just for emscripten. :sweat_smile:

Thanks for reporting, `npm` indeed never worked well for me and I always use yarn. I wonder whether there is a way to use `yarn` instead of `npm`.

Btw, what error does it give which is preventing `emscripten` post install script to be executed, I will prioritise it

**Comment by truboxl** [comment]
```
.../opt/emscripten $ pwd
/data/data/com.termux/files/usr/opt/emscripten
.../opt/emscripten $ npm ci --no-optional --production
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-11-01T12_04_21_252Z-debug.log
.../opt/emscripten $ cat /data/data/com.termux/files/home/.npm/_logs/2021-11-01T12_04_21_252Z-debug.log
0 verbose cli [
0 verbose cli   '/data/data/com.termux/files/usr/bin/node',
0 verbose cli   '/data/data/com.termux/files/usr/bin/npm',
0 verbose cli   'ci',
0 verbose cli   '--no-optional',
0 verbose cli   '--production'
0 verbose cli ]
1 info using npm@8.1.0
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 10ms
5 timing config:load:file:/data/data/com.termux/files/usr/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 verbose config optional Use `--omit=optional` to exclude optional dependencies, or
7 verbose config `--include=optional` to include them.
7 verbose config
7 verbose config     Default value does install optional deps unless otherwise omitted.
8 verbose config production Use `--omit=dev` instead.
9 timing config:load:cli Completed in 13ms
10 timing config:load:env Completed in 2ms
11 timing config:load:file:/data/data/com.termux/files/usr/opt/emscripten/.npmrc Completed in 2ms
12 timing config:load:project Completed in 7ms
13 timing config:load:file:/data/data/com.termux/files/home/.npmrc Completed in 1ms
14 timing config:load:user Completed in 2ms
15 timing config:load:file:/data/data/com.termux/files/usr/etc/npmrc Completed in 1ms
16 timing config:load:global Completed in 1ms
17 timing config:load:validate Completed in 1ms
18 timing config:load:credentials Completed in 8ms
19 timing config:load:setEnvs Completed in 6ms
20 timing config:load Completed in 58ms
21 timing npm:load:configload Completed in 58ms
22 timing npm:load:setTitle Completed in 1ms
23 timing npm:load:setupLog Completed in 3ms
24 timing config:load:flatten Completed in 20ms
25 timing npm:load:cleanupLog Completed in 12ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load:projectScope Completed in 3ms
28 timing npm:load Completed in 109ms
29 timing arborist:ctor Completed in 6ms
30 timing npm-ci:rm Completed in 1193ms
31 timing idealTree:init Completed in 6ms
32 warn old lockfile The package-lock.json file was created with an old version of npm,
32 warn old lockfile so supplemental metadata must be fetched from the registry.
32 warn old lockfile
32 warn old lockfile This is a one-time fix-up, please be patient...
33 timing npm Completed in 2756ms
34 verbose unfinished npm timer command:ci 1635768259897
35 verbose unfinished npm timer reify 1635768261110
36 verbose unfinished npm timer reify:loadTrees 1635768261115
37 verbose unfinished npm timer idealTree 1635768261118
38 verbose unfinished npm timer idealTree:inflate 1635768261127
39 info ok
40 error Exit handler never called!
41 error This is an error with npm itself. Please report this error at:
42 error <https://github.com/npm/cli/issues>
```
If you can't fix I wouldn't mind huhu...
I guess the users will figure out how to workaround somehow (if there's anyone actually using emscripten)...

**Comment by truboxl** [comment]
I think I have tested enough. Termux maintainers can proceed to merge this if the codes are fine.

**Comment by thunder-coding** [comment]
The npm Exit Handler not called errors are due to resource constraints on Android devices according to https://github.com/npm/statusboard/issues/395. But I feel it's npm cli not handling them properly. Probably, there is nothing I can do here. Sorry 😔.

If you find anything else regarding this, consider informing me, I may investigate further if possible.

**Pull request merged**
