### PR TITLE
llvm fixes using jit and calling getProcessTriple

### PR DESCRIPTION
**Pull request by its-pointless**
llvm-config edit allows me to build nightly rustc  using our llvm6....

### CODE REVIEW

**Comment by joakim-noah** [comment]
Not sure why these two changes are actually needed.

**Comment by its-pointless** [comment]
When compiling julialang on device it calls getprocess triple which is
meant ti be the triple llvm runs on as opposed to default target triple
which may or may not be a cross compiler. So julia actually started
compiling x86 code on my arm device with the jit..... It caused crashes...
until i figured out what was going on. It didn't cause crashes on x86
because the process triple was i386-pc-linux-gnu. Same as on arm device but
obviously not as fatal.
The llvm-config script change isn't right though. I will fix that up when i
get home.


On 31 Mar. 2018 7:41 pm, "joakim-noah" <notifications@github.com> wrote:

Not sure why these two changes are actually needed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/termux/termux-packages/pull/2299#issuecomment-377677251>,
or mute the thread

**Comment by joakim-noah** [comment]
Isn't that a bug in Julia that should be fixed there? They shouldn't be relying on llvm's host triple but its target triple.

**Comment by its-pointless** [comment]
No they are correct. if you need to jit local code but also cross compile
to another arch its needed.  Its actually recommended to to rely on process
triple as its more accurate. Regardless the correct process triple setting
here is correct.

**Comment by its-pointless** [comment]
anyway it fixes this...
thread 'main' panicked at '

bad LLVM version: 6.0

, need >=3.9


Need to get a few more things done then merge i guess...

**Comment by its-pointless** [comment]
this is done ... basically.

**Comment by joakim-noah** [comment]
Are you planning on submitting a Rust package?

**Comment by its-pointless** [comment]
at this point no too many break points to have a consistent build script that would work. 
next stable update it might be ready.
at this point the nightlies are far simplier since they have fixed a few more bugs in build process.

**Comment by its-pointless** [comment]
It would be nice if this was merged...

**Comment by fornwall** [comment]
Nice work! The built package will be available shortly.

**Pull request merged**
