### PR TITLE
miniserve: install shell completions and warn user on default behaviour

### PR DESCRIPTION
**Pull request by pvonmoradi**
This commit writes shell completions as a `postinst` hook. Also warns user on default miniserve behaviour.  
This is of special interest for Termux since it may symlink user storage dirs to ~. If user invokes `miniserve` on `home` (without `--no-symlinks` switch), it would expose his storage to the HTTP server.

### CODE REVIEW

**Comment by pvonmoradi** [comment]
@xeffyr I just tested locally. `postinst` did not run for me. Is it because my `$TERMUX_PREFIX` is not set and I have only `$PREFIX`?

**Comment by xeffyr** [comment]
`$TERMUX_PREFIX` is only for build environment, but is being expanded in heredoc anyway. Here is how your script looks like in .deb file:
```
#!/data/data/com.termux/files/usr/bin/sh

# Generating completions
mkdir -p "/data/data/com.termux/files/usr"/share/{bash-completion/completions,zsh/site-functions,fish/vendor_completions.d}
miniserve --print-completions bash 		> "/data/data/com.termux/files/usr"/share/bash-completion/completions/miniserve
miniserve --print-completions zsh 		> "/data/data/com.termux/files/usr"/share/zsh/site-functions/_miniserve
miniserve --print-completions fish 		> "/data/data/com.termux/files/usr"/share/fish/vendor_completions.d/miniserve.fish

# Warn user on default behaviour of miniserve
printf "\e[1;33mWARNING:\e[0m %s %s\n%s\n" 		"miniserve follows symlinks in selected directory by default." 		"Consider aliasing it with '--no-symlinks' for safety." 		"See: https://github.com/svenstaro/miniserve/issues/498"
```

But I have noticed that it doesn't have executable permission.

**Comment by xeffyr** [comment]
Seems like it works even without permission, but script has error about non-existent directory.

**Comment by pvonmoradi** [comment]
> Seems like it works even without permission, but script has error about non-existent directory. You are using Bash features in `mkdir` command, but script uses POSIX sh.

Still, I wonder why the `printf`didn't get printed. Does the script exit on first error?

**Comment by xeffyr** [comment]
Maybe you just installed the older package build where script was not added. It doesn't exit on the first error.

**Pull request merged**
