### PR TITLE
fix(main/zsh): Fix heredoc temp file creation

### PR DESCRIPTION
**Pull request by TomJo2000**
Didn't catch this in testing probably due to some leftovers from previous compilation runs.

Problem is the following, Heredocs `<<` and Herestrings `<<<` don't work in the 5.9-6 package of Zsh.
To remedy this I've moved the PCRE2 patch into a standard patch file instead of fetching it from upstream during the build.

@tstein helped identify the cause of the problem.
https://github.com/zsh-users/zsh/blob/86d5f24a3d28541f242eb3807379301ea976de87/configure.ac#L2992

Which we patch here.
https://github.com/termux/termux-packages/blob/adac1df5a7509126f6ee20e3bdee9abaae8e1f57/packages/zsh/tmp_path.patch#L1-L12
I suspect earlier patches are getting effectively "unapplied" by the `autoreconf -fi`.

A good litmus test for seeing if the issue is solved is running `zsh -c 'cat <<< test'`
Which when broken will output `zsh:1: can't create temp file for here document: no such file or directory`.

I haven't been able to test this revision of the package on device yet.

We might wanna just regenerate all the patches for Zsh with `git diff` just so they're up to date.

### CODE REVIEW

**Comment by TomJo2000** [comment]
<sup>(This is a pre-written, saved reply.)</sup>
If you want to test this PR please download the appropriate DEB package(s)
from the build artifacts of the [associated PR's latest CI run](https://github.com/termux/termux-packages/pull/22381/checks).
Screenshot_20240619_232413


After downloading the build artifact, make sure to `unzip` and un-`tar` it.
<details><summary>Detailed instructions, if needed.</summary>
<p>

```bash
# finding out what architecture you need
# architecture is just below the TERMUX_VERSION
termux-info

# e.g.
# [...]
# TERMUX_MAIN_PACKAGE_FORMAT=debian
# TERMUX_VERSION=0.118.0
# TERMUX__USER_ID=0
# Packages CPU architecture:
# aarch64
# [...]

# =======================

# make sure `unzip` and `tar` are installed using
pkg install unzip tar

# unzip the artifact (if you have a different architecture this might be arm, i686 or x86_64 instead)
unzip debs-aarch64-*.zip

# untar the artifact
tar xf debs-aarch64-*.tar

# You should now have a debs/ directory in your current working directory
# Install the packages from the local source using
pkg install -- ./debs/*.deb

# to clean up, you can remove the debs/ directory, .tar file and .zip file
rm -rfi debs debs-aarch64-*.zip debs-aarch64-*.tar
```

</p>
</details>

**Comment by GR3YH4TT3R93** [comment]
zsh -c `cat <<< test` still seems to return the same error but addt'l things seem to have broken as well with my [config](https://github.com/GR3YH4TT3R93/dotfiles). Here's the output of oh-my-zsh w/ powerlevel10k on my device

```
(anon):29: failed to load module: zsh/system
(anon):7: failed to load module: zsh/stat
/data/data/com.termux/files/home/.oh-my-zsh/lib/async_prompt.zsh:5: failed to load module: zsh/system
regexp-replace:32: failed to load module: zsh/pcre
/data/data/com.termux/files/home/.oh-my-zsh/custom/plugins/fzf-tab/fzf-tab.zsh:382: failed to load module: zsh/mapfile
/data/data/com.termux/files/home/.oh-my-zsh/custom/plugins/fzf-tab/fzf-tab.zsh:383: failed to load module: zsh/stat
/data/data/com.termux/files/home/.oh-my-zsh/plugins/git-auto-fetch/git-auto-fetch.plugin.zsh:6: failed to load module: zsh/stat
/data/data/com.termux/files/home/.oh-my-zsh/plugins/zsh-interactive-cd/zsh-interactive-cd.plugin.zsh:172: failed to load module: zsh/pcre
/data/data/com.termux/files/home/.oh-my-zsh/plugins/zsh-interactive-cd/zsh-interactive-cd.plugin.zsh:172: -pcre-match not available for regex
/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/gitstatus.plugin.zsh:57: failed to load module: zsh/system
/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh:9470: failed to load module: zsh/mathfunc
/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh:9472: failed to load module: zsh/system
/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh:9476: failed to load module: zsh/stat
/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh:9477: failed to load module: zsh/net/socket
/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh:9478: failed to load module: zsh/files
/proc/self/fd/12:522: failed to load module: zsh/pcre
/proc/self/fd/12:522: -pcre-match not available for regex
iconv: conversion from -t unsupported
iconv: try 'iconv -l' to get the list of supported encodings
Error converting string from  to UTF-8
_p9k_init_params:107: cannot do charset conversion (NLS not supported)
localhost% z
zvm_update_repeat_commands:18: failed to load module: zsh/pcre
zvm_update_repeat_commands:18: -pcre-match not available for regex
```

**Comment by TomJo2000** [comment]
I'll relay @robertkirkman's comment from the discord/Matrix room here:
> TomIO, you are adding a patch that modifies `configure.ac`, but an existing patch, this one, patches `configure` https://github.com/termux/termux-packages/blob/master/packages/zsh/configure.patch.
Aren't those two types of patches mutually exclusive, because `autoreconf -fi` is needed to apply `configure.ac` patches, but `autoreconf -fi` cannot be used when there are `configure` patches?
I would guess for consistency, either both patches need to be applied to `configure.ac` and `autoreconf -fi` is used, or both patches need to be applied to `configure` and `autoreconf -fi` is not used?

I think the best thing to do would be to regenerate the patches to be applied to `configure.ac` instead of `configure`.
I can do that later, but I'm out of time for now.

**Comment by robertkirkman** [comment]
Here is my idea how to fix this

<details>
<summary>my idea</summary>

```diff
diff --git a/packages/zsh/build.sh b/packages/zsh/build.sh
index ca2bd566a6..2ded9c314f 100644
--- a/packages/zsh/build.sh
+++ b/packages/zsh/build.sh
@@ -4,7 +4,7 @@ TERMUX_PKG_LICENSE="custom"
 TERMUX_PKG_LICENSE_FILE="LICENCE"
 TERMUX_PKG_MAINTAINER="Joshua Kahn @TomJo2000"
 TERMUX_PKG_VERSION=5.9
-TERMUX_PKG_REVISION=6
+TERMUX_PKG_REVISION=7
 TERMUX_PKG_SRCURL=https://www.zsh.org/pub/zsh-${TERMUX_PKG_VERSION}.tar.xz
 TERMUX_PKG_SHA256=9b8d1ecedd5b5e81fbf1918e876752a7dd948e05c1a0dba10ab863842d45acd5
 TERMUX_PKG_BUILD_DEPENDS="pcre2"
diff --git a/packages/zsh/configure.ac-disable-fixed-sitefndir.patch b/packages/zsh/configure.ac-disable-fixed-sitefndir.patch
new file mode 100644
index 0000000000..0aa6798da8
--- /dev/null
+++ b/packages/zsh/configure.ac-disable-fixed-sitefndir.patch
@@ -0,0 +1,12 @@
+--- a/configure.ac
++++ b/configure.ac
+@@ -318,7 +318,7 @@ dnl Add /usr/local/share/zsh/site-functions if not yet present
+ dnl owing to $sitefndir, whether or not explicitly given.
+ dnl If not explicitly given, it hasn't been expanded yet.
+ if test X$sitefndir = X/usr/local/share/zsh/site-functions || \
+-   test X$sitefndir = Xno
++   test X$sitefndir = Xno || true
+ then fixed_sitefndir=''
+ elif test X$prefix != X/usr/local; then
+   if test X$prefix = XNONE && test X$ac_default_prefix = X/usr/local; then
+
diff --git a/packages/zsh/tmp_path.patch b/packages/zsh/configure.ac-prepend-prefix-to-tmp-path.patch
similarity index 61%
rename from packages/zsh/tmp_path.patch
rename to packages/zsh/configure.ac-prepend-prefix-to-tmp-path.patch
index bdae1b3d55..cf8aad810e 100644
--- a/packages/zsh/tmp_path.patch
+++ b/packages/zsh/configure.ac-prepend-prefix-to-tmp-path.patch
@@ -1,7 +1,6 @@
-diff -u -r ../zsh-5.0.5/config.h.in ./config.h.in
---- ../zsh-5.0.5/config.h.in	2013-11-30 00:28:56.000000000 +0100
-+++ ./config.h.in	2014-02-03 02:21:35.000000000 +0100
-@@ -25,7 +25,7 @@
+--- a/configure.ac
++++ b/configure.ac
+@@ -3212,7 +3212,7 @@ AH_TOP([/***** begin user configuration section *****/
  #define DEFAULT_FCEDIT "vi"
  
  /* The default prefix for temporary files */
@@ -10,3 +9,4 @@ diff -u -r ../zsh-5.0.5/config.h.in ./config.h.in
  
  /***** end of user configuration section            *****/
  /***** shouldn't have to change anything below here *****/
+
diff --git a/packages/zsh/configure.patch b/packages/zsh/configure.patch
deleted file mode 100644
index dca301d7a0..0000000000
--- a/packages/zsh/configure.patch
+++ /dev/null
@@ -1,27 +0,0 @@
-diff -u -r ../zsh-5.4.2/configure ./configure
---- ../zsh-5.4.2/configure	2017-06-30 22:36:56.000000000 +0200
-+++ ./configure	2017-11-01 16:00:08.601290902 +0100
-@@ -2888,21 +2888,8 @@
- fi
- 
- 
--if test X$sitefndir = X/usr/local/share/zsh/site-functions || \
--   test X$sitefndir = Xno
--then fixed_sitefndir=''
--elif test X$prefix != X/usr/local; then
--  if test X$prefix = XNONE && test X$ac_default_prefix = X/usr/local; then
--    if test X$tzsh_name != Xzsh
--    then fixed_sitefndir=/usr/local/share/zsh/site-functions
--    else fixed_sitefndir=''
--    fi
--  else fixed_sitefndir=/usr/local/share/zsh/site-functions
--  fi
--elif test X$tzsh_name != Xzsh
--then fixed_sitefndir=/usr/local/share/zsh/site-functions
--else fixed_sitefndir=''
--fi
-+# Do not use /usr/local/share/zsh/site-functions (#1730):
-+fixed_sitefndir=''
- 
- 
- # Check whether --enable-function-subdirs was given.
```

</details>

My idea works by rebasing `tmp_path.patch` on `configure.ac` also, not just `configure.patch`.

**Comment by GR3YH4TT3R93** [comment]
Latest commit seems to have fixed all issues I was previously experiencing

**Pull request merged**
