### PR TITLE
addpkg(main): wasi-libc, wasm32-wasi target for Rust

### LINKED ISSUE #13117: [Package]: rust-std-wasm32-wasi
### Why do you want to add this package to Termux?

Rust in Termux is not managed by `rustup`. Additional targets are added as `rust` subpackages like `rust-std-wasm32` for target `wasm32-unknown-unknown`. It would be nice to also support the increasingly popular `wasm32-wasi` target as well.

### Home page URL

https://www.rust-lang.org/

### Source code URL

https://github.com/rust-lang/rust

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by truboxl**
Close #13117

### CODE REVIEW

**Comment by truboxl** [comment]
Seems like there's conflict between GitHub hosted image and NDK r26b...

**Comment by Grimler91** [comment]
> Seems like there's conflict between GitHub hosted image and NDK r26b...
> 
> ```
> ERROR: Wrong NDK version - we need 26b
> ```

Weird, should have been uploaded in https://github.com/termux/termux-packages/actions/runs/6605666784...

**Comment by truboxl** [comment]
> Weird, should have been uploaded in https://github.com/termux/termux-packages/actions/runs/6605666784...

I think its because building rust on CI is using GitHub image and not Docker image, probably need to add `./scripts/setup-android-sdk.sh` somewhere. CC @finagolfin

**Comment by finagolfin** [comment]
OK, I've updated the NDK used directly on github in the CI, 62f2443fc, try building this again.

**Comment by truboxl** [comment]
Seems like I hit a problem when I think it shouldnt be a problem?
```
aarch64-linux-android-clang -O2 -DNDEBUG --target=wasm32-wasi-threads -fno-trapping-math -Wall -Wextra -Werror -Wno-null-pointer-arithmetic -Wno-unused-parameter -Wno-sign-compare -Wno-unused-variable -Wno-unused-function -Wno-ignored-attributes -Wno-missing-braces -Wno-ignored-pragmas -Wno-unused-but-set-variable -Wno-unknown-warning-option -mthread-model posix -pthread -ftls-model=local-exec -Ilibc-bottom-half/cloudlibc/src -isystem "/home/builder/.termux-build/wasi-libc/src/build/install/data/data/com.termux/files/usr/share/wasi-sysroot/include" -Ilibc-bottom-half/headers/private -Ilibc-bottom-half/cloudlibc/src/include -Ilibc-bottom-half/cloudlibc/src -Ilibc-top-half/musl/src/include -Ilibc-top-half/musl/src/internal -MD -MP -o build/wasm32-wasi-threads/libc-bottom-half/crt/crt1.o -c libc-bottom-half/crt/crt1.c
In file included from libc-bottom-half/crt/crt1.c:3:
In file included from libc-bottom-half/crt/crt1-command.c:2:
/home/builder/.termux-build/_cache/android-r26b-api-24-v0/lib/clang/17/include/stdatomic.h:33:10: fatal error: 'sys/cdefs.h' file not found
#include <sys/cdefs.h>
         ^~~~~~~~~~~~~
1 error generated.
make[1]: *** [Makefile:528: build/wasm32-wasi-threads/libc-bottom-half/crt/crt1.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```
Apparently
https://android.googlesource.com/toolchain/prebuilts/ndk/r26/+/refs/heads/main/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/17/include/stdatomic.h
and
https://android.googlesource.com/toolchain/prebuilts/ndk/r26/+/refs/heads/main/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdatomic.h
is the same for Android NDK

but standard clang (and our libllvm) `$PREFIX/lib/clang/17/include/stdatomic.h` is
https://clang.llvm.org/doxygen/stdatomic_8h_source.html

???

**Comment by finagolfin** [comment]
Why does it matter what our libllvm/clang packages include? Your error clearly shows it is using the version from the NDK, `home/builder/.termux-build/_cache/android-r26b-api-24-v0/lib/clang/17/include/stdatomic.h`. I think the issue is your flag overriding the sysroot used, `-isystem "/home/builder/.termux-build/wasi-libc/src/build/install/data/data/com.termux/files/usr/share/wasi-sysroot/include"`, guessing that has no `sys/cdefs.h`?

**Comment by truboxl** [comment]
There's nothing wrong with our libllvm. I am surprised they still kept the same file for NDK which differs from standard clang, which in turn different behavior and maybe even broken. I think i should report to them...

**Comment by truboxl** [comment]
I will merge this in 24h excluding the symbol checks if no more reviews

**Pull request merged**
