### PR TITLE
texlive: update to 20200406

### PR DESCRIPTION
**Pull request by Grimler91**
I have also remove texlive-tlmgr and will create a termux-texlive-installer script instead.

I am still running som tests to make sure there are no more file conflicts, will more later today, probably.

### CODE REVIEW

**Comment by Grimler91** [comment]
Packages has been uploaded manually

**Comment by angelog0** [comment]
As I wrote in another post, usually both on GNU/Linux and macOS I create a local mirror of `tlnet` repo (`/mnt/tlrepo`) and than install TL with the `install-tl` script, say

  `.../local/tlrepo/install-tl`

set the installation to HOME/texlive and than `i'

After this, I maintain the TL installation up-to-date using, basically

  `tlmgr --repository /mnt/tlrepo update --list \ self \ all`

With this new TL in Termux can I do something  similar?

I see you have removed `texlive-tlmgr` mut is tlmgr still there in some package?

Happy Easter,
  Angelo.

**Comment by Grimler91** [comment]
@angelog0 happy Easter!

I will add a package called texlive-installer, or something like that, before the end of the month, which allows you to run the install-tl script. I can make sure that it is possible to specify repository path with it.

**Comment by angelog0** [comment]
You didn't answer the other question about tlmgr...

**Comment by Grimler91** [comment]
No other package contains tlmgr. Only way to get tlmgr will be through the upcoming installer

**Pull request merged**
