### PR TITLE
Add game-repo, science-repo and update root-repo url

### PR DESCRIPTION
**Pull request by Grimler91**

### CODE REVIEW

**Comment by xeffyr** [comment]
@Grimler91 Should https://github.com/termux/termux-packages/pull/3313 be closed ?

**Comment by Grimler91** [comment]
@xeffyr #3313 is for the master branch while this one is for the android-5 branch, so both are needed I guess

**Comment by xeffyr** [comment]
Okay.

**Comment by Grimler91** [comment]
Yes, repo and PR is ready, I guess we can merge the PR to master and upload the built packages (I can do that)

**Pull request merged**
