### PR TITLE
tree-wide: setting up python packages and raising the version value

### PR DESCRIPTION
**Pull request by xtkoba**
Packages that do not need rebuild are separated in #14590. CC: @Maxython

### CODE REVIEW

**Comment by xtkoba** [comment]
@Maxython `boost` is handled in #14590 because it does not need rebuild. Revision reset in `libtorrent-rastarbar` seems to be a mistake.

**Comment by xtkoba** [comment]
@Maxython Hello?

**Comment by Maxython** [comment]
I'm here

**Comment by xtkoba** [comment]
@Maxython Please do not include `boost` in this PR. It is in #14590. Thanks.

**Comment by Maxython** [comment]
> @Maxython Please do not include `boost` in this PR. It is in #14590. Thanks.

Yes, it was. Thanks for fixing it.

**Pull request merged**
