### PR TITLE
Bump nvim 0.5

### PR DESCRIPTION
**Pull request by shadmansaleh**

### CODE REVIEW

**Comment by shadmansaleh** [comment]
Sorry wrong repo again 🤦‍♂️

Just experimenting with the build . make a pr if I can get 5he build to succeed :P

**Comment by truboxl** [comment]
You can use specify `TERMUX_PKG_BLACKLISTED_ARCHES` in build.sh so that you dont need to touch packages.yaml to stop building for certain arch.
https://github.com/termux/termux-packages/wiki/Creating-new-package

Its ok to experiment here or in your fork repo, I think others wont mind

**Comment by shadmansaleh** [comment]
That commit on package.yml was just a  experimental . I was going to drop it in actual pr .

I've been experimenting in my fork . I'm kind of stuck for some reason the build script tries to build neovim twice . 2nd time it fails for not finding 'libintl' [build-log](https://gist.github.com/shadmansaleh/e6ed09b64b788f15b486c1c80f7b865c). Any idea why it's building twice or if libintl is packaged in termux?

**Comment by truboxl** [comment]
From the log, my guess is the 1st one is using gcc so its host building, the 2nd one is using Android clang so the actual cross compile...

From the wiki, libintl is unavailable in Android. https://github.com/termux/termux-packages/wiki/Common-porting-problems
Maybe neovim recently got higher requirements?

So we have to link `libandroid-support`.
Something like adding `libandroid-support` to `TERMUX_PKG_DEPENDS` and `export LDFLAGS+=" -landroid-support"` in build.sh

Of course, I could be wrong...

**Comment by shadmansaleh** [comment]
Thanks.

https://github.com/termux/termux-packages/blob/24f36a5fea5417641429498579987d56dba84a7d/packages/neovim/build.sh#L9

libandroid-support is already in `TERMUX_PKG_SUPPORT`.

https://github.com/termux/termux-packages/blob/24f36a5fea5417641429498579987d56dba84a7d/packages/neovim/build.sh#L32

Does `termux_step_host_build` mean it's not cross compiling ?

Are there any documentation that document the build steps and what they actually do ?

https://github.com/termux/termux-packages/blob/24f36a5fea5417641429498579987d56dba84a7d/packages/neovim/build.sh#L45

Is the `|| bash` suppose to be there ?

**Pull request closed without merging**
