### PR TITLE
upgpkg(main/weechat): update to 3.5

### PR DESCRIPTION
**Pull request by zorro**

### CODE REVIEW

**Review by 2096779623 — CHANGES_REQUESTED** [review]
* Please squash the commits.

* Set `TERMUX_PKG_AUTO_UPDATE` to `true`, [like this](https://github.com/termux/termux-packages/pull/11082/files#diff-38715b6d0f9e1eb69f034fd23feca5e6e485093eea760a1a51ba3337a666abd6R6)

**Comment by zorro** [comment]
> * Please squash the commits.
> * Set `TERMUX_PKG_AUTO_UPDATE` to `true`, [like this](https://github.com/termux/termux-packages/pull/11082/files#diff-38715b6d0f9e1eb69f034fd23feca5e6e485093eea760a1a51ba3337a666abd6R6)

Done

**Comment by 2096779623** [comment]
> > * Please squash the commits.
> > * Set `TERMUX_PKG_AUTO_UPDATE` to `true`, [like this](https://github.com/termux/termux-packages/pull/11082/files#diff-38715b6d0f9e1eb69f034fd23feca5e6e485093eea760a1a51ba3337a666abd6R6)
> 
> Done

And the one above.

**Comment by zorro** [comment]
> > > * Please squash the commits.
> > > * Set `TERMUX_PKG_AUTO_UPDATE` to `true`, [like this](https://github.com/termux/termux-packages/pull/11082/files#diff-38715b6d0f9e1eb69f034fd23feca5e6e485093eea760a1a51ba3337a666abd6R6)
> > 
> > 
> > Done
> 
> And the one above.

I have 

> > > * Please squash the commits.
> > > * Set `TERMUX_PKG_AUTO_UPDATE` to `true`, [like this](https://github.com/termux/termux-packages/pull/11082/files#diff-38715b6d0f9e1eb69f034fd23feca5e6e485093eea760a1a51ba3337a666abd6R6)
> > 
> > 
> > Done
> 
> And the one above.

I no

> > > * Please squash the commits.
> > > * Set `TERMUX_PKG_AUTO_UPDATE` to `true`, [like this](https://github.com/termux/termux-packages/pull/11082/files#diff-38715b6d0f9e1eb69f034fd23feca5e6e485093eea760a1a51ba3337a666abd6R6)
> > 
> > 
> > Done
> 
> And the one above.

I have already squashed the commits.

**Comment by zorro** [comment]
> > > * Please squash the commits.
> > > * Set `TERMUX_PKG_AUTO_UPDATE` to `true`, [like this](https://github.com/termux/termux-packages/pull/11082/files#diff-38715b6d0f9e1eb69f034fd23feca5e6e485093eea760a1a51ba3337a666abd6R6)
> > 
> > Done
> 
> And the one above.

I have already squashed the commits

**Review by 2096779623 — CHANGES_REQUESTED** [review]
Please add subpackage to `TERMUX_PKG_DEPENDS`, [like this](https://github.com/termux/termux-packages/pull/10797/files#diff-c0720547e3ee3f8cc3a9103853d9e3f629ef13dc4409936607742144da0544d8R9)

**Comment by zorro** [comment]
> Please add subpackage to `TERMUX_PKG_DEPENDS`, [like this](https://github.com/termux/termux-packages/pull/10797/files#diff-c0720547e3ee3f8cc3a9103853d9e3f629ef13dc4409936607742144da0544d8R9)

The subpackages are plugins. I don't think it's necessary to add plugins to TERMUX_PKG_DEPENDS

**Comment by 2096779623** [comment]
> > Please add subpackage to `TERMUX_PKG_DEPENDS`, [like this](https://github.com/termux/termux-packages/pull/10797/files#diff-c0720547e3ee3f8cc3a9103853d9e3f629ef13dc4409936607742144da0544d8R9)
> 
> The subpackages are plugins. I don't think it's necessary to add plugins to TERMUX_PKG_DEPENDS

OK.

**Review by 2096779623 — APPROVED** [review]

**Pull request merged**
