### PR TITLE
swift: update from 5.2.2 to 5.2.3

### PR DESCRIPTION
**Pull request by buttaface**
I though this would go in with #5251, but it looks like that's been delayed, so let's just get it in now.

### CODE REVIEW

**Comment by xeffyr** [comment]
```
2020-05-19T10:12:53.2076955Z Building the standard library for: swift-test-stdlib-android-aarch64 swift-test-stdlib-android-aarch64
2020-05-19T10:12:53.9486809Z patching file lib/llvm/Support/CMakeLists.txt
2020-05-19T10:12:53.9486982Z Hunk #1 succeeded at 64 (offset 19 lines).
2020-05-19T10:12:53.9505910Z can't find file to patch at input line 4
2020-05-19T10:12:53.9506160Z Perhaps you used the wrong -p or --strip option?
2020-05-19T10:12:53.9506455Z The text leading up to this was:
2020-05-19T10:12:53.9506676Z --------------------------
2020-05-19T10:12:53.9506932Z |diff -u -r ../llvm-4.0.1.src/tools/clang/lib/Driver/ToolChain.cpp ./tools/clang/lib/Driver/ToolChain.cpp
2020-05-19T10:12:53.9507208Z |--- ../llvm-4.0.1.src/tools/clang/lib/Driver/ToolChain.cpp	2016-12-14 17:46:50.000000000 +0100
2020-05-19T10:12:53.9507454Z |+++ ./tools/clang/lib/Driver/ToolChain.cpp	2017-07-13 12:35:02.862534376 +0200
2020-05-19T10:12:53.9507642Z --------------------------
2020-05-19T10:12:53.9507725Z File to patch: 
2020-05-19T10:12:53.9507807Z Skip this patch? [y] 
2020-05-19T10:12:53.9508059Z Skipping patch.
2020-05-19T10:12:53.9509443Z 1 out of 1 hunk ignored
```

Patch needs update.

**Comment by buttaface** [comment]
Will do.

**Comment by buttaface** [comment]
Ready to go.

**Comment by buttaface** [comment]
Thanks, got it installed but had a lot of problems downloading it, took almost 20 tries as the download kept dropping out. Maybe related to `apt`, as I tried it once with curl and it got it right away, or perhaps issues at bintray?

**Comment by xeffyr** [comment]
@buttaface I can confirm there were speed issues (varied between 256 KB/s - 1 MB/s), but it was downloaded successfully just by running `pkg install swift`. Bintray uses CDN so file probably was not cached.

**Comment by buttaface** [comment]
OK, thanks, just reporting the strange dropouts I saw.

**Pull request merged**
