### PR TITLE
dnote: add tag fts5 and remove post installation script

### LINKED ISSUE #12784: dnote package is broken
### Problem description

if you install dnote and install another package then an error will occur
Screenshot_2022-11-02-16-23-21-062_com termux

dnote-server also has an error 
Screenshot_2022-11-02-16-24-14-071_com termux

and cannot use dnote
Screenshot_2022-11-02-16-30-57-456_com termux

### What steps will reproduce the bug?

- if you install dnote and install another package
- run dnote-server
- run dnote new

### What is the expected behavior?

run normally

### System information

termux-info:

```
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1+9e72088
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/com.termux-OYvSoX5TrjLW20Fx0DQ3CQ==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=2048
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c157,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app:s0:c157,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10157
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+20dee0e
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+20dee0e
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.31.0
Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #1 SMP PREEMPT Wed Sep 16 18:28:51 WIB 2020 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 6A

```

### PR DESCRIPTION
**Pull request by ravener**
Fixes #12784

I was missing `-tags fts5` for the build command.

And regarding the post installation script, I'm not sure why @2096779623 added it, I just kept it like that but now that I checked, there's no such command as `dnote completions` so I completely removed the shell completion stuff.

### CODE REVIEW

**Comment by ravener** [comment]
Seems like CI failed for aarch64 and x86_64 due to some gpg signature error.

**Comment by 2096779623** [comment]
```bash
~/debs $ pkg i ./dnote_1\:0.12.0-1_aarch64.deb
Testing the available mirrors:
[*] (1) https://mirrors.ustc.edu.cn/termux/apt/termux-main: ok
Picking mirror: (0) /data/data/com.termux/files/usr/etc/termux/mirrors/china/mirrors.ustc.edu.cn
Get:1 https://mirrors.ustc.edu.cn/termux/apt/termux-main stable InRelease [14.0 kB]
Get:2 https://mirrors.ustc.edu.cn/termux/apt/termux-x11 x11 InRelease [14.0 kB]
Get:3 https://mirrors.ustc.edu.cn/termux/apt/termux-main stable/main aarch64 Packages [464 kB]
Get:4 https://mirrors.ustc.edu.cn/termux/apt/termux-x11 x11/main aarch64 Packages [111 kB]
Fetched 603 kB in 3s (190 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

Why I can not install?

**Comment by 2096779623** [comment]
> Maybe epoch confuses apt, try with dpkg: `dpkg -i ./dnote_1\:0.12.0-1_aarch64.deb`

Thanks, now it seems to work.
```bash
~/.../downloads/debs $ dpkg -i ./dnote_1\:0.12.0-1_aarch64.debSelecting previously unselected package dnote.
(Reading database ... 50%
(Reading database ... 36138 files and directories currently installed.)
Preparing to unpack ./dnote_1:0.12.0-1_aarch64.deb ...
Unpacking dnote (1:0.12.0-1) ...
Setting up dnote (1:0.12.0-1) ...
~/.../downloads/debs $
~/.../downloads/debs $ dnote new day
  ✔ added to day
  • book name: day
  • created at: Nov 2, 2022 2:33pm (UTC)
  • note id: 2
  • note uuid: 52eb3826-4d82-4eee-811f-c2638d4cd33f

------------------------content------------------------
aaaaaa

-------------------------------------------------------
```

**Comment by ravener** [comment]
> I have seen the completion command in dnote before, but I don't know why it disappeared now. There is also need install completion here: https://github.com/dnote/dnote/blob/master/pkg/cli/

Thanks for pointing out the completion files, I've updated it to install those files now.

**Comment by 2096779623** [comment]
> Thanks for pointing out the completion files, I've updated it to install those files now.

Also need to add something like `install -Dm644 /dev/null "${TERMUX_PREFIX}/share/bash-completion/completions/dnote.bash"` .

**Comment by ravener** [comment]
> Also need to add something like `install -Dm644 /dev/null "${TERMUX_PREFIX}/share/bash-completion/completions/dnote.bash"` .

I think that's only needed when going with the post installation approach. Where it tries to set a placeholder file to be later installed with the postinst script. In this case the file already exists and is ready to be installed. I just followed the `yadm` package's script as an example.

**Review by 2096779623 — APPROVED** [review]

**Review by Grimler91 — APPROVED** [review]

**Pull request merged**
