### PR TITLE
add libs for json-glib build

### PR DESCRIPTION
**Pull request by stephengroat**
needed for #1169, should not affect current build process

### CODE REVIEW

**Comment by fornwall** [comment]
Could you explain why/how this affects the #1169 build system?

**Comment by stephengroat** [comment]
sure, sorry about that. when building with #1169, the linker cannot find `bindtextdomain`.

since i'm not changing anything else in the build system that could possibly affect this, i figured that these libs should be included to overcome that issue

**Comment by fornwall** [comment]
@stephengroat Aha! I've just updated so that `bindtextdomain` and other functions provided by `libintl.h` no longer requires libandroid-support (to which libintl was a symlink) - the functions are instead provided inline in `libintl.h`.

So I think that the changes here and those in https://github.com/termux/termux-packages/pull/1268 and https://github.com/termux/termux-packages/pull/1270 should no longer be necessary - can you verify that?

**Comment by stephengroat** [comment]
@fornwall thanks! sounds like a solution. I'll test and let you know. If it works, I'll close the others

**Comment by stephengroat** [comment]
Looks good!

**Pull request closed without merging**
