### PR TITLE
Bump ccache to 4.3

### PR DESCRIPTION
**Pull request by thunder-coding**

### CODE REVIEW

**Comment by thunder-coding** [comment]
Interesting error: The package compiles perfectly on my device (also `aarch64`)

**Comment by Grimler91** [comment]
Looks like it detects that it is being compiled on x86_64 and tries to include x86_64 assembly. Probably introduced in this commit](https://github.com/ccache/ccache/commit/bcd08a3dd8fba88e671c9a79b8b81b4383cbeae2).

We can add a patch to make it always use the c-variant of the function(s): https://github.com/ccache/ccache/blob/a57f70eda32e99221de56f5499079b4f00dc2bc5/src/third_party/blake3/CMakeLists.txt#L57 
(or fix the underlying issue)

**Comment by thunder-coding** [comment]
> Looks like it detects that it is being compiled on x86_64 and tries to include x86_64 assembly. Probably introduced in [this commit](https://github.com/ccache/ccache/commit/bcd08a3dd8fba88e671c9a79b8b81b4383cbeae2).
> 
> We can add a patch to make it always use the c-variant of the function(s): https://github.com/ccache/ccache/blob/a57f70eda32e99221de56f5499079b4f00dc2bc5/src/third_party/blake3/CMakeLists.txt#L57 
> (or fix the underlying issue)

Will see tommorow @Grimler91

**Comment by thunder-coding** [comment]
Oops, accidently commited other files. A bug in git
`git commit -amemdm`

**Comment by Grimler91** [comment]
Nice work!

**Comment by thunder-coding** [comment]
> Nice work!

All thanks to you for helping me find what's wrong.

**Pull request merged**
