### PR TITLE
Update build.sh

### PR DESCRIPTION
**Pull request by jer194**
See https://github.com/termux/termux-packages/issues/6460

### CODE REVIEW

**Comment by Grimler91** [comment]
Please increase TERMUX_PKG_REVISION as well, otherwise apt will not consider it as as a new version

**Comment by jer194** [comment]
done now

**Comment by Grimler91** [comment]
@jer194 no need. Great, thanks for the PR!

**Comment by jer194** [comment]
Thanks for guidance, and encouragement :-)

**Pull request merged**
