### PR TITLE
add nim

### PR DESCRIPTION
**Pull request by stephengroat**
#1816

### CODE REVIEW

**Comment by its-pointless** [comment]
Need some help there?

**Comment by stephengroat** [comment]
@its-pointless can't figure out why the patch is failing, makes 0 sense to me. works locally

**Comment by its-pointless** [comment]
your patch source and the origin file differ 
CC="gcc"  
LINKER="gcc"
                      in the original and
-CC = gcc
-LINKER = gcc
+CC ?= gcc
+LD ?= gcc
in your patch

**Comment by stephengroat** [comment]
@its-pointless are you talking about lines 5-6?

I have this when i download the nim tarball:

```
CC = gcc
LINKER = gcc
```

do you know if `build-package` is making changes?

**Comment by its-pointless** [comment]
Oh no im wrong looking at wrong file i think..

**Comment by stephengroat** [comment]
np. if you see something, let me know!

**Comment by its-pointless** [comment]
even when i get the makefile to look exactly how it should with the patches... it still doesn't build
try using a different diff method
diff -u -r ./original ./new ?
your patch isn't working here

**Comment by vishalbiswas** [comment]
```patch
--- ./cor.patch
+++ ./stp.patch
@@ -1,9 +1,7 @@
---- ./makefile
-+++ ./makefile2
 @@ -2,10 +2,9 @@
  # Template is in tools/niminst/makefile.tmpl
  # To regenerate run ``niminst csource`` or ``koch csource``
- 
+
 -CC = gcc
 -LINKER = gcc
 +CC ?= gcc
@@ -11,5 +9,5 @@
  COMP_FLAGS = $(CPPFLAGS) $(CFLAGS) -w -O3 -fno-strict-aliasing
 -LINK_FLAGS = $(LDFLAGS)
  binDir = bin
- 
+
  koch := $(shell sh -c 'test -s ../koch.nim && echo "yes"')
```

Your patch on line 3 and 14 of the first hunk is missing padding for (+,-).

All other hunks are similar. Wherever there'sna completely empty line, there should at least be a leading space (which is missing in that patch).
Considering you created this using git, can you reproduce this with other repos?

**Comment by stephengroat** [comment]
Thanks @vishalbiswas, that fixed it!

Here's the error that I was trying to replicate to see if I can get any help:

```
aarch64-linux-android-ld -o bin/nim c_code/2_2/compiler_nim.o ... -L/data/data/com.termux/files/usr/lib -landroid-support -ldl -lm
aarch64-linux-android-ld: error: cannot find -ldl
aarch64-linux-android-ld: error: cannot find -lm
c_code/2_2/compiler_nim.o:c_code/2_2/compiler_nim.c:function prependCurDir_GjIeuxoFFHzgsN9aaFgTDcg: error: undefined reference to 'memcpy'
```

**Comment by its-pointless** [comment]
Iv actually got this much further along. Compiled nim binary on all 4 archs.
My issues are
 The nim  c library that is generated has /bin/sh hard coded.  Patching this is needed as compiling with nim on device doesn't work with termux-exec. Nim actually mentions termux in the source. Compiling on device on android uses /system/bin/sh as a replacement. 
This issue here is that nim binary doesn't maintain same env from the shell you invoke it with you have to set thoss env variables yourself.

x86_64 android is not specifically supported and trying to enable it by editing the .ini and generating it doesn't work. 
Its not really useful for us to this without at the very least a working koch binary thst can compile nimble on device.

**Comment by its-pointless** [comment]
k i have nimble compiling 
only thing missing is x86_64 arch due to them not sorting out defines with amd64 and android. 
I can get nim to compile but not anything else...

**Comment by its-pointless** [comment]
Ok i seem to be finished branch nim on mine. Probably more elegant ways but there ya go.

**Comment by stephengroat** [comment]
closing in favor of #1877

**Pull request closed without merging**
