### PR TITLE
add(x11): new package spotify-qt

### LINKED ISSUE #10928: [Package]:  spotify-qt
### Package description

An open source Spotify client

### Home page URL

https://github.com/kraxarn/spotify-qt

### Source code URL

https://github.com/kraxarn/spotify-qt

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by T-Dynamos**
closes #10928

### CODE REVIEW

**Review by 2096779623 — CHANGES_REQUESTED** [review]
* Please squash the commits and/or rewrite commit messages to match the formats used in [git history](https://github.com/termux/termux-packages/commits/master), or the format specified in #10748.
* Please enable auto update: https://github.com/termux/termux-packages/wiki/Auto-updating-packages

**Comment by T-Dynamos** [comment]
> * Please squash the commits and/or rewrite commit messages to match the formats used in [git history](https://github.com/termux/termux-packages/commits/master), or the format specified in #10748.
> 
>     * Please enable auto update: https://github.com/termux/termux-packages/wiki/Auto-updating-packages

for auto update what changes I have to do ?

**Comment by 2096779623** [comment]
> > * Please squash the commits and/or rewrite commit messages to match the formats used in [git history](https://github.com/termux/termux-packages/commits/master), or the format specified in [chore(CONTRIBUTING.md): enforce commit guidelines #10748](https://github.com/termux/termux-packages/pull/10748).
> >   
> >   * Please enable auto update: https://github.com/termux/termux-packages/wiki/Auto-updating-packages
> 
> for auto update what changes I have to do ?

Just setting TERMUX_PKG_AUTO_UPDATE=true in build.sh.

**Comment by T-Dynamos** [comment]
Now the executable is not in termux's perfix which produces error
photo_2022-07-04_16-25-05

**Comment by 2096779623** [comment]
> Now the executable is not in termux's perfix which produces error photo_2022-07-04_16-25-05

* If you know where the binaries are, use the `install` command to install to `$PREFIX/bin`. 

https://github.com/2096779623/termux-packages/blob/bb7e03d86395059259152803c23be9b21c3da7db/packages/glab-cli/build.sh#L17

* then make a patch for the `Makefile` (Repair shortcuts).

https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#submitting-new-packages-checklist

**Review by sylirre — CHANGES_REQUESTED** [review]

**Comment by 2096779623** [comment]
image

Change `TERMUX_PKG_LICENSE` to `GPL-3.0` instead of `GPL-2.0`.

**Review by 2096779623 — CHANGES_REQUESTED** [review]
* Please squash the commits and/or rewrite commit messages to match the formats used in [git history](https://github.com/termux/termux-packages/commits/master), or the format specified in #10748.

**Comment by T-Dynamos** [comment]
I am unable to find executable. I even tried building on termux as `termux-chroot` env , but still executable is not installed in prefix

**Comment by 2096779623** [comment]
image

a strange phenomenon.

**Comment by T-Dynamos** [comment]
> image
> 
> a strange phenomenon.

What ! , This archive contains a one more package `flyctl`

**Comment by MrAdityaAlok** [comment]
> What ! , This archive contains a one more package `flyctl`

`flyctl` was recently updated on master branch but your fork is outdated, thus ci considers it to also be changed (in this pr), therefore builds it.

Rebase against master to update.

**Comment by 2096779623** [comment]
Binaries were not installed into `$TERMUX_PREFIX`.

**Pull request closed without merging**
