### PR TITLE
chore(x11/arc-gtk-theme): Remove explicitly added meson commands

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
@kleo Would you like to review the changes please?

**Comment by Biswa96** [comment]
I have removed `TERMUX_PKG_BUILD_IN_SRC=true` to fix the following error after adding the meson options in `TERMUX_PKG_EXTRA_CONFIGURE_ARGS`.

```
ERROR: Source and build directories must not be the same. Create a pristine build directory.
```

**Comment by TomJo2000** [comment]
hmm missed that earlier

**Comment by kleo** [comment]
> @kleo Would you like to review the changes please?

all good. thank you @Biswa96!

**Pull request merged**
