### PR TITLE
liblua54: build with readline support

### PR DESCRIPTION
**Pull request by zorro**

### CODE REVIEW

**Review by xeffyr — APPROVED** [review]

**Comment by xeffyr** [comment]
I guess `TERMUX_PKG_BUILD_DEPENDS="readline"` should be changed, as readline would be a runtime dependency. Will submit a fix, but there shouldn't be any issues anyway (readline is core package).

**Comment by zorro** [comment]
@xeffyr ```readline``` still not working :/

**Comment by zorro** [comment]
> ~I guess `TERMUX_PKG_BUILD_DEPENDS="readline"` should be changed, as readline would be a runtime dependency. Will submit a fix, but there shouldn't be any issues anyway (readline is core package).~
> 
> Update: `readline` is already set as runtime dependency for `lua54` interpreter subpackage.

```readline``` still not linked

**Comment by xeffyr** [comment]
Then change made to makefile was wrong.

`TERMUX_PKG_BUILD_DEPENDS` and `TERMUX_PKG_DEPENDS` only differ in metadata added to package, everything else is same.

`linux-readline` should be passed as `make` argument instead of being set as target platform.

**Pull request merged**
