### PR TITLE
Fix rustc nightly

### PR DESCRIPTION
**Pull request by mukuact**
Update to be able to build and install rustc-nightly

### CODE REVIEW

**Comment by xtkoba** [comment]
`disabled-packages` does not trigger CI. Please move the package into `packages` directory.

**Comment by mukuact** [comment]
Is this OK?

**Comment by Grimler91** [comment]
Thanks for working on this!

Please cleanup the commits. Maybe some of them can be squashed. All of them should preferably have a `rustc-nightly:` prefix so that that it is easy to see what packages they affect when looking through git history (see [git history](https://github.com/termux/termux-packages/commits/master) for how previous commit have been written)

The [`Fix local-rebuild` commit](https://github.com/termux/termux-packages/pull/9581/commits/8739b1121574f74f27030fe7020b5ccdbf5e59da) is followed by [a revert](https://github.com/termux/termux-packages/pull/9581/commits/8ae036d852284a4592690ce59a706f7c78e9f7da), so both of those can be dropped

One of the commit messages just says ["update"](https://github.com/termux/termux-packages/pull/9581/commits/b16ec7490f853aacd9d29c6225e5ea724b3eb379), that should be re-written to be more informative (or squashed).

See for example https://cbea.ms/git-commit/ for some ideas on what makes a good commit message

**Comment by leapofazzam123** [comment]
disabled-packages: exists
@mukuact: ah yes, enabled-packages

**Comment by mukuact** [comment]
@leapofazzam123 
I'm sorry, I force-updated commits before reading your comment and it became off-topic.
What Is this comment for?

**Comment by mukuact** [comment]
"No space left on device" again.
I'll try to reduce disk usage more.

**Comment by Grimler91** [comment]
> "No space left on device" again. I'll try to reduce disk usage more.

Changing the grep pattern [here](https://github.com/termux/termux-packages/blob/master/.github/workflows/packages.yml#L153) to match rustc-nightly as well should help

**Comment by mukuact** [comment]
@Grimler91 
Thank you very much. It works!

**Pull request merged**
