### PR TITLE
Multilibify libcompiler-rt

### PR DESCRIPTION
**Pull request by buttaface**
Let's see if this fixes the upgrade problem for this package.

### CODE REVIEW

**Comment by xtkoba** [comment]
Rewritten as suggested by @buttaface.

**Comment by buttaface** [comment]
I think the symlink approach is better because we're not copying the same libraries over and over again.

**Comment by xtkoba** [comment]
Confirmed that the foreign compiler-rt libraries are populated in `libcompiler-rt_14.0.3-1_aarch64`:

```
$ tar tvf data.tar.xz
drwxr-xr-x builder/builder   0 2022-05-09 06:44 ./
drwxr-xr-x builder/builder   0 2022-05-09 06:44 ./data/
drwxr-xr-x builder/builder   0 2022-05-09 06:44 ./data/data/
drwxr-xr-x builder/builder   0 2022-05-09 06:44 ./data/data/com.termux/
drwxr-xr-x builder/builder   0 2022-05-09 06:44 ./data/data/com.termux/files/
drwxr-xr-x builder/builder   0 2022-05-09 06:44 ./data/data/com.termux/files/usr/
drwxr-xr-x builder/builder   0 2022-05-09 06:44 ./data/data/com.termux/files/usr/lib/
drwxr-xr-x builder/builder   0 2022-05-09 06:44 ./data/data/com.termux/files/usr/lib/clang/
drwxr-xr-x builder/builder   0 2022-05-09 06:44 ./data/data/com.termux/files/usr/lib/clang/14.0.3/
drwxr-xr-x builder/builder   0 2022-05-09 06:44 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/
drwx------ builder/builder   0 2022-05-09 06:33 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/
-rw------- builder/builder 10768 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_minimal-arm-android.so
-rw------- builder/builder 48876 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan_cxx-i686-android.a
-rw------- builder/builder    18 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone_cxx-arm-android.a.syms
-rw------- builder/builder 741592 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-arm-android.so
-rw------- builder/builder 1979738 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.fuzzer-i686-android.a
-rw------- builder/builder   49914 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.hwasan_cxx-x86_64-android.a
-rw------- builder/builder  213112 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone-arm-android.so
-rw------- builder/builder    1129 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.tsan_cxx-x86_64-android.a.syms
-rw------- builder/builder  755412 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo_minimal-i686-android.a
-rw------- builder/builder  119446 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.profile-i686-android.a
-rw------- builder/builder  149070 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.profile-x86_64-android.a
-rw------- builder/builder   37818 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone_cxx-x86_64-android.a
-rw------- builder/builder   70624 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan_cxx-x86_64-android.a
-rw------- builder/builder    1196 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone-arm-android.a.syms
-rw------- builder/builder    3061 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.hwasan-aarch64-android.a.syms
-rw------- builder/builder  864784 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-aarch64-android.so
-rw------- builder/builder  253672 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone-aarch64-android.so
-rw------- builder/builder      18 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_minimal-x86_64-android.a.syms
-rw------- builder/builder 1032784 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.lsan-i686-android.a
-rw------- builder/builder   14276 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_minimal-i686-android.so
-rw------- builder/builder   11286 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo_cxx_minimal-x86_64-android.a
-rw------- builder/builder  859990 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo_minimal-arm-android.a
-rw------- builder/builder 1293254 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo-arm-android.a
-rw------- builder/builder   42818 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_minimal-x86_64-android.a
-rw------- builder/builder   43091 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.tsan-aarch64-android.a.syms
-rw------- builder/builder 1548272 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.stats-aarch64-android.a
-rw------- builder/builder 1162612 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone-arm-android.a
-rw------- builder/builder   16806 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.fuzzer_interceptors-x86_64-android.a
-rw------- builder/builder   77608 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo_minimal-arm-android.so
-rw------- builder/builder 6468578 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.tsan-aarch64-android.a
-rw------- builder/builder     463 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan_cxx-x86_64-android.a.syms
-rw------- builder/builder 3474440 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.fuzzer_no_main-aarch64-android.a
-rw------- builder/builder 3383688 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-arm-android.a
-rw------- builder/builder   91608 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.tsan_cxx-aarch64-android.a
-rw------- builder/builder    2812 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.hwasan-x86_64-android.a.syms
-rw------- builder/builder 2206000 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.fuzzer-arm-android.a
-rw------- builder/builder   88984 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo_minimal-x86_64-android.so
-rw------- builder/builder     164 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.hwasan_cxx-x86_64-android.a.syms
-rw------- builder/builder      18 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_minimal-arm-android.a.syms
-rw------- builder/builder 1184052 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.lsan-arm-android.a
-rw------- builder/builder 4295234 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.tsan-x86_64-android.a
-rw------- builder/builder 1419842 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.lsan-x86_64-android.a
-rw------- builder/builder    6210 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.stats_client-x86_64-android.a
-rw------- builder/builder   39572 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-aarch64-android.a.syms
-rw------- builder/builder 1977758 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.fuzzer_no_main-i686-android.a
-rw------- builder/builder   55370 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone_cxx-aarch64-android.a
-rw------- builder/builder    1278 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-preinit-aarch64-android.a
-rw------- builder/builder   27278 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone_cxx-i686-android.a
-rw------- builder/builder    1644 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan_static-aarch64-android.a
-rw------- builder/builder     463 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan_cxx-aarch64-android.a.syms
-rw------- builder/builder   32782 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone_cxx-arm-android.a
-rw------- builder/builder 3114778 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.fuzzer-x86_64-android.a
-rw------- builder/builder   13976 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_minimal-x86_64-android.so
-rw------- builder/builder   13608 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_minimal-aarch64-android.so
-rw------- builder/builder   20934 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.fuzzer_interceptors-aarch64-android.a
-rw------- builder/builder 2411658 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.hwasan-aarch64-android.a
-rw------- builder/builder 3477262 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.fuzzer-aarch64-android.a
-rw------- builder/builder 1814468 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.hwasan-x86_64-android.a
-rw------- builder/builder 1039240 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo_minimal-x86_64-android.a
-rw------- builder/builder    5174 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.stats_client-arm-android.a
-rw------- builder/builder   42556 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.tsan-x86_64-android.a.syms
-rw------- builder/builder     416 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.hwasan_cxx-aarch64-android.a.syms
-rw------- builder/builder    1222 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-preinit-x86_64-android.a
-rw------- builder/builder   93440 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan_cxx-aarch64-android.a
-rw------- builder/builder   38698 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_minimal-arm-android.a
-rw------- builder/builder 1551596 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo-x86_64-android.a
-rw------- builder/builder   41322 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-arm-android.a.syms
-rw------- builder/builder    1129 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.tsan_cxx-aarch64-android.a.syms
-rw------- builder/builder   36236 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo_cxx-i686-android.a
-rw------- builder/builder     463 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan_cxx-arm-android.a.syms
-rw------- builder/builder      18 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_minimal-aarch64-android.a.syms
-rw------- builder/builder  850596 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.stats-i686-android.a
-rw------- builder/builder 3950944 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-x86_64-android.a
-rw------- builder/builder  156714 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.profile-aarch64-android.a
-rw------- builder/builder 1014080 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone-i686-android.a
-rw------- builder/builder  334640 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.hwasan-aarch64-android.so
-rw------- builder/builder  232960 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo-i686-android.so
-rw------- builder/builder    4530 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.stats_client-i686-android.a
-rw------- builder/builder    1196 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone-x86_64-android.a.syms
-rw------- builder/builder  967904 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.stats-arm-android.a
-rw------- builder/builder  144704 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.builtins-i686-android.a
-rw------- builder/builder  168952 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo-arm-android.so
-rw------- builder/builder    1082 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-preinit-arm-android.a
-rw------- builder/builder    9090 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo_cxx_minimal-i686-android.a
-rw------- builder/builder  347680 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone-x86_64-android.so
-rw------- builder/builder  282784 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.hwasan-x86_64-android.so
-rw------- builder/builder   44730 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_minimal-aarch64-android.a
-rw------- builder/builder   80638 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.hwasan_cxx-aarch64-android.a
-rw------- builder/builder   30954 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_minimal-i686-android.a
-rw------- builder/builder      18 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone_cxx-aarch64-android.a.syms
-rw------- builder/builder   48972 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo_cxx-x86_64-android.a
-rw------- builder/builder 3112250 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.fuzzer_no_main-x86_64-android.a
-rw------- builder/builder 1897378 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.lsan-aarch64-android.a
-rw------- builder/builder 2749142 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-i686-android.a
-rw------- builder/builder   10814 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo_cxx_minimal-arm-android.a
-rw------- builder/builder 1268346 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.orc-aarch64-android.a
-rw------- builder/builder   43464 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo_cxx-arm-android.a
-rw------- builder/builder   13366 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.fuzzer_interceptors-arm-android.a
-rw------- builder/builder   39069 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-x86_64-android.a.syms
-rw------- builder/builder   96556 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo_minimal-i686-android.so
-rw------- builder/builder  953128 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.tsan-aarch64-android.so
-rw------- builder/builder    6898 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.stats_client-aarch64-android.a
-rw------- builder/builder  822160 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-x86_64-android.so
-rw------- builder/builder 1378858 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone-x86_64-android.a
-rw------- builder/builder  134058 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.profile-arm-android.a
-rw------- builder/builder  216900 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.builtins-arm-android.a
-rw------- builder/builder      18 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone_cxx-x86_64-android.a.syms
-rw------- builder/builder    1196 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone-aarch64-android.a.syms
-rw------- builder/builder  353956 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone-i686-android.so
-rw------- builder/builder   63216 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan_cxx-arm-android.a
-rw------- builder/builder     966 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-preinit-i686-android.a
-rw------- builder/builder  216304 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo-x86_64-android.so
-rw------- builder/builder   68336 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.tsan_cxx-x86_64-android.a
-rw------- builder/builder   12042 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.fuzzer_interceptors-i686-android.a
-rw------- builder/builder 1146506 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.stats-x86_64-android.a
-rw------- builder/builder 1124138 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.scudo-i686-android.a
-rw------- builder/builder 2203800 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.fuzzer_no_main-arm-android.a
-rw------- builder/builder 1840638 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.ubsan_standalone-aarch64-android.a
-rw------- builder/builder  845820 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-i686-android.so
-rw------- builder/builder  285936 2022-05-09 06:32 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.builtins-x86_64-android.a
-rw------- builder/builder  360674 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.builtins-aarch64-android.a
-rw------- builder/builder 4997430 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux/libclang_rt.asan-aarch64-android.a
drwxr-xr-x builder/builder       0 2022-05-09 06:44 ./data/data/com.termux/files/usr/lib/clang/14.0.3/share/
-rw------- builder/builder     285 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/share/hwasan_ignorelist.txt
-rw------- builder/builder     516 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/share/asan_ignorelist.txt
-rw------- builder/builder     590 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/share/cfi_ignorelist.txt
drwxr-xr-x builder/builder       0 2022-05-09 06:44 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/
drwxr-xr-x builder/builder       0 2022-05-09 06:44 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/fuzzer/
-rw------- builder/builder   16125 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/fuzzer/FuzzedDataProvider.h
drwx------ builder/builder       0 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/xray/
-rw------- builder/builder   15991 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/xray/xray_log_interface.h
-rw------- builder/builder    3941 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/xray/xray_records.h
-rw------- builder/builder    5225 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/xray/xray_interface.h
drwxr-xr-x builder/builder       0 2022-05-09 06:44 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/profile/
-rw------- builder/builder   34141 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/profile/InstrProfData.inc
drwx------ builder/builder       0 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/
-rw------- builder/builder    1491 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/scudo_interface.h
-rw------- builder/builder   12627 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/asan_interface.h
-rw------- builder/builder    9713 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/tsan_interface_atomic.h
-rw------- builder/builder  218505 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/linux_syscall_hooks.h
-rw------- builder/builder    5118 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/msan_interface.h
-rw------- builder/builder    3935 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/lsan_interface.h
-rw------- builder/builder    8072 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/dfsan_interface.h
-rw------- builder/builder    7787 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/tsan_interface.h
-rw------- builder/builder    3932 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/allocator_interface.h
-rw------- builder/builder    4331 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/hwasan_interface.h
-rw------- builder/builder  355693 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/netbsd_syscall_hooks.h
-rw------- builder/builder   15879 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/common_interface_defs.h
-rw------- builder/builder    1030 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/ubsan_interface.h
-rw------- builder/builder    1054 2022-05-09 06:31 ./data/data/com.termux/files/usr/lib/clang/14.0.3/include/sanitizer/coverage_interface.h
drwxr-xr-x builder/builder       0 2022-05-09 06:44 ./data/data/com.termux/files/usr/lib/clang/14.0.3/bin/
-rwx------ builder/builder   13787 2022-05-09 06:33 ./data/data/com.termux/files/usr/lib/clang/14.0.3/bin/asan_device_setup
-rwx------ builder/builder   10442 2022-05-09 06:33 ./data/data/com.termux/files/usr/lib/clang/14.0.3/bin/hwasan_symbolize
```

**Comment by xtkoba** [comment]
Superseded by #10539.

**Pull request closed without merging**
