### PR TITLE
m4: Bump to 1.4.19

### PR DESCRIPTION
**Pull request by thunder-coding**

### CODE REVIEW

**Comment by suhan-paradkar** [comment]
You may need to use `-D_FORTIFY_SOURCE` meson option...

**Comment by suhan-paradkar** [comment]
I just can't make out what is wrong here...
My suggestion was based on [this article](https://developers.redhat.com/blog/2020/02/11/toward-_fortify_source-parity-between-clang-and-gcc) tho

**Comment by thunder-coding** [comment]
> I just can't make out what is wrong here...
> My suggestion was based on [this article](https://developers.redhat.com/blog/2020/02/11/toward-_fortify_source-parity-between-clang-and-gcc) tho

Probably, I should try passing it to `make`/`cmake`/`automake`

**Comment by Grimler91** [comment]
Add it to CPPFLAGS, or possibly CFLAGS, as done by for example coreutils: https://github.com/termux/termux-packages/blob/685ec5500cdd4f130cf7871b64c9433fc2d71ad4/packages/coreutils/build.sh#L29

**Review by xeffyr — APPROVED** [review]

**Pull request merged**
