### PR TITLE
ccls: build from latest commit & llvm 14 rebuild

### PR DESCRIPTION
**Pull request by thunder-coding**

### CODE REVIEW

**Comment by buttaface** [comment]
Looks like this doesn't build against LLVM 14, @librevm, anything we should do?

**Comment by thunder-coding** [comment]
Well, I was able to build locally (on-device) from the master branch without any patches. Probably we should be asking upstream to do a new tagged release, other distributions will also be thankful for this!

**Comment by thunder-coding** [comment]
Going forward and merging this. Everything seems to be fine locally

**Comment by buttaface** [comment]
I'd rather wait for the next release.

**Pull request merged**
