### PR TITLE
electric-fence: fix cross-compilation

### PR DESCRIPTION
**Pull request by landfillbaby**
oops!

### CODE REVIEW

**Comment by landfillbaby** [comment]
uh, do i need to list ndk-sysroot as a dependency since that what has libpthread?

**Comment by landfillbaby** [comment]
btw i'll stop using the build system and force pushes so much once my pc is fixed, i'll build on that instead, sorry

**Comment by Grimler91** [comment]
> btw i'll stop using the build system and force pushes so much once my pc is fixed, i'll build on that instead, sorry

Don't worry about it, the CI is here for testing builds, it is good that it is being used!

**Comment by landfillbaby** [comment]
so. there's a choice to make here. -lpthread but no static, or static but no -lpthread
or would it be alright to build dynamically with pthread and statically without?

**Comment by landfillbaby** [comment]
oh also how would i handle that there was previously a static package if i were to delete it?

**Comment by landfillbaby** [comment]
ok pthread just doesn't work on x86(-64), it does on arm and aarch64

**Comment by landfillbaby** [comment]
whatever. no pthread. let's merge it

**Comment by landfillbaby** [comment]
wait. why did it work the first time but not now :(

**Comment by landfillbaby** [comment]
it seems the build system still keeps the contents of commits if you force revert to a previous one? idk

**Comment by landfillbaby** [comment]
ok! once this test passes i think it should be perfect! the _GNU_SOURCE is because of strerror_r's return type

**Comment by landfillbaby** [comment]
ok it definitely 100% works now for sure

**Comment by landfillbaby** [comment]
ok build passed, can't think of anything more to change, it's all good! please merge

**Comment by landfillbaby** [comment]
note that it includes weak references to pthread sem_{init,post,wait} functions despite never being linked to them :)

**Pull request merged**
