### PR TITLE
Enable ghostscript

### PR DESCRIPTION
**Pull request by Grimler91**
Seems to work. 
I blacklisted i686 and x86_64 until we have created the headers for them. 

Note that I don't use archlinux so I'm not 100 % sure if the packages "expat" and "ibjpeg-turbo" are the ones that provide the correct files.

### CODE REVIEW

**Comment by Grimler91** [comment]
Package now builds for all arches. I haven't tested it on x86_64 or i686 but I trust bug reports will be filed if there are any problems. 

Shouldn't be anything else standing in the way of a merge.

**Comment by Grimler91** [comment]
Travis build seem to have failed due to the ubuntu packages `libexpat1-dev` and `libjpeg-dev` not being installed in the docker image.

**Comment by Grimler91** [comment]
Ghostscript is available in @its-pointless [repo](https://github.com/its-pointless/its-pointless.github.io).

**Comment by rnauber** [comment]
This works very well for me. @fornwall:  Would you mind to merge it?

Thanks,
Richard

**Comment by fornwall** [comment]
Nice! The built package is now available in the package repository for installation.

**Comment by Grimler91** [comment]
@fornwall apparently arch-aarch64.h now exists both in https://github.com/termux/termux-packages/tree/master/disabled-packages/ghostscript and https://github.com/termux/termux-packages/tree/master/packages/ghostscript

**Comment by fornwall** [comment]
@Grimler91 Don't know why disabled-packages/ghostscript was left over, I've removed it now.

**Comment by ExarchD** [comment]
This might not be the right place, but I cannot seem to install ghostscript:
`pkg install ghostscript'
Still gives:
Unable to locate package ghostscript

**Comment by Grimler91** [comment]
@ExarchD that seems weird. What is the output of `apt update`? 

Do you see the package with `pkg search ghostscript`?

Which arch are you on?

**Comment by sdrausty** [comment]
@Grimler91 ghostscript/stable,now 9.21 aarch64 [installed]

**Comment by ExarchD** [comment]
`localhost ~  % apt update
Hit:1 http://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.`

I don't see the package with search. My arch is armv8l...this may be the problem?

**Comment by Grimler91** [comment]
@ExarchD Which device do you have? What's the output of `uname -a`?

**Comment by ExarchD** [comment]
`Linux localhost 4.4.70-11295-gf64189f58926 #1 SMP PREEMPT Wed Aug 16 21:53:32 PDT 2017 armv8l Android`

Its a chromebook

**Comment by Grimler91** [comment]
Do you have this problem only for ghostscript or for other packages as well?

**Comment by ExarchD** [comment]
No other issues:
```
@localhost ~  % pkg install emacs
Hit:1 http://termux.net stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
7 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  gnutls
The following NEW packages will be installed:
  emacs gnutls
0 upgraded, 2 newly installed, 0 to remove and 7 not upgraded.
Need to get 34.1 MB of archives.
After this operation, 97.1 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Comment by ExarchD** [comment]
Well...now I tried ghostscript again and its suddenly working...I have no idea what's changed. I must have run that same command a dozen times today

**Pull request merged**
