### PR TITLE
enhance(x11/qt6-qtdeclarative): Build all tools same as host cross tools packages

### PR DESCRIPTION
**Pull request by Biswa96**
Same as #20379

### CODE REVIEW

**Comment by Biswa96** [comment]
<details><summary>Here are the list of added files in qt6-qtdeclarative 6.7.1-1 compared with 6.7.1</summary>

```diff
@@ -4,6 +4,12 @@
 ./data/data/com.termux/
 ./data/data/com.termux/files/
 ./data/data/com.termux/files/usr/
+./data/data/com.termux/files/usr/bin/
+./data/data/com.termux/files/usr/bin/qml6
+./data/data/com.termux/files/usr/bin/qmleasing6
+./data/data/com.termux/files/usr/bin/qmlls6
+./data/data/com.termux/files/usr/bin/qmlpreview6
+./data/data/com.termux/files/usr/bin/qmlscene6
 ./data/data/com.termux/files/usr/include/
 ./data/data/com.termux/files/usr/include/qt6/
 ./data/data/com.termux/files/usr/include/qt6/QtLabsAnimation/
@@ -1993,6 +1999,11 @@
 ./data/data/com.termux/files/usr/lib/cmake/Qt6QmlDomPrivate/Qt6QmlDomPrivateTargets-release.cmake
 ./data/data/com.termux/files/usr/lib/cmake/Qt6QmlDomPrivate/Qt6QmlDomPrivateTargets.cmake
 ./data/data/com.termux/files/usr/lib/cmake/Qt6QmlDomPrivate/Qt6QmlDomPrivateVersionlessTargets.cmake
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlImportScanner/
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlImportScanner/Qt6QmlImportScannerConfig.cmake
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlImportScanner/Qt6QmlImportScannerConfigVersion.cmake
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlImportScanner/Qt6QmlImportScannerConfigVersionImpl.cmake
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlImportScanner/Qt6QmlImportScannerDependencies.cmake
 ./data/data/com.termux/files/usr/lib/cmake/Qt6QmlIntegration/
 ./data/data/com.termux/files/usr/lib/cmake/Qt6QmlIntegration/Qt6QmlIntegrationAdditionalTargetInfo.cmake
 ./data/data/com.termux/files/usr/lib/cmake/Qt6QmlIntegration/Qt6QmlIntegrationConfig.cmake
@@ -2045,6 +2056,15 @@
 ./data/data/com.termux/files/usr/lib/cmake/Qt6QmlToolingSettingsPrivate/Qt6QmlToolingSettingsPrivateTargets-release.cmake
 ./data/data/com.termux/files/usr/lib/cmake/Qt6QmlToolingSettingsPrivate/Qt6QmlToolingSettingsPrivateTargets.cmake
 ./data/data/com.termux/files/usr/lib/cmake/Qt6QmlToolingSettingsPrivate/Qt6QmlToolingSettingsPrivateVersionlessTargets.cmake
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlTools/
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlTools/Qt6QmlToolsAdditionalTargetInfo.cmake
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlTools/Qt6QmlToolsConfig.cmake
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlTools/Qt6QmlToolsConfigVersion.cmake
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlTools/Qt6QmlToolsConfigVersionImpl.cmake
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlTools/Qt6QmlToolsDependencies.cmake
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlTools/Qt6QmlToolsTargets-release.cmake
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlTools/Qt6QmlToolsTargets.cmake
+./data/data/com.termux/files/usr/lib/cmake/Qt6QmlTools/Qt6QmlToolsVersionlessTargets.cmake
 ./data/data/com.termux/files/usr/lib/cmake/Qt6QmlTypeRegistrarPrivate/
 ./data/data/com.termux/files/usr/lib/cmake/Qt6QmlTypeRegistrarPrivate/Qt6QmlTypeRegistrarPrivateAdditionalTargetInfo.cmake
 ./data/data/com.termux/files/usr/lib/cmake/Qt6QmlTypeRegistrarPrivate/Qt6QmlTypeRegistrarPrivateConfig.cmake
@@ -2504,10 +2524,18 @@
 ./data/data/com.termux/files/usr/lib/qt6/
 ./data/data/com.termux/files/usr/lib/qt6/bin/
 ./data/data/com.termux/files/usr/lib/qt6/bin/qml
+./data/data/com.termux/files/usr/lib/qt6/bin/qmldom
 ./data/data/com.termux/files/usr/lib/qt6/bin/qmleasing
+./data/data/com.termux/files/usr/lib/qt6/bin/qmlformat
+./data/data/com.termux/files/usr/lib/qt6/bin/qmllint
 ./data/data/com.termux/files/usr/lib/qt6/bin/qmlls
+./data/data/com.termux/files/usr/lib/qt6/bin/qmlplugindump
 ./data/data/com.termux/files/usr/lib/qt6/bin/qmlpreview
+./data/data/com.termux/files/usr/lib/qt6/bin/qmlprofiler
 ./data/data/com.termux/files/usr/lib/qt6/bin/qmlscene
+./data/data/com.termux/files/usr/lib/qt6/bin/qmltc
+./data/data/com.termux/files/usr/lib/qt6/bin/qmltestrunner
+./data/data/com.termux/files/usr/lib/qt6/bin/qmltime
 ./data/data/com.termux/files/usr/lib/qt6/metatypes/
 ./data/data/com.termux/files/usr/lib/qt6/metatypes/qt6labsanimation_release_metatypes.json
 ./data/data/com.termux/files/usr/lib/qt6/metatypes/qt6labsfolderlistmodel_release_metatypes.json
@@ -2557,7 +2585,9 @@
 ./data/data/com.termux/files/usr/lib/qt6/metatypes/qt6quickwidgets_release_metatypes.json
 ./data/data/com.termux/files/usr/lib/qt6/mkspecs/
 ./data/data/com.termux/files/usr/lib/qt6/mkspecs/features/
+./data/data/com.termux/files/usr/lib/qt6/mkspecs/features/qmlcache.prf
 ./data/data/com.termux/files/usr/lib/qt6/mkspecs/features/qmltypes.prf
+./data/data/com.termux/files/usr/lib/qt6/mkspecs/features/qtquickcompiler.prf
 ./data/data/com.termux/files/usr/lib/qt6/mkspecs/modules/
 ./data/data/com.termux/files/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri
 ./data/data/com.termux/files/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri
@@ -2706,6 +2736,9 @@
 ./data/data/com.termux/files/usr/lib/qt6/plugins/qmltooling/libqmldbg_server.so
 ./data/data/com.termux/files/usr/lib/qt6/plugins/qmltooling/libqmldbg_tcp.so
 ./data/data/com.termux/files/usr/lib/qt6/qml/
+./data/data/com.termux/files/usr/lib/qt6/qml/QmlTime/
+./data/data/com.termux/files/usr/lib/qt6/qml/QmlTime/qmldir
+./data/data/com.termux/files/usr/lib/qt6/qml/QmlTime/qmltime_native.qmltypes
 ./data/data/com.termux/files/usr/lib/qt6/qml/Qt/
 ./data/data/com.termux/files/usr/lib/qt6/qml/Qt/labs/
 ./data/data/com.termux/files/usr/lib/qt6/qml/Qt/labs/animation/
@@ -3378,6 +3411,10 @@
 ./data/data/com.termux/files/usr/lib/qt6/qml/QtTest/testlogger.js
 ./data/data/com.termux/files/usr/lib/qt6/qml/builtins.qmltypes
 ./data/data/com.termux/files/usr/lib/qt6/qml/jsroot.qmltypes
+./data/data/com.termux/files/usr/lib/qt6/qmlcachegen
+./data/data/com.termux/files/usr/lib/qt6/qmlimportscanner
+./data/data/com.termux/files/usr/lib/qt6/qmljsrootgen
+./data/data/com.termux/files/usr/lib/qt6/qmltyperegistrar
 ./data/data/com.termux/files/usr/share/
 ./data/data/com.termux/files/usr/share/doc/
 ./data/data/com.termux/files/usr/share/doc/qt6-qtdeclarative/
```

</summary>

**Comment by TomJo2000** [comment]
Is this something we'll need to do for all the Qt library packages?

**Comment by TomJo2000** [comment]
> Here are the list of added files in qt6-qtdeclarative 6.7.1-1 compared with 6.7.1

How did you diff the two packages by the way I was gonna look into getting #20389 implemented.
And that looks like a good starting point.

**Comment by Biswa96** [comment]
> How did you diff the two packages by the way

1. Download old package.
2. Download CI artifact.
3. `diff_deb_files old-package.deb new-package.deb`

**Review by truboxl — APPROVED** [review]

**Pull request merged**
