### PR TITLE
Update libtalloc to 2.2.0

### PR DESCRIPTION
**Pull request by TheBrokenRail**

### CODE REVIEW

**Comment by xeffyr** [comment]
Updating version number and sha256 isn't enough. Cross-answers.txt has to be fixed as well otherwise it will fail at configuration stage.

**Comment by TheBrokenRail** [comment]
What was wrong with cross-answers.txt?

**Comment by xeffyr** [comment]
Seems like it is ignored at all. I was not able to make it working properly.

**Comment by xeffyr** [comment]
I see a lot of lines about exec format error in log file. They look like following one:
```
OSError: [Errno 8] Exec format error: '/home/builder/.termux-build/libtalloc/src/bin/.conf_check_73e60e927ca15bdb7c513c7b47fff3e7/testbuild/default/testprog'
```

**Comment by xeffyr** [comment]
Option `--cross-compile` doesn't work at all on version 2.2.0.
On v2.1 I can generate template for cross-answers by executing `./configure --cross-compile --cross-answers=answers.txt`. Resulting template was:
```
Checking uname sysname type: UNKNOWN
Checking uname machine type: UNKNOWN
Checking uname release type: UNKNOWN
Checking uname version type: UNKNOWN
Checking simple C program: UNKNOWN
```

But on v2.2 I cannot obtain it because waf assumes that no cross compilation was enabled.

**Pull request closed without merging**
