### PR TITLE
new package: gum

### PR DESCRIPTION
**Pull request by pvonmoradi**
Adds [gum](https://github.com/charmbracelet/gum/)

### CODE REVIEW

**Review by sylirre — APPROVED** [review]

**Comment by eggbean** [comment]
This program isn't working on termux. I don't know how long this has been happening as I have not used it on termux until now.

More details here:
https://github.com/termux/termux-packages/issues/18420

**Comment by pvonmoradi** [comment]
I just tested the examples listed on [project's readme](https://github.com/charmbracelet/gum). They all worked fine.

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
```
Your example would work if you invoke the command like this:
`gum spin --title "foo" -- sh -c ./foo.sh`

**Comment by eggbean** [comment]
@pvonmoradi Okay thanks, that was an easy fix for my scripts.

But there is something different going on, as my scripts work without the the addtional subshell(?) on non-termux systems.

**Comment by pvonmoradi** [comment]
> But there is something different going on, as my scripts work without the the addtional subshell(?) on non-termux systems.

I can confirm this. The x86 build doesn't need that `sh -c`. Don't know the reason though.

**Pull request merged**
