### PR TITLE
ffmpeg enable libvpx (WebM encoder)

### PR DESCRIPTION
**Pull request by belldandu**
https://trac.ffmpeg.org/wiki/Encode/VP8

### CODE REVIEW

**Comment by belldandu** [comment]
This is probably the simplest patch i've ever done. @fornwall

**Comment by its-pointless** [comment]
yeah i could build it usimg this change but it wouldn't complete package without changing the libvpx build before hand. since libvpx was not configured with vp8 support. so for this to be complete you will have to patch libvpx build. thus possibley ruining simplist patch status.

**Comment by belldandu** [comment]
I must have missed that. Is there a reason libvpk has the `--disable-vp8` flag in its build?

**Comment by fornwall** [comment]
Thanks! The updated packages (with version numbers bumped) will be available in the apt repository shortly!

**Pull request merged**
