### PR TITLE
add(main): new package godot

### PR DESCRIPTION
**Pull request by Maxython**
https://github.com/godotengine/godot/issues/73233

### CODE REVIEW

**Comment by Maxython** [comment]
@T-Dynamos, this is an excuse to compile blender for termux /j
Screenshot_20230305-174643_Termux

**Comment by T-Dynamos** [comment]
> @T-Dynamos, this is an excuse to compile blender for termux /j Screenshot_20230305-174643_Termux

Yep, you can count on me to keep working on porting Blender from March 21st onwards! That's actually the day of my last exam, so I'll be all set to dive back in after that. Excited to keep going!

**Comment by Maxython** [comment]
Godot 4 is quite different from Godot 3, not only in functionality but also in compilation steps.  I think that it will not be bad to add Godot 3 to TUR.

@licy183

**Comment by Maxython** [comment]
The `forward+` and `mobile` render methods need the `vulkan` driver to work, which unfortunately is not in our `mesa`. Because of this, they work intermittently. If you specify an `opengl3` driver, they work, but then they lose their mind, since their common goal is "uses RenderingDevice backend".

So I understand that it would be a bad idea to use the `vulkan` driver that android offers?

Screenshot_20230307-173705_VNC Viewer
Screenshot_20230307-173712_VNC Viewer

**Comment by Maxython** [comment]
@licy183, thanks for help.

**Comment by Maxython** [comment]
**Note:** all render methods will use the opengl3 driver. Yes, some functions will not work (for example, TAA in forward+), but they will work more stable. And because of this, godot's vulkan driver will not be disabled, which will allow the user to choose which driver to use, and also for us (the developers) it will be a good testing method if we want to support vulkan on termux.

**Pull request merged**
