### PR TITLE
nala: update 0.7.2 -> 0.11.0

### PR DESCRIPTION
**Pull request by TomJo2000**
Update the `nala` front-end for `apt` from version 0.7.2 to latest stable release, ~~0.10.0~~ 0.11.0

(Please inform me of any issues regarding this Pull Request at your earliest convenience, its my first PR and I'm pretty nervous about potentially having missed something even after reading the contributor readme about 5 times.)

[Edit: Release of `nala` 0.11.0 brings native support for Termux.]

### CODE REVIEW

**Review by 2096779623 — CHANGES_REQUESTED** [review]
Can you squash the commits?

**Comment by 2096779623** [comment]
https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#submitting-new-packages-checklist

Check out the patch section in this link to learn how to fix this.

**Comment by TomJo2000** [comment]
I'm sorry I'm really jumpy right now.
I'm doing my best, but I haven't done this before.

**Comment by 2096779623** [comment]
> I'm sorry I'm really jumpy right now. I'm doing my best, but I haven't done this before.

Don't worry, take your time!

**Comment by TomJo2000** [comment]
I'm so sorry.
I haven't slept in like 18 hours.
I'll convert this to a draft for the time being.

**Comment by volitank** [comment]
Hello,

I'm the developer for Nala. I've noticed recently a lot of people have been using this in termux, and the required patch is rather large with all the strings that need to be changed.

Additionally there have been so many changes since the version in termux that it would be a little bit involved to make all the proper changes. I have a lot of bug fixes to attend due to the large increase of users.

I would like to properly support termux in the next release once I get all of these hashed out. It would be `0.11.0` due to some new features, but I would like to add a constant bool like `TERMUX = False` so that the patch to include it would just need that changed and everything would work.

With my few projects I'm extremely busy, so I can only imagine how busy the devs here are. I think this would make things much smoother for everyone if I officially supported the environment.

**Comment by TomJo2000** [comment]
> [...] 
> I would like to properly support termux in the next release once I get all of these hashed out. It would be `0.11.0` due to some new features, but I would like to add a constant bool like `TERMUX = False` so that the patch to include it would just need that changed and everything would work.
> 
> With my few projects I'm extremely busy, so I can only imagine how busy the devs here are. I think this would make things much smoother for everyone if I officially supported the environment.

Hi thanks for the feedback, I'm a huge fan of your work with `nala`
I unfortunately haven't had time to work on this today due to the fact that we've been renovating the house.

If you're considering adding improved Termux compatibility in the next release though,
it may just be best to hold off on updating the package on the Termux repos for the time being
until we know how that is going to work in detail.

**Comment by volitank** [comment]
Thank you, I'm glad you like it.

That's the goal. I just think it would be smoother for everyone, because undoubtedly I'll be the first line when a Termux Nala user has an issue. And I don't really want to just tell people to ship all Termux concerns your way.

Upgrade paths will be smoother, and with Nala being still relatively new at this point, being on the latest version is pretty important.

IMO it would be best to hold off until the next release. I'm going to try to get it pushed out this week, because there are some pretty widespread bugs with the current release. Nothing in danger to the system, mostly small inconveniences and Ubuntu 20.04 users can't use `nala fetch` along with Mint, Mint Debian, and Zorin OS.

**Comment by volitank** [comment]
I think this commit should do most of the things that was needed in the last patch. Any file paths I add I'll follow this so there shouldn't need to be any worry from y'all.

Let me know if there is anything else that should be added, or if you see a better way, etc.

One benefit of this is that I know the source code very well, I'd imagine it would take a while for someone to patch it who doesn't.

I'm hoping I can get the release out tomorrow if I'm not too busy. Just a few more things need fixed before I can.

https://gitlab.com/volian/nala/-/commit/45aeb8cbbd9ebd19f058df791b394dc138d43b90

**Comment by TomJo2000** [comment]
Squashed the commits, I've been really busy with house renovations so I hadn't found the time until now.

**Comment by TomJo2000** [comment]
This will probably need to be squashed again pending version 0.11.0
> ***(see)***
> [...]
> I would like to properly support termux in the next release once I get all of these hashed out. It would be `0.11.0` due to some new features, but I would like to add a constant bool like `TERMUX = False` so that the patch to include it would just need that changed and everything would work.
> 
> With my few projects I'm extremely busy, so I can only imagine how busy the devs here are. I think this would make things much smoother for everyone if I officially supported the environment.
> [...]
> https://gitlab.com/volian/nala/-/commit/45aeb8cbbd9ebd19f058df791b394dc138d43b90

I'll also need to have another look at the patch files.

**Comment by TomJo2000** [comment]
I'm closing this PR since it has been [superseded by #11843](https://github.com/termux/termux-packages/pull/11843).

**Pull request closed without merging**
