### PR TITLE
upgpkg(main/seafile-client): from 8.0.3 to 8.0.7

### PR DESCRIPTION
**Pull request by tjhexf**

### CODE REVIEW

**Comment by 2096779623** [comment]
> 2022-06-20T06:28:01.5281159Z INFO: Updating seafile-client [Current version: 8.0.3] 2022-06-20T06:28:02.1690050Z INFO: No update needed. Already at version '7.0.9'.
> 
> from the auto-update log, lol. Any idea why the auto-update is reporting a wrong version?

Because the automatic update will be obtained from Github, the version of the official website is 8.0.7, and their apt source is also 8.0.7 (some are still at 8.0.5).

**Comment by tjhexf** [comment]
> > 2022-06-20T06:28:01.5281159Z INFO: Updating seafile-client [Current version: 8.0.3] 2022-06-20T06:28:02.1690050Z INFO: No update needed. Already at version '7.0.9'.
> > from the auto-update log, lol. Any idea why the auto-update is reporting a wrong version?
> 
> Because the automatic update will be obtained from Github, the version of the official website is 8.0.7, and their apt source is also 8.0.7 (some are still at 8.0.5).
> 
> Refer to this link to write an auto-updating script: https://github.com/termux/termux-packages/wiki/Auto-updating-packages#overriding

i took that part from the github actions of this repo. It seems the default script for the update action is saying the latest version is 7.0.9, when its not

**Comment by tjhexf** [comment]
Done, switched the auto-update method, now it can properly auto update :)

**Review by 2096779623 — APPROVED** [review]
Good job!
One suggestion: change `http` in `TERMUX_PKG_HOMEPAGE` to `https`.

**Pull request merged**
