### PR TITLE
fix(x11/glade): fix build with current meson version

### PR DESCRIPTION
**Pull request by Grimler91**
Seems i18n.merge_file function has been changed in non backward-compatible way.  See for example https://gitlab.gnome.org/GNOME/aisleriot/-/issues/916 for a similar fix.

Fixes termux/termux-packages#11156.

### CODE REVIEW

**Comment by Grimler91** [comment]
New issue here seem to be github CI or docker specific: 

```
 [76/367] Generating gladeui/gladeui-resources_h with a custom command
FAILED: gladeui/gladeui-resources.h 
/usr/bin/glib-compile-resources ../src/gladeui/gladeui-resources.gresource.xml --sourcedir gladeui --sourcedir ../src/gladeui --c-name _gladeui --generate --target gladeui/gladeui-resources.h
../src/gladeui/gladeui-resources.gresource.xml: Failed to close file descriptor for child process (Operation not permitted).
```

**Comment by ifurther** [comment]
The same as https://github.com/termux/termux-packages/issues/11357.

**Comment by eli-schwartz** [comment]
> Seems i18n.merge_file function has been changed in non backward-compatible way.

It was actually a sanity check, by the way. The function never documented and never used a positional argument, because it wasn't ever supposed to accept one. But for a time, if you used one anyway it was silently ignored and did nothing, instead of erroring out.

**Comment by licy183** [comment]
We could pass `--security-opt seccomp=unconfined` to solve this error until docker has a solution for it, or change our building system so that it doesn't use docker (https://github.com/termux/termux-packages/pull/11389#issuecomment-1200153653).

**Pull request merged**
