### PR TITLE
texlive-bin: avoid changing {lua,pdf,xe}tex patches all the time

### PR DESCRIPTION
**Pull request by tomty89**
Patches and sed command are directly from Arch Linux. We just need
to steal from it whenever they are changed.

### CODE REVIEW

**Comment by fornwall** [comment]
@Grimler91 Feel free to merge this if you are ok with it!

**Comment by Grimler91** [comment]
I'll merge it tomorrow, just want to compare with the texlive 2019 pre-release and see how different those sources are

**Comment by tomty89** [comment]
@Grimler91 I force-pushed to revert the fast build commit and fix the space problem. I hope you don't mind.

**Comment by Grimler91** [comment]
@tomty89 texlive 2019 does quite a lot of changes to the luatex dir. I suggest that we wait with updating the patches until we update texlive to texlive 2019, it should be released in a month or so.

Pre-test source tars are available: https://github.com/TeX-Live/texlive-source/releases

**Comment by tomty89** [comment]
@Grimler91 To be honest, I'm not sure what's the point in holding back this (and the updating of poppler). Arch will be bumping their texlive to 2019 anyway, most likely we would just need to steal whatever that will be changed.  But if you insist.

**Comment by Grimler91** [comment]
@tomty89 Hm, I though we had already merged the poppler update PR, but that doesn't seem to be the case. 
Do you want to switch to these patches at the same time as we bump poppler to 0.74?

**Comment by tomty89** [comment]
@Grimler91 yeah, as we apparently need a rebuild of texlive-bin for the bump, I think it would be nice that we merge this at the same time, so the rebuild would be done with it. I was hoping to get openjpeg fixed for fast building poppler first though (hence #3397 and #3474).

**Comment by tomty89** [comment]
@Grimler91 openjpeg itself is fine for fast building poppler now (just not the build scripts), so if you don't feel like we should wait for texlive 2019 anymore, this can be merged and we can then bump poppler to 0.74.0 (and rebuild texlive-bin).

**Pull request merged**
